### ISSUE TITLE
Missing method exception.

### ISSUE THREAD

**Issue by endelicious** [quisquous/cactbot#100]
10/04/2018 2:45:15 PM: Error: RB: Update: System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at Cactbot.CactbotOverlay.Initialize()
   at Cactbot.CactbotOverlay.Update()
   at RainbowMage.OverlayPlugin.OverlayBase`1.<InitializeTimer>b__10(Object o, ElapsedEventArgs e)
 Error every time i tried to run it.

**Comment by danakj** [comment]
Did you install .NET Framework version 4.6 or above?

**Comment by endelicious** [comment]
yes still the same problem

**Comment by quisquous** [comment]
I've never seen this error before, and everything on the internet suggests that it's not having the right version of the .net framework.

Can you verify the version you're using and let me know what value Release is from here? https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#to-find-net-framework-versions-by-viewing-the-registry-net-framework-45-and-later

**Comment by endelicious** [comment]
Ok it's working now. I install the wrong net frame work package. Thx for the support!
