### ISSUE TITLE
Cactbot Raidboss Timers keep running

### ISSUE THREAD

**Issue by mizeryschild** [quisquous/cactbot#1001]
I did the test at Summerford to test whether my recent reinstall of ACT and all of my plugins went smoothly.  The /countdown command does not start the test.  It does start with /bow.  While the test runs, there is an encounter timer that keeps ticking up.  It's a part of the cactbot raidboss overlay because if I click to unlock it, it moves around with that module.  When the encounter ends, the timer keeps ticking until I close ACT.  How can i get this to stop?

![image](https://user-images.githubusercontent.com/60420999/73333251-d0f70580-422e-11ea-9488-717a6dd72b86.png)

**Comment by mizeryschild** [comment]
I have confirmed this counter also remains on screen during other fights as well.  I have no idea how to turn it off or what fields in the settings controls it.

**Comment by quisquous** [comment]
Unclick enable debug mode under raidboss.  If you don't see debug mode, click show developer options, then unclick it.

**Comment by mizeryschild** [comment]
> 
> 
> Unclick enable debug mode under raidboss. If you don't see debug mode, click show developer options, then unclick it.

I've tried this.  It did not resolve the issue.

**Comment by mizeryschild** [comment]
Thank you this resolved the issue.
