### ISSUE TITLE
How do I use Raidbossemulator?

### ISSUE THREAD

**Issue by dencur** [quisquous/cactbot#1002]
Simple question I hope,

Is there any documentation on how to use raidbosssimulator?  I'm wanting to replay a log and watch outputs from Raidboss (including timeline and text alerts on screen).  

How do I use it  / load a file?  Thank you!

**Comment by ngld** [comment]
Make sure the game is running and that you've added the overlay.
Then, import a log through ACT, select an encounter in the overlay and hit Play.

**Comment by quisquous** [comment]
Did you have more questions here past what ngld suggested?

**Comment by dencur** [comment]
No more questions!  This helped a lot.  Sorry for not replying,  Closing ticket :).
