### ISSUE TITLE
load error see image - any help would be appreciated

### ISSUE THREAD

**Issue by Lleonharte** [quisquous/cactbot#1003]
![2027008dc991be17acee5b2be433ac11](https://user-images.githubusercontent.com/58599924/73391195-34625f80-4323-11ea-8566-6d74ec91003c.png)

load error see image - any help would be appreciated 

ive been using cactbot for ages dont know why this is happening now and ive removed it and replaced it trying to fix it. this error only shows when i browse and add cactbotoverlay.dll

**Comment by ngld** [comment]
Your OverlayPlugin is too old.
Check the following links for more info:
* https://github.com/quisquous/cactbot#dependencies
* https://github.com/quisquous/cactbot/releases/tag/v0.13.0
* https://github.com/quisquous/cactbot/issues/988

**Comment by Lleonharte** [comment]
eh i did change to that lol how did this happen ty
