### ISSUE TITLE
MIN/BTN timed nodes timeline

### ISSUE THREAD

**Issue by ghost** [quisquous/cactbot#1005]
## Summary

Having a decreasing bar w/timer showing you time remaining before a legendary or ephemeral node expires in current zone would be awesome. Maybe even showing it when your current job is DoL. Right now I'm forced to alt+tab or switch virtual desktop to check the node timer on garland's bell but actually having a reference on screen would save time especially when planning GP management for ephemeral nodes.

**Comment by quisquous** [comment]
I think using https://github.com/Ottermandias/GatherBuddy from xlplugin might be a better answer then another cactbot overlay.
