### ISSUE TITLE
Is this "FFXIV_ACT_Plugin.Common" right?

### ISSUE THREAD

**Issue by Jaehyuk-Lee** [quisquous/cactbot#1015]
## Question

What would you like to ask?
![K-001](https://user-images.githubusercontent.com/4695371/73851633-29528680-4871-11ea-9ba7-f4f48df2a013.png)

I've put `Advanced Combat Tracker.exe` and `FFXIV_ACT_Plugin.dll` on `cactbot\plugin\ThirdParty\ACT`
but it seems Visual Studio can't find `FFXIV_ACT_Plugin.Common`.

it says: `이 참조를 확인할 수 없습니다. "FFXIV_ACT_Plugin.Common" 어셈블리를 찾을 수 없습니다. 어셈블리가 디스크에 있는지 확인하세요. 해당 코드에 이 참조가 필요한 경우 컴파일 오류가 발생할 수 있습니다.`
translating important part: `Could not find 'FFXIV_ACT_Plugin.Common' assembly. Check if assembly is stored on disk.`

![K-002](https://user-images.githubusercontent.com/4695371/73852072-e8a73d00-4871-11ea-9ffb-f0da3d964ccd.png)

**Comment by ngld** [comment]
You have to put `FFXIV_ACT_Plugin.Common.dll` from the plugin SDK and in `ThirdParty\ACT\SDK`:
https://github.com/quisquous/cactbot/blob/edb92e1cf4c408f3ef3882fd2f79834ac8097c87/plugin/CactbotEventSource/CactbotEventSource.csproj#L60-L62

**Comment by Jaehyuk-Lee** [comment]
@ngld Ah, thanks! I'll apply those description on dummy.txt file #1016
