### ISSUE TITLE
Resize handle

### ISSUE THREAD

**Issue by AVBoy** [quisquous/cactbot#102]
Hi there,

I'm a beginner at this, so bare with me...

I'm using the rdmty skin for the dps overlay, and I cannot find the resize handle for it. I can see the .html file points to the resize_handle.js file, but its like its not pointing to the correct location. Is something commented that should not be? How do we make this visible?

**Comment by danakj** [comment]
When you uncheck the box to lock the overlay in place, the background of it turns blue and the resize handle appears.

**Comment by AVBoy** [comment]
This does not give the expected results:
![capture](https://user-images.githubusercontent.com/2094364/38780771-7cc70d10-40d3-11e8-926e-07d39e4ae29b.PNG)

**Comment by quisquous** [comment]
Looks like this was a bug.  There was an extra ../ in the path to resize_handle.js.  It will be fixed in the next release, or you set the rdmty url to use https://quisquous.github.io/cactbot/ui/dps/rdmty/dps.html in the meantime instead.

**Comment by AVBoy** [comment]
Okay, if this is not the appropriate place to ask this question, where should I pose it please?

**Comment by AVBoy** [comment]
Wonderful, thank you!
