### ISSUE TITLE
Update "problems"

### ISSUE THREAD

**Issue by Seferex** [quisquous/cactbot#1028]
Hello, is it possible to avoid that the update replace the CSS/JS files (in my case, i need to keep: raidboss.js, raidboss.css and lippe.css)? Or at least give the option to keep the old CSS files or not.
Cause i (and i guess other people too) have their personal CSS with customized postions and for every update i have to replace the new files with my old files.

I love the new update anyway! So much better than before, thank you a lot for this!

P.S. If its already possible to do that and i missed it, i am sorry!

**Comment by quisquous** [comment]
Take a look at https://github.com/quisquous/cactbot/blob/master/docs/AdvancedCactbot.md#user-folder-config-overrides

You should put your modifications in files inside your cactbot user folder if you don't want them to be overwritten.

**Comment by Seferex** [comment]
oh thank you a lot for the quick reply! And sorry if i missed that part!

**Comment by quisquous** [comment]
No worries at all! I think it's not that obvious and a lot of people painfully do what you were doing as every version overwrites their changes.

**Comment by Seferex** [comment]
Sorry if i open again T_T

How to deal with edits that i made in the \cactbot\ui\raidboss\skins\lippe css?

**Comment by Seferex** [comment]
Sorry if i open again T_T

How to deal with edits that i made in the \cactbot\ui\raidboss\skins\lippe css?

I just have to copy the lippe.css in the user folder? Will it be recognized?

**Comment by quisquous** [comment]
I think it depends on the edits you made.  You should be able to copy the css from that file into your user/raidboss.css file and have it apply on top of the original lippe.css.

**Comment by Seferex** [comment]
hmmm the only thing i wish to do is to increase the font size of .info-text from 140% to 240%... But if i edit the value on the raidboss.css, it will not reflect if using the skin (cause it seems that the skin's css control the font size over the raidboss css).

How could i fix it?

Thank you and sorry again for this... I know its something very minor and kinda a waste of time for you ^^"

**Comment by quisquous** [comment]
No worries!

It works just fine if I create `user\raidboss.css` and insert the following text:
```
.info-text {
  font-size: 240%;
}
```

It works with and without the lippe skin enabled.

**Comment by Seferex** [comment]
Oh? Ok that is pretty weird for me ahaha cause back in the time (about 1 year ago) it did take a lot for me to figure out that i had to edit the lippe CSS in order to increase the size.

Thank you a lot! I will test it asap (i plan to sub again today) and i'll let you know! Thanks again for your time!

**Comment by quisquous** [comment]
Well, `lippe.css` applies after `ui/raidboss.css`, so if you edited the ui files it would get overwritten.  However, `user/raidboss.css` applies after everything.

**Comment by Seferex** [comment]
I understood! It works like a charm now!

You rock man ^^ Thank you really a lot for all the time you spent for me!

**Comment by quisquous** [comment]
Happy to help!
