### ISSUE TITLE
How to translate cactbot's title bar to other language？

### ISSUE THREAD

**Issue by ShadyWhite** [quisquous/cactbot#1029]
https://github.com/ngld/OverlayPlugin/pull/100#issuecomment-583803275
In order to make the interface more concise and convenient for users in other languages.NGLD and I want to modify the title bar in OverlayPlugin's interface like the link on the top.But I don't know how to translate cactbot's title bar to other language.Need your help,thanks a lot.

**Comment by quisquous** [comment]
Thanks.  I commented on the linked issue.

**Comment by quisquous** [comment]
I think this is solved at this point? Or, are there other changes you would like on the cactbot side?
