### ISSUE TITLE
Common replacement - Better replace "will be sealed off" things in one code

### ISSUE THREAD

**Issue by Jaehyuk-Lee** [quisquous/cactbot#1032]
## Summary

Brief explanation of the feature you'd like to request.

https://github.com/quisquous/cactbot/blob/e524fe8b9dafa6256feaa1094a480028889baf92/ui/raidboss/timeline.js#L41-L67

I think common replacement things needs to be gather in `common.js` or something and make it replace after `GetReplacedSync` function. like, `GetReplacedCommon` executes after`GetReplacedSync`,  `GetReplacedText` happens.

`':([0-9]{4}):(.*) will be sealed off': ':$1:15초 후에 $2(이|가) 봉쇄됩니다\.',`
This needs to be in every `[areaName].js` file which contains "will be sealed off" things now.
This makes code maintenance complicated.
I think making `replaceCommon` will make better translating timelines.

or merge `replaceCommon` with `replaceSync` before using `replaceSync` object to replace timelines

## Example
```javascript
const replaceCommon = {
  ':([0-9]{4}):(.*) will be sealed off': {
    de: ':$1:Noch 15 Sekunden bis sich der Zugang zu $2 schließt',
    fr: ':$1:Fermeture $2 dans',
    ja: '$1:$2の封鎖まであと',
    ko: ':$1:15초 후에 $2(이|가) 봉쇄됩니다',
  },
  'is no longer sealed': {
    de: 'öffnet sich erneut',
    fr: 'Ouverture ',
    ja: 'の封鎖が解かれた',
    ko: '의 봉쇄가 해제되었습니다',
  },
}
```

Something like this

## Some problem with `is no longer sealed`
Some timeline has specific area names in front of `is no longer sealed`. like,
https://github.com/quisquous/cactbot/blob/e524fe8b9dafa6256feaa1094a480028889baf92/ui/raidboss/data/02-arr/raid/t5.txt#L11
Actually, there is no need to specify the area name, but it just did. This makes example code I wrote above does not change correctly because of space-bar differences by languages. Especially, Japanese(does not use spacebar between words) and Korean(has postpositional particle).
Usually, it's like,
https://github.com/quisquous/cactbot/blob/e524fe8b9dafa6256feaa1094a480028889baf92/ui/raidboss/data/05-shb/dungeon/akadaemia_anyder.txt#L6
So, this does not differ by spacebar usage. 

### Example
"**바하무트의 오른손** is no longer sealed" should be "**바하무트의 오른손**의 봉쇄가 해제되었습니다" (bold font is area name)
So, we need to remove spacebar between area specified names and "is" on Korean translation.
But, 
".*is no longer sealed" → ".*의 봉쇄가 해제되었습니다"
does not need to remove spacebar.

### Solution
I think just not writing specific area name in front of `is no longer sealed` is better.
Like, change `00:0839:The Right Hand of Bahamut is no longer sealed` to `00:0839:.*is no longer sealed`

`is no longer sealed` is only used when resetting timeline sync. So, it does not need specific area names.

**Comment by quisquous** [comment]
This is a really good idea.

> I think common replacement things needs to be gather in `common.js` or something and make it replace after `GetReplacedSync` function. like, `GetReplacedCommon` executes after`GetReplacedSync`, `GetReplacedText` happens.

I'm not sure the right place to put this.  Probably this could just live in `popup-text.js` as well?  It seems fairly raidboss-specific.

I think there are a number of other "common" translations that could definitely be added there, like all the ones added from `translate_fight.py`: https://github.com/quisquous/cactbot/blob/master/util/translate_fight.py#L54-L76

I'm not sure what you think, but I wonder if it would be good to separate out common texts from common syncs separately? This would help with collisions in #1008.

I think the other addition to this is that I want the tests in #1008 to take this common replacement into account when figuring out what needs translations and what does not.

> Some timeline has specific area names in front of `is no longer sealed`. like,

Yes, agreed that these can all be changed to `00:0839:.*is no longer sealed`.  Having to remove a space is also pretty awkward.

Are there any cases that need the specific zone with "is no longer sealed"? I am having a hard time thinking of any, so hopefully there are not.

**Comment by Jaehyuk-Lee** [comment]
#1049 is dealing with this.
