### ISSUE TITLE
Cactbot test Can't check for ACT and game

### ISSUE THREAD

**Issue by KsRuri** [quisquous/cactbot#1051]
Sorry, I am not good at English, so I am using a translator.
Uh... um... It may not be a perfect translation, but... I'm writing in the hope that the viewer can understand...

I'll get to the point.
I've been trying to use Cactbot for two months, but I can't. It seems to be working at exactly 5%... because some of the plugin's functions are minimal.
When i using the cactbot's test, currentZone- hp, mp- id, name, job, pos... This part is normally marked. maybe...
but, Other part not work.
I think is the most problematic, using the cactbot's test, All the time (inCombat: act: no game: no) <- this marked as. but, I'm sure playing ACT and games.
ACT Program and various overlays have always been kept up to date, and other ACT plugins are functioning normally.
so... Is there anyone who is going through the same bug as me? If anyone solved the same bug, could you tell me how? I can't figure out where it started by myself...
![test](https://user-images.githubusercontent.com/61147337/74655353-90f0c600-51cf-11ea-9a59-bbf20f856b10.jpg)

**Comment by KattTails** [comment]
Hiya! 

That line `inCombat: act: no game: no` is reporting whether ACT and/or the game have the in-combat flag set, aka whether you're in a fight.
It doesn't mean it can't find ACT or the game, and if everything else is correct (which it seems to be!) it means everything is working as normal. 😄

**Comment by KsRuri** [comment]
Oh, my God, I didn't know it was this simple...
I've checked the combat test to make sure it's working properly.
But if everything is normal, I don't know why Jobs and Raidboss aren't working... I'll look for this myself. Thanks for letting me know!
