### ISSUE TITLE
Cactbot v0.16.0 is not working with CN Server.

### ISSUE THREAD

**Issue by ShadyWhite** [quisquous/cactbot#1057]

**Comment by Jaehyuk-Lee** [comment]
This will be the same problem as Korean had. #1054

**Comment by Jaehyuk-Lee** [comment]
This is fixed with this commit https://github.com/quisquous/cactbot/commit/4d09caa51c4012650bcb1471e2cf988df93d8e34 .

**Comment by quisquous** [comment]
Sorry again about this.  I thought for sure I had reverted those back, and either I committed wrong or did some last minute copy and paste wrong and so they ended up unchanged.  Sorry, it's been a long week.  Thanks for the pull request and the fast issue filing
