### ISSUE TITLE
Eureka Module Problem

### ISSUE THREAD

**Issue by InverseRain** [quisquous/cactbot#106]
When I activate the Eureka module, all I get is a blue box with the map in it. No text or anything else. When I lock the overlay, it simply vanishes. Links in the chat seem to do nothing. I do, however, hear a beep when I'm in the instance and an NM spawns, so it's doing _something_. Any suggestions?

![image](https://user-images.githubusercontent.com/38582585/39082751-ffc5f66c-450c-11e8-91c6-8dd62f821e8b.png)

**Comment by quisquous** [comment]
The beep when an NM spawns is coming from raidboss and not from eureka, so that unfortunately isn't telling you anything.

What version of the FFXIV plugin are you on? Older versions didn't name the zone correctly.  Can you let me know what cactbot thinks it is using? It prints this info out in the plugin log on startup.

Are there any errors in the plugin log?

**Comment by quisquous** [comment]
Hmm! Well, 1.7.0.5 is the latest release: https://github.com/ravahn/FFXIV_ACT_Plugin/releases.  So, I guess that theory isn't correct.

Just to double check with you.  Unlocked overlays just displaying a blue map is behaving correctly.  Locked overlays displaying nothing outside of Eureka is also correct.  When you zone into Eureka with a locked overlay (or if you lock/unlock/restart there), the map with labels should appear.  You've definitely locked it while in Eureka?

And there's no plugin errors in the log after you've zoned into Eureka?

**Comment by InverseRain** [comment]
Locking it makes it disappear, yes. I think I didn't try running ACT before I was in there, though I did try restarting while in there several times and got just the blue map. I didn't notice any errors (but I didn't think to look for them either.) I'll check again and see what happens.

**Comment by InverseRain** [comment]
Okay, I just zoned in with the app running, and I got this error:

`4/21/2018 10:06:07 AM: Info: Eureka: BrowserConsole: Uncaught ReferenceError: WeatherFinder is not defined (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/cactbot/ui/eureka/eureka.js, Line: 312)
`
That appears to be the only error.

**Comment by quisquous** [comment]
Aha! Are you loading eureka.html directly from your local hard drive (vs remote github.io pages)? If so, then you need to copy https://github.com/quisquous/cactbot/blob/master/resources/weather.js into your resources folder.

**Comment by InverseRain** [comment]
Hmm, that's really weird. I downloaded it from here and copied it directly into there and I couldn't find that file anywhere; I had to create it just now. It seems to work now, thank you!

I wonder if I'm missing any other files...

**Comment by InverseRain** [comment]
Is it supposed to pull from the tracker to update all the NMs that are down, by the way? The tracker code is appearing on the window, but only a couple NMs are showing up as on cooldown.

**Comment by quisquous** [comment]
Ok, good! I haven't done a cactbot release with eureka yet, so maybe something got messed up when you copied files.  :)

At the moment, it's not pulling from the tracker.  If you paste the NMs on cooldown info into an /echo, it'll update.  But you only need to do that once, and then it'll update from mobs you see die from then on out.
