### ISSUE TITLE
Sound and voice alert not working

### ISSUE THREAD

**Issue by wtyanan** [quisquous/cactbot#1065]
## Description

Re-installed a fresh cactbot from "get plugin" feature, enabled TTS and alerts, but no sound/voice is playing

## Additional information

![image](https://user-images.githubusercontent.com/26291460/75102117-8611a900-55b4-11ea-9e46-3ee07161e2b7.png)

**Comment by wtyanan** [comment]
Timeline is working fine

**Comment by Jaehyuk-Lee** [comment]
TTS is only supported on triggers, have you seen trigger texts on your screen? Maybe you're seeing timeline only.

**Comment by quisquous** [comment]
Which triggers are not working?

**Comment by wtyanan** [comment]
I was testing on the dummy, it used to callout stuff, did the testing triggers got deleted?

**Comment by TeddyHugs** [comment]
E6S Triggers aren't added just yet!

**Comment by wtyanan** [comment]
> E6S Triggers aren't added just yet! The timeline works though!

I was testing in Summerford Farms

**Comment by quisquous** [comment]
Sorry for the extremely belated response here.  Is this still happening?  The testing triggers did not get deleted, for what it's worth.

Have you tried testing in something like unsynced Titan Extreme?

**Comment by quisquous** [comment]
Hi, is still this happening?

**Comment by wtyanan** [comment]
I didn't test it, will try it out when I get time, thx

**Comment by quisquous** [comment]
I'm going through and closing old issues.  If this is still happening, please respond here or open another issue.  Another option is to ask in the [#troubleshooting channel](https://github.com/quisquous/cactbot/blob/master/docs/FAQ-Troubleshooting.md#places-to-get-help).
