### ISSUE TITLE
Text alerts not working on new fights

### ISSUE THREAD

**Issue by TokisakiKuromi** [quisquous/cactbot#1066]
## Description

Going into a e6n fight had no timeline/text alerts show up.
Went into t1n and everything works as intended.
ACT was open prior to zoning in with the new plugin update as well as cactbot 0.16.2 and the latest update of the overlay plugin.

**Comment by Jaehyuk-Lee** [comment]
There is no data for e6n.
https://github.com/quisquous/cactbot/blob/master/ui/raidboss/data/05-shb/raid/e6n.txt
It's empty.

0.16.2 supports only e6s and e7s
https://github.com/quisquous/cactbot/releases/tag/v0.16.2

**Comment by quisquous** [comment]
There are no text alerts on the the new fights yet.  Patches welcome!
