### ISSUE TITLE
Fisher Plugin doesnt work

### ISSUE THREAD

**Issue by SufferMyDear** [quisquous/cactbot#1067]
Hey Guys

My Cactbot Fisher plugin doesnt work atm. Everything else just works fine.

but its not even listed in the  overlayplugin.dll section of my ACT Cactbot.

Is it just me or doesnt it work for u guys too ?

Help would be nice

**Comment by Akurosia** [comment]
At least for me and a friend (both game languages in german) fishing overlay worked like a charm (at least tested on tempest fishing spots)

**Comment by SufferMyDear** [comment]
Hum i dont get why its the only plugin in which doesnt work for me ...

**Comment by SufferMyDear** [comment]
can u maybe show me ur config or screenshots?

**Comment by SufferMyDear** [comment]
ok i tried everything i know including the troubleshoot tips

https://github.com/quisquous/cactbot/blob/master/docs/FAQ-Troubleshooting.md#fisher-module

i mean the overlay load but its like it cant read that im fishing for somehow.....

**Comment by SufferMyDear** [comment]
ok can be closed it needed the 2.5.0.2 patch with the beta one it didnt work

**Comment by quisquous** [comment]
Glad you got it sorted! Thanks for the followup.
