### ISSUE TITLE
E6S.txt timeline remove leftover copy and paste code

### ISSUE THREAD

**Issue by BeIeriand** [quisquous/cactbot#1068]
## Description

leftover copy and paste code

https://github.com/quisquous/cactbot/blob/66394dc421d790c124237c9a2a8f3d9522491126/ui/raidboss/data/05-shb/raid/e6s.txt#L128-L130

**Comment by quisquous** [comment]
@Legends0 Do you know what this should be?

**Comment by BeIeriand** [comment]
They are copy's from line 106,122 and 123 and probably were forgotten there so they can be removed

**Comment by Legends0** [comment]
Fixed in PR #1073. The lines were a leftover when adjusting the times as FFLogs had separate fights.
