### ISSUE TITLE
DirectX9 Error

### ISSUE THREAD

**Issue by Woojoe** [quisquous/cactbot#107]
When running ACT i'm getting an error telling me that DirectX9 FFXIV process exists. However, I have DirectX11 on my PC. How is this possible? Any help would be appreciated.

<img width="543" alt="directx issue" src="https://user-images.githubusercontent.com/38595943/39090227-21ccc32c-45a7-11e8-9707-03ff47821b39.PNG">

<img width="337" alt="directx version" src="https://user-images.githubusercontent.com/38595943/39090228-243c90e2-45a7-11e8-9e28-33e172d3858d.PNG">

**Comment by quisquous** [comment]
You need to run ffxiv in dx11 mode.  It's a configuration option in the ffxiv launcher.

**Comment by Woojoe** [comment]
Thank You. That got it

**Comment by quisquous** [comment]
Awesome.  Glad you got it sorted!
