### ISSUE TITLE
Early pull not working for Oopsy module

### ISSUE THREAD

**Issue by Tink-ScottJacobs** [quisquous/cactbot#1070]
## Description

Early pull is not working for the Oopsy module. Deaths and failures seems to be fine though.

## Additional information

https://streamable.com/m3d5l
https://streamable.com/ujlo4

**Comment by williamfmarinho** [comment]
Same here!

**Comment by ngld** [comment]
Looks like the config UI for Oopsyraidsy doesn't apply the settings properly.
`this.options.MinimumTimeForPullMistake` is `undefined` which effectively disabled the trigger.
I'll investigate further when I have more time.
