### ISSUE TITLE
Set cactbot config shown language to PC's locale.

### ISSUE THREAD

**Issue by Jaehyuk-Lee** [quisquous/cactbot#1074]
## Summary

Brief explanation of the feature you'd like to request.

Like this, shown language is not determined by FFXIV parsing plugin's language, I think this is based on PC's locale setting.
![K-001](https://user-images.githubusercontent.com/4695371/75117786-f523f600-56b7-11ea-94bc-a96745126447.png)

cactbot is in English (FFXIV parsing plugin's language)
![K-002](https://user-images.githubusercontent.com/4695371/75117794-0d941080-56b8-11ea-906f-e80447c59b93.png)

I think cactbot can determine in which language user is using their PC.
I don't know how though.

Also, I've tried to match config's language setting to `Alert Language`'s language setting. 
Example,
If `Use FFXIV Plugin Language` - follow FFXIV Plugin's language
If `English` - fix to English whatever user's PC language is.

But... I couldn't do that.

**Comment by Jaehyuk-Lee** [comment]
`navigator.language.substr(0,2)` is not working well with Cactbot config javascript.
It works on real browser though.

**Comment by quisquous** [comment]
Another option (pun not intended) is to add an option for language to show the config page in?

**Comment by quisquous** [comment]
Actually, a better solution would be that if OverlayPlugin has this information, then OverlayPlugin could send it along with the ffxiv plugin language, and then config page could use that.
