### ISSUE TITLE
Fishing Addon - Ocean Fishing

### ISSUE THREAD

**Issue by Tataru-Taru** [quisquous/cactbot#1075]
Now that the ACT plugin has been updated, is there any plans to extend the fishing cast timer to ocean fishing?

Currently doesn't seem to detecting ocean fish, but I assume it needs data added for location?

**Comment by quisquous** [comment]
Unfortunately, the fishing module is my lowest priority.  Patches are very welcome from anybody who is interested and wants to dig in, but there's many weeks worth of things to do before I (individually) could even think about it.

**Comment by AdriaanDeVos** [comment]
Ocean fishing zones and fishes are added.

However there are a few bugs. Should I file a new issue or should we track status here?
Ocean Fishing bugs:
1. Not updating current fishing zone when spectrals enable/disable
2. Sometimes not updating current fishing zone when moving to a new zone

**Comment by quisquous** [comment]
Maybe track status here, until it gets too unwieldy?

**Comment by AdriaanDeVos** [comment]
this.ui.setPlace is only called when discovering a undiscovered fishing hole, or when there is no place present.

Ocean fishing allows the player to change place/zone without stopping fishing, so this method should add a check that will update the place on every handleCast(place) if the current place is different than the saved place.
https://github.com/quisquous/cactbot/blob/55cfe0c40a9deef11c5a7929bd760fcc3b4a4cd2/ui/fisher/fisher.js#L233

**Comment by AdriaanDeVos** [comment]
Would it be possible to have an event that shows when the fish bite (with !/!!/!!! markers above player head) instead of when the player presses the "hook" button?

https://github.com/quisquous/cactbot/blob/55cfe0c40a9deef11c5a7929bd760fcc3b4a4cd2/ui/fisher/fisher.js#L249-L250

**Comment by quisquous** [comment]
@AdriaanDeVos Yes.  These are probably `1B:` headmarker lines (or lines starting with `27|`) in the Network log.  If you can find them, we can replace the regex for hook.  https://github.com/quisquous/cactbot/blob/master/docs/LogGuide.md
