### ISSUE TITLE
Text and TTS not behaving as expected

### ISSUE THREAD

**Issue by kevv2** [quisquous/cactbot#1076]
I just re-installed cactbot fresh from previously using either v 10 or 11, previously i was using manual re-configuration to disable Sounds alert (Dings, Boings, etc) But with the new config system, even on "Text and TTS", Sound alerts still play and triggers that used to be said out loud in TTS (i.e. Suzaku "Get In" "Move Out", will play their Sound instead. It didn't use to be a requirement for triggers to have a "TTS" override and it could just call out the Alert Text as TTS.

Is this an intended change that Sound still plays even when not enabled/ TTS requires the TTS Tag?

**Comment by kevv2** [comment]
I found the root of the issue, any trigger with a TTS tag, but none for your current language will default back to sound. Some triggers have had Japanese/German TTS entries but none for EN, so those stopped triggering default TTS values

**Comment by quisquous** [comment]
Do you have examples of where this is happening? I'll try to track these down, but pointers would also help.

**Comment by kevv2** [comment]
Suzaku EX was the very noticeable one, but i'm sure i heard the same issue before while doing some other fights. I'll take a look when i have time to see any other triggers where this could be an issue

**Comment by quisquous** [comment]
Ok, looks like this got fixed in Suzaku, at least.
