### ISSUE TITLE
Cactbot WebSocket not working in Firefox

### ISSUE THREAD

**Issue by valarnin** [quisquous/cactbot#1078]
## Description

Cactbot over Web Socket only works on Chrome browsers (e.g. doesn't work in Firefox). Same URL works fine from a Chromium-based browser. (doesn't workin IE11 or pre-Chromium Edge, but I don't think those are worth fixing).

## Additional information

Errors in console:

```
Connected! common.js:160:17
TypeError: window.getComputedStyle(...).borderWidth.match(...) is null timeline.js:629:83
TypeError: gTimelineController is undefined raidboss.js:73:5
TypeError: gTimelineController is undefined 57 raidboss.js:29:5
    <anonymous> http://192.168.1.111:38080/Cactbot/ui/raidboss/raidboss.js:29
    processEvent http://192.168.1.111:38080/Cactbot/resources/common.js:236
    connectWs http://192.168.1.111:38080/Cactbot/resources/common.js:186
```

**Comment by quisquous** [comment]
This is unlikely something that I'm going to fix, sorry.  My feeling is that cactbot will work in the version of Chrome used by CEF in the latest OverlayPlugin as a first priority, and if there's a second priority it's to make sure it works in Chrome's latest version.  You're welcome to submit pull requests if making things compatible is not too intrusive, but new features are not going to be tested to make sure they work.

**Comment by valarnin** [comment]
Perfectly understandable. I'll see what's required to get it working for Firefox and if it's just adjustments to getComputedStyle (null checks maybe?) I'll make them and submit a PR. Going to leave this issue open until I get a chance to investigate.

**Comment by valarnin** [comment]
Looked at it and it's an issue with `borderWidth` vs `borderLeftWidth`/etc. The former is a shorthand property and per the standard isn't supported as part of `getComputedStyle`, only Chrome has support for it. But adjusting that (to `borderLeftWidth`) just revealed a bunch of regex issues with triggers and that's not going to be a non-intrusive change. I might take another look at this down the line sometime but for now it's not feasible.

**Comment by quisquous** [comment]
Thanks for the investigation!
