### ISSUE TITLE
Feature request Eureka Fairy location on Map.

### ISSUE THREAD

**Issue by Pirate144** [quisquous/cactbot#109]
Not sure if possible, but I imagine that ACT does track the location of NPCs when they spawn, if so would it be possible to add like a green dot on the eureka map when it detects one nearby? I know the trigger for them like hunt mobs is "03:Added new combatant Anemos Elemental.".

In fact is that is possible it would probably be possible to overhaul the Eureka module into a hunt module as well.

**Comment by quisquous** [comment]
I can't think of a way to do this very well.  The "added new combatant" doesn't have a position, so it's pretty murky where one is.  You could add a raidboss trigger that alerts you when one is near.

**Comment by Pirate144** [comment]
I already have a trigger for fairys being nearby like hunt mobs. 

I see that the added new combatant log makes no mention of their location, if so then how does FFlogs replay feature show where the boss/adds are at?

**Comment by quisquous** [comment]
It's only ability usage that has positions.  I guess we could detect the fairy using its aoe maybe, and that could have a position attached to it.

**Comment by haasn** [comment]
@Pirate144 I'm lazy, mind copy/pasting me your fairy trigger?

**Comment by haasn** [comment]
Made my own

```javascript
Options.Triggers = [
  {
    zoneRegex: /Eureka/,
    triggers: [
      {
        regex: /Added new combatant (Anemos|Pagos|Pyros|Hydatos) Elemental/,
        infoText: 'Fairy nearby',
      },
    ],
   },
]
```

**Comment by haasn** [comment]
I gave implementing this a try after seeing that ACT now added x/y/z coordinates to the 'added new combatant' log lines, but those seem to live in a completely different reference system compared to the map links, so I don't know how of any easy way to 'project' this onto the minimap.

I guess I could measure the x/y/z position at each corner of the map and then translate that to the map coordinates for each map, but I was wondering if there's an easier way I'm missing?

**Comment by quisquous** [comment]
https://github.com/quisquous/cactbot/blob/master/ui/eureka/eureka.js#L1736 This function will do that for you.  The AddFlag function takes things in map coordinates, but you could make an AddFairy function that converts the coordinates like SetStyleFromEntity does and then call AddFlag?

**Comment by haasn** [comment]
Haha, I just found that function myself, *after* having actually gone through and measured these constants out myself.

(I did add an AddFairy function but since I was too lazy to do any actual UI stuff I just made it call AddFlag, hence why I was needing to translate between the two)

**Comment by quisquous** [comment]
Thanks for this fix!
