### ISSUE TITLE
Turn off sound isnt working anymore?

### ISSUE THREAD

**Issue by magnetic101** [quisquous/cactbot#1095]
I used to go in the raidboss file and just set sounds to false to remove the buzz sound when mechanics go off but ever since the new update that does not stop the noise anymore. How do i turn off the noise?

**Comment by kevv2** [comment]
#1076

**Comment by ngld** [comment]
The `raidboss.js` in your `user` folder should work just like before. That said, you can turn off sounds through the settings screen (Plugins > OverlayPlugin > Cactbot). Please don't edit any files in the `ui` folder unless you know exactly what you're doing.

**Comment by TeddyBearsG** [comment]
commenting cause its similiar to op, im looking to lower sound of alerts. under the assumption its in the same place as turning it off. i went to Plugins > Overlayplugin.dll > cactbot but its just a black screen. how do i go about fixing this, did i do something or is this a bug?

**Comment by quisquous** [comment]
Do you have any errors in your overlayplugin log? Does it say something like can't detect the cactbot directory? This sounds very similar to #1158.

**Comment by quisquous** [comment]
I'm going through and cleaning out old issues.  If this is still happening, please respond here or open another issue.
