### ISSUE TITLE
Provide timeline Text-to-speech

### ISSUE THREAD

**Issue by danakj** [quisquous/cactbot#11]
1. Add Javascript API for Text-to-speech back to the C# plugin
2. Hook it up from timeline parsing
3. Also add a hook for triggers to do Text-to-speech like for text and/or sound

**Comment by danakj** [comment]
This is mostly done in the tts branch, there's a TODO in timeline.js about hooking up alertall sound/speach. But the popup-text.js has everything we need for it. Just need to add a method call across modules similar to alerttext/infotext etc in timelines.

**Comment by quisquous** [comment]
Fixed.
