### ISSUE TITLE
Eureka Module, gale and night time icons not appearing.

### ISSUE THREAD

**Issue by Pirate144** [quisquous/cactbot#110]
See title.

Being replaced by squares, font/language issues? Running windows 7 on JP local.

https://i.imgur.com/6SlhDRa.png

Edit: Appears the daytime icon is working fine. https://i.imgur.com/XB8KRLr.png

**Comment by IrealiTY** [comment]
What Windows version are you using?

**Comment by Pirate144** [comment]
Windows 7 Home Premium version 6.1 (Build 7601: service pack 1.)

**Comment by IrealiTY** [comment]
seems like a unicode issue

the unicode for those icons is:
```
var gGalesIcon = "&#x1F300;"
var gNightIcon = "&#x1F319;";
var gDayIcon = "&#x2600;";
```

Can you visit this site and see if you see a Icon in the middle (and / or) in the url itself? http://graphemica.com/%F0%9F%8C%80

url sould look like:
![image](https://user-images.githubusercontent.com/1223686/39334453-f8d44ef2-49ae-11e8-950c-a5977c354c5d.png)

and this symbol on the site:
![image](https://user-images.githubusercontent.com/1223686/39334464-020cbcc0-49af-11e8-9922-9fca61d916f3.png)


fact is though, that Win7 doesn't support the full range of unicode symbols ("emojis") and maybe a fall back font would be needed (like "[Symbola](http://users.teilar.gr/~g1951d/)")

**Comment by Pirate144** [comment]
https://i.imgur.com/tvnfWnJ.png

Works fine.

**Comment by quisquous** [comment]
Hmm.  I wonder if whatever font it's selecting on your system just doesn't have glyphs for those codepoints.  Does oopsyraidsy also not show its unicode?

I'll look into replacing them all with images.

**Comment by Pirate144** [comment]
Never really used oopsy much before other than to test it, but after messing with it, the unicode in it does not appear to be working either. The green sideways triangle for an early pull works, but the death skulls don't show up.

**Comment by quisquous** [comment]
If you go to Control Panel > Appearance and Personalization > Fonts, do you have the Segoe UI Symbol font? (e.g. https://www.wfonts.com/font/segoe-ui-symbol)

Alternatively, can you tell me what font your eureka is using? Go into eureka with the eureka overlay, and click "Show Devtools" and then find an element with one of those unicode characters and see what its computed style is, e.g. 
![image](https://user-images.githubusercontent.com/462317/39410527-70d422e6-4bae-11e8-8bde-4019e12a5f8c.png)

**Comment by Pirate144** [comment]
https://i.imgur.com/4Z4WNzy.png

I have Segore UI Symbol Regular, but not just Segore UI Symbol.

https://i.imgur.com/jvykdmi.png

**Comment by quisquous** [comment]
Out of curiosity, could you try installing the Segoe UI Symbol update? https://support.microsoft.com/en-us/help/2729094/an-update-for-the-segoe-ui-symbol-font-in-windows-7-and-in-windows-ser

It looks like they updated this at some point, and maybe your Windows update didn't pick it up?

**Comment by Pirate144** [comment]
Sure will do after maintenance.

**Comment by quisquous** [comment]
Ok, phew.  Glad that fixed it.  It's super convenient to be able to use emoji vs creating images for all of them, so I was just trying to avoid having to rewrite all of those when there's other things to fix.  Thanks for all the testing.  I'll add this to the documentation.
