### ISSUE TITLE
Partial translation

### ISSUE THREAD

**Issue by Bluefissure** [quisquous/cactbot#1101]
As said in the release note of [0.16.0](https://github.com/quisquous/cactbot/releases/tag/v0.16.0), the translations must be able to apply in any order and have the same result, which is not applicable to the real situation. 

Take the two actions `Radiant Sacrament`->`拜火圣礼` and `Sacrament`->`十字圣礼` for example, the suffix of one action may be completely another action, so the translation of the other action will become a collision.

What's more, if we want to translate `Fate: Obloquy, Solidarity and 3x Severity`, it's okay we need to translate all `Fate`, `Obloquy`, `Solidarity` and `Severity`, but what about the `and`? if we translate the `and` to `和` then the `Hand of Prayer` will be translated to `H和 of Prayer`.

**Comment by Akurosia** [comment]
`(?<= )and` will match the `and` in `Fate: Obloquy, Solidarity and 3x Severity` but not the `and` in `Hand`

**Comment by Bluefissure** [comment]
I decided to translate `Radiant` -> `拜火` and `Sacrament`->`圣礼` for a temparary resolve.
Thanks @Akurosia for the resolve of `and`.
