### ISSUE TITLE
Fishing Timer incorrect bait detection

### ISSUE THREAD

**Issue by AdriaanDeVos** [quisquous/cactbot#1125]
During Ocean Fishing, especially on zone changes, sometimes the change bait detection fails to work. I propose to use a similar solution as in: https://github.com/quisquous/cactbot/pull/1106

This means: Updating currently used bait on every cast instead of when the user changes bait.

**Comment by quisquous** [comment]
I'm going to mark this fixed, as per #1106.

**Comment by AdriaanDeVos** [comment]
This issue should not be closed as #1106 only addresses the fishing spot/place. It does not solve the issue that is described here, namely the **incorrect bait.**

**Comment by quisquous** [comment]
Not planning to make any more fishing changes.
