### ISSUE TITLE
CSS override doesn't seem to work with absolute positioning elements

### ISSUE THREAD

**Issue by rgwalke2** [quisquous/cactbot#1129]
Placing the following CSS in user/raidboss.css does not override the positioning of the targeted selector in the default raidboss file:

#timeline-container {
  position: absolute;
  bottom: 0px;
  right: 0px;
}

IE - bottom/right are being overridden by the top/left elements in the default selector. Might just be a consequence of CSS ordering, but I wasn't sure if the intent was for the specified selector to replace "timeline-container" or to be additive.

**Comment by ngld** [comment]
The user `.css` file is just added to the web page as it is. As such it works the same way every CSS file does: by combining different selectors.
You'll have to override the `top` and `left` properties if you want to move it elsewhere. You can just set them to `auto` if you want to move the element to the bottom-right corner.

**Comment by rgwalke2** [comment]
Thanks! That answers it. Appreciate the response and all the effort on the overlay.
