### ISSUE TITLE
Feature request or help pointer to where i can edit: Show both players marked by thunder in UCOB

### ISSUE THREAD

**Issue by elisoncampos** [quisquous/cactbot#113]
Maybe this could be a custom trigger, if so, any pointer where I can add this functionality? I want raidboss module to display which party members are being targeted by thunder during nael in UCOB.

Thanks in advance and what a greate addon.

**Comment by elisoncampos** [comment]
Thank you, gonna work on that and make a PR once it's stable. Who knows if this ends up being useful for someone as it'll be for me

**Comment by quisquous** [comment]
:+1: I'll look forward to the pull request!

**Comment by quisquous** [comment]
I don't think I'm going to get around to implementing this at this point.  If somebody sends a pull request, I'd be happy to merge it.
