### ISSUE TITLE
Raidboss not working right

### ISSUE THREAD

**Issue by Rawkingoreedge** [quisquous/cactbot#1147]
So I installed the new update, added an overlay for raidboss, if I have it unlocked , the blue box will show up, but the test in summerford doesnt work and its not working in fights either

**Comment by ngld** [comment]
How did you add the overlay? Did you use the Raidboss preset?

**Comment by Rawkingoreedge** [comment]
presets arent showing up for me for cactbot, so I did it with mini parse

**Comment by ngld** [comment]
If the presets aren't showing up, `CactbotOverlay.dll` isn't enabled and none of Cactbot's overlays will work. Make sure `CactbotOverlay.dll` appears immediately after OverlayPlugin in your plugins list and restart ACT. Remove the overlay and create it again using the Raidboss preset.

**Comment by Rawkingoreedge** [comment]
CacbotOverlay IS enabled and is right under overlayplugin and I still dont have the presets showing up

**Comment by ngld** [comment]
Did you restart ACT after enabling `CactbotOverlay.dll`?

**Comment by Rawkingoreedge** [comment]
yes

**Comment by ngld** [comment]
Can you check if there are any errors in the overlay log? That's the text area below the overlay settings.

**Comment by Rawkingoreedge** [comment]
like this? Error: LoadAddons: Cactbot.PluginLoader: System.IO.FileNotFoundException: Could not load file or assembly 'CactbotEventSource, Version=0.16.6.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

**Comment by ngld** [comment]
Remove Cactbot from your plugins list, remove all files you installed for Cactbot, click the `Get Plugins` button in ACT's Plugins tab, install Cactbot and restart ACT.

You messed something up. You're either missing a file or moved files you shouldn't move. By following the steps above, you're reinstalling Cactbot to fix that issue.

**Comment by Rawkingoreedge** [comment]
that did the trick, thanks
