### ISSUE TITLE
Automatic Cactbot updates fail

### ISSUE THREAD

**Issue by liaoarden** [quisquous/cactbot#1149]
## Description

Cactbot updates fail due to not being able to overwrite files.

## Additional information

Even when the plugin is disabled and retry is hit, the plugin does not update.

It seems like the DLL updates, but the actual plugin files do not. I've been able to get it to succeed before by disabling the plugin, hitting retry, and then renabling it, but that hasn't seemed to work the last two updates.

**Comment by quisquous** [comment]
Where is your plugin? It's possible that it's in a place that ACT can't update.  You might want to consider moving it into `%APPDATA%\Advanced Combat Tracker\Plugins`.

**Comment by liaoarden** [comment]
I thought that could be an issue, so I reinstalled it via the `Get Plugins` but encountered the same error.

Attached error screenshot.

![image](https://user-images.githubusercontent.com/2417229/76141980-db6ea100-601d-11ea-8947-12ab6103d3a3.png)

**Comment by quisquous** [comment]
The IOException in the log there looks like the problem.  Something else on your system has one of the files open.  I assume it's not you having that file open in some other program.  Do you have a virus scanner?

I would recommend following something from https://www.dariawan.com/tutorials/windows/how-know-which-process-using-file-or-folder-windows/ to figure out what has the aetherochemical_research_facility.js file open.

**Comment by liaoarden** [comment]
I do not have a virus scanner (other than the built-in microsoft one, which was not running at the time).

I'll downgrade and take another look.

**Comment by liaoarden** [comment]
Okay so after the 0.16.9 upgrade it did happen again.

But while I was downloading process explorer (since i forgot to last time), it seems that enough time passed that whatever had grabbed a handle on the old files decided to let go of them. I'll see if that happens again with a future update.

**Comment by liaoarden** [comment]
I'm just going to close this bug as WNF.

I can reproduce this pretty reliably, but using ProcessExplorer doesn't turn up any file handles and after letting a PE search fail and retrying a few times, it works. I don't see this issue updating the ACT FFXIV plugin nor the Overlay Plugin however, but those update much fewer files at once.

**Comment by quisquous** [comment]
Sorry about this.

I'll try to think of what can be done here, but I'm not sure there's any easy answers.  I'm surprised that copying files manually doesn't result in the same issue.
