### ISSUE TITLE
Cactbot timeline not working on fights were it should

### ISSUE THREAD

**Issue by M0deRa1n** [quisquous/cactbot#1151]
I tried to look for a fix myself, but wasn't able to, so decided to ask here.
A friend streamed for me some days ago, and I noticed he had the timeline for the Nier's raid, while I haven't.
I looked if I had to enable something, checked the files, even replaced mine with the ones he gave me, but doesn't seem to work.
Same thing appears to happen with Baldesion Arsenal too, where I don't even have the alerts.
So, wanted to ask, am I missing something?
A setting perhaps?
Or do I need to change a value in the files?
Cause I have no idea and the problem is driving me crazy

**Comment by quisquous** [comment]
Do other raids work for you? If you queue into Titan Extreme unsynced, does it work fine? What language are you using?

**Comment by M0deRa1n** [comment]
Sorry for late reply, I had other things going on and forgot to check.
Other raids seems to work fine. Last tier was working good and it is the new one.
Titan EX works fine too, both timeline and alerts.
I'm using English

**Comment by quisquous** [comment]
Baldesion Arsenal is a little bit weird compared to other raids, but it should work just fine, though.  Do you have zone seal/unseal messages turned off in your chat log?

Feel free to attach a link to a zipped Network log of an instance where it's not working and I can take a look.

**Comment by quisquous** [comment]
Is this still happening? Do you have a network log?

**Comment by quisquous** [comment]
Hi, I'm going to close this.  Feel free to attach a network log here and I can take a look and reopen this.
