### ISSUE TITLE
raidboss: `data` variable unavailable for user trigger options

### ISSUE THREAD

**Issue by CostasAK** [quisquous/cactbot#1157]
## Description

I can no longer use the `data` variable in my user triggers. For example, during E5S, when there is either a large or small knockback the text alert is correct, but the TTS I've set up through PerTriggerOptions is always 'small knockback'. See my PerTriggerOption here:
```javascript
Object.assign(Options.PerTriggerOptions, {
  'E5S Gallop': {
    SpeechAlert: true,
    TTSText: function (data) {
      if (!data.fury) {
        return 'Small knockback';
      } else if (data.fury) {
        return 'Large knockback';
      }
    },
  },
});
```
I have a similar TTS setup for Stepped Leader and other mechanics in other fights, and they all default to false when checking `data`.

## Additional information

The per trigger options are loaded into the main `raidboss.js` in the user directory by
```javascript
// Import custom fight files.
let myTriggerFiles = [
	'00-misc/test',
	'00-misc/raid',
	'04-sb/orbonne-monastary',
	'04-sb/shinryu-ex',
	'04-sb/seiryu-ex',
	'04-sb/o8s',
	'04-sb/o9s',
	'04-sb/o10s',
	'04-sb/o11s',
	'04-sb/o12s1',
	'04-sb/o12s2',
	'05-shb/titania-ex',
	'05-shb/innocence-ex',
	'05-shb/ruby-ex',
	'05-shb/e1s',
	'05-shb/e2s',
	'05-shb/e3s',
	'05-shb/e4s',
	'05-shb/e5s',
	'05-shb/tea'
];

myTriggerFiles.forEach((file) => {
	UserConfig.appendJSLink('../../user/raidboss-files/' + file + '.js');
});
```
at the bottom of the `raidboss.js` file.

This behaviour started before patch 5.2, since I did start to notice it during one of my last clears of Titan Savage, where a trigger showed this behaviour. It only affected the one trigger back then, so I assumed I messed something up, but now I'm not so sure anymore.

**Comment by quisquous** [comment]
This is quite surprising.  There's nothing special about the way built-in triggers are called vs overrides.  They all go through the same `ValueOrFunction` evaluator in `popup-text.js`.

I assume `E5S Gallop` is your own trigger and you're setting `data.fury` yourself?

This works as expected if I add this:
```
Object.assign(Options.PerTriggerOptions, {
  'Test Poke': {
      SpeechAlert: true,
      TTSText: function(data) {
        return '' + data.pokes;
      },
  },
});
```

...and go to Summerford Farms and poke the striking dummy.

**Comment by CostasAK** [comment]
You're right, that does work. I only now noticed that the `data.fury` got renamed to `data.furysBoltActive` in one of the recent updates, so I think this was a false alarm from me. I was using the data variable set in the pre-made triggers in custom triggers.

I am assuming that the Titan trigger not working as expected is something unrelated then.

Apologies for the false alarm, thanks for your time :)

**Comment by quisquous** [comment]
Sorry about the changes, triggers often get rearranged a good bit during the first week or so of the tier.

**Comment by CostasAK** [comment]
Totally understandable and justified! I just shouldn't have jumped to conclusions.
