### ISSUE TITLE
(Plugin > Overlay > cactbot) = Black box

### ISSUE THREAD

**Issue by TeddyBearsG** [quisquous/cactbot#1158]
When i navigate to the cactbot to make adjustments for volume, etc, all i get is a black box that is it just a black box. everything else with cactbot works perfect no issues. not sure if this is a bug or not. I've reloaded plugin , removed it then readded nothing changes. everything works fine except that one aspect

**Comment by ngld** [comment]
Are you on Windows 7 or 10? Do you see any errors in the overlay log (the text area below the overlay settings)? Does anything change when you restart ACT?

**Comment by quisquous** [comment]
What does the directory structure look like where you have your CactbotOverlay.dll? Probably the easiest option is to remove cactbot from ACT, and then install it again via Get Plugins: https://github.com/quisquous/cactbot#installing-cactbot

**Comment by TeddyBearsG** [comment]
Thanks for the advice Quis! I tried what you said and it worked. I didn't realize you made it easier to install these now, i have been going to the release page and manually doing. lmao that is an easy way to do it. thanks for all your hard work
