### ISSUE TITLE
Updater has a weird title

### ISSUE THREAD

**Issue by cking** [quisquous/cactbot#1162]
## Description

The Titlebar is called "Overlay plugin update"

**Comment by werewolfboy13** [comment]
That probably intentional.

**Comment by cking** [comment]
well, i just wanted to report it as i havent found anything and i noticed it just the other day.
the updater isnt shown every time so it might slip the eyes of the devs.
plus i dont know if the updater was being copied over from the overlay plugin or is used via an exposed api.

**Comment by werewolfboy13** [comment]
I believe it used the same system.

**Comment by quisquous** [comment]
This no longer happens.  Thanks for the bug report!
