### ISSUE TITLE
Text and sound alerts not working.

### ISSUE THREAD

**Issue by Adeptology** [quisquous/cactbot#1168]
I am getting no text or sound alerts on e5s or any other raid, I tested Eden Normal and some savage raids, only the timeline works.
The striking dummy timeline and alerts work. 
So far I've removed and reinstalled ACT, all the needed plugins and the cactbot plugin via the "get plugins" button. 
I've tried adding overlays with the preset "raidboss alerts" and also added custom overlays using the miniparse type selection and the raidboss.html and still get no sound or pop up text alerts.

**Comment by quisquous** [comment]
Are there any errors in your plugin log? What does the config say in Plugins -> OverlayPlugin.dll -> Cactbot -> Raidboss -> Default Alert Output?

**Comment by Adeptology** [comment]
No errors, I've been checking. Alert outputs were left as default (text and sound), but I also tried the three other alert output options without success, I couldn't get alerts to happen at all outside of the striking dummy test no matter what setting I tried. I uninstalled and reinstalled ACT and the three required plugins, following the tutorial multiple times without success. 

Oddly, I was finally able to fix it by installing cactbot the old way. Instead of using the "get plugins button", I just copied the files from a download cactbt zip to my ACT folder. Then I manually added the cactbot plugin by browsing and selecting the cactbot .dll file and also manually selecting the raidboss.html using custom as the preset for the overlay. Pop up alerts work now flawlessly. 

For whatever reason downloading cactbot directly through ACT by using the “get plugin” button and/or adding overlays via ACT too by using one of the presets such as “raidboss alerts” is what seems to completely break the alerts function for me.

**Comment by Adeptology** [comment]
Upon updating cactbot, pop ups no longer work for E5S and onward.

**Comment by ngld** [comment]
Make sure your parser's version is 2.0.5.7. 2.0.5.6 had a bug that broke a bunch of Cactbot callouts and other things.

**Comment by quisquous** [comment]
Was this fixed with the newer version of the ffxiv plugin?

**Comment by quisquous** [comment]
I'm going to close this.  If this is still happening, please see the [#troubleshooting channel](https://github.com/quisquous/cactbot/blob/master/docs/FAQ-Troubleshooting.md#places-to-get-help).
