### ISSUE TITLE
Error after updating

### ISSUE THREAD

**Issue by Coggi** [quisquous/cactbot#117]
Hi, I just updated cactbot to the latest version from 6.0.2 and in the OverlayPlugin i see this error : 

05/05/2018 18:40:05: Info: test: BrowserConsole: Uncaught TypeError: Cannot read property 'length' of undefined (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Plugins/OverlayPlugin/cactbot/ui/raidboss/popup-text.js, Line: 103)

And the raidboss doesn't work.

What did I do wrong?

Thank you

**Comment by IrealiTY** [comment]
What OverlayPlugin are you using?
This one? https://github.com/hibiyasleep/OverlayPlugin ✅
or
This one? https://github.com/RainbowMage/OverlayPlugin ❌

**Comment by Coggi** [comment]
![image](https://user-images.githubusercontent.com/10145448/39667844-3194acb6-50bf-11e8-8363-988d23388ce6.png)
this one

**Comment by IrealiTY** [comment]
Is there any more in the error log?

Did you try re-installing and unblocking the zip file before extracting it?
![image](https://user-images.githubusercontent.com/1223686/39667876-af6670fc-50bf-11e8-9559-61b686cffb48.png)

**Comment by Coggi** [comment]
nope nothing else in the error log and yes unblocked the zip before updating

**Comment by Coggi** [comment]
completely deleting the folders and resinstalling from scratch seems to have fixed this.
Don't know why copying over the new files didn't work o_O

**Comment by Coggi** [comment]
ok the problem seems to be with my raidboss.js placed in the user folder, if I don't put that there everything works. But I don't know what's the problem, isn't that file supposed to be the user customization file that doesn't interfere with others to keep customizations throughout versions? :O 
Here's the file : [https://pastebin.com/NycXLTwr](https://pastebin.com/NycXLTwr )

**Comment by quisquous** [comment]
Thanks.  I think the issue is that you need any block in Options.Triggers needs to have a "triggers" entry.  You commented those out on line 97, 111, and 145.  You can just replace it with `triggers: []` as just an empty set.

I'll fix this in cactbot so you don't need to do that.  But, that should fix your error.
