### ISSUE TITLE
I wanna add Mandarin translation in the zoneRegex under ui/raidboss/data/*/*.js

### ISSUE THREAD

**Issue by kyan001** [quisquous/cactbot#1171]
I wanna add Mandarin translation in the zoneRegex under `ui/raidboss/data/*/*.js`

This will not change any existing functions and all I wanna do is to add `cn: /^...$/` to raidboss js files.

Is that OK? I'll make a pull request when the works done.

**Comment by quisquous** [comment]
Thanks for the pull request! Feel free to add translations wherever they are missed!
