### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by 500m1n** [quisquous/cactbot#1176]
I was told by two separate parties the raid boss alerts can be heard through my discord input. As I'm using Digital Audio out as my primary sound output and headsets microphone as the only input. I'm not entirely sure if this intended. As I haven't done the workaround for it to be heard through discord.

I was told the call outs volume is low and I would like to prevent them from hearing it! 
Thanks!

**Comment by werewolfboy13** [comment]
Whats the issue? This setting page may help.
![image](https://user-images.githubusercontent.com/43587009/76356571-29b4c600-62e4-11ea-9a70-3cdb7f4ac143.png)

**Comment by quisquous** [comment]
Sorry, I'm not sure that this is something that I can fix via cactbot.    Is it just tts, or sound effects, or both that are playing? Do custom triggers from ACT also have this issue?

**Comment by quisquous** [comment]
Following up, if you could answer my question above?

**Comment by 500m1n** [comment]
I apologize for the late reply, As things are super crazy atm.. These are TTS sounds that can be heard. It can be replicated if a person were to speak while the TTS sounds comes on.  Even with the mic set to mute manually, It sometimes can be heard. To physically stop this from happening muting discord completely from the mic seems to prevent it.

**Comment by quisquous** [comment]
Do custom triggers in ACT have this issue too?

**Comment by quisquous** [comment]
Following up again, do custom triggers in ACT have this issue if they play TTS?

**Comment by 500m1n** [comment]
Again apologize for the late reply. No custom triggers in ACT does not have this issue. Seems that issue is specific to Catcbot and TTS.

**Comment by quisquous** [comment]
Do you have "Stereo Mix" turned on in your sound settings? As per this thread: https://windowsreport.com/discord-picking-up-game-audio/

**Comment by quisquous** [comment]
Sorry, I am still not sure what is going on here.  You will likely have better luck asking in the ffxiv act discord about this if it is still an issue.
