### ISSUE TITLE
Error with urls in cacbot module after 0.6.6 update

### ISSUE THREAD

**Issue by Melfice** [quisquous/cactbot#118]
I was using a separate instance of cactbot module in the overlay plugin for my own implementation of ultimate coil's dragons tracking, which was made in a separate html and ran with "actserver" plugin for making it easier to transfer into obs stream and my own screen, so I just opened in overlay an url http://localhost:23456/nael_dragons_test.html
After the 0.6.6 update it errored out in console with
10.05.2018 17:37:04: Error: test: Error checking html rel dir: http://localhost:23456/nael_dragons_test.html: System.UriFormatException: Недопустимый URI: Невозможно выполнить разбор имени хоста.
   в System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   в Cactbot.CactbotOverlay.GetLocalUserFiles(String config_dir)
   в Cactbot.CactbotOverlay.GetUserConfigDirAndFiles(String& config_dir, Dictionary`2& local_files)
In general, thats not a big issue, because I just had to make an instance of "MiniParseOverlay" and point it to the same place (all the logic is made separately without cactbot api, using it probably was an overkill anyway, just left it like this after experiments) and it works fine, I need it just to show me an overlay on screen anyway, but something regarding trying to open an actual URL and not file from disk probably got broken in cacbot.

**Comment by quisquous** [comment]
Thanks for the report.  I'll take a look and try to fix it for the next version.

Cactbot does work with general urls (e.g. https://quisquous.github.io/cactbot/ui/raidboss/raidboss.html) but maybe there's something wonky going on with proxied localhost urls.
