### ISSUE TITLE
Unable to do TTS

### ISSUE THREAD

**Issue by KiraRyuKage** [quisquous/cactbot#1191]
I just downloaded the latest version of cactbot and I am unable to get the TTS feature to work. I go to edit the raidboss java file but I do not see the command for TTS. Furthermore when I try to save anything I've edited it tells me I do not have permission to do so. I have tried opening notepad with administrator and still nothing. I am trying to get this all setup for my static so any assistance would be greatly appreciated!

**Comment by quisquous** [comment]
If you're just trying to use tts, then probably the config panel is the way to go.  Does https://github.com/quisquous/cactbot/blob/master/README.md#cactbot-customization help?

**Comment by quisquous** [comment]
Hi, is this still happening?

**Comment by quisquous** [comment]
I'm going to close this.  If this is still happening, please let me know.
