### ISSUE TITLE
incorrect cn zoneregex

### ISSUE THREAD

**Issue by DieMoe233** [quisquous/cactbot#1193]
He committed the wrong localization information to overwrite the correct Chinese localization content.

**Comment by quisquous** [comment]
Hey, I get that you're angry, but the issue title here is uncalled for.  I don't know Chinese, so I trust folks submitting pull requests.

**Comment by kyan001** [comment]
> 
> 
> Hey, I get that you're angry, but the issue title here is uncalled for. I don't know Chinese, so I trust folks submitting pull requests.

I'm sorry for the zoneRegex problem. The root cause of this is that I used the Chinese names in Wiki, but they missed quotes which the ACT actually needed. 

I already fixed it in [PR#1197](https://github.com/quisquous/cactbot/pull/1197)
