### ISSUE TITLE
Timeline extensions break act plugin 

### ISSUE THREAD

**Issue by danakj** [quisquous/cactbot#12]
We need to hide them behind comments or event lines to not break it's parsing.

**Comment by danakj** [comment]
Also should we show parse errors?

**Comment by quisquous** [comment]
Parse errors: yes please.

I'm kind of torn on what to do about these.  I wonder if we could just convince the ACT timeline person to say that any unknown keyword starting a line is just ignored with a console warning?  And then we'd be free to do whatever?

**Comment by sqt** [comment]
Is this a different plugin for timelines you're trying to be compatible
with and/or extend?

**Comment by danakj** [comment]
Yes, it reads the same file format, but we've extended the format with additional commands. See https://github.com/quisquous/cactbot/blob/master/ui/raidboss/data/timelines/README.txt for information on what we did at the moment with the file format.

And https://github.com/quisquous/cactbot/blob/master/ui/raidboss/timeline.js is the implementation of the timeline presentation.

**Comment by danakj** [comment]
>  I wonder if we could just convince the ACT timeline person to say that any unknown keyword starting a line is just ignored with a console warning?

That'd be really ideal yeah, worth a try.

**Comment by danakj** [comment]
I think @ayonetta has the canonical repo for it now (it's a fork but more recently maintained). https://github.com/anoyetta/act_timeline  I've had a good experience with submitting patches to them before.

**Comment by danakj** [comment]
I thought about it some more and I don't know its worth it to try submit a fix to anoyetta. It would require them to do a release, which they might or might not do soon after doing the merge. And then it would require users to all update their addon, which most won't probably. So it would still be breaking.

I think we should just hide extensions behind comments..

**Comment by danakj** [comment]
I remembered a convo we had about moving timeline loading to the triggers and explored that a bit. Looks like it's pretty reasonable.

I'm not sure what to do about infotext etc.. although they can go in the triggers file as "timeline additions" instead of in the timeline text file itself.

**Comment by danakj** [comment]
https://github.com/quisquous/cactbot/commit/8ee839acf4b59e2e10e9da66d32062b5961dca3f addresses this.

It's not perfect, but it gets the timeline files we're shipping to be free of the extensions.

**Comment by danakj** [comment]
Inclined to close this for now.
