### ISSUE TITLE
RaidEmulator - Elapsed Time display incorrect when rolling over minutes

### ISSUE THREAD

**Issue by valarnin** [quisquous/cactbot#1246]
## Description

When RaidEmulator's elapsed time rolls over a minute, e.g. from `1:59/11:00` to `2:00/11:00`, it instead displays `1:00/11:00` for the first second of the second minute, etc.

## Additional information

It's the most minor things that I notice when I'm sitting there waiting for custom triggers/timeline entries to test...

**Comment by quisquous** [comment]
Thanks for the bug report.  I like the raidemulator's real time playback, but as a side thought I also wonder if it'd be good to have something that could read a log and instantly just print out all of the triggers that fired and what they printed.

**Comment by valarnin** [comment]
I've thought a few times about some sort of analysis of pulls, like a list of triggers and you can select a trigger to get info about what caused it and what it displayed to who. Also thought about taking a stab at raidemulator pulling the current set of encounters from ACT instead of having to re-import each time (by looking at start time/end time of encounter history and doing a re-import of those lines specifically from the file). Lots of thoughts, but not really much from them yet.

**Comment by quisquous** [comment]
I think the "reimport" issue could be fixed with #853.  If you could store more fights (or even one full TEA log), then it's much easier to reload and iterate without the reimport step.

Not to say that loading from ACT wouldn't also be an option, but just saying I think there's already half a solution there, it just needs to be finished.

**Comment by valarnin** [comment]
This issue is now irrelevant with the redesigned raidemulator.
