### ISSUE TITLE
Cactbot not working after 0.7.0 update 

### ISSUE THREAD

**Issue by GatoGrande** [quisquous/cactbot#125]
Everything seems to load fine but nothing seems to trigger the overlays to appear after starting an encounter. I keep getting these errors after updating cactbot to the newest update.

Info: oopsyraidsy: BrowserConsole: Uncaught TypeError: window.OverlayPluginApi.overlayMessage is not a function (Source: , Line: 6)
Info: Raidboss: BrowserConsole: Uncaught TypeError: window.OverlayPluginApi.overlayMessage is not a function (Source: , Line: 6)

**Comment by GatoGrande** [comment]
i was using the 0.3.4.0 version of the overlay plugin

**Comment by quisquous** [comment]
Sorry to be a broken record, but can you copy and paste the version strings (and paths) from the plugin log that cactbot prints out? Sometimes folks have other version of the overlay plugin lying around and so they think they're using one but are actually using another.

**Comment by GatoGrande** [comment]
Sorry I don’t have all that anymore. I just had a friend send me his whole ACT folder which was working and just replaced everything with that. But I was using the 0.3.4.0 overlay plugin at the time  which is the latest version I think.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by quisquous** [comment]
Ok! Are you saying you got this working now and you're no longer getting this error?

**Comment by GatoGrande** [comment]
Yeah its working now after replacing the entire thing. thanks O/
