### ISSUE TITLE
Raidboss: TEA head marker fix wasn't perfect

### ISSUE THREAD

**Issue by JLGarber** [quisquous/cactbot#1266]
[Per a comment on the pull request](https://github.com/quisquous/cactbot/pull/1206#issuecomment-602139160), the first number on the first Limit Cut does not get a callout. It's probably a race condition, so the easy solution is *probably* to just delay the Limit Cut callout by .25 seconds or something.

**Comment by JLGarber** [comment]
Looking into it a little more, I'm actually a little puzzled on how there could be a race condition. For reference, the current correction function:

```
let getHeadmarkerId = (data, matches) => {
  if (!data.decOffset) {
    data.decOffset = parseInt(matches.id, 16) - 79;
  }
  return '00' + (parseInt(matches.id, 16) - data.decOffset).toString(16);
};
```

I *think* the condition on the Limit Cut trigger shouldn't race here?

`return data.me == matches.target && (/00(?:4F|5[0-6])/).test(getHeadmarkerId(data, matches))`

There's no good reason this should return false on the first pass. That being said, what if we changed the condition to...

`return data.me == matches.target && ((/00(?:4F|5[0-6])/).test(getHeadmarkerId(data, matches)) || !data.decOffset)`

Between this and a `delaySeconds` value of 0.1-0.2, we should be able to avoid missing the first one. Or we could even made the delay dependent on whether or not the offset exists via a line in the condition function. (If the offset doesn't exist, the delay could be set to 0.2, while if the offset *does* exist, we could set it to 0.)

**Comment by quisquous** [comment]
I'm not sure how there can be a race condition here.  What are you suggesting is racing against what?

Does this repro in the raid emulator?

**Comment by JLGarber** [comment]
(Sorry, all that was off the top of my head, I didn't have time to track things down properly last night. Finally got the emulator working after updating it. I haven't cleared out my installation since we moved to the new overlay.)

It does reproduce, yes. Definitely doesn't call marker 1, and calls others. (WHYY does Limit Cut have to be 3 minutes in? Am I missing a convenient way to skip ahead in the encounter?) I'm very confused. I agree that it shouldn't race, and from a quick drop-in of the changes I proposed, it *isn't*. (I did a test with the changed condition I suggested, and even that did nothing.)

However, when I changed `getHeadMarker()` to the following:
```
let getHeadmarkerId = (data, matches) => {
  if (!data.decOffset) {
    data.decOffset = parseInt(matches.id, 16) - 79;
    return '004F';
  }
  return '00' + (parseInt(matches.id, 16) - data.decOffset).toString(16);
};
```

Player 1 instead received an alert of "# Undefined".

I'm baffled.

**Comment by quisquous** [comment]
Re: raidboss, I have added console.log statements with the player's name and then whatever debug info I wanted to print.  I still think it would be useful to have a raid emulator mode (or something similar) that just instantly prints all of the triggers.  There's no way to skip, because time is not handled very well (like delaySeconds/suppressSeconds).  (patches welcome?? :P)

My suspicion is that the error here is that `toString(16)` needs to be `toString(16).toUpperCase()`

**Comment by JLGarber** [comment]
-_____-

That was it.
