### ISSUE TITLE
UWU Titan Gaols issues

### ISSUE THREAD

**Issue by NihalZeor** [quisquous/cactbot#1268]
As title says, the callout for the titan gaols works only when you are not one of the gaols, otherwise it just calls nothing :(
I cleared uwu months ago, and back then the gaol callout worked perfectly, but right now it works only when I'm not one of the gaols.
Thanks for the patience!

**Comment by quisquous** [comment]
Thanks for the bug report.  Do you have a recent Network log that you can zip and attach here?
