### ISSUE TITLE
Oopsy anonymous mode

### ISSUE THREAD

**Issue by Truf** [quisquous/cactbot#1272]
A way to possibly change names to just the job, or maybe initials of the player.

**Comment by quisquous** [comment]
What's the goal of initials instead of names? I'm not sure I quite follow what the underlying intent is here.

**Comment by Truf** [comment]
To have it on stream, but to not outright name people. Mainly for memeing

**Comment by quisquous** [comment]
The goal of oopsy is to make information more obvious so it's faster to analyze what's going wrong, not to trash on people for messing up.  I think this is not something I plan on implementing, and so am going to close this feature request.  Sorry!
