### ISSUE TITLE
Please update information on writing custom trigger to reflect recent changes

### ISSUE THREAD

**Issue by Macapple96** [quisquous/cactbot#1286]
I love the recent changes to triggers, we now have functions to call such as `Regexes.startsUsing` or `Regexes.gainsEffect`, it will be easier to write triggers, but I couldn't find any updated information or list of these new functions; could you please update the examples? 💯

**Comment by JLGarber** [comment]
Not a bad point, there is definitely some updating that could be done in the raidboss readme. I'll see about that this weekend.
