### ISSUE TITLE
Timeline events with the same time should preserve file order

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#13]
If I have:

10 "Thing 1"
10 "Thing 2"

Then "Thing 1" should always precede "Thing 2"

See: https://www.twitch.tv/videos/177084203?t=3m16s and the two things at t=118

**Comment by danakj** [comment]
Fwiw I just used small decimal differences to specify order

**Comment by danakj** [comment]
Fixed by https://github.com/quisquous/cactbot/commit/8ae4f09ea52ed2608f863576dae15ba3789893af
