### ISSUE TITLE
Replace localized regexes with timelineReplace

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#1306]
Right now, it's redundant to have to translate a timeline once and then every regex separately.  `timelineReplace` handles timeline translation at runtime, but only does regexes via scripts in `util/`.  It would be better to have `timelineReplace` cover both timelines and regexes at runtime.

Unfortunately, there are currently some issues before this could switch over:
(1) Missing translations (translations in `timelineReplace`but not in regexes or vice versa)
(2) Inconsistent translations (translations in both, but they're not the same)

To help with this, `util/find_missing_translations.py` complains about missing `timelineReplace`for regexes and also about mismatches beteween `timelineReplace` and localized regexes right now. 

When these are all fixed, and code is written to use `timelineReplace` at runtime, then it would be safe to switch over, and delete all localized regex.

Example errors:
```
.\ui\raidboss\data\04-sb\raid\o4s.js:925 O4S Neo Beyond Death Delta Initial: missing timelineReplace for regex '^.{14} 1a:(?<targetid>[0-9a-f]{8}):(?<target>.*?) gains the effect of (?<effect>beyond death) from (?<source>.*?) for (?<duration>-?[0-9]+(?:[.,][0-9]+)?(?:e-?[0-9]+)?) seconds\.' (but have regexDe)
.\ui\raidboss\data\04-sb\raid\o12s.js:613 O12S Archive Peripheral: incorrect timelineReplace for regex, got '^.{14} 1b:[0-9a-f]{8}:recht(?:e|er|es|en) arm:....:....:(?:009c|009d):', needed regexDe '^.{14} 1b:[0-9a-f]{8}:rechter arm:....:....:(?:009c|009d):'
.\ui\raidboss\data\04-sb\eureka\eureka_hydatos.js:299 BA Owain Ice Element: missing timelineReplace for regex '^.{14} 00:0044:.*?:[^:]*:munderg, turn blood to ice'
```

**Comment by valarnin** [comment]
Copy/pasting my comment from 3120.

---

Wouldn't it be better to do either of these instead?
- Keying triggers with enemy names off of bNpcId
- Pulling translation info from XIVAPI and looking up from that

It seems a bit odd to me that a lot of triggers keep on keying off of name instead of ID in general, and something like one of the following would be better all around:

```typescript
    {
      id: 'T1 High Voltage',
      // `npcName` in this case is { [englishNpcName: string]: LocaleText }
      netRegex: NetRegexes.startsUsing({ source: npcName['ADS'][data.options.ParserLanguage], id: '5A7' }),
      condition: (data) => data.CanSilence(),
      response: Responses.interrupt(),
    },
    {
      id: 'T1 High Voltage',
      // `npcName` in this case is { [npcId: number]: LocaleText }
      netRegex: NetRegexes.startsUsing({ source: npcName[1459][data.options.ParserLanguage], id: '5A7' }),
      condition: (data) => data.CanSilence(),
      response: Responses.interrupt(),
    },
    {
      id: 'T1 High Voltage',
      // If the fight only has one actor using '5A7', why key off of name at all?
      netRegex: NetRegexes.startsUsing({ id: '5A7' }),
      condition: (data) => data.CanSilence(),
      response: Responses.interrupt(),
    },
```

`timelineReplace` could look up the names in the same way, or even do an auto map after the fact, looping over all the relevant IDs or whatever and adding them to `timelineReplace` without having to copy/paste as much, something like:

```typescript
const npcIds = ['ADS', 'Caduceus', 'dark matter slime'];

for (const id of npcIds) {
  for (const lang of languages) {
    let langMap = triggerSet.timelineReplace?.find((m) => m.locale === lang);
    if (!langMap) {
      langMap = {
        'locale': lang,
      };
      triggerSet.timelineReplace?.push(langMap);
    }
    if (!langMap.replaceSync)
      langMap.replaceSync = {};
    if (!langMap.replaceText)
      langMap.replaceText = {};
    if (!(id in langMap.replaceSync))
      langMap.replaceSync[id] = npcName[id][lang];
    if (!(id in langMap.replaceText))
      langMap.replaceText[id] = npcName[id][lang];
  }
}
```

That could even be a Util helper, pass it the trigger set and the array of IDs and it'll map everything over, and automatically pick up new translations whenever the xivapi export or whatever is updated.

**Comment by quisquous** [comment]
Thanks for all the thoughts.  I think there's a bunch of options here.

> Pulling translation info from XIVAPI and looking up from that

Akurosia has a bunch of scripts that do exactly this (although the ability / npc ids are not baked in).  Arguably, we should check those into the repo, but Akurosia promptly commits all the changes any time I ever add anything that needs translation and doesn't seem to want to wrangle getting the scripts committed, so that's where we are.

> Keying triggers with enemy names off of bNpcId

``// `npcName` in this case is { [englishNpcName: string]: LocaleText }`` sounds pretty reasonable here, but it's not clear to me how to get the parser language. You say `npcName['ADS'][data.options.ParserLanguage]` but `data` doesn't exist in this context.

Even if that could get solved, I think ultimately there are still a bunch of types of lines that need translating, game log lines (dialog, zone sealing, zone unsealing), but maybe this would solve the vast majority of it.

> If the fight only has one actor using '5A7', why key off of name at all?

This is also a strong possibility too? There are some examples of npcs using abilities that players can use (often friendly npcs with player jobs) but I don't know of any examples where this matters in practice.

I can't remember why I included names anymore, now that I think about it.  I think maybe it was trying to be robust against things changing, but honestly it's probably overkill??

**Comment by quisquous** [comment]
I see about ~170 instances, some of which are also #4156 which needs to be addressed separately.

[timeline_replace_incompat.txt](https://github.com/quisquous/cactbot/files/8643608/timeline_replace_incompat.txt)

**Comment by quisquous** [comment]
(cc @Akurosia)

**Comment by quisquous** [comment]
Ok, with recent changes (and realizing that "no timelineReplace + no regex" is not an issue and can be ignored), we're down to 27 issues, most of which are incorrect seal messages (revealed by landing #4407) and a couple of missing test translations.

[incorrect_or_missing.txt](https://github.com/quisquous/cactbot/files/8647486/incorrect_or_missing.txt)
