### ISSUE TITLE
old fights not callingout.

### ISSUE THREAD

**Issue by ShinjiSen** [quisquous/cactbot#1310]
So, I noticed this happend to a user before; But it seems to happened to me How do i fix it
The Problem is: 
The OLDER Fights such as E4S Won't call out 'Corner/Cardinal' Left / Right, Get off back left get off top left, For example; Which i don't get why as the New Raid Tier Works. Am i doing something wrong?

**Comment by quisquous** [comment]
Are there any errors in your overlayplugin log? Can you zip up and attach a Network log from doing e4s in case something changed?

**Comment by quisquous** [comment]
Hi, is this still happening?

**Comment by ShinjiSen** [comment]
No actually it seems fixed but tbh I haven’t really been able to test it
yet I did one trial run and it seemed fixed you can close my ticket bout it
I’ll remake it if it’s not sorry for not getting back to you

**Comment by quisquous** [comment]
No worries at all.  Glad it seems fixed, and sorry there wasn't a clearer answer!
