### ISSUE TITLE
A1S triggers no calling

### ISSUE THREAD

**Issue by VanSlanzar** [quisquous/cactbot#1314]
I noticed this problem, the triggers (gunnery pod) and (resin bomb) are not doing their job.
 a problem has identified (ID on resin bomb), but it is not enough.
I tried a lot of things, but I can't find it, I tried with the French and English version.
I'm sorry to bother you for old content. Thank you.

Here are screens and the log file:
- https://uptobox.com/jj5us74d2ess act file a1s
- https://uptobox.com/m7m1g7efnfxf htlm file a1s

no calling resin bomb (infotext)
![resin](https://user-images.githubusercontent.com/61565834/78565503-50501900-781e-11ea-86f5-858793908ce8.PNG)

no caling gunnery pod (respons.js)
![gunnery](https://user-images.githubusercontent.com/61565834/78565672-8ab9b600-781e-11ea-9ee0-b86efa5e5dfb.PNG)

**Comment by JLGarber** [comment]
For Gunnery Pod, at least, that needs to be a timeline trigger as it's an instant cast. There are no associated `14` log lines, so it makes sense you would never have seen a notification.

For Resin Bomb, there's a `targetIsYou()` condition that prevents it from activating. `E46` Resin Bomb is first used on Oppressor. Once that cast ends, Oppressor then starts using `E47` Resin Bomb on Unknown targets. (Four randomly selected players, but it doesn't target them directly.)

**Comment by VanSlanzar** [comment]
I just did (a1s). The problem for (gunnery pod) is solved. However, (resin bomb) still not. Either ID (e46 or e47), I don't know, and could there be a problem with the file (a1s.txt)? Thank you for help me with this problem.
