### ISSUE TITLE
I'm not hearing the triggers of my cactbot.

### ISSUE THREAD

**Issue by hppnq14** [quisquous/cactbot#1318]
Hi all,

I'm currently encountering some how an issue on my cactbot. I've downloaded all the recent patch and installed them carefully, ACT is running as administrator. However when I do a save run e5s-e7s I do not hear any triggers from my cactbot.

See below screenshots:

![image](https://user-images.githubusercontent.com/63309744/78697806-f6417780-7933-11ea-8743-43d10840a787.png)

![image](https://user-images.githubusercontent.com/63309744/78697852-06595700-7934-11ea-9ef6-453e1d4ed75f.png)

![image](https://user-images.githubusercontent.com/63309744/78697883-0d806500-7934-11ea-871f-a6b093e4cf8a.png)

![image](https://user-images.githubusercontent.com/63309744/78697993-36a0f580-7934-11ea-826f-2ada310d4610.png)

**Comment by hppnq14** [comment]
Oh also in addition when I do the /countdown 5 in Summerford it is working, however when inside the raid I cannot hear a single trigger

**Comment by ngld** [comment]
The 5.25 patch broke the parser. Wait until it updates.

**Comment by Tsunayoshi** [comment]
Also have a look at this:
![image](https://user-images.githubusercontent.com/5128201/78763738-d470e080-7985-11ea-8f4d-33023fbd7fa8.png)
Plugins like Yukkuri change this setting and after u removed it, its not reverted to normal.

**Comment by hppnq14** [comment]
Hi all, after the patch somehow the triggers are working but some are not.

For example below

I only hear the avoid green nails and the other but I do not hear AOE

![image](https://user-images.githubusercontent.com/63309744/78772313-26385b80-79c4-11ea-8568-18b341736027.png)

**Comment by hppnq14** [comment]
Also, does cactbot works on discord?

I also tried installing the discord plugin but my friends cannot hear it

**Comment by quisquous** [comment]
Are other triggers not calling out? "aoe" doesn't call out for everybody, only for healers and for folks who could reprisal or addle it.

I do not know much about the discord plugin.  Maybe folks in the ffxiv act discord would know.  You could ask in #troubleshooting there.

**Comment by quisquous** [comment]
If you're still having issues, please see the [#troubleshooting channel](https://github.com/quisquous/cactbot/blob/master/docs/FAQ-Troubleshooting.md#places-to-get-help).
