### ISSUE TITLE
Idea for Tsukuyomi Trigger

### ISSUE THREAD

**Issue by xarfger** [quisquous/cactbot#132]
```
	// Helper for those who want to stay alive till Meteor :D
	// Casttime of Spell ~9sec + 25 sec Delay to have 4-5 seconds to run to small Area
	// http://clees.me/guides/tsukuyomi-ex/
	/*
    0:00 – Moon Tick 1
    0:05 – Moon Tick 2
    0:10 – Moon Tick 3
    0:15 – Moon Tick 4 (Switch here if you have not)
    0:17 – Nightfall Begins
    0:20 – Moon Tick 5 + Weapon Appears
    0:25 – Moon Tick 6 + Gun Resolves
    ~0:28-0:29 – Spear Resolves
    0:30 –  Moon Tick 7 + Meteor position locked
    0:35 – Moon Tick 8 (You must be in the small color for this tick or you will not survive the following ticks) + Meteor explosion	
	*/
	{
	  id: 'Tsukuyomi Surpreme Selenomancy',
	  regex: /:Tsukuyomi uses Supreme Selenomancy/,
	  delaySeconds: 34,
	  alarmText: {
		  en: 'Move to small Area',
	  },
	  tts: {
		  en: 'Move to small Area',
	  }
	}
```

I wrote this code myself to remind me to get a Stack from the Small Area, with the MTQ Strategy this is obsolete but maybe it helps some People. After starting the YingYang Phase a timer is started and ~5 seconds before the last tick the Warning will appear.

**Comment by quisquous** [comment]
Mmm, this is a good thought, thanks!

Out of curiosity, what is the MTQ strategy?

**Comment by xarfger** [comment]
https://youtu.be/6jXScwlL9fM :) there you go

I think there needs to be a little finetuning to the delay for me its fine but maybe for the majority there could be added some seconds. Feel free to use / optimize it :)

**Comment by quisquous** [comment]
I tried this, and I'm not sure it adds a lot.  At least in most pug strats I see, the meteor aoes go off and then it says "stack in small area" about 1 second before hand, and so most folks are already running for the safe area, which is in the small area.

**Comment by xarfger** [comment]
Yeah as I said there maybe needs to be some finetuning on the number of seconds. If you know the fight and the mechanics this trigger is "useless" but its a neat reminder for some people. With no marker strat or mtq strat getting a small area buff is not that hard. I think this trigger is more "needed" if you do the Mr Happy strat.

**Comment by quisquous** [comment]
Yeah, I haven't seen any pugs do the Mr. Happy strat.  I'll keep this in the back of my mind if other folks start asking, but I'm not going to add it for now.
