### ISSUE TITLE
Hello, new to cactbot but

### ISSUE THREAD

**Issue by DreadwyrmBahamut** [quisquous/cactbot#1325]
I wasnt sure where else to post or who to ask, But how long roughly does it take for new raid/trial content to be added to cactbot? For example the memoria misera (extreme) trial. I'm not sure if I have to manually update cactbot? or if auto updates when i start ACT. Also I couldnt find any place to donate... personally for me after being gone from FFXIV for two years this plugin has done wonders and I wanted to show my support by donating

**Comment by cerilaffxiv** [comment]
Cactbot relies on the community (and @quisquous ) to do updates to timelines. There is a fairly comprehensive guide on how to make timelines should you want to try your hand at contributing here: https://github.com/quisquous/cactbot/blob/master/docs/TimelineGuide.md

Cactbot will auto-update once quisquous generates a new release. If you want to see upcoming changes to cactbot, there are two places to check:

- https://github.com/quisquous/cactbot/pulls
- The ACT_FFXIV Discord (https://discord.gg/ahFKcmx)

https://github.com/quisquous/cactbot/pull/1322 seems to indicate Memoria Miser(y)a Ex triggers are on the docket for being included in a release some time in the future. quisquous can comment further

**Comment by DreadwyrmBahamut** [comment]
Thank you!

**Comment by quisquous** [comment]
Glad to hear that cactbot has done wonders for you :heart:

Enjoy the update!
