### ISSUE TITLE
Unable to cast object of type 'Cactbot.PluginLoader'

### ISSUE THREAD

**Issue by Gingy92** [quisquous/cactbot#1339]
![cactboterror](https://user-images.githubusercontent.com/28961671/79176395-bb24c580-7dc5-11ea-850b-888754c1c31a.png)

installed everything how i have on other machines recently from ACT itself, go to download cactbot, it does its thing, and still nothing shows up in presets for cactbot.

**Comment by quisquous** [comment]
What does the order of plugins look like? You probably need to move FFXIV_ACT_Plugin.dll to the top.

**Comment by VanSlanzar** [comment]
Is your problem solved?

**Comment by Gingy92** [comment]
Yes, Success!! Sorry about the delay.
