### ISSUE TITLE
v5.11 TEA head marker support

### ISSUE THREAD

**Issue by Jaehyuk-Lee** [quisquous/cactbot#1346]
## Description

head markers are shown wrong on cactbot overlay with v5.11 client.
|exact number|shown number|
|---|---|
|1|1|
|2|1|
|3|2|
|...|...|
|7|6|
|8|7|

## Additional information

I don't have network log file, but there's working js file now distributed on Korean community.
[link](https://drive.google.com/file/d/1DPmuGLTV-j9Jp8kWR5t95t9HdmyP9x0T/view)

FYI - I don't do TEA.

**Comment by ShadyWhite** [comment]
> ## Description
> head markers are shown wrong on cactbot overlay with v5.11 client.
> 1 shown 1
> 2 shown 1
> 3 shown 2
> ...
> 7 shown 6
> 8 shown 7
> 
> ## Additional information
> I don't have network log file, but there's working js file now distributed on Korean community.
> [link](https://drive.google.com/file/d/1DPmuGLTV-j9Jp8kWR5t95t9HdmyP9x0T/view)

This error is the same as the Chinese server is happening.

**Comment by JLGarber** [comment]
I'm extremely surprised that `getHeadMarkerID()` is failing that way. I'm also surprised that Square did not add in the scrambling for the head markers. Unfortunately I can't do much without a log. If you could ask around your communities for one, I can at least try to figure out what the failure is. (Since the error is occurring for both CN and KO, I can probably use a log in whichever language anyone is able to give me.)

**Comment by Jaehyuk-Lee** [comment]
> I'm also surprised that Square did not add in the scrambling for the head markers.
@JLGarber I think you're telling, you've thought SQEX will apply some scrambling to head marker on v5.1 to CN and KO, but there's never been forth applying patches. There were no randomizing opcodes before v5.1 on Korean server even though SE's server was already applied. This scrambling head markers won't happen until v5.2 too.
So, if there's some important code change which varies by patch version, should diverge code by patch version until other servers get the same patch. If it can be solved without divergence, it's better though.

**Comment by JLGarber** [comment]
I know it has not been done before, but there has not been a good reason in previous patches. Here, there was a good reason, or at least I would have thought Square would think so. I did not expect them to simply follow the straight patch progression with no changes.

You are likely correct about having to split code by patch, but I do hope that after I get a log I can figure out a way to fix things that will not care about which patch we are on.

**Comment by Jaehyuk-Lee** [comment]
I understand you think that way, but there won't be something applied forward, skipping 0.x patches. 
+I'm trying to get log.

**Comment by Jaehyuk-Lee** [comment]
[log1](https://drive.google.com/file/d/1q_v9cRcz6kPg2mxhfsbyDpxd9ssa0ikm/view)
[log2](https://drive.google.com/file/d/1XovhNKT9ATTktBwE376xMYAe26ZJm72H/view)
I don't know if this log includes other fights too.

**Comment by JLGarber** [comment]
Thanks for that! Unfortunately, I cannot see what the issue might be from a brief look, and it will take longer than I have over lunch to investigate. I will take a closer look tonight.

**Comment by JLGarber** [comment]
Okay, quisquous helped me figure this out. I'll write up the full explanation for what went wrong on the pull request. Thanks for the bug report!
