### ISSUE TITLE
Exception when importing file while game isn't running

### ISSUE THREAD

**Issue by valarnin** [quisquous/cactbot#1350]
## Description

When importing a log while the game is not running, an exception is thrown and logged in the OverlayPlugin output text area and the log is never passed to raidemulator.html

## Additional information

Stack trace:
```
[4/17/2020 7:15:48 PM] Error: Exception in SendFastRateEvents: Object reference not set to an instance of an object.
[4/17/2020 7:15:48 PM] Error: Stack:    at Cactbot.FFXIVProcess.GetInGameCombat()
   at Cactbot.CactbotEventSource.SendFastRateEvents()
   at Cactbot.CactbotEventSource.<Start>b__75_0(Object o, ElapsedEventArgs args)
[4/17/2020 7:15:48 PM] Error: Source: CactbotEventSource
```

I can't fix this myself and submit a PR since my C# dev VM is currently busted, unfortunately.

Also, any chance the date can be passed as part of the `onImportLogEvent` event? Just the date of the first line from the file would be sufficient. Otherwise there's no way to get the date from the imported lines overlay-side.

**Comment by quisquous** [comment]
The imported log lines are exactly what are provided from the ACT plugin.  This could be another case where if everything was on network log files, we could just drag and drop network log files into the raid emulator and skip the plugin entirely.

I'll try to take a look at the exception end of things.

**Comment by valarnin** [comment]
My hope is that the date of the log being imported is sent at some point and can be added to the JS response separately like:

```json
{
  "logs": ["line"],
  "date": "2020-04-19 (maybe also time, or just a timestamp)",
}
```

**Comment by valarnin** [comment]
I think that this issue is defunct now that everything's on network log lines and now that raidemulator doesn't read imported logs through ACT anymore. The exception should probably still be fixed, but it's not impacting the original use case this issue was opened for.

**Comment by quisquous** [comment]
I agree that this is defunct.
