### ISSUE TITLE
raidboss: default css - infoText color

### ISSUE THREAD

**Issue by Jaehyuk-Lee** [quisquous/cactbot#1352]
## Summary

I'm using white color for infoText, green color wasn't standing out against green grass platform while Titania EX.
![K-001](https://user-images.githubusercontent.com/4695371/79689721-94690200-8291-11ea-9b7d-d35e29d87749.png)

I've applied some other slight changes to css, but I don't know if those changes are good for everyone.
However, I think white color for infoText is definitely better than green one.
+I'm not a designer so I'm not good at coloring, so I didn't tried changing text-shadow css, my best is black, simple.
If comments says this change would be good, I'll pull request here.

**Comment by Bluefissure** [comment]
As you said green may be a bad color for Titania EX, white may also be similar to the ground in E7S.

I think we may provide a css override for different raids if necessary.

**Comment by Jaehyuk-Lee** [comment]
white was okay since there's text-shadow: black

**Comment by quisquous** [comment]
Another option is to change the shadow color so that when it is green infoText on a green background, it is more readable?

**Comment by Jaehyuk-Lee** [comment]
I've tested with complimentary color of #2b2.
`text-shadow: -2px 0 4px #b22, 0 2px 4px #b22, 2px 0 4px #b22, 0 -2px 4px #b22;`
This looks bad I think.

![K-001](https://user-images.githubusercontent.com/4695371/80294482-2eeea700-87a4-11ea-9424-cf0b93808c32.png)

**Comment by quisquous** [comment]
Yes, agreed that red and green don't really go together.  Maybe white is the best answer here as a default.  I still want to leave this open in case other people have opinions, but I'd be happy to merge a change like this in a little bit if nobody has other complaints.

**Comment by quisquous** [comment]
Hmm.  I got some angry complaints about this from people who really didn't like the white.  I also feel like playing for a bit with it, I find it much harder to read during big flashy boss explosions, which often seem to be more bright and white.

I think I might revert this if the only issue is really Titania, for the most part?

**Comment by Jaehyuk-Lee** [comment]
okay, if so I'll keep this just my own.
