### ISSUE TITLE
Timelines no longer showing

### ISSUE THREAD

**Issue by laigerzer0** [quisquous/cactbot#1360]
For some reason the timelines are no longer showing up on my ui. The error I'm getting is Info: Raid: BrowserConsole: Uncaught TypeError: this.timerlist.clear is not a function (Source: file:///C:/Users/<Username>/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot-0.16.6/cactbot/ui/raidboss/timeline.js, Line: 640).

**Comment by quisquous** [comment]
Fixed in 0.17.1.
