### ISSUE TITLE
Test mode isn't working.

### ISSUE THREAD

**Issue by inarahana** [quisquous/cactbot#1361]
I've installed the addon and the dps overlay works, but the actual cactbot raid addon doesn't seem to want to work at all.

I've gone to summerford and done /cd 5 but nothing happens after the timer expires. I can load the overlay and move it around, but other than that, it's not responding at all.

Are there any common mistakes people make that I might have done during setup that means it isn't working?

**Comment by Bluefissure** [comment]
Could you provide the log in ngld overlayplugin or any screenshot?

**Comment by quisquous** [comment]
Did you add a raidboss overlay preset?

**Comment by quisquous** [comment]
I'm going to close this for now due to lack of responses.  If you're still having trouble please visit the [#troubleshooting channel](https://github.com/quisquous/cactbot/blob/master/docs/FAQ-Troubleshooting.md#places-to-get-help).
