### ISSUE TITLE
How can i use chinese text and alter in EN client?

### ISSUE THREAD

**Issue by FrankBlue453** [quisquous/cactbot#1364]
Alter language i can find easily
but cant find how to show chinese text in raidboss
timeline and trigger

**Comment by Una-P** [comment]
![image](https://user-images.githubusercontent.com/39465903/79813929-f1f76e80-83b7-11ea-9302-01bdc60deb85.png)
Did you change Alerts language to CN?

**Comment by FrankBlue453** [comment]
> ![image](https://user-images.githubusercontent.com/39465903/79813929-f1f76e80-83b7-11ea-9302-01bdc60deb85.png)
> Did you change Alerts language to CN?

sure， nothing change....

**Comment by Bluefissure** [comment]
Do you mean text in trigger alerts or timeline?

IIRC the text in trigger alerts can be changed in the config panel, not sure about the timeline.

**Comment by Jaehyuk-Lee** [comment]
timeline is fixed to your game language, it wouldn't be changed since timeline mostly consists of skill names. You would see skill bar charging in game and same on timeline.
For Plugin UI language, I think it's possible to change, but I'm not doing it right now.

**Comment by FrankBlue453** [comment]
maybe we need some function to do it....

**Comment by Bluefissure** [comment]
> maybe we need some function to do it....

do what?

**Comment by quisquous** [comment]
I think you're looking for #1074

**Comment by quisquous** [comment]
If you're looking for timelines, #1247 will have fixed it.
