### ISSUE TITLE
Party Tank Shirk/Provoke/Invuln alerts not going off

### ISSUE THREAD

**Issue by AlexanderWan01** [quisquous/cactbot#1372]
When playing with a tank in your party, sometimes the alerts do not go off as expected

Expected results:
Tanks use Shirk/Provoke:
People that get alerts: All tanks (in party)

Tanks use Invuln abilities (Living Dead/Holmgang/Superbolide/Hallowed Ground):
People that get alerts: All tanks and healers (in party)

Recieved results:
DRK - Expected as above, however if you are
- also a DRK, you don't get Shirk/Provoke/LD alerts from the other DRK
- an AST doesn't recieve Living Dead notification

GNB - Expected as above, however if you are
- a DRK, you don't get alerts from the GNB
- a SCH, you don't get alerts from Superbolide

WAR - Expected as above, however if you are
- also a WAR, you DO get alerts from the other WAR (unlike DRK/GNB)
- a DRK/PLD, you don't get alerts from the GNB
- a WHM, you don't get alerts from Holmgang

PLD - Unfortunately I was not able to test with a PLD, so I don't know what happens

I was wondering if this was due to some form of check, to see if you are an appropiate class before being told about the alerts, and if so, some form of checkbox, to be told about everything regardless of class. Eg MNK being told about Living Dead, and/or Shirk.

**Comment by quisquous** [comment]
Is this related to #1153? This shouldn't be related to particular roles, I don't think, just whether you are a tank/healer, and if the person is in your party.

One thing to try, re: #1153, is to restart ACT and see if that fixes things.

**Comment by AlexanderWan01** [comment]
Yep, apparently there was an update to ACT, got that and from a glance, they seem to work as expected now.
