### ISSUE TITLE
Raidboss Timeline for O7S Bugged

### ISSUE THREAD

**Issue by nlachica** [quisquous/cactbot#138]
Hi, wasn't sure if someone let you know already but the callouts for O7S aren't working properly since the patch. First couple call outs are fine but mess up after the Dadaluma/Biblio monitors. 
Continues to call out the wrong Program Retrieval, etc...

**Comment by quisquous** [comment]
I think this is the same as issue #123.  Have you updated to https://github.com/ravahn/FFXIV_ACT_Plugin/releases/tag/v1.7.0.10?

**Comment by nlachica** [comment]
Ah, I feel dumb, I hadn't. It's fixed now, thanks a lot!
