### ISSUE TITLE
4.3 o7s triggers/timeline working incorrectly

### ISSUE THREAD

**Issue by torchick11** [quisquous/cactbot#139]
Say it starts as dadaluma, it will tell me its bibliotecha and cause multitude of issues

**Comment by quisquous** [comment]
This sounds the same as issue #138 and issue #123. Have you updated to https://github.com/ravahn/FFXIV_ACT_Plugin/releases/tag/v1.7.0.10?

**Comment by torchick11** [comment]
No I hadn't, I never know when there's an update because ACT just tells me there's an update 24/7

**Comment by quisquous** [comment]
Ok! I'll mark this as fixed, then.  Glad that was it!
