### ISSUE TITLE
radar: Bune mob in Ridorana Lighthouse incorrectly shows up as NM

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#1402]
`[15:12:03.177] 03:400011C6:Added new combatant Bune.  Job: N/A Level: 70 Max HP: 973250 Max MP: 10000 Pos: (-258.9914,-471.0002,430) (72580000009011).`

**Comment by VanSlanzar** [comment]
I did not pay attention, if this problem was solved, I would add this boss. Amdapor keep hard, i think in english game.
![Capture](https://user-images.githubusercontent.com/61565834/81989417-7945a400-963d-11ea-8c8c-38c34a0411b2.PNG)
