### ISSUE TITLE
python util/find_missing problem

### ISSUE THREAD

**Issue by VanSlanzar** [quisquous/cactbot#1419]
During my check, it is considered as missing (regex) for all language. Yet the line works. The check should be modified so that it considers these lines as translated.
![e1s 1](https://user-images.githubusercontent.com/61565834/81486454-335f9900-9255-11ea-86cd-a4e9f2b3a5a1.PNG)
![e1s 2](https://user-images.githubusercontent.com/61565834/81486456-38244d00-9255-11ea-92d0-2db32b19b4d3.PNG)

**Comment by quisquous** [comment]
Please see #1306 for more details on this error.

This means that you have translated the regex differently than what the `timelineReplace` section has it translated it as.  It's likely this effect name is missing from the `~effects` section.

**Comment by VanSlanzar** [comment]
I found the problem, it's a capital letter. Can I put (found) with the lower case? It's the real spelling.
![Capture](https://user-images.githubusercontent.com/61565834/81486719-09a77180-9257-11ea-933e-a439d8313137.PNG)
By doing this, it's good for checking.

**Comment by quisquous** [comment]
It's not the capital letter.  If you capitalize that, the test will still fail.

The effect name is missing from the `~effectNames` section.  Add it like this:
```diff
diff --git a/ui/raidboss/data/05-shb/raid/e1s.js b/ui/raidboss/data/05-shb/raid/e1s.js
index 89f2bd22..40381bc7 100644
--- a/ui/raidboss/data/05-shb/raid/e1s.js
+++ b/ui/raidboss/data/05-shb/raid/e1s.js
@@ -594,6 +594,7 @@
         'Healing Magic Down': 'Malus de soin',
         'Fetters': 'Attache',
         'Bleeding': 'Saignement',
+        'Paradise Regained': 'Paradis retrouvé',
       },
     },
     {
```

**Comment by VanSlanzar** [comment]
- effect name added. check is ok. 
- Should I modify this ?i don't see this line. Sorry for the inconvénience and my questions.
![Capture](https://user-images.githubusercontent.com/61565834/81486988-7de31480-9259-11ea-8a10-a4ae8f24e5f9.PNG)

**Comment by quisquous** [comment]
Sorry for the confusion, this is https://en.wikipedia.org/wiki/Diff#Unified_format.  It just tells you which files have been modified.  It is the kind of thing you see when you modify a file and then type `git diff`.

**Comment by VanSlanzar** [comment]
OK, thank you.
