### ISSUE TITLE
fisher: Korean data

### ISSUE THREAD

**Issue by Jaehyuk-Lee** [quisquous/cactbot#1435]
## Summary

I think reading `cn` data's keys (4776, 4869, 4870, 4871, ...)
https://github.com/quisquous/cactbot/blob/e27c33a34f69e5ba53ac4937e7a9468b57d78f29/ui/fisher/static-data.js#L8-L12
 and read data which matches those keys from [https://raw.githubusercontent.com/Ra-Workspace/ffxiv-datamining-ko/master/csv/Item.csv](https://raw.githubusercontent.com/Ra-Workspace/ffxiv-datamining-ko/master/csv/Item.csv) can solve Korean data extraction.
Like, 
```
4776,"말름미역",
4869,"멜토르 망둥이",
4870,"로민사 멸치",
4871,"손가락새우",
```

For place names, [https://raw.githubusercontent.com/Ra-Workspace/ffxiv-datamining-ko/master/csv/PlaceName.csv](https://raw.githubusercontent.com/Ra-Workspace/ffxiv-datamining-ko/master/csv/PlaceName.csv)

Tackle uses same csv as fish data. (Item.csv)

If there's no matching key, skip it. (It's because of patch version differences.)

## SaintCoinach problem for me

I made some logic in my head, but I couldn't develop it.
I did success reading that csv file, but having problem with SaintCoinach and cannot test and debug now.

`subprocess.CalledProcessError: Command 'C:\SaintCoinach\SaintCoinach.Cmd.exe "C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn" "lang de" "exd PlaceName"' returned non-zero exit status 3762504530.`
Am I only having this problem? I have latest patches. (SaintCoianch and FFXIV)

**Comment by Jaehyuk-Lee** [comment]
This is what I've added Korean translation for fisher.js.
[static-data.zip](https://github.com/quisquous/cactbot/files/4638118/static-data.zip)

I did this with javascript by myself, using browser console. (dealing with json object.)
So, I cannot make changes to python program.

**Comment by quisquous** [comment]
I would recommend not using SaintCoinach here (because then I can't update this, because I don't have the Korean version).  I have also had a lot of errors with SaintCoinach in the past.

What about doing something like what `gen_hunt_data.py` does, with `update_raw_csv`, where it gets the csv from `Ra-Workspace/ffxiv-datamining-ko/master/csv/`.  It will probably take a little bit of refactoring to make this all work, since everything else is using xivapi-like things, but that would be the way I would recommend.

**Comment by Jaehyuk-Lee** [comment]
I mean, I was not trying to get data for Korean from SaintCoinach, I meant I couldn't run original python program which makes international version data, it returns error to me.

**Comment by quisquous** [comment]
Does SaintCoinach work if you call it outside of Python?

Maybe I need to think about replacing the use of SaintCoinach with downloading csv or ffxivapi.  That seems more reliable for everybody, especially with different versions.

**Comment by Jaehyuk-Lee** [comment]
It is perfectly a problem with SaintCoinach executable. I have same error with running it own, not calling from other program.
I have latest SaintCoinach but don't know why.
