### ISSUE TITLE
Util: Error in make_timeline when creating timeline from FFLogs

### ISSUE THREAD

**Issue by JLGarber** [quisquous/cactbot#1456]
When attempting to create a timeline from an FFLogs report, the script fails due to lack of support for the `line_type` property on each entry.

```
python make_timeline.py -k [KEY] -r kvPbqZXchD7njwTV -rf 3
Traceback (most recent call last):
  File "make_timeline.py", line 400, in <module>
    print("\n".join(main(args)))
  File "make_timeline.py", line 201, in main
    if entry["line_type"] in ["21", "22"]:
KeyError: 'line_type'
```

This arises because I completely overlooked the FFLogs support when updating the script to allow for `targetable/untargetable` lines.

For my personal use, I just hardcoded all lines from FFLogs as being `21`, but I wonder whether it might be better to do something like
`if not entry["line_type"] or entry["line_type"] in ["21", "22"]`

The alternative would be to map from the `type` property in each FFLogs entry:

```
{ 
  'timestamp': 8794602,
  'type': 'cast',
  'sourceID': 2,
  'sourceIsFriendly': False,
  'targetID': 6,
  'targetIsFriendly': True,
  'ability': {
    'name': 'attack',
    'guid': 5092,
    'type': 1,
    'abilityIcon': '000000-000405.png'
  },
  'pin': '0' 
}
```

(Although I'm not sure whether anything other than 21/22 lines would be represented here anyway.)

**Comment by quisquous** [comment]
I could go either way.  Maybe it's worth adding a line_type for everything.  Or maybe things with a line_type should map to type, since that's more readable?

I think this kind of bug is what I meant a little when I said things felt fragile.  (And this is not to assign blame, just wondering how this code could be improved, you know?)

**Comment by JLGarber** [comment]
Yeah, I know it's not a great situation. I'm honestly not sure how we would improve things though from that standpoint. Whatever we do would have to translate FFLogs <--> network log, since Kihra transforms everything for their own use.

I'd like to say "let's just punt this for now". The thing about "doing it right" is that the list of potential future additions really is limited. For `test_timeline` there's a whole bunch of stuff that should be addressed, but for auto-generation... I just can't see expending much effort to "properly fix" something that's only going to come up again once more.

I don't know. I'm not trying to sound super dismissive here! I think as far as here-and-now solutions, we're probably best off doing your second suggestion, mapping each line number in the network log to `type` as expected from FFlogs. Even though in practice we don't use that feature much, it's worth ensuring it functions and is readable.
