### ISSUE TITLE
Raidboss: Netregexes and names--Ability/Effect names should be indicated somewhere

### ISSUE THREAD

**Issue by JLGarber** [quisquous/cactbot#1460]
panicstevenson [noted](https://github.com/quisquous/cactbot/pull/1458#discussion_r429465012) that we can lose context more easily when we are using bare ability/effect IDs. That is, we have no way of knowing what these lines are, really:

`regex: NetRegexes.ability({ id: '156F', source: 'Sephirot', capture: false }),`
`regex: NetRegexes.gainsEffect({ id: ['3ED', '3EE'], source: 'Sephirot' }),`

The first is Ein Sof, the green puddles, and the second is Force Against Magic/Might, but without context, such as descriptive trigger names, we don't know that.

Currently, the `raidboss` doc has this to say about the trigger ID:

> An id string for the trigger, used to disable triggers. Every built-in trigger that has a text/sound output should have an id so it can be disabled. User-defined triggers need not have one.

I would propose adding to it so that it reads something like this:

> An id string for the trigger, used to disable triggers. Every built-in trigger that has a text/sound output should have an id so it can be disabled. User-defined triggers need not have one.

> Because the current structure for `Regexes/NetRegexes` no longer requires that the ability/effect/whatever name be present as part of the expression, it is extremely important that that information is somewhere alongside. Recommended practice is either to have the effect/ability/NPC name in the trigger ID itself, or in an explanatory comment alongside. Context solely from the trigger body is not necessarily sufficient!

I haven't seen this as being a big problem, necessarily, since most of us are already careful to give triggers descriptive IDs. However, I feel like it should be In The Documentation Somewhere. We lose nothing by making descriptive IDs/comments a standard, and we potentially gain from it.

**Comment by quisquous** [comment]
Sounds great.  Do you want to send a pull request, or should I?

**Comment by JLGarber** [comment]
I’ll do it, I was planning to. I just thought this might be something to ask for discussion instead of “sup, here’s this pull request that reflects *my* vision of how things should be”.

**Comment by quisquous** [comment]
Fair! I think I see pull requests as a conversation as well, but this also feels non-controversial to me, for what it's worth.  It's documenting what we're already doing as a guide for other authors, rather than making a new decision.
