### ISSUE TITLE
What is language options use for?

### ISSUE THREAD

**Issue by MaikoTan** [quisquous/cactbot#1461]
## Question

As the title shows, I am a little confused with "Display Language", "Parser Language" and "PC Locale" which are defined in #1400 . 
I can only see the new "Display Language" is used in module oopsyraidsy to "display" the mistakes.
But as the name, I am confused why doesn't it "display" the UI configurations in the specified language. ( I found that UI language is set by PC Locale in code though. )

#### Edit:
https://github.com/quisquous/cactbot/blob/9614a7ff359230803fa59095963af1c41310d6dc/ui/config/config.js#L58
When I change it as `this.lang = configOptions.DisplayLanguage || configOptions.ShortLocale;`, it shows Japanese in cactbot configurations.

**So I have several questions about these options:**
+ Does cactbot use "Parser Language" specified regex to parse GameLog from ACT (Game Client?) ? If true, can we directly obtain the language setting that FFXIV game using? So that even "Parser Language" is not the same with "Game Language", cactbot would work as usual while matching GameLog.
+ What is "PC Locale" used for, except the configurations displaying? Is it really possible that cactbot cannot get the language setting of FFXIV_ACT_Plugin?
+ As above, could "Display Language" use for display configurations? Or may provide other option like "UI Language" to control this feature?
+ How can I use en in-game but use ja as parser language, while cactbot would work normally.

## Languages in My Environment
It is a little strange in my OS Environment, for some reason I always use English as my primary working language, but while playing FFXIV in jp region, I shall use Japanese term so that I can communicate with other players.

So languages settings on my PC would be:

OS Locale: en-US
FFXIV: International version, usually `en` ( so I can learn English even while gaming ). But sometimes when I want to deeply understand the main story, I set it as `ja`, because I am more familiar with Japanese instead of English.
FFXIV_ACT_Plugin: `ja` when I want to upload my logs to [FF Logs](https://www.fflogs.com/)
cactbot: always set "Timeline Language" and "Alert Language" as `ja`.

------
@Jaehyuk-Lee Sorry for disturbing, but can you explain the meaning of these options?

**Comment by Jaehyuk-Lee** [comment]
Display Language: language which user wants to see, overrides parser language.
Parser Language: parser's language

* priority
TimelineLanguage > ParserLanguage > English
(AlertLanguage > )DisplayLanguage > ParserLanguage > English

So, if you're familiar with Japanese, cactbot will show you most things in Japanese if you select Japanese for display language. Even though you select English in Parser setting.

**Comment by MaikoTan** [comment]
>priority
TimelineLanguage > ParserLanguage > English
(AlertLanguage > )DisplayLanguage > ParserLanguage > English
So, if you're familiar with Japanese, cactbot will show you most things in Japanese if you select Japanese for display language. Even though you select English in Parser setting.

>"Display language" is translated to Korean as "Main language". "주 사용 언어(主 使用 言語)" in Korean hanja.

I see. ( Hanja helps me a lot haha ) So even I set the default value in "Alert Language" and "Timeline Language", only if I set "Display Language" as Japanese, those two would be Japanese too.
It seems that the Japanese option string has not updated after your change. I may take time to deal with them later.

>There's no usage with PC Locale except configurations. I don't think cactbot cannot get language setting of FFXIV_ACT_Plugin, but this change was originally made to show configuration page with PC's language.

Yeah, then, by the way, I think I'm a little weirdo on these things (´。＿。｀) .
For some reason so I have to use US-en as my PC Locale, but I am more comfortable with Japanese or Chinese. So if you can provide an option like "UI Language", or just use "Display Language" as configurations displaying ( just like the code I wrote above? ), I'll be appreciated about it.

>Does that work? I thought parser language and game client language should be same. I mean I thought parser totally does not work with different language setting.

No, it doesn't work. When I set the different language between game client and parser, cactbot would not work. But I want it to work.
However, By your information, I can only set the same language settings in-game and parser. Every time I change my language setting in-game, I should change it in parser too?

>If this is possible, there can be added "Game client language" option on cactbot configuration, and overrides Parser Language, which are not overrided by Display language, with Game client language.

Well, as described above. It is not bad if there is a "Game client language" option, but that would make other users confused, like: "Why are there so many options about languages?".
Plus, by adding this option, most regex pipeline code mechanics of raidboss, oopsyraidsy and jobs should be re-wrote a lot.
I don't think there are few people like me using different language in game client against parser, and even change it eventually. So this option might not a good idea.

**Comment by Jaehyuk-Lee** [comment]
TimelineLanguage and AlertsLanguage have higher priority than anything. So, you can set AlertsLanguage "English" and Display Language "Japanese", shows English for Alerts and Japanese for other things.

I made configuration page language to PC's locale, because I think user uses their PC's locale at least they understand it. -> This was my first thought.
I made Display language option after that. This can replace the PC's locale, but I believe I had some problem with it.
I am busy these days and I think I cannot contribute here before university summer vacation.

I mean I know cactbot don't work with different language setting between parser and client, but I thought parsing is broken for everything with different language setting. If this work we can add "Game Language" setting, as I said before.
> If this is possible, there can be added "Game client language" option on cactbot configuration, and overrides Parser Language, which are not overrided by Display language, with Game client language.
##
> Well, as described above. It is not bad if there is a "Game client language" option, but that would make other users confused, like: "Why are there so many options about languages?".

hmmm without this, you cannot use cactbot with different parser language from game client.

**Comment by quisquous** [comment]
>>When I change it as this.lang = configOptions.DisplayLanguage || configOptions.ShortLocale;, it shows Japanese in cactbot configurations.
>
> ah, yes yes. This change would be better.

:+1:

> However, By your information, It seems like I can only set the same language settings in-game and parser. Every time I change my language setting in-game, I should change it in parser too?

Yes, that is my understanding.

> No, it doesn't work. When I set the different language between game client and parser, cactbot would not work. But I want it to work.

Can you help me try to understand why?

I do not understand the difference you are trying to make between "parser language" and "game client language".  The "parser language" value comes from the Plugins -> FFXIV Settings -> Options -> Game Language field.  These to me are the same thing.  "parser language" and "game client language" are both "what language do I need to write regular expressions against to match logs from the game".  "display language" is "what does the user of cactbot want their UI to appear as".

I think in your use case, you want to set FFXIV's game language to English (because you're playing in English) but cactbot's display language to Japanese.  This sort of use case was precisely the goal of having a separate display language option.

**Comment by MaikoTan** [comment]
> > No, it doesn't work. When I set the different language between game client and parser, cactbot would not work. But I want it to work.
> 
> Can you help me try to understand why?

Sorry, my misunderstanding! I thought that Lee was talking about cactbot would work or not!

Well, parser would work as usual even with different language settings against game client.
For example, in my case, I set game language as `en`, but parser language is `ja`.
Parser would translate most of localized string in-game into Japanese, like skill name, buff name, zone name and so on.
However, type `00 GameLog` would remain in English, since it is directly extract from game.
So some plugin like cactbot, try to match LogLine with regex written in Japanese would not work. i.e, regex like `Countdown`, `CancelCountdown`,`ZoneSeal` and so on.

> I do not understand the difference you are trying to make between "parser language" and "game client language".  The "parser language" value comes from the Plugins -> FFXIV Settings -> Options -> Game Language field.  These to me are the same thing.  "parser language" and "game client language" are both "what language do I need to write regular expressions against to match logs from the game".  "display language" is "what does the user of cactbot want their UI to appear as".

In fact, I just often forgot to change my parser language as well after I change my game language.
I know literally it should be the same between game language and parser.
But ACT works normally even with different language settings.
Maybe this is just my own problem, since I can set it the same, so never mind.

> I think in your use case, you want to set FFXIV's game language to English (because you're playing in English) but cactbot's display language to Japanese.  This sort of use case was precisely the goal of having a separate display language option.

Yes, yes.
At the first time, I was confused with those language because the option text in Japanese have not updated after Lee's commit. So I ask what are these languages use for.
But now it is clear to me since Lee's explanation was easy to understand.

**Comment by MaikoTan** [comment]
Close 'cause no more questions. ( •̀ ω •́ )✧
