### ISSUE TITLE
after updating 7.1 my timeline isnt showing

### ISSUE THREAD

**Issue by monkeyzealer** [quisquous/cactbot#148]
for some reason after updated to 7.1 my timeline for raidboss is now not showing i see the alert text but not the timeline

**Comment by quisquous** [comment]
Timelines for which zone?

If you teleport to Summerford Farms and do a /countdown, does the test timeline start?

**Comment by monkeyzealer** [comment]
it started working today now my act just doesnt parse

**Comment by jeandaaark** [comment]
hello, when i updated today to 7.1 i recieved such error :
2018-06-05 13:59:46: Error: LoadAddons: C:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin\addons\CactbotOverlay.dll: System.IO.FileLoadException: Nie można załadować pliku lub zestawu 'file:///C:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin\addons\CactbotOverlay.dll' lub jednej z jego zależności. Operacja nie jest obsługiwana. (Wyjątek od HRESULT: 0x80131515)

can somebody help:(

**Comment by quisquous** [comment]
That sounds like a firewall / running as administrator issue in ACT.  It sounds like cactbot is working though, yeah?

**Comment by IrealiTY** [comment]
UwU timeline seems not to load here:
![image](https://user-images.githubusercontent.com/1223686/41037775-9211908e-6994-11e8-998b-7020ecabaafe.png)

**Comment by quisquous** [comment]
Hmm.  If you unlock your overlay, does the test text show correctly? Is the zone Unknown Zone (309)? Are there any errors when running?

I heard some reports that this worked for some folks but not others (but then eventually worked for them).  I wonder if github pages are rate limiting or something.

**Comment by IrealiTY** [comment]
It suddenly started working again, nothing was changed on my side, no errors before that either.
