### ISSUE TITLE
util: make_timeline issues on ucob golden phase

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#1498]
Pulls 7/8 and 9/10 split across golden bahamut even though they are the same pull.

[Network_20190328.zip](https://github.com/quisquous/cactbot/files/4809859/Network_20190328.zip)

(cc @JLGarber)

**Comment by JLGarber** [comment]
Welp. That's because "The limit gauge resets" is one of the "combat is over" flags.  I'll have to rummage through my old logs and see whether there's anything else we can use for splitting encounters similar to Stormblood tier finals. Fortunately, I think even if not, we can just safely remove that particular check.

**Comment by JLGarber** [comment]
Alright, after a bit of log trawling, I can't find anything consistent that accompanies a limit reset. The only thing I found was that Kefka appears to send `80000009` as an actor control during his fight transition. Other than that, the only commonality was the music change, and of course we can't use that.

Given that Square *probably* won't be implementing many checkpoint bosses, and given that the community is fairly set on deliberately resetting between any phases, I think it's safe to just remove that check and do the manual work necessary in the 1% of cases where it would actually be used.

**Comment by quisquous** [comment]
Yeah, I think considering them "the same pull" seems fine for the purposes of `-lf`.  If somebody went through and did a real pull after a checkpoint, I think the timeline should still work just fine for both make (because of `-p`) and test purposes.
