### ISSUE TITLE
Locales with a comma as decimal place don't work - ie 20,00 instead of 20.00

### ISSUE THREAD

**Issue by Darthbeiber** [quisquous/cactbot#15]
HI idk why icons, cds, pots etc are not displayed ...
everything else works well, life bar, special rdm bar,

ty and great job.

**Comment by danakj** [comment]
What job are you on when that is the case?

What's your character's name? (Is there non-ascii characters?) You can scramble the name or something if you're worried about anonymity, just wondering how to reproduce it.

**Comment by Darthbeiber** [comment]
in all jobs, life/tp/mana bars work well and only icon not work
 Misko Jhones is my character name

**Comment by danakj** [comment]
Hm, probably not a name problem then. Is there anything interesting in the OverlayPlugin tab's log?

**Comment by Darthbeiber** [comment]
When I get home, I'll take screenshots of my config, etc ...

**Comment by danakj** [comment]
I had a thought. Cactbot uses the network log triggers for everything from the FFXIV plugin - since they are more reliable and quicker, with more info. That means if you have network parsing disabled that things like the potions and such will break.

The HP/mana bars come memory directly so they don't depend on that.

Make sure in the FFXIV plugin settings that "Disable Parsing from Network Data" is not checked.

**Comment by Darthbeiber** [comment]
me ffxiv settings https://gyazo.com/585609d44c0fdaf914503f1c9f18b1fa FFxiv not found in automitic for me, i need swich me process, disable all addons exceppt ffxiv and put on all addons, al all work except buffs
me overplugin https://gyazo.com/21afb44099ea28f9328c7be3c40b321b
plugins https://gyazo.com/7b71b9ce2a11be563848b8cd08188a13

**Comment by Darthbeiber** [comment]
https://gyazo.com/886de2ab9c5636b28d28a9e93b3a0b82 probably not automatic process is the problem

**Comment by Darthbeiber** [comment]
https://gyazo.com/095b45c0b317b2e8770eb72fcbf776e4 the rpoblem i think

**Comment by danakj** [comment]
Hm, ok let me try to translate those. If that error is that it can't find FFXIV_ACT_Plugin.dll, then https://github.com/quisquous/cactbot#potential-errors-and-workarounds has a suggestion.

**Comment by danakj** [comment]
Oh, I think it's this one:

If you get an overlay plugin error similar to Error: (overlay): Exception in SendFastRateEvents: Could not load file or assembly 'FFXIV_ACT_Plugin, Version=(version), Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified. then you likely need to unblock the ffxiv plugin. See the instructions above for unblocking DLLs.

**Comment by Darthbeiber** [comment]
i make a new full install, and the same problem. now act dont have any problem.

**Comment by danakj** [comment]
> i make a new full install, and the same problem. now act dont have any problem.

I'm not sure what you mean there, the problem went away so it's all good? Or it changed?

Did you unblock the FFXIV_ACT_Plugin.dll?

**Comment by Darthbeiber** [comment]
it still does not show the icons, but now I have unlocked all the files, and the ffxiv and overplugin do not give any faults

**Comment by danakj** [comment]
Can you:
1. start combat a striking dummy
2. activate RDM embolden
3. go back to act and click "End Encounter"
4. right click on the encounter with the dummy
5. go to "View Logs"
6. click "Copy All" button in top right
7. come back here and paste what you copied here?

**Comment by Darthbeiber** [comment]
[04:00:48.110] 15:1072E940:Darth Beiber:1D64:Jolt II:40000EF3:Striking Dummy:750203:197A:3033A:8000BA:10:800557:1C:801D64:0:0:0:0:0:0:0:0:159353:165452:0:0:1000:1000:-834,4091:-607,7821:13,5907:30848:30848:14400:14400:1000:1000:-827,2372:-598,3194:11,6:
[04:00:48.110] FC:
[04:00:48.110] FC:
[04:00:48.110] 1A:Darth Beiber gains the effect of Dualcast from Darth Beiber for 15,00 Seconds.
[04:00:48.110] FC:
[04:00:48.110] FC:
[04:00:48.110] 1F:1072E940:Darth Beiber:30323:00:6200:5D01
[04:00:47.000] 00:08ae:You gain the effect of Dualcast.
[04:00:48.747] 0D:Striking Dummy HP at 99%.
[04:00:48.747] 0D:Striking Dummy HP at 98%.
[04:00:48.747] 0D:Striking Dummy HP at 97%.
[04:00:48.747] 0D:Striking Dummy HP at 96%.
[04:00:48.953] FC:
[04:00:48.953] FC:
[04:00:48.953] FC:
[04:00:48.953] FC:
[04:00:48.953] 1A:Darth Beiber gains the effect of Impactful from Darth Beiber for 30,00 Seconds.
[04:00:48.953] FC:
[04:00:48.953] FC:
[04:00:48.953] FC:
[04:00:48.953] FC:
[04:00:48.953] FC:
[04:00:48.953] FC:
[04:00:48.000] 00:082b:You cast Jolt II.
[04:00:48.000] 00:0aa9:⇒ Direct hit! The striking dummy takes 6522 damage.
[04:00:48.000] 00:08ae:⇒ You gain the effect of Impactful.
[04:00:49.979] FC:
[04:00:49.979] FC:
[04:00:49.979] 15:1072E940:Darth Beiber:1D60:Embolden:1072E940:Darth Beiber:500020F:4D7:0:0:0:0:0:0:0:0:0:0:0:0:0:0:30848:30848:14040:14400:1000:1000:-827,2372:-598,3194:11,6:30848:30848:14040:14400:1000:1000:-827,2372:-598,3194:11,6:
[04:00:50.187] FC:
[04:00:50.000] 00:082b:You use Embolden.
[04:00:50.000] 00:08ae:⇒ You gain the effect of Embolden.
[04:00:50.811] FC:
[04:00:50.811] 1A:Darth Beiber gains the effect of Embolden from Darth Beiber for 20,00 Seconds. (5)
[04:00:50.812] FC:
[04:00:50.812] FC:

**Comment by danakj** [comment]
Ooh I see!

It says "20,00 Seconds" instead of "20.00 Seconds" like it would for me. Thanks! We'll have to go through and make sure all the checks we do for numbers support both formats.

**Comment by Darthbeiber** [comment]
and any solution for fast fix?

**Comment by danakj** [comment]
If you go through jobs.js and change things that look something like [0-9.]+ to be [0-9.,]+ then I expect it to work for that module.

Would have to do the same with all the triggers for the raidboss module to work, though.

**Comment by danakj** [comment]
However that will not be perfect. According to https://stackoverflow.com/questions/7571553/javascript-parse-float-is-ignoring-the-decimals-after-my-comma the commas will not parse correctly, so we'll have to convert them to periods before doing parseFloat(). That will be harder for you to do one-off, but most things are actually whole numbers so you probably won't notice it for now. If things feel off by a second, then that is why.

**Comment by Darthbeiber** [comment]
I have modified the jobs.js file with the changes you have posted, now the procs of the jobs are working, but the buffos are still not working.

**Comment by Darthbeiber** [comment]
in what directory should the buff icons be?

**Comment by danakj** [comment]
The icon images are in ui/jobs/jobs-icons.js, they are saved as js strings.

Do the boxes appear but the icons are not there, or nothing appears at all, or something else?

**Comment by danakj** [comment]
And did you get the lines like this?

      gainRegex: new RegExp(':' + me + ' gains the effect of Embolden from \\y{Name} for ([0-9.]+) Seconds'),

That's the one for Embolden for example.

**Comment by danakj** [comment]
https://github.com/quisquous/cactbot/commit/5269d55a0c73c73f426c4623ef8280f565c6395d should fix this more robustly for the next release.

**Comment by Darthbeiber** [comment]
yeahhhhhhhhhhhhhhhh finally work https://gyazo.com/394961bb880f3af4f07a3cf8893b438f ty dude.

I remplace all [0-9.]+ for [0-9.,]+
 i remplace gainRegex: new RegExp(':' + me + ' gains the effect of Embolden from \\y{Name} for ([0-9.]+) Seconds'),

and all work .

if anyone have the same problem y can upload me jobs.js


ty for all, <3

**Comment by Darthbeiber** [comment]
bbut now, i know your code and probably make a good ui for ninja

**Comment by danakj** [comment]
Awesome! Thanks for helping me fix it. Will be cool to see a Ninja UI!

If event.detail.jobDetail is missing anything you can take a look at the event.detail.debugJob which has all the bytes for job info in raw format. If you figure out what bytes are set to to describe what job states, then we can change the FFXIVMemory.cs to pull that data out into jobDetail to give it to the JavaScript nicely. I don't have a 70 nin so couldn't do this myself yet.

The ui/test/cactbot_test.html ui shows this debugJob string too so you can observe it and record what it does.
