### ISSUE TITLE
Nael Quotes don't show what to do on screen. 

### ISSUE THREAD

**Issue by Rietty** [quisquous/cactbot#1503]
Like the title says, I've been trying to use the Nael quotes to just show on screen what the mechanic is, but for some reason no matter how I configure it, the quotes never result in any text being show on screen for what mechanic is happening.

**Comment by quisquous** [comment]
Can you show me what your raidboss config looks like (both the general config and the specific nael quote config)?

Also, do you have a `user/raidboss.js` file?

**Comment by Rietty** [comment]
I do not have a `user/raidboss.js` file. 

This is the general config:
![image](https://user-images.githubusercontent.com/35241556/85236918-5357b000-b3f0-11ea-84f1-4998672842cd.png)

This is the Nael config:
![image](https://user-images.githubusercontent.com/35241556/85236928-610d3580-b3f0-11ea-9eda-040f5d347854.png)

**Comment by quisquous** [comment]
Do you get any text or sounds on screen? Can you should me wait your raidboss url is on the overlay config panel?

**Comment by Rietty** [comment]
Yes, I do get Texts/Sounds for stuff like Twisters, Thunder, other mechanics/other fights. Just specifically Nael quotes don't show any text. 
```
file:///C:/Users/Rietty/Documents/Tools/FFXIV/Cactbot/ui/raidboss/raidboss.html
``` is what I have as URL

**Comment by quisquous** [comment]
Oh, I see! This means it is almost certainly due to one of two things:
(1) You have "hide chat log for privacy" turned on (see this [fisher instructions](https://github.com/quisquous/cactbot/blob/master/docs/FAQ-Troubleshooting.md#fisher-module))
(2) You don't have any chat log in game that shows NPC dialog.  In general, I recommend having one chat window that just has everything turned on that you never look at.

**Comment by Rietty** [comment]
I enabled it now! I'll make sure it works and then close out the issue tomorrow if that was it. Thanks!

**Comment by quisquous** [comment]
(Sorry, just to be clear, you should have "hide chat log for privacy" *unenabled* and "NPC Dialogue" in your in-game log filters *enabled*.)
