### ISSUE TITLE
oopsy: Add job specific oopsy triggers

### ISSUE THREAD

**Issue by liaoarden** [quisquous/cactbot#1506]
## Summary

Add in job specific oopsyraidsy triggers to get a more real time sense of how you're playing.

Initial examples off the top of my head:
- Counting SF/WW in demi windows for SMN
- Counting GCDs in a Hypercharge window MCH

**Comment by liaoarden** [comment]
I've got hypercharge GCDs working, and a rudimentary SF/WW tracker working as well.

I'm going to see if I can get the combatant stuff to also work so that colliding SF/WWs from other SMNs don't get counted incorrectly.

**Comment by liaoarden** [comment]
@quisquous sorry been swamped with work but not sure if this is necessary anymore. Will look at what's now in jobs and close this out if jobs now manages this.

Otherwise, I might push out the hypercharge change for review. The SF/WW tracker seems to work on Dummies but falls apart in actual instances for some reason.

**Comment by quisquous** [comment]
Very belatedly, I have some local "positional" oopsy triggers, but they're a lot of work to maintain and I don't want to commit to doing that for everything for all time.

I think if somebody is interested in job-specific oopsy and wants to contribute that work I'm happy to take it, but I don't have time to maintain it over time, so am going to close this.
