### ISSUE TITLE
parser language is set to English

### ISSUE THREAD

**Issue by Jaehyuk-Lee** [quisquous/cactbot#1509]
default language was intended to match FFXIV plugin language, but it's set to English. I don't have computer to check this now, but I see many complaints about why cactbot is shown in English after update.
I'll check this after I go home.

**Comment by Jaehyuk-Lee** [comment]
This issue happens with these condition

* clean first install of cactbot (remove ACT and re-install)
* update from 0.17.2 to 0.18.0

This does not happen after you select specific language and then, select "Use FFXIV Plugin Langauage".

**Comment by Jaehyuk-Lee** [comment]
I think default setting is not set to 'default', I guess it's "null".

**Comment by Jaehyuk-Lee** [comment]
parser language set to Korean
![K-002](https://user-images.githubusercontent.com/4695371/85433718-d11de600-b5bf-11ea-9680-edd2c780cf03.png)

but it's shown in English
![K-001](https://user-images.githubusercontent.com/4695371/85433754-de3ad500-b5bf-11ea-977b-aaad6643c152.png)

**Comment by quisquous** [comment]
Is this causing a lot of people a problem, such that it would be helpful to do another release soon?

**Comment by Jaehyuk-Lee** [comment]
@quisquous ummm... this differ by amount of users who does not uses English. But, it can be solved with manual language setting, but only some people got it.
Korean users are getting my own release version with HAERUBOT which is used to maintain ACT plugins for Korean server. (If I [release](https://github.com/Jaehyuk-Lee/cactbot/releases) a new version, HAERUBOT users get updates.) I've been releasing my own release for Korean server because original(quisquous) cactbot release is focused on intl version users.

So, only concern is for Chinese / Japanese / French / German users.
I don't know user amount of these users, so I actually don't know. It's okay to not release a new version for Korean users.
