### ISSUE TITLE
UwU prep link is full of spam?

### ISSUE THREAD

**Issue by j78FG86l69VA58U** [quisquous/cactbot#151]
https://github.com/quisquous/cactbot/releases/tag/v0.7.1
Says we should use the url below for the uwu prep but that html file is chock full of spam banners?

https://quisquous.github.io/cactbot/ui/raidboss/raidboss.html
https://i.imgur.com/lqzI4cc.png

**Comment by quisquous** [comment]
Looks like your browser or your ISP is injecting spam.  That block of ads is not in the file.

**Comment by j78FG86l69VA58U** [comment]
aight fair enuf fella, i'll have a look
