### ISSUE TITLE
Can I use Cactbot to avoid boss(low level dungeons) attacks?

### ISSUE THREAD

**Issue by HbergonZ** [quisquous/cactbot#1524]
Hello everyone! I recently installed the ACT and Cactbot, but i'm new in game and I would like to know if i can use Cactbot in low level dungeons, just to study the bosses.  Besides that i want to know if i can change the Warnings Messages to my own warning messages because i understand in english, but how i speak in portuguese, i think that is better to me use my own messages :P

**Comment by quisquous** [comment]
Timeline and trigger support for low level dungeons is very sparse.  The last expansion's dungeons are all covered, but very few dungeons before that are.  Patches are welcome to add timelines and triggers for them, but you should not expect them to be there.

If you want to customize triggers, it's a little bit involved. 
 This will give you some steps: https://github.com/quisquous/cactbot/blob/master/docs/AdvancedCactbot.md#per-trigger-options

**Comment by HbergonZ** [comment]
> Timeline and trigger support for low level dungeons is very sparse. The last expansion's dungeons are all covered, but very few dungeons before that are. Patches are welcome to add timelines and triggers for them, but you should not expect them to be there.
> 
> If you want to customize triggers, it's a little bit involved.
> This will give you some steps: https://github.com/quisquous/cactbot/blob/master/docs/AdvancedCactbot.md#per-trigger-options


Oh, sad. Well, thank you for answer! Anyway it is a great tool that you have developed, congratulations for that.

Do you have any list that will show me what are the bosses that the Cactbot works? Only if it’s easy there, it would help me organize myself.

**Comment by quisquous** [comment]
The easiest way to see is to look in the [cactbot config](https://github.com/quisquous/cactbot#cactbot-customization) and see which entries are listed under raidboss.  Most of the time if there's something listed there, that means it's supported.

**Comment by HbergonZ** [comment]
Well, I found it, I guess...but I'm not that familiar with that language. If I translated the phrases for you, can you make changes and send to me the new code and where i need put it? If not, maybe if you direct me what i need to edit and what i need to use, helps too. I don't work with programming language but i can learn and understand quickly :)

**Comment by quisquous** [comment]
Sorry, this is not something that I can do for you.

https://github.com/quisquous/cactbot/blob/master/docs/AdvancedCactbot.md#per-trigger-options is the documentation to customize and write your own triggers.

**Comment by quisquous** [comment]
It sounds like there's maybe nothing else to be done here.  If you have any further questions, feel free to open new issues or ask on the ACT FFXIV discord.
