### ISSUE TITLE
baldesion arsenal

### ISSUE THREAD

**Issue by Tsunayoshi** [quisquous/cactbot#1571]
I noticed that cactbot get stuck on art/orwain.
i dont have any timelines in BA, i get calls to not move while we already done with the boss (like its not notice the kill of art and orwain.
and i have not a single call or timeline for the rest of the run. all other savages/ex working fine.

is that a know problem?

i added some normal triggers for the basic stuff, but i would like to have at least the timelines back. its rly helpful for shieldhealers

Update: i checked on the run after again now. first boss have timeline and calls. after that it never ends the boss. this time i didnt restart act and i get ramdomly timers even on the support fate rooms without beeing infight. or getting voice messages like eureka potions there (still not infight)

Update2: a restart of act before AV did nothing. no timeline and no calls for AV and Ozma

To Test: I asked months ago on the discord, if cactbot need battle log. i got a no. I will test it with full battle log again today...
=> Checked it now. no Timeline no Callout even with full Battlechat

**Comment by youranfu** [comment]
I have exactly the same problem. I also did all the tests mentioned by Tsunayoshi and had the same results.

**Comment by quisquous** [comment]
> I noticed that cactbot get stuck on art/orwain.
> i dont have any timelines in BA, i get calls to not move while we already done with the boss (like its not notice the kill of art and orwain.
> and i have not a single call or timeline for the rest of the run. all other savages/ex working fine.
> 
> is that a know problem?

No, this is not a known problem.

In the cactbot config, if you turn on `Show developer options` and then also click `Enable debug mode` for raidboss, this will add a timer on screen for the current timeline time.  I'm assuming this time will stay on screen after ending Art or Owain? It should disappear when the timeline resets, and it should reset when the zone is unsealed.

Are you playing in English?

> To Test: I asked months ago on the discord, if cactbot need battle log. i got a no. I will test it with full battle log again today...
> => Checked it now. no Timeline no Callout even with full Battlechat

Do you have the ACT setting `Hide Chat Log (for privacy)` enabled?

If you import your log into ACT and view the logs, are there any lines that look like `00:0839:The Shin-Zantetsuken Containment Unit will be sealed off`?

**Comment by Tsunayoshi** [comment]
> Show developer options and then also click Enable debug mode for raidboss [...]

I enabled it and will test it on my next run at monday.

> Are you playing in English?

yes

> Hide Chat Log (for privacy)

yes and **i removed it for my next run now**

> 00:0839:The Shin-Zantetsuken Containment Unit will be sealed off

I can not find it on any BA fights, also searched only for 00:0839 or Shin-Zantetsuken. Both had 0 results.

**Comment by quisquous** [comment]
Yeah, that's almost certainly going to be the fix, then.  Let me know!

**Comment by youranfu** [comment]
Thank you so much for the quick response! My friend running BA together with me didn't have this problem. So I just double checked with him - I had "Hide Chat Log (for privacy)" toggled on (same as Tsunayoshi) while my friend didn't. Appreciate the tip, and I think this should be the fix :)
