### ISSUE TITLE
"Downloaded file did not contain a plugin that could be loaded." error

### ISSUE THREAD

**Issue by SuiRose** [quisquous/cactbot#1608]
## Description

Attempting to download Cactbot from the Plugins > Get Plugins... method throws out an error with the following text:
"The downloaded file did not contain a plugin that could be loaded."

I'm able to download Cactbot's files separately, but I'm not real clear on which plugins need to add/enabled manually - attempts at this have thrown out various errors citing dependencies missing when I attempted that.

Feel like I'm missing something obvious here, haha.

## Additional information

If available, please include any logs or screenshots depicting the issue you're experiencing.

**Comment by quisquous** [comment]
Did you add OverlayPlugin first?

https://github.com/FFXIV-ACT/setup-guide#readme might help too

**Comment by SuiRose** [comment]
Yes, at least I think. Screenshot with what I've got, if it helps!
![Plugins snip](https://user-images.githubusercontent.com/68800070/88472240-8563a280-cec5-11ea-96ac-1f50051c364a.JPG)

**Comment by quisquous** [comment]
Yeah, that's the ancient version of OverlayPlugin.  You should remove it and then follow: https://github.com/FFXIV-ACT/setup-guide#overlayplugin

**Comment by SuiRose** [comment]
Oh snap! Looks like everything's working again. Thanks and apologies for the silly question!

**Comment by quisquous** [comment]
Happy to help!
