### ISSUE TITLE
Raidboss Timeline Overlay Not Starting

### ISSUE THREAD

**Issue by smithk58** [quisquous/cactbot#1636]
The timeline doesn't appear to work for some fights after the update 4 hours ago (18.5.0). Bowing to the dummies in summerford farms work, but it doesn't start in actual fights (maybe it's not detecting the fight starting?).

It isn't isolated to me (several other people in my static are experiencing it, and a couple people at summerford were testing there and said they were experiencing the same thing).

**Comment by quisquous** [comment]
I think I fixed this in 6b19e082.  If you switch your url to https://quisquous.github.io/cactbot/ui/raidboss/raidboss.html, then that should pick that up.

**Comment by smithk58** [comment]
Can confirm it fixed it. Thanks for the speedy response!
