### ISSUE TITLE
Cactbot Not Working Properly

### ISSUE THREAD

**Issue by xithejokerix** [quisquous/cactbot#1644]
I got ACT up and running and can verify that everything works as expected. Kagerou is installed and fully funcioning so I know the Overlay is working.

I installed the newest update of Cactbot and for some reason it will not work for me.

When I load up the Raidboss plugin, I see the text in the blue box, but it doesnt show any timelines on it.

When I go to Summorford and do the /countdown 5 nothing happens.

The other cactbot plugins seem to not be working for me either.
Its installed in the same folder as ACT and Im using the HTML's in the files for the plugins.

Any ideas?

**Comment by quisquous** [comment]
Did you lock the overlay? If you are seeing blue, then then that's just the debug text.

You may want to consider asking in the [ffxiv act discord](https://discord.gg/ahFKcmx) where you can get some more synchronous help in the #troubleshooting channel.

**Comment by quisquous** [comment]
If this is still happening, I recommend going to the ffxiv act discord linked above.
