### ISSUE TITLE
ja Localization

### ISSUE THREAD

**Issue by Riunia** [quisquous/cactbot#165]
Hi.

I was wondering if there was anything about the Japan localization being worked on, or if someone else was working on it. If not, is it possible that I may contribute to the project?

Thank you.

**Comment by quisquous** [comment]
Nope, nobody is working on it! I'd take any pull requests you want to send me.

I think the first thing to do is to add a ja file to https://github.com/quisquous/cactbot/tree/master/resources/lang.  From there, probably starting to translate triggers and timelines in **ui/raidboss/data/triggers** is the next step.

**Comment by quisquous** [comment]
No no, that's a more than reasonable question.  My apologies that this is not very obvious.  Right now, switching language to anything other than English is controlled by an option.

https://github.com/quisquous/cactbot/blob/master/AdvancedCactbot.md#customizing-behavior tries to explain how to set options.  The summary is that for each cactbot module (raidboss, jobs, eureka, etc) you add a **user/raidboss.js** file (or whatever the module is called), and inside there, make sure you have a line that says `Options.Language = 'ja';`

If you translate the test timeline in **test.js**, you can go to Summerford Farms and do a /countdown and it should start a test timeline etc.  If you've set the language correctly, this should behave properly and the triggers should work too.

I need to think about making setting a different language easier.  I'm thinking that I probably need to add a language selection box from the overlay page.  Ideally I could just detect it from the game itself, but I'd have to do some digging in memory.

**Comment by eestyle** [comment]
Hi, I am getting this when testing raidboss ui with japanese.
22/06/2018 6:34:26 PM: Info: Boss: BrowserConsole: Uncaught TypeError: Cannot read property 'replace' of undefined (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Plugins/overlay%20plugin%200.3.4.0/cactbot/resources/regexes.js, Line: 48).

**Comment by eestyle** [comment]
Thank You, yes its working now. Heres the test.js and general.js file I modified for Japanese.
I noticed that the general.js from the master file does not have tts in the triggers it like in 0.7.2 release and I did not add them back in. Also I did not keep the Fr replace part, as I just modified that to Japanese.

[general.zip](https://github.com/quisquous/cactbot/files/2130222/general.zip)
[test.zip](https://github.com/quisquous/cactbot/files/2130182/test.zip)

**Comment by quisquous** [comment]
@eestyle If you're planning on making more contributions in the future, would you mind uploading those as a pull request? https://github.com/CPAN-PRC/resources/wiki/My-first-Pull-Request

Re: tts.  In ae92fda263e I made it so that if not tts is specified, it willl just use alarm/alert/info text directly.  This reduced a bunch of redundancy in triggers.

**Comment by eestyle** [comment]
Ok noted, sorry, this is the first time I use github so I dont really know what I should do.

**Comment by Riunia** [comment]
So I've been running tests with the jobs overlay and having a bit of an issue trying to get the Ja localization to work properly. Every time I change the language to Ja it throws back an error:

`Info: jobs: BrowserConsole: Uncaught TypeError: Cannot read property 'youGainEffectRegex' of null (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/cactbot/ui/jobs/jobs.js, Line: 206)
`

This seemingly happens only when I switch the language to Ja. Works fine with any other language. Double checked the ja.js file in the resources folder also to be sure and nothing seemed out of the ordinary.

**Comment by quisquous** [comment]
I'm going to close this for now.  Any followup translations can just be pull requests.
