### ISSUE TITLE
Jobs: Visibility of crafter UI out of combat

### ISSUE THREAD

**Issue by CharonM72** [quisquous/cactbot#1658]
## Summary

Is there a way to have the crafter UI change opacity/hide when not crafting? I don't really like the UI to be there all the time.

**Comment by quisquous** [comment]
Unfortunately, no.  I don't know of any way to know whether or not you are in the middle of crafting or not.

**Comment by CharonM72** [comment]
Oh well, worth asking.

**Comment by g0shu** [comment]
Could just looking for log lines "you started/finished/failed synthesis" work?

**Comment by Una-p** [comment]
Think ACT works only in combat, so it doesn't know when you're crafting.
How about make minimalize/restore button?

**Comment by quisquous** [comment]
> Could just looking for log lines "you started/finished/failed synthesis" work?

I can't find these lines, but it's possible that I don't have them turned on for some reason.  I'll check and respond back here.

> Think ACT works only in combat, so it doesn't know when you're crafting.

This isn't true, for what it's worth.  The encounters in ACT are only in combat, but ACT is always parsing and writing to the log even when you're not in combat.

> How about make minimalize/restore button?

You can already add a global hotkey to show/hide overlays, so that's an option too for @CharonM72 that would work today.

**Comment by CharonM72** [comment]
Yeah I've considered that. Another thing that should be possible is to selectively show the UI only for certain jobs (detected when a job change appears in the log) but that's kind of a different thing (and also might not be able to check the current job on login/area change, not sure if that shows in the log or not).

**Comment by quisquous** [comment]
Yeah, looks like the log lines are LogMessage 1150-1161:
https://xivapi.com/LogMessage/1150?pretty=true
https://xivapi.com/LogMessage/1150?pretty=true
https://xivapi.com/LogMessage/1150?pretty=true
https://xivapi.com/LogMessage/1150?pretty=true
https://xivapi.com/LogMessage/1150?pretty=true
https://xivapi.com/LogMessage/1150?pretty=true
https://xivapi.com/LogMessage/1150?pretty=true
https://xivapi.com/LogMessage/1150?pretty=true
https://xivapi.com/LogMessage/1150?pretty=true
https://xivapi.com/LogMessage/1150?pretty=true
https://xivapi.com/LogMessage/1150?pretty=true

**Comment by Echoring** [comment]
I'm also thinking about it. 
I have not check `translations.js` before, but I'll have a try.
