### ISSUE TITLE
Cactbot keeps ending my encounters randomly - mid fight

### ISSUE THREAD

**Issue by MKE57** [quisquous/cactbot#1662]
## Description

Cactbot ends encounters outside of wipes/kills

## Additional information

Cactbot will end my encounter in ACT randomly, during a fight I will watch the timer tick up and then all of a sudden reset, for seemingly no reason. Encounter time set to 300 in options.

**Comment by quisquous** [comment]
Are you sure that it's cactbot? cactbot resets the encounter only when seeing a log line in ACT that matches ` 21:........:40000010:` or when doing an `/echo cactbot wipe` in game.

**Comment by MKE57** [comment]
It only begun happening after installing Cactbot, I only have ACT, the
FFXIV add-on, Cactbot & the required overlay.

I used to have to end my encounters manually before installing Cactbot.

**Comment by quisquous** [comment]
This is kind of a silly question, but can you double check and disable the cactbot plugin (not just the overlay but the plugin in ACT -> Plugins -> Plugin Listing) and let me know if it still happens? I made some changes to OverlayPlugin recently about ending combat, and I want to make sure it's cactbot and not OverlayPlugin?

**Comment by MKE57** [comment]
I can definitely try, could you let me know how I disable it?

**Comment by MKE57** [comment]
I didn’t turn off the plugin but I think I’ve found the issue, I sat and watched the screen for 20 minutes and it resets everytime I receive a notification from a different addon...

**Comment by MKE57** [comment]
Sat and watched ACT for over an hour now on a dummy. I have another add-on installed which gives me notifications in-game and it appears that these are resetting the encounter in ACT.

I can easily disable this addon whenever I want to parse, it's not much of an issue.

**Comment by quisquous** [comment]
Oh, interesting! I saw somebody else in discord having similar issues.  Could you let me know what plugin is so that I can check with them?

**Comment by MKE57** [comment]
Not an ACT plugin 😊

**Comment by quisquous** [comment]
That's fine, I just wanted to know what it was!

**Comment by MKE57** [comment]
It’s a hunt notification add-on, it fills the chat box with about 4-5 lines
of text when a hunt is found.

**Comment by quisquous** [comment]
Would you mind giving me a link?
