### ISSUE TITLE
Jobs: Hide/unload UI when combat in PVP area

### ISSUE THREAD

**Issue by Echoring** [quisquous/cactbot#1672]
Jobs UI will appear when you get in combat no matter PVE or PVP.
PVP is completely different from PVE. Showing UI is not necessary and may cause additional interference.
Can it be hide or unload in PVP specfic zone like the "well fed" icon?

**Comment by quisquous** [comment]
I think some of it is useful, like the health and mp bar? If you've hidden the normal UI for that, then you'd still want that for PVP.  Overall I think this seems like a good idea! I don't really do a ton of pvp, so it's not something I'm thinking about much.  (Would people still want buffs for pvp? Are there even pvp group buffs?)

**Comment by Echoring** [comment]
Yes, health and mp bar may be of use, but the color changed percent should be adjust. 
How about hiding Boxes and Procs only?

**Comment by quisquous** [comment]
I think maybe we could just early return from `UpdateJob` before calling any of the `setupJob` functions if we're in a pvp zone? I think avoiding adding boxes and procs might be the easiest solution here, as there's not a consistently named place to put a css rule here to hide them later.
