### ISSUE TITLE
radar module broken (5.3)

### ISSUE THREAD

**Issue by Cat-McCatface** [quisquous/cactbot#1673]
## Description
Radar isn't working post 5.3. Tried resetting (?) minimum distance, changing zones and checking again on a B rank and nothing (no notification sound for S rank or SS rank so might be an issue of changes to determining actor location). Tried clean replacement of files (with release) and nothing. Other modules work (raid module) ok

## Additional information
![Untitled](https://user-images.githubusercontent.com/19581414/90105519-a6245880-dd0b-11ea-958e-ef4acd54e2b8.png)
reload overlay on changes is disabled, no errors in overlay plugin log

**Comment by quisquous** [comment]
Should be fixed now via #1680
