### ISSUE TITLE
5.3 jobs overlay, storm's eye tracker

### ISSUE THREAD

**Issue by AmenneHolelane** [quisquous/cactbot#1676]
## Description

5.3 changed storm's eye in 3 meaningful ways. the eye combo will apply/add 30 seconds to a maximum of 60, mythril tempest combo will add 30 seconds to a maximum of 60, and Inner Release will add 15 seconds to a maximum of 60.

## Additional information

i'm going to peek at the coding but i have no idea what i'm doing so i may or may not have any success.

ty

**Comment by quisquous** [comment]
Thanks again!
