### ISSUE TITLE
Inserting a new timer into a timeline through a custom trigger

### ISSUE THREAD

**Issue by IllidraEthorn** [quisquous/cactbot#168]
I'm not sure that my title makes sense. But I would like to be able to add a timer to my timeline based on certain things that happen in an encounter. The encounter I have in mind is tsukuyomi, I'd like to be able to sync up a 5 second timer on the timeline for each time the moon stacks would tick.

My problem is that the moon stacks happen at different times in the fight due to server ticks. (I've noticed that I sometimes get the 4th stack right before the meteors explode and sometimes I get the 4th stack right before I touch the puddles.) How could I go about doing something like this? Can I make a cactbot custom trigger that inserts a timeline entry 5 seconds into the future? And if so, how can I do it?

**Comment by quisquous** [comment]
Hmm, at the moment there's no way to add anything into the timeline dynamically.  I'll think about it, but there are a lot of edge cases that make this tricky (looping timelines, needing to clear these things after reset, etc).
