### ISSUE TITLE
Cactbot Eureka not updating

### ISSUE THREAD

**Issue by TimStroodle** [quisquous/cactbot#1688]
The Eureka plugin for cactbot doesn't seem to want to update NM's as they spawn. It tracks day/night properly and add flags but nothing else. Attached is a picture of a bunny event spawned but it not showing on the cactbot map. Not sure if I have a setting wrong or this was from 5.3 update or what. 
![Advanced_Combat_Tracker_kj3sDj9E19](https://user-images.githubusercontent.com/65512393/90303531-a55f0400-de7c-11ea-9b25-e2f81904d831.png)

**Comment by quisquous** [comment]
Hmm, I wonder if the fate opcodes changes.

I'll try to take a look next week, but I'll also CC @KattTails.

**Comment by coldyworld** [comment]
it works on my end, but it updates very very slowly that it's pretty useless for tracking fates. weather & day/night seems pretty accurate though.

**Comment by KattTails** [comment]
I'm looking into it right now. Network behaviour hasn't changed, opcodes are the same (there's actually a new one too possibly, but doesn't impact here). I'll update when I find out what's going on.

**Comment by KattTails** [comment]
Found the issue and pushed a fix. 

Should be fixed in the next plugin release. Sorry about this.
