### ISSUE TITLE
Raidboss not working for wol ex German ffxiv client

### ISSUE THREAD

**Issue by MarikoMakaze** [quisquous/cactbot#1711]
I only get Raidboss notifications if i set my game language to english. Timeline is working in wol ex with german language.
For all the other content (eden, shiva un, older content) raidboss is giving me the calls with german game language.

Not sure if thats realy a bug or the full support for german isnt implemented yet.
Just wanted to make you aware of it.

**Comment by Akurosia** [comment]
Which cactbot version did you use when you tested this?

**Comment by MarikoMakaze** [comment]
Hi, im using 0.19.4.0

**Comment by MaikoTan** [comment]
Can you double-check if your language settings in FFXIV_ACT_Plugin.dll settings is the same as the language setting in the game client?
And AFAIK in the 0.19.4 version, although alert text in German was already implemented, timeline would stay in English because it is not fully translated.

**Comment by MarikoMakaze** [comment]
Language is set to german, not sure about the language the timeline is in, diddnt pay attention to that.
I also did several reinstall of the plugins and act.
Just now there was a new patch to cactbot, and in the notes was stated that localisation isnt fully done yet.
So i guess no bug and we just have to wait.

**Comment by Akurosia** [comment]
99% of WoL in german is translated in the 0.19.5 release (i know this since i did it) only a few new elements are missing in it.
Only other languages are not that done fully.

**Comment by MarikoMakaze** [comment]
No clue then whats the cause :s
