### ISSUE TITLE
special problem in the raidboss.js file 

### ISSUE THREAD

**Issue by adminferiale** [quisquous/cactbot#172]
hello i have try many things but with no real solution

I play tank and i try to do somethings with cactbot

I want to keep  all TTS trigger for all fight but  no TTS or sound allert for  provoc/shirk/ultimatum 

but i want to keep provoc/shirk/ultimatum as visual alert or Text info

in other word i try to have a 

Options.SoundAlertsEnabled = false
and 
Options.SpokenAlertsEnabled = false

for only provoke/shirk/ultimatum 

if someone can say me how to do because i play since 1h on the raidboss.js and i found no solution for  what i want to do

thanks in adavance

**Comment by quisquous** [comment]
Did you get this figured out?
