### ISSUE TITLE
Cactbot white screen in OverlayPlugin.dll

### ISSUE THREAD

**Issue by younglink098** [quisquous/cactbot#1721]
As you can see it only shows a white screen. Also at the bottom, it keeps trying to restart. It also not showing anything in FFXIV(Alerts, timeline, etc) as it doesn't load.

![image](https://user-images.githubusercontent.com/69880999/90584865-8b396480-e1a1-11ea-9a1b-5082e169b589.png)

**Comment by JLGarber** [comment]
There are a few pieces of information we could use on this one. First, can you open your Plugin Listing tab and give us a screenshot of the load order? Then, can you check through the installed plugins in that listing and give us a version number for each? And finally, what sorts of error messages are you getting in your Notifications tab? Are they all just generic warnings that Cactbot has crashed?

**Comment by younglink098** [comment]
![image](https://user-images.githubusercontent.com/69880999/90623404-69ad9c80-e1e4-11ea-80ec-b08bd4d35f18.png)


OriginalFilename: FFXIV_ACT_Plugin.dll
FileVersion: 2.0.6.4
ProductVersion: 2.0.6.4

OriginalFilename: OverlayPlugin.dll
FileVersion: 0.15.1.0
ProductVersion: 0.15.1.0

OriginalFilename: CactbotOverlay.dll
FileVersion: 0.19.5.0
ProductVersion: 0.19.5.0

As for the notification, I had a FFXIV_ACT_Plugin.dll in my ACT folder. I deleted it and the notification is gone. The problem is still there though.

How do I backup my settings?

**Comment by JLGarber** [comment]
Excellent, so you're on the latest versions of the different pieces. That's good.

Your settings (I believe? And maybe others can better inform you here) live at `C:\Users\USERNAME\AppData\Roaming\Advanced Combat Tracker\Config` by default. You can just create a copy of that folder to save whatever settings you need to before you make any drastic changes.

Maybe a foolish question, but do you have the latest version of Chrome installed? A moderately-recent-ish version is necessary for any overlays to function.

**Comment by younglink098** [comment]
Yes, I have the latest version installed.

**Comment by younglink098** [comment]
I just reinstalled ACT and now it's working. Thank you for helping!
