### ISSUE TITLE
radar: Incompatible config

### ISSUE THREAD

**Issue by Bluefissure** [quisquous/cactbot#1724]
## Description

Related commit: https://github.com/quisquous/cactbot/commit/2f3acb9716cb424946e46726b086d5930fd96c30
The added `Enabled` option didn't occur in former user options, so this will disable all types of hunt monsters by default unless users add `Enabled` to their user config file.

**Comment by MaikoTan** [comment]
So that is the reason that so many people complain that their radar stop working?
Maybe it should be
```javascript
if (options.Enabled === undefined || !options.Enabled)
  return;
```
?

**Comment by Bluefissure** [comment]
> So that is the reason that so many people complain that their radar stop working?
> Maybe it should be
> 
> ```js
> if (options.Enabled === undefined || !options.Enabled)
>   return;
> ```
> 
> ?

`options.Enabled === false` is enough, but I find that the `rankOption` will be overwritten to null if it doesn't occur in the user config file, investigating it.

**Comment by MaikoTan** [comment]
I think the better way is leave the `Options` in user config remains.
But rename the `Options` in this file as `DefaultOptions` or something, then use `Object.assign` to combine them.
