### ISSUE TITLE
Can we translate cactbot/ui/raidboss/raidboss.html?

### ISSUE THREAD

**Issue by Una-p** [quisquous/cactbot#1730]
![image](https://user-images.githubusercontent.com/39465903/90996406-a7059600-e5f9-11ea-8758-7918c8f7516b.png)

In Korea, some people recognize this text as just an error and ask us "I just installed and got error. How can I fix it?".
There are not a few people who ask this, so I would like to translate them.
But there's no zone to put translate line at js,html. (think it is not changeable) I've no idea how can I do this...

Attached them that I would like to translate.
https://github.com/quisquous/cactbot/blob/dd784061e9b28adc5b02f06745e25ba96e099e59/ui/raidboss/raidboss.html#L42-L57

**Comment by MaikoTan** [comment]
That is also happened in Chinese server. Such a bunch of people would ask "I have set the language as Chinese but why does it still shows English?"
Maybe we can dymanically load these text by reading the `System Locale` property?

**Comment by quisquous** [comment]
This sounds like a great idea.  Would it make sense to list the translations in the .js file and then dynamically set in them on the elements in the html?

**Comment by Una-p** [comment]
Yes maybe. It will be good for user who are installed now.

**Comment by Una-p** [comment]
Thanks for improve! I'll test translated data and push when it works. I hope it'll be alive when server opened.
