### ISSUE TITLE
Better way to handle custom personal triggers

### ISSUE THREAD

**Issue by lombax5832** [quisquous/cactbot#1735]
It would be helpful if there was a dedicated folder where the user could dump personal trigger and/or timeline files and they would be found by cactbot without having to edit the manifest.txt file every update.

**Comment by Akurosia** [comment]
put all your custom stuff into `cactbot/user/raidboss.js` and you dont have to touch any manifest.txt at all

**Comment by lombax5832** [comment]
> put all your custom stuff into `cactbot/user/raidboss.js` and you dont have to touch any manifest.txt at all

That misses the point of making this it an easy drag&drop.

Lets say someone makes some custom triggers for some fight and I want to use them. Its still an extra unnecessary step to paste the triggers into raidboss.js or to add them into the data folder and then modify manifest.txt.

Putting all custom stuff into `cactbot/user/raidboss.js` also makes for a massive file eventually and the triggers wont be zone locked anymore

**Comment by valarnin** [comment]
The code is written such that `raidboss*.js` and `raidboss*.css` will be read and passed back, with the exception of `raidboss-example.js`/`raidboss-example.css`.

This won't pull from subdirectories and it won't pull timeline files, which would probably be the ultimate goal here?

So you could have something like this:

```
user/raidboss.js
user/raidboss.css
user/raidboss.txt
user/raidboss/some-timeline.txt
user/raidboss/some-zone/some-fight-timeline.txt
user/raidboss/some-zone/some-fight-triggers.js
```

**Comment by quisquous** [comment]
> Lets say someone makes some custom triggers for some fight and I want to use them. Its still an extra unnecessary step to paste the triggers into raidboss.js or to add them into the data folder and then modify manifest.txt.

You definitely shouldn't modify manifest.txt or add them into the data folder directly, as it'll get overwritten when cactbot updates.

It sounds like the "have a user subdirectory" request here is what #860 is asking for.

> Putting all custom stuff into `cactbot/user/raidboss.js` also makes for a massive file eventually and the triggers wont be zone locked anymore

I don't know what you mean about them not being zone locked.  You can have multiple sets of triggers for different zones in the same file.

**Comment by lombax5832** [comment]
Yeah, I think what #860 wants is what I'm looking for.
