### ISSUE TITLE
Raidboss doesn't work while in trial/raid

### ISSUE THREAD

**Issue by harubie** [quisquous/cactbot#1736]
Hi,

I am having issues getting raidboss to work. I have installed the guide previously and everything seemed to work fine until the recent update. Going into raids no longer trigger raidboss. I have tried to reinstall everything according to the guide but it fails to run every time. Testing it on summerford farms seemed to work okay. Where do I retrieve the logs for this?

**Comment by quisquous** [comment]
Hope you got this figured out!

**Comment by ChristianIvicevic** [comment]
I noticed that the newest raidboss modules for Seat of Sacrifice and Shiva Unreal don't show when using the separate raidboss modules for alerts and bars rather than the combined one.

**Comment by harubie** [comment]
I was under the assumption that raidboss worked on all older content. Had a look in the files and found that some of the older ones were missing so I just assumed that it was left out because there was no point in mapping them. I tested on Titan ex and the call-out triggered. Today I queued the nier collaboration raid and everything called out fine. :)
