### ISSUE TITLE
Feature: Show marked players for UWU gaols?

### ISSUE THREAD

**Issue by wsoxfan1214** [quisquous/cactbot#175]
I know SST does this in some way, but for those with Cactbot already, this may be nice. Essentially, a Titan entity targets one player for a gaol and a Garuda entity targets two players. 

Is it possible for cactbot to throw an alert text below the timeline making those marked? 

The base triggers used in ACT are below, if it helps: 

<Trigger R="Garuda:[^:]*:Rock Throw:[^:]*:YOUR NAME" SD="Call" ST="3" CR="F" C=" General" T="F" TN="" Ta="F" />

<Trigger R="Titan:[^:]*:Rock Throw:[^:]*:YOUR NAME" SD="Far" ST="3" CR="F" C=" General" T="F" TN="" Ta="F" />

Thanks! :)

**Comment by quisquous** [comment]
If by "show" you mean actively mark in game, I'm not quite sure I want to go down the route of having cactbot inject things into the game.

If by "show" you mean have some triggers, cactbot already has that.  It (should) list all three jail people in alphabetical order by first name.

**Comment by wsoxfan1214** [comment]
Interesting. I don't think that was firing for me. I did indeed mean the latter.

**Comment by quisquous** [comment]
Hmm, I have had some reports of it not showing.  I've only seen that once, when somebody got killed by upheaval.  I've been trying to reproduce it locally, but has worked every other time for me.

**Comment by nobodyofnote** [comment]
The gaol triggers broke after the update to the trigger file to add JP support, alongside a few others; I rolled the file back to the pre-JP version and it works fine. I did notice that some of the JP strings, for things that still worked, were regexja, while the things that broke were just regex, duplicating the line above.

**Comment by Riunia** [comment]
Thanks for the heads up @nobodyofnote , I noticed the ones with regex arent tagged as regexJa so I assume it's trying to find the regex for both and failing because it can't find both. I'll send in a pull request to have it fixed.

**Comment by quisquous** [comment]
This should be working again now.  Sorry!!

**Comment by wsoxfan1214** [comment]
Awesome. Until the next release hits, which file should we download to replace until then?

**Comment by quisquous** [comment]
https://github.com/quisquous/cactbot/archive/master.zip and replace your cactbot/ui folder with the ui folder there.

I'll try to put out another release once I fix a few more small issues with timeline desyncing later in the fight.
