### ISSUE TITLE
new raidemulator unresponsive

### ISSUE THREAD

**Issue by lombax5832** [quisquous/cactbot#1751]
I wanted to play around with the new raidemulator.html and it seems like I cannot do anything with it. I cannot drag and drop network log files into it, it does not detect anything when I manually import into ACT. None of the buttons do anything, its completely unresponsive. I've even done a clean re-install of cactbot. I included a screenshot, there also seems to be these 2 errors in the console: 
`Uncaught (in promise) TypeError: Cannot read property 'style' of null`
`Uncaught (in promise) TypeError: Cannot read property 'SetDataFiles' of undefined`

Maybe I just entered the URL wrong, but hopefully someone can correct me.

![chrome_2020-09-02_06-14-42](https://i.imgur.com/ZHN6hON.png)

**Comment by quisquous** [comment]
Sorry, this should be fixed with 654f68b54664e2119cc784a7e613301126f7ab1a.  You should be able to view it via https://quisquous.github.io/cactbot/ui/raidboss/raidemulator.html?OVERLAY_WS=ws://127.0.0.1:10501/ws (if you haven't changed any of the settings).
