### ISSUE TITLE
E7S Timeline Disappearing After 2nd Pull

### ISSUE THREAD

**Issue by KiBlack** [quisquous/cactbot#1761]
## Description

The timeline in E7S is not showing up. I still hear callouts though. Not sure why it's happening and not sure if it's happening in other content.

## Additional information

Happens on 0.19.7. Downgraded to 0.19.6 and going to see if that fixes it. Will edit under here with an update.

**Comment by quisquous** [comment]
I think this is related to @valarnin's #1731 change.  I've added more syncs to e7s so it should continue to work in the next release (even though it might not start right on engage).
