### ISSUE TITLE
/countdown regular expression should only match the initial countdown

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#1762]
When you use a countdown from the menu and not from `/countdown 15`, it spits out extra log messages.  I'd like to make it so the countdown only matches the first.  This will help me clean up a fix for #1761.

English example:
```
Battle commencing in 30 seconds! (Player Name)
Battle commencing in 25 seconds!
Battle commencing in 20 seconds!
... etc ...
```

This is what I'd like to change: https://github.com/quisquous/cactbot/blob/main/resources/translations.js#L26-L33

Sorry to ping everybody, but can I get help figuring out what this looks like in various languages? I'm happy to send a pull request if you just want to paste an example here.  I looked in the data files, but I don't see this.  Do all other languages just put the player name in parentheses, or is that English only? @Akurosia @VanSlanzar @Una-p

(The second thing that needs to happen is that when people use duty recording (whyyyyyyyyy) the countdown message looks different, e.g. `Duty record started. Battle commencing in 30 seconds! (Player Name)`.  I think I can fix that on my own via https://xivapi.com/LogMessage/1990?pretty=true translations.)

**Comment by mooondark** [comment]
I can confirm the name in parenthesis for the FR client :
```
00|2020-09-06T19:10:40.0000000+02:00|00b9||Début du combat dans 30 secondes! (Elarun Moyse)|6d7100f1aa2d8574ab04dc7110ae42b4
00|2020-09-06T19:10:45.0000000+02:00|0039||Début du combat dans 25 secondes!|198d663a3e097a7e17892fe844671713
00|2020-09-06T19:10:50.0000000+02:00|0039||Début du combat dans 20 secondes!|3ebdc8dae29fd8cf805ade8a22e22a85
00|2020-09-06T19:10:55.0000000+02:00|0039||Début du combat dans 15 secondes!|9b5c7c321de7b494c76b0611ca398a34
00|2020-09-06T19:11:00.0000000+02:00|0039||Début du combat dans 10 secondes!|605fa42f43bd4440f1aef82478547c4d
00|2020-09-06T19:11:05.0000000+02:00|0039||Début du combat dans 5 secondes!|dafdfa70ad4cd7a5fe86b5d3f0a4e1db
00|2020-09-06T19:11:10.0000000+02:00|0039||À l'attaque!|ebb505015d745aa87f9ff492b95b11e8
```

**Comment by Una-p** [comment]
I playing with EN client not KO server so I haven't any logs.. 
```
전투 시작 20초 전! (먓미)
전투 시작 15초 전!
전투 시작 10초 전!
전투 시작 5초 전!
전투 시작!
```
![제목 없음](https://user-images.githubusercontent.com/39465903/92338429-5018ba00-f0eb-11ea-868f-1a250686efc4.png)
If you want to see more log, it's good to tell other KO translators. :)

**Comment by quisquous** [comment]
No that's perfect, thanks both of you.  It seems like maybe the name is in parentheses in all languages, potentially.
