### ISSUE TITLE
oopsyraidsy: <Buff Name> Missed <>

### ISSUE THREAD

**Issue by panicstevenson** [quisquous/cactbot#1763]
## Description

Using the buff tracker for Oopsyraidsy, there are times where buffs are reported as missing a player, but no player name is returned.

## Additional information

Screenshot:
![image](https://user-images.githubusercontent.com/8849608/92297640-57c33d80-eef6-11ea-889b-61f2d718f317.png)

Related log entry:
```
Info: Oopsyraidsy: BrowserConsole: Couldn't find name for 106F8A6D from pet 4000797E (Source: , Line: 47)
```

It looks as though this line is occurring explicitly because the Scholar isn't in the party list upon zoning in, which is also why Selene is showing up as the caster for the Whispering Dawn entry instead of the Scholar's name.

Related code shows the same:
https://github.com/quisquous/cactbot/blob/37ae15b684cb98d17013cf980cd4586653f82dca/ui/oopsyraidsy/data/00-misc/buffs.js#L47

Effectively, I would imagine that these are two separate bugs, but I think had the missing player been anyone other than the Scholar there would have been less information to go off of.

Ultimately, the code being called (`data.party.nameFromId(ownerId)`) is simply a lookup in a hashmap:
https://github.com/quisquous/cactbot/blob/d4f4086a3ecf75c491226f81d68a481b4740f730/resources/party.js#L136-L138

And the hashmap is pre-populated here:
https://github.com/quisquous/cactbot/blob/d4f4086a3ecf75c491226f81d68a481b4740f730/resources/party.js#L28-L33

So, it's possible there's not a way to fix this code within cactbot itself, but rather it would need to be addressed downstream. Nonetheless, opening an issue here to point people to for questions.

**Comment by quisquous** [comment]
I'm hoping that this will be fixed by https://github.com/ngld/OverlayPlugin/releases/tag/v0.16.0 but I'd like to keep an eye out for a while before closing this.

**Comment by quisquous** [comment]
I think this is fixed now.
