### ISSUE TITLE
Formated computer and cactbot wont work anymore

### ISSUE THREAD

**Issue by mooztikette** [quisquous/cactbot#177]
Hello there!

I thought it would just take a simple copy/paste of my ACT's folder in Program Files to get back to work but it actually would also have taken a copy/paste of what was in my user's /roaming folder xD

So i re-installed everything properly, step-by-step in a clean way but i can't get cactbot to work anymore :-(

Only 2 things have changed from prior to formating : big windows 10 update and i updated to latest cactbot's version.

Everything seems fine in the Overlay console as shown below :
![act](https://user-images.githubusercontent.com/39465024/41931764-4e005880-797f-11e8-86a4-cb5aef9920a5.png)

To test it i teleported to Summerford Farms and had some ERP with the dummies but no emote would trigger anything :-(

In case this can help finding the issue :
• I still ran ACT in that state during my weeklies; and while i was doing O5S it popped the light trigger text (+sound) and same for Ultimatum (yes i had a strange OT), but nothing else
• I play the game in french and i set both ACT and raidboss-example.js to french

Does anyone have any idea? :•)

Thanks in advance !

**Comment by Riunia** [comment]
Did you rename raidboss-example.js renamed to raidboss.js?

**Comment by mooztikette** [comment]
Wow i feel idiot... I personally renamed the raidboss.js that is in user folder to raidboss-example.js cause it was working like that before i format my comp.

Well thank you very much @Riunia the dummy and i just had lots of good time :)

**Comment by quisquous** [comment]
Excellent sleuthing! Glad you got it sorted out.  :)
