### ISSUE TITLE
Jobs: UI become invisible while in instance

### ISSUE THREAD

**Issue by Jaehyuk-Lee** [quisquous/cactbot#1772]
## Description

The Jobs overlay makes "sound" but not visible while in instance. (sound with /countdown)
This may be Korean server only bug.
I should "Refresh" overlay when I get in to an instance area to make it visible.
This happened in e5s ~ e8s (more than 20 times)
(Also, Copied Factory)
This didn't happen when I unsynced level and go o8s alone.

## Additional information

#1752(jobs: Hide CP bar when not crafting) is working fine though.

**Comment by Jaehyuk-Lee** [comment]
![K-003](https://user-images.githubusercontent.com/4695371/92598103-51143c00-f2e3-11ea-948a-d2439c047776.png)
I think this `class="hide"` make the problem.

**Comment by MaikoTan** [comment]
https://github.com/quisquous/cactbot/blob/4edded91f973069b409d47c43fae105169809478/resources/translations.js#L76-L99

I think it can happen when there are some logs match these regexes.
@Echoring (and I) made this work but we forgot to limit it only execute when you are a crafting job.
But I am curious about what is matched. Echoring and I are not familiar with Korean (and we don't have Korean server account, too), can you provide some related log file or lines?

**Comment by Jaehyuk-Lee** [comment]
Log: https://1drv.ms/u/s!ArFh2dBXj3ULiNoPD_UepKtBlT_n5g?e=dCrTMw
This log is too long, so just see near line 408162, `00|2020-09-10T21:58:13.0000000+09:00|0839||희망의 낙원 에덴: 공명편(영웅) 4 공략을 시작합니다.|f79fd368e13a42270a55b0b7156f286a`

**Comment by Jaehyuk-Lee** [comment]
`<other player name> 님이 취은 덩어리를 완성했습니다!` log makes this bug.

**Comment by MaikoTan** [comment]
Oh I see, so it is the same problem that we trapped in CN and JP too.
Shall @Echoring has time to fix it?

**Comment by Jaehyuk-Lee** [comment]
Ummm.. this would not happen in JP/CN I think.
When I added `(?<player>\\y{Name})` on front, KR is fixed.

**Comment by Echoring** [comment]
Yes, we are once meet this problem, but finally fix it.
