### ISSUE TITLE
Remote cactbot: non-English TTS and instance member problem, etc

### ISSUE THREAD

**Issue by Jaehyuk-Lee** [quisquous/cactbot#1773]
## ~~non-English TTS problem~~ (fixed)
I think this is happening to all other languages, non-English is spoken in English pronounce.
I think it's better to watch a video, I've uploaded on Youtube.
In real situation now: [Youtube Link](https://www.youtube.com/watch?v=gy8p2jbKzww)
How Korean should be read: ~~[Youtube Link](https://www.youtube.com/watch?v=jVpBybe_qs4)~~
How English speaker reads: ~~[Youtube Link](https://youtu.be/wVG-eTm5nkU)~~
EDIT: I didn't notice I was recording video while other sounds were playing, sorry.

## Korean server party member problem (guessing it's overlay plugin's bug)

Party member is not loaded even though I refreshed the web page **while in battle**. (I got into the Copied Factory.)

![Screenshot_20200909-212921_Samsung Internet](https://user-images.githubusercontent.com/4695371/92598433-c2ec8580-f2e3-11ea-801b-cd29eae77156.png)

It worked properly when I manually input player parameter. (I played DRG and input DRK's name, remote cactbot worked as I was tank)

## ~~timeline sync is not working well~~ (looks like not-an-issue)
Timeline usually work, but shown late. Cactbot overlay on ACT shows timeline as the battle starts, but remote cactbot is shown late.
Also, sometimes it does not appear at all. The real situation video I posted on the first topic, did not load timeline.

**Comment by quisquous** [comment]
* Non-English TTS problem

Do ACT custom triggers sound correctly? Can you explain a little bit more what you mean by "real situation"? I assume cactbot tts normally sounds correct? If you select `Use Browser for Text to Speech` in the cactbot raidboss options, does it sound correct then? If you select the ko-KR voice on https://embed.plnkr.co/WjmlDnxcXX5dqlQI/ in your browser, does that sound correct? 

Sorry for all the questions, just trying to differentiate which things work and which don't.

* Korean server party member problem

Sorry, I am not sure what's going on here.  When I am in an instance, I can refresh the page and the party will show up.  Even if I start ACT and the remote server while in the instance, the party will still show up.  This is using the `PartyChanged` event from OverlayPlugin.  It's sent whenever an overlay first registers for the `PartyChanged` event or when it changes.

You could try debugging this by adding `console.log(JSON.stringify(e));` to these two places:
* https://github.com/quisquous/cactbot/blob/main/resources/player_override.js#L38 (remote or local raidboss when active)
* https://github.com/quisquous/cactbot/blob/main/resources/player_override.js#L202 (remote raidboss player select)

If you don't see anything locally or remotely, it could possibly be an OverlayPlugin bug, as there's been polling added there.  However, if you're seeing it locally but not seeing it remotely, then there's something wrong with the port forwarding?

* Timeline sync latency

Remote cactbot sends everything (logs, network logs, data for your character moving around, etc) over websocket and forwarded .  If you have a bad internet connection and there is latency between you and the person who is connected to your computer, then I think things will be delayed.

Timelines not starting at all is very surprising to me.  I am not sure what to do about that or even where to start debugging.

**Comment by MaikoTan** [comment]
I try to use Korean TTS and test it in Middle LaNoscea, but it works well.
Although I don't know Korean, I can differentiate the correct sound and the English-like one that you mentioned above.

I don't know if it related. But FYI, I am using URL like `https://quisquous.github.io/cactbot/ui/raidboss/raidboss.html?OVERLAY_WS=wss://127.0.0.1:10501/ws` because ngrok doesn't work on my PC.

**Comment by Jaehyuk-Lee** [comment]
@quisquous 
* Non-English TTS problem
I mean, the raidboss trigger shows properly in Korean text, but it reads in English pronounce. When you write other languages in English, you cannot write it to pronounce exact same, right? "こんいちは" in English pronounce is "konnichiwa", but native speaker does not pronounce as English "konnichiwa". It's slightly different, and sometimes it can be really different.
So, the browser-tts for Korean is really weird to hear. It's very unnatural.
* Korean server party member problem
So, this maybe related to overlay plugin problem. It has some bug with Korean server after v5.2 patch. I found a bug "hide overlay while in cutscene" does not work with Korean server now.
But, refreshing webpage didn't fix it. So, some part looks cactbot problem.

**Comment by Jaehyuk-Lee** [comment]
@quisquous You might understand better with this video. English is read with Korean voice.
[Youtube](https://www.youtube.com/watch?v=QNMirV2hjQM)
For cactbot, it's happening reversely.

**Comment by quisquous** [comment]
Ok, I'll try to take a look.  I could tell a difference but wasn't 100% confident.  I am glad it is working with that embed.plnkr.co link, because that means I should be able to get it to work in cactbot, since cactbot is using the same code.  I should have some time to look at this this coming weekend, but if you want to look at it yourself, https://github.com/quisquous/cactbot/blob/main/ui/raidboss/browser_tts_engine.js#L12-L24 is the code that is used for browser tts.

**Comment by Jaehyuk-Lee** [comment]
I've found something interesting. When I debug tts with local `raidboss.html` file, it read with Korean voice whatever text language is. But `https://quisquous.github.io/cactbot/ui/raidboss/raidboss.html` read everything in English voice.
Posting this just to share new knowledge.

**Comment by Jaehyuk-Lee** [comment]
Found out what decides announcer's language.
https://github.com/quisquous/cactbot/blob/90254494745acfa5fbae05bcbf303fc93ac838de/ui/raidboss/browser_tts_engine.js#L36
`&tl=en` part decides language. If I change this to `&tl=ko`, TTS reads everything with Korean voice.
We should make language parameter on TTS player.

**Comment by quisquous** [comment]
I guess my question is why is something using the google tts instead of the speech synthesis tts? Recent versions of Chrome should support this.  What browser are you trying this on that's falling back on the google tts?

**Comment by Jaehyuk-Lee** [comment]
If you're asking me I was using google tts, was just tts says Korean in English pronounce. Not failed, it was a bug of cactbot.

**Comment by quisquous** [comment]
Yeah, I don't understand why https://github.com/quisquous/cactbot/blob/main/ui/raidboss/browser_tts_engine.js#L61-L73 isn't running for you and choosing to use the speech synthesis api instead of google tts.  That's why I wanted to know what browser you were using.

**Comment by Jaehyuk-Lee** [comment]
Ah, yes I also wondered why. When I run html file with local file, it used speech synthesis api.
But when I connected github page version, it used Google TTS.

**Comment by Jaehyuk-Lee** [comment]
After resetting ACT and installing everything again, fixed some bug with overlay plugin. I'll check what's fixed and post new comment here.

**Comment by Jaehyuk-Lee** [comment]
"Korean server party member problem" is still happening.
Timeline sync looks fine. It was like 20sec late start, but it's now unnoticeable.

**Comment by Jaehyuk-Lee** [comment]
Remote cactbot doesn't work without adding `player` parameter manually. It does not work with blank value.

**Comment by quisquous** [comment]
@Jaehyuk-Lee What do you mean by "without adding `player` parameter manually? If you haven't specified player at all in the url, it should go to the player select screen.  If you select the default option, it should add `player=` with a blank value and proceed to normal raidboss.  Is that not true?

**Comment by Jaehyuk-Lee** [comment]
> If you select the default option, it should add player= with a blank value and proceed to normal raidboss. Is that not true?
It does not.

**Comment by Jaehyuk-Lee** [comment]
I think this is not an issue about cactbot (`partyChanged` listener part), closing this issue.

**Comment by Jaehyuk-Lee** [comment]
For reference, this problem was occured by DiscordPresence Plugin crashing with Overlay Plugin
https://github.com/Elysia-ff/FFXIV_DiscordPresence/issues/1
The developer is not dealing with this, this won't be fixed.
