### ISSUE TITLE
Locking Radar Overlay makes it Invisible

### ISSUE THREAD

**Issue by Djinnistorm** [quisquous/cactbot#1777]
When unlocked, the Radar is visible and works. When LOCKED, the radar turns invisible. 

Here's a picture of it unlocked:
![image](https://user-images.githubusercontent.com/6293633/92686461-b37f3380-f307-11ea-9e5b-8e2d207e2201.png)

and now it's locked, It's disappeared, whether I'm in the game or not:
![image](https://user-images.githubusercontent.com/6293633/92686634-0bb63580-f308-11ea-9dc6-e9f7a7d65bc1.png)

If I select the force white background option, a white square appears in the correct spot, but doesn't function. 

I reinstalled all plugins after updating for this patch, no change in behavior. 

Nothing in Notifications. Only thing of note is the message "[9/10/2020 1:54:20 AM] Info: ZReorder: Fixed Radar." whenever I tab back into the game in the radar's plugin section. 

Let me know if I can assist further, and thanks for this plugin! For now I'll just use it in unlocked mode.

**Comment by Akurosia** [comment]
The radar turns invisible as long as no B/A/S Rank has been found.

To easy test this, make sure B ranks are enabled and quickly fly around e.g "central la noscea" to see if the b-rank is displayed

**Comment by Djinnistorm** [comment]
Yep, you're right, this is a thing it now does. So used to the square staying visible that this change threw me for a loop. Closing.
