### ISSUE TITLE
Jobs: comboTracker break when Sonic Thrust hit mutiple mobs

### ISSUE THREAD

**Issue by Echoring** [quisquous/cactbot#1778]
```
  comboTracker.AddCombo([
    kAbility.DoomSpike,
    kAbility.SonicThrust,
    kAbility.CoerthanTorment,
```
I add this DRG's AOE combo to comboTracker, but find that when Sonic Thrust hit mutiple mobs, comboTracker will errorly consider that mutiple Sonic Thrust has been cast, and combo is broken.
Only DRG has this problem, because only DRG has 3 AOE combo.

**Comment by quisquous** [comment]
Hmm.  I was actually wondering a little about removing the combo tracker.  I think there are very few things that need it, and it's very incomplete.
