### ISSUE TITLE
TTS Changes and the character [#] in Triggers

### ISSUE THREAD

**Issue by Hoshiyuu** [quisquous/cactbot#178]
With the recent TTS changes in most triggers, setting TTS readouts on popup texts now cause some callouts such as Byakko stack, Nael's Cleanse to read [#] as [Sharp] causing weird and long callouts. 
(e.g. Nael's "Cleanse Sharp 1 : Firstname Lastname")

I don't see a way to easily override these triggers since they are quite non-standard for Coils, is there an example to change these without needing to reapplying the changes to the non-user trigger.js file everytime an update overwrites the old files?;

and is there a change planned for the master files on github?

**Comment by quisquous** [comment]
Oh, hmm.  That does seem awkward.  Thanks for mentioning this.  I'll do a search and replace on tts strings to remove `#` before playing them out.

What do you mean by a change planned for the master files?

**Comment by Hoshiyuu** [comment]
Ah, what I meant was if you were going to roll the changes into the files, or introduce a way for user config customization, but with the method used in https://github.com/quisquous/cactbot/commit/b2d4ac9d1102c43e8e739dacab706a3ee9a178b6 nothing else need to be change, thanks!
