### ISSUE TITLE
I wonder if we can make copy&paste works on overlay

### ISSUE THREAD

**Issue by Jaehyuk-Lee** [quisquous/cactbot#1782]
## Question

What would you like to ask?

I would happy to add copy and paste support on overlay, especially with oopsy. I sometimes want to copy and paste warnings or death report to ffxiv client, not typing myself.

**Comment by quisquous** [comment]
You're talking about being able to copy from an oopsy overlay to something else? How are you thinking about adding copy support, as I know Ctrl+C is captured by the game and not the overlay?

The other thing that you might be interested in is `ui/oopsyraidsy/oopsy_summary.html`.  If you open that up in a browser via local websocket before you start, then you'll get a list you can copy and paste from there.

**Comment by Jaehyuk-Lee** [comment]
Thanks for other way to copy it, but I wonder maybe right-mouse click to copy thing possible?

**Comment by quisquous** [comment]
I don't know if it is.  I think that would be a question for ngld.

One other alternative is to add something that uses the [clipboard api](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API).  I could imagine adding something where left clicking on oopsy at all copies the current list of mistakes into the clipboard?

**Comment by Jaehyuk-Lee** [comment]
Oh, yes that looks good. w3school provides [example](https://www.w3schools.com/howto/howto_js_copy_clipboard.asp) how to copy to clipboard. Maybe we could add a button or add a click listener to each warning/death report/etc DOM.

**Comment by quisquous** [comment]
I was going to propose the simplest option I could think of, which is that clicking anywhere on oopsy copied the whole list.  Then you could paste into discord (or whatever) and edit out the parts you didn't want.  I'm not quite sure where a button would go in the ui so that's hard for me to imagine, but maybe you have better ideas.

**Comment by Jaehyuk-Lee** [comment]
I think copying one line is better, if you need multiple lines you may copy&paste every line. Normally, you don't need so much lines since mostly one mistake causes more problems.
