### ISSUE TITLE
Hide unnecessary weather slots when hopping from an Eureka area to another

### ISSUE THREAD

**Issue by steponmepls** [quisquous/cactbot#1784]
## Summary

Normally there's only a single relevant weather condition displayed in Anemos and that's Gales. If you actually hop from Hydathos into Anemos more than one relevant weather will be shown actually covering portions of the map for no reason. I inspected the page and found out you use area specific classes for the main container so I added the following in my custom eureka.css file. Maybe it can help as workaround.

```
/* Hide unnecessary weather slots in Anemos */
.aspect-ratio-anemos #label-weather-container > div:not(:first-of-type) {
	display: none;
}
```

**Comment by quisquous** [comment]
Thanks!
