### ISSUE TITLE
DRG or NIN bars?

### ISSUE THREAD

**Issue by Hyrulean** [quisquous/cactbot#179]
Hello! Just wanted to first thank you for this amazing tool you have created.

My question is: are there any plans to create DRG or NIN bars for cactbot? Or any jobs that aren't currently included for that matter? I have tried creating them myself but am not experienced enough to get them to work. Thanks!

**Comment by quisquous** [comment]
At the moment there aren't.  I don't really play those jobs, so I think I'd really need somebody to tell me what they wanted tracked to understand what bars to make.

**Comment by Hyrulean** [comment]
understood! well, being someone who plays almost every job, I might be able to help a bit if you were ever to add those features. Some things I would think would be useful for different jobs off the top of my head would be: 

White Mage: almost same as astro
-Freecure proc
-Medica 2 time remaining

Scholar:
-Aetherflow timer
-Eos' Whispering Dawn remaining time
-Sacred Soil remaining time

Black Mage:
-Thunder 3 timer

Dragoon:
-Blood of the Dragon / Life of the Dragon timer: would be amazing if it was blue like Warrior's storm's eye GCD timer, but turned red during Life of the Dragon.
-track how many units of the dragon gauge you have filled 1/2/3
-Timer on Dragon Sight Tether
-Bar showing how long until combo-drop timer is met

Ninja
-Huton Timer
-Doton remaining time
-Bar showing how long until combo-drop timer is met
-Ninki gauge tracking (color changing at 80 ninki)

I'm sure there are other things that could be useful but I can't think of them & I don't really play BRD / MCH / SAM so am afraid I can't offer much with them. The combo tracker that mnk has would also be very nice to have on warrior :)

**Comment by ArkfrostLumas** [comment]
I as a main DRG am not sure, what you want the DRG BotD/LotD gauge for, because this already natively exists within the game as the basic job gauge both normal and simplified, as well as the units of dragon gauge and the NIN huton timer.
Just wondering.

**Comment by Hoshiyuu** [comment]
Chiming in, a few Dragoon ideas I've had for a while. These are a lot less on the fancy jet fighter dashboard side, but more practical for DRG trying to self improve. Some of them are the current nuances of Dragoon for people who are blue/purple chasing for orange, so if this is ever developed, I would expect quite some time is needed to work with a proper DRG main theorycrafter.

1. Whenever Dragon Sight is used, I'd like to track if Jump, Spineshatter, Dragonfire and the 2 respective mirage dives are used under Dragon Sight. This is one of the hallmarks of a good Dragon Sight when played optimally.

2. Some sort of indicator that, given that you are pressing Blood for Blood, Dragon Sight, Battle Litany on cooldown, when is the next expected time they will fully overlap. (for when CDs are not fully aligned with interruptions from boss)

2a. As an extension of 1 and 2, an indicator tries to guess based on whether Dragon Sight or Blood for Blood will be available in X second, you should go into Life of the Dragoon now or 30 second later so you get more buffed GK/Nastronds.

3. A clutch for Dragoon newcomers to show them a warning when SSD, if used now, will lose them an Eye. (two mirage dive available at 2 eyes with GK on a >15s CD)

Bonus, extra fancy stuff: After a pull ends, somehow with FFLOGs API and algorithm behind http://tethercalc.herokuapp.com/ (Xephera uses FFLOGs API to do the math too) to show the optimal Dragon Sight target per dragon sight casted.

**Comment by Hyrulean** [comment]
Thanks Demoness, I'll be sure to check into that. Thanks for the suggestions. 

@ArkfrostLumas - I am using a multi monitor setup and was trying to get visual bars to place on my second monitor just for aesthetic reasons and some testing rather than to replace the in-game gauges since they work just fine and are actually rather nice looking. 
By combo dropper, I mean, any the 12-ish second window in between using your True-Vorpal-Full thrusts & same thing for other melee jobs. It would be a bit handy to see visually how much time I have left until my combo drops. The reasoning for this is to avoid those rare moments when you'll return to uptime and use the 2nd or 3rd step in your combo just to realize the combo dropped right before you used it, wasting a GCD. Ideally there's no downtime ever unless something is untargetable, of course, and I am aware of that ^^

@Hoshiyuu - Those are some great ideas, and are actually much more along the lines of what I'd want from this tool if DRG pr NIN was implemented into it. I'm not main on DRG, I'm actually very new to it, so "training wheels" on optimizing, as you put it. Sounds amazing.

**Comment by arlarzelere3** [comment]
I feel like we should start simple or the overlay will be overwhelming.

Maybe just a better indicator of when geirskogul/nastron and dragon sight are up.

**Comment by Hoshiyuu** [comment]
@arlarzelere3 there is no need to develop features which can already be done within spending 3 minutes on special spell timer...

**Comment by arlarzelere3** [comment]
Sure, but it would be a good stepping stone to further development, such as being able to show how many nastronds you can execute with your current BotD countdown.

The big advantage to cactbot over custom spelltimers is that everything is centralized in one addon.  Same with why I like the timelines here rather than managing it all myself.

**Comment by quisquous** [comment]
I think in the future I'll still consider other things to add to jobs, but really I want somebody who's going to use it to help guide that work rather than just add things I think are interesting.
