### ISSUE TITLE
Hunt/Radar problem with Kurrea

### ISSUE THREAD

**Issue by MyTechnoHunter** [quisquous/cactbot#1808]
## Description

was in Mor Dhona, when my Triggernometry hunt triggers flagged Kurrea in the area.. Radar, did not..
all files are verified as the same on the latest github, other hunts work fine (later expansions are fine, b, a, and s from what i see) 

## Additional information
[09:59:21.895] 03:4002F0D4:Added new combatant Kurrea.  Job: N/A Level: 50 Max HP: 286134 Max MP: 10000 Pos: (261.0174,-646.4034,31.8126) (29520000003208).

03|29029|e0000000||0|0|0|0||0|1011823|0|0|0|10000|0|0|88.09033|-619.7452|28.33594|1.467227|

the above are teh added combatant lines from the log to try to replicate the issue

**Comment by quisquous** [comment]
Are you sure that's the added combatant line? Not only does it look like it's missing its id, it also has a different position?

**Comment by quisquous** [comment]
Have you seen this happen again?

**Comment by quisquous** [comment]
Closing this.  Let me know if you see this again.
