### ISSUE TITLE
Raidboss: Directions in common replacement?

### ISSUE THREAD

**Issue by MaikoTan** [quisquous/cactbot#1821]
## Summary

There are many timeline using directions like `(NW)` `(SE)` `(NE/SE)`, to specify where to handle the mechanic.

But then we should write a bunch of replacement text to localize it.

Just like:
```javascript
'\\(NE\\)': '(北東)',
'\\(NW\\)': '(北西)',
'\\(SE\\)': '(南東)',
'\\(SW\\)': '(南西)',
```

So, can we just put them into `common_replacement.js`?

Also, maybe some role-specific text like `(T)` `(DPS)`, `(T/H)`, can be put into that file, too?

**Comment by quisquous** [comment]
Sounds reasonable to me!
