### ISSUE TITLE
Missing/incorrect job specific data

### ISSUE THREAD

**Issue by ProjectOblivion** [quisquous/cactbot#1823]
DNC job detail is missing esprit information.
I believe this is one byte starting at offset 0x01, but I do not have a 76 DNC to verify.

DRK is missing Dark Arts and Living Shadow timer.
Dark Arts is one byte starting at offset 0x04.  It is a 1 or 0, presumably number of charges.
Living Shadow is two bytes starting at offset 0x06.

SAM is missing Kenki value and I believe is passing Meditation stacks as Kenki.
Kenki is one byte starting at offset 0x03.
I believe meditation stacks are one byte starting at offset 0x04, but I do not have an 80 SAM to verify.

The debug_job information does not appear to be initializing correctly for DRK/GNB.
Context:
- Switched to NIN
- Cast Huton
- Switched to DRK/GNB during Huton, debug_job did not reset to all 00
- Switched to GNB/DRK, debug_job did not reset to all 00
- Switched to PLD, debug_job reset to all 00
- Switched back to DRK/GNB, debug_job returned to previous NIN values
- Switched to WHM, debug_job reset to all 00
- Switched back to DRK/GNB, debug_job remained all 00

**Comment by ProjectOblivion** [comment]
I see the DNC detail has already been adding in #1822

**Comment by KattTails** [comment]
Thanks a lot for this, I'll look into this when I get a chance.

**Comment by KattTails** [comment]
I've added the missing job info in #1822 

> The debug_job information does not appear to be initializing correctly for DRK/GNB.
> Context:
>     * Switched to NIN
>     * Cast Huton
>     * Switched to DRK/GNB during Huton, debug_job did not reset to all 00
>     * Switched to GNB/DRK, debug_job did not reset to all 00
>     * Switched to PLD, debug_job reset to all 00
>     * Switched back to DRK/GNB, debug_job returned to previous NIN values
>     * Switched to WHM, debug_job reset to all 00
>     * Switched back to DRK/GNB, debug_job remained all 00

I think Cactbot is behaving correctly here. The bytes are just not being fully zeroed out in the game memory for certain classes. eg switching from NIN -> GNB leaves me with 00 09 00 00 00 01 00 00, but GNB only uses the 0x00, 0x02 and 0x04 bytes.

**Comment by ProjectOblivion** [comment]
Thank you for jumping on this so quickly!

I am impressed that you took the extra time to grab those couple other things as well.

**Comment by quisquous** [comment]
> > The debug_job information does not appear to be initializing correctly for DRK/GNB.
> > Context:
> > * Switched to NIN
> > * Cast Huton
> > * Switched to DRK/GNB during Huton, debug_job did not reset to all 00
> > * Switched to GNB/DRK, debug_job did not reset to all 00
> > * Switched to PLD, debug_job reset to all 00
> > * Switched back to DRK/GNB, debug_job returned to previous NIN values
> > * Switched to WHM, debug_job reset to all 00
> > * Switched back to DRK/GNB, debug_job remained all 00
> 
> I think Cactbot is behaving correctly here. The bytes are just not being fully zeroed out in the game memory for certain classes. eg switching from NIN -> GNB leaves me with 00 09 00 00 00 01 00 00, but GNB only uses the 0x00, 0x02 and 0x04 bytes.
> I verified the region in Cheat Engine and it matches Cactbot's output.

Yeah, this is my understanding as well.  The gauge is just reading from memory directly.  If memory doesn't clear it, then cactbot will still have stale data there.  I think this is fine.

I think this issue is all addressed now, so I'll close this issue.  Thanks for filing it and for fixing it!!
