### ISSUE TITLE
Jobs: Read action information from file instead of hard coding

### ISSUE THREAD

**Issue by ProjectOblivion** [quisquous/cactbot#1835]
I've created a utility to structure all of the action information available in the xivapi/ffxiv-datamining .csvs, but using it would possibly necessitate a large amount of change to how some variables are used.  I created PR #1834 with it.

I began looking at jobs about a week or two ago and the first thing I did was try to add in a class that hadn't been added yet.  One of the things I noticed is that all of the action information was hardcoded, which was already a bit unwieldy at this small scope.  Making use of the action info, even if only doing name and ID means rewriting how the data is accessed mainly due to some jobs sharing action names.  For example, SMN and SCH both have Aetherpact, but with very different function and attributes.

This will also make it easier to update come major action/class updates.

**Comment by quisquous** [comment]
As I discussed on that PR, I think it could be reasonable to write some automated script to generate names and solve collisions, but the approach of separating out abilities by class makes it very hard to use.  I am going to close this old feature request just to clean up the set of active issues, but am happy to rediscuss here or on the PR.
