### ISSUE TITLE
I have created a vscode extension

### ISSUE THREAD

**Issue by MaikoTan** [quisquous/cactbot#1846]
[cactbot-highlight](https://github.com/MaikoTan/cactbot-highlight)
Here is the repository URL.

As quisquous said in [issue (comment)](https://github.com/quisquous/cactbot/pull/1834#issuecomment-703332443), I try to create an extension for highlighting in VSCode.

This is my first time to create a VSCode extension, it is not very robust.
If you have some suggestion or bug report, feel free to send me an issue.

`cactbot-highlight` now available in [Visual Studio Market](https://marketplace.visualstudio.com/items?itemName=MaikoTan.cactbot-highlight)!

**Comment by JLGarber** [comment]
This looks really nice. I'm actually in the middle of putting a dungeon package together right now, so I'll finish compiling that with this extension enabled and let you know what I come across. The timeline highlighting looks like it could be extremely helpful!

**Comment by quisquous** [comment]
This looks *really* nice.  Maybe I should finally stop using Notepad++ and start using VSCode.  I think my only feedback from the gifs is that translations come later and omitting them lets the tools find when they are missing.  So, I don't think I would ever add every language at once to a trigger.

If you want to send a pull request to add it to the `CONTRIBUTING.md` (or anywhere else you think it would be good to mention), I'd be happy to add a link.

**Comment by MaikoTan** [comment]
> I think my only feedback from the gifs is that translations come later and omitting them lets the tools find when they are missing. So, I don't think I would ever add every language at once to a trigger.

They are just `snippets` and configurable in [snippets/trigger.js.code-snippets](https://github.com/MaikoTan/cactbot-highlight/blob/master/snippets/trigger.js.code-snippets) file. I can't recall which snippets are useful, so I just wrote down some "examples", you can provide some suggestions for which can be added in and which not.

In fact, I think the most thing that we need is `Intellisense`, maybe it is time to migrate cactbot to modern JavaScript with JSDoc and module system (like CommonJS) ?

> If you want to send a pull request to add it to the `CONTRIBUTING.md` (or anywhere else you think it would be good to mention), I'd be happy to add a link.

Yeah, sure of course.
But you know I am Asian, my English is not very well as native. I am afraid that I write something wrong in the document. (´。＿。｀)

**Comment by quisquous** [comment]
> In fact, I think the most thing that we need is `Intellisense`, maybe it is time to migrate cactbot to modern JavaScript with JSDoc and module system (like CommonJS) ?

Modules are trickier since you can't use modules from `file://` schemes.  I need to look into more, but I think I can use webpack to bundle modules together and then have the html page include just the bundle with a `<script>` tag.  This will require some more setup work for cactbot developers in their development environments, but I think is probably the best way forward.  I've been resisting webpack somewhat because I didn't want to add that overhead, but I think we finally need to do it some.  In summary, I would like to get to using modules so that we can import code more reasonably.

As for JSDoc and Intellisense, I think it might make more sense to move to TypeScript, which would turn a lot of that parameter and type documentation into type annotations that could be enforced and that intellisense would know about automatically.  That transition can also be done incrementally.

> But you know I am Asian, my English is not very well as native. I am afraid that I write something wrong in the document.

I can add a link myself then, if that's easier for you.

**Comment by panicstevenson** [comment]
> > If you want to send a pull request to add it to the `CONTRIBUTING.md` (or anywhere else you think it would be good to mention), I'd be happy to add a link.
> 
> Yeah, sure of course.
> But you know I am Asian, my English is not very well as native. I am afraid that I write something wrong in the document. (´。＿。｀)

1. Please don't feel that way; no one here will judge anything (this is in the repository's code of conduct), and nothing "wrong" will make it passed a review. 😊

2. I know @quisquous' VSCode-fu is a little weak (I've been telling them to swap for like a year!), but I also wanted to point out there's a few things you can do with the `.vscode` folder, like sharing debug setups, editor settings, and recommended extensions. I was going to mention it since we had brought up [editorconfig](https://editorconfig.org/) in the past, and it can become a recommended installation with:

```
{
  "recommendations": [
    "editorconfig.editorconfig"
  ]
}
```

Theoretically this could be added there as well (along with things like eslint), but I don't really want to shove that on anyone if that's a little much at this time.

**Comment by quisquous** [comment]
> > But you know I am Asian, my English is not very well as native. I am afraid that I write something wrong in the document.
> 
> 1. Please don't feel that way; no one here will judge anything (this is in the repository's code of conduct), and nothing "wrong" will make it passed a review. 

I want to strongly agree with this!  If there is documentation that is missing, please feel encouraged to send improvements even if you're not sure of the best way to word something.  That's what reviews are for.  :)

**Comment by MaikoTan** [comment]
> > > But you know I am Asian, my English is not very well as native. I am afraid that I write something wrong in the document.
> > 
> > 
> > 
> > 1. Please don't feel that way; no one here will judge anything (this is in the repository's code of conduct), and nothing "wrong" will make it passed a review.
> 
> I want to strongly agree with this! If there is documentation that is missing, please feel encouraged to send improvements even if you're not sure of the best way to word something. That's what reviews are for. :)

Okay, Thank you all.
I'll try to add a section in `CONTRIBUTING.md` myself to describe the extension.

**Comment by Jaehyuk-Lee** [comment]
I tried it, I could use auto-maker(?) thing, shortcut thing.
![K-002](https://user-images.githubusercontent.com/4695371/95334576-456b6380-08e9-11eb-9929-149246147cb0.png)

But, I couldn't see coloring timeline.
![K-003](https://user-images.githubusercontent.com/4695371/95334590-4a301780-08e9-11eb-9cb5-511d1e3ae756.png)

Do you know why?

**Comment by MaikoTan** [comment]
> But, I couldn't see coloring timeline.
> ![K-003](https://user-images.githubusercontent.com/4695371/95334590-4a301780-08e9-11eb-9cb5-511d1e3ae756.png)
> 
> Do you know why?

Oh, you should click "Plain Text" button at right of the bottom status bar, and then select "cactbot-timeline" in the prompt dialog window.
You can also select "Configure file associasion", and associate all the txt file with my highlight solution.

It is because timeline file is `*.txt`, VSCode recognize it as Plain Text file before my extension enabled.

**Comment by Jaehyuk-Lee** [comment]
oh, great.
Is there anyway to set vscode option to recognize every txt file for cactbot-timeline? project specific. (I know that there's `.vscode` file for storing project options.)

**Comment by MaikoTan** [comment]
Yes, you can add this to your `.vscode/settings.json` file.

```json
    "files.associations": {
        "*.txt": "cactbot-timeline"
    }
```

**Comment by Jaehyuk-Lee** [comment]
oh thanks! I think it's good to have that information on [cactbot-highlight](https://github.com/MaikoTan/cactbot-highlight)'s readme.

**Comment by MaikoTan** [comment]
> oh thanks! I think it's good to have that information on [cactbot-highlight](https://github.com/MaikoTan/cactbot-highlight)'s readme.

(；・∀・) Sure!
But I'll add it tomorrow because I am on bed now.

**Comment by MaikoTan** [comment]
**`cactbot-highlight` now on 0.0.3!**

#### New feature:

Adjust time with one click:

- Select lines that you want to change the time
- Right-click and select "Adjust Time By ..."
- Input how much do you want
- Press Enter (；´∀｀)

Ping me if you got issues !!

**Comment by MaikoTan** [comment]
## 0.0.4 now

I invoke `python util/check_translation.py` and make it easier for using.

Besides, there is a new setting option for this new feature.

Add `"cactbot.timeline.defaultLocale": "ja"` to your `.vscode/settings.json`, then the prompt window for asking locale would not show anymore.
Delete the option or set it as null would recover the prompt back.

![translate-timeline](https://github.com/MaikoTan/cactbot-highlight/blob/master/images/translate-timeline.gif?raw=true)

**Comment by Jaehyuk-Lee** [comment]
oh wow that's amazing thanks!

**Comment by MaikoTan** [comment]
By the way, @quisquous can I use this image as the extension's logo?
I think to make them consistent would easy to recognize.
![](https://raw.githubusercontent.com/quisquous/cactbot/main/screenshots/cactbot-logo-320x320.png)

**Comment by quisquous** [comment]
Yes, feel free to reuse the logo!

I know you said you didn't want to upload it to the marketplace, but would it make sense to? I think that way this could be added to cactbot as a recommended extension.

**Comment by Jaehyuk-Lee** [comment]
translating timeline to `ko` is not working well.

this is `e8s.txt` translation to `ko`
```
### Eden 8 (Savage)
# Eden's Verse: Refulgence
#  -p 4DCC:16 4D74:213 4D79:368.6 -ii 4DA8 4D9C 4D95 4D9A 4DA9 4DA8 4DCD 4DAB 4D84 4E19 4D98 4E3C 4D7A 4DCF 4DAF 4D91 4DA7 4D88 4FD8

hideall "--Reset--"
hideall "--sync--"

0.0 "--Reset--" sync / 21:........:40000010:/ window 10000 jump 0 #MISSINGSYNC

0.0 "--sync--" sync /:Engage!/ window 0,1 #MISSINGSYNC
1.5 "--sync--" sync /:�ù�:4D59:/ window 2,0
16.0 "���뿵��" sync /:�ù�:4DCC:/ window 17,20
27.2 "�ſ� ����" sync /:�ù�:4D5A:/
39.3 "���� ����/�ϰ�" sync /:�ù�:4D6[67]:/
44.4 "�ݻ�� ����/�ϰ� (�ʷ�)" sync /:���� �ſ�:4DB[78]:/
49.4 "�ݻ�� ����/�ϰ� (����)" sync /:���� �ſ�:4DC[34]:/

### Diamond Frost
57.5 "--middle--" sync /:�ù�:4D58:/ #MISSINGTEXT
63.7 "���̾Ƹ�� ����Ʈ" sync /:�ù�:4D6C:/
71.9 "������" sync /:�ù�:4D9B:/
74.9 "���帧 ����" sync /:�ù�:4DA0:/
76.9 "õ���� �ϰ�" sync /:�ù�:4D61:/
78.9 "���帧 ����" sync /:�ù�:4DA0:/
80.9 "�����ٴ�" sync /:�ù�:4D9D:/
80.9 "��������" sync /:�ù�:4D9E:/
82.9 "���帧 ����" sync /:�ù�:4DA0:/
83.9 "���� ���� 1" #sync /:�ù�:4D9F:/
85.9 "���� ���� 2" #sync /:�ù�:4D9F:/
87.9 "���� ���� 3" #sync /:�ù�:4D9F:/
92.9 "���� �ϰ�/����" sync /:�ù�:4D6[67]:/
101.7 "���� Ÿ��" sync /:�ù�:4D65:/
115.0 "���� ����" sync /:�ù�:4DD1:/
123.0 "��������/������" sync /:�ù�:4D6[DE]:/

### Light Rampant
131.2 "--middle--" sync /:�ù�:4D58:/ #MISSINGTEXT
137.4 "���� ����" sync /:�ù�:4D73:/ window 150,10
148.6 "ħ�ı�" sync /:�ù�:4DA2:/
148.6 "���� �ĵ�" sync /:�ù�:4D63:/
156.6 "ħ�ı�" sync /:�ù�:4DA2:/
159.8 "���� �ĵ�" sync /:�ù�:4D63:/
164.7 "ħ�ı�" sync /:�ù�:4DA2:/
173.0 "�ſ� ����" sync /:�ù�:4D5A:/
185.2 "������/��������" sync /:�ù�:4D6[DE]:/
190.2 "�ݻ�� ��/�������� (�ʷ�)" sync /:���� �ſ�:4DB[9A]:/
193.3 "��Ͻð�" sync /:�ù�:4D8[01]:/

### Adds Phase
201.5 "--untargetable--" #MISSINGTEXT
201.7 "--sync--" sync /:�ù�:4D58:/
213.0 "�дܵ� ����" sync /:�ù�:4D74:/ window 220,20
229.2 "������ ����" sync /:��Ӵ� ũ����Ż:4DAC:/
238.9 "�ε��� 1" sync /:�� ���׸�:4D86:/
243.3 "������ ����" sync /:��Ӵ� ũ����Ż:4DAC:/
253.0 "�ε��� 2" sync /:�� ���׸�:4D86:/
257.4 "������ ����" sync /:��Ӵ� ũ����Ż:4DAC:/
267.1 "�ε��� 3" sync /:�� ���׸�:4D86:/
271.5 "������ ����" sync /:��Ӵ� ũ����Ż:4DAC:/
281.2 "�ε��� 4" sync /:�� ���׸�:4D86:/
292.6 "���� �Ҹ�" sync /:�ù�:4DAD:/ window 100,100

### Dragon Fanfic
# :eyes:

### Wing Mirrors
350.5 "--targetable--" #MISSINGTEXT
364.2 "--sync--" sync /:4D79:�ù�/ window 370,10
368.6 "��ũ �� x3" sync /:�ù�:4D79:/ duration 3.1
378.0 "�� ����" sync /:�ù�:4D7B:/
389.4 "�ſ� ����" sync /:�ù�:4D5A:/
396.9 "--sync--" sync /:�ù�:4D58:/
403.2 "�ż��� ����" sync /:�ù�:4D7[56]:/
403.2 "�ݻ�� �ż��� ���� (�Ķ�)" sync /:���� �ſ�:4D9[01]:/
408.2 "�ݻ�� �ż��� ���� (�ʷ�)" sync /:���� �ſ�:4DB[BC]:/
413.2 "�ż��� ����" sync /:�ù�:4D7[56]:/
413.2 "�ݻ�� �ż��� ���� (����)" sync /:���� �ſ�:4DC[78]:/

### Wyrm's Lament
421.7 "--middle--" sync /:�ù�:4D58:/ #MISSINGTEXT
427.9 "������ ��ȿ" sync /:�ù�:4D7C:/
441.0 "�ż��� ����" sync /:�ù�:4D7[56]:/
449.1 "�ż��� ����" sync /:�ù�:4D7[56]:/
457.2 "�ż��� ����" sync /:�ù�:4D7[56]:/
465.3 "�ż��� ����" sync /:�ù�:4D7[56]:/
473.5 "���� ����" sync /:�ù�:4DD0:/
481.4 "����/������ �ְ˱�" sync /:�ù�:4D6[89]:/
483.5 "����/������ �ְ˱�" sync /:�ù�:4D6[AB]:/
491.6 "���� Ÿ��" sync /:�ù�:4D65:/
504.8 "���� ����" sync /:�ù�:4DD2:/
507.3 "��ũ ����" sync /:�ù�:4D99:/

### Stack Mirrors
516.1 "�ſ� ����" sync /:�ù�:4D5A:/
523.6 "--teleport--" sync /:�ù�:4D58:/ #MISSINGTEXT
530.0 "�ż��� ����" sync /:�ù�:4D77:/
535.1 "�ݻ�� �ż��� ���� (�ʷ�)" sync /:���� �ſ�:4DBD:/
540.1 "�ݻ�� �ż��� ���� (����)" sync /:���� �ſ�:4DC9:/

### Lookaway Mirrors
554.1 "�ſ� ����" sync /:�ù�:4D5A:/
566.6 "���� ����" sync /:�ù�:4DD1:/
566.6 "�ݻ�� ���� ���� (�Ķ�)" sync /:���� �ſ�:4D8A:/
571.7 "�ݻ�� ���� ���� (�ʷ�)" sync /:���� �ſ�:4DB5:/
576.7 "�ݻ�� ���� ���� (����)" sync /:���� �ſ�:4DC1:/
577.6 "Ȧ��" sync /:�ù�:4D8[23]:/
585.7 "�ؾ�/�þ��� ������" sync /:�ù�:4D(6F|70):/
589.8 "�þ�/�ؾ��� ������" sync /:�ù�:4D7[12]:/

### Akh Rhai Mirrors
600.9 "�ſ� ����" sync /:�ù�:4D5A:/
608.1 "���� ����" sync /:�ù�:4DD2:/
610.6 "��ũ ����" sync /:�ù�:4D99:/
618.2 "�ݻ�� ���� ����" sync /:���� �ſ�:4DC2:/
620.4 "��ũ �� x4" sync /:�ù�:4D79:/ duration 4.2
620.7 "��ũ ����" sync /:�ù�:4D99:/
630.8 "�� ����" sync /:�ù�:4D7B:/

### Icelit Dragonsong
648.8 "--middle--" sync /:�ù�:4D58:/ #MISSINGTEXT
655.4 "������ ���� ���" sync /:�ù�:4D7D:/
663.6 "������" sync /:�ù�:4D9B:/
666.6 "ħ�ı�" sync /:�ù�:4DA2:/
668.6 "���� �ϰ�" sync /:�ù�:4D62:/
669.3 "--knockback--" #MISSINGTEXT
672.7 "�����ٴ�" sync /:�ù�:4D9D:/
674.7 "ħ�ı�" sync /:�ù�:4DA2:/
676.7 "���� ���� 1" #sync /:�ù�:4D9F:/
676.8 "��Ͻ�" sync /:�ù�:4D7[EF]:/
678.7 "���� ���� 2" #sync /:�ù�:4D9F:/
680.8 "���� ���� 3" #sync /:�ù�:4D9F:/
682.7 "���α�" sync /:�ù�:4DA3:/
688.0 "���� ����" sync /:�ù�:4D64:/
688.9 "���� �ĵ�" sync /:�ù�:4DA1:/

### Ice Mirror
699.6 "�ſ� ����" sync /:�ù�:4D5A:/
709.9 "���� ����" sync /:�ù�:4DD0:/
719.9 "�ݻ�� ���� ���� (�ʷ�)" sync /:���� �ſ�:4DC0:/
720.4 "���� ����" sync /:�ù�:4DD2:/
722.9 "��ũ ����" sync /:�ù�:4D99:/

### Wyrm's Lament Take 2
732.1 "--middle--" sync /:�ù�:4D58:/ #MISSINGTEXT
738.3 "������ ��ȿ" sync /:�ù�:4D7C:/
745.5 "��ũ �� x5" sync /:�ù�:4D79:/ duration 5.3
757.1 "�� ����" sync /:�ù�:4D7B:/
764.3 "��ũ �� x6" sync /:�ù�:4D79:/ duration 6.4
777.0 "�� ����" sync /:�ù�:4D7B:/
784.3 "��ũ �� x7" sync /:�ù�:4D79:/ duration 7.5
798.1 "�� ����" sync /:�ù�:4D7B:/

### Enrage Mirrors
817.1 "�ſ� ����" sync /:�ù�:4D5A:/
819.2 "--teleport--" sync /:�ù�:4D58:/ #MISSINGTEXT
830.6 "�ż��� ����" sync /:�ù�:4D78:/
840.8 "Enrage" sync /:���� �ſ�:4DC[AB]:/ #MISSINGTEXT

```

**Comment by MaikoTan** [comment]
@Jaehyuk-Lee You might need to download the new version, @Echoring has reported this issue too.

I guess it is related [this](https://stackoverflow.com/questions/20731785/wrong-encoding-when-using-child-process-spawn-or-exec-under-windows), so I abandoned the "python-invoking" solution, and try to "JavaScript-ize" it.

**Comment by MaikoTan** [comment]
> I know you said you didn't want to upload it to the marketplace, but would it make sense to? I think that way this could be added to cactbot as a recommended extension.

Well...sounds reasonable. (*´ω｀*)

But I got a qualification exam these days, I would follow it later.

**Comment by Jaehyuk-Lee** [comment]
ah yes translation is fixed

**Comment by MaikoTan** [comment]
Just for annoucing, `cactbot-highlight` now available in [Visual Studio Market](https://marketplace.visualstudio.com/items?itemName=MaikoTan.cactbot-highlight)!

![image](https://user-images.githubusercontent.com/19927330/95754312-6d860880-0cd5-11eb-8a55-5a19a8b3c299.png)

**Comment by Jaehyuk-Lee** [comment]
is timeline translation working well with market place version? I'm having a bug.

**Comment by MaikoTan** [comment]
> is timeline translation working well with market place version? I'm having a bug.

At least it worked on my computer...
Feel free to report bugs that you got.

But I am going to close this issue.
Please come to my repo and open a new issue. So I can easily track it.
