### ISSUE TITLE
[Help] RaidBoss Timeline & Text Alerts Separation

### ISSUE THREAD

**Issue by Krojack** [quisquous/cactbot#185]
RaidBoss works however my Timelines and Test Alerts are stacked.  In the screenshot I see Text in the middle while Timelines are off to the side.  I want mine like this but can't figure out how to do that.  Can I get some help with this? Thanks.

**Comment by quisquous** [comment]
Yeah, let me try to explain what you need to do.  You can get this by unlocking the overlay (so that there's a blue background and the test timelines appear), then resizing the plugin (by clicking and dragging the lower right corner of the overlay), and then relocking the plugin again.

Let me know if that's not clear or if that's not what you're looking for.  :)

**Comment by imynwulf** [comment]
I made a quick little video using your instructions. You can find it at [https://i.imgur.com/N7xbEbj.mp4](https://i.imgur.com/N7xbEbj.mp4). The video assumes the user has already gotten the plugin installed and the overlay setup.

**Comment by Krojack** [comment]
Yeah quisquous was enough to understand.  I though tthere was a way to make them 2 separate items.  Still not crazy for the placement but hey, it is what it is. =)

**Comment by quisquous** [comment]
You can make them separate with a **user/raidboss.css** file and use some css to adjust where the timeline vs the triggers are, if you have some other preference.

**Comment by Krojack** [comment]
I was able to get exactly what I wanted by editing the .css and changing
`#timeline-container {
  position: absolute;
  top: 0px;
  left: 0px;
.....`
to
`#timeline-container {
  position: fixed;
  bottom: 0px;
  left: 0px;
.....`
Real simple fix.

**Comment by quisquous** [comment]
:+1:

Glad you got it sorted!  I would recommend pasting that block into your **cactbot/user/raidboss.css** file and not directly editing **cactbot/ui/raidboss/raidboss.css**, which will get overwritten in the next update.
