### ISSUE TITLE
New version not updating.

### ISSUE THREAD

**Issue by larserus** [quisquous/cactbot#186]
Hello. I am attempted to update to the UwU update, however my plugin consistently shows me this error in the log:

14/07/2018 16:39:02: Error: Cactbot: There is a new version of Cactbot is available at: 
https://github.com/quisquous/cactbot/releases/latest 

New version 0.7.3 
Current version 0.6.5.0

Even when removing the files and freshly installing I get this error.

**Comment by quisquous** [comment]
Sorry for the belated response.

Are you downloading the cactbot-0.7.3.zip link from https://github.com/quisquous/cactbot/releases/tag/v0.7.3?

Does the log print out the paths for the DLLs? (I can't remember what version this was added in.) If so, can you copy and paste it here?

Finally, if you right click the cactbot dll in your ACT/OverlayPlugins/addons/ folder, what does it say for version there?

**Comment by larserus** [comment]
Hello, thanks for the reply.

I managed to work out the problem - it was because ACT was drawing on an
update for the overlayplugin. I updated that and it brought everything in
line.

Apologies for wasting your time!

**Comment by quisquous** [comment]
No worries at all! Glad you got it sorted.  :)
