### ISSUE TITLE
Emulator: Encounters not splitting correctly across zone seals

### ISSUE THREAD

**Issue by JLGarber** [quisquous/cactbot#1877]
It looks like the logic that handles zone seals/unseals for the emulator is somewhat non-functional. Various different dungeons (including Baelsar's Wall, Bardam's Mettle, Fractal Continuum (hard), and Heroes' Gauntlet) either are recorded as one long encounter, or have only two encounters.

https://cdn.discordapp.com/attachments/760609440742899723/766194321061445632/unknown.png
https://cdn.discordapp.com/attachments/760609440742899723/766194571239096350/unknown.png
https://cdn.discordapp.com/attachments/760609440742899723/766194815041404948/unknown.png

As you can see, zone sealing/unsealing doesn't seem to be working correctly. One anomaly that I noticed in my logs is that in the ACT main interface, some boss encounters don't seem to have the zone seal message, even though it's present in the network log.

There's probably more to add for this, but it's late on the east coast and it's probably better to sleep on it and add pertinent information as it's asked for.

**Comment by quisquous** [comment]
I think ACT trims your logs to the first attack in each encounter, and so if the zone seal message is delivered before your attack, it won't show up in the encounter view, even though it's in your log.

Am I right in understanding here that Qitana Ravel is working fine, but the various dungeons you've listed above don't work?

Also cc @valarnin FYI

**Comment by JLGarber** [comment]
See, that puzzles me. The Qitana logs have all three bosses represented, but if you look at the durations for each encounter, both Lozatl and Eros are obviously wrong. So far this zone seal issue seems to have been affecting every dungeon run I've participated in for at least the last couple of weeks.

As for the theory on the zone seal being delivered outside of combat, that would a nice solution, but I *think* it's not the case. A recent run through Heroes' Gauntlet showed this:
https://cdn.discordapp.com/attachments/760609440742899723/766905376280936458/Broken_Heroes_Gauntlet_1.png
(Apologies for linking images, Github is not being nice about direct uploads.)

This was generated even though my log had *very* clear zone seal lines for each encounter:
```
[23:17:30.873] 15:........:TANK:E38:Plunge:40014126:Spectral Thief:ETC
[23:17:30.000] 00:0839:The Mount Argai Mines will be sealed off in 15 seconds!
[23:19:28.000] 00:0839:The Mount Argai Mines is no longer sealed!

[23:22:08.786] 15:........TANK:1D6D:Provoke:4001435B:Spectral Necromancer:ETC
[23:22:09.000] 00:0839:The Summer Ballroom will be sealed off in 15 seconds!
[23:24:00.000] 00:0839:The Summer Ballroom is no longer sealed!

[23:27:06.572] 15:........TANK:E28:Unmend:40014638:Spectral Berserker:ETC
[23:27:07.000] 00:0839:The Illuminated Plaza will be sealed off in 15 seconds!
[23:29:55.000] 00:0839:The Illuminated Plaza is no longer sealed!
```

Based on reviewing other encounters, both trials and raid zones, I'm confident there's an issue with zone seals specifically. TEA and EX trials are correctly splitting by encounter.

**Comment by valarnin** [comment]
Is the `Start Status` blank for all encounters that are not correct in raidemulator?

**Comment by JLGarber** [comment]
No. Specifically in that Qitana log, the only "correct" one is Batsquatch. Lozatl does show a zone seal, but then dumps the playback at the start of the Batsquatch encounter. Eros just doesn't show a start condition. None of the Heroes' Gauntlet encounters show a start condition for me.

 I've sent you a logfile that contains some of the encounters in the screenshots linked here. Not sure whether there's anything in there, but it might help?

**Comment by valarnin** [comment]
The specific issue here is with NetRegexes' areaSeal regex, and underlying it the `{Name}` macro.
https://github.com/quisquous/cactbot/blob/9dce2742eeaec053e4fe3c3ca9ef953407129a08/resources/translations.js#L50-L51
https://github.com/quisquous/cactbot/blob/9dce2742eeaec053e4fe3c3ca9ef953407129a08/resources/regexes.js#L595

Checking via debug tools, areaSeal is:
```javascript
LocaleNetRegex.areaSeal.en
/^(?<type>00)\|(?<timestamp>[^|]*)\|(?<code>[^|]*)\|(?<name>[^|]*)\|(?<line>(?<area>[^\s:|]+(?: [^\s:|]+)?) will be sealed off in (?<time>-?[0-9]+(?:[.,][0-9]+)?(?:E-?[0-9]+)?) seconds![^|]*?)\|/i
```

The `<name>` capturing regex will match `Some Subarea`, but not `Some Long Named Subarea`, because it only matches two words. This can be verified by comparing to the network line for the seal for the last area of Qitana:

```javascript
let a = "00|2020-10-15T02:26:14.0000000-04:00|0839||The Song of Ox'Gatorl will be sealed off in 15 seconds!|8a94f5e008bb6677c30c893132ff8ad1";
// Original regex
let b = /^(?<type>00)\|(?<timestamp>[^|]*)\|(?<code>[^|]*)\|(?<name>[^|]*)\|(?<line>(?<area>[^\s:|]+(?: [^\s:|]+)?) will be sealed off in (?<time>-?[0-9]+(?:[.,][0-9]+)?(?:E-?[0-9]+)?) seconds![^|]*?)\|/i
// Regex with asterisk added to match more words
let c = /^(?<type>00)\|(?<timestamp>[^|]*)\|(?<code>[^|]*)\|(?<name>[^|]*)\|(?<line>(?<area>[^\s:|]+(?: [^\s:|]+)*?) will be sealed off in (?<time>-?[0-9]+(?:[.,][0-9]+)?(?:E-?[0-9]+)?) seconds![^|]*?)\|/i
console.log(b.test(a),c.test(a))
false true
```

Given that `{Name}` is also used to match player names and enemy names, there may be some issues with changing the underlying regex across the board. It might make sense to add a new macro `ZoneName` instead.

There's also the still-unanswered question of what to do with trash pulls between boss fights in dungeons. RaidEmulator could split those into `Trash` encounters in the view, but then how do we treat the situation where trash gets pulled into the boss fight? Just end the `Trash` pull when the boss fight start condition is met?

**Comment by JLGarber** [comment]
Thanks so much for all of that. As far as fixing zone seals, I think we probably would be best off with a new macro there. It wouldn't change anything for the majority of users, and it's unlikely to break much for those who do use the `name` macro.

For trash, my feeling is that we 100% want to break encounters on zone seal, no matter what. But that's because I'm coming at this solely from a timeline writer's point of view. On the flip side of that, I think it's mostly moot. For the vast majority of post-Heavensward content, boss rooms are locked until after all preceding trash is cleared. I feel like attempting to support what's already a relatively small pool of content, and growing proportionally smaller every patch, isn't really worth it.

**Comment by valarnin** [comment]
I tracked this issue back to this commit:
https://github.com/quisquous/cactbot/commit/845ec5ed403d058a465599b716ab10bcf0fb8889

Which changed the match from "any amount of words" to "one to two words", FYI.

**Comment by quisquous** [comment]
Ohhhhh.  `\y{Name}` is just meant to be player name, not "any name including zone names".  Sorry, I should have caught that when I looked at the zone sealing messages.

**Comment by quisquous** [comment]
> For trash, my feeling is that we 100% want to break encounters on zone seal, no matter what. But that's because I'm coming at this solely from a timeline writer's point of view. On the flip side of that, I think it's mostly moot. For the vast majority of post-Heavensward content, boss rooms are locked until after all preceding trash is cleared. I feel like attempting to support what's already a relatively small pool of content, and growing proportionally smaller every patch, isn't really worth it.

Yeah, I generally don't feel like trash is worth handling specially.  There's very few triggers for them, and it's never anything more complicated than "here is an ability, make a callout".  I have never had an instance where I wanted to test out trash pulls in a raid emulator.
