### ISSUE TITLE
Cactbot: Question? Request? Not sure.

### ISSUE THREAD

**Issue by Vezko** [quisquous/cactbot#188]
First of all let me thank you for all the work you have done so far with cactbot. It's an amazing tool.  
  
Now to my question or request however you want to call it:  
  
It's regarding the titan jails in Ultimate Ultima Weapon. Not too long ago I've watched a stream where the jails got marked automatically with some sort of trigger. Is it possible to make that work with cactbot as well?

**Comment by Vezko** [comment]
Alright, thanks. Your reasoning makes perfect sense.

Just wanted to ask, because even tho my group and I are far beyond that progression already, the jails are still causing a lot of wipes. 

And sadly not everyone can use Cactbot as there are people playing on PS4. :(

**Comment by quisquous** [comment]
We've had good luck with just one person calling out the order that cactbot gives in voice comms and going from there.  Sorry that I don't have anything better for you.

And I'm not sure what you mean about hoping the other trigger doesn't go viral.  It's an interesting tool, and I have no problem with other people making something like that.  I'm just not sure it's what I want cactbot to do.  I looked around for you, but all I could dig up where like two or three various plugins and scripts that all did some variant on what cactbot does already.

I hear you can make triggernometry hit buttons in game for you.  I suspect the way people do it is to have eight macros on some hidden hotbar tied to button presses (one for each party member) that all mark that person.  I think the attack marks all count up, so if you just hit the three buttons associated with those party members then all three will be marked 1 2 3.
