### ISSUE TITLE
Not getting Invuln/Provoke/Shirk alerts as healer

### ISSUE THREAD

**Issue by Marisaaaaaa** [quisquous/cactbot#1884]
A few months ago I noticed an issue came up where I'm no longer getting any alerts when a tank uses an invuln/provoke/shirk anymore like I used to. I still get these alerts when I'm on a tank job, but when I heal I get nothing. Is this a setting I need to enable?

**Comment by MaikoTan** [comment]
It Was originally designed like this.
You would only get alert when you are tank or you are in an alliance.

**Comment by Marisaaaaaa** [comment]
I distinctly remember getting these alerts in the past playing as a healer which allowed me to adjust as needed.

Regardless, I am not getting these alerts. How do I enable them as a healer?

**Comment by MaikoTan** [comment]
Oh sorry.
You mean you did not get alerts when you are a healer and a tank uses invuln like Hallowed Field?


If you don't like the original mechanics, you can copy the trigger code (for those you mentioned above, they are in `ui/raidboss/data/00-misc/general.js` ) to your `cactbot/user/raidboss.js` file and modify it.
Here is a guide for this. https://github.com/quisquous/cactbot/blob/main/docs/AdvancedCactbot.md

**Comment by quisquous** [comment]
You can do something like https://github.com/quisquous/cactbot-user/blob/master/raidboss.js#L249-L289 in your `cactbot/user/raidboss.js` file to enable these.  I think it probably makes sense to enable these for healers though, so I'll go ahead and do that.
