### ISSUE TITLE
Add ability to modify trigger text duration from user trigger overrides.

### ISSUE THREAD

**Issue by liaoarden** [quisquous/cactbot#1889]
Since https://github.com/quisquous/cactbot/issues/1869 is coming, one thing that got mentioned in discussion is users modifying the `${ENCOUNTER}.js` files themselves with each release and wanting users to move to per-trigger overrides.

One thing I've been doing is extending duration of certain triggers in UCoB for Nael for the quotes on moving in or out, because my brain immediately spaces sometimes and having an additional second or two of it on screen can jolt me into moving correctly.

Currently the documentation for per-trigger overrides doesn't seem to support that based on https://github.com/quisquous/cactbot/blob/main/docs/AdvancedCactbot.md#per-trigger-options.

**Comment by quisquous** [comment]
I think there's a couple options here.  We could add duration to the config ui.  Alternatively you can wait for #1786, which will make it easier to copy and paste triggers into your `cactbot/user/raidboss.js` file and edit the duration in there.

**Comment by quisquous** [comment]
You should be able to use https://github.com/quisquous/cactbot/blob/main/docs/CactbotCustomization.md#overriding-raidboss-triggers to add a copy of the triggers to your user/raidboss.js file and add an additional duration line for each of them.  Let me know if you run into trouble.

**Comment by liaoarden** [comment]
Sounds goods, I'll try that out the implicit trigger overrides. 

That does make me a little bit sad since that means that upstream changes to the changes will just get overridden but c'est la vie.

As an aside does this break any existing explicit trigger overrides? I see that's no longer listed in the customization?

**Comment by quisquous** [comment]
I think this is your best bet in the short term.  I can add this to the config UI too, but that will likely take me a while to get to.  I would be happy to take a pull request.

And no, it doesn't break existing explicit `PerTriggerOptions` overrides.  I just removed the documentation, as I think trigger overrides cover almost everything you'd want to do with them, and I thought it'd be clearer to most people who are editing via copy and paste and aren't JavaScript programmers.

**Comment by liaoarden** [comment]
Sounds good, do you have issue for the UI enhancements? 

That makes sense to me!
