### ISSUE TITLE
Bug reports (Easter Egg? | Intended?) + Feature request

### ISSUE THREAD

**Issue by Vezko** [quisquous/cactbot#189]
~~Bug 1 (Easter Egg?): Starting a pull timer on the S Rank Croque-Mitaine makes Cactbot go crazy.~~
  
Bug 2 (Intended?): No trigger (or not working) for the gaol on Ultima Surpression. There's a tactic where the group moves as a whole making it sometimes hard to see if you have the gaol.  
  
Feature request: Is it possible to make Cactbot somehow reset? If a pull timer goes through on a canceled pull, Cactbot just starts and goes through the timeline. Either a wipe or ACT refresh/restart is needed.  
  
If there is a reset already tho, then I somehow missed it and apologize for it.

**Comment by quisquous** [comment]
Bug 1: What do you mean by go crazy? And you can't really start a pull timer "on" something, so I'm not quite sure what you mena.

Bug 2: I added a trigger (untested) for that recently, but I haven't released a new version yet.  If you grab https://github.com/quisquous/cactbot/archive/master.zip and then copy the **ui/** and **resources/** folders on top of the ones in your cactbot folders, you should get them.

`/echo cactbot wipe` resets some things, but I'm not sure that it resets timelines.  I'll take a look and add something like that.  I usually just reload the raidboss overlay.

**Comment by Vezko** [comment]
It's just as I meant. Once the pulltimer goes through, Cactbot just goes insane with random spells and timers all over the place. It's not a serious issue as it doesn't happen everytime which is why I thought it was an Easter Egg or some sort. Sadly it died on my server not too long ago and I would need to wait for it's next spawn to show it to you. 😅

**Comment by Wyti** [comment]
For bug1 I would guess its more about the S rank being in Middle La Noscea than the boss itself.
I guess what you're seeing is the testing feature to test cactbot functionalities outside of raids.

**Comment by quisquous** [comment]
Oh yeah yeah yeah, Middle La Noscea is the test zone.  Doing a countdown there starts all the test timers.  :innocent:

**Comment by Vezko** [comment]
That would explain it then. 😁

**Comment by quisquous** [comment]
Ok, I think all of these are fixed now (other than the Middle La Noscea, which I'm just going to leave).
