### ISSUE TITLE
timeline line with duration + sync skips the duration

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#19]
e.g. 1251.5 "Control Tower x2" duration 13.5 sync /:Hashmal, Bringer Of Order starts using Control Tower on Hashmal/ window 10,10

It only does the sync but no duration.

**Comment by xephero** [comment]
This actually happens regardless of duration; if the line is used on a sync, it will immediately disappear, even disregarding Options.KeepExpiredTimerBarsForSeconds.
