### ISSUE TITLE
Error loading cactbotoverlay.dll

### ISSUE THREAD

**Issue by Dictatorrabbit** [quisquous/cactbot#193]
for some reason i am getting an error so the cactbot window is not an option when i attempt to create a new one. any help you can give me? 
8/7/2018 2:07:21 PM: Error: LoadAddons: C:\Users\micha\ACT\Advanced Combat Tracker\addons\CactbotOverlay.dll: System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at RainbowMage.OverlayPlugin.PluginMain.LoadAddons()

**Comment by quisquous** [comment]
Take a look at https://github.com/quisquous/cactbot#potential-errors-and-workarounds

**Comment by Dictatorrabbit** [comment]
fixed, thank you for the help. i thought i did everything in that manual lol.
