### ISSUE TITLE
Cactbot Stopped Working

### ISSUE THREAD

**Issue by InverseRain** [quisquous/cactbot#194]
With the new patch, Cactbot appears to have stopped working. Both myself and a friend have tried clean installs of ACT, and we're getting the same error. Here is the error in its entirety:

```
8/16/2018 4:07:52 AM: Error: LoadAddons: C:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin-0.3.3.9-x64-full\addons\CactbotOverlay.dll: System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at RainbowMage.OverlayPlugin.PluginMain.LoadAddons()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].```

**Comment by InverseRain** [comment]
I found a different version of the OverlayPlugin and got it to at least load the module, but now I'm getting a different error. Any ideas?

```8/16/2018 11:43:48 AM: Error: raidboss: Error parsing most recent github release, no match found. Please report an issue at https://github.com/quisquous/cactbot/issues```

**Comment by quisquous** [comment]
I think that's different, and shouldn't affect cactbot working.  I've had some other reports of this, and I'll look into it later.  If everything else is working, you can close this issue.  :)

**Comment by InverseRain** [comment]
It wasn't working initially (I got the same error before trying the clean install) but now it seems to be working despite the error. Thanks!
