### ISSUE TITLE
Jobs: Rearrange code by job order

### ISSUE THREAD

**Issue by Echoring** [quisquous/cactbot#1944]
With more and more UI added to Jobs module, seems it's a little... chaos.
I'm considering about rearrange these code by an order, like PLD WAR DRK GNB WHM SCH AST MNK DRG NIN SAM BRD MCH DNC BLM SMN RDM BLU Other(Order on job list).
I know that it's not important, but it makes locating something a little easier(maybe a little obsessive).
This may make the whole file up-side-down, and very hard to review.
May I going to do this?

**Comment by MaikoTan** [comment]
Cactbot is going to migrate to use webpack, I think we can seperate every UI component for individual jobs into related file (for example, `ui/jobs/component/blm.js` for black mage).
And then just dynamic import them to the main class.

**Comment by quisquous** [comment]
I think we could do both.  The order you list above sounds great.  I think we can also break these out into individual files later when it becomes easier.  If you'd like to do it, please do this!
