### ISSUE TITLE
100% CPU usage after recent update in Bozjan southern front

### ISSUE THREAD

**Issue by Drudicta** [quisquous/cactbot#1947]
Received an update for Cactbot today, after an hour in Bozjnan southern front my CPU usage will continue to climb until All of it is used up for ACT. A restart of ACT fixes the issue temporarily.

**Comment by zzhou612** [comment]
Encountered the same issue.

**Comment by Cryotechnic** [comment]
Can confirm this happens as well.

**Comment by quisquous** [comment]
Sorry for the belated response, but this sounds more like an ACT issue.  I've seen some reports in the ACT discord of folks changing their parse filter to alliance/party and having that help.
