### ISSUE TITLE
Chrome 0.7.5 Download Warning

### ISSUE THREAD

**Issue by Krojack** [quisquous/cactbot#196]
Just an FYI, Google Chrome says that the 0.7.5 zip might be dangerous.  I know it's not but just giving a heads up.  Not sure why it just started doing this.  The other versions never did.

**Comment by theisrah** [comment]
I can confirm this. Happened to me on Chrome just today.

**Comment by quisquous** [comment]
Is this still happening with the newest version?

**Comment by Krojack** [comment]
Nope, 8.0 was fine.

**Comment by quisquous** [comment]
Thanks! I'll close this, then.
