### ISSUE TITLE
Disable "you died" trigger.

### ISSUE THREAD

**Issue by sethi12345** [quisquous/cactbot#198]
Not really an issue but I can't figure out where the tts trigger "You Died" is stored, as I want to disable it.

**Comment by quisquous** [comment]
This is because you added it in your cactbot/user/raidboss.js file.  If you open that file up, you can remove it.

It's an example trigger, so you likely got it if you copied cactbot/user/raidboss-example.js into cactbot/user/raidboss.js directly.

**Comment by meciuPL** [comment]
If this is about a sound that pops after you die and than repeats until you get up than I have the same problem after I've updated cactbot to the newest version. I've never created a cactbot/user/raidboss.js file or never used cactbot/user/raidboss-example.js to copy anything from there yet I have this sound. Please help.

**Comment by quisquous** [comment]
What is in your **cactbot/user/** folder?

**Comment by meciuPL** [comment]
jobs-example
oopsyraidsy-example
raidboss-example
README

**Comment by quisquous** [comment]
There are two places that cactbot looks for a user folder.  If your plugin folder is in ACT/OverlayPlugin/addons (for example), then it will look in ACT/OverlayPlugin/cactbot/user.  Additionally, if you link to some somedir/cactbot/ui/raidboss/raidboss.html and that cactbot directory is different than the ACT/OverlayPlugin/cactbot directory, it will also look local to the html file in somedir/cactbot/user.

Do you happen to have two user directories?

YOU DIED is only in raidboss-example.js, and should only appears on screen if it's been somehow injected into a raidboss.js file.  https://github.com/quisquous/cactbot/blob/66bf0729ab5eae8f5b970cfb39506300d495b6c8/user/raidboss-example.js#L102

**Comment by meciuPL** [comment]
Installing the newest version somehow resolved the problem. Thanks for your support.

**Comment by quisquous** [comment]
Glad you got it sorted!
