### ISSUE TITLE
TEA BETA CALIBRATION CALL OUTS NOT WORKING FOR BEACONS/CLONE POSITIONS

### ISSUE THREAD

**Issue by maverix16** [quisquous/cactbot#1996]
## Description

Description of the issue you're seeing.

hello.  did latest act update (11/9) mess with the cactbot tea callouts?  Went in for a few pulls tonight and the beta calibration beacons and light and dark positions were not called out.  The spread mechanic and radiant safe spot were however.  Happened to whole group.  also, for the beta becons and light and dark positions,  the text overlay that we usually see on the screen didnt show.

whole group had this issue (believe 7/8 using cactbot there).

for example,  i was light beacon and callout is usually something like "orange bait, bait north".  instead,  this never happened- the call out and the text overlay.  same with rest of us and their assignments.

thank you.

## Additional information

If available, please include any logs or screenshots depicting the issue you're experiencing.

**Comment by quisquous** [comment]
Were there any errors in the overlayplugin log?

**Comment by maverix16** [comment]
you know,  i asked my group the same question because this was raised in the discord.  

how can i tell?  can i still go back and look?

**Comment by quisquous** [comment]
OverlayPlugin log is here: https://github.com/quisquous/cactbot/blob/main/docs/CactbotCustomization.md#check-the-overlayplugin-log-for-errors

Once you close ACT, it is gone.  You should look after any run where there are issues.

You can also attach (or upload elsewhere, if too big) a [network log](https://github.com/quisquous/cactbot/blob/main/docs/FAQ-Troubleshooting.md#how-to-find-a-network-log) and I can take a look at that in case anything has changed recently.

**Comment by maverix16** [comment]
ok,  we will see what happens tonight.  closed act for sure. i attached the log here. i am in uncharted territory here.. please let me know if this is not helpful.

[Network_20700_20201109.zip](https://github.com/quisquous/cactbot/files/5520101/Network_20700_20201109.zip)

**Comment by maverix16** [comment]
from a teammate who may comment here..

I tested the triggers
Wormhole puddles and beta do not call anything out
But everything else does
I used the network log from our 0.1% wipe [from the night before the update]
So clearly something happened to certain triggers when they rolled out the update

**Comment by panicstevenson** [comment]
Running the above network log through the raidboss emulator, the following trigger text shows up for Beta:
>PLD: ALERT: Purple, no tether: E->W
WAR: ALARM: Purple Bait: bait E
SCH: INFO: Orange, no tether: E->N
AST: ALERT: Purple, far tether: E->S
DRG: ALARM: Orange Bait: bait N
MCH: INFO: Purple, close tether: E->N
BLM: INFO: Orange, far tether: E->N
SMN: INFO: Orange, close tether: E->N

I also see that the Limit Cut Numbers, Wormhole Puddles, and Wormhole Callouts here produce trigger results too. This isn't to say you're wrong or anything like that, just that this might be a little bit more tricky to debug than the initial thought that something looks wrong from within the triggers themselves. How was your teammate testing this that they were unable to see the trigger callouts?

**Comment by Sarvadi** [comment]
On Sunday night I was running version 19.11.0 and everything worked. The next day (Monday, so no Tuesday patch in-between) I encountered what OP describes with 19.13.0, so the problem exists in one of the commits between those two versions.

[network log trimmed to p4](https://github.com/quisquous/cactbot/files/5521738/tea-p4.zip)

[You can see here](https://streamable.com/a9vo0h) that clone callouts (beacon, tether) are missing but everything else works.

Nisis are also a bit odd. Instead of "get <color> <letter> from <name>", the callout now is only "get <color> <letter>". Only the "get" callout is affected - the "pass <color> <letter> to <name>" callout is still fine. The name omission usually only happens when nisis are fucked, but now it's omitted every time.

**Comment by quisquous** [comment]
Ok, I fixed the nisi issue.  That was straightforward.  Other than that, the only thing missing is the beta instructions?

**Comment by quisquous** [comment]
Ok, I'm pretty hopeful I understand what was broken here.  I'll do a cactbot release with this change.  Please let me know if beta is not working after the next release, or if there are any other things that broke.

Sorry for all the hassle.  I knew it was a bit risky to touch all the triggers, but letting users override all trigger output text from the UI seemed worth this chnage.

**Comment by maverix16** [comment]
awesome, ty.. we did clear last night and some of us just rolled back the release to before this.  we are going tonight, ill let you know

**Comment by Sarvadi** [comment]
Can confirm beta is fixed. I never had to pick up during the 3rd nisi pass tonight so I can't confirm if beta is fixed.
