### ISSUE TITLE
TTS not working 

### ISSUE THREAD

**Issue by Feith6** [quisquous/cactbot#1997]
Saw this on other posts but I didn't find fix for it. 
Basically I had to reinstall win, after that TTS in cactbot is not working, everything else in ACT is working perfecly, sounds work, even browser TTS is working. Is there any fix for it?

**Comment by quisquous** [comment]
What does your cactbot config look like? Did you set the default alert output to be tts? Are you using the "use browser for text to speech" option?

**Comment by Feith6** [comment]
It's set to Text and TTS. No I'm not using browser tts, I just wanted to try if it works. It did, after that I changed it back normal one.

**Comment by panicstevenson** [comment]
What happens if you try to run the Narrator app on Windows 10? Does that play text to speech?

Start Menu -> Narrator

(OK -> Exit Narrator to exit)

**Comment by quisquous** [comment]
Does ACT text to speech work? You can go to ACT -> Custom Triggers -> TTS radio button.  Type something into the text field next to TTS and then hit the play button to the right.

**Comment by Feith6** [comment]
Yes, Narrator is working. TTS radio button isn't working.

**Comment by quisquous** [comment]
If that's true, then it's an issue with ACT.  Since cactbot uses ACT for TTS, if the radio button isn't playing TTS then something is awry with ACT.  I think your best bet is to ask in https://discord.gg/ahFKcmx #troubleshooting about ACT TTS not working.

**Comment by Feith6** [comment]
I see. Thank you anyways!

**Comment by MyTechnoHunter** [comment]
issue seems to be related to the WMP API, having them switch to the other option in the ACT audio options allows TTS to work.. once they get windows media player fixed that should fix it for them
