### ISSUE TITLE
'ui/jobs' completely not working on 4.0

### ISSUE THREAD

**Issue by hibiyasleep** [quisquous/cactbot#20]
**FFXIV version**: 4.0 @ KR (released TODAY)
**FFXIV_ACT_Plugin**: 1.5.1.6
**cactbot**: 0.3.0 (without options) and 0.4.1 (with default config)
**does this happening on `test`**: no
![image](https://user-images.githubusercontent.com/5380174/34155529-0a9a9004-e4fd-11e7-9be6-2fe9d9bdff3c.png)
**steps**:
1. fresh install
2. with `ui/jobs`, do anything in game
3. `Uncaught TypeError: Cannot read property 'OnPlayerChanged' of undefined`
4. well, lets say `gBars = new Bars(Options);`
5. `Uncaught TypeError: Cannot read property 'search' of undefined`  (jobs.js:1226, trying 'this.zone.search')
6. `gBars.zone = []` (or `''`)
7. nothing but this (even after any status update)
![image](https://user-images.githubusercontent.com/5380174/34155388-7500831e-e4fc-11e7-877f-af8f806ecb03.png)

**Comment by quisquous** [comment]
Thanks for the detailed bug report.  By "4.0 @ KR (released TODAY)" I'm assuming you mean the Korean version of FFXIV? The English version seems to be working fine for me.

Sadly, `ui/jobs` reads a lot of log messages in English, so probably won't work well in other languages.  Did this work before for you on any version?

Are there any error messages in the OverlayPlugin log? I'm guessing not, but just want to check.

Does the onGameExistsEvent ever fire? I'm kind of surprises that you would ever get an OnPlayerChanged message if the game doesn't exist.  It early outs and doesn't send any more messages if that's the case.  https://github.com/quisquous/cactbot/blob/master/CactbotOverlay/CactbotOverlay.cs#L344

**Comment by hibiyasleep** [comment]
> I'm assuming you mean the Korean version of FFXIV? The English version seems to be working fine for me.

Yes, if there are any localization features, I can help translation etc.

> Did this work before for you on any version?

I didn't except cactbot work on Heavensward, so no.

> Are there any error messages in the OverlayPlugin log?

Nothing but browser error log.

> Does the onGameExistsEvent ever fire?

Seems no, since `gBars` didn't initialize. I'll create and perform a test for this.

**Comment by danakj** [comment]
onGameExistsEvent will fire if FFXIVProcess::FindProcess() returns true. But it should return true if it found a ffxiv_dx11.exe running. Even if memory locations/signatures differ it should fail to find them but still return true. https://github.com/quisquous/cactbot/blob/c4ddc7f53f616e7422148341851d20cba9a1ca05/CactbotOverlay/FFXIVProcess.cs#L264

**Comment by hibiyasleep** [comment]
I always use ffxiv_dx11 when possible. dx11 is unavailable over RDP, so I cannot test this right now.

**Comment by quisquous** [comment]
Are you saying that onGameExistsEvent fires if ACT is run as administrator? I'm not sure what to understand from your last PS.

> Yes, I can help localization features, or if it already exists, translations.

Ooh! We don't have localization features at the moment.  @danakj and I have been chatting about what we want to do.

Sadly, there are a lot of English regular expressions and strings that are defined up front and in line on various lines of code.  I think we'll need to move all of those into separate out of line variables, and maybe have several language .js files to define those variables based on Options.language.  I'll see if I can come up with a good pattern to follow for the jobs module, which will probably be the easiest to start with.

**Comment by hibiyasleep** [comment]
Oh, I forgot to test it, but at last try, it didn't fire.

**Comment by quisquous** [comment]
Localization issues aside, I think there are a few issues that you will need to debug with your own version.

(1) Debug the onGameExistsEvent not firing.

Can you  debug what FFXIVProcess::FindProcess and FFXIVProcess::IsActive are doing? When ffxiv dx11 version is running both of these should work properly, and it seems for you that they are not.  It's possible that maybe the message isn't getting to the overlay, but it seems more likely that the C# code thinks the game is not running.

(2) Once that's done, get the test page working correctly.

Does the test page work correctly for you? The hp/mp/tp/job values that are there seem very incorrect.  This is what it should look like:

![image](https://user-images.githubusercontent.com/462317/34311141-a6414844-e710-11e7-8b7a-c8d7994791d4.png)

If the onGameExistsEvent is firing and these values are wrong, then I think something is different with the memory offsets in your version that we will have to sort out.

**Comment by hibiyasleep** [comment]
tried but failed to run debugger with ACT (i'm not familiar with VS) - will try again next night. ;(

**Comment by danakj** [comment]
The trick to debugging is to load the cactbot project in vs, but change
it's properties to point to the act .exe file so it runs that. If you
copied a debug dll and pdb file to where act is loading cactbot from, then
you can set breakpoints, inspect values, and everything.

**Comment by quisquous** [comment]
Another possibility is to just add some log messages to see what's going on.  If it's helpful, here's a patch plus a built DLL that adds log info lines for trying to find the right process.  If you pasted the output from that, maybe that would reveal what's going on.

[hibiyaprocessdebug.zip](https://github.com/quisquous/cactbot/files/1587866/hibiyaprocessdebug.zip)

**Comment by hibiyasleep** [comment]
![image](https://user-images.githubusercontent.com/5380174/34382344-82591778-eb51-11e7-8a32-d714e79f0072.png)

All is like just before, debug log says it found FFXIV process correctly.

**Comment by quisquous** [comment]
Thanks.  :)

I agree with you about something wrong with the signature or maybe the offsets into memory from that signature.  Is the position data reasonable? If you jump, does the Z value go up and when you move around, do X and Y change reasonably?  Is your player id the same one that shows up in ACT logs for you?  You have no errors in the overlay plugin log and so the signature is found (and found exactly once), so I am suspecting that the signature is correct but some of the values (but not all) have incorrect offsets.

Looking at the code, name, id, distance, pos x, y, z are all at the top of the entity structure.  However, hp/job/level/etc are all at some offset.  Maybe kEntityStructureOffsetCharacterDetails is wrong?

 If I were debugging, I'd probably bump kEntityStructureSize up to maybe 10k (in case it's farther) and then add something like this inside of GetEntityData(), and then go fishing for what offset has your hp value in it.

```
  int my_current_hp = 58732;  // or whatever yours is in game right now
  for (int i = 0; i < kEntityStructureSize; i += 4)  {
    int hp = BitConverter.ToInt32(bytes, i);
    if (hp == my_current_hp)
      LogInfo("offset {0}: current hp: {1}", i, hp);
  }
```

(Sorry for my confusion, but are you getting the onGameExists message now? It seems like if the process is found, then that should be being sent?)

**Comment by hibiyasleep** [comment]
![image](https://user-images.githubusercontent.com/5380174/34412069-3df3590e-ec1e-11e7-96b5-e3f19e9f5beb.png)

Nope, this seems very strange.... I'll try address digging first.

**Comment by danakj** [comment]
It's "onGameExistsEvent". Maybe it has just been a typo causing confusion?

**Comment by hibiyasleep** [comment]
oh sorry, it was my typo.

`onGameExistsEvent` dispatched correctly, but this time I started ACT first - when I tried before, I started FFXIV first and restarted ACT several times.

**Comment by quisquous** [comment]
Hmm, that's very curious! I'm not sure why that ordering would make any difference, unless the timer isn't running.  Do you still get the debug log messages for finding the process if you start ffxiv first and then start ACT?

Another thought: have you tried a debug build instead of a release build? I wonder if some error is happening silently that would be more obvious in debug.

**Comment by hibiyasleep** [comment]
I'm currently running with DLL from `hibiyaprocessdebug.zip`, however it's same when starts FFXIV first.

**Comment by danakj** [comment]
If I understand correctly that means the event is working correctly for you
now in all cases? Thanks :)

**Comment by hibiyasleep** [comment]
Yes. I'll try with new version, excepting `ui/jobs` will work with current incorrect offset. thanks!
