### ISSUE TITLE
Cannot read Property of *.js,

### ISSUE THREAD

**Issue by ceanadh** [quisquous/cactbot#200]
![unbenannt](https://user-images.githubusercontent.com/42588867/44427249-50d86500-a591-11e8-8aac-b559444fb775.PNG)
Making my Timeline unusable

**Comment by quisquous** [comment]
This seems likely to be something wrong with your cactbot/user/raidboss.js file.  Can you try removing/renaming that?

**Comment by ceanadh** [comment]
Well it worked with the previous versions, I installed 0.7.0 again and it's working. I'll try again as soon as I'm home

**Comment by ceanadh** [comment]
Alright. I got the newest version again. It definitely works with the default raidboss.js, but not with mine :/
