### ISSUE TITLE
E6S Strike Spark

### ISSUE THREAD

**Issue by Gravehearts** [quisquous/cactbot#2000]
## Description

Sorry first time posting but i noticed with the recent updates that Strike Spark in E6S is no longer calling out positionals. It could just be a meant change since uptime soccer is becoming more popular but i was wondering if its suppose to be working or not at this point

## Additional information

Version wise i seem to have 0.19.13.0 and i will include the E6S.txt to help. Not sure what else i could include but any help would be appreciated
[e6s.txt](https://github.com/quisquous/cactbot/files/5521275/e6s.txt)

**Comment by quisquous** [comment]
Are errors in your overlayplugin log when this is happening?

**Comment by quisquous** [comment]
I put up a potential fix.  Can you set your raidboss url to `https://quisquous.github.io/cactbot/ui/raidboss/raidboss.html` and let me know the next time you run e6s if this is fixed?

**Comment by Gravehearts** [comment]
I have changed the url to the one you posted i will try it out. For the logs i never looked at them, are they saved to a file somewhere or deleted when the app is closed

**Comment by quisquous** [comment]
Or, if it's easier, I just made a release, so you can try the 0.19.14 version which includes this fix, no need to change your url.  I think this is fixed so I'll close this issue for now.  Let me know if it's not fixed and I'll reopen.
