### ISSUE TITLE
support for multiple processes?

### ISSUE THREAD

**Issue by em452e** [quisquous/cactbot#2001]
## Question

What would you like to ask?
Alerts don't work properly when running multiple instances of ffxiv. On discord I was told cactbot ignores the process ID and just grabs data from a random process. Is there a plan to add support for this so that changing process ID in plugin settings displays the alerts for that process specifically?

**Comment by quisquous** [comment]
At the moment, no.  Patches welcome.  I think this is likely to be fixed in the future when ngld merges cactbot plugin code into OverlayPlugin.

**Comment by quisquous** [comment]
Fixed!
