### ISSUE TITLE
Eureka: Uncaught TypeError: Cannot read property eureka.js

### ISSUE THREAD

**Issue by Krojack** [quisquous/cactbot#201]
`8/21/2018 8:48:46 PM: Info: Eureka: BrowserConsole: Uncaught TypeError: Cannot read property '0' of null (Source: file:///M:/ACTv3/OverlayPlugin/cactbot/ui/eureka/eureka.js, Line: 1157)
`

I get the above when I copy the tracker killed NMs and paste it via

`/echo NMs on cooldown: Snow Queen (19m) > Glavoid (20m) > Minotaurs (62m) > Ash Dragon (67m)`

**Comment by Brainlazy** [comment]
I had this happen when trying to reconnect to a eureka session after a BSOD, but tracker pastes worked again after restarting both ffxiv and ACT and re-entering Eureka. #199
