### ISSUE TITLE
document link bug(?)

### ISSUE THREAD

**Issue by Jaehyuk-Lee** [quisquous/cactbot#2011]
## Description
In [readme.md](https://github.com/quisquous/cactbot/blob/main/README.md) last sentence, `timeline` link and `trigger` link are wrong. I don't know what it was actually linking, so I opened an issue.

Unicode characters are supported throughout, through the use of the helpers in the
[resources/regexes.js](resources/regexes.js) file. However **[timelines](ui/raidboss/data/timelines)**
and log event **[triggers](ui/raidboss/data/triggers)** may be incorrect if names that appear in the
ACT log events are different.

**Comment by Akurosia** [comment]
we should either remove both links or point both to `/ui/raidboss/data`
The original links are simply not valid as in the OG days trigger and timeline files had theire respective folders inside `ui/raidboss/data`
@quisquous do you prefere removing both links, change both to the same location or rephrase the sentence to reflect the current setup?

**Comment by quisquous** [comment]
I think we could just remove both of those sentences that Jaehyuk-Lee quoted in the original issue.  I don't think they really add much.  Also unicode is...just supported in general, and the mess of unicode helpers got removed some time back, so that's not accurate either.
