### ISSUE TITLE
Cactbot not showing in OverlayPluggin.dll

### ISSUE THREAD

**Issue by Jolkien** [quisquous/cactbot#202]
So I haven't played FFXIV in  a week or two and I updated Cactbot and it doesn'T work anymore. Checking in ACT it's not listed in OverlayPluggin.dll anymore I have 2 Mini Parse, 1 Spell Timer but Cactbot is not there anymore.

Can someone help ?

**Comment by Jolkien** [comment]
So I managed to bring it back but it still doesn't work. Here's what my OverlayPlugin.dll looks like:
https://imgur.com/a/9tlf5U2

**Comment by quisquous** [comment]
Hmm.  Out of curiosity, can you show me your list of plugins? Is it possible to put the ffxiv plugin before the cactbot plugin in the list and retest?

cactbot should still work, however.  What do you mean by "it doesn't work"?

**Comment by Jolkien** [comment]
I meant the bars and alert were not triggerring on the test dummy or in sigmascape but I figured out my issue. For some reason in Cactbot the url was empty (the one we need to put raidboss.html in) I'm not sure what happened when I upgrade to the latest version probably a fluke or a user error on my part but it's now resolved.
