### ISSUE TITLE
Resources: Add first-class support for combining canned conditions

### ISSUE THREAD

**Issue by JLGarber** [quisquous/cactbot#2026]
There was [some discussion](https://github.com/quisquous/cactbot/pull/2017#discussion_r523799111) on my last pull request about whether it could be useful to add extra scaffolding for combining canned conditions. It's a not-uncommon situation where tank busters don't always work terribly well with `caresAbout` canned conditions. While these conditions do notify anyone to *mitigate*, they don't include the "YOU are the target" component that's kind of necessary for busters.

One suggestion from quisquous was to add a `conditionFunc` base object to return a boolean from a canned helper, so that we could then return that in a condition like any other comparison. (That is, something like `return condFunc.caresAboutMagical() || condFunc.targetIsYou()`.) This is of course the *right* way to do it, but I'm not sure whether it's really worth the effort.

Panic suggested adding `physicalTankbuster` and `magicalTankbuster` as conditions, mapping to `matches.target || Conditions.caresAboutX()`. This isn't as totally "correct", but it's not wrong, and it wouldn't require any actual work. (This has my vote simply because of these factors.)

Maybe the best thing is to specialize the tank buster conditions for now, and revisit this in 6.0 if Square adds new mechanics that necessitate new conditions?

**Comment by quisquous** [comment]
Yeah, I think specializing tankbuster conditions for now sounds good.  It doesn't preclude helper functions later!

(And I think saying my proposal is the right way to do it is overstating the case!  I think there's lots of ways to do this.  My biggest concern in all of this is making it harder to do the deceptively incorrect `condition: (data, matches) => data.something && Conditions.targetIsYou()`, as `Conditions.targetIsYou()` always evaluates as truthy as it's a function.)

**Comment by JLGarber** [comment]
Closing since it's largely irrelevant now that `caresAbout` conditions aren't applied to busters/raidwides.
