### ISSUE TITLE
TTS Triggers talk too much

### ISSUE THREAD

**Issue by xDemonessx** [quisquous/cactbot#204]
After pushing the update from 7.1 to 7.5, the triggers in encounters started to speak more and for every notice (not just alarms and alerts). For example, in UCoB the TTS would simply state "3" if i was doom 3 in Nael. Now, the TTS not only speaks my doom number, but also "Cleanse 1 Player Name" "Cleanse 2 Player Name" "Cleanse 3 Player Name". This chatter can get rapid and overlay one another. This also happens with Hatch Triggers, and Divebomb mark positions (all of which are lowest priority).

I'm not sure what changed between versions that would cause this. Is there an option to make the TTS triggers speak more plainly, or not speak certain sections of the timeline?

I have a suspicion its because i choose to disable sounds, so this is happening: https://github.com/quisquous/cactbot/issues/180

Thank you

**Comment by xDemonessx** [comment]
I can confirm that "alarmText" is being parsed and spoken where no sound is defined. As mentioned in #180 , `    zoneRegex: /.*/,
    triggers: [
      {
        regex: /:You are defeated by/,
        alarmText: 'YOU DIED',
      },
    ],
  },
`
is in my raidboss.js. So if i understand what was committed in  [3bd1b9a](https://github.com/quisquous/cactbot/commit/8eed2b8cb95b7e929e6d5c9ce2859e34eb27f758); I add `tts: false like` so:

`    zoneRegex: /.*/,
    triggers: [
      {
        regex: /:You are defeated by/,
        alarmText: 'YOU DIED',
        tts: false,
      },
    ],
  },
`
So to edit other triggers specific to the encounter, how would i go about doing that exactly?
Let's take my main issue, with the doom "cleanse" callout:

`Options.Triggers = [
  { zoneRegex: /The Unending Coil Of Bahamut \(Ultimate\)/,
    triggers: [
      {  id: 'UCU Nael Cleanse Callout',
      regex: /:Fang of Light:26CA:/,
      infoText: function(data) {
        data.doomCount = data.doomCount || 0;
        if (data.dooms)
          var name = data.dooms[data.doomCount];
        data.doomCount++;
        if (name)
          return 'Cleanse #' + data.doomCount + ': ' + data.ShortName(name);
          tts: false;
      },
    ],
  },`

Would this be a possible solution? to clarify, I dont want `infoText:` data of any sort to be parsed and spoken via tts.

**Comment by quisquous** [comment]
(Sorry for the delayed response.)

I assume you want *some* tts, or you wouldn't have turned on that option? (Or would you prefer no tts at all?)

For built-in triggers like the cleanse callout, even if you have tts turned on via `Options.SpokenAlertsEnabled = true;` you can set per-trigger options based on id.  https://github.com/quisquous/cactbot-user/blob/master/raidboss.js#L53 is an example of having tts off by default but turning tts on for some particular triggers.  You can do something similar, but set the playTTS values up differently.

For example, if you just want to turn off the cleanse callout, you can add something like this to your **cactbot/user/raidboss.js** file:
```
Options.PerTriggerOptions = Options.PerTriggerOptions || {};
Options.PerTriggerOptions['UCU Nael Cleanse Callout'] = { SpeechAlert: false, TextAlert: true };
```

**Comment by xDemonessx** [comment]
Thanks for explaining these settings and providing an example. Yes, I prefer TTS for on, but only at the alarm and alert level (nothing from the lowest priority "info" line). I hope that makes sense. 

I'll give this a try and next time I am in I'll let you know how it goes. Will close the issue for now and re-open should this persist.

**Comment by quisquous** [comment]
Yeah, sorry.  There's no option for "tts only on these particular levels".  I think your options are:
(1) turn off tts in general, turn on tts for specific triggers
(2) turn on tts in general, turn off tts for specific triggers

I probably need to make some sort of configuration tool at this point, as you're not the only person who has been confused by this.

Let me know if you get stuck making these changes.
