### ISSUE TITLE
Cactbot causing tons of lag

### ISSUE THREAD

**Issue by zemlja** [quisquous/cactbot#205]
I'm not sure when it exactly started, but cactbot raidboss started causing so much lag during ff14 that I had to start turning it off. I've reinstalled both ACT and cactbot and this did not resolve the issue. I've been using raidboss for a long time without any issues, and I don't recall changing anything. Any idea of what prompted this issue and how I might resolve it?

**Comment by ArkfrostLumas** [comment]
An advice that quisquous gave me a while ago:

In the OverlayPlugin.dll options in ACT go to each Cactbot Window and set the "Dps update interval seconds" to 0 (I think the default is 30 or something). Doing that reduced almost any lag I had before.

**Comment by quisquous** [comment]
Are you still having this issue?

**Comment by quisquous** [comment]
I'm going to close this for now.  Please reopen if you're still having this issue.
