### ISSUE TITLE
[Question] Usually how long does it take for you to update Cactbot for the next let's say 4.4 Patch?

### ISSUE THREAD

**Issue by JohnSmmiths** [quisquous/cactbot#206]
[Question] Usually how long does it take for you to update Cactbot for the next let's say 4.4 Patch?

**Comment by quisquous** [comment]
I usually have cactbot memory signatures updated for day 1 before the ACT release.  Triggers and timelines come in the first few days, usually a release in the first week.  To avoid being noisy to everybody with continual releases, I tend to not do a ton of releases the first week (maybe one early and one at the end of the week), but I do check everything into github.

You can use the github version of https://quisquous.github.io/cactbot/ui/raidboss/raidboss.html if you want to use the latest before it's released.
