### ISSUE TITLE
Add mocha for unit tests

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#2063]
Currently cactbot unit tests are a bit freeform and it'd be nice to use something like mocha to give them some structure, be able to run specific tests.  Just filing this because I keep thinking about it, and wanted to write it down somewhere.

**Comment by panicstevenson** [comment]
I think conceptually the work here is very straightforward, if someone was looking to pick something up with minimal oh-no-you-broke-people's-triggers-mid-raid worries. If anyone's interested, feel free to chime in. If not, I can pick this up in a couple days.

**Comment by Trim21** [comment]
Will we choose jest or mocha as test tool? Both tools can handle typescript painless.

**Comment by MaikoTan** [comment]
Personally I prefer mocha, though.

**Comment by panicstevenson** [comment]
From what @quisquous and I tested a while ago, we had to use Jest's [transformers](https://jestjs.io/docs/en/configuration#transform-objectstring-pathtotransformer--pathtotransformer-object) to use the tests how we use them, since we aren't testing code but instead are running text files through tests.

**Comment by quisquous** [comment]
Fixed in #2483, #2486, #2487, #2488.

I liked Jest's transformers better because you could ask Jest to go test `ui/raidboss/data/00-misc/test.js` and it would run a trigger test on it.  However, I couldn't figure out how to get Jest tests to deal with modules (or typescript) properly and it was a huge pain to set up.  Mocha is a lot more direct, although there's a weird indirect in #2483 to deal with testing data files.
