### ISSUE TITLE
config: add beforeSeconds override to config ui

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#2084]
Mentioned by @Akurosia.  I think it would be pretty straightforward to add this for any timeline trigger to the ui.  It'd be very similar to the changes in #1908.  If anybody wanted to implement this, I'd be happy to help give pointers.

**Comment by Akurosia** [comment]
could it somehow be filtered to only show on trigger that are timeline related?
For other triggers there would be no way of using `beforeSeconds` as e.g. how would you know 5sec in advance when a tank decides to use invuln?
Or will this be just something we have to live with?

**Comment by quisquous** [comment]
Yeah, I agree that it should only show for triggers that are timeline triggers, in the same way that there's no duration field for anything that doesn't have output (e.g. is just a trigger with a run field).
