### ISSUE TITLE
Need help with 'data' and 'matches'

### ISSUE THREAD

**Issue by Elypha** [quisquous/cactbot#2095]
Hello, I am writing my custom triggers but need help with the objects documented [here](https://github.com/quisquous/cactbot/blob/main/docs/RaidbossGuide.md#data-matches-output).

I found examples such as
```
matches.source
matches.target
data.me
data.role
```
also I see some triggers store their data in `data`.

Is there a list or so that shows all data as well as their structures that are supposed to be there in `matches` and `data`? I want to know all valid ones. Perhaps could I do it myself by something like printing out those data?

**Comment by MaikoTan** [comment]
### `data`

`data` is a "shared" variable across triggers, its initial properties are defined here:
https://github.com/quisquous/cactbot/blob/345e2d36052c33afb2e004b3a3e5084eafccf276/ui/raidboss/popup-text.js#L560-L579

So you can see we always set some variable on `data` property in one trigger, and then use it in another trigger, even delete the variable in the other trigger.

Here is an example to do this:

https://github.com/quisquous/cactbot/blob/345e2d36052c33afb2e004b3a3e5084eafccf276/ui/raidboss/data/04-sb/raid/o9s.js#L370-L422

### `matches`

`matches` is a `RegExpMatchArray` ([mdn link](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/String/match)), which contains the match group from regex matching when you set `capture` as `true` or `undefined`.

You can find all the match names in [regexes.js](https://github.com/quisquous/cactbot/blob/main/resources/regexes.js) or [netregexes.js](https://github.com/quisquous/cactbot/blob/main/resources/netregexes.js).

**Comment by Elypha** [comment]
@MaikoTan Thanks so much for the detailed explanation! That's just what I am looking for

**Comment by MaikoTan** [comment]
@quisquous I think these object can be documented precisely more in `RaidbossGuide.md`, what do you think ?

**Comment by quisquous** [comment]
Yeah, better documentation for this would be great.
