### ISSUE TITLE
Localization of timeline message parsing

### ISSUE THREAD

**Issue by hibiyasleep** [quisquous/cactbot#21]
split from #20 - I can provide some regexes in Korean, base on `ui/jobs`.

**Comment by quisquous** [comment]
https://github.com/quisquous/cactbot/commit/2593b43f8337ea9c01806e78909093c11c73545c splits out all the strings and regular expressions for ui/jobs.

I think raidboss would probably take more work, so jobs might be a good place to start, once the test page is working correctly.

**Comment by hibiyasleep** [comment]
for reference - some system messages are appearing in English even on Korean client.

![2017-12-26 10 23 47](https://user-images.githubusercontent.com/5380174/34344241-efba308a-ea26-11e7-94a6-0516a442beca.png)

**Comment by quisquous** [comment]
I think localization is in progress here, and so I'm going to close this.
