### ISSUE TITLE
plugin: find new shield value offset for 5.4

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#2107]
When updating the plugin in aeb55b2945e I couldn't find the shield percentage any more.  If anybody with cheat engine expertise has time to look into this, it'd be much appreciated.

**Comment by KattTails** [comment]
I took a brief look at this a couple of nights ago after raid and from what I can see it has been removed from the EntityMemory region completely. I was able to find it, possibly(?) in a totally separate section of memory. It sits right next to current/maxHP and current/maxMP so it might be related to the party list, although its still valid solo! 
You can semi-reliably find it by shielding yourself and doing a 2 byte scan for values between 1 and 100, removing the shield and searching for values equal to 0, and then repeating.

**Comment by AmenneHolelane** [comment]
the shield percentage is at 0x1977 on the actor
