### ISSUE TITLE
no raidboss role alerts in dungeons

### ISSUE THREAD

**Issue by em452e** [quisquous/cactbot#2114]
## Description
I'm no longer getting raidboss aoe and tank buster alerts in dungeons while playing as a healer. Alerts like goRight and left are working fine. 

## Additional information
Testing in summerford farms is fine. But in Holminster Switch for example, the alerts will not play for aoe and tank buster. I tried commenting out the condition attribute in the alerts but it still doesn't work. Tried as white mage and astrologian.

**Comment by quisquous** [comment]
If you add the cactbot test overlay, does it know what job you are?

**Comment by em452e** [comment]
> If you add the cactbot test overlay, does it know what job you are?

Actually, no. It lists job as "0 None".

**Comment by quisquous** [comment]
Are you on the latest cactbot plugin version 0.21.0?

**Comment by em452e** [comment]
> Are you on the latest cactbot plugin version 0.21.0?

I was on 0.20. I restarted ACT several times and the auto updater didn't pop up so I thought I was on the latest version. I managed to update it now and it's working now, thanks!
