### ISSUE TITLE
Cactbot not loading in plugins

### ISSUE THREAD

**Issue by Smuggus** [quisquous/cactbot#216]
Every time a patch drops i have this issue, sorry im a total newb. When the patch dropped, i tried to copy/paste cactbot 8.0s overlay folder to my ACT folder to no avail. ACT does not show cactbot as an available plugin. I have the most up to date FFXIV plugin. I tried deleting my old cactbot entirely and installing fresh and it still didnt work.

**Comment by quisquous** [comment]
If you're having trouble installing, one thing you can do is to run the bundle installer: https://github.com/ezsoftware/OverlayPlugin-Compiler/releases/download/v0.3.4.0.EZS.Enmity-1.10.0.0.Cactbot-0.7.0/OverlayPluginSetup.0.3.4.0.EZS.Enmity-1.10.0.0.Cactbot-0.7.0.exe

And then once that's installed, install the new version of Cactbot on top of that.  That will set up all your dependencies, like the OverlayPlugin framework, etc.

**Comment by Smuggus** [comment]
I tried that package and it didnt give me any of the plugins. Ill ss a few pages so you can see

**Comment by Smuggus** [comment]
![screenshot 1](https://user-images.githubusercontent.com/43510246/45988584-49e3bd00-c03d-11e8-94db-1dca38b55ca6.png)

**Comment by Smuggus** [comment]
I completely uninstalled, reinstalled, and still cant find cactbot for an option

**Comment by Smuggus** [comment]
![screenshot 2](https://user-images.githubusercontent.com/43510246/45988674-ac3cbd80-c03d-11e8-9221-de8970458f30.png)

**Comment by Smuggus** [comment]
I also just updated the file, following directions to the T, it still doesnt show up in plugins :C. I know im doing something stupid, i just dont know what.

**Comment by mooondark** [comment]
My advice : install ACT out of **_C:\Program Files\_**, I had numerous errors like you. Now it's installed in **_C:\Apps\ACT_** and everything works fine.

**Comment by Smuggus** [comment]
I dont have an apps folder under C:, can i just make an apps folder under Cs directory? Like on the screen where program files is, but a new folder so itd be like
Apps folder (i just made)
Other stuff
Program files
Im not computer savvy, im sorry

**Comment by mooondark** [comment]
Yeah, just create a new folder (I took an exemple with C:\Apps, but you can put it where you want except in C:\Program Files and name it like you want).

**Comment by Smuggus** [comment]
That did not work, i uninstalled ACT entirely, reinstalled all plugins and kagerou, and the drop down still doesnt have cactbot

**Comment by quisquous** [comment]
Sorry, I don't really have any other good suggestions here.  Where is your OverlayPlugin.dll relative to that addons folder? Is it inside ACT/OverlayPlugin/?

**Comment by Smuggus** [comment]
The overlay plugin.dll is inside acts folder. Not under any other sub folder. Is that wrong?

**Comment by Smuggus** [comment]
Ok, so i used the http version (where i copy that link in the URL) and the overlay loads for raidboss (which is 95% of what i use) so it seems to be working using that method. Thank you all so much for your help and i again apologize for my ignorance.

**Comment by quisquous** [comment]
Glad you got it sorted!
