### ISSUE TITLE
Pagos map not opening with Eureka module

### ISSUE THREAD

**Issue by dtonberry** [quisquous/cactbot#217]
When i open the eureka module in Pagos it still shows the anemos map with no info.

**Comment by Zelfire85** [comment]
I am having the same problem. It only shows up when I have it unlocked and even then its only the anemos map with no info.

**Comment by Sapphiratelaemara** [comment]
+1

**Comment by quisquous** [comment]
Fixed in 0ff7a2a18a239c25a1e1e1dccec5bc7db2b9e449
