### ISSUE TITLE
[Suggestion] NetRegexes.tether({ id: '0007' }) for Rock Throw

### ISSUE THREAD

**Issue by lexxiesia** [quisquous/cactbot#2172]
https://github.com/quisquous/cactbot/blob/ad2d3a9857ad1d1445b73b68ae4d995be170d2be/ui/raidboss/data/05-shb/trial/titan-un.js#L66

First off, I apologize if this is the wrong way to submit a suggestion/fix.

There is a **23: NetworkTether** line (ID: 0007) before the **15: NetworkAbility** line for Rock Throw. The DPS is listed as the source while the healer is listed as the target.

> `[23:30:52.184] 23:1025775F:Riku Tribal:102D78FF:Mahiru Hoshino:0000:0000:0007:102D78FF:000F:0000:`
> `[23:30:52.453] 15:400188BC:Titan:5ADD:Rock Throw:1025775F:Riku Tribal:`

> `[23:32:06.763] 23:1025775F:Riku Tribal:102D78FF:Mahiru Hoshino:6D20:0000:0007:102D78FF:000F:2020203A:`
> `[23:32:06.985] 23:1025775F:Riku Tribal:102D78FF:Mahiru Hoshino:B330:0000:0007:102D78FF:000F:0000:`
> `[23:32:06.985] 15:400188BC:Titan:5ADD:Rock Throw:1025775F:Riku Tribal:`

> `[23:32:51.895] 23:101F5B64:Knyssa Callistis:1033BE65:Ankey Kilth:42C0:0000:0007:1033BE65:000F:3E4CCCCD:`
> `[23:32:52.163] 15:400188BC:Titan:5ADD:Rock Throw:101F5B64:Knyssa Callistis:`

> `[23:34:34.252] 23:101F5B64:Knyssa Callistis:102D78FF:Mahiru Hoshino:0000:0000:0007:102D78FF:000F:0000:`
> `[23:34:34.517] 15:400188BC:Titan:5ADD:Rock Throw:101F5B64:Knyssa Callistis:`

> `[23:37:13.840] 23:1025775F:Riku Tribal:102D78FF:Mahiru Hoshino:6D20:0000:0007:102D78FF:000F:2020203A:`
> `[23:37:14.018] 15:400188BC:Titan:5ADD:Rock Throw:1025775F:Riku Tribal:`

**Comment by panicstevenson** [comment]
Awesome! I just ran this again this morning, so I'll take a look. Unless you're interested in making the change yourself?
