### ISSUE TITLE
Util: Display duration when auto-listing in make/test_timeline

### ISSUE THREAD

**Issue by JLGarber** [quisquous/cactbot#2177]
(Mostly filing this as a reminder for myself.)

`-lf` is an incredibly useful tool when working with timelines. However, it can be hard for human eyes to parse the output for how long any individual encounter is. Which of these is the longest?

```
20. 19:48:15.992 19:54:59.890 Eden's Promise: Anamorphosis (Savage)
21. 19:57:08.404 20:03:25.946 Eden's Promise: Anamorphosis (Savage)
22. 20:05:50.502 20:12:06.811 Eden's Promise: Anamorphosis (Savage)
23. 20:14:30.460 20:21:54.378 Eden's Promise: Anamorphosis (Savage)
24. 20:27:54.258 20:30:53.767 Eden's Promise: Anamorphosis (Savage)
25. 20:31:46.595 20:39:20.264 Eden's Promise: Anamorphosis (Savage)
```

It's not too hard here, but when the list is 30-40 long, it's not easy. It would be nice to have duration listed as well:

```
22. 20:05:50.502 20:12:06.811 6:16.309 Eden's Promise: Anamorphosis (Savage)
```

This shouldn't be too difficult, just have to make a minor modification to the encounter listing.

**Comment by quisquous** [comment]
Strongly agreed! I think we could drop the end time and just list something like `6m16s`.
