### ISSUE TITLE
Regexes yName bug

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#22]
`console.log(Regexes.Parse(/\y{Name}/));`

```
12/22/2017 9:41:49 PM: Info: danabars: BrowserConsole: /(?:[ƻǀ-ǃʔא-תװ-ײؠ-ؿف-يٮٯٱ-ۓەۮۯۺ-ۼۿܐܒ-ܯݍ-ޥޱߊ-ߪࠀ-ࠕࡀ-ࡘऄ-हऽॐक़-ॡॲ-ॷॹ-ॿঅ-ঌএঐও-নপ-রলশ-হঽৎড়ঢ়য়-ৡৰৱਅ-ਊਏਐਓ-ਨਪ-ਰਲਲ਼ਵਸ਼ਸਹਖ਼-ੜਫ਼ੲ-ੴઅ-ઍએ-ઑઓ-નપ-રલળવ-હઽૐૠૡଅ-ଌଏଐଓ-ନପ-ରଲଳଵ-ହଽଡ଼ଢ଼ୟ-ୡୱஃஅ-ஊஎ-ஐஒ-கஙச
... etc
```

**Comment by danakj** [comment]
Whats the bug?

**Comment by quisquous** [comment]
Does that look output look correct to you?

**Comment by danakj** [comment]
Sure? It should match any "word" character across all unicode. I'm not sure how it represents that exactly. I guess by putting them all in a []?

**Comment by quisquous** [comment]
Hmmmmm ok.  I filed this while debugging, and in retrospect I think this was spurious.  I was having a hard time getting some \y{Name} to match and this seemed super suspicious.  I had an incorrect memory at the time of logging it sometimes and having it look much shorter, so thought something was up for some corner case.

Somewhat dubious that giant character set is the best way to match, but seems working for now.

Sorry for confusion!  Too much debugging.  /o\

**Comment by danakj** [comment]
OK! I think there's better alternatives in newer chrome v_v but can't upgrade CEF atm.
