### ISSUE TITLE
Cactbot disapprearing when I engage mob

### ISSUE THREAD

**Issue by Brymkitti** [quisquous/cactbot#220]
I am pretty sure I have everything installed the right way, when I go to test it in summerford farms I use the countdown, cactbot will show the raidboss plugin until I take an action and then it completely disappears.  Please help me.  I used the plugin for all of sigmascape and never had any issues.

**Comment by quisquous** [comment]
That's a new one for me.  Hmm.

Are there any errors in the plugin log? What do you mean by "take action"? Can you show me a screenshot or two?

**Comment by Brymkitti** [comment]
![image](https://user-images.githubusercontent.com/43530109/45937821-9ff72880-bf89-11e8-9d85-4632f3ef61dc.png)
![image](https://user-images.githubusercontent.com/43530109/45937824-a7b6cd00-bf89-11e8-9b72-a6e2feb3eca1.png)
![image](https://user-images.githubusercontent.com/43530109/45937828-adacae00-bf89-11e8-94a9-f787b5adee5c.png)
![image](https://user-images.githubusercontent.com/43530109/45937834-bf8e5100-bf89-11e8-97df-075f7356f4c7.png)
![image](https://user-images.githubusercontent.com/43530109/45937836-c4eb9b80-bf89-11e8-95d2-418e16e1a4c7.png)
![image](https://user-images.githubusercontent.com/43530109/45937838-ccab4000-bf89-11e8-904b-c35b4ba7340e.png)

**Comment by Brymkitti** [comment]
the last pic is after I engage the dummy

**Comment by Brymkitti** [comment]
I can screenshare you through temaviewer I just need it fixed lol.

**Comment by quisquous** [comment]
Thanks.  My suspicion here is that maybe the wipe detector is detecting a wipe for some extremely unknown reason.  The next released version should have an improved wipe detector, so let me know if 0.8.4 doesn't fix your problem.

**Comment by quisquous** [comment]
Did 0.8.4 fix things at all?

**Comment by quisquous** [comment]
I'm going to close this old issue due to lack of response.  Let me know if 0.8.4 didn't fix this.
