### ISSUE TITLE
Errors of translations on wol and wol-ex, maybe.

### ISSUE THREAD

**Issue by VanSlanzar** [quisquous/cactbot#2218]
@quisquous, @JLGarber, @panicstevenson, i need your help. I need to be sure of these translations for my request, because it seems wrong to me because I have not found these skills on FFlogs and Garlandtools. Thank you ans sorry for the inconvenience.

- This is on timeline wol.js, `Absolute Fire/Blizard` it's normal, because i not finded on fflogs or garlandtools ? `Blizard` should be `Blizzard` ?
```
670.7 "Absolute Fire/Blizard" sync /:Warrior Of Light:4F2[DE]:/
760.6 "Absolute Fire/Blizard" sync /:Warrior Of Light:4F2[DE]:/
```

- This is on timeline wol-ex.js.  Is a good name ?
Imbued Holy, I not finded, but absolute Holy, yes.
Imbued Stone, I not finded, but absolute Stone, yes.
Imbued Stone/Holy, see above.
Imbued Fire/Ice, that should be Imbued Fire/Blizzard ? I not finded Imbued Ice.
Fire/Ice -> SMN/WAR, same ice -> Blizzard ?
```
$ python util/find_missing_translations.py -f wol-ex.js -l fr
C:\Users\Bauer\Documents\GitHub\cactbot\ui\raidboss\data\05-shb\trial\wol-ex.txt:40 text "Imbued Stone"
C:\Users\Bauer\Documents\GitHub\cactbot\ui\raidboss\data\05-shb\trial\wol-ex.txt:41 text "Imbued Fire/Ice"
C:\Users\Bauer\Documents\GitHub\cactbot\ui\raidboss\data\05-shb\trial\wol-ex.txt:52 text "Imbued Holy"
C:\Users\Bauer\Documents\GitHub\cactbot\ui\raidboss\data\05-shb\trial\wol-ex.txt:53 text "Imbued Ice/Fire"
C:\Users\Bauer\Documents\GitHub\cactbot\ui\raidboss\data\05-shb\trial\wol-ex.txt:119 text "Fire/Ice -> SMN/WAR"
C:\Users\Bauer\Documents\GitHub\cactbot\ui\raidboss\data\05-shb\trial\wol-ex.txt:172 text "Fire/Ice -> SMN/WAR"
C:\Users\Bauer\Documents\GitHub\cactbot\ui\raidboss\data\05-shb\trial\wol-ex.txt:221 text "Fire/Ice -> SMN/WAR"
C:\Users\Bauer\Documents\GitHub\cactbot\ui\raidboss\data\05-shb\trial\wol-ex.txt:227 text "Imbued Stone/Holy"
C:\Users\Bauer\Documents\GitHub\cactbot\ui\raidboss\data\05-shb\trial\wol-ex.txt:265 text "Fire/Ice -> SMN/WAR"
C:\Users\Bauer\Documents\GitHub\cactbot\ui\raidboss\data\05-shb\trial\wol-ex.txt:271 text "Imbued Fire/Ice"
C:\Users\Bauer\Documents\GitHub\cactbot\ui\raidboss\data\05-shb\trial\wol-ex.txt:314 text "Fire/Ice -> SMN/WAR"
C:\Users\Bauer\Documents\GitHub\cactbot\ui\raidboss\data\05-shb\trial\wol-ex.txt:356 text "Fire/Ice -> SMN/WAR"
C:\Users\Bauer\Documents\GitHub\cactbot\ui\raidboss\data\05-shb\trial\wol-ex.txt:394 text "Fire/Ice -> SMN/WAR"
C:\Users\Bauer\Documents\GitHub\cactbot\ui\raidboss\data\05-shb\trial\wol-ex.txt:400 text "Imbued Stone/Holy"
C:\Users\Bauer\Documents\GitHub\cactbot\ui\raidboss\data\05-shb\trial\wol-ex.txt:428 text "Fire/Ice -> SMN/WAR"
C:\Users\Bauer\Documents\GitHub\cactbot\ui\raidboss\data\05-shb\trial\wol-ex.txt:434 text "Imbued Fire/Ice"
```

**Comment by MaikoTan** [comment]
I think they are "Imbued Absolute Fire III" and "Imbued Absolute Blizzard III", what I translate them in ja are also these.

**Comment by MaikoTan** [comment]
I think they are "Imbued Absolute Fire III" and "Imbued Absolute Blizzard III", what I translate them in ja are also these.

**Comment by JLGarber** [comment]
>  Absolute Fire/Blizzard

This is simply a contraction, in English, of `Absolute Fire/Absolute Blizzard`. If French can have it be short enough to have both skill names included on one line, you can do that.

> Imbued skills

Wherever you see this, it should be the same situation, where it could be `Imbued Absolute Stone/Imbued Absolute Holy`. You can see a list of imbued skill names on XIVAPI:
[FIRE](https://xivapi.com/search?indexes=action&string=absolute+fire&columns=Name,Name_de,Name_fr,Name_ja,ID), [BLIZZARD](https://xivapi.com/search?indexes=action&string=absolute+blizzard&columns=Name,Name_de,Name_fr,Name_ja,ID), [HOLY](https://xivapi.com/search?indexes=action&string=absolute+holy&columns=Name,Name_de,Name_fr,Name_ja,ID), [STONE](https://xivapi.com/search?indexes=action&string=absolute+stone&columns=Name,Name_de,Name_fr,Name_ja,ID)

Please do let us know if I misunderstood your question!

**Comment by VanSlanzar** [comment]
It's not that, sorry.

**On wol.txt timeline**
My first question is: 
`Blizard` should will be written `Blizzard` ? Because, i not finded `Blizard` in the logs.

**On wol-ex.txt timeline**
My second question is:
`Imbued Holy`, I not finded in the logs, but absolute Holy, yes.
`Imbued Stone`, I not finded in the logs, but absolute Stone, yes.
`Imbued Stone/Holy`, see above.
Imbued Fire/`Ice`, that should be Imbued Fire/`Blizzard` ? I not finded  in the logs `Imbued Ice.`
Fire/`Ice` -> SMN/WAR, same `ice` should will be `Blizzard` ?

I feel like these abilities don't exist, because I can't find them, and I wonder, if it's bad writing. I hope I have been clearer. sorry for the difficulty in understanding each other.

**Comment by quisquous** [comment]
`Blizard` is probably a typo.

It looks like all of the imbued abilities are named `Imbued Saber` in the game.  The timeline differentiates by element to be more clear and it looks like `Imbued Holy` is not a real name.

I think `Ice` and `Blizzard` are synonymous here.  `Ice` was shorter, so that's probably why I wrote it that way, but I don't feel strongly.

**Comment by VanSlanzar** [comment]
I Finded in logs and garlandtools this abilities.
- Imbued Absolute Blizzard III, Imbued Absolute Fire III, Imbued Coruscance, Imbued Saber.
- Absolute Blizard III, Absolute Fire III, Absolute Holy, Absolute Stone.
