### ISSUE TITLE
ACT updater can't update to 0.21.8

### ISSUE THREAD

**Issue by anthonypants** [quisquous/cactbot#2229]
## Description

Open ACT, remove Cactbot from ACT, and close ACT.
Delete any cactbot folders from the `%APPDATA%\Advanced Combat Tracker\Plugins\` folder, if they exist.
Unpack one of the earlier releases into the `%APPDATA%\Advanced Combat Tracker\Plugins\` folder (e.g. cactbot-0.21.3).
Open ACT, add this plugin, and close ACT.
Reopen ACT to trigger the auto-updater.  Click Install Update.
- A `cactbot.tmp` folder will be created, and will be deleted when the "install" is completed
Click Restart when prompted.
Go to the Plugins tab in ACT and click on the CactbotOverlay.dll.
- The version reads "0.21.3.0"
- This matches the version of the DLL as reported by Windows

## Additional information

Traditionally, `CactbotOverlay.dll` is installed at `%APPDATA%\Advanced Combat Tracker\Plugins\cactbot-[version]\cactbot\` -- this is the version ACT automatically downloads (except with version 0.21.8, and potentially other releases). However, if you had `CactbotOverlay.dll` installed at `%APPDATA%\Advanced Combat Tracker\Plugins\cactbot\`, there is no change to the above.

The release zip for 0.21.8 doesn't have a `cactbot-0.21.8` folder inside it, but I don't think that's the cause of this issue.

**Comment by quisquous** [comment]
> The release zip for 0.21.8 doesn't have a cactbot-0.21.8 folder inside it, but I don't think that's the cause of this issue.

I think this is definitely *an* issue, if not *the* issue.

**Comment by quisquous** [comment]
I think this should be fixed now.
