### ISSUE TITLE
Raidboss: E12N Titanic Bombs sometimes call the wrong direction

### ISSUE THREAD

**Issue by JLGarber** [quisquous/cactbot#2232]
(Filing as a reminder and to solicit input.)

Per a [bug report](https://discord.com/channels/551474815727304704/594899820976668673/788798153381511198) in the ACT Discord server, it appears that the Titanic Bombs trigger calls incorrectly sometimes. There wasn't a lot of data, but @valarnin was kind enough to go through a few things there. It looks like I may have inverted the direction of the Y axis? When I initially set these triggers up, I assumed the arena to be a standard Cartesian layout, with the arena center at 0, -70.

Looking through my logs, it *appears* that the center is 0, -75, based on the positioning of the bomb boulder that drops in the center. According to Valarnin, inverting the "is this entity north or south" check resolves the issue for them. That is, `bomb.north = parseFloat(matches.y) + 70 > 0` should be changed to `bomb.north = parseFloat(matches.y) + 70 < 0`.

**Comment by valarnin** [comment]
Note that this may not be the correct solution. It fixed the specific instance that I was testing, but it's possible there's a different underlying problem. It's also important to note that this seems to work properly in raidemulator, it's only wrong in-game, which might indicate a line ordering issue?

**Comment by JLGarber** [comment]
@valarnin any chance you have the exact log lines that were called incorrectly? I've been chasing this down a bit today and everything I've seen so far points to "camera was pointed wrong". I'd really like to eliminate that possibility definitively if possible.

**Comment by valarnin** [comment]
I had a run today that had the wrong callout. I can DM you the log on Discord, don't want to post it publicly @JLGarber

**Comment by valarnin** [comment]
Relevant log lines:

```
03|2020-12-20T12:16:58.6860000-05:00|40013b0e|Bomb Boulder|0|50|0|0||9815|12431|148000|148000|0|10000|0|0|11.31371|-86.31371|75|-0.7854581||f74eef24e2b680d3b25626c28fb9560e
03|2020-12-20T12:16:58.6860000-05:00|40013b0d|Bomb Boulder|0|50|0|0||9815|12431|148000|148000|0|10000|0|0|0|-75|75|-4.792213E-05||e6fb5cdf122d4420db1839e6c32b9d39
03|2020-12-20T12:16:58.6860000-05:00|40013b0f|Bomb Boulder|0|50|0|0||9815|12431|148000|148000|0|10000|0|0|-11.31371|-86.31371|75|-0.7854581||cd5f7b0b43eaa770b6f8183ba8de6447
03|2020-12-20T12:16:58.6860000-05:00|40013b10|Titanic Bomb Boulder|0|50|0|0||9816|12432|148000|148000|0|10000|0|0|-11.31371|-63.68629|75|0.7853622||2ae3302a12dca5471a005a5a5096ac2e
03|2020-12-20T12:16:58.6860000-05:00|40013b11|Titanic Bomb Boulder|0|50|0|0||9816|12432|148000|148000|0|10000|0|0|11.31371|-63.68629|75|-0.7854581||df3deab7ac9945ca77c77d771b582fc7
03|2020-12-20T12:17:01.6980000-05:00|40013b14|Bomb Boulder|0|50|0|0||9815|12431|148000|148000|0|10000|0|0|-16|-75|75|-4.792213E-05||5603e66f2284617622b1ef2cff80b4ac
03|2020-12-20T12:17:01.6980000-05:00|40013b16|Bomb Boulder|0|50|0|0||9815|12431|148000|148000|0|10000|0|0|16|-75|75|-4.792213E-05||a155f07072ef8f057084c02f2ad07a1d
03|2020-12-20T12:17:01.6980000-05:00|40013b15|Bomb Boulder|0|50|0|0||9815|12431|148000|148000|0|10000|0|0|7.45058E-09|-59|75|-4.792213E-05||6ea4b625446e7eb95e4d453eeaf372da
03|2020-12-20T12:17:01.6980000-05:00|40013b17|Bomb Boulder|0|50|0|0||9815|12431|148000|148000|0|10000|0|0|1.490116E-09|-91|75|-4.792213E-05||84fbe8ce887a0ae2e493645600e05869
```

Screenshot in Raidemulator showing callout going south even though small bombs were north:

![image](https://user-images.githubusercontent.com/6119598/102724470-b5309e00-42dd-11eb-9df1-23d994b403a9.png)

**Comment by JLGarber** [comment]
Alright, I was finally able to reproduce this myself as well. It looks like you're correct, I had the North/South values reversed. East/West values were correct, so I'm not sure what was causing those reports.

**Comment by quisquous** [comment]
This was fixed by #2252, right?

**Comment by valarnin** [comment]
As far as I'm aware, yes. I haven't run e12n yet to verify but that PR was meant to address this issue.

**Comment by quisquous** [comment]
Ok, will close for now.  We can reopen if it shows up again.  Thanks!
