### ISSUE TITLE
Crits at 0% - rdmty dps

### ISSUE THREAD

**Issue by tj-mai** [quisquous/cactbot#2237]
Hi, the rdmty dps overlay kept showing 0% Crit.

the bandaid fix `(formatNumber(100 / encounter.hits * encounter.crithits) + "%")` at row 218 worked for a while, now since a few patches changing something doesn't do anything anymore.
it seems cactbot doesn't use the dps.js file in the rdmty folder anymore, is there another bandaid fix I could use in the meantime?

**Comment by quisquous** [comment]
It uses the `dps.js` fille in the rdmty folder, however updating that file is not enough anymore.  You should see the last few months of release notes (https://github.com/quisquous/cactbot/releases?after=v0.21.0) that warned that this was no longer possible.

Thanks for filing a bug.  This is a much better way to get this fixed than manually fixing it yourself every release.  I don't use rdmty, so if there's bugs I will most likely not see them.
