### ISSUE TITLE
any tutorial for building the dist folder?

### ISSUE THREAD

**Issue by hkgmschildren** [quisquous/cactbot#2251]
I successfully follow the instruction to build the dll file, but failed to generate bundle.js using the npm run build command

**Comment by MaikoTan** [comment]
cactbot is a npm package project.
so just install nodejs, and then run this below:
```shell
$ npm install
$ npm run build
```

**Comment by hkgmschildren** [comment]
Thanks! I think the thing that I did wrongly is I cd the directory to *\cactbot-main-1\webpack
successfully run the command in *\cactbot-main-1

**Comment by quisquous** [comment]
Glad you got this sorted! Sorry for the hassle.
