### ISSUE TITLE
e10n not showing up under settings

### ISSUE THREAD

**Issue by chairmanxyz** [quisquous/cactbot#2261]
No triggers during the fight and there's no section for it under the 5.0 raids in the settings. I see the files in the folder though so I'm not sure why it isn't working.
![image](https://user-images.githubusercontent.com/30763902/102932850-f481fa80-4455-11eb-8e39-cb4c9802789e.png)

**Comment by quisquous** [comment]
It's in the repository, but I haven't done a release with it yet.

**Comment by quisquous** [comment]
Fixed in https://github.com/quisquous/cactbot/releases/tag/v0.21.10
