### ISSUE TITLE
Cactbot not working after previous FFXIV hotfix

### ISSUE THREAD

**Issue by Xanxus015** [quisquous/cactbot#2263]
Hello,

Just a quick question, is cactbot currently down due to the previous hotfix?
Countdown timeline + call out in Summerford works fine, but inside raids it's not calling out or showing timelines.

I tried reloading the Cactbot Overlay plugin but same thing is still happening

**Comment by JLGarber** [comment]
This will always be the case after any hotfix that updates the client. The underlying FFXIV plugin for ACT will be non-functional until it's updated. Fortunately, the beta for that plugin was just posted, so the release version should be available in the ACT auto-updater Sometime Soon.

**Comment by Xanxus015** [comment]
Thank you! I
