### ISSUE TITLE
Raidboss addon not activating

### ISSUE THREAD

**Issue by ArashiOoyama** [quisquous/cactbot#228]
So, I've a feeling this may be related to the other issues, but when attempting to run the Raidboss addon, I can receive the "Game On" audio during a ready check, but nothing further. No items pop up, no sound effects go off. Nothing. 

There's no listed error (I thought one existed, but it involved not being allowed past the firewall), and I have the cactbot DPS meter run just fine, meaning it's accessing/processing data from ACT. 

I moved the ACT installation to a new folder as well in an assumption that it could be related to that from another thread, and nada there. I've clean installed, and used the exe file provided in a recent thread as well, followed by dropping the newest cactbot folder onto the installation location to overwrite to the newer files.

**Comment by quisquous** [comment]
If the ready check is working, then that means that raidboss is working, at least to some degree or another.  Are you able to try the summerford farms test? If you teleport there and do a countdown, do you get triggers and timelines there?

**Comment by quisquous** [comment]
Just checking back in if Summerford Farms test worked for you?

**Comment by quisquous** [comment]
Due to lack of response here, I'm going to close this.  Feel free to comment again if you're still having issues.
