### ISSUE TITLE
o10n and o10s

### ISSUE THREAD

**Issue by noxaeternus** [quisquous/cactbot#230]
Hi,
Thanks for the great work as always. Quick request please. 
Could you remove or not use "/" in the TTS elements. Sounds really strange when spoken out. Maybe replace with "or" or "and". Example:

Next Spin: In/Out' to Next Spin: In or Out'
Next Spin: Cardinals/Corners to Next Spin: Cardinals or Corners

Saves me changing with each update. 
Thanks a lot.

**Comment by quisquous** [comment]
Thanks! I don't use tts for most things, so I don't notice this sort of thing.  Please let me know if I ever mess this up again or if there's any other tts that you find cumbersome or wrong.
