### ISSUE TITLE
Allow users to overwrite timelineReplace

### ISSUE THREAD

**Issue by fly1n** [quisquous/cactbot#2307]
I want to do customization to my timeline display to directly display actions instead of spell names, but I found currently this is not overwritable?

**Comment by JLGarber** [comment]
[Cactbot customization](https://github.com/quisquous/cactbot/blob/main/docs/CactbotCustomization.md#overriding-raidboss-timelines) looks like it should be what you want. Can you describe the way it wouldn't work for you?

**Comment by fly1n** [comment]
Copy paste the timeline file and manually replace each display name works for me, but I am not sure if it can be easier, something like
Options.Triggers.push({
  zoneId: ZoneId.TheEpicOfAlexanderUltimate,
  timelineReplace: [
    {...}
  ]
});

**Comment by panicstevenson** [comment]
The only part that feels like a "gotcha" that makes me consider it more is the fact that you'd be able to shoot yourself in the foot with a standard trigger file and custom timeline file if the trigger file contains timelineTriggers, especially since timelineTriggers aren't supported in the user-defined triggers, meaning you'd have to overwrite the trigger file and run a local webpack server to solve this problem (or just don't change the things that are specified as timelineTriggers).

**Comment by quisquous** [comment]
Mmm, I think timelineTriggers should be supported in user files? And, timelineTriggers are based on the original English text, and ignore timelineReplace.  I feel like I'm not sure I understand the worry that you have.

**Comment by quisquous** [comment]
Yeah, it looks like this is supported.

If you are playing in English, add something like to your user file, and then do a `/countdown 5` in Summerford Farms.  You'll see the replacements in the test timeline.
```javascript
Options.Triggers.Options.Triggers.push({
  zoneId: ZoneId.MiddleLaNoscea,
  timelineReplace: [
    {
      locale: 'en',
      replaceText: {
        'Final Sting': 'Finalest Sting',
        'Angry Dummy': 'Mildly Irate Dummy',
      },
    },
  ],
});
```

Does this work for you? Is there something else you're trying to do?

**Comment by JLGarber** [comment]
That's cool. I was in fact going to ask about that on the EN ReplaceText PR, but you beat me to it here. This will make "Do I abbreviate this or not" decisions slightly less stressful!

**Comment by quisquous** [comment]
I think this is implemented and working.  Closing this for now.
