### ISSUE TITLE
No more provoke alert

### ISSUE THREAD

**Issue by mooondark** [quisquous/cactbot#2308]
With the last build (0.21.10), provoke & shirk infos for tanks are no more shown.

Tested in normal raid & trials.

Moon.

**Comment by MaikoTan** [comment]
What is your job?
Only Tank and Healer would receive provoke/shirk notification.

**Comment by mooondark** [comment]
I play DRK. It was working fine the other day.

**Comment by MaikoTan** [comment]
Try to enable the debug option, and switch zone once.
Is there something like `Info: RaidBoss: BrowserConsole: Loading 00-misc/general.js` logged in OverlayPlugin?

**Comment by mooondark** [comment]
Well, this is weird. Just reinstalled the lastest FFXIV_ACT_Plugin, and now it works again.
It was updated automatically this morning, but a manual reinstall fixed it.

Thanks @MaikoTan for testing on your side.

**Comment by MaikoTan** [comment]
Oh, maybe the machina library not updated,
congratulation you fixed it!
