### ISSUE TITLE
UI Settings override defaults

### ISSUE THREAD

**Issue by unfaiyted** [quisquous/cactbot#231]
Hey! I wanted to change the UI for everything to better align with the games UI and stick out less.

Sample of what I did so far: 
https://codepen.io/unfaiyted/pen/bxPZLB

Was wondering if you had a UI settings for overrides, like you do with the user settings folder.

Thanks again!

**Comment by quisquous** [comment]
There are definitely UI overrides.  You can drop things into **cactbot/user/raidboss.css** and it will include after the built in CSS.

Let me know if this doesn't work for you or if there's more stuff you want to change.  Some folks have needed more things exposed to customize everything.

**Comment by unfaiyted** [comment]
Hey Thanks! I found the stuff you have already included for overrides. I'll close this for now!
