### ISSUE TITLE
5.4: Fishing plugin update

### ISSUE THREAD

**Issue by JCmAxohtwEoK0fdaQip7** [quisquous/cactbot#2313]
The following file is out of date for the new fish/zones added in 5.4
cactbot-main\cactbot-main\ui\fisher\static-data.js

It is auto-generated from 
cactbot-main\cactbot-main\util\gen_fisher_data.py

**Comment by quisquous** [comment]
This was updated in #2291 but hasn't been put in a release yet.

**Comment by quisquous** [comment]
Released in 0.21.11.
