### ISSUE TITLE
feature idea: groupTTS

### ISSUE THREAD

**Issue by unfaiyted** [quisquous/cactbot#232]
Hey again, 

I have been editing the triggers some each time we have an update for some time and I realize the majority of it is me trying to adjust for my raid group since I stream the ACT triggers through discord for my whole team. 

The triggers now are user centric in the way they are designed and since I want some of my triggers to be specific to my group I just rewrite them normally. 

My thoughts: 

**raidboss setting:** 
```js
// Will override the singular TTS alerts if a group alert is set for a specific trigger
// Change phrasing to make sense in a group setting
Options.GroupSpokenAlertsEnabled = false;
```

**concept trigger:**
```js
    {
      id: 'O10S Fire Marker',
      regex: /1B:........:(\y{Name}):....:....:0017:0000:0000:0000:/,
      alarmText: {
        en: 'Fire Marker on YOU',
      },
      infoText: function(data, matches) {
        if (data.me != matches[1])
          return 'Fire on ' + data.ShortName(matches[1]);
      },
      // default TTS callout
      tts: function(data) {
         return {
             en: 'Fire on YOU',
         }
      },
      // Calls outs for every person who gets fire, if group alerts enabled overrides default, if exists.
      groupTTS: function(data, matches) {
            return 'Fire on ' + data.ShortName(matches[1]);
      }
    },
```
I'd be happy to fork and make the changes myself to integrate this functionality. Was hoping for some clarity on the part of the code to look at for the tts portion and implementing.

Thank you!

**Comment by unfaiyted** [comment]
I actually tested and got this working on my end as described with some changes to the popup-text.js file and a few others. I don't know if you want this functionality in the core product. If so I can submit a pull request.

**Comment by zixsen** [comment]
I would be really interested in this!

**Comment by tant4lus** [comment]
I can see this being useful for a healer who would have to cast a heal.

**Comment by unfaiyted** [comment]
Since we added this, going to close this topic! Thanks!
