### ISSUE TITLE
Not Getting Titan Bomb/Shape Alerts E12S

### ISSUE THREAD

**Issue by Agres53** [quisquous/cactbot#2333]
I'm not getting either text or sound alerts for Titan bomb shapes in E12S. I can see them as an option in cactbot settings, and they are enabled. As far as I am aware, every other alert is working.

I do have the most recent update, and have also tried a full reinstall of cactbot but that hasn't changed anything. Other people in my static have cactbot and the alert was working for them.
[TitanBombLog.zip](https://github.com/quisquous/cactbot/files/5756360/TitanBombLog.zip)

**Comment by quisquous** [comment]
Next time you are trying this, can you check if there are any errors in your overlayplugin log when they don't show up?

**Comment by Veiguesama** [comment]
Oh I see yeah. It's the same then, no Titan and no Statue. Thank you for your time.

**Comment by Agres53** [comment]
There were no errors in the overlayplugin log. I have since completely uninstalled and reinstalled ACT, overlayplugin, and cactbot. I'll let you know if the issue continues or was fixed after my next attempts.

**Comment by Agres53** [comment]
Still having the issue. After a full reinstall of all parts, and a computer restart.

**Comment by quisquous** [comment]
And no errors in your overlayplugin log when this is happening?

**Comment by Agres53** [comment]
No errors. While I did a full reinstall, I copied the config file so I wouldn't lose my custom timers. It could mean there is some act option that I changed that carried over.

**Comment by quisquous** [comment]
Hmm.  They definitely worked for me tonight, sorry.  I'll try to add some debugging lines before the next release so this can be tracked down.

**Comment by Agres53** [comment]
Nothing is out of place in the log I posted? The information needed for the call out is there, it's just not being called out?

**Comment by quisquous** [comment]
I think I see what the issue was.  Let me know if this is still broken after the next release.
