### ISSUE TITLE
volume is extremely high since the last patch 

### ISSUE THREAD

**Issue by sisco1986** [quisquous/cactbot#234]
i had to disable the addon because its actually hurting my ears now, since the last patch the sound effects are at least 4 times higher than the game

**Comment by quisquous** [comment]
Sorry, nothing has changed in the volume settings.  I think this is all in Windows to configure.

**Comment by Lifell** [comment]
This is indeed from Windows his end. I was ingame and noticed the same thing. It seems the volume sliders in ACT (Options tab > Sound Settings) don't work anymore. Just open the volume mixer in Windows and adjust the sound there. I've set it to 20.

Right click the speaker icon in your tray > "Open Volume Mixer".

**Comment by sisco1986** [comment]
yeah.. that just doesn't work on my end, i had to edit and normalize every single sound but then a new cactbot release deleted my work (this was my fault) so i just had to delete cactbot, not gonna modify the entire sound volume on my system just because cactbot doesn't have a sound slider

**Comment by quisquous** [comment]
Yeah, I'm not sure what you mean by "doesn't work on your end".  If you open ACT and then play a sound with it, it should show up in the Windows volume mixer, and that is where you adjust sounds for all of ACT.  Does that not work for you?

Do you adjust the ACT volume levels directly in ACT, under its Options->Sound Settings options?

**Comment by retracx** [comment]
Sisco is just a idiot who doesn't know how to lower the volume of a program on windows. Thanks for the hard work. Really appreciated. @quisquous

**Comment by quisquous** [comment]
@retracx Hey, knock that off.  Please don't jump into comments and insult people trying to fix their problems.

**Comment by quisquous** [comment]
I'll also mention here that you can add options to your **cactbot/user/raidboss.js** file to set the volume levels for all the cactbot sounds: https://github.com/quisquous/cactbot/blob/master/user/raidboss-example.js#L63

I'm going to close this, as I don't think there's anything else for me to do here.
