### ISSUE TITLE
E12S, Statue number not showing

### ISSUE THREAD

**Issue by Veiguesama** [quisquous/cactbot#2349]
I was wondering if I was the only one having this bug, it used to work, but it doesn't show the number you get when tethered to the right or left statue on e12s part 1 anymore.
I can't see the option in cactbot settings. As far as I am aware, every other alert is working.

EDIT : I also don't get the Titan headmarks alerts.

**Comment by quisquous** [comment]
This seems like the same issue as #2333, potentially.  It is curious to me that it worked before but you can't see the options in the cactbot settings.

Can you screenshot your Eden's Promise: Eternity (Savage) section in the cactbot ui? `E12S Promise Headmarker` should be the first item in the list.

Are there any errors in the OverlayPlugin log when this happens?

**Comment by Veiguesama** [comment]
I didn't verify before when it was working but here is the screenshot.

And no, no errors with Overlayplugin. :)

![image](https://user-images.githubusercontent.com/76577125/103486461-66ffbc80-4dfe-11eb-8d8e-dcd10f08180f.png)

**Comment by quisquous** [comment]
Is that different than what you were seeing in the options before? What did you mean by "I can't see the option in cactbot settings."?

**Comment by Veiguesama** [comment]
That's what I mean, I actually didn't check when it was working, what options I had. I can't tell you if it was different than now. I can't see in the image I posted here the options for statue.

**Comment by quisquous** [comment]
The options for the statue are in the image.  That's what triangle1-4 and square1-4 are.

Since your options are fine, it sounds like this is the same as #2333.

**Comment by Veiguesama** [comment]
Oh I see yeah. It's the same then, no Titan and no Statue. Thank you for your time.

**Comment by quisquous** [comment]
Ok, I'll close this and everybody can follow up with any additional information in #2333.  Thanks!
