### ISSUE TITLE
Suzaku EX timeline ends too early

### ISSUE THREAD

**Issue by Fractura** [quisquous/cactbot#235]
https://github.com/quisquous/cactbot/blob/master/ui/raidboss/data/timelines/suzaku-ex.txt is ending on the soft enrage(?) rather than the real one (with all fields purple).

I've been going through the logs and it should look like this at the end:
```
665.2 "Scarlet Hymn" sync /:Suzaku:3237:/
680.6 "Ruthless/Mesmerizing" sync /:Suzaku:32D(A|B):/
685.8 "Hotspot x8" duration 7.7
700.7 "Southron Star" sync /:Suzaku:32DF:/
705.2 "Hotspot x8" duration 7.7
724.1 "Phantom Flurry" sync /:Suzaku:32DD:/
730.3 "Phantom Half" sync /:Suzaku:32DE:/
735.8 "Scarlet Hymn" sync /:Suzaku:3237:/
748.8 "Southron Star"
755.0 "Enrage"
```
The last Southron Star at 748.8 can also be omitted since it's a long cast, ending after the enrage mechanic.

**Comment by quisquous** [comment]
Perfect, thanks.  I'll add this in before the next release.

**Comment by xarfger** [comment]
I think this is a Bug... sometimes the purple fields will be there at ~8:40 but sometimes you will get a fourth colour phase ... I don't know what the real enrage timer is. Also the cast bar for the enrage is filling up slowly but as the phoenix reaches the first purple thing its a wipe. I think there will be a fix in the next days / weeks.

**Comment by Fractura** [comment]
8:40 would be matching where usually the 4+4+4+4 pattern appears... so apparently you can push dps so hard that you skip two entire phases? 8:40 is definitely a bug/unintended behavior because there are only around 30 groups that killed Suzaku in <9min on fflogs. Enrage at 11:15 (one phase-skip) seems more plausible but I think 12:45 is the "normal" one.

> Also the cast bar for the enrage is filling up slowly but as the phoenix reaches the first purple thing its a wipe.
Yea I noticed that as well. She casts a very slow Southron Star while all fields are purple. Not sure what the purpose is.

**Comment by Fractura** [comment]
Actually the timings are off, despite them using log timings, feels like a solid 10 seconds.

**Comment by quisquous** [comment]
Thanks for the log.  I don't know what to do about the early enrage possibility, so I'm just going to leave the timeline assuming it will go long.

**Comment by Fractura** [comment]
Yea it probably makes sense just to keep it one way until square fixes it to however it is intended.
