### ISSUE TITLE
o11s starboard/laboard directions

### ISSUE THREAD

**Issue by nicholasnjh** [quisquous/cactbot#236]
I dont know if its just me, but i usually turn towards the boss' direction he's facing and only do laboard/starboard properly , having it call out left/stay is pretty comfusing ._.

**Comment by quisquous** [comment]
Let me know if 0.8.3 doesn't do what you want.

Starboard always says left, and if it's starboard again it says "move (left)".  0.8.2 had some wrong directions in parentheses.

**Comment by nicholasnjh** [comment]
yup its alright now :o
