### ISSUE TITLE
Minimum time to notice a mechanic

### ISSUE THREAD

**Issue by HbergonZ** [quisquous/cactbot#2360]
How can i set the minimum time to notice a mechanic?

**Comment by quisquous** [comment]
Sorry, I don't know what you mean.  For timeline triggers, you can change `beforeSeconds` in the cactbot ui.  For non-timeline triggers, there is no earlier, because it's as soon as the boss uses an ability.

You may want to look into adding new timeline triggers if you want earlier warnings on non-timeline triggers.

**Comment by HbergonZ** [comment]
For Exemple (https://imgur.com/a/IiC6Nle) the mechanic "7" will occur in few seconds, and a text mensage will appear in my screen telling me what to do. The message will appear when a certain time is missing for the mechanic. I want to edit this time.

**Comment by quisquous** [comment]
In the cactbot config ui, there is `Timer bar show window (seconds)` which is how far ahead to show mechanics.

**Comment by HbergonZ** [comment]
I will try it. Another question is: Can i change the skills names in code? :s

**Comment by miaonima** [comment]
Hi @HbergonZ! The timeline is stored as text files under ui/raidboss. Or you can use a user file and add a timeline entry.

Triggers use infoText/alertText/alarmText to show you messages. Some triggers are timeline triggers. Those are the ones that fire when a matching timeline entry is reached. You can use beforeSeconds to adjust the time window. Other triggers fire on certain events (regex matching on network/game logs), and these triggers can be delayed but cannot notice you in advance.

If you would like to write custom triggers I found the [docs](https://github.com/quisquous/cactbot/blob/main/docs/CactbotCustomization.md) very useful. Hope this helps.

**Comment by HbergonZ** [comment]
Hello! Thanks for answer! I couldn’t find where it is to edit beforeSeconds ☹

Luis Henrique Bergonzini Souza
Universidade Federal de Rondônia - UNIR
V Turma - Engenharia Civil
Mat.: 201520982

De: yhz<mailto:notifications@github.com>
Enviado:terça-feira, 9 de fevereiro de 2021 01:57
Para: quisquous/cactbot<mailto:cactbot@noreply.github.com>
Cc:HbergonZ<mailto:luishenriquebergsouza@outlook.com>; Mention<mailto:mention@noreply.github.com>
Assunto: Re: [quisquous/cactbot] Minimum time to notice a mechanic (#2360)


Hi @HbergonZ<https://github.com/HbergonZ>! The timeline is stored as text files under ui/raidboss. Or you can use a user file and add a timeline entry.

Triggers use infoText/alertText/alarmText to show you messages. Some triggers are timeline triggers. Those are the ones that fire when a matching timeline entry is reached. You can use beforeSeconds to adjust the time window. Other triggers fire on certain events (regex matching on network/game logs), and these triggers can be delayed but cannot notice you in advance.

If you would like to write custom triggers I found the docs<https://github.com/quisquous/cactbot/blob/main/docs/CactbotCustomization.md> very useful. Hope this helps.

**Comment by HbergonZ** [comment]
You mean one of these archives? Or ic ACT?

[cid:image001.png@01D6FF2C.04195020]

Luis Henrique Bergonzini Souza
Universidade Federal de Rondônia - UNIR
V Turma - Engenharia Civil
Mat.: 201520982

De: yhz<mailto:notifications@github.com>
Enviado:terça-feira, 9 de fevereiro de 2021 01:57
Para: quisquous/cactbot<mailto:cactbot@noreply.github.com>
Cc:HbergonZ<mailto:luishenriquebergsouza@outlook.com>; Mention<mailto:mention@noreply.github.com>
Assunto: Re: [quisquous/cactbot] Minimum time to notice a mechanic (#2360)


Hi @HbergonZ<https://github.com/HbergonZ>! The timeline is stored as text files under ui/raidboss. Or you can use a user file and add a timeline entry.

Triggers use infoText/alertText/alarmText to show you messages. Some triggers are timeline triggers. Those are the ones that fire when a matching timeline entry is reached. You can use beforeSeconds to adjust the time window. Other triggers fire on certain events (regex matching on network/game logs), and these triggers can be delayed but cannot notice you in advance.

If you would like to write custom triggers I found the docs<https://github.com/quisquous/cactbot/blob/main/docs/CactbotCustomization.md> very useful. Hope this helps.

**Comment by quisquous** [comment]
@HbergonZ Sorry for the belated response.  I think if you are interested in changing the text of a timeline, you should look at the customization docs linked above (https://github.com/quisquous/cactbot/issues/2360#issuecomment-775717260) as well as issue #1835 and #2307.
