### ISSUE TITLE
E12s some triggers are not showed at KO lang

### ISSUE THREAD

**Issue by Una-p** [quisquous/cactbot#2361]
It's very odd problem, my cactbot e12s's some triggers (titan's yellow/orange/blue rock, second boss's almost thing) are not printed.

And... I know that's not translated at current release. I think this is problem and solution is also make new release that included #2358.

But why is it happened? It originally call out in English if it was not translated, but this one are not printed.

**Comment by Una-p** [comment]
Eww.. want to change label.. its more like a question than a bug.

**Comment by Una-p** [comment]
And I'm not sure but 'bigAOE' trigger isn't printed though translated.

**Comment by quisquous** [comment]
Is this #2333?

**Comment by Una-p** [comment]
Sorrry for same asking I didn't even search.. I think same as that.
