### ISSUE TITLE
E12S Relativity Debuff Collector not working

### ISSUE THREAD

**Issue by 1unie** [quisquous/cactbot#2363]
The x > y > z callout for Relativity is not working. 

> EDIT: I originally thought this was only on French logs although I'm no longer think this is the case. 

I don't understand the way the RegEx works enough to understand why, as it seems that it should be grabbing the ID of the effect rather than a translation. 
   
This at least affects Flare, Gaze, Aero and Ice... 
```
id: 'E12S Relativity Debuff Collector',
      // 690 Spell-In-Waiting: Flare
      // 996 Spell-In-Waiting: Unholy Darkness
      // 998 Spell-In-Waiting: Shadoweye
      // 99C Spell-In-Waiting: Dark Eruption
      // 99E Spell-In-Waiting: Dark Blizzard III
      // 99F Spell-In-Waiting: Dark Aero III
```

From investigating, it could be that in the localisation section it says:
`'Spell-In-Waiting': 'Déphasage incantatoire',`

And it could be that it should be the below instead?
`'Spell-In-Waiting': 'Sort Déphasé',`

When the boss is casting the spell it's "Déphasage incantatoire" as per below log line:
`[02:04:07.556] 15:40015466:Prêtresse Des Ténèbres:58C8:Déphasage Incantatoire:40015466:Prêtresse Des Ténèbres:E:7100000:1B:58C88000:0:0:0:0:0:0:0:0:0:0:0:0:56753367:62524080:0:10000:0:1000:-0.04577637:-65.35437:75:-0.008005857:56753367:62524080:0:10000:0:1000:-0.04577637:-65.35437:75:-0.008005857:000168DF`

But when the debuff is applied it's actually "Sort Déphasé" as per below log line:
`1A:106AAC07:Name Surname gains the effect of Sort Déphasé : Éruption Ténébreuse from  for 11.96 Seconds.`

Could that be it? There's also typically a space after the : in French grammar, so I wonder if that could be what's causing the issue, but I still can't wrap my head around how Cactbot is actually grabbing the effect IDs so I might be completely wrong.

Happy to help investigate further or provide logs if needed, but I truly have no idea how to fix it myself.

**Comment by MaikoTan** [comment]
Effect IDs are from [network log lines](https://github.com/quisquous/cactbot/blob/main/docs/LogGuide.md#network-log-lines), so it is language-independent, if it works in EN, it should work in FR too...

**Comment by 1unie** [comment]
Right, that’s what I thought. Something else is causing the issue then, but I’m not sure how to investigate further.

**Comment by 1unie** [comment]
Looking at closed issues, I reckon this might be the same bug as #2333 and #2349 because I don’t get Titan Bombs nor do I get Statue tether numbers in that fight.

**Comment by 1unie** [comment]
Issue might have been fixed by @quisquous in a recent commit but it could also be a different bug (the fix seems to only apply to Door Boss?). All I know is that I was also missing the triggers for Titan Bombs and Statues in the Door Boss, I do play DPS, and I’m also missing Relativity Triggers in phase 2: https://github.com/quisquous/cactbot/commit/bf87ca77f246d9957d23c43114d074778cb9dd5b

**Comment by 1unie** [comment]
Can confirm this was not resolved by the latest release.
