### ISSUE TITLE
Is there a workaround?

### ISSUE THREAD

**Issue by AngelSeed** [quisquous/cactbot#2372]
AdvancedCombatTracker, Version 3.5.0.273,
After updating, cactbot freezes and freezes.
In addition, there is no problem with measurement.
When I revert to version 3.4.10.272, it works fine, but I don't know the cause,
If you find any other problems, please let me know.

Language is Japan

**Comment by quisquous** [comment]
Sorry, I don't know offhand.  I have not heard of any cactbot issues related to upgrading ACT.  You might want to ask in the ffxiv act discord.

**Comment by AngelSeed** [comment]
Thank you for your reply.
I will try and error while watching a little more
Thank you

**Comment by quisquous** [comment]
I'm going to close this.  If you are still having issues, I would recommend asking in the ffxiv act discord.
