### ISSUE TITLE
Clouded Cactbot config page?

### ISSUE THREAD

**Issue by MaikoTan** [quisquous/cactbot#2387]
## Summary

Just noticed cactbot config page here was loaded from local file `ui/config/config.html`, since we can already host our cactbot overlays on GitHub pages, could `config.html` also be on the cloud? (Or, at least an option to switch between cloud/local version?)

![Snipaste_2021-01-13_22-02-49](https://user-images.githubusercontent.com/19927330/104462334-6aa7f600-55eb-11eb-83af-44462e00c940.png)

**Comment by quisquous** [comment]
Yeah, I think making it always use the github hosted version seems reasonable? I think it means that we need to make sure any changes to config are backwards compatible with older versions of the plugin, but that shouldn't be too hard.

**Comment by MaikoTan** [comment]
But I should point out that `github.io` domain is not accessible or hardly accessible in China, so when we apply this, we may need to expose an option for Chinese developers to change the config page URL.

**Comment by quisquous** [comment]
Hmm, that's something I didn't know.  That will be something I'll have to think about in the future if the cactbot plugin goes away.

I am confused a little how an option would work.  If you need to get to the config page to set an option, that seems like an impossible situation.  If somebody in China changes the option to "use the github.io version", and then suddenly their config doesn't work, how do they change it back?

**Comment by MaikoTan** [comment]
Set it in the config json/xml file, I think this option is for developers, we don't need to expose it to regular users.

But it looks like that when we fully switch to a clouded version, if an user just got bad network and unable to fetch config page, then he would not be able to change every thing via GUI?

I think to switch to clouded config page is aim to update it ASAP, so maybe we can continue to use the current approach, and plugin would fetch/update config page local files ASAP?

**Comment by valarnin** [comment]
All of the config settings are saved back to ACT, not to local storage or anything, so you could just default it to cloud and try local instead if cloud fails, or go the other way and default to local and test cloud, then redirect there.

**Comment by quisquous** [comment]
Belatedly, what's the goal with this?  Users who are on older versions of cactbot will have options that don't apply.  Developers can load cactbot directly from where the vsproject builds the dll, and get their local version.  Who is the cloud version for?

**Comment by MaikoTan** [comment]
Well, (how old this issue is...)
I think my original thought is to use the newest version always without download the release. But yes, I didn't thought that would cause incompatiable bugs when version bumps.
Maybe it can be closed, sorry!

**Comment by quisquous** [comment]
(sorry about the old issue, I was just going through old ones and trying to follow up on some things that maybe didn't make any sense any more.)
