### ISSUE TITLE
wol-ex, raidboss trigger bug

### ISSUE THREAD

**Issue by Jaehyuk-Lee** [quisquous/cactbot#2391]
## Description

mistakenly changed regex I guess.

## Additional information

https://github.com/quisquous/cactbot/commit/3c63a9f5446e0356736207fd85a9278dbc4b8977
`id: 'WOLEx Spectral Ninja',`
this trigger got skill ID changed, I guess this was a mistake.
Many people are reporting bad calling out about ninja, not Imbued Saber

**Comment by Jaehyuk-Lee** [comment]
I reverted that ID part, but it does not fix completely, it was wrong before that commit too.

**Comment by Akurosia** [comment]
If you changed the ID, you need to change the source as well (wolex <-> phantom ninja).

but tbh i never really had any problems with phantom callouts o.o

**Comment by Jaehyuk-Lee** [comment]
ah, the sources were changed too, I missed it.

**Comment by Jaehyuk-Lee** [comment]
It was plugin bug, I missed something.
