### ISSUE TITLE
Settings Module - Discussion

### ISSUE THREAD

**Issue by unfaiyted** [quisquous/cactbot#241]
I think the real catch is the question of how you save all of the settings.  Maybe we would need to send some json back to C# and write that out on disk.  Maybe something that writes out **cactbot/user/raidboss-autoconfig.js** so that folks can still do manual customization, but this UI could generate the same sort of input that folks are now doing manually.  That's just a thought, though.  Maybe you have some alternative idea of how to persist and reload this data.

_Originally posted by @quisquous in https://github.com/quisquous/cactbot/issues/155#issuecomment-425288116_

**Comment by unfaiyted** [comment]
I had a few ideas about the current way the settings works. 

You are using a sort of priority system if I understand it correctly

1. Loads module, for example **raidboss**
2. Module loads its default settings as variable `Options`
3. `UserConfig` class loads configuration information from files `user\raidboss.js`
4. You have something setup to load the script even when the user is using a remote hosted file. If I understand it correctly. 

I had the idea of using localStorage to store the settings information for the current user.

We could, in theory, append these steps to sync to the localStorage. 

We would still have the priority system as it is now, but the localStorage would be the final settings location for all of this. If the values didn't exist in localStorage, they would be loaded and then localStorage would be created as part of this process. If they did exist, they would override the settings just as the user settings folder does now. 

LocalStorage -> user\raidboss.js -> raidboss.js

We could create an EXPORT/IMPORT function to store the LocalStorage values and this could make it easy for a raid-group to share settings, or custom triggers if added to UI at some point. 

Some downsides to this method obviously do exist, for example if someone clears all browser data it could delete these settings. 

This would have an advantage though for people using the current version hosted on GitHub, the localStorage settings would be able to work pretty seamlessly. 

**Other related thoughts:** 
I had thought it would be neat to extend the UI to add custom triggers, name overrides, adding new triggers could also be done, with some preset conditions for non-technical types. Of course at some point I think it would be ideal to be able to store these locally and you would need some backend to deal with that.

I'm not entirely sure what functionality you can extend within the context of the actual DLL. We would only really need the ability to perform some CRUD operations.

**Comment by quisquous** [comment]
Local storage sure sounds good, except it is not hooked up in CefSharp and doesn't work.  I would have likely used it for the pull counter if I could.

I think that means that we'd need to send the config back to the C# plugin so it can persist it to disk.  The pull counter code already does this (although it stores it in the ACT config for the plugin, which is maybe not what we want to do here).

One option here is to just have this write out something like **cactbot/user/raidboss-autoconfig.js**, so that it's in a consistent spot with the manual config files and users will know where to delete it if need be.  This can then be included in that priority order (probably before the manual one?).  I'm not sure if that'd be a pain to read back in, though and know what the autoconfig settings were.

**Comment by quisquous** [comment]
Another open question for me is what scope should this config run at, global for cactbot or local per module.  I can kind of picture either option?

Your mock has you click an icon on screen to bring up the config, but most overlays I suspect have click through enabled, so probably we'll need a C# button that says Config that could pop up the config.  On top of that, most overlays on screen aren't sized well to fit that config window.  (For example, oopsyraidsy is pretty small for me, and pull counter is even tinier.  Sending some JS to show a config menu inside the existing overlay wouldn't have any room.) So maybe hitting such a "Config" button would need to pop up another entirely separate overlay that's big enough for the config?

An alternative to all of this would be to have a separate config html file that folks would have to add as a separate overlay if they wanted to configure any of the overlay types, but that seems a bit cumbersome for a tool that's supposed to be making it easier.

**Comment by xDemonessx** [comment]
> An alternative to all of this would be to have a separate config html file that folks would have to add as a separate overlay if they wanted to configure any of the overlay types, but that seems a bit cumbersome for a tool that's supposed to be making it easier.

honestly I would prefer this method - bonus points if it allows for you to switch different timeline/trigger file versions for those who edit them.

**Comment by unfaiyted** [comment]
So the way I wrote the UI so far was a separate config html file like you are talking about. It's its own module that they would have to setup like this: **ui/settings/settings.html**

Also on the topic of complexity the settings UI is optional I would think and they could either, continue editing files (arguably more confusing to some) or leave the default settings, or use settings overlay

On the config saving, I think sending it back to the C# plugin isnt a bad idea at all and overcomes some concerns with localStorage anyway (mostly clearing the data somehow losing it)

Here is an update to the UI gif I sent last time: https://gyazo.com/5b18dedcb622434f8263890034f81129

Few concerns with this after some work:

If it got bigger and had more features I found that some things are not working well with the UI and maybe we have a workaround and maybe not specifically *focus* and input boxes. 
I noticed with the UI locked in place it wont show a focus on the input box, it ignores several CSS styling and often wont type in the box. **Is this a setting/config I'm overlooking?*

**Comment by xDemonessx** [comment]
@quisquous - usually just mechanical direction. The most recent example would be Larboard Starboard - cactbot calls the safe spot, when some players prefer having the mech called out directly:      
```
 id: 'O11S Starboard Cannon 1',
      regex: / 14:326[23]:Omega starts using Starboard/,
      condition: function(data) {
        return data.lastWasStarboard === undefined;
      },
      alertText: {
        en: 'Starboard on Right',
```

vs

```
 id: 'O11S Starboard Cannon 1',
      regex: / 14:326[23]:Omega starts using Starboard/,
      condition: function(data) {
        return data.lastWasStarboard === undefined;
      },
      alertText: {
        en: 'Left',
      },
      run: function(data) {
        data.lastWasStarboard = true;
      },
    },
```


This is also the case in Suzaku - Cactbot states "Get In" when I'd rather "Knockback". "Get Out" would be "Draw In". This is also more in line with in game language: 
![image](https://user-images.githubusercontent.com/3487603/46249905-b6bcd580-c3f6-11e8-80f5-04a594e8352b.png)

**Comment by quisquous** [comment]
@xDemonessx If there are triggers you don't like, the current way to fix that is to disable them by id in your cactbot/user file and then to add other triggers that do the thing you want in your cactbot/user file.  That way you don't have to keep re-editing.

**Comment by xDemonessx** [comment]
> 
> 
> @xDemonessx If there are triggers you don't like, the current way to fix that is to disable them by id in your cactbot/user file and then to add other triggers that do the thing you want in your cactbot/user file. That way you don't have to keep re-editing.

OK thanks, I keep forgetting about that. Its a lot to keep track of and editing timelines directly was always easier for me.

**Comment by unfaiyted** [comment]
@quisquous Yeah I found it a little suprising as well. I am not sure but I was looking into how Electron (https://electronjs.org/) does it and it does not seem to be having the same issue  and the concept is similar.  They use webkit specifically to deal with the moving in CSS `-webkit-app-region: drag;` I couldn't figure out if that was in this codebase somewhere or if its handled by OverlayPLugin in some way. 

With more thought on the subject I actually wonder if it might be easier to separate the Settings UI and the Overlays in a way. 

You could create an entire interface in electron and have the additional file editing functionality. 

Things like editing triggers or getting a list of triggers to disable might be rough in the overlay itself, I think we could do it though if we got creative. 

Some of this stuff might be a lot easier with a separate, but full featured UI

**Comment by unfaiyted** [comment]
Yeah I do agree with you about the flow being a lot easier if everything is is one very consolidated codebase.

In many ways I think you could look at this like a front-end to the back end interface, which could merit the separation.  You might be right that the app region thing is a very specific implementation. I couldn't find any way to override the way it was being handled although anything is possible I'm sure given time/effort input. It seems that it really limits the functionality which is unfortunate.

**Comment by unfaiyted** [comment]
![e3c3ddc112d76a7f1842cb730edcb0d7](https://user-images.githubusercontent.com/898928/46573197-40205a80-c957-11e8-9d84-50fe3220131c.png)

**Comment by unfaiyted** [comment]
![8673cfd75d168fad5550853cdc189882](https://user-images.githubusercontent.com/898928/46574118-55e84c80-c964-11e8-91b3-0191bea5e540.png)

**Comment by quisquous** [comment]
I think my biggest feedback here is that I think showing JavaScript at all and adding support for adding triggers isn't necessary.  I don't feel super strongly on this point, so if you feel differently, please push back.  I'm just trying to be a little bit opinionated here on what a config tool should look like.

As for showing JavaScript at all, if the goal is to show what potential trigger output looks like, I think there are maybe other ways to do that? It might also be enough to just say "this trigger outputs Alarm" or "Alert or Info" etc.

I also feel a little bit that if folks want to write their own triggers, that cactbot isn't necessarily the easiest way to do that? cactbot's trigger system is flexible, localized, and something that can be checked into source control, but it's also super complicated.  If you're not a programmer, then it's not that easy to write.  (And if you're not a programmer, I'd probably suggest just writing ACT or triggernometry triggers than adding cactbot ones?) And, if you are a programmer, then probably it's not too hard for you to go add that JavaScript yourself.  I don't quite know who the audience would be for writing trigger in a config tool.

Also, the o9s image looks nice, but my only thought is that you're signing yourself (or me) up for a lot of ongoing work whenever new things come out.

Unrelated to anything else, I suspect that things you'd want on a per trigger basis would be:
* turn this trigger off entirely
* play/don't play tts for this trigger, ignoring global settings
* play/don't play sound for this trigger, ignoring global settings
* show/don't show text for this trigger, ignoring global settings

With the thought being that maybe folks set up global settings for most of what they want and then flip switches on individual triggers that they want to behave differently? I do that for tts when I don't normally have it on.  I also suspect folks will probably just want to turn a bunch of things off.

**Comment by unfaiyted** [comment]
I think you actually make a lot of good points here on that stuff.

I guess I got carried away a little bit. You are right Triggernometry has a bunch of those features for creating smarter triggers, ACT triggers are fine for the more basic ones.

I'm going to recap on this some on your thoughts too

**Images:** 
The images can actually be harvested from the game files pretty easily so you dont need to crop or edit them or anything. I think it would be one effort per major patch cycle to get those images and a number of tools exist to help with that already. I would estimate the effort to be less than half an hour if you are already setup.
- Alternatively and possibly better we could pull the images from XIVDB or Garland tools which have APIs for dealing with that stuff.

I think the biggest thing a config tool can do for people is to 

* Create a personal config file
* Override default callout functionality. 

I wonder if being able to purely "view" the triggers logic would be nice? If so, I would say that it would be best if we kept it hidden until a user asks to see it. 

It may help with people reporting issues with specific triggers or not understanding what they should expect to get from the output, or do you think that would just be confusing too?

Thanks again!

**Comment by quisquous** [comment]
Yeah, I think my other concern with images are copyright issues.  I think if it's part of the build process and isn't checked in, maybe that's less bad.  I think I'm just less keen on checking in ffxiv images into an open source repo.

Yeah, maybe some expand button to view the trigger source might be helpful if folks aren't sure what it does? I was trying to think of any easy way to print out examples of all the triggers, but it all just felt really redundant to the triggers themselves and not any easy way to automate it all.  That seems easiest.  it probably doesn't need to be shown by default.  I suspect that the vast majority of folks only care about high level settings.

Thanks for all your work here!  I see a lot of questions about configuring cactbot (even in this thread itself) and so this tool is going to be really great! :+1:

**Comment by Lifell** [comment]
Just wanted to hop in here and say that the UI (from what I could see from the gifs) looks awesome :)

**Comment by quisquous** [comment]
I wanted to check in and see if there was any update on a config tool? Is this still something you're working on?

**Comment by quisquous** [comment]
Fixed with https://github.com/quisquous/cactbot/commit/0eeb44834f4aba1d48090538f9d6dd6ddd619439.
