### ISSUE TITLE
Cactbot Call out sound isolation

### ISSUE THREAD

**Issue by Xanxus015** [quisquous/cactbot#2415]
Is cactbot callout sound dependent to something?
I tried isolating the callout sounds using slimDX and voicemeteer banana but it still follows my main sound output.
is there somebody successful isolating the callouts especially on streams?

**Comment by MaikoTan** [comment]
I think this can be changed via system settings?
In Settings -> System -> Sound -> App volume and device preferences, find ACT and change its output device.

**Comment by Xanxus015** [comment]
I tried that one as well but it still goes to the default system sound output.

**Comment by Xanxus015** [comment]
Oh I tweaked it a little bit by changing it in the device preferences again and in voicemeter banana. it works now thanks @MaikoTan .
