### ISSUE TITLE
[Question] Cactbot hasnt updated in weeks?

### ISSUE THREAD

**Issue by encadi** [quisquous/cactbot#2427]
I know the way the plugin worked has chanegd and I dont really understand it, but it feels like I havent got an udpate request for it in weeks? It used to udpate quite frequently? Also it feels like O12S stuff doesnt tell you much?

**Comment by Akurosia** [comment]
Last update was 17 days ago.
For old stuff you need to run the content a lot of times (with a full group in best case) and check for loops, skips etc which takes a long itme and sometimes the current creators need a break as well or just want to enjoy the game.

If you want trigger/timeline than create them (documentation can be found in the docs folder of this repository) as PRs are always welcome :) .

Also o12s has all important triggers in it (everything also translated into de, fr, ja, cn, ko). What exactly are you missing in o12s?

**Comment by encadi** [comment]
Aaah Thanks and sorry i meant E12S

**Comment by Akurosia** [comment]
For e12s P2 (afaik) some stuff is not called out due to different ways of playing it.
Usually cactbot tries to avoid "forcing" you into one way of playing.

The best place to ask is the default ACT Discord from Ravahn (also best place to ask for overlay plugin issue)

**Comment by encadi** [comment]
Oh yeha but soemthing like short/long fire/ice  wouldnt force you to do anything just inform.

**Comment by quisquous** [comment]
Re: update frequency.  There's a lot of updates when content is new, but then it slows down over time.

If there's stuff missing that you would like, filing github issues or asking in discord is a good way to do it.

Sorry that there's no short/long ice/fire callout.  I'm a tank and I forgot about that one.

**Comment by encadi** [comment]
Aaah cheers would be amazing if its doable =)
