### ISSUE TITLE
error with loading cactbot in overlay plugin tab

### ISSUE THREAD

**Issue by jensendong141** [quisquous/cactbot#244]
9/29/2018 2:10:54 PM: Error: raid: Update: System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at Cactbot.CactbotOverlay.Initialize()
   at Cactbot.CactbotOverlay.Update()
   at RainbowMage.OverlayPlugin.OverlayBase`1.<InitializeTimer>b__10(Object o, ElapsedEventArgs e)

Please help. I have the latest hibiyasleep overlay plugin installed. It is not rainbow mage which is why I'm confused why rainbow mage overlay related error is popping up.

**Comment by quisquous** [comment]
That's just what the code says.  It's still named RainbowMage there, so this doesn't necessarily mean something is wrong.

This sounds like issue #100.  I think you have the wrong .NET version installed.  Can you try reinstalling .NET framework 4.6 or above?

**Comment by jensendong141** [comment]
Yup that was the problem! It's all good now. Thank you!

**Comment by quisquous** [comment]
Excellent!
