### ISSUE TITLE
when is the condition function of timeline trigger being executed ?

### ISSUE THREAD

**Issue by Trim21** [quisquous/cactbot#2442]
I'm writing some timeline trigger which depends on a property set by a bulit-in network log trigger. These triggers accessed the property in `condition` function and didn't work as I expected. I checkout the document and I didn't understand well. I'd like to ask when is the function being executed(with or without `beforeSeconds`)?

**Comment by Akurosia** [comment]
beforeSeconds does only work in timeline trigger.

The order is described here: https://github.com/quisquous/cactbot/blob/main/docs/RaidbossGuide.md#trigger-structure

So if the regex match was found it checks the condition first (than prerun etc)
If you set a variable in another trigger, make sure it executes everything as you want (e.g. do a console.log() to check it after you set it)

**Comment by Trim21** [comment]
@Akurosia I didn't get it. I guess the regex match of `tinelineTrigger` has been done when the battle begin. Is the condition function execute at the same time?

**Comment by Akurosia** [comment]
its easier when you post your trigger to give a better, more detailed answer.

**Comment by quisquous** [comment]
The order of field evaluation is https://github.com/quisquous/cactbot/blob/main/docs/RaidbossGuide.md#miscellaneous-trigger-info.  `id`, `regex`, `netRegex`, and `disabled` are all evaluated when triggers are loaded.  Everything else is evaluated in order when the regex matches.

**Comment by Trim21** [comment]
Thanks for you explanation, but I didn't understand what the time of a `timelintTrigger`'s regex match is(it's easy to understand for network log trigger). Is the phase with matched record is loaded in UI?

**Comment by quisquous** [comment]
The timeline trigger plays `beforeSeconds` ahead of time from when there is an English timeline text that matches the `regex`.  So if you have `100.0 "Some Ability"` in the timeline and you have some trigger `{ regex: /Some Ability/, beforeSeconds: 6 }`, then that will play at time=94 when the timeline gets there.

**Comment by Trim21** [comment]
thanks
