### ISSUE TITLE
Latest Release is throwing error in logs on parsing bosses

### ISSUE THREAD

**Issue by nishalp** [quisquous/cactbot#246]
10/1/2018 9:49:04 AM: Info: InitPlugin: PluginDirectory = C:\Program Files (x86)\Advanced Combat Tracker\Plugins
10/1/2018 9:49:04 AM: Info: LoadAddons: C:\Program Files (x86)\Advanced Combat Tracker\Plugins\addons\CactbotOverlay.dll
10/1/2018 9:49:04 AM: Info: LoadAddons: Cactbot.OverlayAddonMain: Initialized
10/1/2018 9:49:05 AM: Info: InitPlugin: Initialized.
**10/1/2018 9:49:07 AM: Error: Bosses: Error parsing most recent github release, no match found. Please report an issue at https://github.com/quisquous/cactbot/issues**
10/1/2018 9:49:07 AM: Info: Bosses: cactbot: 0.7.3.0 C:\Program Files (x86)\Advanced Combat Tracker\Plugins\addons\CactbotOverlay.dll
10/1/2018 9:49:07 AM: Info: Bosses: OverlayPlugin: 0.3.4.0 C:\Program Files (x86)\Advanced Combat Tracker\Plugins\OverlayPlugin.Common.dll
10/1/2018 9:49:07 AM: Info: Bosses: FFXIV Plugin: 1.7.0.13 
10/1/2018 9:49:07 AM: Info: Bosses: ACT: 3.3.2.257 C:\Program Files (x86)\Advanced Combat Tracker\Advanced Combat Tracker.exe
10/1/2018 9:49:13 AM: Info: Bosses: BrowserConsole: Unknown job role (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Plugins/cactbot/ui/raidboss/popup-text.js, Line: 164)

**Comment by tant4lus** [comment]
Are you sure you have the latest release?  In the log you shared, it says cactbot: 0.7.3.0 and it's up to 0.8.4.  0.8.0 was released to unbreak Cactbot.  Perhaps the installation didn't go as expected.

**Comment by quisquous** [comment]
Yeah, that definitely looks like the problem.  Your cactbot version is not up to date.  You should grab https://github.com/quisquous/cactbot/releases/download/v0.8.4/cactbot-0.8.4.zip and reinstall it.

**Comment by nishalp** [comment]
Thx guys.  I didn't realize the DLL was loaded from a different folder under add-ons.  Wasn't updating that.  All fixed now.  Appreciate the help.

**Comment by quisquous** [comment]
Glad you got it sorted! :+1:
