### ISSUE TITLE
Unable to get tts working

### ISSUE THREAD

**Issue by red-perilla** [quisquous/cactbot#247]
Hello, 

I have changed the settings in in raidboss.js

let Options = {
  TimelineEnabled: true,
  AlertsEnabled: true,
  TextAlertsEnabled: true,
  SoundAlertsEnabled: true,
  SpokenAlertsEnabled: true,
...

And also in user/raidboss-example.js

Options.SpokenAlertsEnabled = true;

I've also reloaded the plugin, restarted ACT, still no go.

Is there an option I'm missing?

Thanks for the great work!

-Ana

**Comment by red-perilla** [comment]
It's working now. Please ignore.

**Comment by quisquous** [comment]
Glad you got it working! Sorry for any confusion.
