### ISSUE TITLE
Raidemulator Issues with  data.party.jobName()

### ISSUE THREAD

**Issue by Datachange** [quisquous/cactbot#2477]
## Description
In the "attached" E12S Bug Demo 1 trigger, in the preRun, two data elements are set, one which stores off job names of the target using data.party.jobName() and the other the target names, themselves.

The bug demo trigger outputs the resulting objects in alert text and info text.
The text in the alerts and timeline pane indicates that the jobName() function always returned null. However, in the JSON dump pane, the jobName() function worked just fine; data is populated.

For some reason, the JSON dump doesn't match the alerts. Why is this? Could the split have a part in this?

## Additional information
The log file, DB export, user JS file, and screenshot are too large for uploading, here.
So here is a drive link:
https://drive.google.com/file/d/1J1_HOAfYn0ANryX7hsW7JX73WgmvY7S1/view?usp=sharing

In the raid emulator, in the **split** file (done by the ff uploader) has a few E12S fights within it.
The particular fight I used for demoing this issue was:
Start: 2021-02-13 21:41:55
Duration: 07:23
Pull At: 00:57
Name: Oracle Of Darkness

**Comment by valarnin** [comment]
I'm looking into this now. It did lead me to find a bug with raidemulator where the first line of the log file is ignored, which isn't an issue when loading a normal log but is an issue when loading a trimmed log.

**Comment by valarnin** [comment]
@quisquous I have the fix for this issue as well as the first line being skipped. Do you want me to roll this into #2235? Or wait for that to merge and make a new PR after?

@Datachange here's a .patch for the issue you can use temporarily until I can get a PR open for it.

```patch
diff --git a/ui/raidboss/emulator/data/AnalyzedEncounter.js b/ui/raidboss/emulator/data/AnalyzedEncounter.js
index 32a1d8f6..8c355120 100644
--- a/ui/raidboss/emulator/data/AnalyzedEncounter.js
+++ b/ui/raidboss/emulator/data/AnalyzedEncounter.js
@@ -20,6 +20,15 @@ export default class AnalyzedEncounter extends EventBus {

   selectPerspective(ID) {
     const partyMember = this.encounter.combatantTracker.combatants[ID];
+    this.popupText.partyTracker.onPartyChanged({
+      party: this.encounter.combatantTracker.partyMembers.map((ID) => {
+        return {
+          name: this.encounter.combatantTracker.combatants[ID].name,
+          job: Util.jobToJobEnum(this.encounter.combatantTracker.combatants[ID].job),
+          inParty: true,
+        };
+      }),
+    });
     this.popupText.OnPlayerChange({
       detail: {
         name: partyMember.name,
@@ -27,6 +36,10 @@ export default class AnalyzedEncounter extends EventBus {
         currentHP: partyMember.getState(this.encounter.logLines[0].timestamp).HP,
       },
     });
+    this.popupText.OnChangeZone({
+      zoneName: this.encounter.encounterZoneName,
+      zoneID: parseInt(this.encounter.encounterZoneId, 16),
+    });
   }

   async analyze(popupText) {
```

**Comment by quisquous** [comment]
A new PR for different issues, please! It's hard when a PR keeps getting stuff tacked onto it that I then have more questions about it, etc, and it kind of holds everything up.  Better to have smaller PRs that land quicker, imo.
