### ISSUE TITLE
TypeScript testing issues

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#2479]
# 1) npm run test doesn't work (for me) locally

  ```
$ npm run test

> cactbot@ test C:\Users\enne\cactbot
> tsc types/*.d.ts --noEmit && python test/run_tests.py

error TS6053: File 'types/*.d.ts' not found.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! cactbot@ test: `tsc types/*.d.ts --noEmit && python test/run_tests.py`
npm ERR! Exit status 2
  ```

  Running the command on its own has no output and runs just fine:
  ```
$ node_modules/.bin/tsc types/*.d.ts
  ```

# 2) npm run test is SUPER slow 

At tip of tree, if I work around the above issue for missing files:
  ```
$ time npm run test

(Use `node --trace-warnings ...` to show where the warning was created)
(node:7392) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
...
[repeated a million times]

real    14m45.178s
user    0m0.030s
sys     0m0.015s
  ```

  With `NODE_COMMAND = ["node"]`:
  ```
$ time npm run test

real    0m39.858s
user    0m0.030s
sys     0m0.045s
  ```

I'm going to revert the ts test changes until we have anything that depends on it and this is solved.
cc @MaikoTan @Trim21

**Comment by quisquous** [comment]
https://github.com/quisquous/cactbot/runs/1896024627 running in 16 minutes suggests that it is also very slow on the bots.

**Comment by MaikoTan** [comment]
Yep, I think the better way is, migrate our unit test to jest first, and then directly call `ts-node` to run the tests.

**Comment by Trim21** [comment]
which OS are you using and what shell are you using? Normally there's no need to add `node_modules/.bin/` in npm scripts

**Comment by Trim21** [comment]
node take some time to load `ts-node`, but `ts-node` will be loaded in each timelint and is loaded too many times.

I'll rewrite current test, scan timeline files in node process and reduce the times `ts-node` was loaded.

**Comment by quisquous** [comment]
> which OS are you using and what shell are you using? Normally there's no need to add `node_modules/.bin/` in npm scripts（I think this is handled by npm, npm will add this dir to path when executing the scripts). I'm using Windows and bash as npm scripts shell, it works fine in both my computer and CI.

Yeah, I'm not sure why it's listed there in the npm script.  Probably because I copied and pasted from what I was running on the command line.  I think it could be removed.

> If you're using Windows and cmd/powershell
> , I think we should set OS of our ci to Windows to make sure that test environment is simally to developing environment.

I am on Windows + git bash (aka mingw64).

**Comment by Trim21** [comment]
I guess your npm scripts is not executed by bash. There is a config of npm setting shell to bash.

**Comment by quisquous** [comment]
At any rate, I have converted everything to Mocha, so hopefully that will be a better way to go about using typescript in tests.  I'll close this, as I don't think it applies anymore.
