### ISSUE TITLE
What do I miss when using user config dir?

### ISSUE THREAD

**Issue by Trim21** [quisquous/cactbot#2494]
I'm trying to split my `user/raidboss.js` in to multiple files, but none of them in `raidboss` dir are loaded.

```txt
user
├── raidboss
|  └── TEA
|     └── the_epic_of_alexander.js
└── raidboss.js
```

I check the log and find that only `user/raidboss.js` is loaded. `user/raidboss/TEA/the_epic_of_alexander.js` is not loaded at all.

Then I modified the `dist/config.bundle.js` and find that details in event `cactbotLoadUser` only contains `raidboss.js`.
In `loadUser(e)`, `localFiles` is `{'user/raidboss.js': something else}`.
It looks like it should conrains other user js files. What did I miss?

**Comment by quisquous** [comment]
Are you using an old plugin that doesn't support the user directory? Is your user directory set correctly in the config to the directory you think it is?

**Comment by Trim21** [comment]
> Are you using an old plugin that doesn't support the user directory? Is your user directory set correctly in the config to the directory you think it is?

I'm using the least version in github releases, and console.log in raidboss.hs works as expected.

**Comment by Trim21** [comment]
Sorry, I just find I make a stupid mistake. The distribution of my ACT contains a really old dll. I remove it and install the latest version. But I didn't restart ACT so in fact I'm using the old plugin.

**Comment by quisquous** [comment]
Aha! Glad you got it figured out.  :)
