### ISSUE TITLE
Proposal: limit function definition style

### ISSUE THREAD

**Issue by Trim21** [quisquous/cactbot#2497]
There are too many function definition style in code. add eslint rule [func-style](https://eslint.org/docs/rules/func-style) to allow only some of them for code readability.

**Comment by quisquous** [comment]
I think if we wanted to add a rule, I'd prefer `"expression", { "allowArrowFunctions": true }`.  Would you want something different?

**Comment by Trim21** [comment]
I prefer `"declaration"` only. And disallow arrow function in top-level function definition.

**Comment by MaikoTan** [comment]
No, the arrow function was used everywhere when we need a `this pointer` pass-through function. I think it should be enabled definitely.

**Comment by Trim21** [comment]
so vote for `"declaration", { "allowArrowFunctions": true }` 🤔

**Comment by quisquous** [comment]
My reasoning for "expression" is the same as given here: https://airbnb.io/javascript/#functions--declarations.  I think hoisting hurts readability, and it's inconsistent to have top-level functions be different from inner functions (due to no-inner-declarations).

**Comment by Trim21** [comment]
There is another eslint rule `no-use-before-define` can prevent this.
