### ISSUE TITLE
Bug: user trigger behavior problem

### ISSUE THREAD

**Issue by Trim21** [quisquous/cactbot#2503]
## Description

User trigger can't override built-in trigger. If I add a trigger with same id, both trigger will be loaded, and they share same config.

## Additional information

I add a trigger with `disabled: true` to disable built-in trigger<del>(Or I just copy a built-in trigger for debugging). But I didn't see a log `Overriding *** from *** with ***` like I used to do.</del>

Then in config.html, there are 2 trigger with same ID, one in user local file, one in built-in file.

When I disable one of them in UI, both are disabled. When I enable one of them, both of them are enabled. And they will both run in the real game when they could be triggered.

version:
cactbot dll: 0.21.20.0
ngld dll: 0.16.5
cactbot frontend: current main (169e11e) and latest release 0.21.20(hotfix for bozja)

**Comment by quisquous** [comment]
Looks like `disabled` is behaving weirdly.  I don't know that something has changed here.  If you just create a trigger that has nothing but the id in it, it should override properly (as a workaround for now).

**Comment by Trim21** [comment]
not only happened with `disabled` property. It happened when I simply copy a built-in trigger to user config file.

**Comment by quisquous** [comment]
Ok, then you'll need to provide some examples, because overriding triggers works for me locally, and I'm not sure what's going on differently for you.

The UI will show both the built-in trigger and the overridden one (or at least the last one per file, if you happen to have multiple in the same file), so that's to be expected.

**Comment by Trim21** [comment]
There should be a console.log `Overriding *** from *** with ***` if built-in trigger is overrided by user trigger with same ID, am I right? Or only `local user file: *****`

**Comment by quisquous** [comment]
Yes, there should be the `Overriding...` text in the overlayplugin log when the same id is used: https://github.com/quisquous/cactbot/blob/main/ui/raidboss/popup-text.js#L98

Maybe add more debugging? Are the ids not exactly the same for some reason?

**Comment by Trim21** [comment]
I add some debug log and find that `OrderedTriggerList.push()` isn't called infact.

I'm at commit 169e11e4a0

**Comment by quisquous** [comment]
If `push` is not called, then either you are in a zone where there are no triggers or your debugging is somehow faulty, I think?

**Comment by Trim21** [comment]
Sorry for the trouble, I thought that overriding happened when all user files add loaded... 😬
Didn't notice that they are loaded only the `zoneId` match... 😬😬😬 there is no bug in overriding.

**Comment by Trim21** [comment]
This is really strange...

![8~(M@$)X4IXB %RUEU I}RL](https://user-images.githubusercontent.com/13553903/108867916-a72a3100-7630-11eb-9129-da626053cdc0.png)


I used to though that It's my misusing, but now it looks like a bug.

**Comment by Trim21** [comment]
more details:
user config file:
![1](https://user-images.githubusercontent.com/13553903/108871881-91b70600-7634-11eb-821d-b040c72d9771.png)
updated popup-text.js
![2](https://user-images.githubusercontent.com/13553903/108871887-92e83300-7634-11eb-8832-0f0494634daf.png)
result:
![3](https://user-images.githubusercontent.com/13553903/108872026-b9a66980-7634-11eb-8dde-b42cd7e06308.png)

this.idToIndex:
```json
"{"General Provoke":0,"General Frog Legs":1,"General Shirk":2,"General Holmgang":3,"General Hallowed":4,"General Superbolide":5,"General Living":6,"General Walking":7,"General Ready Check":8,"TEA Brute Phase":9,"TEA Inception Phase":10,"TEA Wormhole Phase":11,"TEA Fate Alpha Phase":12,"TEA Fate Beta Phase":13,"TEA Liquid Tank":14,"TEA Hand Tank":15,"TEA Cruise Chaser Tank":16,"TEA Brute Tank":17,"TEA Cascade":18,"TEA Protean Wave":19,"TEA Drainage Tether":20,"TEA Hand of Pain 5":21,"TEA Throttle":22,"TEA Limit Cut Numbers":23,"TEA Limit Cut Knockback":24,"TEA Chakrams Out":25,"TEA Chakrams In":26,"TEA Whirlwind":27,"TEA Spin Crusher":28,"TEA Ice Marker":29,"TEA Hidden Minefield":30,"TEA Enumeration YOU":31,"TEA Enumeration Everyone":32,"TEA Limit Cut Shield":33,"TEA Compressed Water Initial":34,"TEA Compressed Water Explode":35,"TEA Compressed Lightning Initial":36,"TEA Compressed Lightning Explode":37,"TEA Pass Nisi 1":38,"TEA Pass Nisi 2":39,"TEA Pass Nisi 3":40,"TEA Decree Nisi Gain":41,"TEA Decree Nisi Lose":42,"TEA Final Judgment Nisi Gain":43,"TEA Final Judgment Nisi Verdict":44,"TEA Gavel":45,"TEA Double Rocket Punch":46,"TEA Brute Ray":47,"TEA Buff Collection":48,"TEA Temporal Stasis No Buff":49,"TEA Restraining Order":50,"TEA House Arrest":51,"TEA Shared Sentence":52,"TEA Shared Sentence Inception":53,"TEA Aggravated Assault":54,"TEA Chastening Heat":55,"TEA Judgment Crystal":56,"TEA Judgment Crystal Placement":57,"TEA Terashatter Flarethrower":58,"TEA Inception Vuln Collection":59,"TEA Inception Alpha Sword":60,"TEA Wormhole":61,"TEA Cactbot Wormhole Strat":62,"TEA Cactbot Wormhole 4 Super Jump":63,"TEA Incinerating Heat":64,"TEA Mega Holy":65,"TEA Summon Alexander":66,"TEA Divine Judgment":67,"TEA Perfect Optical Sight Spread":68,"TEA Perfect Optical Sight Stack":69,"TEA Ordained Motion":70,"TEA Ordained Stillness":71,"TEA Contact Prohibition":72,"TEA Contact Regulation":73,"TEA Escape Prohibition":74,"TEA Escape Detection":75,"TEA Fate Tether Bois":76,"TEA Alpha Instructions":77,"TEA Alpha Instructions Callout":78,"TEA Alpha Ordained Motion 1":79,"TEA Alpha Ordained Stillness 1":80,"TEA Alpha Ordained Motion 2":81,"TEA Alpha Ordained Stillness 2":82,"TEA Alpha Safe Spot":83,"TEA Alpha Resolve First Motion":84,"TEA Alpha Resolve Second Motion":85,"TEA Beta Instructions":86,"TEA Beta Instructions Callout":87,"TEA Beta Radiant":88,"TEA Beta Optical Spread":89,"TEA Beta Optical Stack":90,"TEA Beta Optical Final":91,"TEA Beta Radiant Final":92,"TEA Ordained Punishment":93,"TEA Trine Get Middle":94,"TEA Trine Initial":95,"TEA Trine Second":96,"TEA Irresistible Grace":97}"
```

**Comment by quisquous** [comment]
Oh!  Good catch.  I guess I need to add all triggers to the ordered list, and then separate by netregex/regex at the end.
