### ISSUE TITLE
add a `reload` button in config.html when develop mode is enabled.

### ISSUE THREAD

**Issue by Trim21** [quisquous/cactbot#2509]
## Summary

never hide this part when development options are enabled, or add a reload button below the checkbox.

![image](https://user-images.githubusercontent.com/13553903/109020121-a3f87900-76f4-11eb-8aa6-a15ea2c97ad0.png)

**Comment by quisquous** [comment]
I think this is already pretty easy to do via right click -> reload.  Additionally, webpack will automatically reload when using the dev server if you've changed any files.
