### ISSUE TITLE
make_timeline.py UnicodeEncodeError

### ISSUE THREAD

**Issue by Legends0** [quisquous/cactbot#2510]
## Description

I am trying to run make_timeline.py on report Dp3qMH4nXzWV2YyL, fight 10. (https://www.fflogs.com/reports/Dp3qMH4nXzWV2YyL#fight=10). Receiving the following error message:

```
Traceback (most recent call last):
  File "C:\Users\nac10\Downloads\cactbot\util\make_timeline.py", line 499, in <module>
    print("\n".join(main(args)))
  File "C:\Users\nac10\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 737-746: character maps to <undefined>
```

**Comment by quisquous** [comment]
#2326 was one attempt to fix this, but I'm not sure that was the right approach.  It might be something you could apply and see if it fixed this issue.

(What are you making a timeline of, out of curiosity?)

**Comment by Legends0** [comment]
For the savage content I put together timelines and triggers with just the savage IDs replacing from the normal encounter. I can make a PR if you want or do you have a PR that you plan to add?

**Comment by Legends0** [comment]
This log I was going to use to see where/how it loops.

**Comment by quisquous** [comment]
I don't think they are the same as just replacing the ids.  I was planning to add a PR this week to do some basic timelines.

**Comment by Legends0** [comment]
Converting the print to utf-8 does get me some output I can run through a find/replace for \n with newline.

This line stood out:
32.6 "\xe9\x87\x91\xef\xbc\x9a\xe5\xba\xa7\xe6\xa8\x99\xe7\xa7\xbb\xe5\x8b\x95\xef\xbc\x9a\xe7\x84\xa1\xe8\xa9\xa0\xe5\x94\xb1" sync /:Stygimoloch Lord:57DA:/

**Comment by Legends0** [comment]
It appears its an untranslated spell:
Stygimoloch Lord casts 金：座標移動：無詠唱

**Comment by Legends0** [comment]
It will also happen during the Slimes and Golems fight:
"\xe3\x83\x87\xe3\x82\xb9\xe3\x82\xb5\xe3\x82\xa4\xe3\x82\xba" sync /:Grim Reaper:5747:/
Grim Reaper casts デスサイズ

Ref: https://www.fflogs.com/reports/qBDc1djvGhK6y7Af#fight=2

The Grim Reaper situation is considered a soft enrage for these encounters.

**Comment by quisquous** [comment]
This should be fixed now.
