### ISSUE TITLE
DRS Trigger for Trinity Seeker Incorrect

### ISSUE THREAD

**Issue by jekyll87** [quisquous/cactbot#2521]
The trigger currently listed for Trinity Seeker as "DelubrumSav Seeker Baleful Onslaught Stillness" is not actually a stillness check. The MT can continue to push actions and attack throughout. What the attack actually does is do a knock-back IF other tanks come to the front to try to share the TB. More accurately, this is a solo tank check cleave that does 0 damage and no knock-back if the MT is standing by themselves. 

I realize people can change the text from "Stillness Tank Cleave" to w/e they want but I feel something like "Solo Tank Check" is more accurate.

**Comment by quisquous** [comment]
Ah, thanks! I feel like I saw streams and guides that said it was stillness.  I see that lyra's guide says this, and so maybe I misread it before or maybe it's been updated.  I'll update it to "Solo Tank Cleave".

**Comment by jekyll87** [comment]
> 
> 
> Ah, thanks! I feel like I saw streams and guides that said it was stillness. I see that lyra's guide says this, and so maybe I misread it before or maybe it's been updated. I'll update it to "Solo Tank Cleave".

No problem. I think it's a common misconception from the first few weeks but it definitely only checks that the tank is alone then does nothing.

**Comment by Legends0** [comment]
Oops, didn't realize @jekyll87 wrote this issue when he contacted me about it. I submitted a PR for it.

**Comment by quisquous** [comment]
Should be fixed!
