### ISSUE TITLE
New Online Raid Emulator Issues

### ISSUE THREAD

**Issue by Datachange** [quisquous/cactbot#2529]
## Description
When going to the new raid emulator website:
https://quisquous.github.io/cactbot/ui/raidboss/raidemulator.html

I have two (three?) problems:
1. From the console: Failed to load resource: the server responded with a status of 404 ()   /favicon.ico:
2. This may be related, but the Load Network Log button doesn't do anything.
3. This may also be related, but drag and dropping a log file just opens a new tab in Chrome.

Thank you very much for your help!

**Comment by MaikoTan** [comment]
- RE: favicon missing

This is a known issue, it just complains that the webpage has not declared an web icon (which would display in the left of the webpage title), this issue would not affect anything, so don't mind.

- RE: button not working

  - Are you using OverlayPlugin from ngld?
  - Did you enable the WebSocket Server feature of the OverlayPlugin?
  - Did you use Chrome to open the emulator?
  - Did you add `?OVERLAY_WS=ws://127.0.0.1:10501/ws` query to your url when you open it in Chrome?

**Comment by Datachange** [comment]
I've used the emulator plenty of times before, no problem. It's only with this new update am I having issues.
* I would presume so as Cactbot ahs been working, and from the fact that it has worked before
* I don't know what this is, but I did Start the WSServer.
* Yes
* This was it.
