### ISSUE TITLE
e10s limit cut dots only say ??? now

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#2530]
Just reporting.  No further information (sorry).

**Comment by JLGarber** [comment]
Since this is here, I'll confirm. This was the case both with and without head markers. More investigation tomorrow...

**Comment by quisquous** [comment]
> Since this is here, I'll confirm. This was the case both with and without head markers. More investigation tomorrow...

If it can't find your clone, it will always give you an early ??? so you know to look.  So, for some reason it can't find any clones (or it finds multiple of the same job, even when it shouldn't).  Probably adding some console logging to what gets returned from getCombatants might help here.  Maybe the combatant names changed or something else went awry?

**Comment by miaonima** [comment]
Just curious: is it intended behavior to call out ??? when the player has the stack marker? I think I saw that happen before. Will record the fight later.
