### ISSUE TITLE
raidboss only working for half of suzaku?

### ISSUE THREAD

**Issue by mystiael** [quisquous/cactbot#254]
I'm not sure if I'm doing something wrong but when I'm using raidboss it'll show the timeline and the "tankbuster on <name>" trigger for the first half of Suzaku, up until she disappears for the phase change - after the phase change the timeline is gone and the name specific triggers won't show up

it suddenly stopped working a few days ago. I didn't change anything about the files or anything

any chance you'd know something about it?

**Comment by quisquous** [comment]
Did you figure this out?

**Comment by mystiael** [comment]
Kind of! I had to do a fresh install of ACT (for reasons other than cactbot) and it worked after, it was probably just ACT being funny! Thank you!
