### ISSUE TITLE
lint-staged tsc doesn't respect tsconfig.json

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#2543]
Repro steps:
1) make a change to resources/party.ts
2) git commit -a -m errors

```
× tsc --noEmit:
resources/party.ts(55,7): error TS1056: Accessors are only available when targeting E
CMAScript 5 and higher.
resources/party.ts(59,7): error TS1056: Accessors are only available when targeting E
CMAScript 5 and higher.
resources/party.ts(64,7): error TS1056: Accessors are only available when targeting E
CMAScript 5 and higher.
resources/party.ts(69,7): error TS1056: Accessors are only available when targeting E
CMAScript 5 and higher.
resources/party.ts(74,7): error TS1056: Accessors are only available when targeting E
CMAScript 5 and higher.
resources/party.ts(79,7): error TS1056: Accessors are only available when targeting E
CMAScript 5 and higher.
```

This is because in package.json:
```
  "lint-staged": {
    "*.ts": "tsc --noEmit",
  },
```

`tsc` when provided files does not respect the tsconfig.json file.  If you provide one with `--project` you cannot provide input files.  There is no way to provide a tsconfig.json file here.  See: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

We have a lot of options set, and I don't want to duplicate those onto the command line.

Some possible workarounds in these issues (broken to avoid needless linking, sorry):
1) https://github.com/microsoft/TypeScript/issues/ 27379
2) https://github.com/okonet/lint-staged/issues/ 468

**Comment by quisquous** [comment]
cc @Trim21 @MaikoTan

**Comment by Trim21** [comment]
As we mentioned at https://github.com/quisquous/cactbot/pull/2532/files/b97400d51d6f4802dfde7b28945970e864ae49fb#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by quisquous** [comment]
Ah sorry, I missed that hiding in the resolved comment.

I am not sure about running tsc on everything on every commit.  lint-staged is already a little bit slow and I don't want it to get worse.  On my computer, editing a comment in one trigger file and then doing this:

```
$ time git commit -a -m temp

[...output elided...]

real    0m9.665s
user    0m0.000s
sys     0m0.015s
```

```
$ time node_modules/.bin/tsc --noEmit

real    0m5.284s
user    0m0.030s
sys     0m0.105s
```

I don't want to add 5 seconds to an already slow 10 second process, if possible.  I think `ts-node` will already catch a number of errors in trigger files and common resource files that triggers include.

I think there are some proposed options in what I linked to (e.g. https://github.com/okonet/lint-staged/issues/ 468#issuecomment-541384443) that might be able to work around this and only run tsc on particular files.  It would be worth trying that.

**Comment by Trim21** [comment]
I think we could add it in ci instead of a pre-commit hook

**Comment by quisquous** [comment]
> I think we could add it in ci instead of a pre-commit hook, It may be slower with the more TS files.

I think it should definitely be in ci, regardless.  I think there may also be some way to have it be in lint-staged, if we can figure out how to only make it run on one file.

**Comment by Trim21** [comment]
> > I think we could add it in ci instead of a pre-commit hook, It may be slower with the more TS files.
> 
> I think it should definitely be in ci, regardless. I think there may also be some way to have it be in lint-staged, if we can figure out how to only make it run on one file.

maybe `eslint-plugin-tsc`
