### ISSUE TITLE
Add coverage-report to ci

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#2544]
90% of the time the gh-pages step fails is because the coverage report fails to build.

Here's the last one (10000% my fault, sorry Maiko): https://github.com/quisquous/cactbot/runs/2047349016?check_suite_focus=true

...but it would be nice to check that this will succeed on other patches.  I think it may just need to be run on all .js/.ts file changes, unfortunately.

**Comment by MaikoTan** [comment]
I am not quite sure about `ts-node/esm`, it looks like the problem that @Trim21 had met.
To add a `transpile-only` flag would save this, but may be not intended.

**Comment by Trim21** [comment]
> I am not quite sure about `ts-node/esm`, it looks like the problem that @Trim21 had met.
> To add a `transpile-only` flag would solve this, but may be not intended.

What happened here... it looks that most tests run successfully https://github.com/quisquous/cactbot/actions/workflows/update-gh-pages.yml. What do I miss?

**Comment by MaikoTan** [comment]
Oh sorry I misunderstand your meaning!
Yes, I think the `tsc` checking part is needed.

**Comment by quisquous** [comment]
This is fixed now in the new post-process step.
