### ISSUE TITLE
raidemulator should display an error when loaded over file://

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#2564]
This no longer works because of the web workers, and so it it'd be nice to display some error for users rather than silently not working.

**Comment by valarnin** [comment]
Would it make more sense to embed the web worker so it doesn't have to load over file:/// URI?

**Comment by quisquous** [comment]
Sure.  If this is possible to fix so that it works over `file://`, that's even better!

**Comment by valarnin** [comment]
It's not possible to fix over `file://` but it's possible to embed the worker as source and load it via blob URL instead. I'll see what I can code up when I get a minute.
