### ISSUE TITLE
Raidboss - Archive all inaccurate stack/spread

### ISSUE THREAD

**Issue by HailZaros** [quisquous/cactbot#259]
On final omega, when he casts "Archive All" there is a delta attack, where you either have to stack or spread.
The trigger for it will always show "stack", even if you don't have any debuff.
I'd assume this comes due to this bit of code, which is meant for Omega M/F:
 ```
...
    {
      id: 'O12S Stack Marker',
      regex: /1B:........:\y{Name}:....:....:003E:0000:0000:0000:/,
      suppressSeconds: 1,
      infoText: {
        en: 'Stack',
      },
    },
...
```

I think adding a check for target might help fix this. Not sure how to correctly add that, though.

**Comment by quisquous** [comment]
Thanks for reminding me that I needed to fix this.  Sorry for the confusion!
