### ISSUE TITLE
eureka: Korean server CE opcode needed

### ISSUE THREAD

**Issue by Jaehyuk-Lee** [quisquous/cactbot#2596]
## Description

Since CE opcode is not updated on cactbot for Korean server, CE alerts are not working.
I don't know how to find it, is it possible with FFXIV Parsing Plugin with Debug mode(Log all network packets)?

**Comment by MaikoTan** [comment]
https://github.com/karashiiro/FFXIVOpcodeWizard
With this you can find opcodes easily.

**Comment by Akurosia** [comment]
I am not quite sure if the OpcodeWizard can detect `CEDirector` and `AC143` Opcodes.

you could try the wizard and if it does not work, you can try https://github.com/SapphireServer/ffxivmon

**Comment by Jaehyuk-Lee** [comment]
@MaikoTan I couldn't find about CE opcodes. It was interesting and easy though.

@Akurosia I tried FFXIVmon before, it returns an error and couldn't find what's wrong.

![K-002](https://user-images.githubusercontent.com/4695371/111614107-91202280-8822-11eb-9aec-3860b34d4bfc.png)
![K-003](https://user-images.githubusercontent.com/4695371/111614110-91b8b900-8822-11eb-90a5-e1c1713a3f86.png)

Does this program needs global server's path? I guessed it reads client data for each different version. Korean server has different version so I entered Korean path.

**Comment by Jaehyuk-Lee** [comment]
oh the program returns the same error with the global server path.

**Comment by Jaehyuk-Lee** [comment]
```
252|2021-03-18T20:45:54.6850000+09:00|00000030|1008A40B|1008A40B|00000003|03470014|011F0000|60533D72|00000000|60533DAE|00000000|00010009|00000000||09275d61d66cdd3736207322a3f43f6a
252|2021-03-18T20:45:54.6850000+09:00|00000030|1008A40B|1008A40B|00000003|03470014|011F0000|60533D72|00000000|60533DAE|00000000|0001000A|00000000||dc1a33321cc8f8fa4186dd97cb509375
```
These two logs seems CE spawn logs.

**Comment by Jaehyuk-Lee** [comment]
```
252|2021-03-18T20:45:54.6850000+09:00|00000030|1008A40B|1008A40B|00000003|03470014|011F0000|60533D72|00000000|60533DAE|00000000|00010009|00000000||09275d61d66cdd3736207322a3f43f6a
252|2021-03-18T20:45:54.6850000+09:00|00000030|1008A40B|1008A40B|00000003|03470014|011F0000|60533D72|00000000|60533DAE|00000000|0001000A|00000000||dc1a33321cc8f8fa4186dd97cb509375
```
By the way, `0347` part was opcode part. Maybe I could find opcode better next time with this information.
