### ISSUE TITLE
Using the timeline as a trigger?

### ISSUE THREAD

**Issue by kartana** [quisquous/cactbot#260]
Not an issue, I just want to make a custom trigger file for certain raids. Is there a way to access a certain point in the timeline via a trigger?
For a random example: in o9s at the 
1160.7 "Cyclone" sync /:Chaos:318F:/ in the timeline file:
Use this specific point in the timeline as a trigger to write "Debuffs" as info text. 
How would I do this if possible?

General question: Is there a more detailed documentation I could use?

**Comment by quisquous** [comment]
I hope you found this, but timelineTriggers in triggers file are a way to do this.

Here's two examples:
https://github.com/quisquous/cactbot/blob/master/ui/raidboss/data/triggers/test.js#L36
https://github.com/quisquous/cactbot/blob/master/ui/raidboss/data/triggers/o9s.js#L26
