### ISSUE TITLE
did the newest update change the 11s plugin?

### ISSUE THREAD

**Issue by magnetic101** [quisquous/cactbot#263]
o11s was working perfectly until i updated to 0.8.6 and now it calls left or right only sometimes , is that an error on my end for updating it wrong or did it change something

**Comment by quisquous** [comment]
Sorry, nothing has changed on that front.  I have seen this happen before, but only when there's a lot of packet loss and events are just being dropped.

Were there any errors in the plugin log?

**Comment by quisquous** [comment]
I'm going to close this.  Let me know if this is still happening or if this was a one time thing.
