### ISSUE TITLE
cactbot not appearing as new overlay option

### ISSUE THREAD

**Issue by cspwnsurface** [quisquous/cactbot#265]
Followed every step I could find, reinstalled multiple times, still nothing.

**Comment by TheTweets** [comment]
To update this as I'm having the same issue on 0.8.6 - CactbotOverlay.dll is present at C:\Program Files (x86)\Advanced Combat Tracker\plugins\OverlayPlugin\addons, and it is the only file in that folder. 

Overall, from \plugins\OverlayPlugins, the folders available are \addons, \cache, \cactbot, \ja-JP, \ko-KR, \locales, \resources, and there are a multitude of files in the \OverlayPlugin folder itself, of note being AdvancedCactbot.md. 

The following image is the \plugins\OverlayPlugin folder, for illustration's sake.

![image](https://user-images.githubusercontent.com/8594837/47870786-4f81af00-de02-11e8-93d5-9b6f6c5ed17e.png)

**Comment by TheTweets** [comment]
Hey, I just went through and gave this another shot - the issue appears to be that the zip file for 0.8.6 was not unblocked before transferring the files over the last time I threw it on to check. After installing it properly it appears to work fine (other than potentially the weather issue reported in #272, I was not able to confirm this).

For @cspwnsurface, you can unblock the zip file by finding it in your Downloads folder (or wherever you downloaded it to), right-clicking and selecting Properties, then checking "Unblock" and then "Apply". 
![image](https://user-images.githubusercontent.com/8594837/48276907-15875d00-e441-11e8-8d79-e5b98027e6bd.png)

If Cactbot is still installed you can solve this by manually unblocking each file, but for the sake of ease and expedience I would recommend simply unblocking the .zip and copying everything over the top of the curren installation.

**Comment by quisquous** [comment]
@cspwnsurface Did you get this working?

**Comment by cspwnsurface** [comment]
So I copied the entire ACT file directory from a friend's who was working.
That fixed it. Don't know what specifically it was that fixed it.

**Comment by quisquous** [comment]
Glad you got it sorted!
