### ISSUE TITLE
Fisher : french translation - fishing spot misspelled

### ISSUE THREAD

**Issue by NewbieVenerable** [quisquous/cactbot#2651]
Nothing much to say : with the french version of the game, i found a misspelled spot in Azys Lla.

"Arbre à pappus" should be spelled "L'arbre à pappus". Works perfectly when changed in local files.

Thanks in advance ! :)

**Comment by quisquous** [comment]
Thanks for filing this issue! (@VanSlanzar @mooondark FYI)

I think this is not a data file issue, but rather a fishing regex issue.  The fish is called `Arbre à pappus`.

Maybe this line needs to be changed? https://github.com/quisquous/cactbot/blob/main/ui/fisher/fisher.js#L99

```diff
-'catch': /00:0843:Vous avez pêché (?:un |une )?.+?\s?([\w\s\-\'\(\)\u00b0\u00c0-\u017f]{3,})\ue03c?.+de \d/,
+'catch': /00:0843:Vous avez pêché (?:un |une |L')?.+?\s?([\w\s\-\'\(\)\u00b0\u00c0-\u017f]{3,})\ue03c?.+de \d/,
```

Do you have a log line for this? If you find the line in your ACT log that has `L'arbre à pappus` in it and paste it here, that would be helpful.

That said, I'm not sure what this regex is doing.  There's a surprising amount of `.+` and `.+?` going on.

**Comment by NewbieVenerable** [comment]
Hey, thanks for answering !

It's actually not about a fish, but a fishing area. It doesn't have the same name in the fisher plugin files as it has in the game, so the timer won't even start. I should have described the problem a little better. ^^

I went in the fisher.bundle.js file and replaced "Arbre à pappus" with "L'arbre à pappus" and it works perfectly, kind of like a few months ago when i reported the same thing with parentheses and such, so i think just changing it in static-data.js would work ?

`00|2021-03-30T19:22:30.0000000+02:00|08c3||Vous commencez à pêcher. Point de pêche: L'arbre à pappus.|7c4f5f4f7ff6aa19b6b17fe16299efc5`

Is this what you need ?

Thanks again ! ;)

**Comment by quisquous** [comment]
Hmm, that's weird.  There are several fishing holes that have `L'` in their data, but that one doesn't:

```
      '413': 'L\'Enchevêtrement',
      '969': 'L\'Épée',
      '989': 'L\'Ascension',
      '1022': 'L\'Éphore',
      '2029': 'L\'Eurée feste',
      '2173': 'Arbre à pappus',
      '2504': 'L\'Étendue de Rhalgr',
      '3294': 'L\'Origine',
      '3300': 'L\'Aigrette',
```

Do these other fishing locations work properly?

**Comment by VanSlanzar** [comment]
Peux tu m'ajoutez à ton discord @NewbieVenerable. Van#6013
J'aimerais voir quelque chose pour le fishing, et ce serait plus simple en vocal pour moi. Merci.

**Comment by NewbieVenerable** [comment]
> 
> 
> Hmm, that's weird. There are several fishing holes that have `L'` in their data, but that one doesn't:
> 
> ```
>       '413': 'L\'Enchevêtrement',
>       '969': 'L\'Épée',
>       '989': 'L\'Ascension',
>       '1022': 'L\'Éphore',
>       '2029': 'L\'Eurée feste',
>       '2173': 'Arbre à pappus',
>       '2504': 'L\'Étendue de Rhalgr',
>       '3294': 'L\'Origine',
>       '3300': 'L\'Aigrette',
> ```
> 
> Do these other fishing locations work properly?

Didn't have any kind of trouble with any other spot recently, and according to ff14angler, they should all be correct :

![image](https://user-images.githubusercontent.com/71186908/113477911-b7ca9400-9485-11eb-9404-9b729d6abc24.png)

@VanSlanzar je t'ai ajouté sur discord (Lisath), tu me diras ce dont tu as besoin. :)

**Comment by Akurosia** [comment]
The differences are i think the used columns.
The `Name` column does contain the leading `L'` while the column `Name[NoArticle]` does not.

For other entries e.g. `2514.0` both columns contain the same value
