### ISSUE TITLE
Show more detail about built-in common condition.

### ISSUE THREAD

**Issue by Trim21** [quisquous/cactbot#2660]
![image](https://user-images.githubusercontent.com/13553903/113485057-48cd5980-94de-11eb-8133-891e86db2a54.png)
 
 We can add a custome prop for built-in common used condition like `(data) => data.role === 'tank'`

```javascript

const isTank = (data) => data.role === 'tank'

isTank._somePropName = {
  en: 'role is tank'
}

export default {
    id: 'some trigger id',
    condition: isTank,
}

```

Then we got

`condition: role is tank.` in config page.

**Comment by valarnin** [comment]
While this is a nice idea, there's probably a way to handle this in a more automatic fashion, e.g. getting the body for anonymous functions, or the function name for defined functions:

```js
((data) => data.role === 'tank').toString().split(/\s*=>\s*/)[1]
"data.role === 'tank'"
```

```js
function isTank(data) {return data.role === 'tank';}
isTank.toString().match(/function\s+([^\s(]+)/)[1]
"isTank"
```

Maybe it makes sense to have a `_somePropName` property and fall back to some basic logic like above, and revert to `(function)` if the body is too long?

**Comment by MaikoTan** [comment]
well, I think more general is better.
For example, we have a "Condition" class with prolerties such as `name, description, call(the actual function process condition judging)`, and then let trigger accept `condition` with a function or a Condition instance object.

> When `condition` is a Condition instance
The UI would extract `name` and `description` to describe what is this function like, as most triggers use this.

> When `condition` is a function
The UI would still use `(function)` as the name, but when the mouse point to it, a popup tooltip would show info from `func.toSource()`

**Comment by quisquous** [comment]
I am somewhat wary about this doing this in any generalized way, as conditions can have logic in them or are used to select one of several mutually exclusive triggers to fire.  So, blindly overwriting the condition function might cause some hard to track down bugs in some cases.  It's why I've avoided doing this in the past.

One option I've thought about in the past is adding some trigger field like `cannedCondition: 'isTank',` where we have a multiple choice set of conditions and then for such triggers in the ui you could pick from a list.  Unfortunately, there are many cases (e.g. inside of responses) that overwriting or replacing the condition itself won't be enough for users to be able to see them.  I think updating the condition function alone is somewhat of a dead end.

At a higher level, my question is: which triggers do people want to see that they can't see now, and what can we do to enable that.  In my opinion, what people ask about the most is probably tank busters, raidwide aoes, and tank abilities (invulns/provoke/frog legs/etc).  Maybe there are other things, but this is my understanding.  See: #2076.

A couple of ideas:

(1) **Just turn everything on for everybody**.  Long ago, there wasn't a config ui, and so it was hard to turn on or off various triggers.  Now that you can, if you don't care about raidwide warnings, you can turn them off.  I could see an argument where cactbot moves towards defaulting to showing everything to everybody and letting people turn it off themselves.  This also means rewriting triggers to show callouts that we previously would have omitted, and removing some condition functions.

(2) **Add more options, use helper functions more**.  Use more `caresAboutX` style functions to determine if we should show callouts for mechanics that don't apply.  Then add some raidboss options that say "I care about aoes, even if I can't do anything about them" or "please show me tank stuff".  Then we check those options in `caresAboutX` helper functions, and triggers get rewritten to use helper functions as much as possible.

**Comment by valarnin** [comment]
> I worry a little bit that often a lot of the logic on whether or not a trigger gets shown is not in the condition function itself (or the condition function is only half of it), so it seems to me like simpler is better here, especially if there's not a full solution.

That's even more reason to allow a "nice" description of the condition when it's necessary instead of always relying on the source of the condition function.

For instance, if there's a trigger that bails in `promise` or even in `response`/`alertText`/etc, being able to indicate in the `Condition` portion of the config UI that the actual conditions are `player is tank and phase is XYZ` or whatever  would be beneficial.

Canned conditions from the `Conditions` class could return an object as outlined above, and complex conditions could just inline that object creation, with the default being to show source on hover regardless. Backwards compatibility could be maintained by pulling in https://www.npmjs.com/package/callable-instance to allow the object to act as a function, for example.

**Comment by panicstevenson** [comment]
Do we have any insight on how frequently users are missing/requesting this feature? I feel like the config page is already a subset of a subset of users.

Understandably, that's not a great rationale to not provide a new feature/enhancement, but it might be helpful in guiding how complex the solution should be.

**Comment by quisquous** [comment]
I think the "view trigger source" link in the config ui now covers this for any users who want to know more about the details of a trigger.  Showing the condition at all requires clicking the "show developer options" checkbox.  I'm going to close this for now, as I think this is solved enough.
