### ISSUE TITLE
Raidboss not populating.

### ISSUE THREAD

**Issue by ExplodingFajita** [quisquous/cactbot#268]
Just trying to get the boss casts visible for me. The overlay box (displaying ALARM TEXT, ALARM TEXT 2, etc) is visible, but the castbars are not populating it. I've tried uninstalling and reinstalling, followed the installation guide, but no upcoming casts are visible.

When locked, I can't see anything. So here's an image of what appears when I unlock the overlay:
![box](https://user-images.githubusercontent.com/44585652/47672952-a2046680-db89-11e8-9a5d-ba59cd655d6b.png)

I'd be happy to upload more images if necessary to get this fixed. Just let me know what you'd like to see in the screenshot.

**Comment by tant4lus** [comment]
Lock the overlay (yes, the "alarm text" will disappear), teleport to Summerford and do like a `/countdown 5` and you should see timeline text appear if everything is setup correctly.

**Comment by tant4lus** [comment]
Generally this is what I check when I help friends out:

- Make sure parsing damage is working and recognizing what zone your character is in
- You allowed ACT through the firewall
- When you download the zip file release, make sure it is unblocked (in properties) before unzipping it and putting it inside the ACT folder
- Check that there are no errors in loading the plugins when ACT is starting up

**Comment by ExplodingFajita** [comment]
> Generally this is what I check when I help friends out:
> 
> * Make sure parsing damage is working and recognizing what zone your character is in
> * You allowed ACT through the firewall
> * When you download the zip file release, make sure it is unblocked (in properties) before unzipping it and putting it inside the ACT folder
> * Check that there are no errors in loading the plugins when ACT is starting up

Hmm, I don't think I unblocked prior to unzip. I'll give that a shot.

**Comment by ExplodingFajita** [comment]
Still nothing. I'm stumped.

**Comment by ExplodingFajita** [comment]
I may have an error, but I have no idea what it means:
![box](https://user-images.githubusercontent.com/44585652/47676144-2a870500-db92-11e8-93e5-685d14476a87.png)

**Comment by quisquous** [comment]
https://github.com/quisquous/cactbot#potential-errors-and-workarounds should help for that error

**Comment by ExplodingFajita** [comment]
> https://github.com/quisquous/cactbot#potential-errors-and-workarounds should help for that error

Ahh, that fixed it. I'll give it a try. Thanks for replying! Much appreciated!
