### ISSUE TITLE
O10 double timelines?

### ISSUE THREAD

**Issue by Weisshuf** [quisquous/cactbot#269]
I did O10 yesterday and there was only one timeline, but now i got two of every skill, and since that, its also using the sound twice and thats kinda hurting my ears. 

Edit: Alright, I got twice the timelines for everything, even for the test

**Comment by DrLippe** [comment]
Any chance on you just having the raidboss.html assigned twice in your plugin?

**Comment by quisquous** [comment]
Agreed with @DrLippe that two raidboss overlays is the most likely cause here.  Did that end up being the case?

**Comment by quisquous** [comment]
Is this still happening? Were you able to figure out what was going on?

**Comment by Akurosia** [comment]
i also have double trigger in severall fights (were i have no timelines like o4s)

**Comment by quisquous** [comment]
o4s has its own problems.  There's an ACT bug that skill ids are wrong.

Which fights do you have double triggers on? Are there ones other than o4s?

**Comment by Akurosia** [comment]
it also rarely happend during o9s and o10s
and i always make sure to only have either raidboss or raidboss-emulator activ

**Comment by DrLippe** [comment]
can you provide a screenshot of said bug?

**Comment by quisquous** [comment]
I'm going to close this for now.  If this is still happening, please leave another comment.
