### ISSUE TITLE
A simple way to add several timeline record avoiding editing full timeline file.

### ISSUE THREAD

**Issue by Trim21** [quisquous/cactbot#2714]
Add a prop `extraTimeline: string[]` in user trigger set and merge it into original timeline records

**Comment by quisquous** [comment]
I think this already exists as `timeline`: https://github.com/quisquous/cactbot/blob/main/ui/raidboss/data/00-misc/test.js#L7-L37

Maybe it needs better documentation?

**Comment by Akurosia** [comment]
Here is an example how its used in a user file
```
Options.Triggers.push(
    // Advanced ztimelines for E4S to use addle in YM group
    {
      zoneId: ZoneId.AlexanderTheBurdenOfTheSonSavage,
      timeline: `
        1064.9 Line 1
        1099.1 Line 2
        1179.7 Line 3
      `,
    },
);
```

**Comment by MaikoTan** [comment]
I think my last PR #2535 had explained already how it is like?

**Comment by quisquous** [comment]
Oh you're right! Sorry for forgetting that.

**Comment by Trim21** [comment]
Sorry, I misunderstand how this works.
