### ISSUE TITLE
Weather calculation issue (Eureka)

### ISSUE THREAD

**Issue by Cerily** [quisquous/cactbot#272]
Weather calculations aren't working correctly for me in Pagos nor Anemos.  For example, zoning into Anemos with rain as current weather, cactbot's eureka ui is displaying sun for the next 26 minutes with gales in 64 minutes.  Using Garlandtools skywatcher, the weather is showers for the next 15 minutes and double gales after.  This weather issue existed at least a few days before the latest patch from what I remember.

**Comment by quisquous** [comment]
Thanks, I'll take a look.  The weather had been working just fine for me in pagos before the patch.  I'll double check if they modified the weather tables.

**Comment by Cerily** [comment]
Thank you!

**Comment by AEBus** [comment]
Also in Pagos
![](https://i.imgur.com/3PdFpKS.png)
