### ISSUE TITLE
UCOB Nael Quotes aren't working

### ISSUE THREAD

**Issue by cmgau** [quisquous/cactbot#2727]
My static just began UCoB, we reached Nael. All the callouts are fine, the only exception so far is the Nael quotes not being called out. Log can be found [here](https://drive.google.com/file/d/1CkELOqXC1ruiHjn0Kwhr9ERP6H1V1MxQ/view?usp=sharing), apologies for the file size.

**Comment by Akurosia** [comment]
i had a quick glance over the file (searched for all Nael quotes) and could not find any quote.
Only messsages i found had code `000e` (normal chat?) but now message with code `0044` from Nael itself.

Message with code 0044 are in the log itself (e.g. some earlier runs have `00|2021-04-15T00:49:01.0000000+10:00|0044|Familiar Male Voice|I won't let you harm my sister!|454ac4234f314a3a15a8402f3bf6879d`

**Comment by panicstevenson** [comment]
> Message with code 0044 are in the log itself (e.g. some earlier runs have `00|2021-04-15T00:49:01.0000000+10:00|0044|Familiar Male Voice|I won't let you harm my sister!|454ac4234f314a3a15a8402f3bf6879d`

Oh wow, so those are from Diamond Weapon; but, there was a deliberate update in 5.5 to potentially hide some information from ACT.

@cmgau do you know if the chat lines still appear in the logs? I'd imagine you have the NPC event logs enabled since you got them for Diamond Weapon. Since someone is using a macro to call these out (it seems like to maybe manually trigger everyone's ACT?), the bubbles still obviously appear, but I wonder if they've been removed from the log lines as a means to prevent basic ACT usage (similar to TEA headmarkers). This information is obviously still available in the network capture, but I don't know if chat bubbles are currently being parsed by the FFXIV parsing plugin.

**Comment by quisquous** [comment]
One thing that you could test is doing a `/countdown 5` in Summerford Farms and seeing if that starts the test timeline.  Did you happen to click the "disable chat log for privacy" checkbox at any point?

**Comment by ackwell** [comment]
> there was a deliberate update in 5.5 to potentially hide some information from ACT.

if you mean the `_rsv` fields, it doesn't look like `NpcYell` isn't effected by that particular change - the quote yells are still in the data (using hallowed moon as an example):

[![image](https://user-images.githubusercontent.com/534235/114806577-56d97f00-9de8-11eb-9df0-399e448b4aeb.png)](https://xivapi.com/lore?string=hallowed%20moon&columns=Text)

that doesn't rule out other changes, obviously

**Comment by cmgau** [comment]
> > Message with code 0044 are in the log itself (e.g. some earlier runs have `00|2021-04-15T00:49:01.0000000+10:00|0044|Familiar Male Voice|I won't let you harm my sister!|454ac4234f314a3a15a8402f3bf6879d`
> 
> Oh wow, so those are from Diamond Weapon; but, there was a deliberate update in 5.5 to potentially hide some information from ACT.
> 
> @cmgau do you know if the chat lines still appear in the logs? I'd imagine you have the NPC event logs enabled since you got them for Diamond Weapon. Since someone is using a macro to call these out (it seems like to maybe manually trigger everyone's ACT?), the bubbles still obviously appear, but I wonder if they've been removed from the log lines as a means to prevent basic ACT usage (similar to TEA headmarkers). This information is obviously still available in the network capture, but I don't know if chat bubbles are currently being parsed by the FFXIV parsing plugin.

I think I figured it out, was rewatching our vods. The Nael Quotes weren't working, after progging I reset all my settings in FFXIV. Turns out the messages weren't appearing in the chat log during our prog run because they were disabled. I think it should work now that I've reverted my chat settings to default. 

Thanks guys for all your help.
