### ISSUE TITLE
eslint key ordering warning shows false positive warnings

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#2739]
See: https://github.com/quisquous/cactbot/pull/2736/files#diff-6e4e9ad12c6f2792e12247c8aa2ab1613ac2fed50a678684beced2721211c552

cc @MaikoTan

**Comment by quisquous** [comment]
Ah, this is a real warning, it's just not present in that tree that the PR is on top of.

**Comment by quisquous** [comment]
I wonder if this should be an error instead?

**Comment by MaikoTan** [comment]
If it were set as an error, then users should always order the keys before the PR merged.
I think both okay, though.
