### ISSUE TITLE
Raidboss module error

### ISSUE THREAD

**Issue by LydieSuelle** [quisquous/cactbot#274]
Hi!
The raidboss module suddenly doesn't work for me anymore. In ACT it says "Uncaught TypeError: Cannot read property 'SetDataFiles' of undefined (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/cactbot/ui/raidboss/raidboss.html, Line: 47)".
I didn't use ACT for a few days but yesterday again. There were no updates or other changes during that time. Then I downloaded the latest Cactbot update thinking it would help, but I still get the same error. I removed the overlay plugin and added it again but this didn't work either.
I'm sorry, I don't know very much about programming and stuff, so I don't know how to solve this problem myself at all.
Thank you for helping!

**Comment by Pirate144** [comment]
Sounds like your forgot to unlock what you downloaded.

**Comment by quisquous** [comment]
I don't think this is an unblocking issue.

Does selecting the raidboss overlay in ACT and hitting the "Reload Overlay" button make the problem go away, or does that happen 100% of the time?

Out of curiosity, what do you have set in your Custom User Config Directory? If you clear that, does it work properly?

**Comment by quisquous** [comment]
Were you able to sort out what was going on here?

**Comment by quisquous** [comment]
I'm going to close this old bug for now.  If this is still happening, please leave another comment.
