### ISSUE TITLE
Cactbot giving out .NET Framwork errors

### ISSUE THREAD

**Issue by leonathemoth** [quisquous/cactbot#278]
I'm running the latest everything but I'm getting an error saying "An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. IF this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch." I was not having this issue with the default overlay plugin so this is a cactbot issue for me. I've looked in the machine.config for .NET Framework for this loadFromRemoteSources switch but it apparently doesn't exist. Please assist!

**Comment by quisquous** [comment]
Take a look at https://github.com/quisquous/cactbot#potential-errors-and-workarounds for your error message, and let me know if that doesn't fix your problem.

**Comment by leonathemoth** [comment]
Thanks, that fixed it!

**Comment by quisquous** [comment]
Glad you got it sorted.  :+1:
