### ISSUE TITLE
Resources: Selecting info severity level for the tankBuster() response fails

### ISSUE THREAD

**Issue by JLGarber** [quisquous/cactbot#2793]
I came across this one while doing some work on Lakshmi. `tankBuster()` works, and `tankBuster('alarm') works, but `tankBuster('info') fails. ([Sohm Al normal](https://github.com/quisquous/cactbot/blob/56e201238fccddb67f6005f3e3f6610c205c94b2/ui/raidboss/data/03-hw/dungeon/sohm_al.js) has one, although it's probably easier to reproduce by editing something else.)

There's nothing immediately obvious (to me, anyway) on why it's failing. I poked through `responses` a little and there doesn't *seem* to be any reason `info` fails while `alarm` doesn't.

**Comment by quisquous** [comment]
It's possible that `combineFuncs` is broken.  I would be curious if `tankBuster('info', 'alert')` worked when `tankBuster('info')` (which should be equivalent to `tankBuster('info', 'info')`) doesn't work.

**Comment by JLGarber** [comment]
I'm away from my computer for a while, but I should be able to check that later tonight.

**Comment by JLGarber** [comment]
Your intuition was correct. If the two parameters for `tankBuster()` match, the trigger fails, no matter what level that matching severity is. I don't have time to sift through this tonight, but I'll look more tomorrow or Monday if you haven't got to it by then.

(Copying [`combineFuncs()` ](https://github.com/quisquous/cactbot/blob/main/resources/responses.js#L104)here in line for ease of reference for other readers.)
```
const combineFuncs = function(text1, func1, text2, func2) {
  const obj = {};

  if (text1 !== text2) {
    obj[text1] = func1;
    obj[text2] = func2;
  } else {
    obj[text1] = (data, matches, output) => {
      func1(data, matches, output) || func2(data, matches, output);
    };
  }
  return obj;
};
```

**Comment by quisquous** [comment]
I think there's a missing return there.  It should say `return func1() || func2()`.

**Comment by JLGarber** [comment]
Confirmed, that was the issue. PR landing shortly...
