### ISSUE TITLE
Not getting Long/Short Ice calls during 12s basic relativity

### ISSUE THREAD

**Issue by imynwulf** [quisquous/cactbot#2803]
Last night while running 12s, I noticed that I wasn't being alerted when I got the ice debuff during basic relativity. 

This morning, I loaded the network log into the emulator to verify that I wasn't blind. In every pull of Oracle, the fire debuff is being alerted on the proper DPS, but the ice debuffs are missing from the list. 

[Trimmed Network log](https://github.com/quisquous/cactbot/files/6385719/Network_20809_20210426.zip)

Here's some screenshots from the emulator on our last pull of Oracle. 
[Short fire on MNK and RDM(not shown)](https://b.catgirlsare.sexy/1io0Dme-.png)
[Long fire on NIN and DNC (not shown)](https://b.catgirlsare.sexy/_jG4HNiu.png)

**Comment by quisquous** [comment]
Fixed by #2811
