### ISSUE TITLE
Bug: AST Cards are not showing up anymore

### ISSUE THREAD

**Issue by valth0nis** [quisquous/cactbot#2814]
When I draw a card the color and 1 or 0 are no longer showing up in the jobs overlay for AST.

**Comment by panicstevenson** [comment]
Sorry if this comes off as redundant, I don't play AST so I'm not intimately familiar with what the user experience should be.

Are you saying that your overlay does not look like this?
![image](https://user-images.githubusercontent.com/8849608/116792653-db79fd80-aa76-11eb-854b-aec7e5809196.png)

Or that it _does_ look like that, and that is a regression/change from what it previously looked like?

**Comment by valth0nis** [comment]
Mine no longer looks like that. It's just grey squares where the X and 3 should be.

**Comment by MaikoTan** [comment]
Did you update `cactbot` after patch 5.5 landed?
I think this is related to my last PR, which changed the returned data format of the backend, so users can only get correct data when they update cactbot.

**Comment by valth0nis** [comment]
I updated through ACT but I'll do it manually and report back.

**Comment by valth0nis** [comment]
Deleting it and reinstalling manually fixed the issue for me.
