### ISSUE TITLE
Samurai offsets

### ISSUE THREAD

**Issue by gaogaostegosaurus** [quisquous/cactbot#282]
Not much of a programmer/developer and I find it likely that someone has already figured it out, but I saw that the pointers for SAM didn't exist in FFXIVProcess.cs yet. So just in case:

Kenki is +0 ("0x8 bytes in"? Looking at the comments, but I don't really know what it means...)
Sen is +1  ("0x9 bytes in"?)

On the Sen byte, Setsu = 1, Gekko = 2, Ka = 4, so all three (for example) would show up as 7 at the Sen offset, Setsu + Gekko as 3, and so forth.

Excuse the lack of proper terminology. =)

**Comment by quisquous** [comment]
Thanks!
