### ISSUE TITLE
Looking for ways to modify timeline localisation (timelineReplace) in user file

### ISSUE THREAD

**Issue by Elypha** [quisquous/cactbot#2835]
Hello, I want to have my custom text modification over the existing localisations and want to save such configurations in my user files. I tried to do it in the same way I do with my custom triggers first, but it does not work.

```javascript
Options.Triggers.push({
  zoneId: ZoneId.TheRoyalMenagerie,
  timelineReplace: [
    {
      'locale': 'ja',
      'replaceText': {
        'Tidal Wave': 'アムレン',
      },
    },
  ],
});
```

I found another related [issue](https://github.com/quisquous/cactbot/issues/2307) but the solution seems to be not working.

BTW, editing the bundle js definitely works well but I think users are not supposed to make modifications directly to that file.

Could someone give me suggestions about it? Thanks!

**Comment by Akurosia** [comment]
locale is `ja` not `jp`

**Comment by Elypha** [comment]
> locale is `ja` not `jp`

Thanks for pointing that out! I edited my local config file and reloaded it, but it seems that it is still not working and I could not see any of my modifications.

From the log window, I can see log lines for trigger overriding like:
`BrowserConsole: Overriding 'General Provoke' from '00-misc/general.js' with '...'`
But I didn't find log lines related to localisations being overridden. Is there any way that I can debug and know whether the user config is parsed well?

**Comment by quisquous** [comment]
There are no log lines for this.  You could debug by overriding the test timeline and doing a `/countdown 5` in Summerford Farms to see if it works.
