### ISSUE TITLE
Deleting code out of .js file doesnt stop triggers at runtime

### ISSUE THREAD

**Issue by jmgwynn** [quisquous/cactbot#2843]
I've both commented and deleted the code for UWU jails in an attempt to stop interference with the jail plugin my static is using. However, cactbot's jail functions still execute, causing overlap, and subsequently, wipes unless i disable audio callouts.

Things I have done:

- Commented the code in the .js
- Deleted the code
- Removed cactbot from my plugins and added it back
- Deleted the plugin cache in %appdata%

**Comment by quisquous** [comment]
Yes, that is 100% true.  The individual trigger file js files are not used, so you cannot modify them and have any effect.  You should use the cactbot config ui to disable triggers.

See: https://github.com/quisquous/cactbot/blob/main/docs/CactbotCustomization.md#using-the-cactbot-ui

**Comment by quisquous** [comment]
Let me know if you have any other questions.  I think this is answered, so I will close it for now.
