### ISSUE TITLE
Feather Rain in Uwu - Phase Ultima isnt getting called

### ISSUE THREAD

**Issue by Vaniquin** [quisquous/cactbot#2867]
Basically, the double feather rain before the stack marker/triple weight of the lands with Mesohigh isnt getting called by cactbot

**Comment by quisquous** [comment]
Sorry I forgot about this issue for almost a year.  Did did this keep happening for you?  I ran uwu after this bug report and it seemed to work fine for me.  Do you have any network logs of this happening?

**Comment by quisquous** [comment]
I'm going to close this for now, as I didn't see any issues.  Feel free to reopen or recomment if this is still an issue.
