### ISSUE TITLE
Unable to save edited UI user modules.

### ISSUE THREAD

**Issue by DanchouKiki** [quisquous/cactbot#287]
I'm very new to working with Cactbot, so not sure if I'm not doing something right/I'm missing something. I wanted to edit the raidboss.js in the user folder to turn on TTS like how it was shown in the guide, so I dragged the js into a note pad and edited what I needed to then tried to save the file. Everytime I try to overwrite the raidboss.js file I will get an error saying that I don't have permission to open the file, made sure everything was unblocked and that I had permissions on my end for the file.

**Comment by quisquous** [comment]
Usually people have their ACT folder inside of Program Files, which means that you need to be an administrator to edit the files there.  If you run notepad as administrator, it'll let you save it there.

**Comment by DanchouKiki** [comment]
Apparently admin permissions on my computer got messed up after a power outage. I got it to work after re going over all of the permissions, sorry about that...

**Comment by quisquous** [comment]
No worries! Glad you got it sorted.
