### ISSUE TITLE
Gladiator Has Wrong Acronym

### ISSUE THREAD

**Issue by panicstevenson** [quisquous/cactbot#289]
Gladiator is stylized as `GLD` throughout Cactbot; the acronym in game is `GLA`.  However, everything works as expected from within the code since the enumeration within `FFXIVProcess.cs` returns `GLD`. Changing this value would require users to update their plugin if they're pointing to the remote HTML. Pretty pointless change; we can determine if it's worth leaving a pull request open until another update comes through to be published with or skip fixing it entirely.

**Comment by quisquous** [comment]
I don't know that anything uses this directly, so it'd probably be fine to change whenever.  I'll try to remember to get this in the next version.
