### ISSUE TITLE
Sigmascape Timelines

### ISSUE THREAD

**Issue by xephero** [quisquous/cactbot#29]
I made a timeline for O5S based off various streams and videos. No syncs, no in-game testing while ACT is down, but I figure it's a headstart on 4.2 raidboss support.

[o5s.txt](https://github.com/quisquous/cactbot/files/1680532/o5s.txt)

**Comment by quisquous** [comment]
Oh heck yeah.  I'll add this in once ACT is fixed and we have some zone names.  Thanks!
