### ISSUE TITLE
Raidboss not showing Timeline for Garuda in UwU.

### ISSUE THREAD

**Issue by DanchouKiki** [quisquous/cactbot#291]
Raidboss module isn't showing timelines for Garuda in UwU, I still get call outs for getting marked for minstrel and when she is woke. Time line appears right after Ifrit transition before he lands to do his ultimate, normal for the rest of the fight.

**Comment by quisquous** [comment]
The garuda timeline should start if you have a countdown timer, but also on the `Heehee HAHA` message that she does when you start.

If you have an ACT log still around, can you look at the combat message and paste the line that has `Heehee HAHA` here? I wonder if this is related to #295 and the log message ids have now changed.

**Comment by DanchouKiki** [comment]
00|2018-11-24T23:13:38.0000000-08:00|0044|Garuda|Heehee HAHA hahaha HEEHEE haha HEEEEEE!!!|3a22329f37e82e451cefea46de4b0212

Strangely enough, the issue resolved itself after a few days for no real reason, but just in case there it is.
