### ISSUE TITLE
Partial Callouts

### ISSUE THREAD

**Issue by xlpbodily** [quisquous/cactbot#293]
I keep seeming to have this issue where while running content (i.e. O10S) callouts are accurate, but occasionally they will just not go off. Earthshaker in's/out's, Cardinals or Corners, Tank Debuff for death from above and death from below (I play War). Just wondering if anybody else is having this issue where callouts are missed. Most of the time it works, just occasionally it doesn't and I'm trying to figure out why and kinda pulling my hair out over it. 

Thanks

**Comment by quisquous** [comment]
I have seen ACT drop messages in the past when network log processing gets overloaded.  Do you have the "use high performance network filter" checkbox checked in the ffxiv plugin settings?

Are there any errors in the plugin log?

**Comment by xlpbodily** [comment]
There are no errors, i did not have the "use high performance network filter" checked, but I did lower the "dps update interval" to 0 and seemed to do better during an O10S run on 2 nights ago but was only there for 2 pulls, so i might have been a fluke. would it be better to use the high performance network filter or leave it off?

**Comment by xlpbodily** [comment]
After making the change issue has been resolved. thanks for your help!
