### ISSUE TITLE
add Labels to github PR

### ISSUE THREAD

**Issue by Trim21** [quisquous/cactbot#2945]
It's a little bit nosying to watch all PR.

Add labels to pr would help to filter PR like "translation: CN"

**Comment by MaikoTan** [comment]
If you want to add more labels, I think labels as below should be added too:

- Translations
  - DE
  - FR
  - JA
  - CN
  - KO
- Feature
  - Raidboss
  - Jobs
  - Eureka
  - (and so on)
- Bug Fixed
- Performance
- Coding Style
- Utils
- CI

**Comment by quisquous** [comment]
Is there some way to automate adding labels?  I don't want to be responsible for labeling PRs that other people don't label if you think this is useful.

**Comment by Trim21** [comment]
2 way, PR template and github actions https://github.com/actions/labeler

**Comment by quisquous** [comment]
I think the only things that aren't really automated are bug/performance/coding style, but if we could automate labels for everything else through a script and a github action, that'd be great.  Is that something you'd be interested in writing?

**Comment by Trim21** [comment]
We can write a script to parse checkboxes in PR descriptions and set labels.

**Comment by quisquous** [comment]
Oh, I was wondering if it could parse the changes in the PR itself.  Is that possible?

**Comment by Trim21** [comment]
I think not all labels are possible.

it's easy to parse labels like `module: raidboss`, but hard for `translation: DE`.

**Comment by quisquous** [comment]
I think the hard ones are bug/feature/style.  I think translation is possible (maybe tricky, but still possible), as we already have scripts to find missing translations.

Mostly, I just don't want to add any extra work to people submitting PRs to categorize.  If we can make it automatic, then I think that will add a lot of information without requiring every PR to categorize itself manually.

**Comment by Trim21** [comment]
It would be impossible to parse diff and saying that it's bugfix/feature/style. There is no way to distinguish them.

**Comment by quisquous** [comment]
Yes, I agree that those are impossible, but I think those are also the least useful.  If those are optional/manual, that seems ok.

**Comment by Trim21** [comment]
I'm considering that parse diff with some regex like `/-.*cn.*/`

**Comment by Trim21** [comment]
https://github.com/Trim21/cactbot/blob/main/.github/workflows/labels.yaml

example:
https://github.com/Trim21/cactbot/pull/143

**Comment by panicstevenson** [comment]
This is awesome! Could we [color-code the various labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels)? For example, the distinction between `bug` and `enhancement` labels in the issues tab are different colors, which makes it very easy to look at things at a high level. (I think this is an ask for quisquous, not for the open PR, to be clear).

**Comment by Trim21** [comment]
@quisquous can set the color of these labels manually.

And my scripts didn't contain labels like `bug fix` or `feature`
