### ISSUE TITLE
PR labels for copy+paste translations

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#2972]
This is a follow-up question for #2967.  (cc @Trim21)

Looking at #1677, new triggers are being added and there's copy+paste of various languages.  Nothing *new* is being translated, I'm just trying to save some work.  However, this copy+paste leads to these labels:

```
PR_NUMBER=1677 node .github/scripts/auto-label.cjs
label: cn [translation]
label: de [translation]
label: ja [translation]
label: fr [translation]
label: ko [translation]
label: raidboss [filename] (ui/raidboss/data/05-shb/trial/wol-ex.js)
label: raidboss [filename] (ui/raidboss/data/05-shb/trial/wol-ex.txt)
label: raidboss [filename] (ui/raidboss/data/manifest.txt)
apply: ["raidboss","�CN","�DE","�JA","�FR","�KO"]
```

Should we ignore new translations when the object itself that the translations are included in is also added?  Mostly I ask because if you did filter it out (so that this patch would only be "raidboss"), then a "de" label on its own is "this is a translation patch only" and "de"+"raidboss" means "this is a translation patch that also has other raidboss changes".

One reason I was thinking this is that I think these labels might make it possible to do what @panicstevenson has suggested to me for forever, and that's to automate the release notes.  I usually skip translation patches there because there's usually a lot of them, and (maybe I'm wrong) but I think that the information conveyed by saying "translated a bunch of in arr" is not very useful to anybody.  So, having a way to say "this is only a translation patch" would be useful for me (and maybe more useful for people looking at PRs as well)?

Mostly just asking here because I don't know how people expected to use labels.

(This does make me also wonder if we should include +netregexDe kinds of lines too as translations.)

**Comment by Trim21** [comment]
I don't think so, a CN translation is added for a new raid indeed.

**Comment by panicstevenson** [comment]
Thinking about an end product of a changelog, I would expect something like:
```
Raidboss:
 - Added WoL Ex (#<fake number to not link>)
Translations:
 - Chinese (#FakeNo1, #FakeNo2)
```
In which case, I think tagging that I added something in Chinese would not be true. For this case, I would also expect that `+ netRegex\w{2}` should not add a translation tag, since those generally get added in a batch?

Maybe a counter-point would be to stop bringing in default translation blocks from other languages (to avoid incorrect translations) and to instead focus on using and extending Outputs? I say this even though I'm probably the most guilty person when it comes to that pattern.

**Comment by Trim21** [comment]
And I think `- netregexDe` maybe a good suggestion.

**Comment by quisquous** [comment]
So sounds like maybe we shouldn't copy and paste translations then, both for correctness and for labels.  Sorry for copying and pasting incorrect translations in the past!

Ok, assuming that we stop doing that, then if we want to be able to generate such a changelog, how do we say that 2966 (see output [in this comment](https://github.com/quisquous/cactbot/pull/2967#issuecomment-851643675)) is only a translation patch and not a raidboss patch.  I mean, technically it is a raidboss patch too (and so maybe that's good to have a label, to differentiate "this is an oopsy translation" from "this is a eureka translation"?)

We can certainly have a different script generate a changelog.  It doesn't have to be tied to labels, although reusing the label code would be convenient.

**Comment by Trim21** [comment]
I think it's enough if you write merge commit message in semantic commit message, there are a lot of changelog generator...

**Comment by quisquous** [comment]
Yes, but this comes back to enforcing that everybody else writes commit messages that can be parsed properly.  (Or it means that I carefully rewrite everything to be a proper commit message?)  Mostly I'm asking a "can this be automated so I don't have to do anything manually" sort of question.  I think commit messages are definitely an option (and maybe we should do it anyway?), just trying to understand if it's possible to automate this too.  :)

**Comment by Trim21** [comment]
My suggestion means that you carefully rewrite everything to be a proper commit message.

Of we force pr title to be valid (maybe better) and using the title as commit message(github already do it as default)

**Comment by panicstevenson** [comment]
> Of we force pr title to be valid

There's existing workflows that do similar: https://github.com/zeke/semantic-pull-requests

**Comment by Trim21** [comment]
> > Of we force pr title to be valid
> 
> There's existing workflows that do similar: https://github.com/zeke/semantic-pull-requests

Looks good

**Comment by quisquous** [comment]
Back to the original issue, I think #2975 is a another example of what I meant (if we added netRegex line detection).  I don't think that patch should be labeled as all languages, mostly because I don't feel like that would be useful to people looking at PRs?

**Comment by panicstevenson** [comment]
> Back to the original issue, I think #2975 is a another example of what I meant (if we added netRegex line detection). I don't think that patch should be labeled as all languages, mostly because I don't feel like that would be useful to people looking at PRs?

I agree, I'm personally still of the opinion that we shouldn't add netRegex__ to the check, since Akurosia comes through with giant swaths of translations for these, but not translating the actual callouts generally. Since these are generated automatically from XIVAPI or something similar, I don't think there's any reason to catch the interest of Japanese or French translators for that, since there's nothing they need to review as far as I can tell. They might be interested in the new triggers being added, but that's probably implied with new content dropping.

**Comment by Trim21** [comment]
if they are generated from xivapi, I think we shouldn't.

**Comment by quisquous** [comment]
I think the PR labelling is all good at this point and we have PR title enforcing, so this can be closed.
