### ISSUE TITLE
Nothing working and logs spammed with error

### ISSUE THREAD

**Issue by kyroxiv** [quisquous/cactbot#299]
Sorry if this is simple im not sure exactly what to do, so basically everything shows up but when i do anything nothing gets logged, errors are - 
![image](https://user-images.githubusercontent.com/45282757/48932338-34113d80-eeb0-11e8-9c48-af558645bae5.png)

**Comment by quisquous** [comment]
Whoa, this is very strange.  Are you running as administrator?

**Comment by quisquous** [comment]
Is this still happening? Have you tried reinstalling and unblocking everything?

**Comment by quisquous** [comment]
I'm going to close this old bug for now.  Please leave another comment if this is still happening.
