### ISSUE TITLE
cactbot not working at all

### ISSUE THREAD

**Issue by 73u38** [quisquous/cactbot#30]
im using cactbot 0.5.2 and not working at all even jobs ui, raidboss and test not working
overlay i use ver 0.3.4.0 and ffxiv act plugin i use 1.6.2.4
![image](https://user-images.githubusercontent.com/6307962/35691738-db561062-07ab-11e8-8368-f9691257a0be.png)

**Comment by michii88** [comment]
There is a new release of cactbot that quisquous just uploaded. Use that one and post update if possible.

**Comment by 73u38** [comment]
yeah only jobs not working raidboss and test working atm

**Comment by danakj** [comment]
There's a number of troubleshooting steps in the install instructions which you should make sure to give a try, if you haven't. If you have can you confirm what log messages you are seeing in the OverlayPlugin ACT tab?

**Comment by danakj** [comment]
> yeah only jobs not working raidboss and test working atm

The jobs UI depends on reading memory addresses from the game which changed with the latest patch. Hopefully the latest cactbot update resolves that as michii88 says. If not can you explain the problem in more detail, what job you're playing, what you are or aren't seeing, the log messages from the OverlayPlugin tab, etc? Thanks.

**Comment by 73u38** [comment]
im playing monk atm... but so weird no error message on logs. but it didnt show anything

**Comment by quisquous** [comment]
Did 0.5.2 work for you before ffxiv patched to 4.2?

The only thing that changed with the plugin (other than the version number) was the memory addresses, so that would make the test page and jobs not work if you were still using the old plugin.

Can you double check what version of cactbot ACT thinks it's using?

**Comment by 73u38** [comment]
Yea i alreqdy use 0.6.0 but still jobs not working and i tried on dummy timeline works but using like poke not work atm.

**Comment by quisquous** [comment]
So just so I understand, the raidboss overlay is working for you.  You can start the timeline with /countdown properly, I'm guessing?

You've added a second overlay for jobs? What does it look like? Can you screenshot the config for the jobs overlay? Do you get any hp bars or anything?

**Comment by xDemonessx** [comment]
Test UI works for me, I also tested dps rdmty which works (But is not catching crits for some reason). First time installation. Instructions clear, had no issues loading it. Will check back after I get into O5S. Testing that unsycned timeline with the plugin, if my PC is able to handle it...

**Comment by 73u38** [comment]
i didnt get any bar for jobs overlay just blank page. 
![image](https://user-images.githubusercontent.com/6307962/35722891-b66ca08e-082a-11e8-81e1-5e8f997befc6.png)
for raidboss only work timeline but when i use /poke etc didnt show me any message

**Comment by 73u38** [comment]
![image](https://user-images.githubusercontent.com/6307962/35722926-ec8ca8d0-082a-11e8-95e3-f24496ae44f0.png)
this for my jobs overlay

**Comment by xDemonessx** [comment]
Didn't have raidboss "working" last night. I double checked my version and realized i had an old release, reinstalled, and can confirm jobs are populating. 

![gilliamii_2018-02-02_46](https://user-images.githubusercontent.com/3487603/35760277-d6f562cc-0844-11e8-97c2-674156a6eb25.png)

I'll have to re-work some sync/triggers on my encounter last night.

 @73u38 - delete everything and double check your version.  Make sure youre on .6.0 - close ACT, delete all files and folders for catcbot and try again.

**Comment by 73u38** [comment]
I gonna try clean all cactbot addons first and gonna reinstall from clean. For pull request yes its detected i tried on rabanste the timeline working but sometimes timeline late

**Comment by 73u38** [comment]
yep after i do clean install now working :D gonna test for raidbots call out then

**Comment by quisquous** [comment]
Thanks for the update.  Sounds like this is all (or at least, mostly) working, then?

**Comment by 73u38** [comment]
Yeah for now but still sometimes rabanste timer pop late like late for 4 sec

**Comment by quisquous** [comment]
I've found that other plugins can really lag ACT.  If you're running enmity plugin with everything turned on, all raba triggers will lag.  You could try adding ACT Custom Triggers and see if it's ACT vs cactbot, but I suspect it's everything together that's slow.

I'm going to close this issue as it sounds like the original "cactbot not working at all" is solved.
