### ISSUE TITLE
TEA Final Word call out override doesn't work

### ISSUE THREAD

**Issue by wtyanan** [quisquous/cactbot#3005]
## Description

TEA Final Word Override didn't work for me, I manually changed callouts and it's still calling out default callouts.

## Additional information

![image](https://user-images.githubusercontent.com/26291460/120745125-7462c500-c4ca-11eb-96dc-d70e19338bc5.png)
![image](https://user-images.githubusercontent.com/26291460/120745141-7e84c380-c4ca-11eb-8fae-2f7bf2b26fb0.png)

**Comment by quisquous** [comment]
Additional info from discord that changing overrides for the Angry Dummy test trigger did work, however.

**Comment by valarnin** [comment]
I tested this in raidemulator and can't reproduce, for at least the `TEA Contact Prohibition` trigger.

![image](https://user-images.githubusercontent.com/6119598/120840593-74011300-c538-11eb-9550-5750a914a9bf.png)
![image](https://user-images.githubusercontent.com/6119598/120840786-a7dc3880-c538-11eb-9953-b1681d0f379a.png)
![image](https://user-images.githubusercontent.com/6119598/120840701-909d4b00-c538-11eb-8588-5e03d2e2fd2e.png)

**Comment by wtyanan** [comment]
Don't know how to use raidemulator, but here's a clip of cactbot calling out purple with the above setup 
https://clips.twitch.tv/HedonisticTolerantVelociraptorAMPEnergy-AdRYrs8HAruvQ9yb

**Comment by quisquous** [comment]
Sorry for not having the time to explain raidemulator on discord the other day.  I realized belatedly that there's instructions in the main readme: https://github.com/quisquous/cactbot#raidboss-emulator

**Comment by wtyanan** [comment]
I tried to use it but seems like my 12min log doesn't have an entry for the call for some reason

**Comment by quisquous** [comment]
Sorry to not get back to this in so long.  Did you ever get this sorted?

I think really you running this in raid emulator is the best bet to solve this.  I saw your clip, but there are no default triggers that only say "Purple" and so it's not clear to me what is calling that out.

**Comment by quisquous** [comment]
Let me know if this is still an issue, but I am going to close this old issue for now.
