### ISSUE TITLE
xephero layout won't resize

### ISSUE THREAD

**Issue by benfreefly** [quisquous/cactbot#303]
I've loaded the xephero html into a cactbot overlay and resized the overlay to the width I want, but the actual content does not resize with the overlay -- it just stays a small size taking up only a small corner of the available space.  Am I missing something? Does CSS need to be edited somewhere?

**Comment by quisquous** [comment]
I prefer to have my dps meter to not be super huge if it doesn't need to be.  If folks have long names, it will take up *up* to the width you specify, but otherwise be as small as it needs to be.

If you want to make it bigger, create a file called **cactbot/user/xephero.css** and add this in it:
```
#overlay {
  width: 100%;
}
```

**Comment by quisquous** [comment]
That I just fixed in d1e158a, sorry.

**Comment by quisquous** [comment]
Is there more to be fixed here, other than the ellipses issue?
