### ISSUE TITLE
Dun Scaith: Ferdiad Hollow Wormhole callouts' Atomos colors are wrong about half of the time

### ISSUE THREAD

**Issue by Kryomancer** [quisquous/cactbot#3033]
## Description

I've been running Dun Scaith a few times in the past few days, and I've noticed that the callouts for Ferdiad Hollow's Wormhole (where the blue and yellow Atomos warp either round or donut AoE markers around) seems to be wrong in terms of the Atomos colors about half of the time, give or take a little. I haven't figured out any specific pattern as to when it'll be right or wrong, and seemingly it can happen on all possible variations of the mechanic. I think it does always get the donut vs circle right but the color seems more or less randomly successful.

## Additional information

For example:

Single donut calling the color right:
![right](https://i.imgur.com/4dgFzGn.png)
And the same thing but wrong (should be "go to untethered blue"):
![wrong](https://i.imgur.com/KRRGeNz.png)

[Log of run in question](https://gist.github.com/Kryomancer/8453a2d00656765fab75a1925a99820f#file-splitnetwork_20907_20210607-2021-06-07t17-24-44-171z-txt). I'm sorry I can't point out which specific instances of the mech corresponds to the images in question so I'm not sure how helpful this is.

ACT version 3.5.0, release 273
FFXIV act plugin version : 2.0.9.7
Overlay plugin NGLD version: 0.16.6.0
Cactbot version: 0.22.10.0

(I'm fully aware this isn't particularly relevant content nor a difficult mechanic, so the priority of this is not that high. It's more of a "would be nice if" -thing.)

**Comment by valarnin** [comment]
This looks like it might be caused by case sensitivity issues?

Running this log through raidemulator:

`00:54 | Dun Scaith Atomos Setup` (the second one) shows:
```json
{
"matches": {
      "type": "03",
      "timestamp": "2021-06-07T20:38:54.6680000+03:00",
      "id": "40008c96",
      "name": "Cursing Atomos",
      "job": "0",
      "level": "3c",
      "ownerId": "0",
      "world": "",
      "npcNameId": "5511",
      "npcBaseId": "6442",
      "currentHp": "4800000",
      "hp": "4800000",
      "x": "-322.3",
      "y": "236.5",
      "z": "-7",
      "heading": "-1.981023"
    }
}
```

`id` has lowercase hex value.

`00:56 | Dun Scaith Atomos Compile` shows:
```json
{
    "matches": {
      "type": "20",
      "timestamp": "2021-06-07T20:38:55.9670000+03:00",
      "sourceId": "40008C93",
      "source": "Aetherial Chakram",
      "id": "1CA0",
      "ability": "Juggling Sphere",
      "targetId": "40008C96",
      "target": "Cursing Atomos",
      "castTime": "6.70"
    }
}
```

`targetId` is uppercase hex.

**Comment by JLGarber** [comment]
Wow. Thanks for tracking that one down!
