### ISSUE TITLE
Question: Get Enemies' Location Realtime

### ISSUE THREAD

**Issue by MaikoTan** [quisquous/cactbot#3037]
As the title says, is there an exposed API from cactbot or OverlayPlugin to get the realtime location of enemies?

I know that currently we are using type `03: AddCombatant` LogLine that includes position, but only the position when it SHOWS/APPEARS. It is okay for mob hunting as those mobs would not run away from the appearing location so far, but when I want to track a enemy in dungeon, the logline methods doesn't work anymore.

**Comment by valarnin** [comment]
You can call `getCombatants` on-demand to get info. See various triggers such as `E9S Clone The Art Of Darkness` or `LeviUn Slam Location`. Is there something else you're looking for beyond that?

**Comment by MaikoTan** [comment]
> You can call `getCombatants` on-demand to get info. See various triggers such as `E9S Clone The Art Of Darkness` or `LeviUn Slam Location`. Is there something else you're looking for beyond that?

It is based on WebSocket message, right?
If I call it frequently like every .5 seconds or every 100 milliseconds, will it cause performance issues?

**Comment by valarnin** [comment]
.5s should be fine, but .1s might be a bit too fast for some slower PCs. What's the scope of this? raidboss trigger, or some other component?

**Comment by MaikoTan** [comment]
> .5s should be fine, but .1s might be a bit too fast for some slower PCs. What's the scope of this? raidboss trigger, or some other component?

A personal tracker used in solo Deep Dungeon, there are some scary mobs for a single player so I want to monitor their pace and decide whether I should hide myself.
Yeah, maybe .5 is okay for this use.

**Comment by valarnin** [comment]
If it's personal you can run adjust timing as needed, maybe make sure you run it in a setTimeout loop and not a setInterval so that if it's delayed it doesn't immediately run again causing cascading lag?

**Comment by valarnin** [comment]
This might be useful at some point for actual raidboss/etc functionality, if that ends up being the case I can handle setting up some sort of util that accepts essentially two callbacks, the first to get a request object, and the second to process the response and determine if it should keep watching, but that's a large chunk of code to write if it's not going to be used for anything yet.

**Comment by MaikoTan** [comment]
Oh you're right!
I should change setInterval to setTimeout.

And another question, I saw that `getCombatant` receive a array of names, so that means we can track multiple enemies in a single request? Also If I sent a empty array will it return all the combatants that it recorded?

**Comment by valarnin** [comment]
Yes to both of those questions.

Functionally:

1. If no IDs or Names are provided, all combatants in memory are returned
2. If any Names are provided, any combatant that matches a name is returned
3. If any IDs are specified, any combatant that matches an ID is returned

Essentially:

```typescript
for (const combatant of combatants) {
  if (names.length === 0 && ids.length === 0) {
    returnedCombatants.push(combatant);
    continue;
  }
  if (names.length && names.includes(combatant.name) {
    returnedCombatants.push(combatant);
    continue;
  }
  if (ids.length && ids.includes(combatant.id) {
    returnedCombatants.push(combatant);
  }
}
```

**Comment by MaikoTan** [comment]
Wow that's extremely comprehensive!
Thanks for your help.

**Comment by valarnin** [comment]
(actual C# code from OverlayPlugin just for reference)
https://github.com/ngld/OverlayPlugin/blob/master/OverlayPlugin.Core/EventSources/MiniParseEventSource.cs#L115-L152
https://github.com/ngld/OverlayPlugin/blob/master/OverlayPlugin.Core/EventSources/MiniParseEventSource.cs#L245-L316

**Comment by MaikoTan** [comment]
Close 'cause answered comprehensively.
