### ISSUE TITLE
lint: Add rule to disallow non-relative imports

### ISSUE THREAD

**Issue by valarnin** [quisquous/cactbot#3039]
Continuing the discussion from https://github.com/quisquous/cactbot/pull/3034#discussion_r647023921

CC @MaikoTan @Trim21 @quisquous since you all commented on the original thread.

I played around with the `no-restricted-imports` rule for a while tonight and wasn't able to get it to allow `./*` or `../*` paths. There doesn't seem to be another rule that would work here, either. All other related rules are to specifically disallow relative imports.

That seems to lead to the following two questions:

1. Is enforcing only relative imports the correct action, given that all rules seem to go towards the opposite?
2. Should we roll our own eslint rule to handle this if so?

**Comment by Trim21** [comment]
this maybe out of topic, “types/trigger” looks like a package that should be looked into `node_modules`, why it's working?

**Comment by quisquous** [comment]
I would also be ok with absolute imports everywhere instead of relative.  I think consistency is most important to me.

We're also at the point where https://eslint.org/docs/rules/sort-imports might be good too.

**Comment by valarnin** [comment]
I didn't mean to imply "hey, we should do it this way", just to point out what I was able to see with 30 minutes or so of googling and poking at the issue. It's entirely possible that there's no rule to enforce it fully the other way either, or that stylistically it makes more sense to use only relative imports.

Ultimately either way is fine with me and I agree that it's better for it to be consistent regardless of which way the import rule goes. I'm perfectly fine writing the rule myself if it needs to be done.

**Comment by MaikoTan** [comment]
Oops, sorry for that I suggested the wrong way.
I have searched for a while and found nothing about enforcing the relative imports.
(and I think what Trim said is right, given a path like `types/trigger` is not only like a package path but also possible cause conflict?)

**Comment by panicstevenson** [comment]
This is because the [base URL](https://github.com/quisquous/cactbot/blob/main/tsconfig.base.json#L17) is set to `./`, allowing you to import relative to the base when using the non-relative import syntax. It looks to be [purely cosmetic](https://www.typescriptlang.org/tsconfig#baseUrl) if we wanted to disable it (and update affected import statements).

**Comment by Trim21** [comment]
So we didn't need a lint rule just remove `baseUrl` from tsconfig looks enough

**Comment by valarnin** [comment]
Closing this now that the PR is merged, I don't think we need any further discussion around this.
