### ISSUE TITLE
no timelines for severall fight (german game)

### ISSUE THREAD

**Issue by Akurosia** [quisquous/cactbot#304]
Hi,
I encountered it now on severall fights that the timelines are not displayed.
These includes Suzaku Ex, Shinry EX, o9s, o10s and many others, while in some fights they are displayed without a problem.
I also tried to do the "reload overlay" trick mentioned in some other tickets.
When i try the timelines in other timeline plugins, i will get an issue with the timelines (to resolfe the issue in other timeline plugins, all decimal dots must be converted to a comma e.g. 0.0 will be 0,0)
There is also no error message inside the overlay.dll log section.

Any idea to fix this?

**Comment by quisquous** [comment]
Is it consistent in which fights they are and aren't displayed in? It sounds a little bit like #293.  Have you tried turning on the high-performance network filter? Have you made sure that in all the plugin configurations that the "dps update rate" is set to zero for all non-dps overlays?

Thanks for letting me know about the locale issue with commas when loading them in other timeline plugins.  I don't think that's something that I can fix automatically.

**Comment by Akurosia** [comment]
The fights are totally random (and once its displayed it will usually be displayed for all runs in the current session).
i did nod had the settings like you mentioned and i will try them now to see if these will work better. Once i had some runs i will let you know about the outcome.

**Comment by slashy** [comment]
I'm not sure if this is related. But I installed the plugin today for the first time and tried the test timeline with the striking dummy and it didn't work with the german client.

As soon as I set the client to English it started working tho. 

I have yet to test any of the other timelines, so I don't know if they work or if it's something I am missing.

**Comment by ArkfrostLumas** [comment]
I'm not sure, but for some reason recently there have been a few issues, where ACT changes the location name, which results in raidboss not detecting the fight at all on the German client. I had this problem as well, occasionally, but after a while it fixed itself somehow.
I'm also pretty confused about it, but for me everything is working fine, so far. No problems with o9s,  o10s and o11s so far. Callouts always come as supposed and timeline is also working.
I haven't tried out Suzaku and Shinryu Ex in months though.

**Comment by quisquous** [comment]
@slashy I wouldn't worry too much about the test timeline.  It looks like that doesn't have a german translation, so it's not surprising it didn't work.  So, I don't think that says anything one way or the other.

**Comment by Akurosia** [comment]
Ok some updates from yesterday,
o9s and o10s were working fine but Shynryu, Tsuku and Suzaku weren't.
is there any way to see the zone names which he should load + the files he should load?

**Comment by quisquous** [comment]
The zone names should appear in ACT.  It's what the encounter gets grouped under.  Another way to do it is if you add a cactbot overlay and point it at **ui/test/test.html** it will also tell you what the zone name is.  If you try this again, let me know what it says the zone name is.  I wonder if we're running into the mysterious parenthesis vs bracket issue again.

(Also, there's only triggres and timelines for extreme versions of all of those primals, so if you mean the normal versions, then that's expected that there's nothing there.  That seems unlikely that's what you mean, but thought I'd mention it.)

**Comment by Akurosia** [comment]
Ok so th einstance of Shinryu is called: "The Minstrel's Ballad: Shinryu's Domain" (in the german version using the test file you mentioned)
And yes, i am talking about ex versions :)

**Comment by quisquous** [comment]
Yeah, that's what the zoneRegex says for that fight: https://github.com/quisquous/cactbot/blob/master/ui/raidboss/data/triggers/shinryu-ex.js#L5

Do the triggers work in Shinryu, just not the timeline?

Looking at that file, it looks like there's no timeline translation and so it's not surprising to me that none of those syncs start the timeline properly.  This is what that looks like for o9s: https://github.com/quisquous/cactbot/blob/master/ui/raidboss/data/triggers/o9s.js#L579

**Comment by Akurosia** [comment]
Trigger are working fine

**Comment by quisquous** [comment]
Ohhhhh, ok.

Re: the extreme primals, no timeline just looks not implemented.  I can fix that, although probably need some translation followup.  I think those primals are old enough that they predated timeline translation support.

Re: o9s and o10s.  Those should be working, so if they're not, something else is awry.

**Comment by Akurosia** [comment]
In the shinryu file i can see a lot of "regexDe" tags which are only half translated (e.g. where only the skill name was changed but not the text before it).
Whats really strange is, that very rarely i can see the timelines in e.g. Shinryu.

**Comment by Akurosia** [comment]
ok tried shinryu and seems fine now.
Also we had yesterday the issue with the old data, that the final left/right wing were announeced incorrect in the english version.
But from what i saw in the file it looks correct (also in german these triggere weren't even displayed at all) Wanna have a sepperate issue for this?

**Comment by quisquous** [comment]
I'm going to go ahead and close this now as mostly working other than that last left/right wing issue.  Let me know if you run into any other german issues, as I don't run with that so it is easy for me to miss.  I'm always happy to fix them!
