### ISSUE TITLE
Manual cooldown inputs via command aren't formatted properly in Hydatos

### ISSUE THREAD

**Issue by steponmepls** [quisquous/cactbot#3042]
## Description

When using an echo command or just simply inputting cooldown info in chat from the eureka tracker, NMs are properly set on cooldown but the formatting doesn't change. It's supposed to be formatted in a smaller font and color changed to red (or that's what happens in other zones). I do use a custom css file but it edits unrelated parts of the overlay:

```
#label-container {
	font-size: .75rem;
}

.text.icon {
	font-size: 1rem;
}
```

## Additional information

![image](https://user-images.githubusercontent.com/63500907/121177792-1f260b00-c85e-11eb-9fd4-95a7c87b262d.png)

**Comment by quisquous** [comment]
Sorry, thanks for the bug report.  I'll try to get this fixed this weekend.  I probably broke it when changing the CSS formatting for duels.
