### ISSUE TITLE
Timeline progress bar does not start at the right position.

### ISSUE THREAD

**Issue by toomucheffort** [quisquous/cactbot#305]
The timeline progress bars starts at about 80% filled instead of 0%.

**Comment by quisquous** [comment]
I'm not quite sure what you mean, or what you expect to have happen.

Timeline progress bars all move at the same rate, and show up thirty seconds ahead of time.  So, if you start a fight, and something is going to happen in ten seconds right after the timeline starts, then the bar will start 2/3 of the way filled.

Does that help explain what you're seeing?

**Comment by toomucheffort** [comment]
Yes, it is what I was seeing. I thought it would always start at 0%. If it's how they're implemented then it's not a big deal. Thanks!
