### ISSUE TITLE
cacbot just doesnt appear after updating

### ISSUE THREAD

**Issue by geowolf18** [quisquous/cactbot#306]
previously i had cacbot installed and working but after updating it to the most recent version it just stopped showing up in the plugin set up menu i did everything i could think of even a complete fresh install of ACT and cacbot with the most recent files and still nothing

**Comment by geowolf18** [comment]
no i made sure to check that and even re downloaded the file and made sure to unblock it

**Comment by quisquous** [comment]
Do you get any error messages? Did the cactbot dll end up in the right place on disk? Can you show me what your directory structure looks like?

**Comment by geowolf18** [comment]
![wrgaga s](https://user-images.githubusercontent.com/45958074/50182387-357e2c00-02dd-11e9-9101-016e871e4d24.png)

**Comment by geowolf18** [comment]
![aehaehshsa](https://user-images.githubusercontent.com/45958074/50182465-6199ad00-02dd-11e9-83ae-20fe89bdc0df.png)

**Comment by quisquous** [comment]
Yeah, that all looks correct to me.  I'm assuming OverlayPlugin just shows the default options? In ACT is the OverlayPlugin.dll that you're using coming from that **Advanced Combat Tracker\OverlayPlugin** directory right there, and not somewhere else?

**Comment by geowolf18** [comment]
that is correct yes

**Comment by quisquous** [comment]
Sorry, I don't know what else to suggest at this point.

I think my only recommendation would be to use ezsoftware's bundle installer which sets up all the dependencies: https://www.reddit.com/r/ACTOverlayPlugin/comments/3b7ogz/instructionslatest_download/

If that works for cactbot 0.7.0, then from there try installing the newest cactbot on top of that.

**Comment by geowolf18** [comment]
ok thank you i will

**Comment by quisquous** [comment]
Excellent.  Sorry for all the hassle.  Getting everything installed properly is really a huge pain, and you're not the only person who has struggled to make it work.
