### ISSUE TITLE
Text to speech not working

### ISSUE THREAD

**Issue by CptDraco** [quisquous/cactbot#307]
A few weeks ago I noticed the TTS no longer working. I assumed it was a windows error and didn't persue it at the time. Now on a fresh install of the OS, ACT, OverlayPlugin and Cactbot it still doesn't work and setting
Options.SpokenAlertsEnabled = true seems to break Raidboss now.

**Comment by DrLippe** [comment]
Use the test overlay and type in chat `/e tts: something` to test TTS in general. 
If that is working take a look at your `user/` directory and check if there is a user override in your `raidboss.js` .

> seems to break Raidboss >

like what? crashing ACT / throwing errors on console?

**Comment by quisquous** [comment]
Are you still having trouble with this?

**Comment by quisquous** [comment]
I'm going to close this old bug for now.  Please leave a comment if this is still happening.
