### ISSUE TITLE
Add a Way for TriggerSets to Initialize Data

### ISSUE THREAD

**Issue by panicstevenson** [quisquous/cactbot#3071]
## Summary

As mentioned at the end of [this comment](https://github.com/quisquous/cactbot/pull/2880#issuecomment-855293396), it would be helpful to have a way to let triggersets define what is guaranteed inside data on initialization. I don't think this is necessary before converting other triggers to TypeScript, but it might create more work than necessary if it's not solved.

The problem is that an individual triggerset's data looks like this:
```ts
export interface Data extends RaidbossData {
  fieldOne?: { [key: string]: string };
}
```
where fieldOne isn't guaranteed to exist, leading various triggers to inspect if `fieldOne` is undefined before doing any sort of logic on it. TypeScript won't actually guard here; for instance:
```ts
export interface Data extends RaidbossData {
  fieldOne: { [key: string]: string };
}
```
won't throw an error, but it would be more correct to add a way to initialize variables we want to be initialized, for example:
```ts
const triggerSet: TriggerSet<Data> = {
  init: ((data: RaidbossData) => {
    return {
      ...data,
      fieldOne: {},
    };
  }),
  . . .
}
  ```

**Comment by valarnin** [comment]
Maybe modifying `TriggerSet`'s typedef in `trigger.d.ts` as follows:

```typescript
export type TriggerSet<Data extends RaidbossData> = {
  // ZoneId.MatchAll (aka null) is not supported in array form.
  zoneId: ZoneId | number[];
  resetWhenOutOfCombat?: boolean;
  overrideTimelineFile?: boolean;
  timelineFile?: string;
  timeline?: TimelineFunc;
  triggers?: NetRegexTrigger<Data>[];
  timelineTriggers?: TimelineTrigger<Data>[];
  timelineReplace?: TimelineReplacement[];
  timelineStyles?: TimelineStyle[];
  initData?: (data: RaidbossData) => Data;
}
```

This would allow the following in `t1.ts`, for example:

```typescript
export interface Data extends RaidbossData {
  started?: boolean;
}

const triggerSet: TriggerSet<Data> = {
  initData: (data: RaidbossData): Data => {
    return {
      started: false,
      ...data,
    };
  },
  zoneId: ZoneId.TheBindingCoilOfBahamutTurn1,
```

Upon looking at this, it might make sense for every templated `Data` parameter in `trigger.d.ts` to instead be `Data extends RaidbossData`?

**Comment by panicstevenson** [comment]
So, I think the difficult part here is what happens in popup text with multiple triggersets being loaded? A simple example is: What happens when you load t1.ts and general.ts, since they both should be active (assume for a second that general.ts also initializes some data (and that it got converted to typescript)).

**Comment by valarnin** [comment]
I think there's a general assumption here that each TriggerSet should only be concerned with its own Data type. Right now, even with 0 changes, before the typescript conversion, if a trigger in general.js and a trigger in t1.js both used the same data property, they would conflict. I don't think there's a good way to prevent this in general without essentially proxy-izing the `RaidbossData` properties and then having a new instance of TriggerSet-specific Data per TriggerSet, and that gets ugly to track pretty quick.

As such, when the change to PopupText to support `initData` was made, essentially on zone load when building `this.triggers` etc, it would call `initData` for each valid TriggerSet it's loading. Therefore, only the TriggerSets that are currently valid are loaded, and the state of `data` remains as it was before.

**Comment by valarnin** [comment]
For example, a naive implementation in PopupText might look like:
```typescript
      if (this.options.Debug) {
        if (set.filename)
          console.log('Loading ' + set.filename);
        else
          console.log('Loading user triggers for zone');
      }

      // Initialize data for this trigger set if needed
      if (set.initData)
        set.initData(this.data);

      // Adjust triggers for the parser language.
      if (set.triggers && this.options.AlertsEnabled) {
```

**Comment by quisquous** [comment]
> For example, a naive implementation in PopupText might look like:

A couple of tiny thoughts, but Data gets reset without reloading timelines, so I think we'd have to store an array of init functions, and chain the data object through them (in case initData recreates it, as per the initial comment's `init` function) during reset.

> I think there's a general assumption here that each TriggerSet should only be concerned with its own Data type. Right now, even with 0 changes, before the typescript conversion, if a trigger in general.js and a trigger in t1.js both used the same data property, they would conflict

Yeah, I think that's my assumption.  Each trigger set only cares about its own trigger set and their properties shouldn't conflict.  PopupText deals in `RaidbossData` while each trigger file deals in its own `Data extends RaidbossData`.  There's very few times (general being the only one?) where cactbot will load multiple triggersets at once in a zone.

**Comment by panicstevenson** [comment]
\<insert where I wrote what quisqous beat me to posting>

Potentially a sufficient solution here is to store them off in a list (cleared in ReloadTimelines) and just apply them in order from there, such that in Reset() this.data just rolls through all the set.initData and has the final result.

**Comment by valarnin** [comment]
That might make it a bit more complex because `Reset` is called before triggerSets are looped through in `ReloadTimelines`, probably there needs to be a separate `resetData` method that's called in both `Reset` and at the end of `ReloadTimelines`?

**Comment by quisquous** [comment]
Are you suggesting an alternative where we generate an initial `Data` object during `ReloadTimelines`, but then save a copy of it that we can copy and reuse during `Reset`, rather than saving the set of init functions?

**Comment by valarnin** [comment]
No, I'm suggesting that:

1. Add `dataInitializers: ...[]` as a property to PopupText to store current initializers, default to empty array
2. `ReloadTimelines` sets `dataInitializers` to empty array before calling `Reset`
3. `ReloadTimelines` populates `dataInitializers` as it loops over `triggerSets`
4. `ReloadTimelines` calls `resetData` at the end of the function
5. `Reset` calls `resetData`

It's cleaner to move the call to `Reset` to the end of `ReloadTimelines` but I don't know if that'll cause issues.
