### ISSUE TITLE
ci: label script thinks #3076 is a German translation

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#3078]
Just filing to look at later.

**Comment by valarnin** [comment]
Looks like it was this change, which sort of makes sense?

![image](https://user-images.githubusercontent.com/6119598/121816374-36dc0580-cc49-11eb-8f11-4e6c57906bb9.png)

**Comment by quisquous** [comment]
Oh!  Haha, thank you.  I swear I looked through this like twice and didn't see that.
