### ISSUE TITLE
Question: TypeScript-ize webpack-related files?

### ISSUE THREAD

**Issue by MaikoTan** [quisquous/cactbot#3082]
Webpack [supports configuration files in TypeScript](https://webpack.js.org/configuration/configuration-languages/#typescript), but needs one more `tsconfig-for-webpack.json` and some special environment variables. So I'm not sure if it is worth to TypeScript-ize those files as well.

**Comment by quisquous** [comment]
I think this would make editing that file nicer because all of the configuration would be typed, so it seems like a good thing.

**Comment by panicstevenson** [comment]
I'm in favor of it; I think overall most files should aim to be TypeScript where they can be? I think the main things that come to mind that would not be good candidates are ESLint rules and maybe GitHub actions?

**Comment by MaikoTan** [comment]
Yeah, I think this can be done after #3074 landed.
