### ISSUE TITLE
Overlay stops updating when game in focus

### ISSUE THREAD

**Issue by gaogaostegosaurus** [quisquous/cactbot#309]
Hello,

I'm having an issue where Cactbot appears to stop updating itself after a few seconds. I load the test module and it will rapidly show changes in position for a few seconds, but after that the reported position freezes along with everything else (MP and such won't update). I can apparently force it to check again by alt-tabbing out or changing jobs, but it then stops working again within a few seconds.

If I run around with the XIV window not in focus, the position and such will update without issue (as far as I know) but at a much slower rate. 

Not sure if this is something to do with my machine, but I figured I'd ask in case there's something I overlooked. Thank you!

**Comment by quisquous** [comment]
Hmm.  This is very curious.  Cactbot treats itself as active when the the process id called ffxiv_dx11 is the foreground window.

If you open up task manager in Windows, are there multiple processes with that name? Are you using any sort of weird Windows window manager or things that might make the window not think that it's the foreground?

If you can't find anything in task manager, I'll make you a custom build that spits out the process id that it is following and we can make sure that it's finding the right process.  Past that, I'm not sure what else to do.

**Comment by gaogaostegosaurus** [comment]
So again, not sure if this is some weird setting (or screw up...) on my system or not, but I figured it'd be useful information anyone that might run into this issue. I don't know if this is something that is "fixable" from the plugin side (but if it is, let me know so I can feel like I contributed =p).

There's something strange going on on my system where XIV is not obeying the framerate limit I set. When XIV shoots off into the 100+FPS range and the GPU hits 90-100%, overlays stop working, but when the GPU load falls they start working again. From the Task Manager view, it looks like the overlay uses just a little bit of GPU to display so if it has no space it just decides to quit updating. Additionally, I had the option set where it would lower the framerate when XIV wasn't in focus, which explains why the overlays worked a lot more consistently when it was out of focus.

I am almost positive frame limiting was working before which explains why I had no (or at least fewer? I'm not sure now) problems with the overlay prior to very recently, so for now I'm just trying to figure out why nothing is paying attention to the FPS limit anymore. ┐(´д｀)┌

**Comment by gaogaostegosaurus** [comment]
CPU usage looked (and looks) normal. 

For anyone that sees similar issues, I turned on Chill in my AMD settings for FFXIV specifically (made a profile for it) and that seems to have solved my issues with cactbot sporadically stopping - I presume anything that limits normal GPU load to under 90% would have a similar result.

**Comment by quisquous** [comment]
Excellent.  Thanks for the update! :+1:  I will point people to this if I ever see this happening again.
