### ISSUE TITLE
emulator: loaded bozja logs and game player in bozja will bolck forever

### ISSUE THREAD

**Issue by Trim21** [quisquous/cactbot#3094]
re-produce:
1. open act
2. teleport to bozja
3. load a log with bozja
4. refresh emulator

and you will see trying to load bozja trigger file forever

**Comment by valarnin** [comment]
That's, uhh, interesting. Any Bozja log will work, it doesn't have to have fights or anything?

**Comment by Trim21** [comment]
I'm not sure, at least this could re-produce it.

https://github.com/Trim21/actions-cron/releases/download/1/Network_20806_20210614.2021.06.14.log.7z

**Comment by valarnin** [comment]
Being caused by this, but not sure why yet.

```js
  timelineTriggers: [
    {
      id: 'Bozja South Castrum Lyon Winds\' Peak',
      regex: /Winds' Peak/,
      beforeSeconds: 5,
      response: Responses.knockback(),
    },
  ],
```

**Comment by valarnin** [comment]
For reference, it's actually working, it just thinks that timeline trigger is being fired for every single log line.
