### ISSUE TITLE
Raidboss

### ISSUE THREAD

**Issue by beefsuprem** [quisquous/cactbot#311]
Is raidboss working after the patch? I loaded up the test overlay and it was showing my position and hpmp and everything. So I switched to tank and provoked a dummy and no pop up on cactbot. Log says there was an unknown job action.

**Comment by beefsuprem** [comment]
That makes sense. Mechanic countdowns for bosses still work. Just the ability triggers that don't work.

**Comment by sparkymotive** [comment]
ACT update is live, hopefully it works properly now. Timeline was wonky last night in o11s and fully broken in o12s.  I'm at work now so I can't test it.

**Comment by beefsuprem** [comment]
I see. I did the summerford test last night and things seemed normal. Hopefully after the patch the raid timelineswill be right. I'll find out tonight.

**Comment by quisquous** [comment]
Thanks! Let me know if 0.9.0 doesn't fix this and open up another issue.
