### ISSUE TITLE
Have TriggerSet Matches Determine the Correct Parameters

### ISSUE THREAD

**Issue by panicstevenson** [quisquous/cactbot#3119]
## Summary

Currently, trigger functions use `MatchesAny` for their matches parameter, which means that you can run into places like [this](https://github.com/quisquous/cactbot/blob/main/ui/raidboss/data/02-arr/raid/t8.ts#L57):

```ts
infoText: (data, matches: MatchesAbility, output) => {
  if (matches.target && matches.target in data.landmines)
    return;
  const num = Object.keys(data.landmines).length + 1;
  return output.landmine!({ num: `${num}` });
},
```

Where, although the code is specifying  that it is a `MatchesAbility`, it states that `matches.target` could potentially be undefined, leading to an additional truthy check that wasn't present in the JavaScript version.

After playing around in the trigger type definition file, I removed `MatchesAny` from `type Matches<Param>`:
```ts
export type Matches<Params> = { [s in Params]: string };
```
And updated the `TriggerOutput`, `PartialTriggerOutput`, and `TriggerFunc` types to be:
```ts
// The output of any non-response raidboss trigger function.
export type TriggerOutput<Data, T> =
    T extends MatchesAbility ? undefined | null | LocaleText | string | number | boolean |
    ((d: Data, m: MatchesAbility, o: Output) => TriggerOutput<Data, MatchesAbility>) :
    undefined | null | LocaleText | string | number | boolean |
    ((d: Data, m: Matches, o: Output) => TriggerOutput<Data, Matches>);

// Used if the function doesn't need to return an en key
export type PartialTriggerOutput<Data, T> =
    T extends MatchesAbility ? undefined | null | Partial<LocaleText> | string | number | boolean |
    ((d: Data, m: MatchesAbility, o: Output) => PartialTriggerOutput<Data, MatchesAbility>) :
    undefined | null | Partial<LocaleText> | string | number | boolean |
    ((d: Data, m: Matches, o: Output) => PartialTriggerOutput<Data, Matches>);

// The type of a non-response trigger field.
export type TriggerFunc<Data, T, Return> =
    T extends MatchesAbility ? (data: Data, matches: MatchesAbility, output: Output) => Return :
    (data: Data, matches: Matches, output: Output) => Return;
```

Which, with the conditional typing, I can now remove the `matches.target` from the trigger's infoText function conditional, but I don't think copying and pasting the type conditional for each Matches type is the best way about this. I'm curious if anyone has any other thoughts or ideas to make this logic cleaner, either through type conditionals or something else entirely.

**Comment by valarnin** [comment]
I'm looking into options for this. Let's see if I can find another good book in the wizard's library 😄

**Comment by valarnin** [comment]
Well, I've managed to completely break node so far, and I have no idea how.

**Comment by valarnin** [comment]
I think this can be closed now? I guess I forgot to mention in the new PR that it closes this.
