### ISSUE TITLE
"Has no regex property specified" error

### ISSUE THREAD

**Issue by Seferex** [quisquous/cactbot#312]
Hi, first of all: very very very nice work!

My cactbot works fine, but if i go in the logs of act, i keep getting this info:

10/01/2019 02:35:48: Info: InitPlugin: PluginDirectory = C:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin
10/01/2019 02:35:48: Info: LoadAddons: C:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin\addons\CactbotOverlay.dll
10/01/2019 02:35:48: Info: LoadAddons: Cactbot.OverlayAddonMain: Initialized
10/01/2019 02:35:49: Info: InitPlugin: Initialized.
10/01/2019 02:35:51: Info: RaidBoss: cactbot: 0.9.0.0 C:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin\addons\CactbotOverlay.dll
10/01/2019 02:35:51: Info: RaidBoss: OverlayPlugin: 0.3.4.0 C:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin\OverlayPlugin.Common.dll
10/01/2019 02:35:51: Info: RaidBoss: FFXIV Plugin: 1.7.2.5 C:\Program Files (x86)\Advanced Combat Tracker\FFXIV_ACT_Plugin.dll
10/01/2019 02:35:51: Info: RaidBoss: ACT: 3.3.3.258 C:\Program Files (x86)\Advanced Combat Tracker\Advanced Combat Tracker.exe
10/01/2019 02:35:51: Info: RaidBoss: Language: en
10/01/2019 02:36:35: Info: RaidBoss: BrowserConsole: Trigger undefined: has no regex property specified (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/cactbot/ui/raidboss/popup-text.js, Line: 115)
10/01/2019 02:36:35: Info: RaidBoss: BrowserConsole: Trigger undefined: undefined regexEn (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/cactbot/ui/raidboss/popup-text.js, Line: 120)
10/01/2019 02:36:35: Info: RaidBoss: BrowserConsole: /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details. (Source: , Line: 0)
10/01/2019 02:36:35: Info: RaidBoss: BrowserConsole: Trigger undefined: has no regex property specified (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/cactbot/ui/raidboss/popup-text.js, Line: 115)
10/01/2019 02:36:35: Info: RaidBoss: BrowserConsole: Trigger undefined: undefined regexEn (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/cactbot/ui/raidboss/popup-text.js, Line: 120)
10/01/2019 02:37:09: Info: RaidBoss: BrowserConsole: Trigger undefined: has no regex property specified (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/cactbot/ui/raidboss/popup-text.js, Line: 115)
10/01/2019 02:37:09: Info: RaidBoss: BrowserConsole: Trigger undefined: undefined regexEn (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/cactbot/ui/raidboss/popup-text.js, Line: 120)
10/01/2019 02:37:21: Info: RaidBoss: BrowserConsole: Trigger undefined: has no regex property specified (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/cactbot/ui/raidboss/popup-text.js, Line: 115)
10/01/2019 02:37:21: Info: RaidBoss: BrowserConsole: Trigger undefined: undefined regexEn (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/cactbot/ui/raidboss/popup-text.js, Line: 120)
10/01/2019 02:37:51: Info: RaidBoss: BrowserConsole: Trigger undefined: has no regex property specified (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/cactbot/ui/raidboss/popup-text.js, Line: 115)
10/01/2019 02:37:51: Info: RaidBoss: BrowserConsole: Trigger undefined: undefined regexEn (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/cactbot/ui/raidboss/popup-text.js, Line: 120)
10/01/2019 02:46:00: Info: RaidBoss: BrowserConsole: Trigger undefined: has no regex property specified (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/cactbot/ui/raidboss/popup-text.js, Line: 115)
10/01/2019 02:46:00: Info: RaidBoss: BrowserConsole: Trigger undefined: undefined regexEn (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/cactbot/ui/raidboss/popup-text.js, Line: 120)

Is there any way to get rid of it?

**Comment by quisquous** [comment]
This is very surprising to see.  What is in your **cactbot/user/raidboss.js** file, if anything?

**Comment by quisquous** [comment]
Ah, I see.  You just copied the raidboss-example.js over.  You should just delete everything from ` A set of nicknames to use for players,` all the way to the end of the file, I think.

**Comment by Seferex** [comment]
Ok perfect, i dont get that error anymore! 
I do only get this: 

10/01/2019 19:18:09: Info: RaidBoss: BrowserConsole: /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details. (Source: , Line: 0)

And for the test? Is it normal that it does not work anymore?

**Comment by quisquous** [comment]
Yeah, that's normal.  There's nothing I can do about that error.  I'm going to close this, since the original issue is fixed.
