### ISSUE TITLE
Feature Request: Spectral Current (countdown) timer for Ocean Fishing

### ISSUE THREAD

**Issue by hreffero** [quisquous/cactbot#3123]
I'm not sure how hard is this to make but I always wanted this for the fishing plugin

Just a simple countdown how much left from the Spectral Current (sometimes I forget to check the exact time when it started either on the Duty timer or the Ocean Fishing window)

The Spectral Current has 2 lengths
- 2 minutes if it appears normally
- 3 minutes if there were no Spectral Current at the previous stop or if the previous one was shortened (spawned after 2:30 were left on the timer thus it wasn't the full 2 minutes length). This effect does not accumulate so even if the first 2 stops had no Current the 3rd one will be still 3 minutes. These were introduced in 5.4 [1]

Spectral Current has 3 different trigger text from Foerzagyl (the captain on the ship), appears as NPC/event talk in the chat log per XIVAPI [2]
-1st stop: Looks like PLAYERNAME/SERVER fished up Lady Luck herself! Here comes a spectral current!
-2nd stop: We've got PLAYERNAME/SERVER to thank for this spectral current! No one's going home hungry tonight!
-3rd stop: A fish ain't all PLAYERNAME/SERVER pulled out of the water! Here comes a spectral current!

So yeah that's all I know. Would be nice to have but once again I'm not sure how hard is this to make.

1, [5.4 patch notes.](https://na.finalfantasyxiv.com/lodestone/topics/detail/230f6e0af3536f9a40654d783c8c2f1094131070) _In the event a spectral current does not appear at a destination, or a spectral current appears shortly before traveling to a new destination, the next spectral current to appear will have an increased duration._

2, https://github.com/xivapi/ffxiv-datamining/blob/master/csv/InstanceContentTextData.csv

**Comment by valarnin** [comment]
Can you provide log files with both length events and all three chat log events?

**Comment by hreffero** [comment]
Working on it!

This is a log file with normal (2 minutes) length events and 2 messages (1st and 2nd stop)

1st stop: Looks like ____ fished up Lady Luck herself! Here comes a spectral current!
2nd stop:  We've got ____ to thank for this spectral current! No one's going home hungry tonight!

https://send.vis.ee/download/30b49f8be1aa90cd/#wpnnbKTMC_xGoUnhEhL2rQ

**Comment by hreffero** [comment]
Here is a log with 1 short (2nd stop, spawned when ~1:30 were left) and 1 extended Spectral Current (3rd stop, 3 minutes long)

Also the 3 messages are always the same, considering the stop. Edited my first comment.

https://send.vis.ee/download/a394920a864036fd/#EGKvFOucPvbOs7HVk3pEvQ

**Comment by Neraud** [comment]
I would love this feature too.
Ideally, with a timer that handles short/long windows. But just a simple couple of timers (displayed for both short and long) would also work.

Do you need any help to capture logs ?

**Comment by quisquous** [comment]
Sorry, I am not planning on adding any more fishing features.
