### ISSUE TITLE
BUG: P2 `UCU Bahamut's Claw` is missing in real game

### ISSUE THREAD

**Issue by Trim21** [quisquous/cactbot#3126]
![image](https://user-images.githubusercontent.com/13553903/122419580-99246580-cfbd-11eb-9fcc-cf73d88c327f.png)

```JS
    {
      id: 'UCU Bahamut\'s Claw',
      regex: /Bahamut's Claw x5/,
      beforeSeconds: 5,
      // It's tough to track who this is on, especially for the first one.
      // Both tanks should care about the tankbuster because they can throw
      // mitigation on the other, so just always play this for both tanks.
      condition: Conditions.caresAboutPhysical(),
      suppressSeconds: 1,
      response: Responses.tankBuster(),
    },
```

there is a recent change that rename prop `conditions` to `condition`, but I didn't think it's relative.

**Comment by Trim21** [comment]
re-production log https://github.com/Trim21/actions-cron/releases/download/1/Network_20806_20210617.log

**Comment by Trim21** [comment]
@valarnin 
```diff
diff --git a/ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.js b/ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.js
index cc2543f1..76b6ecbc 100644
--- a/ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.js
+++ b/ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.js
@@ -17,10 +17,15 @@ export default {
       // It's tough to track who this is on, especially for the first one.
       // Both tanks should care about the tankbuster because they can throw
       // mitigation on the other, so just always play this for both tanks.
-      condition: Conditions.caresAboutPhysical(),
+      // condition: Conditions.caresAboutPhysical(),
       suppressSeconds: 1,
       response: Responses.tankBuster(),
     },
+    {
+      id: 'UCU Bahamut\'s Claw 2',
+      regex: /Bahamut's Claw x5/,
+      infoText: 'debug message tank tankBuster',
+    },
   ],
   triggers: [
     // --- State ---
```
![image](https://user-images.githubusercontent.com/13553903/122422768-ff11ec80-cfbf-11eb-8ea3-cf257d980e8a.png)

Another but, I'm not sure if these are relative, either.

**Comment by valarnin** [comment]
Is this specifically raidemulator, or does this happen in normal raidboss too?

**Comment by Trim21** [comment]
> Is this specifically raidemulator, or does this happen in normal raidboss too?

this issue is about trigger it self I guess.

https://github.com/quisquous/cactbot/issues/3126#issuecomment-863317570 is about raidemulator, or I should separate them?

**Comment by MaikoTan** [comment]
What do you mean relative?

**Comment by Trim21** [comment]
> What do you mean relative?

same reason? the reason of one bug causes another?

**Comment by valarnin** [comment]
These are two separate issues but I'm working on a PR for the emulator issue now so I don't think it's worth opening a new issue for it.

**Comment by valarnin** [comment]
After the fix for timeline triggers, claws are visible in emulator for at least the first pull of the log file you posted?

![image](https://user-images.githubusercontent.com/6119598/122438206-774cc380-cf68-11eb-940c-9344898a3012.png)

**Comment by Trim21** [comment]
I updated the title

**Comment by Trim21** [comment]
Test in-game again, only second Claw is missing.

**Comment by Trim21** [comment]
TEA trigger is missing too 
 https://github.com/quisquous/cactbot/blob/8219a6fe5e7eef04efe4a02735d8fad7d9b3b564/ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.js#L321-L327

**Comment by valarnin** [comment]
Wonder if it's something weird with `suppressSeconds`?

**Comment by Trim21** [comment]
> Wonder if it's something weird with `suppressSeconds`?

Yes, I can re-produce it with dummy now.
```ts

import { TriggerSet } from './cactbot';
import { RaidbossData } from '../../types/data';

interface Data extends RaidbossData {
  times: number;
}

export const trigger: TriggerSet<Data> = {
  zoneId: ZoneId.MiddleLaNoscea,
  timeline: [
    `5 "test"`,
    `10 "test"`,
    `15 "test"`,
  ],
  timelineTriggers: [
    {
      id: 'trim21 test refresh',
      regex: /Death/,
      run() {
        location.reload();
      },
    },
    {
      id: 'trim21 test',
      regex: /test/,
      preRun(data) {
        data.times = data.times ?? 0;
        data.times++;
      },
      suppressSeconds: 1,
      beforeSeconds: 3,
      infoText(data) {return `test message ${data.times}`;},
    },
  ],
};

Options.Triggers.push(trigger);
```

**Comment by valarnin** [comment]
Alright. I'm currently working on something else, if someone else wants to debug this one, otherwise I'll let you know when I start looking into it.

**Comment by Trim21** [comment]
> Alright. I'm currently working on something else, if someone else wants to debug this one, otherwise I'll let you know when I start looking into it.

I'm working on it.

**Comment by Trim21** [comment]
I'm not sure why, but many `currentTime` of `Timeline` never change with time.
