### ISSUE TITLE
E12S Double Aero Finder still has tts

### ISSUE THREAD

**Issue by Trim21** [quisquous/cactbot#3136]
is the purpose of this `tts: null` to make it silent?

This still get tts.

https://github.com/quisquous/cactbot/blob/961a1ba7321f96d5d475b449b75b016a3d0c8b8e/ui/raidboss/data/05-shb/raid/e12s.js#L1607-L1616

I guess the reason is here, we didn't distinguish `null` and `undefined`

https://github.com/quisquous/cactbot/blob/ed708582d715cf304e354b2631f9766b175f12ae/ui/raidboss/popup-text.ts#L1183-L1190

**Comment by quisquous** [comment]
> is the purpose of this tts: null to make it silent?

Yeah, that's correct.

**Comment by Trim21** [comment]
maybe tts should be `''` here?

**Comment by quisquous** [comment]
> maybe tts should be `''` here?

I think there are maybe user triggers that could be using `null` at this point, so I would argue to be backwards compatible by supporting what already exists unless it's a pain to do so.

**Comment by Trim21** [comment]
> I think there are maybe user triggers that could be using `null` at this point, so I would argue to be backwards compatible by supporting what already exists unless it's a pain to do so.

I mean just change this trigger to slient it.

**Comment by quisquous** [comment]
I guess I'm saying that this is a bug in popup-text that needs to get fixed.  It makes more sense to me to fix the underlying popuptext bug (which affects a few other triggers too) than to change this tts value.
