### ISSUE TITLE
dps overlay not working after OverlayPlugin update

### ISSUE THREAD

**Issue by Khuzvhan** [quisquous/cactbot#314]
![copke8q](https://user-images.githubusercontent.com/14275181/50937662-d6cf4c80-145b-11e9-8a56-6cbd4ca89186.png)

the default overlay is working fine but cactbot can't get data.

dps.html is correctly setted

**Comment by quisquous** [comment]
What is your dps update rate set to in the config for this overlay?

**Comment by Khuzvhan** [comment]
idk where to check this and don't have a clue how these things work =/

but i've seen the dps.html works if i create a New tab as Mini Parse instead of Cactbot.
![f0w5cja](https://user-images.githubusercontent.com/14275181/50939645-eacb7c00-1464-11e9-96a2-4a9ef8ca56b8.png)


1st was Created as Mini Parse 2nd as Cactbot. both with the same html. cactbot one can't get data

**Comment by werewolfboy13** [comment]
![image](https://user-images.githubusercontent.com/43587009/50940367-3c184300-1446-11e9-8eb4-6e122581b2b8.png)
This is what he is talking about.

**Comment by Khuzvhan** [comment]
i see
this option only exists in a Cactbot Tab and was set to 0 after updating apparently.
thanks for your quick responses and attention.
everything works fine now.

**Comment by werewolfboy13** [comment]
I also have a problem from time to time where it doesn't sync on that one. Rebooting usually helps.

**Comment by werewolfboy13** [comment]
Also wondering where did you get that ping overlay?

**Comment by Khuzvhan** [comment]
here [https://github.com/Noisyfox/ACT.FFXIVPing](url)

**Comment by werewolfboy13** [comment]
Thanks!

**Comment by quisquous** [comment]
Sorry, I changed it to 0 this release because it affects performance and many people didn't change it from 3 to 0 for non-dps overlays.  I added a belated note to the release about this.  Sorry for the confusion!
