### ISSUE TITLE
Emulator bug showing sound instead of alertText in analyzed list

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#3157]
Use log from https://github.com/quisquous/cactbot/issues/3156#issue-926788664
Use patch from https://github.com/quisquous/cactbot/commit/dbde1ec4f6541fc1eea43aa831e16f73d6bd2a90

![image](https://user-images.githubusercontent.com/462317/122859686-3db1ea80-d2d1-11eb-870a-d0841155b800.png)
![image](https://user-images.githubusercontent.com/462317/122859704-473b5280-d2d1-11eb-91de-f59de4fdfbae.png)

The alert works fine during playback.

**Comment by valarnin** [comment]
From that patch:

```js
          if (data.holyTargets.includes(data.me)) {
            ret.alertText = output.getOut();
            ret.infoText = output.othersStackOnHoly({ player: data.ShortName(stackTarget) });
          }
```

Is this supposed to result in one alert or two being displayed?

**Comment by quisquous** [comment]
https://github.com/quisquous/cactbot/blob/main/ui/raidboss/popup-text.ts#L1337-L1340 sets the sound if not set before.  The order of evaluation (alarm > alert > info) determines which one gets set first.
