### ISSUE TITLE
Text/Sound alerts not working

### ISSUE THREAD

**Issue by doodlev** [quisquous/cactbot#317]
pretty sure this is since the new update, the text and sound notifications from things like provoke, shirk, and tank actions like hallowed ground, holmgang and living dead no longer showing up or getting sound, i had a look i have no errors that i can see...

**Comment by doodlev** [comment]
yeah both have been updated, worked fine before the update

**Comment by doodlev** [comment]
update, i was just in ultimate, text and sound alerts working for things like garuda screech and fetters in ifrit, its just the actions ones that are not working

**Comment by quisquous** [comment]
I'm guessing that you're a tank as well? (They don't show up for non-tanks.)

In uwu, do you get slipstream callouts? Those are tank-specific.

**Comment by doodlev** [comment]
omg, im so sorry i didnt hit enter, yes i am a tank, the issue lied somewhere else tbh im not sure where i ended up reinstalling both act and cactbot 9.0 at the time and it started to work again, i did update this saying it was working again after both reinstall,  again sorry

**Comment by quisquous** [comment]
No need for apologies! Thanks for the update, and glad you got it working.  Sorry I took so long to get back to this, it's been a busy few weeks.

**Comment by doodlev** [comment]
i could only imagine, thanks tho, love your work :)
