### ISSUE TITLE
raidboss.js "matches" returns empty object

### ISSUE THREAD

**Issue by Webberjo** [quisquous/cactbot#3203]
## Description

After updating cactbot to the latest version, custom triggers I've written in my raidboss.js file are no longer working. Logging the return data, I'm seeing `matches` is an empty object instead of the regex capture info.
```js
Options.Triggers = [
  {
    zoneRegex: /.*/,
    triggers: [
      {
        regex: /.*/,
        alertText: function(data, matches) {
          console.log(matches); // Logs {}
          return;
        }
      }
    ]
  }
];
```

**Comment by valarnin** [comment]
What are you expecting here in `matches`? Are you expecting a `RegExpExecArray` with no groups? Because that RegExp doesn't have any capturing groups.

**Comment by MaikoTan** [comment]
Because the "matches" variable is actually the "captured groups", i.e. `regex.exec(log).groups`.
The regex you have written `/.*/` has no capture groups, if you change it as `/(?<log>.*/`, then you should get an object which has a string property that contains the whole log line.

**Comment by Webberjo** [comment]
I used to use `.*` to capture everything, and `matches` would contain an array with a single index containing the full string of the capture. I've never had to use `?<log>` to get the result of the regex.

Even something as simple as `/.*(a|b).*/` returns an empty object, despite using a capture group.

**Comment by MaikoTan** [comment]
Yeah, as far as I know, there are only "named capture groups" that would be recorded in.

**Comment by valarnin** [comment]
The old logic before PopupText was converted to ts was to replace the RegExpExecArray with `.groups` if it was set but leave it intact if not, which resulted in this object getting passed to triggers:

![image](https://user-images.githubusercontent.com/6119598/123549148-ae279400-d735-11eb-9fb5-8561a7e07777.png)

Maybe we need a special handler for the `'None'` type case which passes through this type instead?
