### ISSUE TITLE
Cloud Deck Extreme (Diamond Weapon Ex) - triggers not displaying

### ISSUE THREAD

**Issue by wexxlee** [quisquous/cactbot#3216]
## Description

Alert triggers (text and sounds) are not displaying for Cloud Deck Extreme (Diamond Weapon).  Timeline and other cactbot modules (jobs & oopsy) are working fine in the fight, and alerts seem to be working properly in every other fight.

## Additional information

Opening an issue per advice from discord.  Troubleshooting steps so far:
- Deleted overlayplugincache folder, removed cactbot plugin, deleted cactbot-0.xx-x folders, and reinstalled plugin per install guide.
- Confirmed fight is listed as supported content for both timeline and triggers
- Verified/reset cactbot user directory in UI

Also, once I completed the reinstall, I noticed that when I loaded the fight for the first time, I received an 'info' alert sound (with no accompanying text) for the first fight mechanic, but nothing after that.  No alert sound at all for the second fight.   When I reset the user directory to the default and tried again, same thing - info alert sound for the first mechanic, but then nothing again.

**Comment by valarnin** [comment]
Can you confirm a few other things, please?

1. What is the game language set to?
2. What are your alert settings set to?
3. If you drop the network log into raidemulator (see https://github.com/quisquous/cactbot#raidboss-emulator), does it happen there as well?

**Comment by quisquous** [comment]
Even more questions:
1. Are there any errors in the OverlayPlugin log window when this happens?
2. Does `/cd 5` in Summerford Farms give you multiple alerts?

**Comment by wexxlee** [comment]
Thanks - here's the answers:

1.  English
2.  English (en)
3.  In raidemulator using the fight log, all of the instances I ran of the fight today seem to load and display the correct alert text and sounds
4. No errors appear in the OverlayPlugin log pane in ACT
5. I do get multiple alerts in Summerford - the typical countdown alert, and the various fight alert texts/sounds as normal.

**Comment by quisquous** [comment]
Hmm.  That's definitely very odd.  I don't have any great ideas offhand, but I'll let you know if I think of anything.  I would definitely keep an eye on the OverlayPlugin log pane if this happens again.

**Comment by wexxlee** [comment]
It's a recurring issue - happens every time.  Have never had text alerts for this fight.  Tried again today and repro'd the issue - no text alerts. Nothing in the overlayplugin log pane either, although RaidEmulator shows the alerts from the log.  And this only seems to be happening with this one particular fight.

**Comment by valarnin** [comment]
Go to your overlay settings in OverlayPlugin, hit the `Open Devtools` button, go to the `Source` tab, and on the right enable the stop-sign looking option to pause on exceptions and then check the box to pause on caught exceptions, then try loading into the zone and see if it pauses. If so, screenshot the devtools window and hopefully we'll be able to help.

![image](https://user-images.githubusercontent.com/6119598/124067404-5a080280-da08-11eb-8c6f-cf3f2917e3e7.png)

Make sure to turn these options off afterwards and then close dev tools and reload the overlay with the appropriate button in ACT.

**Comment by wexxlee** [comment]
Sorry for the long delayed response.  I tried the above and wasn't seeing any caught exceptions.  I did a complete reinstall of ACT + Cactbot last night, and it seems to be working now, so I'm guessing whatever it was local config weirdness.  Really appreciate the help!

**Comment by quisquous** [comment]
Glad you got it fixed!
