### ISSUE TITLE
New Weird Issue

### ISSUE THREAD

**Issue by markynatorka** [quisquous/cactbot#323]
So today I started to get this weird issue where scrollbars started to appear and the overlays seem distorted. Not sure why this is happening.
![image](https://user-images.githubusercontent.com/42062385/51083349-0c548e00-1719-11e9-8e25-542d3b520539.png)
![image](https://user-images.githubusercontent.com/42062385/51083353-18405000-1719-11e9-9220-2337c397e582.png)

Even the fonts seem to have somehow changed.
Also some of the overlays dont seem to be updating anymore for me such as  the eureka when I'm out of eureka, it still seems to show up.

**Comment by quisquous** [comment]
This looks like the CSS isn't loading.  Do you have any errors in your plugin log?  If you hit the `Show devtools` button and click `console`, are there any errors there?

**Comment by markynatorka** [comment]
So i dunno how, but the issue seems to have fixed itself, thank you for taking the time to reply though! :)

**Comment by quisquous** [comment]
Ok! Glad it got sorted out.  If it ever happens again, let me know if you see any errors or figure out how to reproduce the bug.
