### ISSUE TITLE
Cactbot language is not set properly.

### ISSUE THREAD

**Issue by Jaehyuk-Lee** [quisquous/cactbot#3256]
![K-003](https://user-images.githubusercontent.com/4695371/124594142-6a9dfa00-de9a-11eb-9135-e82fee6a8782.png)

As you see in the log, the parser language is "Korean". But Cactbot UI is shown in English, and this includes Alerts.

**Comment by MaikoTan** [comment]
Loos like the commit b4910b6392d0fd147c8adb575c47b8e5b6df02a7 cause the issue.
