### ISSUE TITLE
DrLippe's new raidboss skin

### ISSUE THREAD

**Issue by TheHeroAlfred** [quisquous/cactbot#326]
So I used the new raid skin by adding a line in raidboss.js. It's working fine but the Test bar 1-6 is still there. I couldn't find solution anywhere to get rid of it. Thank you
![image](https://user-images.githubusercontent.com/14954924/51161111-11a60a00-18cc-11e9-942b-659a72a058f4.png)

**Comment by quisquous** [comment]
It looks like you need to click the `Lock overlay` checkbox in ACT for this overlay.  If you do that, it should go away.

**Comment by DrLippe** [comment]
@TheHeroAlfred did `Lock overlay` solve this issue for you?

**Comment by TheHeroAlfred** [comment]
@DrLippe Sadly, no. When I click Lock overlay, the whole cactbot overlay disappears.

**Comment by DrLippe** [comment]
That sounds perfectly normal.
- Place the overlay where you like the Text / Timelines to be, then lock the overlay. 
- The overlay should be invisible now.
- Go to Summerford Farms and type in chat /e Engage!

**Comment by TheHeroAlfred** [comment]
I got it! Thank you so much for your help. I love the minimalist style of this overlay.

**Comment by DrLippe** [comment]
resolved #326

**Comment by quisquous** [comment]
Sorry for the confusion around locking overlays.  For what it's worth, all the cactbot overlays work like this, in that they show some default stuff when unlocked and then expect them to be locked.

Thanks for getting this sorted! :+1:
