### ISSUE TITLE
Daily/Weekly Auto Checklist

### ISSUE THREAD

**Issue by vmwinckler** [quisquous/cactbot#3285]
## Summary

**Based on**  https://accomp.me/ffxiv-daily-weekly-checklist/

I create this simple HTML (incomplete and rustic):

--------------------------------------------------------------------------

<h1>Daily Checklist</h1>
<ul>
	<li>
		<h2>Duty Roulette/Daily Challenges</h2>
		<ul>
			<li><input type="checkbox"> Level 50/60/70 Dungeons</li>
			<li><input type="checkbox"> Leveling</li>
			<li><input type="checkbox"> Trials</li>
			<li><input type="checkbox"> Main Scenario</li>
			<li><input type="checkbox"> Guildheists</li>
			<li><input type="checkbox"> Alliance Raids</li>
			<li><input type="checkbox"> Normal Raids</li>		
			<li><input type="checkbox"> Frontline</li>		
		</ul>
	</li>
	<li><h2>Mini Cactpot <spam>(0/3)</spam></h2></li>
	<li>
		<h2>Daily Hunts (Clan Hunt Boards)</h2>
		<ul>
			<li><input type="checkbox"> A Realm Reborn: Allied Seals</li>
			<li><input type="checkbox"> Heavensward: Centurio Seals</li>
			<li><input type="checkbox"> Stormblood: Centurio Seals</li>
			<li><input type="checkbox"> Shadowbringers: Sack of Nuts</li>			
		</ul>
	</li>
	<li>
		<h2>Beast Tribe Quests</h2>
		<ul>
			<li>Amal’jaa	<spam>(0/?)</spam></li>
			<li>Ixali	<spam>(0/?)</spam></li>
			<li>Kobold	<spam>(0/?)</spam></li>
			<li>Sahagin	<spam>(0/?)</spam></li>
			<li>Sylph	<spam>(0/?)</spam></li>
			<li>Moogle	<spam>(0/?)</spam></li>
			<li>Vath	<spam>(0/?)</spam></li>
			<li>Vanu Vanu	<spam>(0/?)</spam></li>
			<li>Namazu	<spam>(0/?)</spam></li>
			<li>Ananta	<spam>(0/?)</spam></li>
			<li>Kojin	<spam>(0/?)</spam></li>
			<li>Pixie	<spam>(0/?)</spam></li>
			<li>Qitari	<spam>(0/?)</spam></li>
			<li>Dwarves	<spam>(0/?)</spam></li>
		</ul>
	</li>
	<li>
		<h2>Retainer Ventures</h2>
		<ul>
			<li>Retainer XYZ	<spam>Sended</spam></li>
			<li>Retainer ABC	<spam>Waiting</spam></li>			
		</ul>
	</li>
	<li>
		<h2>Grand Company Turn-ins</h2>
		<ul>
			<li>Provisioning	<spam>(0/?)</spam></li>			
		</ul>
	</li>
	<li>
		<h2>Adventurer Squadron</h2>
		<ul>
			<li>Command Mission	<spam>(0/3)</spam></li>			
		</ul>
	</li>
	<li>
		<h2>Treasure Hunts</h2>
		<ul>
			<li><input type="checkbox"> The Dungeons of Lyhe Ghiah</li>
			<li><input type="checkbox"> The Shifting Altars of Uznair</li>
			<li><input type="checkbox"> The Lost/Hidden Canals of Uznair</li>
			<li><input type="checkbox"> The Aquapolis</li> 
		</ul>
	</li>
</ul>
<h1>Weekly Checklist</h1>
<ul>
	<li><h2><input type="checkbox"> Eden’s Verse</li>
	<li><h2>Allagan Tomestones of Allegory <spam>(0/?)</spam></h2></li>
	<li>
		<h2>Alliance Raids</h2>
		<ul>
			<li><input type="checkbox"> The Puppets’ Bunker</li>
			<li><input type="checkbox"> Cracked Stellaclusters</li>
			<li><input type="checkbox"> Puppet’s Coin</li>			
		</ul>
	</li>
	<li>
		<h2>Custom Deliveries (0/12)</h2>
		<ul>
			<li>Ehll Tou – The Firmament	<spam>(0/6)</spam></li>
			<li>Kai-Shirr – Eulmore, The Canopy	<spam>(0/6)</spam></li>
			<li>Kurenai – The Ruby Sea	<spam>(0/6)</spam></li>
			<li>M’Naago – Rhalgr’s Reach	<spam>(0/6)</spam></li>
			<li>Zhloe Aliapoh – Idyllshire	<spam>(0/6)</spam></li>
			<li>Adkiragh – Idyllshire	<spam>(0/6)</spam></li>
		</ul>
	</li>
	<li><h2><input type="checkbox"> Challenge Log</h2></li>
	<li><h2><input type="checkbox"> Wondrous Tails</h2></li>
	<li><h2><input type="checkbox"> Faux Hollows</h2></li>
	<li><h2>Jumbo Cactpot <spam>(0/3)</spam></h2></li>
	<li><h2><input type="checkbox"> Fashion Report</h2></li>
	<li>
		<h2>Weekly Hunts (Clan Hunt Boards)</h2>
		<ul>
			<li><input type="checkbox"> A Realm Reborn: Allied Seals</li>
			<li><input type="checkbox"> Heavensward: Centurio Seals</li>
			<li><input type="checkbox"> Stormblood: Centurio Seals</li>
			<li><input type="checkbox"> Shadowbringers: Sack of Nuts</li>			
		</ul>
	</li>
	<li><h2><input type="checkbox"> The Masked Carnivale</h2></li>
</ul>

--------------------------------------------------------------------------

but idea is create a checklist based on level, job, msq level and others variants and disponibiliser a checklist auto complete for player.

**Comment by quisquous** [comment]
Hi! Thanks for the suggestion.  Unfortunately, I don't think cactbot is a good fit for this sort of idea.  I think this could easily be its own overlay or quicklauncher plugin, and isn't necessarily something that has to be part of cactbot.
