### ISSUE TITLE
UwU Goals Numbering

### ISSUE THREAD

**Issue by Lokidoki8017** [quisquous/cactbot#3299]
I would like to see if you could implement this into catbot or help me set something up to help my group and other group who are stuck at this part. 

## Summary

Brief explanation of the feature you'd like to request.

**Comment by panicstevenson** [comment]
Hey there! I'm unsure what the ask here is. If you're looking for numbering in game, like with the in game markers (1, 2, 3, etc.), then unfortunately that is a line that we refuse to cross within cactbot. There are other plugins that have that functionality, I believe [Triggernometry](https://github.com/paissaheavyindustries/Triggernometry) has the functionality to mark players based off the incoming triggers by sending keypresses to the client, but I can't say for certain.

If you're looking for a callout, there should already be [a trigger](https://github.com/quisquous/cactbot/blob/14d69f56804b9dfda9b6e51a0bf070addf4c6aef/ui/raidboss/data/04-sb/ultimate/ultima_weapon_ultimate.ts#L296) that will call 3 players in order.

**Comment by Lokidoki8017** [comment]
yeah got the tigger that calls out the 3 people, i just call out the names and works out for us. thank you for replying.
