### ISSUE TITLE
Allow the use of TT+Sound+Text at once for raidboss alerts

### ISSUE THREAD

**Issue by 20133774** [quisquous/cactbot#3301]
## Summary
Please allow the use of TT+Sound+Text at once for raidboss alerts, i've been using "Text and Sound" for a while but would love to implement TTS instead of making custom triggers for individual actions.
I would switch to Text + TTS but I'm used to hearing the sounds and they help me quite a lot

**Comment by quisquous** [comment]
To clarify, you want the default info/alert/alarm sounds to play over top of the tts? Wouldn't that make it hard to hear?

If you really want to do this, you can add a `user/raidboss.js` file and add the line `Options.SoundAlert = true;`.  See https://github.com/quisquous/cactbot/blob/main/docs/CactbotCustomization.md#user-directory-overview

**Comment by 20133774** [comment]
I'll give the tweak a go and see how it turns out! thanks for the clarification; I think some might find it difficult to hear but I'm pretty used to hearing both since I had a few custom individual triggers for some mechanics that went off at the same time

**Comment by quisquous** [comment]
I still am not sure I want this as a config ui option, and since there's a path to do this via user config js, I'll close this.
