### ISSUE TITLE
Radar and Custom Monsters not working

### ISSUE THREAD

**Issue by jpdied** [quisquous/cactbot#3307]
## Description

Using the radar-example.js as a base, I've tried creating a Custom Monster for Lighting Sprites but OverlayPlugin outputs the following error:

> [7/16/2021 12:43:48 AM] Error: LoadAddons: CactbotOverlay.dll: System.ArgumentNullException: String reference not set to an instance of a String.
Parameter name: name
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at Cactbot.CactbotEventSource.Start()
   at RainbowMage.OverlayPlugin.Registry.StartEventSource[T](T source)
   at RainbowMage.OverlayPlugin.PluginMain.LoadAddons()
[7/16/2021 12:43:52 AM] Info: Found enmity memory for 5.5.

## Additional information

My radar.jss config is as following:
```
Options.CustomMonsters = {
  'Lightning Sprite': {
    'name': {  // monster names
      'en': 'Lightning Sprite',
    },
    'rank': 'B',  // rank
  },
};
```

I should also note if I simply take the example and uncomment the example monster it gives, it also produces the error. I think the example may not be correct or something is wrong with the code that reads the config.

**Comment by JLGarber** [comment]
This is the same issue as #3306. It's likely just a typo of some sort in the plugin core. We'll likely have to sit tight until that's resolved, but unless we're incredibly unlucky it should be a quick fix.

**Comment by jpdied** [comment]
Issue was fixed with the patch. Thanks!
