### ISSUE TITLE
create-release workflow has errors

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#3308]
See: https://github.com/quisquous/cactbot/actions/runs/1036506643

However https://github.com/quisquous/cactbot/runs/3083679535?check_suite_focus=true worked???

**Comment by MaikoTan** [comment]
The first one uses dotnet, but the second one uses MSBuild.
That is the only difference I think.

**Comment by panicstevenson** [comment]
I believe this is from the new languages; we probably have to build the former with MSBuild as well
