### ISSUE TITLE
Partially change trigger behavior

### ISSUE THREAD

**Issue by AkiyoAratemuso** [quisquous/cactbot#333]
Heya, apologies for an issue ticket that is more on the side of help request, is there a way to partially modify trigger behavior in user\raidboss.js and not mess with the original trigger file in /ui/?

e.g. Disable/change alert text/tts, match condition and behavior (inserting tts in triggers that only has alerts, change tts to accomodate other languages)

Secondly, if a custom trigger is inserted through user\raidboss.js, can it access the data stored in the original trigger files? (For example, dumping UCoB dragon placement data from user\raidboss.js)?

i.e. is custom triggers in user\raidboss.js considered part of \triggers\fight_name.js when loaded?

Thank you for your continuous hard work!

**Comment by quisquous** [comment]
Yes, you can definitely change behavior.  **user/raidboss-example.js** should have a bunch of examples of how to do this.  If those examples don't help, let me know what I can explain better.  This could be a lot better documented.

Yeah, if a custom trigger is inserted, it runs with the same `data` object as everything else.

All triggers are loaded based on zoneRegex.  If the triggers match the zoneRegex, then all of those triggers get loaded.  There's really no difference between built-in ones and user ones.

**Comment by AkiyoAratemuso** [comment]
Ah I see. Thanks for clearing up question two!

For question one, I've been through the PerTriggerOptions documentation - If you don't mind, can you work with this example?

`{
      id: 'SeiryuEx Handprint East',
      regex: / 15:\y{ObjectId}:Yama-no-shiki:37E5:Handprint:/,
      regexFr: / 15:\y{ObjectId}:Shiki montagneux:37E5:Main Lourde:/,
      regexDe: / 15:\y{ObjectId}:Yama no Shiki:37E5:Handabdruck:/,
      infoText: {
        en: 'East =>',
        de: 'Osten =>',
        fr: 'Est =>',
      },
      tts: {
        en: 'East',
        de: 'Osten',
        fr: 'Est',
      },
},`

Based on the documentation, I know that I can override and toggle Sound, Text, Speech alert on and off or override the sound alert.
Can I have an example in this case, on how to:
1. Add a new alert text.
2. Override info text.
3. Override TTS.
4. Attach a custom function on it (maybe a simple counter + 1 for example?)
and achieve all or any of this without disabling the trigger and creating a completely new custom trigger?

**Comment by DrLippe** [comment]
You could disable the original trigger and add a custom one.
```
DisabledTriggers: {
  'SeiryuEx Handprint East': true,
},
Triggers: [
  {
    zoneRegex: /Seiryus zoneRegex/,
    triggers: [
      {
        id: 'Custom SeiryuEx Handprint East',
        regex: / 15:\y{ObjectId}:Yama-no-shiki:37E5:Handprint:/,
        alarmText: 'my custom alarm text',
        run: function(data) {
          data.awesomeness = data.awesomeness + 1 || 0;
        },
      },
    ],
  },
],
```
This may break the overall trigger performance if you cut important functions of existing triggers.

**Comment by AkiyoAratemuso** [comment]
Thank you, but that's not what I am looking for. I know about disabling triggers and building my own, but I opened this issue to specifically ask about partial inline modification, similar to how you can override volume, sound effect or turn off alerts without writing a replacement trigger, using TriggerOptions.

**Comment by quisquous** [comment]
Sorry for the belated response.

Regarding PerTriggerOptions, I half agree with @DrLippe above in that anything you can do with those options, you can do by just disabling the trigger and copy+pasting it.  The only downside is that if the trigger regex ever breaks and cactbot updates, you'll have to update yourself.

I use PerTriggerOptions for things like turning on text to speech for only a few triggers or showing tank things no matter what job I am, but not for anything more complicated: https://github.com/quisquous/cactbot-user/blob/master/raidboss.js#L52

The available fields on PerTriggerOptions are:
```
// Boolean options
GroupTTSText
GroupSpeechAlert
SpeechAlert
SoundAlert
TextAlert
// Trigger functions
Condition
AlarmText
AlertText
InfoText
GroupTTSText
TTSText
SoundOverride
VolumeOverride
```

Here's how you would do most of the things you asked about.
```
Options.PerTriggerOptions = {
  'SeiryuEx Handprint East': {
    AlertText: function(data) {
      return 'I am a new alert text';
    },
    InfoText: function(data) {
      return 'I override the existing info text';
    },
    TTSText: function(data) {
      return 'I override the tts';
    },
  },
};
```

There's no way to override `run` or `preRun`.

**Comment by AkiyoAratemuso** [comment]
Thank you, I just wanted to make sure I'm not losing the flexibility of auto update while I go off reinventing the wheel when there is already a great feature built in that I didn't know of. The available fields and the example are exactly what I needed.

Thanks again for the swift replies and continued hard work on cactbot. I think the info you've provided would also be great if included in the readme/documentation too. I'll close the issue now.
