### ISSUE TITLE
TTS Alerts disabled 

### ISSUE THREAD

**Issue by sarynmoon** [quisquous/cactbot#3331]
I haven't changed anything since the last update and this new update made the alerts not work properly. not tts or sounds or even text display on the screen. The timers work fine though.

**Comment by Akurosia** [comment]
Game was updated today which breaks the ACT plugin and in return some functionality of cactbot.
Did you use the latest ACT beta? If not, try the beta and see if it works.
If you dont know how to use the beta, wait a day till it is fully released.

**Comment by quisquous** [comment]
Let me know if this is still an issue, and I can reopen this.

**Comment by TheOddball** [comment]
I am still having issues. XIV Parsing plugin is updated, and DPS counters work. I am unsure as to why Cactbot is no longer working.

**Comment by quisquous** [comment]
I think the best plan is to follow up in the FFXIV ACT discord and get help there.

**Comment by TheOddball** [comment]
It started happening after the TS rewrite update, I don't think it's a configuration issue
