### ISSUE TITLE
UWU Titan Jump Direction

### ISSUE THREAD

**Issue by zedekblue** [quisquous/cactbot#3338]
## Summary

UWU Phase 3, Titan jumps to a random cardinal.
It is determined by which way he faces before jumping, and it is ridiculously brief and hard to notice. Would be great if its possible to have a simple trigger added, much like e12s p2 @ apocs.

**Comment by Akurosia** [comment]
Titan will always jump in the cardinal direction he is looking right befor he jumps

**Comment by zedekblue** [comment]
> 
> 
> Titan will always jump in the cardinal direction he is looking right befor he jumps

He will change direction, it is not baitable.
Titan will turn away from the main tank and look in the direction for only a fraction of a second.

**Comment by quisquous** [comment]
If it is only for a fraction of a second and there is no cast bar, I think this would be tricky to write a trigger for.  Is there a log line that shows which direction Titan is going?

**Comment by valarnin** [comment]
Note that the way the e12s callout works is by delaying for half a second after she starts casting Cataclysm to allow her to fully turn, and even then it doesn't work unless she's reasonably centered (though that could be fixed with some more advanced logic). Cataclysm is a 5.7s cast, for reference.

https://github.com/quisquous/cactbot/blob/main/ui/raidboss/data/05-shb/raid/e12s.ts#L1180

I'm not familiar with the UWU timings, but if the jump is so fast that there can't be a half second delay to allow the boss to fully turn like there is in e12s, it's not really going to be possible I think?

**Comment by zedekblue** [comment]
> 
> 
> If it is only for a fraction of a second and there is no cast bar, I think this would be tricky to write a trigger for. Is there a log line that shows which direction Titan is going?

I am no expert, and this is my first time sifting through a log, but I do see this line right as he is jumping in my ACT log:

`20|2021-07-22T01:49:50.4580000-06:00|40022C3F|Titan|2B66|Geocrush|40022C3F|Titan|2.70|114|100|0|-1.570868||c12700b1032810f60b78cbd66d540d08`

4 seconds later he lands and the damage goes out, and you get 8 lines of this:
`22|2021-07-22T01:49:53.4520000-06:00|40022C3F|Titan|2B66|Geocrush|104C28DD|Player Name|450003|45480000|1B|2B668000|0|0|0|0|0|0|0|0|0|0|0|0|50096|50096|7932|10000|0|1000|88.858|93.15311|-0.0007127686|-0.6737885|3425034|4607480|10000|10000|0|1000|114|100|0|-1.570868|0000DFDE|0|c2aaaf456311f96b96b79ca030fa890a`

Video of this part of the log, where you can also see how breif it is: https://youtu.be/3AJXA929XQs?t=383

**Comment by valarnin** [comment]
You could try a custom trigger like this and see if it works. I have no realistic way to test this myself since I don't currently do any ultimate content.

Again, the usual caveat that it'll probably only be right if the boss is relatively centered, etc etc.

```ts
    {
      id: 'UWU Titan Geocrush',
      type: 'StartsUsing',
      netRegex: NetRegexes.startsUsing({ id: '2B66', source: 'Titan' }),
      netRegexDe: NetRegexes.startsUsing({ id: '2B66', source: 'Titan' }),
      netRegexFr: NetRegexes.startsUsing({ id: '2B66', source: 'Titan' }),
      netRegexJa: NetRegexes.startsUsing({ id: '2B66', source: 'タイタン' }),
      netRegexCn: NetRegexes.startsUsing({ id: '2B66', source: '泰坦' }),
      netRegexKo: NetRegexes.startsUsing({ id: '2B66', source: '타이탄' }),
      infoText: (_data, matches, output) => {
        const cardinal = ((2 - Math.round(matches.heading * 4 / Math.PI) / 2) + 2) % 4;

        const dirs: { [dir: number]: string } = {
          0: output.north!(),
          1: output.east!(),
          2: output.south!(),
          3: output.west!(),
        };

        return dirs[cardinal];
      },
      outputStrings: {
        unknown: Outputs.unknown,
        north: Outputs.north,
        east: Outputs.east,
        south: Outputs.south,
        west: Outputs.west,
      },
    },
```

**Comment by zedekblue** [comment]
> 
> 
> You could try a custom trigger like this and see if it works. I have no realistic way to test this myself since I don't currently do any ultimate content.
> 
> Again, the usual caveat that it'll probably only be right if the boss is relatively centered, etc etc.
> 

I will test this out next week during prog. Thank you for taking the time!

**Comment by Lokidoki8017** [comment]
zedekblue did this work

**Comment by zedekblue** [comment]
We ended up taking a week off, so sorry it took so long to test.
I'm hoping I'm doing this right in the first place, I threw that block of code into ultima_weapon_ultimate.js right after line 34: "triggers: ["
Had nothing pop up during prog.
I don't think my tts works if that's how outputs.north works, but I didn't see any other prompts or echoes.

**Comment by valarnin** [comment]
You need to add the trigger to a user/raidboss.js file. Built-in trigger files are all compiled into the overlay, only the user files are read during runtime.

**Comment by zedekblue** [comment]
I am closing this because either I am too stupid to get this script to work, or it just isn't going to work in the first place.
Regardless, after seeing Titan enough it has become pretty easy to tell which way he is jumping, and it's likely more reliable to just learn it than trust a potentially haphazard trigger.
Thank you all for your help anyway. If somebody else progging would like to try it out or open this later down the line feel free.
