### ISSUE TITLE
DR:S Trinity Avowed Sword and Brand Raidboss calls not working.

### ISSUE THREAD

**Issue by Volkaru** [quisquous/cactbot#3339]
## Description

7/23/21

During the Trinity Avowed boss in Delubrum Reginae (Savage) the Raid Boss plugin has stopped accounting for sword cleaves AND brands. So it will call the sword safe spot, but not where to stand cardinal from the safe spot. And during the second half of the fight, the callouts don't account for brand debuff when telling you where to go.
Confirmed running latest version.

**Comment by quisquous** [comment]
Were there any errors in the overlayplugin log when this happened?

**Comment by Volkaru** [comment]
Does it automatically save the log anywhere? I can post it if needed. If not, I'm going on another run tonight. If there's an option to turn on for logging, I can, then report it when I'm done.

**Comment by quisquous** [comment]
No, it does not.  While ACT is open, you can see the log in Plugins ->OverlayPlugin.dll -> the log window at the bottom.

If this is still having issues, please zip up your [Network log file](https://github.com/quisquous/cactbot/blob/main/docs/FAQ-Troubleshooting.md#how-to-find-a-network-log) and upload it somewhere that I can take a look at.  I gave this a run through a previous log I had, and things seemed ok.

Sorry for the hassle!!

**Comment by Volkaru** [comment]
Here is the network log for yesterday during the run where the calls didn't work properly. I asked another person using Cactbot on the same run, they also were having issues on Trinity Avowed with the same calls.
[Network_22006_20210723.zip](https://github.com/quisquous/cactbot/files/6873158/Network_22006_20210723.zip)

**Comment by Volkaru** [comment]
Here is the network log from my friend who was on the same run and having the same issue, if it'll help. 
[DRS 7-23 run.zip](https://github.com/quisquous/cactbot/files/6873170/DRS.7-23.run.zip)

**Comment by quisquous** [comment]
Ok, I think I found the issue.  You can change your overlay's url to `https://quisquous.github.io/cactbot/ui/raidboss/raidboss.html` and that will use the version that includes that change.  Let me know if that fixes things!

**Comment by Volkaru** [comment]
Will do! Run is in an hour. Will report back afterward. Is the proper place for this Raidboss > General > URL?

**Comment by quisquous** [comment]
Yeah, that's it exactly.  You can verify it's working if you go to Summerford Farms and do a `/countdown 5`.

**Comment by Volkaru** [comment]
Completed the run. It worked perfectly, thank you for the quick fix!

**Comment by Volkaru** [comment]
There's another bug on Avowed now, I think. It's not calling out the first set of meteors in Savage anymore. The ones WITHOUT the brand. Hasn't for the last few runs I've been on. Overlay isn't reporting any errors in text.
