### ISSUE TITLE
CACTBOT is not loading - error with ACT when starting with CACTBOT Enabled

### ISSUE THREAD

**Issue by M5RR** [quisquous/cactbot#3340]
## Description

When trying to start ACT with the latest version of CACTBOT, I get a series of overlay errors and CACTBOT is disabled by ACT. I've tried to research this error and have made sure that I'm running the latest version of everything.

## Additional information

1. ACT disables cactbot - nothing is reported in the logs
![image](https://user-images.githubusercontent.com/34949710/126878480-86be7768-e6dc-4042-94d2-a3ce69d6511a.png)

2. Manually enabled - then restarted
![image](https://user-images.githubusercontent.com/34949710/126878528-0dab1221-e5f3-4b76-a024-e6b2b2c10c8c.png)

3. On restart, the following error appears:
![image](https://user-images.githubusercontent.com/34949710/126878552-bef40abb-d103-4bfd-9434-f2e94501f68e.png)
![image](https://user-images.githubusercontent.com/34949710/126878609-da0bfa05-7fd9-487e-9bb7-6a65a0be5590.png)

ACT then disables cactbot - not sure why it's looking for an older version of the library.

This is the all that I see in the logs:
253|2021-07-24T14:39:30.6747261-04:00|FFXIV PLUGIN VERSION: 2.2.0.6|2f41ca8f329252b5fd291f21b6b28aad
249|2021-07-24T14:39:30.8642592-04:00|Language ID: 1, Disable Damage Shield: False, Disable Combine Pets: False, Parse Filter: None, DoTCrits: False, RealDoTs: False, Parse Potency: False|d067729548d25854aa3c9573f8ed1d6e
249|2021-07-24T14:39:30.8672598-04:00|Selected Process ID: 0, Disable Network Data: False, Enable HP Scan: False, Dump All Network Data: False, Disable Combat Log: False, Selected IP: , WinPcap: False, Socket Filter: True|026e5bff6d687262612c7593b53f7083
253|2021-07-24T14:39:49.8461988-04:00|FFXIV PLUGIN VERSION: 2.2.0.6|e2ccaa122715c44325a30fddb2eed2ab
249|2021-07-24T14:39:50.0352319-04:00|Language ID: 1, Disable Damage Shield: False, Disable Combine Pets: False, Parse Filter: None, DoTCrits: False, RealDoTs: False, Parse Potency: False|30ba99d3b3a320ee77be6f77fc90193b
249|2021-07-24T14:39:50.0382324-04:00|Selected Process ID: 0, Disable Network Data: False, Enable HP Scan: False, Dump All Network Data: False, Disable Combat Log: False, Selected IP: , WinPcap: False, Socket Filter: True|aa780fcc81a9fbf2767cedb4ff865e94
249|2021-07-24T14:42:21.1913152-04:00|Language ID: 1, Disable Damage Shield: False, Disable Combine Pets: False, Parse Filter: None, DoTCrits: False, RealDoTs: False, Parse Potency: False|496f6fc289f171cd0a769134f166b44c
253|2021-07-24T14:42:44.5913967-04:00|FFXIV PLUGIN VERSION: 2.2.0.6|9d83491a175e01a45127e9a38ac4f306
249|2021-07-24T14:42:44.7784296-04:00|Language ID: 1, Disable Damage Shield: False, Disable Combine Pets: False, Parse Filter: None, DoTCrits: False, RealDoTs: False, Parse Potency: False|c33feaee6137dd75646a3a770178651a
249|2021-07-24T14:42:44.7809301-04:00|Selected Process ID: 0, Disable Network Data: False, Enable HP Scan: False, Dump All Network Data: False, Disable Combat Log: False, Selected IP: , WinPcap: False, Socket Filter: True|a8f14d39f22f27cb1316eb05b59c9fec
253|2021-07-24T14:43:15.7665216-04:00|FFXIV PLUGIN VERSION: 2.2.0.6|cfb2e7a437b5359dbd7c7f3453f4534d
249|2021-07-24T14:43:15.9520544-04:00|Language ID: 1, Disable Damage Shield: False, Disable Combine Pets: False, Parse Filter: None, DoTCrits: False, RealDoTs: False, Parse Potency: False|e839b32166ed8e6790f11c2748171382
249|2021-07-24T14:43:15.9545552-04:00|Selected Process ID: 0, Disable Network Data: False, Enable HP Scan: False, Dump All Network Data: False, Disable Combat Log: False, Selected IP: , WinPcap: False, Socket Filter: True|8695d1beb7e993aa0dc8c8bea37bdbd0
249|2021-07-24T14:43:47.9332645-04:00|Language ID: 1, Disable Damage Shield: False, Disable Combine Pets: False, Parse Filter: None, DoTCrits: False, RealDoTs: False, Parse Potency: False|6bec2e5e91d86d444dbc774f8d68fa5f

**Version of ACT:** 3.5.0.273
**Version of Cactbot:** 0.23.3

**Comment by valarnin** [comment]
You need to move Cactbot to load after OverlayPlugin, then restart ACT, then click the enable checkbox.

**Comment by M5RR** [comment]
> You need to move Cactbot to load after OverlayPlugin, then restart ACT, then click the enable checkbox.

That worked. Good information to have.

**Comment by quisquous** [comment]
I tried to list that in the documentation here: https://github.com/quisquous/cactbot#:~:text=Verify%20your%20plugins%20are%20in%20the%20correct%20order

If there's some way you think this could be made more clear, I'd be happy to try to fix it up.

**Comment by M5RR** [comment]
I see it now and the mistake is mine - i glossed over it and I should have read it. 

If I am the only one having this problem, then I wouldn’t change anything. But if this is something you get asked a lot, then I’d just put a subheading and bullet point it out - the format difference from standard paragraph text will force people to notice. If I may, 

**Load Order**
Because of Cactbot’s dependencies, it is import to verify your plugins are loaded in the correct order. The order should be: 
1. FFXIV Plug-in 
2. OverlayPlugin
3. CactbotOverlay

Then add your screenshot here sleuth the remaining text. It just makes it easier to find and take notice of. 

By the way, now that I have it working, what an amazing plugin! My respect and gratitude for all your hard work on this!
