### ISSUE TITLE
raidemulator GetCombatants errors when seeking

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#3349]
Repro:
* Import https://github.com/quisquous/cactbot/issues/3339#issuecomment-886120461
* Open Trinity Avowed
* (make a coffee)
* Notice only `Gleaming Arrow: expected 6, got 4` error in log (I'll look at this)
* Click on 8 minutes in timeline
* Hit play (?)
* See a bunch of unexpected GetCombatants errors in the log

```
delubrum_reginae_savage.ts:2102 Avowed Avatar: expected at least 3 combatants got 0
delubrum_reginae_savage.ts:2358 Gleaming Arrow: expected 6, got 0
delubrum_reginae_savage.ts:2102 Avowed Avatar: expected at least 3 combatants got 0
delubrum_reginae_savage.ts:2358 Gleaming Arrow: expected 6, got 0
delubrum_reginae_savage.ts:2102 Avowed Avatar: expected at least 3 combatants got 0
delubrum_reginae_savage.ts:2358 Gleaming Arrow: expected 6, got 0
```

**Comment by quisquous** [comment]
Actually, I suspect the `expected 6, got 4` issue is also an emulator GetCombatants issue.  It's asking for these ids `[1073760139,1073760140,1073760141,1073760142,1073760143,1073760144]` but only getting 4 combatants back.

**Comment by valarnin** [comment]
This `if` statement in the `getCombatants` override is failing the second condition for ID `0x4000478A`:

```ts
        if (firstStateStamp > timestamp || lastStateStamp < timestamp)
          continue;
```

Looking into this further, it looks like because the state of the combatant is identical between casts of `Gleaming Arrow` (same position, same HP, etc), the new casts aren't being flagged as significant per this code:

https://github.com/quisquous/cactbot/blob/9495509340f72f75b500a8f87f8435c83cadc550/ui/raidboss/emulator/data/Combatant.ts#L96-L100

Should `20` lines force a significant state update, maybe?

**Comment by quisquous** [comment]
Yeah, either force a significant state update or update the time of the previous one if it's the same?

**Comment by valarnin** [comment]
We'd never want to update the previous timestamp, so it would be forcing a new state. Are there any other lines that should force a new significant state?

**Comment by valarnin** [comment]
For context to help explain the logic here, "significant" states are combatant states where the combatant data is known to be completely accurate or states that no longer match the previous state. So if there are other lines where the combatant's state is guaranteed 100% accurate from the network log lines, it might make sense to have those force a significant state update as well.

**Comment by quisquous** [comment]
Sorry, my mental model was that we "got next significant state" and so state A at time T and state A at time T=2 is equivalent to state A at time T=2 for "get next significant state".  Maybe I'm thinking about it wrong?  I think adding more significant states seems fine!
