### ISSUE TITLE
Should update documents for developers/translators/contributors

### ISSUE THREAD

**Issue by MaikoTan** [quisquous/cactbot#3379]
Several scripts in `util` were transformed into TypeScript and added in `package.json`.
Therefore, those scripts should be invoked by `npm run` command instead of `node <filename>` or something.
But the document is not updated, there are few people who don't know the changes confusing with this.

I wanted to add instructions, but I don't know where is better to note the changes.

**Comment by tssailzz8** [comment]
I want to know how to use the old one like check_translation.py and fetch_deps.py

**Comment by quisquous** [comment]
It looks like `README.md` explains fetch_deps.py, so probably should be updated for the typescript version.

I think `CONTRIBUTING.md` might be a good place how to use a bunch of scripts that only developers are using?

**Comment by quisquous** [comment]
extremely belatedly, #5365 addresses fetch_deps.py. If still think `CONTRIBUTING.md` is a reasonable place to add other script documentation for now if anybody wanted to send pull requests.  I am going to close this for now, but feel free to send further PRs to address anything that is missing.
