### ISSUE TITLE
Make LogGuide Better

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#3380]
In my mind, the [LogGuide](https://github.com/quisquous/cactbot/blob/main/docs/LogGuide.md) is missing a few things:
* new log lines that have been added to ACT (e.g. 0x28 Map)
* old log lines that haven't been documented (e.g. 0x1C NetworkRaidMarker and 0x1D NetworkTargetMarker)
* network log line structure and examples
* question: should we add regex examples too?

So, it probably needs a good bit of attention.

I wanted to discuss a little bit what the format should look like before anybody takes a huge pass at it.  I do think it'd be nice to have the ACT log lines and network log line versions represent the same data, ideally.  Also, "network log line" and "ACT log line" are both pretty wordy, but I'm not sure how to abbreviate in a way that retains clarity.

Here's a couple of random thoughts on what this could look like.  Other proposals/ideas/criticisms/opinions extremely welcome.

# Current Structure

Structure:
`14:[Source ID]:[Source Name] starts using [Ability Name] on [Target Name].`

Examples:

```log
14:5B2:Twintania starts using Death Sentence on Potato Chippy.
14:DF9:Tini Poutini starts using Fire IV on Striking Dummy.
```

# Proposal 1 (everything separate)

Net structure: `20|timestamp|sourceId|source|id|ability|targetId|target|castTime|x|y|z|heading||hash`

Net regex: `/^(?<type>(?:20))\|(?<timestamp>(?:[^|]*))\|(?<sourceId>(?:[^|]*))\|(?<source>(?:[^|]*))\|(?<id>(?:[^|]*))\|(?<ability>(?:[^|]*))\|(?<targetId>(?:[^|]*))\|(?<target>(?:[^|]*))\|(?<castTime>(?:[^|]*))\|(?<x>(?:[^|]*))\|(?<y>(?:[^|]*))\|(?<z>(?:[^|]*))\|(?<heading>(?:[^|]*))\|/`

Net examples:
```log
20|2020-03-18T09:39:40.5230000-07:00|106E0DB3|Potato Chippy|1D3F|Midare Setsugekka|40000284|Green Dragon|1.53|-389.807|224.858|238.695|-3.132169||ff0eb93ae3714f3e520b871c3d72cfee
20|2018-09-18T20:40:06.9110000-07:00|400069FE|The Manipulator|F5C|Mortal Revolution|400069FE|The Manipulator|5.70|120.789|-90.37|0|1.872||a1e83a963cea8bb7f1dff1bbae7d6fd6
20|2020-03-18T09:35:50.6220000-07:00|103D4280|Tini Poutini|8B|Holy|103D4280|Tini Poutini|2.28|-80|92.3|0.01|-2.7113||a0117bf7bdb350d53ad3dfae117caca9
```

ACT Structure: `14:[Source ID]:[Source Name] starts using [Ability Name] on [Target Name].`

ACT regex: `/(?<timestamp>(?:^.{14})) 14:(?<id>(?:[0-9A-Fa-f]{1,8})):(?<source>(?:.*?)) starts using (?<ability>(?:.*?)) on (?<target>(?:.*?))\./`

ACT examples
```log
[09:39:40.523] 14:1D3F:Potato Chippy starts using Midare Setsugekka on Green Dragon.
[20:40:06.911] 14:F5C:The Manipulator starts using Mortal Revolution on The Manipulator.
[09:35:50.622] 14:8B:Tini Poutini starts using Holy on Tini Poutini.
```

# Proposal 2 (blocks)

Network Log Lines
```log
Structure:
20|timestamp|sourceId|source|id|ability|targetId|target|castTime|x|y|z|heading||hash

Regex:
/^(?<type>(?:20))\|(?<timestamp>(?:[^|]*))\|(?<sourceId>(?:[^|]*))\|(?<source>(?:[^|]*))\|(?<id>(?:[^|]*))\|(?<ability>(?:[^|]*))\|(?<targetId>(?:[^|]*))\|(?<target>(?:[^|]*))\|(?<castTime>(?:[^|]*))\|(?<x>(?:[^|]*))\|(?<y>(?:[^|]*))\|(?<z>(?:[^|]*))\|(?<heading>(?:[^|]*))\|/

Examples:
20|2020-03-18T09:39:40.5230000-07:00|106E0DB3|Potato Chippy|1D3F|Midare Setsugekka|40000284|Green Dragon|1.53|-389.807|224.858|238.695|-3.132169||ff0eb93ae3714f3e520b871c3d72cfee
20|2018-09-18T20:40:06.9110000-07:00|400069FE|The Manipulator|F5C|Mortal Revolution|400069FE|The Manipulator|5.70|120.789|-90.37|0|1.872||a1e83a963cea8bb7f1dff1bbae7d6fd6
20|2020-03-18T09:35:50.6220000-07:00|103D4280|Tini Poutini|8B|Holy|103D4280|Tini Poutini|2.28|-80|92.3|0.01|-2.7113||a0117bf7bdb350d53ad3dfae117caca9
```

ACT Log Lines
```log
Structure:
14:[Source ID]:[Source Name] starts using [Ability Name] on [Target Name].

Regex:
/(?<timestamp>(?:^.{14})) 14:(?<id>(?:[0-9A-Fa-f]{1,8})):(?<source>(?:.*?)) starts using (?<ability>(?:.*?)) on (?<target>(?:.*?))\./

Examples:
[09:39:40.523] 14:1D3F:Potato Chippy starts using Midare Setsugekka on Green Dragon.
[20:40:06.911] 14:F5C:The Manipulator starts using Mortal Revolution on The Manipulator.
[09:35:50.622] 14:8B:Tini Poutini starts using Holy on Tini Poutini.
```

### Proposal 3

Other ideas?

**Comment by valarnin** [comment]
Does it make sense to automatically generate the majority of the file based off of `logDefinitions`, so that it's automatically kept mostly up-to-date?

**Comment by quisquous** [comment]
> Does it make sense to automatically generate the majority of the file based off of `logDefinitions`, so that it's automatically kept mostly up-to-date?

Yeah, definitely! Maybe there's other options but I was looking at https://github.com/DavidWells/markdown-magic as one option that updates markdown files in place between special tags, and could support some arbitrary script.

**Comment by JLGarber** [comment]
Of the presented options, I prefer the second. It's simpler to understand. However, what if we did an "interleaved" layout?

---
# LINE 14/20: NetworkStartsUsing

DESCRIPTION
This line is written to the log any time an entity begins casting a cast-time spell or ability. Words words words words etc etc etc.

STRUCTURE
```
Network Log Line Structure:
20|timestamp|sourceId|source|id|ability|targetId|target|castTime|x|y|z|heading||hash

ACT Log Line Structure:
14:[Source ID]:[Source Name] starts using [Ability Name] on [Target Name]
```

REGEXES
```
Network Regex:
/^(?<type>(?:20))\|(?<timestamp>(?:[^|]*))\|(?<sourceId>(?:[^|]*))\|(?<source>(?:[^|]*))\|(?<id>(?:[^|]*))\|(?<ability>(?:[^|]*))\|(?<targetId>(?:[^|]*))\|(?<target>(?:[^|]*))\|(?<castTime>(?:[^|]*))\|(?<x>(?:[^|]*))\|(?<y>(?:[^|]*))\|(?<z>(?:[^|]*))\|(?<heading>(?:[^|]*))\|/

ACT Regex:
/(?<timestamp>(?:^.{14})) 14:(?<id>(?:[0-9A-Fa-f]{1,8})):(?<source>(?:.*?)) starts using (?<ability>(?:.*?)) on (?<target>(?:.*?))\./
```

EXAMPLES
```
Network Examples:
20|2020-03-18T09:39:40.5230000-07:00|106E0DB3|Potato Chippy|1D3F|Midare Setsugekka|40000284|Green Dragon|1.53|-389.807|224.858|238.695|-3.132169||ff0eb93ae3714f3e520b871c3d72cfee
20|2018-09-18T20:40:06.9110000-07:00|400069FE|The Manipulator|F5C|Mortal Revolution|400069FE|The Manipulator|5.70|120.789|-90.37|0|1.872||a1e83a963cea8bb7f1dff1bbae7d6fd6
20|2020-03-18T09:35:50.6220000-07:00|103D4280|Tini Poutini|8B|Holy|103D4280|Tini Poutini|2.28|-80|92.3|0.01|-2.7113||a0117bf7bdb350d53ad3dfae117caca9

ACT Examples:
[09:39:40.523] 14:1D3F:Potato Chippy starts using Midare Setsugekka on Green Dragon.
[20:40:06.911] 14:F5C:The Manipulator starts using Mortal Revolution on The Manipulator.
[09:35:50.622] 14:8B:Tini Poutini starts using Holy on Tini Poutini.
```
---

This has the significant downside of being very dense, but it could be very helpful for people trying to learn how to correlate between ACT and network logs. I know in the FFXIV_ACT Discord server, we've seen confusion from some people between what the different types of logs are. Laying it out like this might be helpful to someone who doesn't know what hexadecimal is, but is able to see "oh, that log line is `14` in ACT, and the guide says I should look for a `20` in the network log."

Strong agree on auto-generating what we can. Quisquous, did we ever hear back from that one person who had new information on headmarker IDs (or maybe it was names)? I'm happy to make another pass through and add some of the stuff from Shadowbringers, but if we could automate that table of headmarkers (and tethers?) it would be so much more convenient.

**Comment by MaikoTan** [comment]
I think mostly I'll regard how would it be localised into other languages. Is there a easy way to localise them even with a document generator?

Also, sometimes we are trying to explain the meaning of some glossary that the explanation might be redundant in English, e.g. something like:

> **targetId** _在内存中指向目标实体的独一无二的id_ (A unique id pointing to the current target entity in memory)

Do you think something like this is worth to add in even the English name is already self-explained?

**Comment by valarnin** [comment]
> LINE 14/20: NetworkStartsUsing

Should probably be denoting these properly? One of these options?

> LINE 0x14/20: NetworkStartsUsing
> LINE `14:`/`20|`: NetworkStartsUsing

**Comment by JLGarber** [comment]
> Should probably be denoting these properly? One of these options?

The second, probably, since there will be log guide readers who don’t know about hex.

**Comment by quisquous** [comment]
> Of the presented options, I prefer the second. It's simpler to understand

Yeah, interleaved seems reasonable too!  I was wondering about making markdown subheadings, and the interleaved suggestion would be pretty clear to have a structure / regex / examples subheading for each line type.

I feel like there's just a lot of information and I'm just not sure of the best way to present it reasonably.  I'd definitely take other opinions if folks had them.

> I think mostly I'll regard how would it be localised into other languages. Is there a easy way to localise them even with a document generator?

I think it could be possible.  Do the example lines need to be localized?  Or, just the fields in the "structure" descriptions?

In a hypothetical sense, I could imagine writing some script that could be run to update each section.  If that's true, then we could add translations to that script or to the netlog_defs file that could get used.

> > Should probably be denoting these properly? One of these options?
> 
> The second, probably, since there will be log guide readers who don’t know about hex.

I could go either way on this one.  I think `14: / 20|` is probably clearer but is kind of awkward to read.  `0x14/20` or `0x14 (20)` or `20 (0x14)` is more clear.  I think the document itself explains hex and has example lines with the id, so I think that weakens that concern a little bit for me.

**Comment by valarnin** [comment]
I'm taking a look at this right now, just playing around with options and checking how it looks.

For `Examples`, how thorough should I be if I decide to fully implement this? Like, should I pull in all 254 (at current count) possible GameLog event types as examples?

**Comment by quisquous** [comment]
For me, I think really the important thing is just to show a couple of examples (n=3).  For things like ability (where there's flags) or game log event types (where there's a code) or headmarkers (where there's ids), I think it's better to have a table for that particular field rather than spell them out in the example section.

**Comment by JLGarber** [comment]
Agreed. For GameLog, I feel like it would be best to give the “most useful” examples (zone seal, chat, etc) in-line, with a link to “here’s a document that has all the different game log lines”. This document could in turn be partially auto-generated just like the main log guide.

**Comment by valarnin** [comment]
Here's what my testing looks like right now.

This markdown:

```markdown
<!-- AUTO-GENERATED-CONTENT:START (logLines) -->

<!-- AUTO-GENERATED-CONTENT:END -->
```

With this config:

```ts
  GameLog: {
    description: {
      en: `
These are what this document calls "game log lines".
There is a two byte log type and then a string.
Because these are not often used for triggers
(other than \`0839\` messages),
the full set of LogTypes is not well-documented.

(Pull requests welcome!)
`,
    },
    regexes: {
      network: NetRegexes.gameLog({ capture: true }).source,
      logLine: Regexes.gameLog({ capture: true }).source,
    },
    examples: {
      en: [
        '00|2021-04-26T14:12:30.0000000-04:00|0839||You change to warrior.|d8c450105ea12854e26eb687579564df',
        '00|2021-04-26T16:57:41.0000000-04:00|0840||You can now summon the antelope stag mount.|caa3526e9f127887766e9211e87e0e8f',
        '00|2021-04-26T14:17:11.0000000-04:00|0b3a||You defeat the embodiment.|ef3b7b7f1e980f2c08e903edd51c70c7',
        '00|2021-04-26T14:12:30.0000000-04:00|302b||The gravity node uses Forked Lightning.|45d50c5f5322adf787db2bd00d85493d',
        '00|2021-04-26T14:12:30.0000000-04:00|322a||The attack misses.|f9f57724eb396a6a94232e9159175e8c',
      ],
    },
    notes: {
      en: `
#### Don't Write Triggers Against Game Log Lines

There are a number of reasons to avoid basing triggers on game log lines:

* can show up later than ACT log lines (often up to half a second)
* inconsistent text (gains effect vs suffers effect, begins casting vs readies, you vs player name)
* often vague (the attack misses)
* can change spelling at the whim of SquareEnix

Instead, the recommendation is to base your triggers on ACT log lines that are not type \`00\`.
Prefer using \`1A\` "gains the effect" message instead of \`00\` "suffers the effect" messages.
Prefer using the \`14\` "starts using" instead of \`00\` "readies" or "begins casting".

At the moment, there are some cases where you must use game log lines,
such as sealing and unsealing of zones, or boss rp text for phase transitions.

Note:
There are examples where \`14\` "starts using" lines show up
after the corresponding \`00\` "readies" line,
but it is on the order of tens of milliseconds
and does not consistently show up first.
\`15\` "ability" lines always seem to show up before the \`00\` "uses" lines.
`,
    },
  },
```

Results in this markdown:

https://gist.github.com/valarnin/5fb2af69cd3358d7def71f20e947525e

This is using ParseLine from raidemulator to convert the network lines to log lines automatically.

Thoughts?

**Comment by valarnin** [comment]
Whoops, fixed a typo in the ts that generated that markdown, so the structure has actual names now and not "name"

**Comment by JLGarber** [comment]
Wow. That's *very* good. I guess the idea is that the log guide will no longer be directly updated, but that we will instead run all updates through the config file? I don't have issues with that, just want to be sure, since other auto-generated files don't have anything besides structure and data. (Whereas this one will have to have some exposition as well.)

**Comment by valarnin** [comment]
The idea here would be to require a LogGuide entry for anything in netlog_defs.ts, and automatically build everything possible based on what's available in the defs file.

**Comment by quisquous** [comment]
This is looking great!

I think my one piece of feedback is that I think having to put big blocks of markdown into a script is a bit awkward.  It makes it hard(er) to preview.  It's much less natural.

Can I propose doing the auto update at a smaller granularity, e.g.
```markdown

### LINE 0x00 (00): GameLog

<!-- AUTO-GENERATED-CONTENT:START (logLines gameLog en) -->

<!-- AUTO-GENERATED-CONTENT:END -->

These are what this document calls "game log lines".
There is a two byte log type and then a string.
Because these are not often used for triggers
(other than `0839` messages),
the full set of LogTypes is not well-documented.

(Pull requests welcome!)

#### Don't Write Triggers Against Game Log Lines

...etc...
```

**Comment by valarnin** [comment]
I don't know if we can enforce having a LogGuide entry per netlog_defs entry if we do it that way. I'll poke around at it a bit more to see if maybe it could be done with a callback and collector setup, but even then it's not going to error at compile time, only when docs are generated.

**Comment by quisquous** [comment]
Regarding testing, I was imagining that we'd add some workflow that says "if you updated netlog_defs or this script then docs must be up to date", and any errors in generating docs would fall out from there.

**Comment by valarnin** [comment]
Alright. More tweaking. Missing entries will now generate an error:

```
npm run generate-log-guide

> cactbot@ generate-log-guide C:\Users\valar\Source\cactbot2
> node --loader ts-node/esm util/gen_log_guide.ts

(node:56844) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

Language en is missing LogGuide doc entry for type GameLog
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cactbot@ generate-log-guide: `node --loader ts-node/esm util/gen_log_guide.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cactbot@ generate-log-guide script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Here's an example with no errors:

```
npm run generate-log-guide

> cactbot@ generate-log-guide C:\Users\valar\Source\cactbot2
> node --loader ts-node/esm util/gen_log_guide.ts

(node:50552) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
✔ docs\LogGuide-en.md Updated
 Transforms run
  ⁕ logLines:type=GameLog&lang=en
```

Here's the base markdown:

```markdown
...
the full set of LogTypes is not well-documented.

(Pull requests welcome!)

<!-- AUTO-GENERATED-CONTENT:START (logLines:type=GameLog&lang=en) -->

<!-- AUTO-GENERATED-CONTENT:END -->

These are what this document calls "game log lines".
There is a two byte log type and then a string.
...
```

Here's the converted markdown:

https://gist.github.com/valarnin/a22c12a4c251a97cda80fe3f519d13eb

Right now the process is to track what type is generated per lang, and then check that at the end of the process via this callback:

```ts
  (_error, output) => {
    let exitCode = 0;
    for (const lang of languages) {
      // Only check this lang if it was converted/base file existed
      if (!output.some((o) => o.originalPath.includes('-' + lang + '.md')))
        continue;
      const convertedLines = mappedLogLines[lang];
      for (const type in logDefinitions) {
        if (!isLineType(type))
          continue;
        if (!convertedLines?.includes(type)) {
          console.error(`Language ${lang} is missing LogGuide doc entry for type ${type}`);
          exitCode = 1;
        }
      }
    }
    process.exit(exitCode);
  }
```

If this looks like a good base, I can open a PR for what I've got and start that process.

**Comment by quisquous** [comment]
That looks great! Thank you!
