### ISSUE TITLE
Custom Timeline Additions Not Showing After Restarting ACT/Game While Instanced

### ISSUE THREAD

**Issue by SableCentaur** [quisquous/cactbot#3399]
## Description

Recently I've been having an issue with my raidboss custom timeline additions. They work just fine as long as ACT is open when we start the instance, but if I have to restart ACT or the game while we're in the instance, I no longer see any of my extra timeline data. This wouldn't be a problem but when we're progging I frequently add new events to the timeline and have to restart ACT or reload cactbot to update the timeline... but then I don't get any of my events at all unless we reinstance.
When I originally started using cactbot in patch 5.3 reloading cactbot did not have this behavior, it would load my updated timeline as expected even without reinstancing. An update at some point changed this, I'm not sure how/why.

## Additional information

I will add some example screenshots later today once we go back into TEA to prog. See below for an example of my timeline additions from the raidboss file in the user folder.

`Options.Triggers = [
{
    zoneRegex: /(^The Epic of Alexander \(Ultimate\)$)/,
    timeline: function(data) {
      if (data.job != 'DNC')
        return;
      return [
        '82 "👋 Samba"',
        '215 "👋 Dance"',
        '290 "👋 Samba"',
        '355 "👋 blue orange purple green"',
        '664 "👋 Dance"',
        '710 "👋 Samba"',
	'alarmtext "👋 Samba" before 5 "👋 SAMBA"',
	'alarmtext "👋 Dance" before 2 "👋 DANCE"',
      ]},
  },
];`

**Comment by valarnin** [comment]
Just to clarify, when starting ACT in-zone the normal TEA timeline works but your user timeline additions don't?

**Comment by SableCentaur** [comment]
Correct.
If ACT is open BEFORE we instance, I can see my timeline additions.
If I restart ACT or reload cactbot while we are in the instance, I cannot see them.

**Comment by valarnin** [comment]
Do you have any other plugins aside from FFXIV parser, OverlayPlugin, Cactbot? There's an old issue logged on the parser plugin that causes problems with the zone change event if hojoring is installed, for instance.

**Comment by SableCentaur** [comment]
I have Triggernometry, OverlayPlugin WSServer, and Discord Triggers.

**Comment by valarnin** [comment]
Alright, I don't think trigg and discord trigger plugins would cause any problems, I'll try to repro and debug.

**Comment by valarnin** [comment]
I was able to reproduce this via the test timeline in summerford, looks like `data.job` isn't initialized when the timeline loads initially. 

I'll see if I can fix that but in the meantime you could just remove that check or check for `data.job === 'NONE'` as well.

**Comment by SableCentaur** [comment]
Aha! Thank you for tracking it down :)
