### ISSUE TITLE
Getting this error when loading test haven't seen any info relating to it while reading

### ISSUE THREAD

**Issue by Krylios** [quisquous/cactbot#34]
![image](https://user-images.githubusercontent.com/26440403/35766437-e937db9e-0895-11e8-8468-9aa3ccef35f0.png)

**Comment by quisquous** [comment]
Please update cactbot to https://github.com/quisquous/cactbot/releases/tag/v0.6.0.  Those errors are most likely because you're using v0.5.2 still which hasn't been updated for the 4.2 patch.  :)

**Comment by quisquous** [comment]
If this is still an issue for you after updating, please respond here again and I'll reopen this, thanks!
