### ISSUE TITLE
Titania Ex timeline entry wrong

### ISSUE THREAD

**Issue by valarnin** [quisquous/cactbot#3402]
## Description

The Titania Ex timeline entry that follows is incorrect:

```
880.2 "Phantom Rune" sync /:Titania:3D4D:/
```

Either:

1. The name is wrong and can be improved (`"Phantom Rune In"`)
2. The regex is wrong and should match both in and out variants (`/:Titania:3D4[CD]:/`)

**Comment by quisquous** [comment]
What made you look at this, out of curiosity?

**Comment by valarnin** [comment]
I was watching the analysis of limit max and the rest of that team's clear of the fight and they were talking about how the mechanic was random in/out for all of them, and I knew that some of them weren't random and it bothered me that I couldn't remember which were and weren't, so I went to check and saw it.
