### ISSUE TITLE
LogGuide includes hashes on ACT log line examples

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#3405]
On 21, 27, 28 (others?) log lines, there's an incorrect hash at the end, e.g. `[12:48:39.126] 15:40024FCE:The Manipulator:13D0:Seed Of The Sky:E0000000::0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:::::::::::16000:16000:8840:10000:0:1000:8.055649:-17.03842:10.58736:-4.792213E-05:0000DE92:0:ca5594611cf4ca4e276f64f2cfba5ffa`.

(Also, unrelated but minor, but I wonder if the structure for log lines should include a trailing `|` always and `:` when it matters so that folks know there's one there.)

**Comment by valarnin** [comment]
This would be a bug with this line:
https://github.com/quisquous/cactbot/blob/main/ui/raidboss/emulator/data/network_log_converter/LineEvent.ts#L31

Should probably be `parts.slice(2, -1)`?

In a similar vein, this would be a bit cleaner by using `parts.slice(2, -1)`, though there's no direct bug here:

https://github.com/quisquous/cactbot/blob/main/ui/raidboss/emulator/data/network_log_converter/LineEvent0x0C.ts#L47-L48
