### ISSUE TITLE
Feature Request: Oopsy log file

### ISSUE THREAD

**Issue by Kanarisky** [quisquous/cactbot#3429]
With the current summary page, you need to have it opened before raid begins, and keep it open until the end of raid. Once you've closed it, all that information is gone. 
Having Oopsy append summary to a log file after every wipe would be helpful for review.

**Comment by quisquous** [comment]
Yeah, this is on my radar to do.  I don't know about writing to a log file, but I would like to do some combination of:
(1) be able to open the summary to show you everything that ever got shown on the live list
(2) be able to load a file into the summary page and show you what errors occurred
