### ISSUE TITLE
Is it possible to trigger TTS with timeline file?

### ISSUE THREAD

**Issue by zplaced** [quisquous/cactbot#3430]
I am thinking to customize so that I can get an TTS 5 seconds before boss starts to cast critical raid-wide AOE/tankbuster.

I understands how to customize timeline file but is there a way to make TTS for a specific time? Say 5 seconds after the pull, TTS me on "Tank buster"

**Comment by zplaced** [comment]
oops, timelineTrigger it is

**Comment by quisquous** [comment]
Glad you got it sorted!
