### ISSUE TITLE
caresAboutAOE()

### ISSUE THREAD

**Issue by dvdio** [quisquous/cactbot#3431]
As far as i understand, the condition caresAboutAOE() is only for tank, healer and blu.
How can i add the samurai, or any dps so that i can see the alert warning aoe with them too?

**Comment by Akurosia** [comment]
https://github.com/quisquous/cactbot/blob/6cb3596707531ff0647e6d78d448e0cfbcc90a1d/resources/conditions.ts#L14

Its tank, healer, blu and people that can addle.

Melees usually dont need this information as the majority of AoEs is magical damage and not phisical

**Comment by quisquous** [comment]
Fixed in #3432 to show them for everybody.
