### ISSUE TITLE
I am inable to hear the TTS callouts.

### ISSUE THREAD

**Issue by werewolfboy13** [quisquous/cactbot#344]
I followed the instructions on another ticket to put the volume down on for the callouts. When I did that the volume was to low. I reverted the changes that I did now its to soft I can barely hear the callouts.

Here is the code I changed:
`// Volume between 0 and 1 to play the InfoSound at.
Options.InfoSoundVolume = 1;

// Volume between 0 and 1 to play the AlertSound at.
Options.AlertSoundVolume = 1;

// Volume between 0 and 1 to play the AlarmSound at.
Options.AlarmSoundVolume = 1;

// Volume between 0 and 1 to play the LongSound at.
Options.LongSoundVolume = 1;`

I changed them to .5 and reverted them back. Its sounding like the .5 instead of the 1 if that make sense.

**Comment by quisquous** [comment]
1 just means that it plays at 100% of the volume that Windows wants it to play at.  If you want it to play louder, you need to go into your Windows volume mixer settings and adjust ACT's volume to be louder.  There's not anything else that can be done inside of cactbot.

Let me know if that doesn't work or there's something else I can help with here.

**Comment by werewolfboy13** [comment]
Turning it up to 2 fixed it :). I think it was an issue with the insider builds that I am running. I have put a feedback thingy in. Thanks! Closing.

**Comment by werewolfboy13** [comment]
or not. I don't know whats causing it. ugh.

**Comment by werewolfboy13** [comment]
Im thinking is an ACT problem. Before the program did the shouts at maximum volume. now it looks like its 20% or so by what volume mixer is saying. I can't figure whats causing this. Only experiencing the issue on one machine but with different versions of Windows 10 running (builds) on each machine.

![image](https://user-images.githubusercontent.com/43587009/52373970-b0cca600-2a21-11e9-829d-14d1cf51d333.png)

I may have found the issue. the sound option changed to "Use Windows API Sound" may have fixed it. The middle option is what it was before.

**Comment by werewolfboy13** [comment]
That did fix it.

**Comment by quisquous** [comment]
Ok!  Glad you got it sorted.  Thanks for the update.
