### ISSUE TITLE
Cloud Deck wrong platform

### ISSUE THREAD

**Issue by rrbailey89** [quisquous/cactbot#3453]
## Description

While playing the cloud deck (normal) cactbot would tell me to move to the incorrect platform the entire duration of the instance.

## Additional information

If available, please include any logs or screenshots depicting the issue you're experiencing.

**Comment by quisquous** [comment]
Do you have any network logs or screenshots?

**Comment by rrbailey89** [comment]
> Do you have any network logs or screenshots? @valarnin mentioned [on discord](https://discord.com/channels/551474815727304704/594899820976668673/888408541713551371) that this hasn't changed and was correct a few weeks ago.

If you could please provide me with guidance on how to get those logs I'll queue it up tonight to try and capture what you need as well is get video or screenshots

**Comment by rrbailey89** [comment]
Ran it again, it was wrong about which platform to go to when Diamond Weapon does the jump onto a platform after shedding its armor, and then at least one other time when its doing the laser swipe on a platform it suggested going to the platform that would have resulted in laser death.

I have attached the network log

[Cloud Deck.log](https://github.com/quisquous/cactbot/files/7192841/Cloud.Deck.log)

**Comment by valarnin** [comment]
Just as a heads up, your attempt to anonymize the log file weren't very good. You replaced your name but not your player's ID, which means that someone could just look up the ID to get your player name.

---

East/West callouts triggered 8 times during that encounter.

X = 100 is dead center between the two platforms.
X > 100 is east.
X < 100 is west.

Here's the 8 lines, which trigger they triggered, what the callout was, and what your player's X position was when the trigger fired, and at +5/+10/+15 seconds afterwards.

```json
[{
        "line": "20|2021-09-19T09:35:15.6030000-10:00|400320A2|The Diamond Weapon|5F9B|Adamant Purge|400320A2|The Diamond Weapon|3.70|99.99231|99.99231|-1.055269E-15|3.141497||de14c3b9166f84cfb260879aca9ef071",
        "triggerId": "Diamond Claw Swipe West",
        "callout": "Teleport to east platform",
        "posAtPlus0": 88.33487,
        "posAtPlus5": 88.33487,
        "posAtPlus10": 115.5209,
        "posAtPlus15": 115.6412
    }, {
        "line": "20|2021-09-19T09:35:39.0500000-10:00|400320A2|The Diamond Weapon|5F9A|Adamant Purge|400320A2|The Diamond Weapon|3.70|99.99231|99.99231|-1.055269E-15|3.141497||c71afd6c2ec9977ab7f2214cbc153b18",
        "triggerId": "Diamond Claw Swipe East",
        "callout": "Teleport to west platform",
        "posAtPlus0": 114.9442,
        "posAtPlus5": 116.2087,
        "posAtPlus10": 85.01626,
        "posAtPlus15": 88.20569
    }, {
        "line": "20|2021-09-19T09:37:24.7680000-10:00|400320C4|The Diamond Weapon|5FE8|Airship's Bane|400320C4|The Diamond Weapon|4.20|120|100|6.505213E-19|-4.792213E-05||a1b2fb039de479fc6755d5431e8d3a60",
        "triggerId": "Diamond Airship's Bane",
        "callout": "Teleport to east platform",
        "posAtPlus0": 84.49337,
        "posAtPlus5": 84.49337,
        "posAtPlus10": 82.5898,
        "posAtPlus15": 82.14857
    }, {
        "line": "20|2021-09-19T09:40:17.1190000-10:00|400320A2|The Diamond Weapon|5F9A|Adamant Purge|400320A2|The Diamond Weapon|3.70|100|100|-2.780979E-16|3.141593||63012e06d297e6889a168435d73b66dc",
        "triggerId": "Diamond Claw Swipe East",
        "callout": "Teleport to west platform",
        "posAtPlus0": 87.88223,
        "posAtPlus5": 87.88223,
        "posAtPlus10": 87.88223,
        "posAtPlus15": 87.88223
    }, {
        "line": "20|2021-09-19T09:40:50.7620000-10:00|400320A2|The Diamond Weapon|5F9B|Adamant Purge|400320A2|The Diamond Weapon|3.70|100|100|-2.780979E-16|3.141593||ad17b6a76e82952a4a7648eab76b09af",
        "triggerId": "Diamond Claw Swipe West",
        "callout": "Teleport to east platform",
        "posAtPlus0": 87.88223,
        "posAtPlus5": 87.7897,
        "posAtPlus10": 87.66824,
        "posAtPlus15": 115.7917
    }, {
        "line": "20|2021-09-19T09:42:59.5680000-10:00|400320A2|The Diamond Weapon|5F9B|Adamant Purge|400320A2|The Diamond Weapon|3.70|99.99231|99.99231|-1.055269E-15|3.141593||b45b3e4d862ed51fcd2864bbc6a04681",
        "triggerId": "Diamond Claw Swipe West",
        "callout": "Teleport to east platform",
        "posAtPlus0": 125.8863,
        "posAtPlus5": 125.0844,
        "posAtPlus10": 114.7557,
        "posAtPlus15": 97.0873
    }, {
        "line": "20|2021-09-19T09:43:33.1660000-10:00|400320A2|The Diamond Weapon|5F9A|Adamant Purge|400320A2|The Diamond Weapon|3.70|99.99231|99.99231|-1.055269E-15|3.141593||9b722f9ee012be67f8657f327e7bad13",
        "triggerId": "Diamond Claw Swipe East",
        "callout": "Teleport to west platform",
        "posAtPlus0": 112.2339,
        "posAtPlus5": 86.78625,
        "posAtPlus10": 85.89655,
        "posAtPlus15": 85.82899
    }, {
        "line": "20|2021-09-19T09:45:42.2680000-10:00|400320A2|The Diamond Weapon|5F9B|Adamant Purge|400320A2|The Diamond Weapon|3.70|99.99231|99.99231|-1.055269E-15|3.141593||72ed187a54110f999b25524385f52898",
        "triggerId": "Diamond Claw Swipe West",
        "callout": "Teleport to east platform",
        "posAtPlus0": 122.0315,
        "posAtPlus5": 86.57196,
        "posAtPlus10": 85.4311,
        "posAtPlus15": 87.77824
    }
]

**Comment by rrbailey89** [comment]
> Just as a heads up, your attempt to anonymize the log file weren't very good. You replaced your name but not your player's ID, which means that someone could just look up the ID to get your player name.
> 
Thanks for letting me know, I removed the log

**Comment by rrbailey89** [comment]
https://www.youtube.com/watch?v=pjuJi6b1Oiw
video of it saying go to wrong platform for the jump part

**Comment by Akurosia** [comment]
I tried it like 2min ago and at least for the german callouts i can say that everything works like expected (payed extra attantion to each east/west callout).

**Comment by Akurosia** [comment]
> https://www.youtube.com/watch?v=pjuJi6b1Oiw
> video of it saying go to wrong platform for the jump part

In your video cactbot gives the correct callouts. The callouts are for 99% of all fights true north and are nearly never based on your facing position.
The game told you on the first one to go to the East as the boss was cleaving west side (blue plattform).
After this the second one (where you are on the east plattform) he cleaves east so cactbot told you to go west.

**Comment by valarnin** [comment]
At this timestamp, the callout says to go east (for platform destroy) but east is the platform being destroyed.

https://youtu.be/pjuJi6b1Oiw?t=170

**Comment by Akurosia** [comment]
Its the ''Diamond Airship\'s Bane'' trigger which only has the east version

**Comment by rrbailey89** [comment]
I'm still not sure that the platform destroy trigger is an issue only I am expierenceing and it's a bug on my side or if it's legitimately something that should be corrected. I think more people who use this program need to run it and report findings.

**Comment by quisquous** [comment]
Looking at logs, it seems like `Airship's Bane` is both `5FFE` and `5FE8` right after one another.  The extreme version doesn't have a callout for this mechanic, so I'm wondering if maybe it's wrong to say "go east" and maybe the normal version should be removed also? (Extreme ids seem to be `5FFE` and `5FD3`).

**Comment by Akurosia** [comment]
Ichecked all my log and found the same results. I would remive the trigger as its also obviouse where to go and the indikator is up early enough in game.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
