### ISSUE TITLE
Most triggers don't work in BA

### ISSUE THREAD

**Issue by ImMoa** [quisquous/cactbot#3464]
## Description

There is some problems about tiriggers when in Baldesion Arsenal.
Triggers work for few things Like 'Pop Eurekan Potions', 'Damage Reduction', and others not.
But timeline works fine also damage log.
In other raid it perfectly work but only in ba, not work properly.

## Additional information

I'm playing ff14 in JP
Main language in cactbot is Korean.

### RaidBoss
Trigger lang is same as main lang.
Timeline lang is Japanese.
And attach BA network log.
[Network_22105_20210922.zip](https://github.com/quisquous/cactbot/files/7209229/Network_22105_20210922.zip)

**Comment by ImMoa** [comment]
## Additional Info
Just checked trigger stop after 1st Boss.
Works fine at 1st boss.

**Comment by quisquous** [comment]
Sorry for the belated response.  Is this still happening?

**Comment by quisquous** [comment]
Is this still happening? Did this work for Raiden? When I load this in raidemulator, I see 
![image](https://user-images.githubusercontent.com/462317/178371624-a7a7edd3-2ce7-4a80-b16c-f378a1e24f1e.png)


@valarnin From looking at the log, it looks like this log gets into Absolute Virtue (e.g. `|3798|`), but there's only Ovni/Owain/Raiden when loading it in raidemulator.

**Comment by zedekblue** [comment]
I can confirm this is still happening, and has been for quite some time. Sometimes the timeline for art/owain just never ends, and I will get random "STOP MOVING" raidalerts during hallways.
I will try to get a smaller log with only one BA run included later, however I do have a network log (178MB) containing two whole runs here: https://drive.google.com/file/d/1TEFwPbp1sbOyxsRGeHn4BGXMDDBn1m-K/view?usp=sharing

**Comment by quisquous** [comment]
Sorry for not getting around to fixing this. I'm trying to consolidate eureka issues in #4904.  If you have any other comments, please leave them there.
