### ISSUE TITLE
Fishing overlay could use more colors/columns?

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#347]
e.g. 
![image](https://user-images.githubusercontent.com/462317/52189413-5e0aa880-27ed-11e9-82bb-704895f913c3.png)

This has four fish, and the two fish of the very similar color are overlapping, which makes it a bit read the UI.

Would it worth be having like 3-4 columns instead of 2? And maybe a set of colors to pick from that are more distinguishable?

**Comment by quisquous** [comment]
:stuck_out_tongue: 

I still think that even if the colors are meaningful, there could be more columns and more variety of colors.

**Comment by ArkfrostLumas** [comment]
I have a suggestion. As it is now, the windows for each fish biting are overlapping like this:

![v1](https://user-images.githubusercontent.com/39298126/52903601-3a4d5680-3220-11e9-92a1-80058d092e52.png)

What would be great, would be if first of all, the bars for each fish didn't overlap and secondly, every fish had its own colour so you can foresee, which fish is biting in most cases, by simply omitting fish in the wrong window. Could look like this:

![v2](https://user-images.githubusercontent.com/39298126/52903624-7a143e00-3220-11e9-94b1-cf7af4fe415d.png)

**Comment by xephero** [comment]
The color coding (and columns) are green/yellow/red for light/medium/heavy tug. They overlap when, for example, two light-tug fish can be caught in the same timing window. I wasn't super confident in the design, so this is helpful discussion.

If they're all separate colors, that helps distinguish them from one another, but loses the ability to predict what kind of fish a bite actually is before hooking it. I could simply get rid of the three columns, and have ten distinct columns on the left for each fish, and keep the color coding by tug strength. I'll play around with it and see if it looks good. In the mean time, I'm very open to design suggestions!

**Comment by ArkfrostLumas** [comment]
Or you can make colour groups. For example:

- Light tugs are: Indigo, Slate Blue, Dark Blue, Royal Blue, Cornflower Blue, Sky Blue, Light Blue, Magenta
- Medium tugs are: Khaki, Yellow, Orange, Yellow-Green, Dark Khaki, Gold, Brown
- Large tugs are: Firebrick Red, Bright Red, Dark Red, Light Coral, Indian Red, Crimson

This way, you still know: Blueish group is light, Yellowish group is medium and red'ish group is large in tugs.

**Comment by Tataru-Taru** [comment]
I know this hasn't had an update since Feb, but I was just wanting to say that I love the idea of adding more scope to the addon. At the moment it feels very busy and the mockup by Arkfrostlumas would at least show the windows of each fish. 

Would definately agree that tug needs to be displayed using a colour group banding like Arkfrost has mentioned.

**Comment by quisquous** [comment]
Thanks for the feedback that you would be interested in this. I really haven't had much time to improve this lately, but I would happily support pull requests if somebody else wanted to take a stab at improving it.
