### ISSUE TITLE
Raid Overlay only work with dummies.

### ISSUE THREAD

**Issue by THEFOXSGREED** [quisquous/cactbot#349]
Hello there,
Just wondering why my Raid Overlay only work with dummies ? I setup everything like it is in the installation guide but nothing to do. 
I can't find other people in the same situation as me so it's really annoying. 

Thanks ! 

Note : I'm using the latest version of ACT, same for Cactbot and Cactbot is my only plugin on ACT.
My game is in French, maybe it's why I don't know.

**Comment by quisquous** [comment]
I'm going to close this old bug for now.  Please leave a comment if this is still happening.
