### ISSUE TITLE
Huge fps drops while using cactbot.

### ISSUE THREAD

**Issue by NotKawaii** [quisquous/cactbot#352]
It starded a while ago, im having a bunch of drops if i use cactbot overlay. I already looked up to some other threads in here and my update interval is already at 0. It started at some point near 4.5. Any tips or something i can do to find the issue?

Thankls in advance.

**Comment by quisquous** [comment]
Could this be similar to issue #71?

**Comment by quisquous** [comment]
Also, are you using the enmity plugin? Or, how many overlays do you have? If you only use raidboss but nothing else, is it fine? (Just trying to debug from afar.)

**Comment by NotKawaii** [comment]
Sorry about not answering before, yeah Im using more than one overlay. I have a pretty old CPU and when I use act + special spell timer it's fine. But when i run both overlays there's a lot of lag (fps drops) caused by my CPU beeing at 99%.

There is any way to let my GPU take care of the overlay? I have a Pretty decent GPU and I usually use 30% of my GPU playing the game. So there's plenty to render the overlay. I don't know if this is possible but it would be great if I could use my GPU.

I love cactbot but I stopped using  because of my shitty CPU.

I have a i7 2nd gen (2600) and a RTX 2060, I will do a upgrade at the end of the year but I don't have the money to do yet. If there's any other info you need to try help me out just ask. Thanks in advance.

**Comment by quisquous** [comment]
Have you seen issue #71? That's one thing that a lot of people have run into.

cactbot really isn't any different than running Chrome simultaneously, so 99% cpu seems like something else is going wrong.

**Comment by NotKawaii** [comment]
Yea, i saw that issue but mine is not similar. I used to have 2 monitors but at the moment im using just one and the refresh rate is 60 not 144. I use Special Spell timer and cactbot, the cpu goes high when im doing some contents like seiryu. So i thought was just a CPU problem.

Already tried deactivating other overlays, didnt worked.

**Comment by quisquous** [comment]
Is this still happening for you? I've had a report that the ngld overlayplugin makes this a bit better, so I'd be curious if using that fixes that as well.

**Comment by NotKawaii** [comment]
Not having this issue anymore, ngld plugin makes everything smoother. My CPU is old and his plugin is a little better performance wise so that fixed for me o7

Thanks for asking tho.
