### ISSUE TITLE
Eureka flags not showing up

### ISSUE THREAD

**Issue by ZonihaDarkness** [quisquous/cactbot#3524]
## Description

Eureka map overlay flags doesnt persist. Not fairy locations nor any /shout flag.

## Additional information

I noticed that if I teleport to a aetheryte and near it there's a fairy it shows up for a microsecond and then its gone.
On overlay.dll flags are set to persists for 60 seconds.

**Comment by quisquous** [comment]
This should be fixed by #3495 and in the next release.

**Comment by quisquous** [comment]
Please comment back if this is not fixed, but it seemed to work fine for me.

**Comment by quisquous** [comment]
What options do you have on for Eureka? Could you screenshot it for me?

Also, are there any errors in the overlayplugin log when this happens? You can `/echo something <pos>` to generate a flag if you need to easily.
