### ISSUE TITLE
General Cactbot Lag

### ISSUE THREAD

**Issue by ArkfrostLumas** [quisquous/cactbot#353]
Soooooooo...
Here I am to write a question I'm having for some time already, due to some suspicions I've had. Since the first day I've been using Cactbot, from time to time, the whole ACT gets laggy and not fluid like seen on many videos.

First of all, here's my setup:
i7-7700K
GTX 1070
16GB RAM
Also, I'm using 2 monitors. A 144Hz acer Predator and a 60Hz Philips TV.

Then, let me continue with my fix-attempts:

- First of all, I've tried setting the dps update interval in ACT in the cactbot overlays to 0 instead of default 3, which already helped with some major lags, but didn't solve the problem completely.

- Then I've read about the NVidia dual screen bug on Win10, that occurs, when one screen has 144Hz and one has only 60Hz. I've tried to fix that like in the link you've posted under another comment, by plugging in the TV into my mainboard (enabled it via BIOS), while the main PC screen is still in the GPU. Also, I've set the Display to 120Hz.
Nothing has changed.

- I've also checked, the CPU priority of ACT in ACT itself and it is set to above normal

And now I'm a bit clueless, what the problem might be. Things where the lag is noticeable:
- When I'm using the raidboss plugin, occasionally the lag gets so severe, that callouts or even sound cues get delayed by several seconds. TTS callouts get choppy and especially in combination with the ACT Discord Triggers plugin it barely works consistently
- Also, bars like in the fisher plugin or the raidboss timeline section fill pretty choppy and un-fluent. I've made a video with my phone (since neither OBS nor Fraps seem to capture the overlay) how it looks:
http://sendvid.com/ruxde795

Now I'm out of clues, what causes this problem.

**Comment by quisquous** [comment]
Oof that fisher video is heartbreaking.  :C

Re: the dual screen bug.  Have you tried only using one monitor, just as a debugging check?

What plugins are you using? One thing I've had issue with in the past has been the enmity plugin (if running with all defaults).  Do cactbot plugins lag if they're the only one?

**Comment by ArkfrostLumas** [comment]
Yup and that's what I'm going through with raidboss for quite a while as well.

I have tested it right now with only one monitor, but that didn't help. It's still lagging and from what I've experienced, the more fish you have caught in a spot, the heavier the lag.

I've tested another thing by the way: 
For months now I've been experiencing some kind of stuttering in FFXIV, like a 0.05s freeze every 3 seconds. I've googled around and I've found out, that is due to the most recent NVidia Drivers all being trash for FFXIV. I had to roll back from NVidia Driver version 418.91 all the way to NVidia Driver version 388.71 via uninstalling the driver with DDU and manually installing the older driver.
This completely fixed all the game-stuttering, but sadly it didn't resolve the Cactbot lags in any way.

I've also tried uninstalling and re-installing ACT and cactbot as well, but to no improvement whatsoever.

I'm only using the ffxiv parsing plugin and Cactbot, because Cactbot is all I need. Even for parsing I use Cactbot as base.

The plugins that are active are Raidboss, Eureka, DPS Parser and Fisher.

**Comment by quisquous** [comment]
When you say "plugins that are active" what do you mean? What is an inactive plugin? If you only have a single cactbot plugin, how does it perform?

You don't happen to have any weird ACT options set like Dump all Network Data to Log file?

**Comment by ArkfrostLumas** [comment]
With active plugins I mean the modules (raidboss, eureka, etc.) are installed in the OverlayPlugins page. I didn't bother installing any other modules because I don't need them. 

If I only install 1 single cactbot plugin (like Fisher) it doesn't change anything.

Where is that option? At least I'm pretty sure I didn't turn anything extra on that wasn't on by default or instructed to me.

And as mentioned before in Discord, the fisher overlay plugin and raidboss plugin only lag, while the game is in the foreground. When I tab out of the game, the plugins perform perfectly smooth.

**Comment by quisquous** [comment]
[cactbot-test-always-active.zip](https://github.com/quisquous/cactbot/files/2872585/cactbot-test-always-active.zip)

Here's a build of cactbot that always believes that ffxiv is up and active if you want to try having it up in front of other 3d games, etc.  Otherwise, I know it hides so it might be harder to test out.

**Comment by quisquous** [comment]
Mostly I just put this up so that you can definitively verify that it's FFXIV and not other fullscreen games.

**Comment by ArkfrostLumas** [comment]
Hmmm... Okay... And how do I use it?
I mean, I need some kind of bars, like the fisher bar running, to verify, if anything is slowing down cactbot.

**Comment by ArkfrostLumas** [comment]
BIG UPDATE!
It was in fact NVidia Inspector, as I assumed!! I re-installed NVidia Inspector, went into that extremely tiny crossed tools icon in the middle (profile settings) and on the top I found a drop-down list with a few thousand games inside. One of them was FFXIV and there is also an NVidia button at the top which's tooltip says "restore to NVidia Defaults". Selected FFXIV, pressed that button and a few settings changed. 

And now look at this gorgeous thing:

https://streamable.com/bnh4u

I even tried it out in Kugane at the Piers #1 where everyone is standing around, queueing for Eureka and there is absolutely zero slowdown <3
Even my heavy load android emulator doesn't have choppy sound anymore and neither do YouTube videos lag even at 60fps x)

**Comment by quisquous** [comment]
HECK YEAH! Nice work!!!
