### ISSUE TITLE
RE: Tankbusters always sound

### ISSUE THREAD

**Issue by kaedys** [quisquous/cactbot#3531]
## Summary
This is regarding https://github.com/quisquous/cactbot/pull/3432, and the change to remove the "CaresAbout" conditionals.  This appears to be somewhat inconsistent, as some conditions (ex. [Pillory](https://github.com/quisquous/cactbot/blob/main/ui/raidboss/data/05-shb/dungeon/holminster_switch.ts#L34) in Holminster Switch) are still using an ad-hoc version.

However, the point is more around the "well, if users don't like it, they can disable it" conclusion.  The issue, for me, is that I play multiple roles.  I _don't_ care about tankbusters as a DPS, but I very much _do_ care about them when I'm tanking or healing.  I'd like to propose either:

* A global "don't show tank alerts as DPS" option (and maybe also one for healer and tank, but eh).  This would apply to tankbusters for sure, and _maybe_ also tank cleaves and other tank-centered effects that DPS generally don't have to muck with.

OR:

* A new enhancement to the config in the UI that lets the user specify that the alerts should only fire for X roles.  This would be be a series of checkboxes (probably a horizontal row, but UI design isn't my forte) listing the 5 roles in FFXIV (tank, healer, melee, ranged, caster).  Default checked state could be all on, or defined by the trigger, or only tanks and healers, whatever seems to make the most sense.  But that would let users directly control whether each trigger showed for any given role, without having to manually go in and change them every time they decide to swap to tanking or healing for a change.
  * Edit: also, the intent with this one is that it'd apply globally to _all_ alerts, providing the customization regardless of the alert type (ex. if DPS or tanks don't care about general raid AoE hits that are there mostly just to give healers something to do).

Personally, I prefer the second option, as it affords the greater amount of control and flexibility (ie. can set a tankbuster on one fight to show but not on another, depending on relevance to your role), but I'm not sure on the relative effort between the two, or which y'all feel would make more sense from a UX perspective.

**Comment by kaedys** [comment]
> As with nearly everything, it's a tradeoff.

It's a fair point.  And mine apologies if I made it sound like this is merely stubbornness on your part.  As you say, I think this ultimately comes down to a judgment on how many users are likely to engage with the feature, versus how many are not.

The current options for customizing notifications are fairly basic, being confined to a handful of options as far as alert type, and then an option to set the actual text displayed.  All other customization requires at least some knowledge of and comfort with editing code files.  While the actual implementation of those custom triggers is likely something you (and I) find to be quite easy, from a mechanical perspective, I know many who would be overwhelmed by the mere prospect of trying to put together a custom trigger, regardless of how many help comments and examples were given, and regardless of how much of it was, tbh, essentially copy-paste with some tweaking.  I think software engineers like you and I sometimes forget how daunting looking at code can be for those not familiar with coding as a concept.

> That's why "maintain this feature across all triggers" has a cost.

But that was really my point.  Handling this on a trigger-by-trigger basis is a _huge_ amount of work, both now and for every single feature going forward.  If, on the other hand, this were implemented in a single common function that all of the triggers leverage (or even a handful of them), like the same config set you store the existing options for displaying text, sound, and/or TTS, that the solution would be a set-it-and-forget-it without needed maintenance except where code that affects it actually changes.  The default for triggers without a configured set of options could be all-roles-selected, and then maybe the triggers could override it if the trigger needs to be specific (but you'd only need to define it for triggers that _are_ specific, and only if you want to go that direction; the existing role conditions are probably fine if you don't).

Now, unfortunately, I don't know Typescript (or Javascript, for that matter, my primary language is Go), and looking over the code for this plugin is in fact the first time I've encountered Typescript code, else I would have simply PR'd the changes by now.  I have a vague idea of where the code for it might live and how it might work, but my knowledge of TS simply isn't up to the task ('yet', potentially).

> The changes and the workaround are both roughly the same set of work.

Only if you presume the only possible solution on the plugin side is to edit every single trigger.  And that's not what I'm proposing.

I'm proposing a new option created (I'd assume this would be in a single place, as I assume each trigger simply uses a template to generate its options section in the UI), and then the selection for those would be leveraged in a single or possible a handful of places, depending on how the triggers are actually handled (tbh, it's a bit difficult following the program flow, not knowing the particulars of TS syntax), where in some common function each of the triggers ultimately passes through before being displayed, it would check that optionset and simply return without doing anything if the player's role did not match the optionset.  If the ability for triggers to set a default set of roles (thus obviating the need for role-based trigger conditions, though that's an optional enhancement, imo), that would be handled when generating the UI options, in much the same way that triggers can define the default alert text, duration, etc (which can then be overridden by the user).

Can you not see how there's a world of difference in the effort required between copying 70+ triggers, probably _per expansion_, versus implementing a single approach in a common function that automatically applies to all triggers merely by virtue of their existing templating?

**Comment by quisquous** [comment]
Coming back to old issues.  I'm sorry for the disagreement here, but if this is something that you want I think your best bet is to fork cactbot and implement it yourself.  I haven't heard anybody else ask for this or complain about the tankbusters in endwalker.
