### ISSUE TITLE
[Question] Timeline bars emptying instead of filling

### ISSUE THREAD

**Issue by Nitrodroki** [quisquous/cactbot#354]
I have seen a stream a while ago where the bars in the timeline would reverse when the boss did the spell (like nael "dive then in", it was a bar that was emptying instead of filling while the animations were ongoing)

I asked the streamer and she didnt remember changing anything because mine is just bars filling. Is it a custom setting or something I can opt in into ?

**Comment by quisquous** [comment]
The bars reverse on any timeline entry that has a duration.  Most things don't have a duration and just have the time for when the ability ends.  You can see this in the Summerford Farms test timeline for the Long Castbar: https://github.com/quisquous/cactbot/blob/master/ui/raidboss/data/timelines/test.txt#L22
