### ISSUE TITLE
TEA Fate Calibration Alpha does not work

### ISSUE THREAD

**Issue by RainEpocan** [quisquous/cactbot#3569]
## Description

Description of the issue you're seeing.

## Additional information

If available, please include any logs or screenshots depicting the issue you're experiencing.

**Comment by RainEpocan** [comment]
Fate Calibration Alpha does not work 100% of the time. For instance a wipe occurred today because it showed I had no de buff, when in fact I was the shared sentence. It's happened on numerous occasions with raid members who use the same application. Thank you

**Comment by quisquous** [comment]
The log from #4212 appears to be working, so I don't think this is a general problem.  Please attach a network log where it is not working if this is still an issue.
