### ISSUE TITLE
raidboss: Blue Mages should care about tank/healer alerts

### ISSUE THREAD

**Issue by Serity** [quisquous/cactbot#3582]
## Description
Alerts restricted to `data => data.role === 'tank' || data.role === 'healer'` (such as Tankbusters) don't fire for Blue Mages.

## Additional information
I feel like all Blue Mages should have access to tank-focused callouts, since all roles often take White Wind and Diamondback, and depending on the content (or level of mages), there may not even be a Mimiced: Healer or Tank (or, indeed, any Aetherial Mimicry at all), but at the minimum, if possible to detect, Healer and Tank-roled Blue Mages should get the callouts.

**Comment by quisquous** [comment]
I think this is mostly fixed.  If there are individual triggers that need to be fixed, feel free to send PRs for those.
