### ISSUE TITLE
Fisher module error

### ISSUE THREAD

**Issue by arlarzelere3** [quisquous/cactbot#359]
`2/18/2019 6:12:58 AM: Info: fishing: BrowserConsole: Uncaught TypeError: Cannot read property 'id' of null (Source: file:///D:/Advanced%20Combat%20Tracker/PlugIns/OverlayPlugin/cactbot/ui/fisher/fisher.js, Line: 203)
`

Fishing at the Comet's Tail in the fringes.
Was undiscovered when I started.
Stopped fishing and restarted, module didn't show any content.
Restarted both ACT and FFXIV and got the same error.

**Comment by arlarzelere3** [comment]
Tried again in Western Coerathas (West Banepool specifically) and it appears to be working now

I'll leave this up in case it's specific to Comet's Tail

**Comment by someONEgood** [comment]
Can confirm also had this same scenario. I went and tested Comet's Tail as well.
Also undiscovered. Module didn't show content.

I got a similar error when fishing at Hell's Lid which WAS already discovered:

_2/18/2019 11:05:58 AM: Info: Fishing Overlay: BrowserConsole: Uncaught TypeError: Cannot read property 'id' of null (Source: file:///[Shortened Install Path]/fisher.js, Line: 203)_

Overlay is unresponsive at Hell's Lid. Doesn't even appear.
I wonder if this is related to how FF14AnglerRep won't hook in unless you load it shortly before or after launching the game?

Also is it intended that you have to populate the columns manually by fishing at the zones?
My left side meters don't appear until I've fished the locale myself several times.
If so, is there a way we could consolidate info? A repository to merge the .js files or wherever the timelines are stored?

**Comment by quisquous** [comment]
Looks like the issue is the apostrophe in the name.  Thanks for the report.

At the moment, you have to manually fish at the zone to populate it, yes.  @xephero said that he wanted to consolidate info eventually, but that likely meant setting up some server and a bit more work.  Eventually!
