### ISSUE TITLE
TTS Doesn't work for me

### ISSUE THREAD

**Issue by jurias90** [quisquous/cactbot#3590]
Hello,
I've been using cactbot for a while now and one of the issues I had recently is that raidboss won't play TTS. I have tried enabling it inside of user/raidboss.js.  I have also set inside of cactbot overlay settings to text and TTS and to no avail. One of the suggestions from my friend was to set the specific fights I want to use to TTS only or text and TTS but it doesnt work. It all gets overlapped by a bell noise. I am wondering if it's I who did the error and did not install something correctly. I have uninstalled cactbot and act from my comptuer and started from scratch but nothing. No TTS.

**Comment by quisquous** [comment]
cactbot uses ACT's tts mechanism.  Does that work for you, if you make a custom trigger, add some text, and hit play?  If you're still having trouble, I recommend the ACT FFXIV Discord to help get your ACT tts sorted out.

**Comment by quisquous** [comment]
If this is still an issue, you should check with the ACT FFXIV Discord.
