### ISSUE TITLE
Fishing overlay randomly displays empty fish timings

### ISSUE THREAD

**Issue by Neraud** [quisquous/cactbot#3598]
## Description

The fishing overlay sometimes "forget" the fish timings for a location.
It seems to think I've changed location, bait or buff and displays an empty list of known fish timings.
I've produced the issue during ocean fishing, 2 days in a row.

Everything was working fine before last update.

## Additional information

I've captured the issue a few times on video : https://youtu.be/qP-pFbR6UlU
For this example, I've kept the same bait and didn't get any buff for the whole duration.

I've also uploaded the ACT logs, if that can help : https://gist.github.com/Neraud/ff0d7ad35561c719728c64377ee88a46

**Comment by quisquous** [comment]
I tried reproducing this myself with fishing in various places but couldn't do it.  If this happens again, can you check the OverlayPlugin log messages? e.g. ACT -> Plugins -> OverlayPlugin.dll -> log window at the bottom?  My guess is that there's some error that's happening.

**Comment by Neraud** [comment]
I've tried again in Ocean Fishing.
No logs in the ACT Windows (I cleared them before fishing, and nothing appeared).

Also, the issue seems to trigger at the same time for someone else in my party.

I haven't tried fishing in other zones.

**Comment by frstndrd** [comment]
Also having this issue. Just to add, I also noticed that issue while fishing in the Northwestern Caliban Gorge (The Tempest). Sometimes the overlay won't go empty, but its info gets inaccurate (it forgets the data you had for one fish and said fish is listed at the bottom again).

Log window is empty. I tried tweaking with self/everyone else's fishing messages, and it had no effect.

**Comment by Neraud** [comment]
Reproduced in a controlled case.

If someone near you uses chum, it's detected as your own.
I could see `handleChumGain` and then `updateFishData` (with chum = true) getting called.

**Comment by quisquous** [comment]
@Neraud Thank you for the detailed debugging.  That was exactly it.  Sorry for the hassle!

**Comment by Neraud** [comment]
No worries, thanks for the fix !
