### ISSUE TITLE
Raidemulator Generates Error on Loading UCOB Encounter

### ISSUE THREAD

**Issue by Datachange** [quisquous/cactbot#3599]
In Raid Emulator (https://quisquous.github.io/cactbot/ui/raidboss/raidemulator.html?OVERLAY_WS=ws://127.0.0.1:10501/ws), whenever I try and load any of the UCOB encounters from my [Log File](https://drive.google.com/file/d/1V-RoP5NL_HtLF8j4rtrosXfn3zQxg0Nk/view?usp=sharing), I get an error in Chrome (it may take attempting to laod an encounter more than once):

`Uncaught (in promise) undefined`
`Promise.then (async)`
`(anonymous) @ dexie.mjs:1239`
`setCurrent @ RaidEmulator.ts:39`
`setCurrentByID @ RaidEmulator.ts:49`
`(anonymous) @ raidemulator.ts:221`
`Promise.then (async)`
`(anonymous) @ raidemulator.ts:218`
`dispatch @ EventBus.ts:56`
`(anonymous) @ EncounterTab.ts:245`

Even when I clear the DB and reload the file, I get the same problem.

Other zone's "encounters" work. (Do not attempt the Nandi from Limsa, it crashes the emulator.)
So... it is just the UCOB ones.
I wish I could do more investigative work to help, but that's all I have for now.

Thank you very much for your help and support!

**Comment by Datachange** [comment]
If I put a breakpoint on this line...
https://github.com/quisquous/cactbot/blob/d8dcdce911d29f6ba0300d01af185f5ad3c87988/ui/raidboss/emulator/data/AnalyzedEncounter.ts#L229
... with the condition: `currentLogIndex = this.encounter.logLines.length - 1` then step manually through for each player (8 times), the fight parses just fine without any errors! ...I don't get the tiny vertical bars below the timeline showing the triggers, but that's fine!

I don't know if this helps, but I figured I'd say something.

**Comment by quisquous** [comment]
This will be fixed by #3286.
