### ISSUE TITLE
Eureka overlay error since 0.9.2

### ISSUE THREAD

**Issue by Akurosia** [quisquous/cactbot#360]
since the new release i get following error everytime i move inside eureka:
18.02.2019 22:38:14: Info: Eureka: BrowserConsole: Uncaught TypeError: Cannot read property 'style' of undefined (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin/cactbot/ui/eureka/eureka.js, Line: 2194)

**Comment by Akurosia** [comment]
Small bumb as the issue still exists (did a fresh install of act)

**Comment by quisquous** [comment]
Sorry for the delay in getting back to this.  @ArkfrostLumas also reported seeing this issue.  I'm looking through the code, and I can't quite tell how this would happen.  Nothing significantly changed in any of this logic...

Do you get any other errors before all of the style property errors? Or is there anything else in the log?

**Comment by schebbi** [comment]
My girlfriend uses german game client and ACT, she had the exact same error (any move in Eureka pops X errors, Map not working). Since i tried my files on her PC and it didnt work, the only difference was ACTs set language. After changing it to english, all seems to be working now without errors.

Not sure how raidboss and other plugins are gonna react to this now though.

**Comment by Akurosia** [comment]
i think i saw 1 additional error message but its to fast gone.
Current issues are only in hydatos:
 - the error messages already described
 - random fate pop sound

I can try to capture the log today and send i to you.

As a side note, it seams we need more german testers for cactbot :P

**Comment by Akurosia** [comment]
this is the other error:
25.02.2019 20:36:23: Info: Eureka: BrowserConsole: Uncaught TypeError: Cannot read property 'replace' of undefined (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin/cactbot/resources/regexes.js, Line: 48)

**Comment by cfxxldev** [comment]
The error caused by these lines:
```
      if (nm.spawnTrigger)
        nm.addRegex = Regexes.Parse(nm.spawnTrigger[this.options.Language]);
```
for the nm "Tristitia" only nm.spawnTrigger["en"] is defined. This causes InitNMs() to exit before this.playerElement can be initialized.

One Solution(other than adding the missing spawnTrigger) could be to change the code like this:
```
      if (nm.spawnTrigger && nm.spawnTrigger[this.options.Language])
        nm.addRegex = Regexes.Parse(nm.spawnTrigger[this.options.Language]);
```

**Comment by Akurosia** [comment]
newest commit fixed the issue. 
Will be fixed with the next release or if you update the eureka.js file manually
