### ISSUE TITLE
Feature request: Better oopsyraidsy tracking

### ISSUE THREAD

**Issue by sparkymotive** [quisquous/cactbot#361]
It would be nice to have the ability to scroll through each pull, like with < and > buttons or something along those lines.

Also the ability to export said pulls to a .txt file would be tops.

**Comment by quisquous** [comment]
Mmm, thanks for this idea!

One other thought I had was maybe making it possible to open up the results in a browser.  Possibly also being able to paste in a twitch link and autolinking to time stamps in a video?

**Comment by sparkymotive** [comment]
Both of those sound :italian_hand:

We use twitch clips alot for mistake tracking.

**Comment by quisquous** [comment]
I think if I move to ngld's overlay plugin where you can also use websocket, this idea of being able to open up results in a browser will make a ton more sense.

**Comment by quisquous** [comment]
I think the summary view addresses this.
