### ISSUE TITLE
Something with Cactbot TTS isn't working

### ISSUE THREAD

**Issue by RosemaryCatbutt** [quisquous/cactbot#3628]
What is the problem?

In game when I use something that should trigger a TTS it doesn't work. It makes no sound. It makes no cache either when actions are running. The timers work. I have tried setting the setting just to TTS, to sound, to text and TSS, etc. 

 HOWEVER, I can make a custom trigger and that works.

I have done a complete clean install 5 times. Like purge all the documents hard reinstall. 

This is either a bug or a setting that needs to be checked, but what confuses me is that a custom trigger works while the default triggers don't work. I've looked everywhere and compared my ACT with my FC mates to compare settings.  The files are not being corrupted and the log file works fine.

**Comment by quisquous** [comment]
Sorry for not following up on this sooner.  Hopefully you have gotten this sorted.  If you are still having issues, please check with the FFXIV ACT Discord for more direct support.
