### ISSUE TITLE
fisher: mooching doesn't show any fish bars

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#363]
The fisher overlay seems fine when using bait directly, but doesn't seem to record anything when mooching.  I tried on several different fishing holes.

![image](https://user-images.githubusercontent.com/462317/53296365-c9c7ac00-37c2-11e9-84eb-cef0ecc94622.png)

**Comment by someONEgood** [comment]
I went and tested this as well.
Can confirm mooched hedgemole cricket doesn't populate the columns or the rows.
Weirdly enough though, mooched Bullfrog does populate the row timer, but the column remains empty.
Dunno if you experienced the same?

What other places did you test? I can try them as well.

**Comment by quisquous** [comment]
I just filed it while testing other things in that area, so I didn't test other areas.  I also only got one Bullfrog mooch, so can't speak to that either.

**Comment by mabako** [comment]
From what I've observed with mooching, when you actually reel the catch in, the bait is changing from the fish to 'undefined' often (but not always).

**Comment by quisquous** [comment]
Ok, following up, I think this sometimes fills in, but not always.  It may be related to what mabako says above with the bait changing to undefined (sometimes).
