### ISSUE TITLE
UCOB Nael dive callouts aren't properly formatting directions

### ISSUE THREAD

**Issue by Sarvadi** [quisquous/cactbot#3630]
## Description

When you get a dive, a sample callout should (and used to) be "Go to NE with marker". Currently, the callout is "Go to dirNE with marker".

Description of the issue you're seeing.

## Additional information

This is caused by changes from 032cf59c1f9081c95d06f91d5033e308709705ff.

**Comment by Datachange** [comment]
Something seems wrong with the Outputs variable or how it is used.
I say this because in my user file...
```
Outputs.dirN = 'North';
Outputs.dirNE = 'Northeast';
Outputs.dirE = 'East';
Outputs.dirSE = 'South';
Outputs.dirS = 'Southeast';
Outputs.dirSW = 'Southwest';
Outputs.dirW = 'West';
Outputs.dirNW = 'Northwest';
```

...doesn't seem to do anything.

**Comment by Datachange** [comment]
https://github.com/quisquous/cactbot/blob/d8dcdce911d29f6ba0300d01af185f5ad3c87988/ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.ts#L1239-L1245

Since data.naelMarks is now ['dirNE',dirSE','dirW'] (for example) dirXX is not being translated using outputs correctly.
