### ISSUE TITLE
Ways to detect if ID or name is someone in party? Also, stopping encounters via cactbot

### ISSUE THREAD

**Issue by gaogaostegosaurus** [quisquous/cactbot#364]
(I thought I posted this but I don't see confirmation of this anywhere... if it was actually deleted for a reason and not just me forgetting to post the submit button, sorry.)

I'm playing around with making plugins and I was trying to see if cactbot has a way to tell if a player (by name or ID) is in the party/alliance or not. I couldn't find it. Am I looking in the wrong places?

I also noticed that cactbot can tell when XIV says we're in combat. Is there a way to tell ACT to end or start encounters via cactbot? I looked for it but couldn't find it.

**Comment by quisquous** [comment]
At the moment, there's no way to know if somebody is in your party or not or even the list of people in your party.  I know some other plugins have this, but I haven't dug up the memory signature to look for this.

I think there are some ways around it at the moment if you're desperate, such as seeing who friendly aoes like protect/succor/etc all hit, but that feels like a hack.  For example, the ucob triggers look to see who has been hit by heavensfall to get the full party list.  <_<

Sorry that this doesn't exist.  It'd be useful, but it just hasn't sounded *so* useful that I've gotten around to adding it.  What did you want to use it for in particular, just so I can understand your use case?

Re: ending encounters.  If you're talking about dps-related things, cactbot auto-stops encounters on wipes and clears.  It doesn't currently auto-stop encounters for things like multi-boss alliance raid zones.  Doing it just on in combat vs not would maybe be too much, as you don't want like every trash mob in eureka to be its own encounter either.  What in particular do you wish auto-stopped that currently doesn't?

**Comment by gaogaostegosaurus** [comment]
I'm writing some custom plugins and it would just be useful if I can identify an action either coming from or going to a party member. Can't seem to quite remember at the moment what I was thinking to use it for though... I play around with triggernometry sometimes and I just noticed that it was a thing there for some reason and not here.

For the encounter stop - it's not something I wish on everyone (not requesting it to be part of cactbot); I'm just wondering how it's done. I'm playing around with making my own things and it is one of the things I know (or at least I think) cactbot does, but I don't know how it works.

**Comment by quisquous** [comment]
Yeah, I think triggernometry looks at the memory location for that or somehow secretly gets it out of ACT in a way that I can't find.

For encounter stop, https://github.com/quisquous/cactbot/blob/master/CactbotOverlay/CactbotOverlay.cs#L95 is the function to call in ACT.  It's the same thing that happens when you `echo end` in game.
