### ISSUE TITLE
Log line structure changes and timeline adjustments necessary to compensate

### ISSUE THREAD

**Issue by JLGarber** [quisquous/cactbot#3664]
*Based on a conversation with quisquous, writing this up here so the discussion has a place to live on Github*

With 6.0 approaching, it looks like Ravahn is going ahead and making breaking changes to the format of log lines. The overall goal here is to bring a universal structure to log lines, rather than the absolute chaos we have now. Ultimately this will be a good thing, but it does mean that timelines will break, since they fully rely on the differences in structure between the different log line types.

The new structure will be
`[14:47:01.593] StartsCasting 14:10686258:Paprika Rika:4095:Glare:400011C5:Striking Dummy:2.46:-640.06:-850.17:32.15:0.97`

This will necessitate changes to every currently existing timeline, as well as modifications to our current tools. We still haven't been able to rewrite our timeline tools to take advantage of `netRegexes`, and with 6.0 now being under two weeks away, we don't have time for that, so we will have to make changes to our existing Python utilities to handle the new format. That part is probably relatively simple.

The larger issue is that of rewriting the existing timelines to match the new log line format. Currently, `make_timeline` emits timeline entries that will match zoneseal game log lines, `15/16` ability lines, and `22` targetable/untargetable lines. However, timelines can *use* basically any of the existing log lines, so we'll have to have a process in place to ensure everything gets correctly converted.

We will probably have to take this in several steps.

1. Sort out which timelines have only simple entries from `make_timeline`
2. Write an auto-converter and convert those timelines.
3. Go through the remaining timelines and hand-convert them or special-case a converter for them.
4. Modify the existing utilities just enough to match the new log line format.

(And of course before 6.2 we *should* be able to rewrite the timeline utilities entirely.)

I'll try to get us an idea of how many timelines have "non-basic" log line regexes in place over the next week. Getting hard numbers for step 1 above is needed before we do anything else.

**Comment by JLGarber** [comment]
<https://gist.github.com/JLGarber/a8156e986c90cb5c42ea1829d8f03056>

I smashed together a script to find timelines that had "exceptional" sync entries. These are defined as entries that are not one of 
```
startsUsing, ability, gainsEffect, addedCombatant, gameLog, targetable
```

and additionally do not contain:
```
  'hideall', '0 "--reset--"', '0 "--Reset--"', '/Engage!/', '/:Engage!/',  '/:Engage!:/'
```

Out of all this, it looks like the only timelines that should require manual intervention are:

```
t7
gubal_library_hard
a7s
a8s
swallows_compass
o11n
o12n
o7s
o7n
o9n
lakshmi-ex
the_epic_of_alexander
```

I'll start making the necessary additions to the script to perform an automated conversion, and once I get to that point I'll ask for futher input.

**Comment by JLGarber** [comment]
Alright, I think we're almost there. [Convert_timeline](https://gist.github.com/JLGarber/28fd5739f867e38f745aa13d469be150). When run from the `util` directory, this script will:

1. Auto-convert every auto-convertible line that exists in the repository, except for `test.txt`.
2. Log any timeline files that contain syncs that are *not* auto-convertible to the console.
3. List out the offending lines by file in the console.

I'm confident in the soundness of the conversion mechanics, but I particularly need reviewing of the sync match regexes and the replacement functions. I pulled them from `test_timeline` if they existed there, but some of them needed minor modifications. I've listed each one in-line here, along with a Regex101 link to the regex alongside a matching line.

### startsUsing
[`/\/:(?<ability>[0-9A-F\[\]\(\)\|]+):(?<entity>[^:]+):?\//`](https://regex101.com/r/2mTPXk/1)

### ability
[`/sync \/:([^:]+):([0-9A-F\(\)\|]+)/,`](https://regex101.com/r/vYHYtJ/1)

### gainsEffect
[`/1A:........:(.+) gains the effect of (.+)(?: from)?\//`](https://regex101.com/r/PAullu/1)

### addedCombatant
[`/Added new combatant (?<entity>[^:\/]*)(?:\:|\/)/`](https://regex101.com/r/S3q2BS/1)

###gameLog
[`\s*00:(?<messageId>[0-9]*):(?<message>[^:\/]*)(?:\:|\/)/`](https://regex101.com/r/bfVX2X/1)

### targetable
[`/ sync \/\s?22:........:([^:]+):/`](https://regex101.com/r/lEsUJX/1)
(Note that all `targetable` timeline entries currently in the repository are already formatted correctly, so the conversion will only normalize the leading space in each timeline entry.)

### headMarker
[` sync \/\s?1B:........:(?<target>(?:[^:])+):....:....:(?<id>(?:[0-9A-F]){0,4})`](https://regex101.com/r/25FXLp/1)
(The same consideration applies here, although there are only 5 total across the repository and we could just as easily handle them manually.)


Here's an example conversion performed on Dun Scaith to give an idea of what the result will look like. [dun_scaith.txt](https://gist.github.com/JLGarber/c6ce8614bbe5f23a1fbdbffb6db2e7aa).

**Comment by quisquous** [comment]
I think this is just a one-off script, but here's some stuff I noticed.  (You've looked at this more closely though, so please ignore me if I'm off base):
* startsUsing should never end with a colon, because it's `:Ability:Name starts using`, so we usually just write `:Ability:Name`.  Unless there's some weird edge case I'm missing?
* You may also want to consider replacing `[^:]*` in various forms with something that's "(not a colon character OR literally `[^:]`) repeated", but if you haven't run into issues matching the colon inside of `[^:]` when you're looking for just a field separator?
* Looking at the ability output, unfortunately ability needs to be `1[56]` and not just `15`.  I think I can't trust that all abilities are `15`, even if we mostly pick self boss-casted ones.
* Definitely agreed that we should add a leading space on everything.
* gameLog doesn't end with a colon.
* added combatant has an inconsistently optional period at the end.  A quick grep says we don't add any other parts of that line.

```diff
 const timelineLineRegexes = {
-  startsUsing: /\/:(?<ability>[0-9A-F\[\]\(\)\|]+):(?<entity>[^:]+):?\//,
+  startsUsing: /\/:(?<ability>[0-9A-F\[\]\(\)\|]+):(?<entity>[^:]+)\//,
   ability: /sync \/:([^:]+):([0-9A-F\(\)\|]+)/,
   gainsEffect: /1A:........:(.+) gains the effect of (.+)(?: from)?\//,
-  addedCombatant: /Added new combatant (?<entity>[^:\/]*)(?:\:|\/)/,
+  addedCombatant: /Added new combatant (?<entity>[^:\/]*)\.?\//,
-  gameLog: /\s*00:(?<messageId>[0-9]*):(?<message>[^:\/]*)(?:\:|\/)/,
+  gameLog: /\s?00:(?<messageId>[0-9]*):(?<message>[^:\/]*)\//,
   targetable: / sync \/\s?22:........:([^:]+):/,
   headMarker: / sync \/\s?1B:........:(?<target>(?:[^:])+):....:....:(?<id>(?:[0-9A-F]){0,4})/,
 };
```

**Comment by JLGarber** [comment]
Added your suggested changes, thanks much.

> startsUsing should never end with a colon, because it's :Ability:Name starts using, so we usually just write :Ability:Name. Unless there's some weird edge case I'm missing?

Fair point, it shouldn't happen. I can't remember any edge cases that I came across.

> You may also want to consider replacing [^:]* in various forms with something that's "(not a colon character OR literally [^:]) repeated", but if you haven't run into issues matching the colon inside of [^:] when you're looking for just a field separator?

The only place I can think of where this arises is the T9 meteor regexes, which I had already planned to fix manually. Anyplace it *does* arise it will end up noted in the "matched a sync, didn't match a type" list, so I think this is probably fine as is.

> added combatant has an inconsistently optional period at the end. A quick grep says we don't add any other parts of that line

Another one I'd missed, thank you.

> Looking at the ability output, unfortunately ability needs to be 1[56] and not just 15. I think I can't trust that all abilities are 15, even if we mostly pick self boss-casted ones.

Yes indeed, that's a major omission, thanks for catching it.

I think when we discussed this elsewhere, we agreed that we would chunk it out by expansion, so it should be four PRs for those plus an extra with the manual fixes. Did you want to add an Alpha Timelines branch for me to send the PR against, or should I just PR it against Main and leave it until Ravahn does a release?

**Comment by quisquous** [comment]
I pushed an `alpha_plugin` branch if you want to PR against that.  Then we can land multiple things there and it'll be easier to test.

**Comment by JLGarber** [comment]
Excellent. I'll maybe send through the ARR stuff tonight since there's a smaller total volume there. If that all goes well I'll send in the rest At Some Point.

**Comment by JLGarber** [comment]
Completed in #3673, #3696, #3692, and #3693
