### ISSUE TITLE
Adding new trigger sounds disables readycheck trigger sound

### ISSUE THREAD

**Issue by sinkaio** [quisquous/cactbot#367]
I've been trying to get a custom trigger sound to work for Provoke and/or whenever tanks use an invuln skill in the general.js file. But for some odd reason, it doesn't play the sound. 

And when my ready check trigger is working fine, the moment I add in another sound code it just stops working all of a sudden.

**Comment by quisquous** [comment]
Can you paste what you've done so I can take a look?

**Comment by sinkaio** [comment]
Just added the string of the sound code in, I wasn't sure if plugging it in like this would work in the first place


`      id: 'General Provoke',
      regex: /:(\y{Name}):1D6D:Provoke:/,
      regexDe: /:(\y{Name}):1D6D:Herausforderung:/,
      regexFr: /:(\y{Name}):1D6D:Provocation:/,
      sound: '../../resources/sounds/Overwatch/Reinhardt_-_Show_you_how_it's_done.ogg',
      soundVolume: 0.6,
      condition: function(data) {
        return data.role == 'tank';`

**Comment by quisquous** [comment]
I will say that it is likely that your ready check probably stops working because there's a syntax error somewhere.  Do you end up with any errors in the overlay plugin log?

**Comment by sinkaio** [comment]
Not that I can find, which folder is it under?

**Comment by quisquous** [comment]
It's not a log file, it's the entries such as the InitPlugin ones in this screenshot: https://camo.githubusercontent.com/47e8b6e471576b61048a70f7e3b79d85ab01d379/687474703a2f2f692e696d6775722e636f6d2f325a51687567622e706e67

**Comment by sinkaio** [comment]
Ahh, no I never got any errors from that

**Comment by quisquous** [comment]
Looking at your original block of code, it says:

`sound: '../../resources/sounds/Overwatch/Reinhardt_-_Show_you_how_it's_done.ogg',`

and it should say:

`sound: '../../resources/sounds/Overwatch/Reinhardt_-_Show_you_how_it\'s_done.ogg',`


Are you still having issues with this? You should definitely see some errors in the plugin log for this.

**Comment by quisquous** [comment]
Let me know if you're still having issues here.  I'm going to close this for now.
