### ISSUE TITLE
Hansel and Gretel Bloody Sweep reporting incorrectly

### ISSUE THREAD

**Issue by jacob-keller** [quisquous/cactbot#3671]
## Hansel and Gretel Bloody Sweep incorrectly reporting which area is safe

The reporting for
[Network_22106_20211122-buggy.log](https://github.com/quisquous/cactbot/files/7585906/Network_22106_20211122-buggy.log)
 The Bloody Sweep ability incorrectly reports the safe area in some cases. In particular, it looks like the skill IDs are not sufficient to determine which side the two bosses hold their spears.

From analyzing this log, I can see that the two bosses use the same ID with different x,y coordinates depending on which side they're on. Additionally, based on these videos the boss doesn't use strict north/south but instead appear to use various sections of the arena.

At a minimum, the callouts will likely need to be "move between Hansel and Gretel" and "move opposite of Hansel and Gretel", rather than just north/south.

I am unsure how to fix the detection of which side each boss is on.

## Additional information

I've attached a log file for the Hansel and Gretel fight. Video of the 2nd bloody sweep can be found here https://www.youtube.com/watch?v=R_SgwEKl7gY and of the 3rd bloody sweep here https://www.youtube.com/watch?v=CapZ7A0rN6Q

Unfortunately I do not have recording of the first bloody sweep in that log.

**Comment by jacob-keller** [comment]
I also investigated trying to use the "Tandem Assault: Bloody Sweep" skills, 61B8 and 61B9, but these seem to be the same across the fight.

There are also some additional skill IDs used at the start of each bloody sweep: 5C6D, 5C6C, 5C6F and 5C6E which are used, but they also appear to be using the same ones depending on cast time.

Basically: the skill IDs themselves do not distinguish which side of the area they are on.

**Comment by quisquous** [comment]
Is it possible to change north/south to "get to wall / get center"? Or is it backwards when they are in different spots?

**Comment by jacob-keller** [comment]
> Is it possible to change north/south to "get to wall / get center"? Or is it backwards when they are in different spots?

So we can probably do "stand between" and "go opposite side" or similar. This is a strict improvement over what we have now but not quite a 100% fix. The key problem though is that I thought the IDs were different depending on what side they are on, but its actually just different IDs for the different cast times, and I think we have to use x,y,z coords or heading to really determine the side that hansel vs gretel is. This was a mistake in analyzing the logs and testing being lucky :(

**Comment by jacob-keller** [comment]
As far as I can tell its both using the wrong prediction regardless of position but is also problematic because they aren't always north/south so it makes sense to just say "between" or "opposite" at least, but we still have to resolve how to tell which one to do.

**Comment by quisquous** [comment]
Makes sense.  I'll revert this for now to avoid having an incorrect callout, and in the future maybe we can get an improved version.

**Comment by quisquous** [comment]
This was fixed in #4139.
