### ISSUE TITLE
FISHER: No location information

### ISSUE THREAD

**Issue by ordercorn** [quisquous/cactbot#370]
I'm sure I'm doing something wrong, but I can't seem to get the fisher UI to display anything besides my current bait, moving around doesn't seem to update anything and nothing shows up when I'm casting.

I went to a few different places just to see if it was a specific area but no luck.

**Comment by ordercorn** [comment]
Forgot to mention, Cast time stays at 0.0 no matter what and location is just @ -------------

**Comment by someONEgood** [comment]
When you unpacked the zip, did you make sure to go to properties and check "Unblock".
That might be the first thing to start with.

**Comment by ordercorn** [comment]
almost positive i did since i remember fixing it when i got an error about it

**Comment by ordercorn** [comment]
game connection is successful, combat information shows up in the main tab, not sure what's going wrong, did a fresh install of cactbot too just in case something got blocked

**Comment by gambino87** [comment]
having the same issue. no cast time, fish or locations will show while fishing. DPS meter and raid plugins work just fine. 

![fishingerror](https://user-images.githubusercontent.com/39010252/54578955-da410000-49d7-11e9-800a-e1a361447e80.PNG)

**Comment by Karmana26** [comment]
I have exactly the same.  Tried backdating as it worked previously but now just get Cast time at 0 and current bait but nothing happens.

**Comment by Karmana26** [comment]
Getting the same as above.  All other Overlays working but Fish does nothing.

![image](https://user-images.githubusercontent.com/49406488/55737656-839a7500-5a1d-11e9-8e90-424ec8a9b3e2.png)

**Comment by quisquous** [comment]
Can you paste some log lines from when you are casting?

**Comment by Gintoot** [comment]
It's an issue on the user's end.
I've had the same issue initially on my end.

Character Configuration > Log Window Settings > Log Filters > Announcements > Own Gathering Messages

Own Gathering Messages has to be checked in order for the game to log the data needed by the module.

**Comment by jpdied** [comment]
I was having this issue as well and it turns out the "Hide Chat Log (for privacy)" in the FFXIV plugin for ACT prevents the fisher module from detecting when the line is cast; at least for me anyways.
