### ISSUE TITLE
rename vscode settings.json to settings.example.json

### ISSUE THREAD

**Issue by Trim21** [quisquous/cactbot#3702]
vscode only  support workspace config in .vscode/settings.json.

We commit this file in git make it very hard to config vscode.

So I suggest changing it to `settings.example.json` and ignore `settings.json`.

Vscode developers could copy this file if they need, and edit it freely without complaining from git.

**Comment by quisquous** [comment]
Are there other settings that developers would want to change other than the path to dprint? (And could they add that to the global vs workspace settings instead?)

**Comment by Trim21** [comment]
like https://github.com/quisquous/cactbot/pull/3677/files#r756464790

**Comment by quisquous** [comment]
Pragmatically, at the moment I think that having a file that people have to edit separately adds more friction than benefits.  If we add new settings that would be useful, there's no way to get those to everybody automatically.  I think that one example is fine to land for now.  If we accumulate more reasons in the future for personal settings, then I'm happy to chat more about it.  But, that doesn't seem like enough for me.

**Comment by Trim21** [comment]
> Pragmatically, at the moment I think that having a file that people have to edit separately adds more friction than benefits. If we add new settings that would be useful, there's no way to get those to everybody automatically. I think that one example is fine to land for now. If we accumulate more reasons in the future for personal settings, then I'm happy to chat more about it. But, that doesn't seem like enough for me.

Like you said in the same PR #3677, code style is more forced by ci but not editor config.

If we need some new code style we just check it in our ci and failed the PR. There is no need to force all developers using same editor config.

**Comment by quisquous** [comment]
I think I am going to close this.  I think developers should use the same editor config for cactbot, as it is enforced and it adds extra friction to require developers to manually apply those editor configs.  If this is causing issues, please reopen and we can rediscuss.
