### ISSUE TITLE
Raidboss: Timelines not starting on zone seal lines

### ISSUE THREAD

**Issue by JLGarber** [quisquous/cactbot#3735]
Running the beta XIV plugin and V24.0 of cactbot. In two separate instances, the zone seal lines failed to start the timeline. (The timeline module was indeed running, since later syncs correctly matched.)

```
[20:57:56.000]   ChatLog 00:0839::The Chancel will be sealed off in 15 seconds!
2000.0 "--sync--" sync / 00:0839::The Chancel will be sealed off/ window 2000,0
```

Not sure what's causing this, but I'll try to find more information.

**Comment by quisquous** [comment]
One thing I did notice is that make_timeline sets things to be `window 0,1` for engage lines, and I think that's incorrect.  It needs to be `window 1,0`, I think?

**Comment by JLGarber** [comment]
You know the internals better than I do, but my intuition is that it's correct as it is? The timeline start point is 0, so in theory anything with a lookahead window that's non-negative should be synced correctly.

That being said, after multiple updates to cactbot and Overlayplugin, this bug seems to have disappeared, or at least I can't reproduce it now. This is probably safe to close unless/until someone else has a similar issue.
