### ISSUE TITLE
Way to make cactbot work on Korean server?

### ISSUE THREAD

**Issue by Bing-su** [quisquous/cactbot#374]
By chance I read a post, how to make cactbot work on Korean server.

It said 'act.utility' plugin (act Korean localization plugin) interrupt cactbot recognize language. (this post says) If not english, cactbot replaces non-english skillnames with en skillnames. but act.utiliy changes act's language en to kr a little later after act work on. so cactbot recognizes language en but real language is kr, and it doesn't replace skillnames and doesn't recognize.

I think this would be helpful to cactbot's korean business... but I have been not familiar with any programming so I attach the plugin.

https://drive.google.com/file/d/1DWo9hm8gzW29IkBdD7AAW4ySQJaz4CBg/view?usp=sharing

제작자님 화이팅!

**Comment by DrLippe** [comment]
You can enforce korean language:
```
user/raidboss.js
Options.Language = 'ko';
```
You may need to add a lot of korean localization though

**Comment by Bing-su** [comment]
thanks... I think I should have read the readme...
