### ISSUE TITLE
Documentation: "ACT Log Line" regexes do not match for types with hex A-F

### ISSUE THREAD

**Issue by allainecactuar** [quisquous/cactbot#3743]
Referencing this documentation: 

https://github.com/quisquous/cactbot/blob/main/docs/LogGuide.md#line-30-0x1e-networkbuffremove

When type contains an A-F hex character (e.g. NetworkBuffRemove=0x1e), the regex has it as lower case, but ACT emits it as upper case in the log, so the regex doesn't match. 

I noticed the doc said pull requests accepted, but reviewing the history made me think that the regexes are machine generated not hand-written, so I hesitated to submit a PR with hand-tweaked changes. 

You could potentially protect yourself from ACT changes by making the type field case insensitive, e.g. `(?<type>(?i:1e))`.

**Comment by Akurosia** [comment]
`[01:40:12.325] StatusRemove 1E:4D7:Ermutigen:0.00:106B2E4F:NAME NAME:106B2E4F:NAME NAME:00:77984:77984`

This is from latest beta where the IDs where capitalized
