### ISSUE TITLE
[HELP] I can't get cactbot/user custom settings to work

### ISSUE THREAD

**Issue by Krojack** [quisquous/cactbot#375]
So in an old issue (#185) I was told to put custom CSS changes into a file in the **cactbot/user** folder so my changes wouldn't get overwrote when I updated.  I've never got this to work.

In the **OverlayPlugin\cactbot\user** folder I created a file called **raidboss.css** and in that file I placed the following:
`#timeline-container { position: fixed; bottom: 0px; }`

But after reloading the overlay or even restarting ACT it just doesn't move the timelines to the bottom left.  It works find if I edit the **OverlayPlugin\cactbot\ui\raidboss\raidboss.css** file directly.  I even tried making a "raidboss" folder in the "user" folder as well and putting my custom .css file in there.

I would also like to know if this user folder also supports custom raidboss data triggers as well.  I've been adding some of my own triggers to the Eureka zones and would like it if those didn't get overwritten as well.

**Comment by quisquous** [comment]
Re: raidboss.css.  Try changing it to `#timeline-container { position: fixed !important; bottom: 0px !important; }`.  I wonder if it's an issue with CSS specificity.

Re: Triggers for Eureka.  Yes, you can add your own triggers to **cactbot\user\raidboss.js**.  See: https://github.com/quisquous/cactbot/blob/master/AdvancedCactbot.md#adding-custom-triggers

**Comment by Krojack** [comment]
Nadda... no change.  It's like it's ignoring the file.  Timers still in upper left.

![act-tmp](https://user-images.githubusercontent.com/908461/53677934-e150da00-3c85-11e9-84b6-10b55e847131.jpg)

**Comment by quisquous** [comment]
That's just the test timeline.  If you lock the overlay, does it work as you expect?

**Comment by Krojack** [comment]
I'll have to wait till I raid next to test the live part.  I know if I edit the raidobss.css within the ui/raidboss/ it moves the test ones.

I'll report back after I get a chance to test the active timelines then.

**Comment by Krojack** [comment]
Just tested in a primal ex and timers are still in the upper left.

**Comment by DrLippe** [comment]
It stays to the upper left because your style will still have `top: 0;`. So your timeline-container stretches from top to bottom now. Use the following CSS instead:
` #timeline-container { top: auto; bottom: 0; }`

**Comment by quisquous** [comment]
Thanks, @DrLippe for coming in with the real answers.   Sorry for wasting your time with guesses.  <_<
