### ISSUE TITLE
Cactbot Jobs won't work

### ISSUE THREAD

**Issue by lfk118** [quisquous/cactbot#3750]
## Description

The Cactbot jobs function is not able to use right now (After the End Walker early access) with the latest version of ACT.
No information shows up no matter what Jobs I am currently using.

## Additional information

The error log I can find is below:
Error: LoadAddons: CactbotOverlay.dll: System.ArgumentNullException: Value cannot be null.
Parameter name: t
   at System.Runtime.InteropServices.Marshal.SizeOf(Type t)
   at Cactbot.FateWatcher.ActorControl143..ctor(Type messagetype_, Assembly assembly_)
   at Cactbot.FateWatcher..ctor(CactbotEventSource client, String language)
   at Cactbot.CactbotEventSource.Start()
   at RainbowMage.OverlayPlugin.Registry.StartEventSource[T](T source)
   at RainbowMage.OverlayPlugin.PluginMain.LoadAddons()

**Comment by MaikoTan** [comment]
Yep, Endwalker would break everything, and cactbot needs update for it. We are now working on it, so please be patient.
By the way, the log you posted is not related to the job module but the eureka module, and already got fixed on the newest release I think.

**Comment by quisquous** [comment]
If you are not seeing anything with jobs, then something is wrong with your setup.  I assume if you use the cactbot test overlay you're not seeing anything either?

My recommendation would be to download the latest version of cactbot manually and unzip it over your directory.  My suspicion is that something went wrong with the update process.  If that doesn't work, I would recommend going to the ffxiv act discord and trying to get more help.  You'll likely get quicker answers there for setup issues.

**Comment by lfk118** [comment]
I re-installed the cactbot and the problem was solved. Thanks a lot.
