### ISSUE TITLE
Change height of bars for each job

### ISSUE THREAD

**Issue by Krekot** [quisquous/cactbot#377]
Hello

I would like to make the different height of bars for each job. I can only do it for DRK but not for PLD and WAR. I adding the youtube link to display what I want to do(turn off sound, sorry). 

https://youtu.be/_HtQ4okXIrU

`#hp-bar, #mp-bar, #tp-bar, #cp-bar, #gp-bar {`
`  width: 315px;`
`  height:40px`
`}`

`#hp-bar.show-number {`
`  height: 50px;`
`}`
`#mp-bar.show-number {`
`  height: 20px;`
`}`
`.drk #tp-bar {`
`  height: 20px;`
`}`

**Comment by quisquous** [comment]
Sorry for the belated response, I'm not sure what's not working for you.

You should be able to do something like:

```
.war #hp-bar {
  height: 100px;
}

.pld #mp-bar {
  height: 100px;
}
```

To adjust the heights of bars for pld and war.  That seems to work for me.
