### ISSUE TITLE
raidboss: misreported tank buster in vanaspati

### ISSUE THREAD

**Issue by ngld** [quisquous/cactbot#3775]
## Description

According to a report from Overdrive on the ACT Discord, `Vanaspati Terminus Snatcher Last Gasp` is currently called out as an AoE even though it's actually a tank buster.

## Additional information

![](https://cdn.discordapp.com/attachments/551476873717088279/918500507826413638/unknown.png)

https://github.com/quisquous/cactbot/blob/d51f16cb449033b073496c1c092502991b11c556/ui/raidboss/data/06-ew/dungeon/vanaspati.ts#L41-L49

**Comment by quisquous** [comment]
Thank you for the report.  I have that in my notes too, so this is probably a copy+paste error.
