### ISSUE TITLE
jobs: Surging Tempest timer is inconsistent

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#3778]
Filing an issue here so this doesn't get lost.  See comments on #3774.

* Initial application of Storm's Eye is not exactly 30s (instead is ~31.1 or so, sometimes varying??)
* Mythril Tempest and Storm's Eye refreshing add a different amount of time
* Storm's Eye refreshing adds a slightly different amount of time than Storm's Eye initial

**Comment by AmenneHolelane** [comment]
technically the application of tempest/eye is different. refreshing is always +30 seconds unless you hit the 60.5 limit

**Comment by quisquous** [comment]
I found that the timer and box were consistent, but if I refreshed then they got offset by like ~0.5s? I don't know.  Something weird is going on, for sure.

**Comment by Echoring** [comment]
I meet a similar issue when updating DRG's `Power Surge`.
Disembowel will apply `Power Surge` at once with a log says `you gain Power Surge for 30s`,
but this buff duration will not go down until Disembowel's damage is dealed.
Maybe something similar working here? My WAR haven't reach lv50 so I cannot test that
