### ISSUE TITLE
Plugin not working (but ACT is parsing)

### ISSUE THREAD

**Issue by Khandurian** [quisquous/cactbot#378]
Hello,
I'm very sorry if this is simple issue, but I've exhausted my options and can't seem to find the answer.
My act is correctly parsing damage, but I can't get Cactbot to work, be it as a dps overlay or raidboss...
I've been following the guides on how to install to the t; nothing happens. I've even reinstalled a couple times, redownloaded all pertinent files, made sure my OverlayPlugin is hibi's (v0.3.4). Nothing seems to work! 
Any help would be greatly appreciated.
Edit. 1: I forgot to mention that I've used the Test overlay and it appears to be working correctly. Also headed to Middle la Noscea to test on dummy and the test ran without any apparent issue.

**Comment by Khuzvhan** [comment]
experiencing the same issue after update. had some issue like that before but that was the "dps update interval" was set to 0 in one of the updates. but this time it's not that.

**Comment by Khandurian** [comment]
Thank you for you reply! My dps update interval IS set to 0, I never noticed that. What number should that be in?

**Comment by gaogaostegosaurus** [comment]
I've set the DPS interval to 3-5ish. It's just the refresh time for the overlay.

Just wanted to offer this if it helps figure out what might be the issue. I have some custom cactbot things and I don't really know what I'm doing, so some of THAT might be the source of this - but regardless:

Start up with overlayplugin on - plugin seems to be reading logs (my plugin acts as it should after log events, I assume raidboss will as well), but ACT doesn't see combat starting so an "encounter" is never recorded. DPS overlay is "awaiting data". Toggling overlayplugin doesn't seem to change anything.

Start up with overlayplugin disabled - ACT will now start/stop encounters. Turning on overlayplugin doesn't seem to stop this but DPS overlay is still "awaiting data".

**Comment by Khandurian** [comment]
Hey! I'm sorry to hear you're having issues! Changing the dps interval to anything other than "0" solved the issue for me! Thank you so much for all your help, I hope you can fix yours too!

**Comment by Slamfish** [comment]
I think I might be having a similar issue - can't get the raidboss overlay to work post 9.3.0, and and rolling back to 9.2.0 didn't fix it. When I go to add the new plugin under the Overlay section, cactbot doesn't even show up anymore as a defaulted option. Anyone have any suggestions?

**Comment by quisquous** [comment]
@Khandurian Glad you got this sorted.  Sorry for the hassle.

@Khuzvhan Are you still having issues?

**Comment by chanzie** [comment]
I am having the same issue as well...
its just stuck on awaiting data even thought the parser is working set dps interval to 5 and it did nothing at all to fix the problem.

**Comment by Khuzvhan** [comment]
> @Khuzvhan Are you still having issues?

i've just found a workaround for this
whenever i open ACT and Cactbot parser doesn't work i just toggle ffxiv/overlay plugin on/off. it takes 1-3 disabling/enabling to work. nothing too troubling. and most of times it just works fines. but if it doesn't i've been doing this and works fine.

**Comment by chanzie** [comment]
my issue was for some reason it has to be in admin mode... once I did that it now and displays fine.

**Comment by ArkfrostLumas** [comment]
@chanzie:

ACT always has to be in admin mode. It's stated literally everywhere from reddit to github, by everyone on every issue with ACT, that you should always use it in admin mode.

Also, I've noticed a huge issue with the OverlayPlugin that bugged me the whole day yesterday. When you install the OverlayPlugin after the FFXIV_ACT_Plugin, the latter gets moved down in the load order (no idea if that's new or if it was like that all the time). 
If that happens, then the OverlayPlugin keeps bugging around and not getting parses from the FFXIV Plugin, if you close ACT once and don't teleport to another area, after starting ACT. The solution for this problem is to remove the FFXIV_ACT_Plugin from ACT and then put it back in, so in the list it's on top of the OverlayPlugin.
Try that out, maybe it helps you.

**Comment by quisquous** [comment]
This issue has kind of been a muddling of a number of people's issues.  If any of you are still having particular issues, please open up another bug and I'll be happy to investigate.  It sounds a bit like most of this has been solved.
