### ISSUE TITLE
fisher: bait memory errors

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#3783]
Fishing at the reflection pool in Old Sharlayan ( 7.9  , 10.8 ) with gold salmon roe (found at the Sharlayan vendor), I get `Info: feesh: BrowserConsole: failed to look up bait: -28948 (Source: http://localhost:8080/ui/fisher/fisher.bundle.js, Line: 18988)`.  This could be related to this bait or is more likely that the bait memory location is incorrect and needs to be adjusted in the plugin.

**Comment by KattTails** [comment]
The sig is correct, it looks like the bait is now a uint and it's just being cast incorrectly from memory.
![image](https://user-images.githubusercontent.com/12807478/145697002-5915b0bc-d8bb-49b9-978e-983b5e9780c3.png)
![image](https://user-images.githubusercontent.com/12807478/145697012-d6667fa1-35bb-41ee-9b82-09b3208db08e.png)

**Comment by quisquous** [comment]
Oooh, thanks for the analysis, that sounds easy to fix.
