### ISSUE TITLE
UWU timeline and callouts are off/bugged.

### ISSUE THREAD

**Issue by HerptyDerpoty** [quisquous/cactbot#3791]
Basically just the title, the first feather rain during plumes is called about 5 seconds early, the rest of the timeline works fine.

**Comment by JLGarber** [comment]
[This trigger is timeline-driven](https://github.com/quisquous/cactbot/blob/54303910154b6ae5847780f1dbac616ce629a381/ui/raidboss/data/04-sb/ultimate/ultima_weapon_ultimate.ts#L28). Have you noticed any timeline desyncs during that section?

**Comment by HerptyDerpoty** [comment]
i havent paid attention to the timeline that much but i will look the next time im in uwu.

**Comment by HerptyDerpoty** [comment]
ok the timeline is correct but almost all the feather rains are having issues, ill get a recording from this party im currectly in and upload it

**Comment by HerptyDerpoty** [comment]
yea the timeline is way off, idk if its just me, my friend also says his timeline is way off, like it says ultima it targetable super duper early and its calling double feather rain during garuda mistral song x2.

**Comment by quisquous** [comment]
Can you post a network log here?

**Comment by HerptyDerpoty** [comment]
[Network_26208_20211214.2021.12.14.log](https://github.com/quisquous/cactbot/files/7714804/Network_26208_20211214.2021.12.14.log)
this should have 6 pulls of just uwu in it. ive reinstalled cactbot, my act and overlay plugins are updated, everything worked fine before endwalker.

**Comment by HerptyDerpoty** [comment]
managed to figure our the issue, isnt cactbot or act, well maybe acts fault but isnt a bug, sorry.
