### ISSUE TITLE
Overlay error

### ISSUE THREAD

**Issue by Desmodion** [quisquous/cactbot#380]
Well since the new Parsa Plugin Cactbot is completele broken. Everytime I get the Networksoft Json error massage. Reinstalled ACT several times now. Cactbot hibiyasleep's OverlayPlugin are on the latests release and Netframework too. Maybe it is just me who has the problem. Or the newest Pars Plugin breakes everything I don´t know.

**Comment by quisquous** [comment]
Can you list the error message you're getting?

I've seen errors like `System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json` when the wrong version of the hibiyasleep overlayplugin was installed.

**Comment by Desmodion** [comment]
I get the massage Assambly Newsoft.jeson Version = 10.0.0.0 error massage but i have the 0.3.4.0x64 version. That is the reason why i wonder as i said stoped working after the release of the new ff plugin

**Comment by quisquous** [comment]
Can you try reinstalling the overlay plugin, making sure you unblock it?

**Comment by Desmodion** [comment]
done same error massage netframework also the latest release i really don´t know what it could be

**Comment by Desmodion** [comment]
And there is something strange. ACT find the hibiyasleep overlay with no problem but cactbot get the error massage.

**Comment by quisquous** [comment]
Has cactbot worked in the past for you? You may want to try running the https://github.com/Luciusp/ffxiv-act-installer which will set up all the dependencies automatically and then installing the latest version of cactbot over that.

**Comment by Desmodion** [comment]
So done. It tells me that atc it self is the problem now don´t know how to handel it now. Try to reinstall win maybe this fix the issue
