### ISSUE TITLE
ACT constantly crashes in Eureka

### ISSUE THREAD

**Issue by Franticcashew** [quisquous/cactbot#381]
Ever since I added the hydatos triggers for BA, ACT keeps crashing in ALL INSTANCES OF EUREKA (Anemos, Pagos, and Pyros as well). It will run for a bit and then just stop responding and I have to kill it. Also when I restart it, the overlay plugin settings I have made since the last restart will not have saved. When I use ACT in BA the timeline for fights will keep running in my raidboss hud even after the program has stopped responding. 

I was thinking it was just the CPU load from BA but it seems to crash even when in a small instance (<20 players) when not much is happening. 

I have tried uninstalled and reinstalling ACT completely 3 separate times to no avail. I also tried turning the performance settings down to the lowest settings, got rid of all my custom triggers aside from raidboss, and set the FFXIV plugin to parse self only -  all to try and maximize CPU usage. I have an Intel i5 3.5HGz processor.

**Comment by quisquous** [comment]
Hmm! I'm sorry but I don't have a great idea why this might be happening.  Does it crash whether or not you're doing BA vs just in the instance?  Does reverting back to the previous cactbot make this stop happening? Is the CPU load high?

**Comment by Franticcashew** [comment]
The CPU overloads and that is what causes it to crash. I don't understand though why it is happening. I can try revert to an earlier Cactbot. It has also started crashing in other instances besides eureka. It crashed during UwU and crashed my game as well. It shouldn't be such a high CPU load, I have never had this problem before.

**Comment by quisquous** [comment]
High CPU usage is something I've seen in issue #71 where different monitors with different update rates can cause overlays to just take way too much CPU.  Is this what's happening to you?

Are you running other plugins?

Did this use to work for you, but then changed?

**Comment by quisquous** [comment]
Is this still happening for you? If so, leave another comment.  Otherwise, I'll close this for now.

**Comment by quisquous** [comment]
If this is still broken for you, let me know.  Otherwise, I'm going to close this for now.
