### ISSUE TITLE
Cactbot Radar broke recently

### ISSUE THREAD

**Issue by Marscgm** [quisquous/cactbot#3815]
Hey there,

Recently the Cactbot Radar for B, A, S and SS ranks has stopped functioning properly. Seems like it may still make the sound (sound also changed recently to be softer), but if the actual radar will pop up or not seems very random . Not sure what the issue is, but wanted to make you aware of it.

**Comment by quisquous** [comment]
Hmm.  Nothing has changed here regarding radar, and it seems to work fine for me in old and new zones.  I don't know that this is enough for me to go on to understand whether this is just your setup or a bug in radar without more information.

**Comment by Marscgm** [comment]
Turns out the entire overlay randomly disappears (I only noticed it with the Radar since that's what I use most). So it might not be even the right place to report the issue, sorry!

**Comment by quisquous** [comment]
Yeah, I would check in with the ACT FFXIV discord and they should be able to sort you out.
