### ISSUE TITLE
Issue with Crystallize callouts near the end of Hydealyn Ex

### ISSUE THREAD

**Issue by Akurosia** [quisquous/cactbot#3817]
Near the end of the fight the callouts are misleading as the order of actions change.

E.g. you `dodge Aureole > Water > Go In (red mark) ` but gets a callout for `In + Healer groups`

**Comment by valarnin** [comment]
Yeah, I was about to post this issue as well. Just got done farming my weapon.

**Comment by quisquous** [comment]
Ah, I see.  I think I should combine the Aureole callouts with the Crystallize, so it should say `Sides > Healer Groups` and clear the crystallize value so that then the red mark on its own just says `In`.
