### ISSUE TITLE
O12N fight Raidboss callouts

### ISSUE THREAD

**Issue by werewolfboy13** [quisquous/cactbot#382]
I am having an issue with the raidboss callouts not working for the first part of the fight. I am haaving to reload the overlay each time to get it to work. I am currently pointing to the web version of it http://quisquous.github.io/cactbot/ui/raidboss/raidboss.html. I also installed ACTWebSocket recently to work with the MopiMopi2 overlay Is there an issue with that plugin maybe? I am not seeing any errors in the logs when this is happening.

**Comment by werewolfboy13** [comment]
![image](https://user-images.githubusercontent.com/43587009/54217165-185e9100-44b9-11e9-8e20-e839cecda988.png)

**Comment by quisquous** [comment]
Does the timeline work when the fight starts? What do you mean that it only works for the first half? When does it start working?

Does it work if you point cactbot at your local **cactbot/ui/raidboss/raidboss.html** file instead of the remote one?

**Comment by werewolfboy13** [comment]
Sorry for the late response. I have tried both methods and it doesn't load on the first part of the fight, then it loads into the second part of the fight,

**Comment by quisquous** [comment]
Oh, I see what's happening.  There's no timeline sync if somebody pulls with a countdown.  Whoops!
