### ISSUE TITLE
raidboss gets slow after being run for too long

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#3824]
https://www.twitch.tv/videos/1232036148

I can't tell if it's just being open for X amount of time or just running X dungeons with raidboss, but eventually raidboss slowly starts to slow down.  Timelines get extremely choppy.  Looking at task manager, there's a CefSharp.BrowserSubprocess that is very busy doing something?  Other overlays are fine.  A fresh raidboss in the browser via websockets is fine.  Reloading the overlay causes both the CPU% to go back to zero and the overlay to behave fine again.

![image](https://user-images.githubusercontent.com/462317/145748271-d5b419f6-f814-4418-9f4e-3479108c1351.png)

I never saw this happen before the new OverlayPlugin/FFXIV alpha release.  I suspect it's related to something in CEF.

cc @ngld for CEF, @MyTechnoHunter for visibility

**Comment by Jwidea** [comment]
Just to add to this topic, I found this issue myself too yesterday when playing Hydaelyn ex, it seems when i was playing zodiark ex it was fine.

**Comment by ngld** [comment]
The next time this happens, can you open DevTools, switch to the `Performance` tab, record a few seconds, then export and upload the result? I wonder what that subprocess is doing with that CPU time...
The subprocess in the screenshot should be a renderer which means that it's probably busy with some JS callbacks but it's difficult to tell what exactly is going on without that trace.

**Comment by Jwidea** [comment]
sure, I'll try to record it next time we are going through the fights.

**Comment by quisquous** [comment]
Is there any way to kick off chrome://tracing hooks from CEF?

**Comment by valarnin** [comment]
I've noticed this as well, but it only seems to happen mid-pull and doesn't persist when there's no timeline active. Since I've basically only been doing extremes recently, it's not a good time to stop for 30 seconds while I try to dump a performance report.

**Comment by quisquous** [comment]
> I've noticed this as well, but it only seems to happen mid-pull and doesn't persist when there's no timeline active

I think this is not the case for me.  I have a combined timeline and alerts, and once it gets into this state, alerts are slow regardless of whether the timeline is up or not, and future timelines are also slow.

Sorry for screenshots, but when it is in this state, it never finishes saving the performance json.  I just get zero byte files.  I'll be patient and check later if it ever finishes.

I think the hiccups are whatever this ~2s "long task" is that's interrupting everything.  It's unclear what that is.  Maybe chrome://tracing could know more?
![image](https://user-images.githubusercontent.com/462317/147807447-b255c0bc-1b41-4fc4-997e-0105df03664c.png)

The little tasks are all animation frames from the timeline updating:
![image](https://user-images.githubusercontent.com/462317/147807521-492147d5-b76f-43bd-b7ba-1d67ca84da76.png)

None of the 2s tasks show up in the Event Log or Call Tree or Bottom Up.  (Sorry, I'm not familiar with devtools performance, only chrome://tracing.)  I think that means it's internal vs user code?

**Comment by quisquous** [comment]
It still never saved.  Another profile of a timeline made it look like those long tasks are maybe GC? 
![image](https://user-images.githubusercontent.com/462317/147808991-83912edf-83c6-4bcc-af46-af3e09b488cc.png)

**Comment by valarnin** [comment]
Memory churn due to the calls to `new Date()` in draw maybe?
