### ISSUE TITLE
way to reset pullcounter?

### ISSUE THREAD

**Issue by Amenne-ennemA** [quisquous/cactbot#384]
Is there a way to reset the pull counter by a command? or maybe a toggleable option to reset on new instances? or am i just not seeing the option perhaps

**Comment by quisquous** [comment]
What do you mean by reset? Like, reset to zero? Or just mark a wipe?  If it's a wipe, you can force that to happen with an `/echo cactbot wipe`.

New instances should have their own unique pull counter.  If that's not happening, then there's something wrong.

**Comment by Amenne-ennemA** [comment]
reset to 0 yeah. i'm at 90+ pulls in 11s now

**Comment by Amenne-ennemA** [comment]
i just updated to the new version so that might address something so we'll see

**Comment by quisquous** [comment]
Ah no, the new version hasn't changed anything with respect to pull counter.

The intention was to keep track of how many pulls you've done on the same fight across instance timeouts.  So, there's not really an easy way to reset it.

Right now, to set it to zero, you need to edit your **%APPDATA%\Advanced Combat Tracker\Config\RainbowMage.OverlayPlugin.config.xml** file, find the pull counter section, and change the json string there.

**Comment by Amenne-ennemA** [comment]
ah, i thought it was counting pulls per instance, not pulls per fight across instances. the XML does seem easy enough, just have to remember.

**Comment by Amenne-ennemA** [comment]
the only one i'm not seeing is the summerford farms dummy. i was using it to test several other things and it doesn't appear in the config. i only see the SB stuff i ran recently

**Comment by quisquous** [comment]
The summerford farms dummy is just listed under `test`.

**Comment by quisquous** [comment]
Did you have other pullcounter questions that I could answer? Is this all sorted?

**Comment by Zeyyagga** [comment]
Hey quisquous, quick question following up a question you already answered a while ago....

There's currently no way to have the pull counter show up in obs via browser source, but would it be possible to set it up so the pull counter number gets output to a text file?

This way people that use window capture to stream can just use that text file to display pull counts on stream?

**Comment by quisquous** [comment]
@Zeyyagga Sorry for the extremely belated response here.  The ngld overlayplugin has act websocket built in, so you can now use pullcounter as a browser source.

**Comment by heissengilbert** [comment]
Hi, I'm using the latest Cactbot from ACT. Somehow I can't reset the pull counter both ways (with echo and editting the xml file). I've tried to reinstall again and clear cache but it still counting from the very first I start using it

**Comment by quisquous** [comment]
You should be able to `/echo pullcounter reset` while not in the middle of combat (or having started an encounter, e.g. doing a `/cd 5` in Summerford Farms).  It will say something like `resetting pull count of: name` where name is the encounter/zone name.

If that doesn't work for you (possible because you have something interfering with your chat log, e.g. echo doesn't show up in your log, or you've got some dalamud plugin messing with your log, or you've turned on hide chat log for privacy), you can also directly edit the counts in the `%APPDATA%\Advanced Combat Tracker\Config\RainbowMage.OverlayPlugin.config.json` file.  See: https://github.com/quisquous/cactbot#pull-counter-module

**Comment by heissengilbert** [comment]
> You should be able to `/echo pullcounter reset` while not in the middle of combat (or having started an encounter, e.g. doing a `/cd 5` in Summerford Farms). It will say something like `resetting pull count of: name` where name is the encounter/zone name.
> 
> If that doesn't work for you (possible because you have something interfering with your chat log, e.g. echo doesn't show up in your log, or you've got some dalamud plugin messing with your log, or you've turned on hide chat log for privacy), you can also directly edit the counts in the `%APPDATA%\Advanced Combat Tracker\Config\RainbowMage.OverlayPlugin.config.json` file. See: https://github.com/quisquous/cactbot#pull-counter-module

Yup, I’ve tried those when I’m in dragonsong before pulling. I used `/e pullcounter reset`. The echo shows up as I also use another script using echo but nothing conflict with that regex or string. It didn’t show up any message too after I entered that. For editting the json file in `%APPDATA%\Advanced Combat Tracker\Config\RainbowMage.OverlayPlugin.config.json`, I’ve tried changing the value under pullcounter object to 1 but it still overwrite with the old one as the cactbot didn’t read the latest value. I tried to empty the object too into `pullcounter: {}`, but nothing changed

**Comment by quisquous** [comment]
One thing to try is to make sure ACT is closed when you're editing the file, otherwise it will likely overwrite the file with whatever is in memory.
