### ISSUE TITLE
Is it possible to add a setting to turn off these new boxes?

### ISSUE THREAD

**Issue by voetre** [quisquous/cactbot#3848]
![image](https://user-images.githubusercontent.com/39429413/146096219-b31af12c-0e4e-4008-9196-a7ea8aed1377.png)

I updated just a few minutes ago and now these boxes for No Mercy, Bloodfest, and Gnashing Fang are on my screen permanently. I can understand why they are useful to some people, but I do not wish to have them.

Could a toggle be added?

I would like to just go back to have raid buffs and food being tracked only.

**Comment by quisquous** [comment]
@MaikoTan it looks like some of the recent changes broke the "only show the party tracker" setting.  Could you take a look?

**Comment by MaikoTan** [comment]
Oops!
It looks like #3818 broke this option, I'll produce a fix patch tonight. Sorry!
