### ISSUE TITLE
Is it possible to change colors of text within the Timeline plugin?

### ISSUE THREAD

**Issue by Merkava2k15** [quisquous/cactbot#385]
Is it possible to change the color of individual lines within the Cactbot Timeline raidboss plugin?

For example in the preview picture you posted:
https://raw.githubusercontent.com/quisquous/cactbot/master/screenshots/Raidboss.png

Would it be possible to change say... "Dualcast" to red instead of it being white?

Thanks for any support offered!

**Comment by quisquous** [comment]
At the moment, there's no way to do this, sorry.  This is a good thought though, and I should be able to make it possible to add custom styling to entries (color, font size, etc).  I'll keep this open as a feature and hopefully I (or somebody else?) can get to it sometime in the next while.

**Comment by Merkava2k15** [comment]
Thanks for the quick reply.

Still, Thanks for everything and keep up the great work!

**Comment by Snsei987** [comment]
Can't you just do it within the `raidboss.css` file ?

**Comment by quisquous** [comment]
This got fixed in #637.
