### ISSUE TITLE
Stigmascape final boss alert for dragon incorrect

### ISSUE THREAD

**Issue by jacob-keller** [quisquous/cactbot#3878]
## Description

The alert for the dragon add that spawns during the last boss of Stigmascape always says "WEST" but the dragon may spawn either on the east or west side. The alert should either be generic or figure out which side the dragon spawns on and call appropriately.

## Additional information

If available, please include any logs or screenshots depicting the issue you're experiencing.

[Network_26208_20211216.zip](https://github.com/quisquous/cactbot/files/7738852/Network_26208_20211216.zip)

The dragon spawns first on the east side, and then again on the west side in this fight, but the alert always says west.

**Comment by JLGarber** [comment]
This should have been fixed in #3868, but there hasn't been a release that includes it yet. Try pointing your `raidboss` overlay at https://quisquous.github.io/cactbot/ui/raidboss/raidboss.html, and see whether that resolves it for you.

**Comment by quisquous** [comment]
As this should have been fixed, I'll close this now.  Please reopen if this is still happening.

**Comment by jacob-keller** [comment]
Yep this has been fixed the last few runs I did.
