### ISSUE TITLE
Raidboss: Smileton First and Last Boss Issues

### ISSUE THREAD

**Issue by twizmaster123** [quisquous/cactbot#3881]
## Description

During the first encounter, cactbot does not seem to recognize that you've been hit by one color or another. Every time the mechanic is repeated, the alert just says "get hit by either color" even though you've already been hit by one.

During the last encounter, the "left" and "right" alerts are not consistent and often times occur at inappropriate times when said mechanic is not occurring.

**Comment by quisquous** [comment]
Sorry, I'll try to take a look at this soon.

**Comment by twizmaster123** [comment]
To give an update, the last boss seems to work fine. I had assumed the left and right side bombs exploding either in the back or front had a trigger but I was wrong. So, to reiterate, no issues with the last boss that I am aware of.
