### ISSUE TITLE
jobs: Possible bug with Job overlay

### ISSUE THREAD

**Issue by Tataru-Taru** [quisquous/cactbot#389]
When a BRD uses Foe's requirem, it would seem the count just keeps counting up

[Image of overlay](https://i.imgur.com/M9vAKh2.png)

In Baldesion Arsenal on SCH

**Comment by quisquous** [comment]
Ah thanks, I really need to fix that.  The problem is that foe's gets cancelled when there's a message that the bard stops using it, but that line can get dropped in eureka.

**Comment by quisquous** [comment]
Should be fixed now, sorry about that!
