### ISSUE TITLE
Unable to backup fisher history?

### ISSUE THREAD

**Issue by stinkpalmd** [quisquous/cactbot#3894]
I have searched as best I can through the github issues and the ACT Discord, but haven't had any luck.

There doesn't seem to be a way to easily backup the Fisher module's history. i.e. I want to bring my fishing history/cast times/etc over to a new computer and I do not see a way to do this since it all seems to get stored through javascript? Would it be possible for this to be added as a feature in the future if it does not exist? Apologies if I am missing an obvious solution!

~Thank you~

**Comment by quisquous** [comment]
I looked through discord and found: https://discord.com/channels/551474815727304704/551476873717088279/830590144033587250

That's probably the directory you're looking for, if you copy that and paste it on the new computer.  Let me know if that doesn't work.

If you want to add such a feature, I'd be happy to review the PR.

**Comment by stinkpalmd** [comment]
This looks very promising - thank you for responding so quickly and sorry for overlooking that. Feel free to close the item on git!!

:-)
