### ISSUE TITLE
No Cactbot type in dropdown

### ISSUE THREAD

**Issue by lolsoftlight** [quisquous/cactbot#390]
i tried this unblock command thingy like 10 times now and restarted like 20 times and i cannot get it to work. No matter how many times i completly reinstall everything... there IS NO cactbot type in the dropdown. it is getting pretty frustrating at this point

**Comment by quisquous** [comment]
Sorry that this isn't working for you.  Have you tried one of the bundle installers like https://github.com/Luciusp/ffxiv-act-installer?

**Comment by quisquous** [comment]
Have you been able to get this working? Did a bundle installer work for you?

**Comment by quisquous** [comment]
If this is still happening, please leave another comment.  I'm going to close this for now.
