### ISSUE TITLE
Sage Eukrasian Dosis III timer not showing on job overlay

### ISSUE THREAD

**Issue by reefer-zz** [quisquous/cactbot#3905]
Hey,

As the title says. All other DOT timers work fine.

Sage Eukrasian Dosis III timer not showing on job overlay.

![image](https://user-images.githubusercontent.com/3834369/147145454-35e3655d-b614-41f0-a290-d64c666057f5.png)

**Comment by quisquous** [comment]
@Echoring can you take a look?
