### ISSUE TITLE
Cactbot Jobs: Party raid buffs aren't showing

### ISSUE THREAD

**Issue by cmgau** [quisquous/cactbot#3909]
Scenario:

1. A party member uses a raid buff; for this example Trick Attack
2. Trick Attack activates, can see how long it lasts goes on CD
3. Cactbot Jobs no longer shows you how many more seconds until Trick Attack goes off CD (please refer to the image attached, excused the quality)
![image](https://user-images.githubusercontent.com/82530248/147194533-67cb50e6-fa1c-453f-b4b5-be0f8c34bde0.png)

It does however still show you how long until your own raidwide buff has until its off CD. E.g. I pop divination, it will show me long I long I have (in the seconds) left till Divination goes off CD.

**Comment by quisquous** [comment]
Sorry, I can't tell what's going on in the photo.

Trick Attack works for me just fine.  It appears when I use it, and I see its cooldown as well.

What is the option in the cactbot config for `Minimum seconds on a cooldown before shown`? If you set it to like 9999, does the cooldown show up?

**Comment by cmgau** [comment]
> Sorry, I can't tell what's going on in the photo.
> 
> Trick Attack works for me just fine. It appears when I use it, and I see its cooldown as well.
> 
> What is the option in the cactbot config for `Minimum seconds on a cooldown before shown`? If you set it to like 9999, does the cooldown show up? (EDIT: mostly I'm curious if it shows up eventually, closer to when it's ready, vs always showing the cooldown).

Hi Quisquous, thanks for replying. I've set the min cooldown to 9999; result is it always shows the cooldown for my raidbuff.

Hopefully the gif would explain it, in the gif. I've popped divination, my friends popped battle voice; which wears off, it doesn't however show how many seconds left before battle voice comes off CD like divination does. 

![raidbuffs](https://user-images.githubusercontent.com/82530248/147215742-51cba24f-1782-4813-ba78-a65ab9a4e561.gif)

**Comment by Echoring** [comment]
@MaikoTan and me took some test and have located this bug.
He will fix it when he is off duty tomorrow.
