### ISSUE TITLE
Unable to change height of individual timeline box for raidboss module

### ISSUE THREAD

**Issue by jjgitprojects** [quisquous/cactbot#3917]
Hi, I understand that there is a specific note that adjusting appearances of the timeline container in the raidboss module will be difficult due to its custom nature.

However, I would like to just check if this is a bug or intended:

<img width="241" alt="image" src="https://user-images.githubusercontent.com/42655877/147340549-b3c34913-7a33-4a39-b6a1-375897e848b3.png">

While I am able to adjust parameters such as the font size and width of the timeline container, I am unable to adjust the height, no matter what I change to the "height: ___" attribute in the specific user css file. This results in the customised timelines unable to cater to font-size that are bigger than the default font size of 14.

Just want to ask if it is possible to adjust the height of the timeline boxes.

**Comment by Akurosia** [comment]
This would be the element to adjust (i used a high value so its abvoius in testing), but currently it seams to ignore user css file completly for me
```
.timeline-bar-color {
    height: 200px !important;
}
```

**Comment by MaikoTan** [comment]
What about to ajust the "zoom" level in OverlayPlugin ?

**Comment by jjgitprojects** [comment]
> 

thank you, your comment solved my issue for me. What I did wrong, was basically editing the info-text for the class "timeline-container" (which apparently seems to me is the correct and only way to change the width of the timeline alerts) instead of "timeline-bar" as you mentioned. But in my case, tested and the raidboss module goes thru my user css file.

Closing this issue.

**Comment by jjgitprojects** [comment]
> What about to ajust the "zoom" level in OverlayPlugin ?

that would work and is a good idea for a quickfix if someone simply wanted a minor upscale or downscale of the timeline alerts. However, without changing the CSS file, the "zoom" function cannot make the timelines go beyond the default container size, and hence there is a limit to simply just zooming w/o making changes to CSS.
