### ISSUE TITLE
eureka: Critical Engagements don't pop. (kr server)

### ISSUE THREAD

**Issue by Bing-su** [quisquous/cactbot#3928]
## Description

![보즈야 제보 사진](https://user-images.githubusercontent.com/37621276/147384357-0d5a18ae-ad0f-4793-adda-e19c6510828c.png)

Critical Engagements don't pop on eureka overlay.

It's been a while since I went to bozja, so I don't know when this problem began.

## Additional information

FFXIV version: 5.57
FFXIV ACT plugin: 2.1.2.9 (kr)
overlay plugin: 0.18.0.0
cactbot: 0.24.8

**Comment by quisquous** [comment]
This probably needs the opcode updated in the plugin for the Korean version.  It would be a change that looks like 80e43e54273605d2daef08759d2e1fb639e8ee15.
