### ISSUE TITLE
Disappearing Timeline for Mustadio

### ISSUE THREAD

**Issue by Agres53** [quisquous/cactbot#393]
When Mustadio is pulled, a timeline appears for a few seconds, then disappears for the rest of the fight. All of the alerts for the abilities still go off.

Timers work correctly for every other Orbonne boss, as well as every BA boss.

I tried a fresh install of ACT and every plugin but same exact error occurs.

**Comment by quisquous** [comment]
Can you post a Network log here from when that happened? Are you using the English client?

**Comment by Agres53** [comment]
I am using the English client. I do not have a log right now, but will post one the next time I run it.

**Comment by quisquous** [comment]
Have you seen this again?

**Comment by Agres53** [comment]
Took me a few runs before I could get it to happen again, and this time with Ultima instead of Mustadio. File is too big to attach here but it is just one run in it. Anything important you would need from the start, or would it be fine if I cut out the first half of the log to be able to attach it.

**Comment by Agres53** [comment]
Got it, 
[Network_20190526.log](https://github.com/quisquous/cactbot/files/3221319/Network_20190526.log)

**Comment by quisquous** [comment]
Thanks so much for following up.  I'm out of town at the moment, but should have time to dig into this next weekend.  I have some suspicions about what might be going on, but need to dig into the log more closely.

**Comment by quisquous** [comment]
Hmm.  I can't see anything at all in the log that would have done that.  The timeline only resets if there's a "is no longer sealed" message in the log.  And there's nothing going on that's causing a bug, at least from the network log import.

If this ever happens again, can you look in the overlay plugin log and see if there's anything printed there? I wonder if there's some error that's causing the timeline to stop for some reason.

**Comment by Agres53** [comment]
Where would I find the overlay plugin log? Tried google but can only seem to get results for parse log location.

**Comment by quisquous** [comment]
Extreme apologies that this conversation dropped off my radar.  The overlay plugin log is what you see when you go to ACT -> OverlayPlugin.dll, and then look at the pane of text on the bottom.

I saw something similar to this once, where a pull happened and then immediately the timeline poofed, but then kicked in again when another ability happened.  I'll keep my eye out, but I only saw it once.

**Comment by quisquous** [comment]
I think I might know why this is happening! The timeline resets when combat starts.  If the timeline starts before combat begins (maybe the zone closing message happens or there's an engage) then it resets.  I think I should be able to fix this by only resetting the timeline when combat stops instead.
