### ISSUE TITLE
fisher: fishing holes with brackets in name don't function

### ISSUE THREAD

**Issue by PimohOrinx** [quisquous/cactbot#394]
All the locations that I fish at with brackets in there name don't seam to work with cactbot., the ui will show the info for the last spot I was at and the timer doesn't function.

**Comment by KioriBug** [comment]
I've run into this issue as well.  The fishing holes I've found to have this problem so far are:

Grymm & Enid
The One River (East)
The One River (West)

**Comment by quisquous** [comment]
Thanks for the bug report!
