### ISSUE TITLE
Feature Request: Oopsy UI float left

### ISSUE THREAD

**Issue by wtyanan** [quisquous/cactbot#3945]
## Summary

Can we have the option to have the window float left without death report enabled? Currently, it floats to the right with death report set to not shown.

**Comment by quisquous** [comment]
I am not sure how to make all of the options for floating make logical sense in the config ui.  I think I'm inclined to leave the config ui options as they are, sorry.

If you'd like it to float left, you can still do this locally with some CSS.  Add this code to your cactbot user folder's `user/oopsyraidsy.css` file:
```css
.flexcontainer {
  flex-direction: row-reverse;
}
```
