### ISSUE TITLE
Module for Raid Cooldowns

### ISSUE THREAD

**Issue by CallaSoatski** [quisquous/cactbot#395]
Hello!

I love this tool and it has made a lot of aspects of the game a lot more accessible. I had a request for a Cactbot module I'd love to see in the future.

Would it be possible to create a visual indicator of the cooldown of raid buffs, such as Trick Attack, Battle Litany, etc.? Ideally in icon form with the number counting down.

I know this is possible to do in SST currently, but SST has traditionally caused a lot of issues that I've been able to get rid of by using Cactbot, so I'd love to see this functionality added here. Thank you!

**Comment by quisquous** [comment]
You should take a look at https://github.com/quisquous/cactbot#jobs-module.  If you don't want the hp/mp/gauge stuff, there's an option for buffs only.

The timers aren't perfect but they're still good indicators.

**Comment by CallaSoatski** [comment]
Oh awesome, I mis-read it at first and thought it only tracked personal buffs. Thanks!
