### ISSUE TITLE
Append abbreviations for Tank Buster (TB) and Area of Effect (AoE) to spell name on timeline for Cactbot Raidboss

### ISSUE THREAD

**Issue by brentrichardjr** [quisquous/cactbot#3954]
## Summary
Currently, Cactbot Raidboss shows a "raid warning" style announcement for AoE and Tank Buster when the spell is beginning to be cast. For most healing spells, this is enough time to react to the damage, but for spells that have a delayed result (like AST) or shields that should be up before the ability (SCH, SGE) it can be hard to prepare before you learn the names and what they do.

Suggestion:
For abilities that will trigger an AoE or Tank Buster "warning", append (TB) or (AoE) abbreviations to the spell name on the timeline. Then a simple glance at the timeline will allow you to know what type of ability the spell name is and help you prepare in the 20/25s that the bar first shows up.

**Comment by quisquous** [comment]
I've added config ui that allows you to rename timeline entries.  If you'd like to append (or replace) this text, you can now do this on each timeline.
