### ISSUE TITLE
Alerts are mixing Safe zone with attack zone on different bosses 

### ISSUE THREAD

**Issue by Theletha** [quisquous/cactbot#3958]
## Question

What would you like to ask?

Why is there a mixed philosophy for the alerts when it comes to the go to safe zone and attack zone?
I see this a lot on different bosses, the alert says LEFT and you are supposed to go left to be in the safe zone since the boss does an attack on the right side. But then on a different boss it says LEFT and then that is the attack zone of where the boss will attack at instead of being the safe zone. 

This keeps me a bit unsure for every boss when these types of alerts come up. Now i know this is just a helping hand and you aren't supposed to rely on it 100% of course, but when you do rely on it in the heat of the moment it would be great if the alerts share a common message throughout all the bosses that this supports to help keep the uncertainties away. 

Maybe we should should make it so instead of using the single word alerts "Left/Right" they can be replaced with "Go to Left/Right" to remove all uncertainties for the simple movement.

**Comment by quisquous** [comment]
There is not a mixed philosophy, if that helps.  Here's the rationale I use:
* always call the safe spot to go to, not the attack zone (I think there's some "don't go back right" on e4s, but this is the exception).  In other words "go left" is the same as "left" in all cases.
* if the boss can be moved around, left/right is facing the back (e.g. left flank, right flank).  If you're a tank, you have to do it backwards, as I don't want the callouts to be inconsistent based on where you are standing.
* if the boss is huge and on the edge of the arena (Aitiascope, o4s, etc) then left/right assumes you are facing the boss

If there are places where something doesn't follow these rules, please let me know.  It would help if you could list specific examples where something was incorrect or made you unsure.

**Comment by Theletha** [comment]
I see thanks for the clarification. I will keep an eye out if something is amiss and get your input. 

Thanks for the reply.
