### ISSUE TITLE
Timeline: Spammed with strange skills 

### ISSUE THREAD

**Issue by gucciBane** [quisquous/cactbot#397]
Hey,

I just started using Cactpot (timeline). I don't get any errors or anything and it seems to work alright, but having used it in 04S, right off the bat I'm being spammed "[Healer]: Provoke" as if it were an alert?

Thanks

**Comment by DrLippe** [comment]
Provoke does trigger a general trigger pop-up. The name displayed should belong to a tank though.
You can disable these triggers by setting up `user/raidboss.js` like this:
```
Options.DisabledTriggers = {
  'General Provoke': true,
  'General Ultimatum': true,
};
```
If this does not solve your problems, could you provide a log file so we can try to reproduce your issue?

**Comment by gucciBane** [comment]
Oh ok, that's good to know. Thanks

Is there a quick way to turn off all alerts, besides manually setting each one?

**Comment by IllidraEthorn** [comment]
O4S (Neo Exdeath) Has an oddity where ability ids are different and mixed around (Bards casting living dead and whatnot).

**Comment by gucciBane** [comment]
> O4S (Neo Exdeath) Has an oddity where ability ids are different and mixed around (Bards casting living dead and whatnot).

lol and of course that's the first one we tried it on. That really clears that up, thanks!

**Comment by quisquous** [comment]
Yes, O4S is weird (https://github.com/ravahn/FFXIV_ACT_Plugin/issues/203).  It should theoretically by the 1.7.2.6 release (https://github.com/ravahn/FFXIV_ACT_Plugin/releases/tag/v1.7.2.6).  Are you using that?

**Comment by quisquous** [comment]
This should be addressed now in the ffxiv plugin.
