### ISSUE TITLE
Raidboss: 'StartsUsing' and 'Ability' P3S triggers not working

### ISSUE THREAD

**Issue by 1unie** [quisquous/cactbot#3984]
The timeline is showing fine, and the first 'Headmarker' trigger is working, but the 'StartsUsing' and 'Ability' ones don't seem to be triggering at all. Unsure what might cause this.

**Comment by 1unie** [comment]
Adding a note that I sent a P3S log in the ACT Discord to help investigate.

**Comment by 1unie** [comment]
[Network_26308_20220106.zip](https://github.com/quisquous/cactbot/files/7826052/Network_26308_20220106.zip)

**Comment by quisquous** [comment]
Are you using a language other than English?

**Comment by 1unie** [comment]
> Are you using a language other than English?

Yes, French.

**Comment by ksledu** [comment]
> Are you using a language other than English?

janpanese client has the same issue, part of triggers are not working . ex:  experimental fireplume rotating cast / out cast.   right cinderwing,   left cinderwing,  flare of condemnation, spark of condemnation, experimental glory plume ratate cast/ out cast   etc..

**Comment by ksledu** [comment]
timeline is working

**Comment by Akurosia** [comment]
The release version vor savage raids only included english as a language and translations were added after the release. Other language support is added with the next release
Changes were made here: https://github.com/quisquous/cactbot/pull/3983/

**Comment by 1unie** [comment]
> 

Just to clarify, my game is in French but I do use English triggers, so it's not the translations that I'm missing but rather that triggers don't work on French logs? Aren't the triggers grabbed from language-agnostic network lines anyways? 
I was under the impression that everything was in order from the last release - especially since the Headmarkers do trigger.

Thanks for fixing anyways, is there a way I can test your commit in raid tonight or do I have to wait for the next release?

**Comment by Akurosia** [comment]
As long as your game is in a non english languages, it cant match the loglines correctly due to changed names of bosses etc.
Some things like buffs/debuffs dont need them this is why some trigger work and some don't

`/ 1[56]:[^:]*:Fountain of Fire:66E9:/` vs `/ 1[56]:[^:]*:Flamme de la vie:66E9:/`

**Comment by 1unie** [comment]
Understood, thank you.

**Comment by 1unie** [comment]
Can confirm this is fixed by #3983.
