### ISSUE TITLE
How to move Healthbar seperate from box timers?

### ISSUE THREAD

**Issue by itanimo** [quisquous/cactbot#399]
I'm trying to move the health bar as a seperate component than the box timers, is there a way to do this?

![image](https://user-images.githubusercontent.com/17196731/55675243-8768b300-58c8-11e9-812a-12418aede693.png)

**Comment by quisquous** [comment]
What's your goal in terms of how you'd like them to be laid out?

There's no easy way to adjust these things.  It's all HTML and CSS.  If you hit "show devtools" on the jobs overlay, it will let you see the html and you can figure out what CSS you need to change.  Then you can put that css in a **user/jobs.css** file and it will be loaded automatically, overriding what is already there. 

See also: https://github.com/quisquous/cactbot/blob/master/AdvancedCactbot.md#customizing-appearance

**Comment by Safo91** [comment]
The goal is to move the healthbar away from the box timers. The current behavior has them bundled together, so I cant move them apart. Is this an option?

**Comment by quisquous** [comment]
#war-procs are the timer boxes, and their left/top CSS is relative to the bar location.  If you set it to be `position: fixed` in CSS then it will be relative to the overlay itself and you can position its `top` and `left` to be where you want it to be.

https://github.com/quisquous/cactbot/blob/master/ui/jobs/jobs.css#L334
