### ISSUE TITLE
Fisher Overlay not working.

### ISSUE THREAD

**Issue by Karmana26** [quisquous/cactbot#400]
Have tried looking at others with similar issues but am unable to get this working again.  I used it a week or so ago and it was fine.  Now it registers my bait but does not show fish or location etc.

I have also gone to summerford and am unable to get the /bow etc to work with dummy.  I can do /countdown 5 and it works fine but reading from a log seems to be an issue.  I do have emotes showing in my log window.

Here is what I get at the moment.  Any advice would be appreciated. 

![Fish](https://user-images.githubusercontent.com/49406488/55746737-66bc6c80-5a32-11e9-9744-4187c6dcd988.jpg)

I have done a FRESH install of all newest files twice so am pretty sure it is nothing to do with structure...

**Comment by Karmana26** [comment]
Just worked out why the emotes do not work.  It is searching for "You" and the emotes writes your name instead.  If I write /echo You bow courteously to the striking dummy it works fine.  Should it automatically change You to my name?  If not the test will not work.

**Comment by Karmana26** [comment]
Well I finally fixed it after narrowing it down to a LOG issue.  

If this helps anyone, NEVER change Log Window Settings to Surname Abbreviated as this begins all logs referring to you in the 3rd person.  Instead of "YOU cast your line...." it changes to "Karmana M casts his line" which breaks all addons that are searching for the generic YOU and not a personalised name.   

Phew, Back to Fishing.

**Comment by chanzie** [comment]
im getting the same display issue, firewall disabled, log checked out fine, just not showing any timers at the Arms of Meed for some reason, havent checked any other locations, also was not getting any coloring with the timers or any of the nifty extras.

**Comment by Akurosia** [comment]
Nearly identical issue here, except that for me (germna client) chat lines seams to be correct but still no display output. Is there any way i can see at least at which step he has an error? there is also no log inside the overlay.dll tab inside act.

**Comment by geekgirl101** [comment]
I'm having this issue myself.  I've made sure I'm using the full name and no abbreviations but the cast time still shows 0.0 whilst fishing and no fish are appearing in the list, this is at The Isle of Bekko in The Ruby Sea.

**Comment by quisquous** [comment]
Sorry for delay on fixing this.  Been distracted with a few other things.  Will try to take a look soon.

**Comment by quisquous** [comment]
Akurosia: can you give me some example lines from fishing that you feel like should work, and I can check them against the regex? Are you seeing the fisher window at all (e.g. the window shown in the first comment in this bug)?

geekgirl101: are you using the English client? Can you paste some log lines from your battle log for what it looks like when you're fishing?

**Comment by Akurosia** [comment]
i checked: Endoceras,Killerkuno, Neptodrache, Namitaro, Shonisaurus and Helicoprion
I see the overlay with like the location i am in but thats all.

**Comment by quisquous** [comment]
Akurosia: can you paste some log lines that show up in your chat box when you're trying to fish for those, e.g. the you cast your line into the etc etc ones.

**Comment by Akurosia** [comment]
This is a demo log line from followinf fishing spot: South Banepool (Coerthas Western Highlands)
[18:05]Du hast mit dem Fischen am südlichen Bannpfuhl begonnen.
[18:05]Etwas hat angebissen!
[18:05]Du hast eine  Patrizier-Seema (24,1 Ilme) gefangen.
[18:05]Du hast mit dem Fischen am südlichen Bannpfuhl begonnen.

**Comment by quisquous** [comment]
Thanks, @Akurosia.  I think I see the problem.  Can you test a fix for me?

Go to your **cactbot/ui/fisher/fisher.js** file on line 62: https://github.com/quisquous/cactbot/blob/master/ui/fisher/fisher.js#L62

And change the full line to:
`'cast': /00:08c3:Du hast mit dem Fischen (?:am |auf dem |im )?([\w\s\-\'\.\d\u00c4-\u00fc]+) begonnen./,`

 and then see if it works in South Banepool.  I think in this case, it's not working because of the `ü` character.  I don't know if that's the case for other places you've tried, but that seems likely for this instance.

**Comment by Akurosia** [comment]
<img width="150" alt="Advanced_Combat_Tracker_2019-06-03_17-48-45" src="https://user-images.githubusercontent.com/7465469/58815468-ebd59380-8627-11e9-837d-b50238525a39.png">
Stil not working

**Comment by Akurosia** [comment]
Another example i just found (due to lack in time currently) is:
Du hast mit dem Fischen an den Erdseim-Feldern begonnen.

**Comment by quisquous** [comment]
Akurosia: does fishing work anywhere or just specific locations are not working?

Can you replace your **cactbot/ui/fisher/fisher.js** file with this file and try fishing? [fisher.zip](https://github.com/quisquous/cactbot/files/3270019/fisher.zip)

In particular, look in the overlay plugin log and see what it prints out for language.  Can you verify that it prints `de` and not `en`?

If it prints `de` can you try fishing with it and see if it works?

**Comment by Akurosia** [comment]
The overlay works in generall but severall fishingspots are just not working (e..g western coerthas, where some spots are working while others don't)
<img width="644" alt="Advanced_Combat_Tracker_Z4NIWLLraq" src="https://user-images.githubusercontent.com/7465469/59199458-49bd2a80-8b96-11e9-8e89-c01d485f09dd.png">

I will check the files today and will give you feedback.

**Comment by Akurosia** [comment]
Ok Update:
Overlay behaves now kinda strange (it will keep displaying the last valid entry in the overlay):
- Went to western coerthas (Unfrozen Pond) = Overlay working as expected
- Went to South Banepool (same area) = Overlay displayes the last working state it had in Unfrozen pond (even the cast time was displayed as a static value)
- Reloaded overlay and started fishing again at South Banepool = Nothing displayed again (same behaviour as in the screenshot i sent befor)

ACT Log displays: `10.06.2019 15:51:28: Info: fischer: BrowserConsole: Language: de (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin/cactbot/ui/fisher/fisher.js, Line: 322)
` but nothing else is displayed there.
Also as a short Question: I had 2 baits in my inventory (Goblin Jig (Unfrozen Pond) and Brute Leech (South Banepool))
When i tried fishing with Goblin Jig in South Banepool, it still displayed Brute Leech in the fisher overlay.
Is this the correct behaviour?

**Comment by quisquous** [comment]
Sorry for taking so long to get back to this.  This is definitely confusing.

In terms of behavior, if I am fishing and I change baits without putting away the rod, then the "last working state" is displayed in terms of time, but the bait will change.  Additionally, if I get up from fishing, then "You put away your rod" message clears the fishing ui.  Does that not happen for you?

It's very confusing to me that it would display Brute Leech when fishing with Goblin Jib, especially because the bait that you have is found from memory and isn't found by reading the log file.  That makes me think that something has gone very wrong, but I would expect a Javascript error or something in the log if that was true.

Do you have a Network_date.log file that you could include here that has the fishing lines you're seeing? These files are usually in the `C:\Users\USERNAME\Documents\My Games\FINAL FANTASY XIV - A Realm Reborn\FFXIV_CHRetcetcetc\log` folder.

**Comment by Akurosia** [comment]
Dont worry. i have enought time :)
currently i dont know the logfile anymore where i took it but should be able to create one for you.
Also for the bait issue, it didn't happend to me (at least for the one spot i tested in western coerthas).
Is there a way we could sit together at anytime to possibly speedup the process?

**Comment by quisquous** [comment]
I think the change I just pushed should fix Akurosia.  And previous fixes adjusted for different logging issues.

If there are further fishing overlay not working bugs, please file separate issues! Thanks for all the feedback!  (Sorry for the bugs!)
