### ISSUE TITLE
cactbot does not work for endwalker content

### ISSUE THREAD

**Issue by barbaraz01** [quisquous/cactbot#4002]
## Question

My cactbot doesn't work properly since Endwalker.  All triggers for old content (text alerts/tts callouts) works, but any endwalker content the triggers do not do the callouts/or text alerts at all.

**Comment by wolfiemuzl** [comment]
Hey, just wanted to say I have the same issue. It's been updated to the latest version and I checked all the configs to make sure it was reading from the proper source, but no endwalker content has any calls.

**Comment by nyanwaffles** [comment]
I am having this issue also. It only works for older content. I have never used this with XIVlauncher so I don't know if that could be part of the problem.

**Comment by quisquous** [comment]
The best place to get support for "cactbot doesn't work at all" is the ACT FFXIV discord.  There's probably some setup issue (maybe different for all of you) that needs to get sorted out.  See: https://discord.gg/hK523Pj

**Comment by barbaraz01** [comment]
This has been fixed.
