### ISSUE TITLE
Github Error while checking Cactbot version

### ISSUE THREAD

**Issue by ShuriWasTaken** [quisquous/cactbot#401]
Apologies if this is in the wrong section. I'm new and not terribly bright.

After updating Cactbot a few weeks back, I've been receiving there error message on starting ACT. 
"Cactbot Manual Check. Github error while checking Cactbot version. Your current version is 0.7.0.0. Manually check for new version now?"
Hitting Yes loads the latest release page.

This error doesn't seem to affect ACT or Cactbot in any way, so I actually ignored it for a while, since it wasn't a problem. However, the popup every time I restart ACT is a bit annoying, and the log IS asking for it to be reported here, so here it is.

I've tried restarting my cactbot plugins and overlayplugin dll, and unblocking the RARs, re-extracting them, and trying again, but that doesn't seem to have done anything. 

Your input would be appreciated. Holler if you need more information or screenshots.

![ss (2019-04-12 at 05 03 59)](https://user-images.githubusercontent.com/49574855/56072011-8e1f7c00-5d47-11e9-94b6-69cf8dd8caaf.png)

**Comment by quisquous** [comment]
You are using an old version of cactbot (0.7.0).  You should just manually update to https://github.com/quisquous/cactbot/releases/latest

**Comment by Mixx-Mixx** [comment]
Hi. I don't know if Shuri was using an old version, but I'm 100% certain I'm not, and I'm getting the same error message. Just today I used that link you provided after a fresh install of FFXIV and ACT.
![Murple](https://user-images.githubusercontent.com/50155889/56995895-462e9080-6b60-11e9-87a6-34189c27044c.png)

**Comment by quisquous** [comment]
Sorry for the belated response.  What do the log messages say in your plugin window? They should print out the detected version numbers and the file locations on disk that it found them in.

Are those the expected versions and locations?

**Comment by Xesyto** [comment]
I'm seeing the same problem for a while, i was hoping a new update would resolve it but no. 

This is a screenshot of the log window. Let me know if you need more information. 

https://i.imgur.com/Ui84sOs.png

**Comment by quisquous** [comment]
@Xesyto It looks like you have cactbot 0.7.0.  I think since then, the github page has changed and so the updating code from that old version no longer works.  Have you tried downloading the latest release of cactbot and updating?

**Comment by Xesyto** [comment]
I updated before writing my post. However to be 100% sure I removed Overlayplugin and everything associated and reinstalled from scratch. This seems to have solved this. 

I'm still not sure why because I genuinely did update it before but I guess I just won't worry about it.

**Comment by Xesyto** [comment]
I updated before writing my post. However to be 100% sure I removed Overlayplugin and everything associated and reinstalled from scratch. This seems to have solved this. 

I'm still not sure why because I genuinely did update it before but I guess I just won't worry about it.

**Comment by quisquous** [comment]
@Xesyto Yeah, I believe you.  My guess is that when you updated it either went into the wrong place or somehow didn't overwrite the old plugin, and so it was still picking up your old 0.7.0 plugin.  Glad you got it sorted!

@Mixx-Mixx Are you still having this same issue?

**Comment by quisquous** [comment]
As there hasn't been a response here for a while, I'm going to close this.  Please let me know if this is still happening.
