### ISSUE TITLE
[Cactbot] P2S Triggers are confusing, inconsistent with how P3S is done.

### ISSUE THREAD

**Issue by jfeliciano-dev** [quisquous/cactbot#4014]
## Summary

Brief explanation of the feature you'd like to request.
P2S: For Winged/Spoken Cataract callout is "Cleave Behind Head"/"Cleave in front of head", calling out areas that are not safe.
P3S: For Left/Right Cinderwing callout is the current safespot.  

I understand that there isn't a true "safespot" for Cataracts but the logic between the two should be similar.

**Comment by Akurosia** [comment]
Maybe a translation is wrong but in english Winged Cataract should alert you with `Front of head` and Spoken Cararact should be `Back of head`

**Comment by jfeliciano-dev** [comment]
I play in english and Winged's callout is "CLEAVE BEHIND HEAD"  which is "correct" just inconsistent with the way Cactbot has called mechanics in the past.  If the callout for Winged is supposed to be "Front of head" than that would be more consistent/ correct to me.

**Comment by Akurosia** [comment]
https://github.com/quisquous/cactbot/blob/main/ui/raidboss/data/06-ew/raid/p2s.ts#L86
https://github.com/quisquous/cactbot/blob/main/ui/raidboss/data/06-ew/raid/p2s.ts#L105

These are the entries for the head callouts and even if you are looking for the word "cleave" it does not find a single match. Do you have custom triggers e.g. of a friend of yours?

**Comment by jfeliciano-dev** [comment]
I'm an idiot, Aho if you read this your triggers stink.  Thanks for the replies >:)
