### ISSUE TITLE
Raidboss: O4S Triggers/Alerts not working

### ISSUE THREAD

**Issue by Macapple96** [quisquous/cactbot#402]
The triggers for **O4S** are not working correctly. 
Most triggers don't work, the only one i've seen playing as a **Tank** in _O4S1 (Exdeath)_ is the Vacuum Wave alert.

I'm not even completely sure what's wrong, in the _O4S2 (Neo Exdeath)_ fight, it sometimes caused a "{Player} Holmgang" alert when using [Inner Release]

I've tried to fix it myself by reverse engineering the O8S triggers, but to little avail.

- Ravahn FFXIV Plugin Version: 1.7.2.8
- Cactbot Version: 0.9.4 (Yojimbo)

**Comment by quisquous** [comment]
Unfortunately, this is due to https://github.com/ravahn/FFXIV_ACT_Plugin/issues/203 and is not a cactbot issue.

**Comment by Macapple96** [comment]
> Unfortunately, this is due to [ravahn/FFXIV_ACT_Plugin#203](https://github.com/ravahn/FFXIV_ACT_Plugin/issues/203) and is not a cactbot issue.

I see. Should I leave the issue open so it is returned in the issue query even with a "is:open" filter to potentially prevent more duplicates?
