### ISSUE TITLE
Request: Clarification on Position Alerts

### ISSUE THREAD

**Issue by mnejing** [quisquous/cactbot#4028]
This is less a full request, more of a tidying up of semantics. 

As it stands now, when an ability requires you to position Right/Left/Front/Behind, it just says the direction. I can't pull a solid example off the top of my head, but it's not always consistent. Sometimes right means the ability is firing on the right and you should stand left, sometimes it means go right because it's happening on the left. 

I'd just like to suggest that it's consistent and perhaps adjust the warnings to say "Go Right" or "Go Left" instead of just "Right" or "Left." In the biggest "figure yourself out" moment I'll have here, I find an ambiguous statement such as "right" or "left" requires extra mental processing and ultimately having to look for sometimes less-than-obvious cues and end up getting hit anyway. 

This is already done on some encounters already, for example "Go Northwest" on the Zodiark fight. 

Nothing major, just asking for official consistency and more verbose directions.

**Comment by quisquous** [comment]
This was mentioned in #3958 as well.  cactbot in general will only call the safe spot.  "Right" and "Go Right" always mean the same thing.  If there's a place where this is inconsistent, please let us know!

**Comment by Legends0** [comment]
I think the p2n and p2s callouts for Dissociation for instance currently call out side of the map it is diving.

**Comment by mnejing** [comment]
I'm going to post again here, about inconsistency. 

I never did Seiryu when it was current, I was taking a break during Stormblood. However, it just came up for me in my trial roulette and I relied on Cactbot to get me through it. Guess what, it did. And one of the best things about it? The part with the big water guy slamming his fist down on either the left or right. It was entirely and completely unambiguous: "<= GO LEFT/WEST" and "GO RIGHT/EAST =>"

No thinking about it, it was clear, unambiguous. This is all I was originally asking for, and it's certainly, as I said, not a completely crazy request because it's already being done.

**Comment by quisquous** [comment]
I don't think that there's anything else I can do in terms of cactbot changes here.  If you prefer "Go Right" over "Right" (which will always mean the same thing for cactbot), you can change this text in the config ui.  cactbot will never say "right" to mean "don't go right" ever.
