### ISSUE TITLE
Changed in /user/raidboss.js not applying

### ISSUE THREAD

**Issue by itanimo** [quisquous/cactbot#403]
I'm editing the volume and sound file of InfoSounds in /user/raidboss.js (renamed from raidboss-example.js) but the changes I'm doing there are not being applied. Volume and Sound are still the default ones.

this is the field I'm changing:

```
// Volume between 0 and 1 to play the InfoSound at.
Options.InfoSoundVolume = 0.3;
```
the value 0.3 is not being applied.

Things I've tried:

1. Restarting ACT after applying changes
2. Double checking if the values I changed in the file are there
3. Editing the 'raidboss.js' file itself in /cactbot/ui/raidboss/raidboss.js
4. Reloading Overlay after each change

Any steps im missing to do these changes? I just want to adjust the volume for now.

**Comment by quisquous** [comment]
Hmm.  I verified that `Options.InfoSoundVolume` correctly works for me.

One thing you could do to debug temporarily is to add the line `console.log(soundVol + ' ' + soundUrl);` into *cactbot/ui/raidboss/popup-text.js* right after `audio.play()` here: https://github.com/quisquous/cactbot/blob/master/ui/raidboss/popup-text.js#L454

That will print out in the plugin log what volume it thinks it is playing at, and you can verify if your option is having an effect.

**Comment by quisquous** [comment]
Hi, is this still happening?

**Comment by itanimo** [comment]
Didn't get into testing it, but the volume was still loud even after changing. 

Is this the correct adjustment to debug it?
![image](https://user-images.githubusercontent.com/17196731/59997035-82640600-9664-11e9-9a36-6e5c3d07ffea.png)

**Comment by DrLippe** [comment]
> I'm not super familiar with the plugin log to check the volume, thats in ACT itself right?

Yes, the log is at the bottom of the window where you added the overlay. 
Whenever a sound is played it should print a line that says 
`Raidboss: BrowserConsole: 0.3 ../../resources/sounds/somesound.wav (Source: bla bla bla..., Line: 455)`
or something similar

**Comment by quisquous** [comment]
Hi, I'm going to close this old issue.  If this is still a problem, let me know and we can debug further.
