### ISSUE TITLE
Config question: Migrating config to a different PC

### ISSUE THREAD

**Issue by TokisakiKuromi** [quisquous/cactbot#4030]
If I were to make config changes under the Cactbot Config tab in ACT, and I get a new PC and need to install ACT and Cactbot again, is there a way to transfer the config settings I changed to the new install or would I need to redo them again?
Thank you!

**Comment by quisquous** [comment]
For reference, https://github.com/quisquous/cactbot/blob/main/docs/CactbotCustomization.md#using-the-cactbot-ui mentions where the file is that you need to back up.  Maybe I can make that more visible?  That file also has all of your overlayplugin settings.

**Comment by TokisakiKuromi** [comment]
Awesome, thank you very much.
I think it would be helpful to have the file location/link to the documentation somewhere at the top of the config screen inside ACT itself, in case other people want to do the same thing and also don't know it is in the documentation here.
I'm not sure which piece of info would be best, since having the file link might eventually have a bunch of info on there as the plugin gets bigger and more people ask questions, but having the documentation link might confuse/turn off some users but it keeps the screen clean.
Thank you again and keep up the great work on this plugin!
