### ISSUE TITLE
ZoneId.MatchAll shows ??? in UI

### ISSUE THREAD

**Issue by fakedestinyck** [quisquous/cactbot#4043]
## Description

In my user-defined js, I copied the example file, with `zoneId = ZoneId.MatchAll`. When I reload the plugin, it shows something like "???".

## Additional information

In my user-defined `rainbows.js` file, I have something like this:
```
const caresAboutTankStuff = (data) => {
    return data.role === "tank" || data.role === "healer" || data.job === "BLU";
};
// Triggers for all occasions and zones.
Options.Triggers.push({
    zoneId: ZoneId.MatchAll,
    triggers: [
        {
            id: "General Provoke",
            disabled: false,
            type: "Ability",
            netRegex: NetRegexes.ability({
                id: "1D6D",
            }),
            condition: (data, matches) => {
                if (
                    matches.source !== data.me &&
                    !data.party.inAlliance(matches.source)
                )
                    return false;
                return caresAboutTankStuff(data);
            },
            infoText: (data, matches, output) =>
                output.text({
                    player: data.ShortName(matches.source),
                }),
            outputStrings: {
                text: {
                    en: "Provoke: ${player}",
                    de: "Herausforderung: ${player}",
                    fr: "Provocation: ${player}",
                    ja: "挑発: ${player}",
                    cn: "挑衅: ${player}",
                    ko: "도발: ${player}",
                },
            },
        },
    ],
});
```
Which is the same as the sample file. Then when I reload the plugin, I saw
<img width="250" alt="image" src="https://user-images.githubusercontent.com/16526801/150018251-de01711f-68bd-4103-ade1-0e36ca74ea4c.png">

And one more thing is when I tried to trigger that, it seems it was triggered twice (The built-in one is not overridden).

**Comment by valarnin** [comment]
PR #4412 fixes the display issue. I can't reproduce the double trigger firing issue and as far as I can tell it should work as-is.

**Comment by quisquous** [comment]
> PR https://github.com/quisquous/cactbot/pull/4412 fixes the display issue. I can't reproduce the double trigger firing issue and as far as I can tell it should work as-is.

If this is still happening, please file another issue.
