### ISSUE TITLE
my raid boss alert and timeline not showing at pandemonium savage

### ISSUE THREAD

**Issue by 73u38** [quisquous/cactbot#4045]
my raid boss alert and timeline not showing at pandemonium savage. but it worked everywhere except pandemonium savage

**Comment by 73u38** [comment]
nope still not working even i restarting my ACT it wont appear at all

**Comment by atoxiclemon** [comment]
I've been having the same issue - they show up in every single piece of content (trials, EX trials, old raids, dungeons, etc.), but don't show up in P1S/P2S/P3S/P4S (they do show up in Normal mode of the raids, just not Savages). I have the latest version & everything enabled, and i'm not changing any settings around between instances - I can queue into a dungeon and have everything show up but if I load into any of the P Savages then nothing shows up.

**Comment by quisquous** [comment]
I think @Kryomancer's issue is separate and is listed in #4046.  The rest of you should ask in the ffxiv ACT discord for support.  In general, I would suggest deleting cactbot directories and re-getting the plugin.  See: https://discord.gg/hK523Pj

**Comment by jiayangmiao** [comment]
I have tried deleting cactbot and re-getting the plugin, have also tried reinstalling ACT and everything. This issue would just randomly happen and there is a small chance to fix it if I restart ACT. This happens not just to pandemonium savage but to all instances. Parser itself has been working fine (test connection works).

**Comment by quisquous** [comment]
If the issue is happening only sometimes, then it is likely #4046.  If the issue is persistent, then it is likely some setup issue that you should resolve with more direct support in the ffxiv ACT discord.
