### ISSUE TITLE
Cactbot overlays randomly stop receiving data

### ISSUE THREAD

**Issue by Kryomancer** [quisquous/cactbot#4046]
## Description

Occasionally all of my cactbot overlays simply disappear and stop functioning. It seems as if they're simply receiving no data, as unlocking their position brings up the positioning guides so they are definitely still there, just not showing anything. Recently this has started occurring fairly frequently. Usually restarting ACT fixes this, until it eventually happens again.

On ACT window all the cactbot menus seem to be working as usual and no errors are shown. Parsing is otherwise working correctly and overlays that don't use cactbot show correct DPS etc.

So far I've confirmed this is affecting raidboss, oopsy, fisher, hunt radar and eureka map, so I'd assume it's every single cactbot overlay.

Enabling Cactbot test shows only the current zone and target info, all other information is missing:

![screenshot](https://i.imgur.com/68JAjKX.png)

## Versions

FFXIV ACT plugin 2.6.3.9
OverlayPlugin (ngld) 0.18.0.0
Cactbot 0.24.14.0

Let me know if there are some logs that would particularly help with diagnosing this.

**Comment by hfluz** [comment]
This issue is also happening with me.

**Comment by jiayangmiao** [comment]
I have been running into the same issue, a small chance of it fixing itself if I reboot ACT. 
Have tried reinstalling cactbot and it will happen the next time I launch ACT.

**Comment by Kryomancer** [comment]
There has been some discussion about this issue on the FFXIV ACT Discord and it's been suggested that the likely cause is that Cactbot for some reason fails to get the process ID, which means that only the data that come from sources other than Cactbot reading the memory (the zone, for example) still work while Cactbot breaks otherwise. 

I've managed to pinpoint that this issue either occurs or doesn't whenever ACT is started up and will persist until ACT is restarted, or conversely keep working until ACT is restarted, which makes sense if the PID acquisition at startup is randomly failing.

I've check the PID switcher in ACT and I only ever have one PID under there, so it's not mistaking something else for the process. Swapping between default and the current PID doesn't affect the issue.

I imagine this could be related to the changes in https://github.com/quisquous/cactbot/pull/3915 since it greatly changed how the PID is obtained and I never ran into this issue prior to that version.

**Comment by Shizzz104** [comment]
Are you guys using xivAlexander by a chance?
Because this is exactly the issue I get unless I disable/reinstall Alexander.
If I reinstall it it's ok for few days, and then it start happening again.

**Comment by quisquous** [comment]
This should be fixed in the next release.  Let me know if it isn't.
