### ISSUE TITLE
Possibility of rumble/force feedback for raidboss timeline

### ISSUE THREAD

**Issue by Genesis-Nova** [quisquous/cactbot#4055]
Been using cactbot for a long time now and I appreciate all the work gone into this over the years

Having recently gone deaf a few months ago and relying on cactbot more than I have before, it'd be nice to have the option for rumble alerts as I'm unable to hear sound alerts for raidboss anymore.

**Comment by valarnin** [comment]
This is technically possible, e.g. following these steps will cause the controller to vibrate:

1. Plug in controller with vibration/haptic feedback support, my test controller was an Xbox 360 controller.
2. Open dev tools for any overlay
3. Press a button on the controller
4. Run the following JS in the console to test:
```js
[...navigator.getGamepads()].filter(gp=>gp).forEach(gp=>{
  gp.vibrationActuator.playEffect(gp.vibrationActuator.type, {
    duration: 100, //ms
    weakMagnitude: 0, //left
    strongMagnitude: 1.0, //right
  });
});
```

As for how exactly this would/should be implemented in cactbot itself, I have no clue.

It's also important to note that the gamepad interface has a v2 spec that this functionality might need to be migrated to eventually depending on if/when OverlayPlugin next updates CEF.

**Comment by Genesis-Nova** [comment]
Testing that snip in chrome works just fine for my gamepads, and same as you I'd be at a loss at how to implement that into cactbot, don't really have much js experience myself

**Comment by quisquous** [comment]
Yeah, I think this is definitely something we could implement.  Do you think we should have different info/alert/alarm vibration levels?  Do you have any suggestions for durations/magnitudes you might want for each of those?

**Comment by Genesis-Nova** [comment]
Would it be too difficult to have strength/duration be user definable? or in steps like 1, 2, 3 secs for duration etc and steps of 10% for strength I don't know what would be best for how its configured internally.

**Comment by quisquous** [comment]
Yeah, it's something we could add options for.  It'd be nice to have good defaults though, I think?  I can play around with it too.

**Comment by Genesis-Nova** [comment]
For defaults? Hm could do something like 1 sec duration and 50% strength on both motors

**Comment by valarnin** [comment]
Maybe something like:

```ts
const hapticDefaults = {
  'info': {
    duration: 500, //ms
    weakMagnitude: 0.5, //left
    strongMagnitude: 0, //right
  },
  'alert': {
    duration: 500, //ms
    weakMagnitude: 0, //left
    strongMagnitude: 0.5, //right
  },
  'alarm': {
    duration: 750, //ms
    weakMagnitude: 0.75, //left
    strongMagnitude: 0.75, //right
  },
};
```
