### ISSUE TITLE
raidboss: timelineTrigger beforeSeconds support (data) => functions

### ISSUE THREAD

**Issue by Legends0** [quisquous/cactbot#4056]
I would like to be able to have a timelineTrigger be able to trigger at different times based on return value of a function from raidboss data.

Currently beforeSeconds does not appear to have access to data:
```
webpack 5.64.4 compiled with 2 errors in 2938 ms
ERROR in ui/raidboss/data/06-ew/raid/p4s.ts:148:22
TS2322: Type '(data: any) => 7 | 5.3' is not assignable to type 'number'.
    146 |       id: 'P4S Kothornos Kick',
    147 |       regex: /Kothornos Kick/,
  > 148 |       beforeSeconds: (data) => !data.kickTwo ? 7 : 5.3,
        |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    149 |       infoText: (data, _matches, output) => {
    150 |         let jumpDir;
    151 |         if (data.jumpDir1 === 'east')

ERROR in ui/raidboss/data/06-ew/raid/p4s.ts:148:23
TS7006: Parameter 'data' implicitly has an 'any' type.
    146 |       id: 'P4S Kothornos Kick',
    147 |       regex: /Kothornos Kick/,
  > 148 |       beforeSeconds: (data) => !data.kickTwo ? 7 : 5.3,
        |                       ^^^^
    149 |       infoText: (data, _matches, output) => {
    150 |         let jumpDir;
    151 |         if (data.jumpDir1 === 'east')
```

Is there a better way I should implement this type of behavior? I'm not really certain how valuable this could be as perhaps this is better handled by just continuing to have the beforeSeconds always be the same each time.

**Comment by valarnin** [comment]
There's a `TODO` note for this functionality, so I assume it's wanted but hasn't been needed yet and requires a significant amount of effort. I'm not sure exactly how you'd go about implementing this change since this is fundamentally different than the way timeline triggers currently work.

Timeline triggers currently are pre-populated on timeline load to always check at the given `beforeSeconds` point in timeline evaluation.

https://github.com/quisquous/cactbot/blob/b020d44123289ef50940cdcb08efe9a8b331ae25/ui/raidboss/timeline_parser.ts#L332-L341

**Comment by Legends0** [comment]
Thanks for that info! Looks like in my case it'd be best to have two triggers then for first event and second event, using a condition to prevent the first from firing during the second, or just calling them both with same beforeSeconds. My case may also work timing with related events on second kick.

**Comment by quisquous** [comment]
You could always use a dynamic delaySeconds too.

**Comment by quisquous** [comment]
I agree with valarnin here.  There is a TODO, but implementing that TODO would be very complicated to do.  I think the best bet in the short term is to use a combination of `beforeSeconds` and `delaySeconds` to get the dynamic behavior that you want.
