### ISSUE TITLE
raid overlay is not working 

### ISSUE THREAD

**Issue by jenkshi** [quisquous/cactbot#406]
5/2/2019 2:51:08 AM: Info: InitPlugin: PluginDirectory = C:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin
5/2/2019 2:51:08 AM: Info: LoadAddons: C:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin\addons\CactbotOverlay.dll
5/2/2019 2:51:08 AM: Info: LoadAddons: Cactbot.OverlayAddonMain: Initialized
5/2/2019 2:51:09 AM: Info: InitPlugin: Initialized.
5/2/2019 2:51:11 AM: Error: raid: Update: System.IO.FileNotFoundException: Could not load file or assembly 'FFXIV_ACT_Plugin, Version=1.6.2.5, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'FFXIV_ACT_Plugin, Version=1.6.2.5, Culture=neutral, PublicKeyToken=null'
   at Cactbot.VersionChecker.GetFFXIVPluginVersion()
   at Cactbot.CactbotOverlay.Initialize()
   at Cactbot.CactbotOverlay.Update()
   at RainbowMage.OverlayPlugin.OverlayBase`1.<InitializeTimer>b__10(Object o, ElapsedEventArgs e)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

5/2/2019 2:51:12 AM: Error: raid: No FFXIV_ACT_Plugin.dll found? Can't set language automatically.
5/2/2019 2:51:12 AM: Error: raid: Exception in SendFastRateEvents: Could not load file or assembly 'FFXIV_ACT_Plugin, Version=1.6.2.5, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
5/2/2019 2:51:12 AM: Error: raid: Stack:    at Cactbot.CactbotOverlay.SendFastRateEvents()
   at Cactbot.CactbotOverlay.<Initialize>b__76_0(Object o, ElapsedEventArgs args)
5/2/2019 2:51:12 AM: Error: raid: Source: CactbotOverlay
5/2/2019 2:51:12 AM: Error: opss: No FFXIV_ACT_Plugin.dll found? Can't set language automatically.
5/2/2019 2:51:12 AM: Error: opss: Exception in SendFastRateEvents: Could not load file or assembly 'FFXIV_ACT_Plugin, Version=1.6.2.5, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
5/2/2019 2:51:12 AM: Error: opss: Stack:    at Cactbot.CactbotOverlay.SendFastRateEvents()
   at Cactbot.CactbotOverlay.<Initialize>b__76_0(Object o, ElapsedEventArgs args)
5/2/2019 2:51:12 AM: Error: opss: Source: CactbotOverlay
5/2/2019 2:51:12 AM: Error: raid: Exception in SendFastRateEvents: Could not load file or assembly 'FFXIV_ACT_Plugin, Version=1.6.2.5, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
5/2/2019 2:51:12 AM: Error: raid: Stack:    at Cactbot.CactbotOverlay.SendFastRateEvents()
   at Cactbot.CactbotOverlay.<Initialize>b__76_0(Object o, ElapsedEventArgs args)
5/2/2019 2:51:12 AM: Error: raid: Source: CactbotOverlay
5/2/2019 2:51:12 AM: Error: opss: Exception in SendFastRateEvents: Could not load file or assembly 'FFXIV_ACT_Plugin, Version=1.6.2.5, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
5/2/2019 2:51:12 AM: Error: opss: Stack:    at Cactbot.CactbotOverlay.SendFastRateEvents()
   at Cactbot.CactbotOverlay.<Initialize>b__76_0(Object o, ElapsedEventArgs args)
5/2/2019 2:51:12 AM: Error: opss: Source: CactbotOverlay
5/2/2019 2:51:12 AM: Error: raid: Exception in SendFastRateEvents: Could not load file or assembly 'FFXIV_ACT_Plugin, Version=1.6.2.5, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
5/2/2019 2:51:12 AM: Error: raid: Stack:    at Cactbot.CactbotOverlay.SendFastRateEvents()
   at Cactbot.CactbotOverlay.<Initialize>b__76_0(Object o, ElapsedEventArgs args)
5/2/2019 2:51:12 AM: Error: raid: Source: CactbotOverlay
5/2/2019 2:51:12 AM: Error: opss: Exception in SendFastRateEvents: Could not load file or assembly 'FFXIV_ACT_Plugin, Version=1.6.2.5, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
5/2/2019 2:51:12 AM: Error: opss: Stack:    at Cactbot.CactbotOverlay.SendFastRateEvents()
   at Cactbot.CactbotOverlay.<Initialize>b__76_0(Object o, ElapsedEventArgs args)
5/2/2019 2:51:12 AM: Error: opss: Source: CactbotOverlay
5/2/2019 2:51:12 AM: Error: raid: Exception in SendFastRateEvents: Could not load file or assembly 'FFXIV_ACT_Plugin, Version=1.6.2.5, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
5/2/2019 2:51:12 AM: Error: raid: Stack:    at Cactbot.CactbotOverlay.SendFastRateEvents()
   at Cactbot.CactbotOverlay.<Initialize>b__76_0(Object o, ElapsedEventArgs args)
5/2/2019 2:51:12 AM: Error: raid: Source: CactbotOverlay
5/2/2019 2:51:12 AM: Error: opss: Exception in SendFastRateEvents: Could not load file or assembly 'FFXIV_ACT_Plugin, Version=1.6.2.5, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
5/2/2019 2:51:12 AM: Error: opss: Stack:    at Cactbot.CactbotOverlay.SendFastRateEvents()
   at Cactbot.CactbotOverlay.<Initialize>b__76_0(Object o, ElapsedEventArgs args)
5/2/2019 2:51:12 AM: Error: opss: Source: CactbotOverlay
5/2/2019 2:51:12 AM: Error: raid: Exception in SendFastRateEvents: Could not load file or assembly 'FFXIV_ACT_Plugin, Version=1.6.2.5, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
5/2/2019 2:51:12 AM: Error: raid: Stack:    at Cactbot.CactbotOverlay.SendFastRateEvents()
   at Cactbot.CactbotOverlay.<Initialize>b__76_0(Object o, ElapsedEventArgs args)
5/2/2019 2:51:12 AM: Error: raid: Source: CactbotOverlay
5/2/2019 2:51:12 AM: Error: opss: Exception in SendFastRateEvents: Could not load file or assembly 'FFXIV_ACT_Plugin, Version=1.6.2.5, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
5/2/2019 2:51:12 AM: Error: opss: Stack:    at Cactbot.CactbotOverlay.SendFastRateEvents()
   at Cactbot.CactbotOverlay.<Initialize>b__76_0(Object o, ElapsedEventArgs args)
5/2/2019 2:51:12 AM: Error: opss: Source: CactbotOverlay
5/2/2019 2:51:12 AM: Error: raid: Exception in SendFastRateEvents: Could not load file or assembly 'FFXIV_ACT_Plugin, Version=1.6.2.5, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
5/2/2019 2:51:12 AM: Error: raid: Stack:    at Cactbot.CactbotOverlay.SendFastRateEvents()
   at Cactbot.CactbotOverlay.<Initialize>b__76_0(Object o, ElapsedEventArgs args)
5/2/2019 2:51:12 AM: Error: raid: Source: CactbotOverlay
5/2/2019 2:51:12 AM: Error: opss: Exception in SendFastRateEvents: Could not load file or assembly 'FFXIV_ACT_Plugin, Version=1.6.2.5, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
5/2/2019 2:51:12 AM: Error: opss: Stack:    at Cactbot.CactbotOverlay.SendFastRateEvents()
   at Cactbot.CactbotOverlay.<Initialize>b__76_0(Object o, ElapsedEventArgs args)
5/2/2019 2:51:12 AM: Error: opss: Source: CactbotOverlay
5/2/2019 2:51:12 AM: Error: raid: Exception in SendFastRateEvents: Could not load file or assembly 'FFXIV_ACT_Plugin, Version=1.6.2.5, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
5/2/2019 2:51:12 AM: Error: raid: Stack:    at Cactbot.CactbotOverlay.SendFastRateEvents()
   at Cactbot.CactbotOverlay.<Initialize>b__76_0(Object o, ElapsedEventArgs args)
5/2/2019 2:51:12 AM: Error: raid: Source: CactbotOverlay
5/2/2019 2:51:12 AM: Error: opss: Exception in SendFastRateEvents: Could not load file or assembly 'FFXIV_ACT_Plugin, Version=1.6.2.5, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
5/2/2019 2:51:12 AM: Error: opss: Stack:    at Cactbot.CactbotOverlay.SendFastRateEvents()
   at Cactbot.CactbotOverlay.<Initialize>b__76_0(Object o, ElapsedEventArgs args)
5/2/2019 2:51:12 AM: Error: opss: Source: CactbotOverlay
5/2/2019 2:51:12 AM: Error: raid: Exception in SendFastRateEvents: Could not load file or assembly 'FFXIV_ACT_Plugin, Version=1.6.2.5, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
5/2/2019 2:51:12 AM: Error: raid: Stack:    at Cactbot.CactbotOverlay.SendFastRateEvents()
   at Cactbot.CactbotOverlay.<Initialize>b__76_0(Object o, ElapsedEventArgs args)
5/2/2019 2:51:12 AM: Error: raid: Source: CactbotOverlay
5/2/2019 2:51:12 AM: Error: opss: Exception in SendFastRateEvents: Could not load file or assembly 'FFXIV_ACT_Plugin, Version=1.6.2.5, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
5/2/2019 2:51:12 AM: Error: opss: Stack:    at Cactbot.CactbotOverlay.SendFastRateEvents()
   at Cactbot.CactbotOverlay.<Initialize>b__76_0(Object o, ElapsedEventArgs args)
5/2/2019 2:51:12 AM: Error: opss: Source: CactbotOverlay

**Comment by quisquous** [comment]
Hope you got this figured out!

**Comment by jenkshi** [comment]
Thx dude
