### ISSUE TITLE
Download interrupted loop

### ISSUE THREAD

**Issue by itchystag** [quisquous/cactbot#4069]
## Description

Every time I try to update Cactbot with the new patch, the download gets interrupted and restarts again, resulting in an endless loop of being stuck at [1/2]

This is the message that keeps popping up: 
The download was interrupted: RainbowMage.OverlayPlugin.Updater.CurlException: Request to "https://github.com/quisquous/cactbot/releases/download/v0.24.15/cactbot-0.24.15.zip" failed: CURLE_PARTIAL_FILE; transfer closed with 4399177 bytes remaining to read
   at RainbowMage.OverlayPlugin.Updater.CurlWrapper.Get(String url, Dictionary`2 headers, String downloadDest, ProgressInfoCallback info_cb, Boolean resume)
   at RainbowMage.OverlayPlugin.Updater.Installer.Download(String url, String dest, Boolean useHttpClient)
Resuming download...

**Comment by quisquous** [comment]
Sorry, I'm not sure what's going on here.  cactbot uses OverlayPlugin's updater mechanism.  It sounds like maybe github is having issues, and you might consider just grabbing the cactbot release manually and replacing your local files.

**Comment by itchystag** [comment]
Huh it somehow worked after a while, prob was just github fuckery lol 👍
