### ISSUE TITLE
Eureka - Critical Engagements (EU)

### ISSUE THREAD

**Issue by hdstarx** [quisquous/cactbot#4075]
Critical Engagements don't pop on eureka overlay. This counts for both, Bozja & Zadnor. since the last update.

![image](https://user-images.githubusercontent.com/32071943/151675673-373eb8c5-d189-4921-a0e2-1715fd183ad3.png)

![image](https://user-images.githubusercontent.com/32071943/151675749-d393cf14-2f7c-4b1f-bd5f-3c3a9da8918c.png)
(Sorry HDR on :D )

**Comment by quisquous** [comment]
Should be fixed with #4071
