### ISSUE TITLE
pullcounter error on line 98

### ISSUE THREAD

**Issue by ezsoftware** [quisquous/cactbot#41]
2/5/2018 1:58:47 PM: Info: pullcounter: BrowserConsole: Uncaught TypeError: Cannot read property 'OnLogEvent' of undefined (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/cactbot/ui/pullcounter/pull_counter.js, Line: 98)

**Comment by quisquous** [comment]
Thanks.  I think I see what's happening here.  I need to create the objects immediately but then wait for document load to grab the elements out of the dom.  I think this error is the same reason I see null children when using oopsyraidsy from github pages.
