### ISSUE TITLE
Callouts not happening randomly

### ISSUE THREAD

**Issue by Khuzvhan** [quisquous/cactbot#4102]
I'm experiencing this for like a week now.  sometimes the timeline doesn't show, or TTS for the same ability in the same fight just don't happen, but then work on the next cast. 
I got back to the game recently and waited a few days just in case some ACT update or cact update would fix it, but since there's not many recent issue posts about Cact behaving inconsistently I imagine something is wrong on my side. 

looking for some advice to not loose my personal configs (if possible)

some details

I do
-Receive automatic updates 
-Hear TTS callouts
-See the Timeline
-See screen warnings

They just fail at random

I Tried
-Disabling/Enabling on ACT
-Re-adding ACT on firewall permissions (DPS meter always works so it's unlikely ACT being blocked I guess)

**Comment by VanSlanzar** [comment]
Same problem, even after removing and reinstalling plugins

**Comment by quisquous** [comment]
Yeah, I haven't heard anything about this.  The only inconsistent thing I know about is #4046, but that's either "everything works" or "nothing works until you restart ACT".

Can you explain what "fail at random" means? Just...sometimes the timeline doesn't start but sometimes it does? In the same fight sometimes at trigger shows but sometimes it doesn't? If you have video/network log of this happening, that would help a lot.

**Comment by VanSlanzar** [comment]
Sometimes the timeline doesn't start sometimes it does. I don't know why. For anything content.

**Comment by quisquous** [comment]
Yeah, I need something more specific.  If you have a particular instance where the timeline doesn't start, please attach a Network log here and let me know which instance it didn't work in.

**Comment by VanSlanzar** [comment]
I'm still trying to reinstall properly. If this continues I will try to send a network log and maybe a video. I want to be sure that the problem is not mine. I'm still looking a bit.

**Comment by Khuzvhan** [comment]
> Yeah, I need something more specific. If you have a particular instance where the timeline doesn't start, please attach a Network log here and let me know which instance it didn't work in.

It's hard for me to record long sessions but for instance, it is exactly as you described on the 1st Reply. 

As for Network Logs. I'll keep an eye from now on and post here on the next instance it occurs. I didn't know about it. sorry. 

But taking an overall look at the files I've noticed lines lines these on many boss fights.

251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: >2 sec since last processed packet, resetting stream.|d927f0e20734042d
251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: Missing Sequence # [1872320382], Dropping packet with sequence # [1872328281].|e4f436f2c6b957db
251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: Missing Sequence # [1872320382], Dropping packet with sequence # [1872328012].|76fc8b8c2681109d
251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: Missing Sequence # [1872320382], Dropping packet with sequence # [1872327924].|c3d27dc2af37ccc9
251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: Missing Sequence # [1872320382], Dropping packet with sequence # [1872327545].|1d1ddca09292458d
251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: Missing Sequence # [1872320382], Dropping packet with sequence # [1872327282].|fb5422c5255d8ac9
251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: Missing Sequence # [1872320382], Dropping packet with sequence # [1872327002].|96c5a466ff737951
251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: Missing Sequence # [1872320382], Dropping packet with sequence # [1872326914].|63c9313d168a9abf
251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: Missing Sequence # [1872320382], Dropping packet with sequence # [1872326786].|39bfbd8df7726926
251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: Missing Sequence # [1872320382], Dropping packet with sequence # [1872326590].|985672f1269989f4
251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: Missing Sequence # [1872320382], Dropping packet with sequence # [1872326234].|5867a23a0ccd1535
251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: Missing Sequence # [1872320382], Dropping packet with sequence # [1872325888].|d2e556d10462cb34
251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: Missing Sequence # [1872320382], Dropping packet with sequence # [1872325679].|5f7b99bd1d3c4a5b
251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: Missing Sequence # [1872320382], Dropping packet with sequence # [1872325378].|070fb612e5f19043
251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: Missing Sequence # [1872320382], Dropping packet with sequence # [1872325086].|2487c4806ea7fb4c
251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: Missing Sequence # [1872320382], Dropping packet with sequence # [1872324998].|1d2f70ea1f74b296
251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: Missing Sequence # [1872320382], Dropping packet with sequence # [1872324910].|b764fecf6fe700ee
251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: Missing Sequence # [1872320382], Dropping packet with sequence # [1872324822].|ca8805b8aca580a0
251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: Missing Sequence # [1872320382], Dropping packet with sequence # [1872324581].|ea63d14c9a338975
251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: Missing Sequence # [1872320382], Dropping packet with sequence # [1872324493].|5663705e395168ba
251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: Missing Sequence # [1872320382], Dropping packet with sequence # [1872324221].|850e943d27a2c625
251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: Missing Sequence # [1872320382], Dropping packet with sequence # [1872323954].|f10d9b3d63c7a59e
251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: Missing Sequence # [1872320382], Dropping packet with sequence # [1872323866].|10d195308a8fb98e
251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: Missing Sequence # [1872320382], Dropping packet with sequence # [1872323583].|f5404e38da63a64d
251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: Missing Sequence # [1872320382], Dropping packet with sequence # [1872323323].|89faee1b4a5e8192
251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: Missing Sequence # [1872320382], Dropping packet with sequence # [1872322963].|3483c62e86009ca5
251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: Missing Sequence # [1872320382], Dropping packet with sequence # [1872322686].|6c2e24cb81126734
251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: Missing Sequence # [1872320382], Dropping packet with sequence # [1872322502].|1cef3e0c4fb816c6
251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: Missing Sequence # [1872320382], Dropping packet with sequence # [1872322414].|7ea9249d2c567c7e
251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: Missing Sequence # [1872320382], Dropping packet with sequence # [1872322214].|6107ce387fe3e6e9
251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: Missing Sequence # [1872320382], Dropping packet with sequence # [1872322048].|94d0b8ab2fe8e9de
251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: Missing Sequence # [1872320382], Dropping packet with sequence # [1872321692].|51e4de13d4637669
251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: Missing Sequence # [1872320382], Dropping packet with sequence # [1872321498].|8de2bccff3b06b3d
251|2022-02-03T10:50:24.0000000-03:00|TCPDecoder: Missing Sequence # [1872320382], Dropping packet with sequence # [1872320808].|c40a4e343b5e2ea1

**Comment by jarrettcommmm** [comment]
I'm having this issue as well, cactbot calls work for 1-2 bosses, then just does nothing until restarted. Leveling an alt through MSQ, and it happen almost every other boss fight.

**Comment by quisquous** [comment]
Are other people seeing the `TCPDecoder: Missing Sequence` error in the logs?

**Comment by VanSlanzar** [comment]
- on The Dead Ends : no timeline, no calls.
`ProcessTCPInfo: Removing connection 192.168.1.10:52428=>52.21.76.151:443(10296)`, it's normal ?

- on ifrit, all works well.
- on seiryu, all works well.
It depends on the content, it seems.

**Comment by quisquous** [comment]
@VanSlanzar I think both of those messages are likely unrelated.  I don't know anything about ProcessTCPInfo.  The Oopsy issue is something I have tried to adjust in the past, but should not affect raidboss.

Does the timeline never work in the Dead Ends, not on any of the bosses for you? I wonder if it's a chat translation issue.  Do you have a network log?

**Comment by QuidamAzerty** [comment]
Hi ! 
I may have the same problem. Like everything's fine in P2S but P3S is empty. 
I guess you're on the right way thinking it's a chat translation issue as I use cactbot with my French FFXIV client (and I guess VanSlanzar is francophone too by looking at its past work on cactbot).
Also, another member of my static uses cactbot, has the client in English and has no problem. 

I put my log file of the evening raiding P1S to P3S in [Network_26401_20220201.2022.02.02_only_savage.log.zip](https://github.com/quisquous/cactbot/files/8026199/Network_26401_20220201.2022.02.02_only_savage.log.zip)
 (I kept the first 45 lines of initialization and deleted everything that was not relevant to the savage parts)
I hope it helps.

**Comment by quisquous** [comment]
Ok, I think I see an issue in common translations.  If I run this:

```
$ npm run util -- translateTimeline -t the_dead_ends -l fr | grep Ferm
(node:7416) ExperimentalWarning: --experimental-loader is an experimental featur
e. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
1000.0 "--synchronisation--" sync / 00:0839:Fermeture d(?:e|u|es) :Amas coquillier naufragé dans/ window 10000,0
2000.0 "--synchronisation--" sync / 00:0839:Fermeture d(?:e|u|es) :Colline des Dés jetés dans/ window 10000,0
3000.0 "--synchronisation--" sync / 00:0839:Fermeture d(?:e|u|es) :Jardin de l'Arbre-Monde dans/ window 10000,0
```

You can see that there's a colon in the name, which is incorrect.  However even if I fix the colon, there's more problems than that.  This is from a log file:

```
00|2022-02-06T22:56:30.0000000+01:00|0839||Fermeture de l'amas coquillier naufragé dans 15 secondes.|d8c2cd4b71153115
00|2022-02-06T23:02:17.0000000+01:00|0839||Fermeture de la colline des Dés jetés dans 15 secondes.|9cca17e5d7c16d87
00|2022-02-06T23:08:46.0000000+01:00|0839||Fermeture du jardin de l'Arbre-Monde dans 15 secondes.|b8025d40f1dff206
```

Does the French translation need to account for optional articles as well so that the automatic translation works? What possibilities are there? (cc @Akurosia)

**Comment by quisquous** [comment]
I think I have fixed the issues with French, but I think that is not necessarily the issues that @jarrettcommmm and @Khuzvhan were having.  @jarrettcommmm, are you having the TCPDecoder issues too?  Please let me know if you see similar issues in the future, especially if it consistently happens on a particular boss or there is anything in the logs.  If you can attach a Network log file from any situation where it is not working, that would be appreciated.

**Comment by QuidamAzerty** [comment]
Here's a full P3S night. No timeline displayed, no calls except for
- The number call for the AoEs that dispels the invulnerable status of the Darkened Fire adds
- The eyeball mobs. The cardinal direction call is made

[Network_26401_20220220.zip](https://github.com/quisquous/cactbot/files/8105020/Network_26401_20220220.zip)

Hope that helps.

**Comment by QuidamAzerty** [comment]
Well I resolved my problem ^^'
My FFXIV is in French and my FFXIV ACT plugin was set as English in the Parse Options...
So yeah, issue solve for me by switching it to French.

**Comment by quisquous** [comment]
@QuidamAzerty Glad you got it sorted out!

I'm going to close this now.  If folks are having similar/related issues, please open up another issue at this point.
