### ISSUE TITLE
Audio alerts for overcapping resources

### ISSUE THREAD

**Issue by haasn** [quisquous/cactbot#411]
Since I was slightly frustrated by how the default job gauge handles WAR's beast gauge, I decided to add my own logic to alert me when I'm about to overcap on beast gauge.

I went for something like this:

```javascript
  OnWarUpdate(beast) {
    if (this.o.beastTextBox == null)
      return;

    this.o.beastText.innerText = beast;

    if (beast == 100) {
      let audio = new Audio('../../resources/sounds/WeakAuras/Shotgun.ogg');
      audio.volume = 1.0;
      audio.play();
    }
    ...
```

However, I thought it would be better if it also warned me on 90 beast gauge, because `Storm's Path` gives 20 beast gauge. I tried using the existing combo tracker for this, something like:

```javascript
    if (beast == 100 || beast == 90 && this.combo.current == gLang.kAbility.Maim) {
      let audio = new Audio('../../resources/sounds/WeakAuras/Shotgun.ogg');
      audio.volume = 1.0;
      audio.play();
    }
```

but this doesn't work as expected. The reason is that by the time this event fires, the combo tracker hasn't been updated yet. Really, the logic I need is that it should warn me if `Maim` was the ability that got me to 90 beast gauge, since that means there's a very real possibility I might use `Storm's Path` next. But for that to work, there needs to be a correct ordering between these events so that the plugin "sees" that Maim was used *before* it updates the beast gauge.

Alternatively, I could put that logic somewhere else, i.e. have it check for (near-)capped beast gauge when the event fires for the actual ability being used that generated beast gauge.

Thoughts?

**Comment by DrLippe** [comment]
You could realize this with a trigger.

In order to get this to work, triggers need info about jobDetail:
```
popup-text.js @ line 27 insert:
  this.data.jobDetail = e.detail.jobDetail,
```
```
popup-text.js @ line 126/127 insert: 
  jobDetail: this.jobDetail,
```
Next you could use a trigger like this:
```
{
  id: 'Warrior Overcap Warining',
  regex: / 15:\y{ObjectId}:(\y{Name}):25:/,
  condition: function(data, matches) {
    return matches[1] == data.me;
  },
  run: function(data) {
    if (data.jobDetail.beast  < 90)
      return;
    let audio = new Audio('../../resources/sounds/WeakAuras/Shotgun.ogg');
      audio.volume = 1.0;
      audio.play();
  }
},
```
Checked working ✔️

**Comment by quisquous** [comment]
DrLippe's trigger seems like a great solution here.  If you need something else, please leave a comment.  Otherwise, I'm going to close this for now.
