### ISSUE TITLE
Why was the triple ice callout removed?

### ISSUE THREAD

**Issue by HerptyDerpoty** [quisquous/cactbot#4163]
Title says all.

**Comment by quisquous** [comment]
Sorry, I don't know what you are referring to here.

**Comment by jacob-keller** [comment]
What boss and what skill?

**Comment by HerptyDerpoty** [comment]
P1S 1st and second intemperance has a variation where all 3 blocks S are the same, ice, hence triple ice, before the update today/yesterday (bad sleep schedule) it had a callout for when it was triple ice, this is useful because the triple ice pattern resolves the same way regardless of if its top/bottom starting, meaning the current new callouts which just give you top/bottom callouts are pointless during triple ice, the callout for that pattern can be "triple ice" and it was before the last update.

**Comment by HerptyDerpoty** [comment]
I am actually so sorry for wasting your time, I just had the weirdest like, fake memory moment of my fucking life, some Mandela effect shit, I could have sworn there was a triple ice callout to the point I have a memory of cactbot tts calling it out but thinking about it for more then 2 seconds I remember intemperance cubes have _never_ had any callouts and I was just remembering myself calling it out every time cause I raid lead, lmao I'm very sorry, I am beyond embarrassed.

for reference i was talking about intemperance pattern triple ice in p1s, it resolves the same way regardless of top/bottom.
