### ISSUE TITLE
question: bard song procs

### ISSUE THREAD

**Issue by Vassi** [quisquous/cactbot#418]
Hi there! I couldn't find a discord or other forum link so forgive me please for asking the question here.

I've been casually messing about with a custom overlay and wanted to do something like a rotation helper to that would help me build some muscle memory.

Long story short, a lot of the classes have neat detail in their jobDetail properties to help figure out their special junk like BLM polyglot and such. I've been testing this out on bard, however, and realized really quick that I have no idea how to detect when Mage's Ballad procs or the timer/cooldown status of bloodletter. It's not a super big deal, and I know the mechanic is changing in 5.0, but I was curious about if you'd given this any thought?

I took a peek at the plugin code itself (i'm a .NET developer too) but I'm not sure how you came to the memory addresses and such so I'd be down for some tips on how to find that stuff out too. I know this is going to change in 5.0 to a flat percentage chance so maybe working on it now is not worthwhile but maybe something to consider for ShB?

**Comment by quisquous** [comment]
Nope, there's no discord or forum other than github issues, so this is the right place!

I assume that jobDetail.songProcs, songName, and songMilliseconds are not quite what you're looking for? That's really all that there is in memory for bard.  The process for jobDetail was really just getting a job to 70 and seeing what was in memory there and what it referred to.  I think I remember bloodletter not being in there.  I'm sure that there's some network message that's delivering the proc, but I don't think it's exposed anywhere.

Finding out the memory addresses is mostly fumbling my way through using CheatEngine.  I keep meaning to write a guide for how to use that for finding memory signatures.  I'll reply here if I make some time and get to that.

Sorry that this is not a very satisfying answer!  I'd be curious to hear what you want your overlay to do, though!

**Comment by quisquous** [comment]
Here's a cheat engine guide: https://github.com/quisquous/cactbot/blob/master/docs/MemorySignatures.md

**Comment by Vassi** [comment]
Thanks so much for this! I just want my overlay to help muscle-memory train me a bit when I'm switching classes. I'm a serial alt-o-holic and if you want to see me sweat ask me what I consider my main to be.

Also, it's a cool excuse to flex some react and vue outside of work and I'm super thankful for the framework this represents, so much more interesting to work on than some todo app.

**Comment by quisquous** [comment]
The other thing is that if you use the cactbot test module (the one in ui/test) there's a debug output for jobs that will show you the 8 bytes for job info.  If you can decipher what this means for bards at 80, I'd be happy to add it.
