### ISSUE TITLE
Issue when using a 4k Monitor

### ISSUE THREAD

**Issue by Akurosia** [quisquous/cactbot#420]
When using a 4k monitor, severall elements are displayed very small.
Would there be a way to specify a file to overwrite the original css?

**Comment by quisquous** [comment]
If you wanted to make raidboss bigger, for example, you can create a user css file.  If you create the file **cactbot/user/raidboss.css**, then anything in that file will be included automatically into raidboss.  You can do the same for other modules by substituting a different name there.

In this case, you probably want css that is something like this:
```
body {
  transform: scale 2;
  transform-origin: 0 0;
}
```

**Comment by Akurosia** [comment]
ahh ok, thank you for this information and it worked like a charm

**Comment by waydownthehole** [comment]
This didn't seem to work for me, but editing the html file in the UI folder and changing the body tag to 
`<body style="zoom: 130%;">` seemed to work for me in either jobs or raidboss.
