### ISSUE TITLE
Cactbot FFXIV_ACT 2.0

### ISSUE THREAD

**Issue by Nekoi** [quisquous/cactbot#421]
Cactbot crashes ACT when using the new ShB patch alpha

**Comment by DarkhShadow** [comment]
To clarify this is the exact error with 2.0.1.2

> 04/06/2019 10:27:48 AM: Error: Raidboss: Exception in SendFastRateEvents: Could not load type 'FFXIV_ACT_Plugin.ACTWrapper' from assembly 'FFXIV_ACT_Plugin, Version=2.0.1.2, Culture=neutral, PublicKeyToken=null'.
04/06/2019 10:27:48 AM: Error: Raidboss: Stack:    at Cactbot.CactbotOverlay.SendFastRateEvents()
   at Cactbot.CactbotOverlay.<Initialize>b__76_0(Object o, ElapsedEventArgs args)
04/06/2019 10:27:48 AM: Error: Raidboss: Source: CactbotOverlay

**Comment by quisquous** [comment]
Thanks for this heads up.  I'll look into this so cactbot can keep working when the new version comes out.
