### ISSUE TITLE
Compatibility with ACT 2.0 Alpha

### ISSUE THREAD

**Issue by Nekoi** [quisquous/cactbot#423]
More bugs! I noticed things like Final Omega tether (close far) will rapidly flood sound or voice callouts. Short long stack, defamation, ect.
Also M/F apart/close. Not sure if it is Cactbot or triggers in general. But going down non-alpha ffxiv plugin fixed it.

**Comment by quisquous** [comment]
Thanks for the report! Do you have a Network log you could upload somewhere that I could take a look at?

**Comment by Nekoi** [comment]
Shoot, I should've thought of that. I did a full clean reinstall when I went to the lower plugin version. Just to make sure everything would work. I can set up a second install and get one the next time I do something.

**Comment by quisquous** [comment]
Your network logs are not inside of ACT usually.  They're in `C:\Users\USER\Documents\My Games\FINAL FANTASY XIV - A Realm Reborn\FFXIV_CHR0000etc\log` usually.

**Comment by Nekoi** [comment]
Oh you don't mean ACT log, my bad. Yeah.
[00000080.log](https://github.com/quisquous/cactbot/files/3294422/00000080.log)
I think this is what you mean?

**Comment by quisquous** [comment]
Yeah, that's it.  Do you have a Network_date.log file that includes the o12s run?

**Comment by Nekoi** [comment]
[000000d9.log](https://github.com/quisquous/cactbot/files/3294430/000000d9.log)
It is kinda hard, this has 12s I think. Nothing as Network_date.log.

**Comment by quisquous** [comment]
Ok, I think ravahn knows about this and this should be fixed now in later plugins.  It's not a cactbot problem.
