### ISSUE TITLE
p4s debuff/tethers are not calling out correctly?

### ISSUE THREAD

**Issue by Anzumatsuri** [quisquous/cactbot#4237]
I am not sure if there are different strats being used for the cactbot callouts but it does feel like the callouts are not being triggered correctly.

No matter which role bloodrake targets, it will always calls out DPS for debuff/tether aka everything.

I'm starting to think it was due to the script, but I am not 100% sure. I am suspecting that this line `const roleRaked = data.party.isDPS(matches.target) ? 'dps' : 'tank/healer';` will always return true since Bloodrake is treated as an AOE (even though only  dps or tank/healer role gets hit with it).

I don't really know much javascript. But after looking at some examples, using custom user triggers, I came up with this condition to check instead `if (data.me == matches.target && (data.role === 'tank' || data.role === 'healer'))`, but it doesn't work either since with this, it'll just calls out tank/healer for everything now.

Anyone else facing this issue?

**Comment by Akurosia** [comment]
what language do you play in? 
for me it worked in english and german

**Comment by quisquous** [comment]
Do you have a network log where it didn't work that you can attach here? (Do you have two people in the party with the same name?)

**Comment by Anzumatsuri** [comment]
I’m playing it in English, and I do not have anyone with the same name in the party. But I do have the last name shortened to the first character, will that affect anything? 

For the logs I do have them but it was from my custom user trigger, is that alright? I’ll attach it later since I am away right now.

**Comment by Anzumatsuri** [comment]
Here's the network log before the custom user trigger:
[Network_26404_20220323.log](https://github.com/quisquous/cactbot/files/8454462/Network_26404_20220323.log)

**Comment by quisquous** [comment]
Seems fine to me.  If I load your network log in https://quisquous.github.io/cactbot/ui/raidboss/raidemulator.html, then:

* [22:55:27] Hesperos (07m37s) -- Tank/Healer Tethers, DPS Role Calls
* [23:03:05] Hesperos (04m32s) -- Tank/Healer Tethers, Tank/Healer Everything
* [23:07:37] Hesperos (03m38s) -- DPS Tethers, DPS everything
* [23:11:15] Hesperos (06m09s) -- DPS Tethers, DPS everything
* [23:17:25] Hesperos (03m43s) -- Tank/Healer Tethers, DPS Role Calls

If you load your local version of raidemulator.html in a browser and do the same thing, does it give you something different than what the remote github.io version does? Do you see the same thing I'm seeing?

**Comment by valarnin** [comment]
> For the logs I do have them but it was from my custom user trigger

I think this means they're using a custom trigger, at which point we'd need to see that trigger to identify any issues?

**Comment by valarnin** [comment]
Custom triggers do not change the network log file.

Maybe your cactbot overlay is pointing to an out-of-date cactbot install? You could try either of the following:

- Remove the existing overlay, re-add it via the correct preset value in the dropdown
- Try your network log file in your local copy of raidemulator to see if it varies from the hosted version (copy the `URL` of the current cactbot overlay, change `raidboss.html` to `raidemulator.html?OVERLAY_WS=ws://127.0.0.1:10501/ws`, open in chrome or firefox)

**Comment by ntdavison1** [comment]
I was experiencing this issue last night running P4S. On the first Bloodrakes, it would call "DPS tethers" even when it should have been "tank/healer tethers".

**Comment by quisquous** [comment]
This seems related to a race condition in OverlayPlugin/ffxiv act plugin: https://discord.com/channels/551474815727304704/551476805148737546/985874131973181481

**Comment by quisquous** [comment]
I'm going to merge this issue with #5184
