### ISSUE TITLE
jobs: adjust buff tracker for mug/trick attack changes

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#4257]
```typescript
      trick: {
        cooldownAbility: [kAbility.TrickAttack],
        mobGainsEffect: EffectId.VulnerabilityUp,
        mobLosesEffect: EffectId.VulnerabilityUp,
```

The effect id is correct, but the ability is now mug (`0x8C8`).  On top of that, there needs to be some code changes to handle versioning, as the Chinese version is on 6.0 (and soon the Korean version too).  We have `is5x` but maybe we need to handle versioning better to handle 5.x, 6.0, and 6.1.

cc @Echoring

**Comment by Echoring** [comment]
I tried to change boolean"is5x" to string"ffxivregion", but failed to fix the type defination everywhere.
Seems this refactor is beyond my ability, and I would like to ask @MaikoTan to do this.
