### ISSUE TITLE
sound alert/text warnings not working

### ISSUE THREAD

**Issue by RuFFy71** [quisquous/cactbot#426]
Hey guys,

I'm using Cactbot for the timeline and raid alert.

Unfortunately, after a reinstall, it doesnt work properly.

I don't get any sound alerts and text warnings.

The timeline works, but not through the whole fight. For example in alphascale savage v3 it works the first phase, but disappears after the level checker phase.

Any solution? Big thanks!

[Network_20190619.txt.log](https://github.com/quisquous/cactbot/files/3307903/Network_20190619.txt.log)

**Comment by RuFFy71** [comment]
Think I fixed it by changing network parsing to WinPcap, although I would like to have network parsing on :/

**Comment by lakaf** [comment]
Just a guess, did the reinstall change the location of your ACT exe file? If so you may need to re-configure the firewall policy / white list .

**Comment by quisquous** [comment]
Yeah, the reinstall changing settings would be my guess as well.  You should make sure you have network parsing on, as many cactbot triggers depend on that.  If it's not working, then you need to run as administrator or fix firewall settings.
