### ISSUE TITLE
TEA Issues After 6.1 Patch

### ISSUE THREAD

**Issue by adeptstar** [quisquous/cactbot#4262]
Hello,

Few problems popped up after the 6.1 patch.

1. The thunder and water debuffs during BJCC strangely also display a limit cut number and says knockback cleave.
2. Players marked for enumeration during BJCC are no longer announced.
3. During the time stop transition to prime, the "no debuff" players no longer get a message saying they have no debuff.
4. The limit cut number during wormhole isn't announced
5. The cactbot wormhole strat as a result isn't displayed if you have it enabled.

Also, this is a maybe since we're still progging the fight but I don't think the clone debuffs during fate calibration alpha or the safe spot was announced.

Log file: https://www.fflogs.com/reports/kjYVWTrFPZQzMa62#fight=3

**Comment by adeptstar** [comment]
[Network_26500_20220412.zip](https://github.com/quisquous/cactbot/files/8477939/Network_26500_20220412.zip)

**Comment by quisquous** [comment]
I'll try to take a look at this eventually, but I'm probably only going to have a brief window of time between getting 6.1 stuff done and then being distracted by ultimate.  If anybody else has a chance to look at this in raidemulator or try to figure out what's going on, I'd appreciate it!

**Comment by adeptstar** [comment]
The update from today seemed to have fixed all the issues. Not sure why it was messed up yesterday. I verified with someone else that it was messed up yesterday as well but glad it's working now!
