### ISSUE TITLE
Cactbot Jobs is not displaying Astrologian card information correctly

### ISSUE THREAD

**Issue by Sunhealer** [quisquous/cactbot#4265]
## Description

Cactbot Jobs is not displaying Astrologian card information correctly, leaving the squares on the right side empty, even though I have both a regular card and a Minor Arcana drawn as seen in the screenshot.

## Additional information

![image](https://user-images.githubusercontent.com/76262256/163128879-ee01c02f-efe5-41a5-b950-cb14f4d43c3e.png)

**Comment by Echoring** [comment]
Seems AstrologianJobMemory structure has been changed in 6.1.
It should be fixed soon.

**Comment by Sunhealer** [comment]
I see. Thanks for the reply! I'll be patiently waiting then.
