### ISSUE TITLE
Delubrum Reginae Savage Trinity Seeker Sword calls and Trinity Avowed Hot/Cold Mechanic RaidBoss call broken with 6.1.

### ISSUE THREAD

**Issue by Volkaru** [quisquous/cactbot#4288]
Trinity Seeker Sword calls (West > East, NW > SW >NE > SE, etc.) not functioning in DRS since 6.1. Tried restarting ACT, didn't fix it.

Trinity Avowed not calling out Sword safe spots with solve, AND is giving wrong calls for temperatures (Saying to go to blank spot for first bow, for example.) broken in DRS. Possibly related to the last time this was broken, referenced in #3339 
Running Latest version. (0.25.2)
Here is the log from the run:
[SplitNetwork_26500_20220415-2022-04-16T04-15-37.807Z.zip](https://github.com/quisquous/cactbot/files/8499377/SplitNetwork_26500_20220415-2022-04-16T04-15-37.807Z.zip)

Only error in the plugin box over the run was "[4/15/2022 9:59:41 PM] Error: Update for EnmityEventSource took too long, skipping overlapping tick!" This happened outside of one of the aforementioned broken calls. 

EDIT: Confirming The Spoken/forgotten Words mechanic for Stygimoloch Lord is broken, as well. Raidboss no longer tells you if it's a get in or get out for your mechanic.

**Comment by quisquous** [comment]
This is unlikely to be related to #3339, as that was due to a TypeScript conversion (which only happened the once).

I am not sure what's going on here, and don't have a ton of time to look at this right now.  If anybody else wants to take a peek, please feel free to see if you can understand the issue.

**Comment by Volkaru** [comment]
Just let me know if you need any more data for whoever works on this. Network Packet log, etc.

**Comment by Volkaru** [comment]
After running the content again, I think, at least for Trinity Avowed, that it might be treating the fight as if I'm in Delubrum Reginae Normal, instead of Savage. First Meteor phase was giving me calls from normal mode. (Telling me to watch for clones, etc.)

**Comment by valarnin** [comment]
I've never been into DR or DRS, but looking at the `DelubrumSav Lord Fateful Words` and tracking that back, the `DelubrumSav Lord Labyrinthine Fate Collect` trigger is never matched. Checking that trigger against the log file, the `26` Gains Effect line isn't in the log file, but the corresponding `00` chat line is.

Unfortunately, given that I haven't (and can't, due to lack of willingness to grind the levels required) run this content, that's about the extent of my ability to help.

**Comment by Volkaru** [comment]
Here's another log from a run last night, had the same issues after reinstalling ACT and Cactbot. So I can rule out a file corruption issue. 
Related to what @valarnin said, could the same issue be happening during Trinity avowed when it's trying to get the Elemental Brand and Temperature effects?
[SplitNetwork_26500_20220418.2022.04.19-2022-04-19T03-48-47.965Z.zip](https://github.com/quisquous/cactbot/files/8516418/SplitNetwork_26500_20220418.2022.04.19-2022-04-19T03-48-47.965Z.zip)

**Comment by quisquous** [comment]
I replied in discord here, to hopefully get Ravahn's eyes on it: https://discord.com/channels/551474815727304704/551474815727304706/966093423989903430

I think this is likely an opcode issue in the ffxiv plugin.  All of the things you mention here are status effect related.  The swords are status effects, the brands on the avatars are status effects, the stygimoloch lord debuffs are status effects.  One thing you could do that would help would be to turn on network dumps (ACT -> Plugins -> FFXIV ACT Plugin -> (DEBUG) Enable Debug Options -> (DEBUG) Log all Network Packets) during one of the fights that is broken (e.g. Stygimoloch Lord).  It will make your network log huge so likely you just need one example fight to hand to Ravahn if they can't figure it out in the meantime.

**Comment by Volkaru** [comment]
I have network logs for seeker, to hopefully get the swords issue fixed. But the group I ran with didn't get to Avowed. Runs are sparse atm because people are prepping for DRU. Will upload network log of that this evening.

**Comment by quisquous** [comment]
Perfect, that should probably be enough.  Thank you!

**Comment by Volkaru** [comment]
Did another run today, here are the logs that include Avowed and Styg Lord. I didn't hit network debug enabled until right before avowed. So don't have network debug data for seeker unless I upload the old network logs, as well.
Run today including Avowed network logs and Styg Lord Network logs: https://www.mediafire.com/file/7gw5az7v9kwnkzl/Network_26500_20220424.log/file
Run yesterday including network logs for Seeker, but didn't get to avowed: https://www.mediafire.com/file/typcqzfkw833ooc/Network_26500_20220423.2022.04.24.log/file
(Each file is about 250MB)

**Comment by valarnin** [comment]
Given the client update incoming for ultimate, this might not even be relevant anymore, except as a general "make sure Ravahn updates the opcode properly for 6.11" check?

**Comment by Volkaru** [comment]
So should I just check to see if the 6.11 update fixes the issue?

**Comment by valarnin** [comment]
From https://github.com/ravahn/FFXIV_ACT_Plugin/releases/tag/2.6.5.1 :
> Delubrum Reginae (Savage) zone logs appear to be missing StatusEffectList2 information (line type 38). This is still being investigated

So probably it'd help to get another log with network debug/all packets setting enabled now that 6.11 is out, since the opcode shuffles with every client update.

**Comment by Volkaru** [comment]
We didn't get to Stygimoloch Lord on this run tonight. But had two wipes on TA (Mostly just fresh prog groups happening now, so hard to get full clear logs.) I hope this helps a bit. Sorry the file is so huge. Network logged two runs back-to-back. 
https://www.mediafire.com/file/c8fhk36ea7l6yt6/Network_26501_20220427.log/file

**Comment by valarnin** [comment]
I'm not familiar with the specific packet structure here, but this looks like the missing data?
```
252|2022-04-27T22:56:11.5480000-07:00|00000038|400005DA|108B9953|00000003|016F0014|012E0000|626A2C7B|00000000|E0000015|00000808|000000F7|E0000000|00000000|00000000||1060b2f03c6ff295
252|2022-04-27T22:57:28.6220000-07:00|00000038|400005D8|108B9953|00000003|016F0014|012E0000|626A2CC8|00000000|00000014|00000808|000000F7|00000000|00000000|00000000||9ea349652b39f3db
252|2022-04-27T22:57:31.7870000-07:00|00000038|400005D8|108B9953|00000003|016F0014|012E0000|626A2CCB|00000000|2FAD0014|00000808|000000FA|00000000|00000000|00007F03||8b457f48c5dd0c1f
252|2022-04-27T22:57:34.9930000-07:00|00000038|400005D8|108B9953|00000003|016F0014|012E0000|626A2CCE|00000000|00000014|00000808|000000F9|00000000|00000000|00000000||849995a7c2f1606f
252|2022-04-27T22:57:38.2030000-07:00|00000038|400005D8|108B9953|00000003|016F0014|012E0000|626A2CD2|00000000|00000014|00000808|000000F8|00000000|00000000|00000000||3dd6203a77430361
252|2022-04-27T22:57:41.4140000-07:00|00000038|400005D8|108B9953|00000003|016F0014|012E0000|626A2CD5|00000000|E0000015|00000808|000000F8|E0000000|00000000|00000000||b1dbcef464798f8f
```

Found via this ugly regex:
```js
/^252\|.*?0808(?:[0-9A-F][0-9A-F]\||[0-9A-F][0-9A-F][0-9A-F][0-9A-F]\||\|).*?F[789A](?:[0-9A-F][0-9A-F]\||[0-9A-F][0-9A-F][0-9A-F][0-9A-F]\||[0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F]\||\|)/
```

**Comment by quisquous** [comment]
Thanks! I pinged Ravahn about them here: https://discord.com/channels/551474815727304704/551474815727304706/969265055738765313

**Comment by ravahn** [comment]
0x16f opcode is ActorControl packet, which isn't the right one for StatusEffectList2.  But, I'll try to find the right one now.

**Comment by quisquous** [comment]
@Volkaru Here's a beta plugin to test: https://discord.com/channels/551474815727304704/551476805148737546/969563354291134475

**Comment by BLS1** [comment]
I tested the beta FFXIV plugin and it fixed the issues on Trinity Avowed. It was properly calling all mechanics and movements. Haven't tested Styg Lord though, because we wiped.

**Comment by quisquous** [comment]
Sounds like it's fixed to me.  Please comment if something else is awry.

It's likely that this will break after every patch.
