### ISSUE TITLE
high cpu usage from call out in Alzadaal using TTS

### ISSUE THREAD

**Issue by mayheart** [quisquous/cactbot#4292]
Articulated Bits special attack notification code is called multiple times when it should only be a one time call out.  I suspect the boss uses the skill multiple times as there's 6 additonal adds on the screen that the mechanic comes from. 

This causes a good 2-3 seconds of ACT using 100% cpu while using TTS calls outs. Enough to cause my game to completely stop. Getting this code to only run once instead of multiple loops should fix the problem.

**Comment by quisquous** [comment]
cc @JLGarber
