### ISSUE TITLE
Ready check not triggering General Ready Check

### ISSUE THREAD

**Issue by djc5166** [quisquous/cactbot#4304]
## Description

Within the last release or two, ready checks no longer trigger the built in trigger.

## Additional information

Probably from this commit, timeframe lines up.

https://github.com/quisquous/cactbot/commit/03af1ac061511e796d32e41819f819989713a1e5
https://github.com/quisquous/cactbot/issues/4294

**Comment by valarnin** [comment]
Hmm, seems like ready check can also be on code `0139`, looking at log files from today. I'm not sure what the differentiator is, I had two ready checks back to back from someone else in the party (same person both times) go to `0139` and `0239`. Running a quick grep shows:

```
$ grep -P '(?: has initiated|You have commenced) a ready check' /.../FFXIVLogs/*.log | cut -d'|' -f3 | sort | uniq -c
     23 0039
     68 0139
     46 0239
```

**Comment by djc5166** [comment]
> Hmm, seems like ready check can also be on code `0139`, looking at log files from today. I'm not sure what the differentiator is, I had two ready checks back to back from someone else in the party (same person both times) go to `0139` and `0239`. Running a quick grep shows:
> 
> ```
> $ grep -P '(?: has initiated|You have commenced) a ready check' /.../FFXIVLogs/*.log | cut -d'|' -f3 | sort | uniq -c
>      23 0039
>      68 0139
>      46 0239
> ```

Yea I just checked, all the ones that didn't trigger for me are 0139.

**Comment by quisquous** [comment]
My logs show the same,  I'm not sure what `0139` is, but I don't see any codes but those three.  Thanks for the investigation!
