### ISSUE TITLE
about npm

### ISSUE THREAD

**Issue by tssailzz8** [quisquous/cactbot#4323]
i use npm run build and meet some problems
 - Module build failed (from ../../c #/cactbot/node_modules/html-webpack-plugin/lib/loader.js):

  - Error: Cannot find module 'F:\c #\cactbot\node_modules\html-webpack-plugin\lib\loader.js'
i do not konw how to fix it

**Comment by quisquous** [comment]
Have you run `npm install`?

**Comment by tssailzz8** [comment]
yes,and i also run npm ci

**Comment by tssailzz8** [comment]
npm WARN deprecated @stylelint/postcss-markdown@0.36.2: Use the original unforked package instead: postcss-markdown
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 1356 packages in 2m

206 packages are looking for fundi

**Comment by tssailzz8** [comment]
PS F:\c#\cactbot> npm ci
npm WARN deprecated @stylelint/postcss-markdown@0.36.2: Use the original unforked package instead: postcss-markdown
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 1356 packages in 2m

206 packages are looking for funding
  run `npm fund` for details

**Comment by valarnin** [comment]
It's possible something in the stack doesn't like the special character `#` in the path?

**Comment by tssailzz8** [comment]
thanks
