### ISSUE TITLE
5.0 cactbot error

### ISSUE THREAD

**Issue by kagekitsune** [quisquous/cactbot#433]
getting this error and it will not load cactbot

6/30/2019 4:45:22 PM: Error: LoadAddons: C:\Program Files (x86)\Advanced Combat Tracker\addons\CactbotOverlay.dll: System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
 
dll file is unblocked, on windows 10
tried a clean install as well, app data deleted and still same issue.

**Comment by quisquous** [comment]
Take a look at https://github.com/quisquous/cactbot#potential-errors-and-workarounds

**Comment by quisquous** [comment]
It sounds like maybe you didn't unblock the overlayplugin?

**Comment by kagekitsune** [comment]
i did, it is unlocked. i zipped the file again which is another work around for unblocking if normal properties unblock apply doesnt work.

**Comment by kagekitsune** [comment]
found the issue, appdata wanst deleting a file while it was in use. its working now. thanks for the help
