### ISSUE TITLE
Raid boss not workin in raids/dungeons after patch 

### ISSUE THREAD

**Issue by Jpauly209** [quisquous/cactbot#4342]
After the most recent update my raidboss alert and timeline do not initiate in dungeons or raids what so ever. They work fine in Summerford farms. I already reinstalled and built everything the way I had it before.

**Comment by quisquous** [comment]
You need an updated ffxiv plugin.  This will happen after every patch.

**Comment by Jpauly209** [comment]
Awesome thank you 👌🏽
