### ISSUE TITLE
New npc_combatants values in make_timeline.py needed for Shadowbringers

### ISSUE THREAD

**Issue by lakaf** [quisquous/cactbot#436]
Hi,

I am trying to create the timeline for Titania Ex right now and noticed Shadowbringers had added several new npc_combatants which need to be excluded in make_timeline results.

Ones I have noticed so far:
"Esteem" from DRK
"Seraph" from SCH

Haven't played with MCH and SMN so far not sure whether they have new pets.

I could submit pull request if you are busy to do so :)

**Comment by quisquous** [comment]
Good catch, thanks!
