### ISSUE TITLE
Alerts and Timeline not showing 

### ISSUE THREAD

**Issue by duuuuumu** [quisquous/cactbot#4375]
## Question

What would you like to ask?

Im new on using Cactbot and ACT for a while. My Cactbot just like the title I said does not show up in anywhere, whenever i bow to dummy or countdown its still not working. but shirk and provoke work successfully. What can I do to fix it?

**Comment by quisquous** [comment]
I would recommend asking the ffxiv act discord.

Here's a few quick possibilities.  The likely answer here is that you something is wrong with your chat.  Do you have the system log messages show up in your chat log? if no, turn them on so you see the countdown/engage there.  Do you have the "hide chat log for privacy" clicked in your ffxiv settings? If so, turn that off.  Are you using dalamud plugins?  Try without quicklauncher.  If that works, then it's some chat-related plugin you need to disable.

**Comment by quisquous** [comment]
This is a pretty old bug with no response to any questions.  If this is still not working for you, I would recommend asking in the ffxiv act discord.  I hope that you have gotten this sorted.

**Comment by kaedys** [comment]
@quisquous was running into the same issue, and your pointer to a chat mod was on the money.  In my case, TidyChat, which filters, among other things, system message.  However, the odd part is that the _Alerts_ portion work even with TidyChat, while the timers do not.  I ended up fixing it by specifically whitelisting the `<Area> will be sealed off in 15 seconds!` message under `Custom Filters` in TidyChat.  So if anyone else has this issue and runs across (or is pointed at) this issue, if you have TidyChat or any other mod that filters chat messages, ensure that the area seal-off messages are whitelisted.
