### ISSUE TITLE
Not showing timeline container since ShB update

### ISSUE THREAD

**Issue by Zarbalan** [quisquous/cactbot#438]
Hi there,

i recently updated my cactbot from 0.9.5 to 0.10.0 and now the timeline container of the dbm part is gone? I can see it when i look into the devmode - but the testimages of them (like the test text in green, yellow and red) aren't there? Is that an issue only related to me, or is it connected to the new update and the need for new datasets/timelines etc.? 

Regards,

Daniel

**Comment by quisquous** [comment]
I'm not sure what you're running that you are expecting timelines for.  I haven't made any for ShB yet, but am hoping to get that done this weekend.

**Comment by Tsunatus** [comment]
I am having a similar issue but it is the fact that the timelines in general aren't working.

**Comment by Kumicoo** [comment]
rip timelines for this weekend.

**Comment by quisquous** [comment]
Does the new 0.10.1 update have the timelines you are looking for?

@Tsunatus What do you mean by timelines in general aren't working? Are you able to do the summerford farms test listed in the documentation?

**Comment by quisquous** [comment]
Hi, is this still happening for both of you?

**Comment by Tsunatus** [comment]
The timelines work on the extreme trials, but they do not work on the
summerford dolls.Due to the frequent updates to the FFXIV plugin, Hojoring
and your Cactbot the only way to test them is to go right into a extreme
trial and make adjustments on the fly while doing the fight which is kind
of silly seeing as we have the summerford farms to do such a thing

The Blood Soaked Empress

**Comment by quisquous** [comment]
@Tsunatus What are you doing to try to start the summerford farms test? Both /bow and /countdown should work, but sometimes /bow doesn't because emote text is turned off.

**Comment by Tsunatus** [comment]
I use /bow, but I never made any changes to my chat logs and it was working
until shadowbringers came out and it hasn't worked since then
The Blood Soaked Empress

**Comment by quisquous** [comment]
Does /countdown work?

**Comment by Tsunatus** [comment]
/countdown has never really worked for me ever since i started using
Cactbot. It appears randomly but I'm pretty sure if there was an option i
probably turned it off

The Blood Soaked Empress

**Comment by quisquous** [comment]
Is this still not working for you?

If you teleport to Summerford Farms and do `/echo Engage!`, does that start the timeline?

**Comment by quisquous** [comment]
If this is still happening, please leave a comment.  Otherwise, I'm going to close this for now.
