### ISSUE TITLE
[DSR] Spiral Thurst - Wrong Callouts

### ISSUE THREAD

**Issue by InitialDet** [quisquous/cactbot#4389]
It seems inconsistent, but sometimes when the safe spots are NE and SW, the callouts given are East and West (not safe lol). Most callouts were right but this pattern of wrong callouts happened more than once.

I'm not sure if it happens in other patterns.

**Comment by quisquous** [comment]
Hmmm, I haven't seen this for any pattern, the spiral thrust callouts have been correct.  Do you have a network log where this happened?

**Comment by InitialDet** [comment]
[Network_26501_20220504.zip](https://github.com/quisquous/cactbot/files/8628900/Network_26501_20220504.zip)

The first one I remember happened at 21:45pm (my time), the second time at 22:49pm

**Comment by InitialDet** [comment]
This might be one of the times

`20|2022-05-04T21:45:22.8940000-03:00|40029F0A|Ser Ignasse|63D4|Spiral Thrust|40029F0A|Ser Ignasse|5.70|100.00|123.00|0.00|-3.14|1c7a7536b59e9466`

`20|2022-05-04T21:45:22.8950000-03:00|40029F0D|Ser Paulecrain|63D4|Spiral Thrust|40029F0D|Ser Paulecrain|5.70|77.00|100.00|0.00|1.57|d0f50ff8da614941`

`20|2022-05-04T21:45:22.8950000-03:00|40029F0E|Ser Vellguine|63D4|Spiral Thrust|40029F0E|Ser Vellguine|5.70|116.26|116.26|0.00|-2.36|b49e4c4bafa0e9a6`

**Comment by levian05** [comment]
Had the same issue. Safe spots were N/S, but the callouts given were E/W(not safe)

**Comment by valarnin** [comment]
InitialDet, your three line example shows the knights at south (X:100,Y:123), west (X:77,Y:100), and southeast(X:116.26,Y:116.26) respectively, making the safe spots northeast and southwest.

This is reflected when loading that encounter in raidemulator:

![image](https://user-images.githubusercontent.com/6119598/166932269-e692add7-89b0-4182-81ba-062b4fc3a495.png)

Two players got hit during that pull, standing at (X:106.38,Y:88.70) and (X:110.24,Y:86.43). They were hit by Ser Ignasse, who started south and moved north.

I checked the pull immediately after that one, and it has the knights at south, southwest, and west, making the safe spots northwest and southeast,

---

levian05, you have two different pulls in your example lines, as follows:
1. Knights at NW, NE, W, making safe spots N/S
2. Knights at S, SE, NE, making safe spots E/W

Your second example has a player getting hit while standing northwest-ish (X:84.12,Y:90.66) by Ser Ignasse and Ser Paulecrain, who started south and southeast respectively.

**Comment by levian05** [comment]
Oops, my bad for the 1st pull (Didn't notice we wiped it early)
However for the 2nd pull, you can see the 3 knights at NE, E, SE. 
(The player being hit ended up being me lol)
https://cdn.discordapp.com/attachments/496100259500654614/971810369058275359/cccccc.jpg

**Comment by Legends0** [comment]
@valarnin @quisquous 
Could it be for some cases getCombatants is not getting the correct position data? I have not seen it wrong in 100s of pulls after coming to the current delaySeconds value, but potentially getCombatants delay required could be different for different players due to latency?

**Comment by Thorgak** [comment]
> @valarnin @quisquous Could it be for some cases getCombatants is not getting the correct position data? I have not seen it wrong in 100s of pulls after coming to the current delaySeconds value, but potentially getCombatants delay required could be different for different players due to latency?

Been experiencing this bug also, another player in my group has the callout enabled and it works fine for them though, I'm playing in NA from the UK and he's in the US, figured it'd be worth noting this as your comment about latency might explain why it works differently for two people in the same raid if that's how it works. 

Seems to be pretty inconsistent which safespots are wrong and when it breaks as well.

**Comment by valarnin** [comment]
I think it's reasonable to account for up to 250ms of latency. I didn't do the timing for this myself so I can't say what the bare minimum is for 0 latency to account for the actual client latency.

**Comment by InitialDet** [comment]
Well, I play with around 200ms, that probably could be it then?

**Comment by quisquous** [comment]
I think this should be fixed now.

**Comment by levian05** [comment]
Haven't had any issues anymore since the update, ty

**Comment by Thorgak** [comment]
> Haven't had any issues anymore since the update, ty

Me either, seems to work fine - though I am having incorrect calls on thordans location during strength, not really a problem as he's easy to find but could be a similar issue to the spiral thrusts?

**Comment by Legends0** [comment]
> > Haven't had any issues anymore since the update, ty
> 
> Me either, seems to work fine - though I am having incorrect calls on thordans location during strength, not really a problem as he's easy to find but could be a similar issue to the spiral thrusts?

Yea, that's going to have the same cause since they both use OverlayHandler. For Thordan's case, aside from just increasing the delay, there may be work such that we can get data from another NPC, maybe even without OverlayHandler, and perhaps just add delay to it so that its timings do not interrupt other TTS.  #4400 for instance (and as has been pointed out in a previous closed PR) there are other methods to determining Thordan's location earlier, just not as straight forward as querying Thordan. I just know that one method involving that same NPC in #4400 with OverlayHandler was getting the data later than when Thordan appears when I tested it out after having wrote the current trigger.
