### ISSUE TITLE
Invalid Plugin

### ISSUE THREAD

**Issue by gtetrakai** [quisquous/cactbot#439]
When I try to enable the plugin, I get the following error:  
  
"This assembly does not have a class that implements ACT's plugin interface."

**Comment by kerriamber** [comment]
You aren't supposed to add cactbot as an ACT plugin. You need to download the [overlay plugin ](https://github.com/hibiyasleep/OverlayPlugin/releases/tag/0.3.4.0) and enable that in ACT. Then follow [the installation instructions](https://github.com/quisquous/cactbot#installing-cactbot)

**Comment by quisquous** [comment]
Yes, kerriamber's response is exactly it.  Let me know if you're still having problems.
