### ISSUE TITLE
Raidboss 

### ISSUE THREAD

**Issue by Shbounab** [quisquous/cactbot#441]
hi,
it seams after the update Raidboss is not functioning at all. idk if it a know issue. everything else is working fine for me Parser and Opsy and Eureka but some reason raidboss never get triggered nothing register.

**Comment by quisquous** [comment]
Yeah, there are breaking log changes in the latest update and also bugs in the added combatant line.  I have local changes that half fix it, and I would recommend using a previous version until 2.0.2.4 comes out.

**Comment by Shbounab** [comment]
also just to mention some reason when i used DRK i have no issue when i switch to GNB it stop working. idk if that is related as well

**Comment by quisquous** [comment]
I think this is a duplicate of #453.  If this is still broken after the next release, please reopen this.
