### ISSUE TITLE
[DSR] Titan Gaols-esque extended text popup for DSR Skyward Leaps and Dragon's Rage stack (Strength of the Ward)

### ISSUE THREAD

**Issue by SamosaWave** [quisquous/cactbot#4410]
Reference
https://github.com/quisquous/cactbot/blob/main/ui/raidboss/data/04-sb/ultimate/ultima_weapon_ultimate.ts#L296

## Summary

Have Cactbot print out sorted names for Skyward Leap and Dragon's Rage stack simalar to Titan Gaols.
Ex. Player 4, Player 1, Player 8. It's a pseudo Titan Gaol-esque text. 

If all 8 players have cactbot they can agree on a priority of where Skyward Leaps go West/South/East relative to Thordan and which persons in the stack go to which tower Left/Middle/Right. 

If all players don't have cactbot, proceed as normal but the extra information of who got which mechanic is helpful.

**Comment by quisquous** [comment]
I think printing this out for everybody is a little bit much, but probably the skyward leap and the stack group could have a list of who was in their group with them, e.g. "Stack (Player1, Player2, Player3)" or "Skyward Leap (Player1, Player2, Player3)" (or possibly put those names in a silent info text underneath?).  But, printing out 6 names would be a lot of names.

**Comment by SamosaWave** [comment]
Yes thats how I had it in my mind but didn't express it in words, sorry. 

> I think printing this out for everybody is a little bit much, but probably the skyward leap and the stack group could have a list of who was in their group with them, e.g. "Stack (Player1, Player2, Player3)" or "Skyward Leap (Player1, Player2, Player3)" (or possibly put those names in a silent info text underneath?). But, printing out 6 names would be a lot of names.

**Comment by quisquous** [comment]
No need for apology, I was just trying to think through how to best convey this information.  It's a good suggestion, thanks!

**Comment by quisquous** [comment]
Sorry for the belated response here.  I am not likely to be back in DSR any time soon and I don't think I am going to get around to this.  I'm going to close this (but would take a PR if anybody else wanted to implement this).
