### ISSUE TITLE
Checking Cactbot update in ACT fail

### ISSUE THREAD

**Issue by HPDeskJet2540** [quisquous/cactbot#4418]
When checking cactbot update in ACT, it shows this error message, have tried clean install and ACT again but it still persists.
![Capture](https://user-images.githubusercontent.com/91416994/167280777-7bad9a66-38d7-4310-9ca1-83d9b76f6818.PNG)

**Comment by quisquous** [comment]
This functionality (despite saying cactbot) is part of OverlayPlugin.  Can you file a bug on https://github.com/ngld/OverlayPlugin/ instead?

**Comment by HQ1995** [comment]
I got the same update error too.

**Comment by valarnin** [comment]
I went ahead and opened the issue on the OP github
https://github.com/ngld/OverlayPlugin/issues/263

**Comment by Andrewzz** [comment]
For people still having this issue, you may be using an outdated version of the Overlay Plugin. The Github address of the Overlay plugin was recently changed from [ngld/OverlayPlugin](https://github.com/ngld/OverlayPlugin) to [OverlayPlugin/OverlayPlugin.](https://github.com/OverlayPlugin/OverlayPlugin), and ACT is not updating it automatically. You will need to deinstall the old plugin from ACT and install it again.

**Comment by quisquous** [comment]
This should be fixed with the new OverlayPlugin.
