### ISSUE TITLE
Incorrect Chinese P2S Trigger Text

### ISSUE THREAD

**Issue by ShenHF1997** [quisquous/cactbot#4423]
https://github.com/quisquous/cactbot/blob/a441ac5355a7e02baa51ae6afa710784469f47c7/ui/raidboss/data/06-ew/raid/p2s.ts#L373
Better to change ”去Boss后面“ to “去Boss平台”
At this stage, the boss faces the outside of the field.Behind the boss is the center of the field and diagonal corners.

**Comment by MaikoTan** [comment]
Let me explain: All other languages says "to boss tile", while ja says "get under boss" and cn says "go behind boss", so they are kind of inconsistent.

cc @ShadyWhite @nekomimi-mode

**Comment by ShadyWhite** [comment]
“去Boss脚下” Would be better.

**Comment by quisquous** [comment]
Can this be closed now after #4546?

**Comment by MaikoTan** [comment]
> Can this be closed now after #4546?

After discussing with @ShadyWhite , we think it is ok to close this.
