### ISSUE TITLE
Minor jobDetail things

### ISSUE THREAD

**Issue by gaogaostegosaurus** [quisquous/cactbot#443]
Hey,

I noticed that the variable that stores lilies is no longer targeting the right location. I'm not really sure how this is achieved, but I can tell you that it's the fifth position in the debug output you have already. It appears that the third and fourth pairs of digits track how much time has elapsed since the last lily (or combat has begun); the third pair moves faster so I assume that means its looking at a smaller place value. Hopefully that helps?

![2019-07-06 (7)](https://user-images.githubusercontent.com/4298394/60760728-72570980-a008-11e9-923e-ec989ef304d3.png)

Also, this is more of an aesthetic thing than anything else, but the sen resource for SAM is not gekko but getsu. =p

**Comment by quisquous** [comment]
thx :D
