### ISSUE TITLE
Ascalons Mercy trigger

### ISSUE THREAD

**Issue by Dainichi22** [quisquous/cactbot#4439]
Be able to modify the duration before it tells you to move, rightnow it calls the move quite late and I find myself getting hit when the trigger says move, and an initial call when he starts casting it.

**Comment by valarnin** [comment]
I have #4408 open to address this but won't be able to make the requested adjustment until tonight.

There's no way to adjust the timing of this callout through the UI, but you can do so via user triggers instead, see the customization documentation in general, and this section specifically:
https://github.com/quisquous/cactbot/blob/main/docs/CactbotCustomization.md#overriding-raidboss-triggers

**Comment by quisquous** [comment]
Fixed by #4408.

**Comment by valarnin** [comment]
I didn't mark 4408 as fixing this since it seemed more like a feature request in general for the config UI?

**Comment by quisquous** [comment]
I think this would be a hard feature to add in general.  Folks have asked for "can I get more warning on aoes" before which is the same sort of question.  Sure, this specific trigger can be slightly adjusted, but it's hard to generalize.  My personal feeling is that this is a "make a user trigger if you want such fine control" but happy to talk more if you feel differently?
