### ISSUE TITLE
Error with cactbot update 07 July 19

### ISSUE THREAD

**Issue by Regenbogenschwan** [quisquous/cactbot#444]
Hello, 

since i updated cactbot today it will permanantly get this error:

https://i.ibb.co/6gW8jRQ/vrgdv-brt.png

can someone help to fix this?

**Comment by Akurosia** [comment]
Did you updated the FFXIV plugin to the latest version (2.0.2.5) ?

**Comment by quisquous** [comment]
Is this still happening?

**Comment by quisquous** [comment]
I'm going to close this due to lack of response.  Let me know if it's still happening.
