### ISSUE TITLE
radar: KR Endwalker hunts are not working

### ISSUE THREAD

**Issue by ffxivvillein** [quisquous/cactbot#4445]
## Description

In Korean Server, radar doesn't work about Endwalker hunts.

**Comment by MaikoTan** [comment]
Yes, KR server gets updated just few days ago. And there are many things should be updated to match the new version. Please be patient to wait for developers working on it.

**Comment by pyeonch** [comment]
6.0에 플러그인 개편 건도 있었고 당시 cactbot도 개발 및 수정했던 부분이 많이 있어 아직 완벽히 대응이 안 될 수 있습니다. 개발자분들께서 작업중이니 기다려주세요.
