### ISSUE TITLE
Call outs not working Baldesion Arsenal

### ISSUE THREAD

**Issue by IssuedVirtue** [quisquous/cactbot#4446]
There was another thread but it seems the person didnt come back to it. So anyways same issue, it works fine on the first boss and stops working on the rest. Tried tweaking settings and its still not working.

**Comment by IssuedVirtue** [comment]
> If you go to Summerford Farms and do a /countdown, does the test timeline start?

Yeah it does work.
I got frustrated from trying to troubleshoot from the current install of ACT + cactbot that I clean reinstalled both. It fixed the issue. The only issue I'm suffering now that that one where you can't update cactbot from ACT. 
Someone made a ticket about it already and made another one at the overlay's side.
![image](https://user-images.githubusercontent.com/105439538/168414727-113ab253-eed7-427f-8e1a-0ff8e8b1e0c4.png)

**Comment by quisquous** [comment]
cactbot will update automatically, regardless of the button.  Glad to hear it's working now.
