### ISSUE TITLE
Triggers on AoE attacks

### ISSUE THREAD

**Issue by amki** [quisquous/cactbot#445]
This is not really a technical issue but more of a taste one I guess but could we get the AoE notifications (like titania) at least for healers (especially scholar)?

It's kinda annoying to stare at the bar to preshield the party if already using triggers.

If not I can ofc keep them in my user/ triggers but I think other healers might think like me on this.

**Comment by quisquous** [comment]
Yes, I definitely can do this.  I don't really play healers very often.  I think mostly my previous thought was that the 3 second cast time warning was just not enough to do anything about aoes, other than just heal up afterwards.  (Whereas as a tank, if you weren't prepared for a buster, you could at least mash some ogcds.)

Would you want timeline-based warnings? Like 5 seconds ahead? Also, what would you want it to say? Just "aoe"? Or "big aoe"? Or something different? Please tell me what would be most helpful, and I'd happily start adding those in.

**Comment by amki** [comment]
My thought behind them is for one precasting the aoe healing (takes 2.4s so 3s is a little close but doable) and especially using anything (ogcds) to push the hp of low hp party members (e.g. after failing something) before the aoe hits and kills them.

I had good results with trigger on spell cast start but haven't tried timline based.

**Comment by quisquous** [comment]
Yeah, timeline based vs spell cast start has some downsides.  If there's a phase push, it might warn for something that's not coming.  If ACT crashes and you restart, your timeline won't be right.  Timelines are pretty darn reliable in general though, so most of the time it'd give you more warning.  Five seconds would be enough to finish a cast and then hit a gcd if you wanted to pre-shield.

Ahahaha `Heal Like Whoa`.  I must have been a little punchy when I added that one.

Ok, thanks for the feedback.  I'll be sure to add these in!
