### ISSUE TITLE
Alerts and Timelines are not working anymore on last build

### ISSUE THREAD

**Issue by mooondark** [quisquous/cactbot#4475]
With Fr language timeline and alerts are no more working since 0.26.7. I've rolled back on 0.26.6 and it's working again.

**Comment by quisquous** [comment]
I don't have any issues with the parser language set to French and trying out things in Summerford Farms.  Can you be more specific about what's not working? @Akurosia are you having any issues in German?

**Comment by mooondark** [comment]
I'm on P4S right now, I've no calls and no timelines with 0.26.7.
Triggernometry is working fine & mopimopi too.

I'll go to Summerford after the raid

**Comment by mooondark** [comment]
Fixed in 0.26.8
