### ISSUE TITLE
No Timeline/cast bar

### ISSUE THREAD

**Issue by memyselfandi987** [quisquous/cactbot#448]
I just updated Cactbot to 0.10.1, and while re-setting up overlay layouts, I can't see the cast bar in the raidboss UI. The warnings show up fine, but there's absolutely no timeline along the left side. I don't know if I accidentally broke something, but I didn't change any settings...it's pretty much a fresh install of Cactbot. This is how it shows up for me
![cactbot issue](https://user-images.githubusercontent.com/12144735/60829736-3c866200-a17b-11e9-977e-81ec9ce2f9cf.PNG)

**Comment by Bluefissure** [comment]
Is there any log output from Overlayplugin plugin?
![](https://i.loli.net/2019/07/09/5d243f4f02e4343120.jpg)

**Comment by quisquous** [comment]
That is just the debug text for raidboss to help you position it properly.  You need to lock your overlay in order to see timelines and triggers.

Once you lock it, it will disappear.  To test if it's working, go to summerford farms, and do a countdown and see if that works.

**Comment by memyselfandi987** [comment]
I got it, I reinstalled Cactbot again and the timelines showed up in the test this time. I don't know what the original issue was, but it's fixed
