### ISSUE TITLE
Issue upgrading to 10.01 (newest version)

### ISSUE THREAD

**Issue by Jiromeru** [quisquous/cactbot#449]
I am unable to remove the addons folder from the base directory where it comes from in the bundled zip file. For whatever reason it keeps saying I have no authorization and installing new versions have always been a simple cut and paste, but now I can't seem to update it.

**Comment by quisquous** [comment]
Do you have ACT open while you're trying to do this?

You don't need to remove the addons folder, you should just be able to paste on top of it and replace the files when it asks you.

**Comment by Jiromeru** [comment]
Nope, ACT is assuredly not running while messing with Program Files.
While I mentioned the Addons folder, there is but a singular file within, Cactbotoverlay.dll. As I had mentioned before when upgrading previously all it ever had been was a simple cut and paste into the proper area. The rewriting of files takes care of the rest, but even trying to remove the file and place it in that appropriate folder in Program Files, nets me this error. I have never had any issues before quite like this.
Also, yes I am the Administrator, and I have tried opening the file, the file folder and other options to 'Everyone' to have access to said file but it still refuses. It is literally the only file with this current release that I have the issue with. 

Sent from Yahoo Mail on Android 
 
  On Tue, Jul 9, 2019 at 12:59 PM, Adrienne Walker<notifications@github.com> wrote:   
Do you have ACT open while you're trying to do this?

You don't need to remove the addons folder, you should just be able to paste on top of it and replace the files when it asks you.

**Comment by quisquous** [comment]
Is this still happening for you? This sort of thing usually only happens when the file is open and in use.  If ACT looks like it's closed, maybe there's still some zombie ACT running in the background and you might try resetting your computer and then doing it.

**Comment by quisquous** [comment]
If this is still happening, please let me know.
