### ISSUE TITLE
Dps parse is now a blank blue square

### ISSUE THREAD

**Issue by skyelord2015** [quisquous/cactbot#450]
since updating to 0.10.1 by overwriting the Overlay plug my dps parse (from OverlayPlugin/cactbot/ui/dps/rdmty/dps.html) is just a blank blue square. 

The connection to the game is fine because I see data in ACT and if i enable the mini parse (OverlayPlugin/resources/miniparse.html) then i do see the fight data.

No errors in the log, last entries are
 09/07/2019 10:22:10: Info: LoadAddons: Cactbot.OverlayAddonMain: Initialized
09/07/2019 10:22:11: Info: InitPlugin: Initialized.

Any ideas please?

**Comment by quisquous** [comment]
If it's a blank blue square, then you probably need to lock your overlay.

The other thing that is often missed is that you need to set the "dps update rate" in the overlay config from 0 to something like 3.

Does that fix it?

**Comment by skyelord2015** [comment]
yep it was set at 0 somehow. that did the trick. thanks

**Comment by quisquous** [comment]
Glad you got it sorted.  Sorry for the confusion!  The default is zero so non-dps overlays don't waste time computing dps.
