### ISSUE TITLE
Raidboss addon and timeline only work once

### ISSUE THREAD

**Issue by Oblivionqt** [quisquous/cactbot#451]
When doing the innocence ex trial, the timeline and triggers only work on the first pull. After that they do not start up again after a wipe unless i restart ACT

**Comment by quisquous** [comment]
Hmm! Do you have a Network_date.log file to post here so that I can look?  Does this happen on any other fight?

(Has anybody else seen this?)

**Comment by Oblivionqt** [comment]
how would i get that for you?

**Comment by Oblivionqt** [comment]
so it appears, i use in game macro to end combat and clear the log, clicking that now causes it to stop working. if i never manually end combat or clear raidboss keeps working, this is new as ive always used these actions

**Comment by quisquous** [comment]
Hmm, this is quite strange.  Are there any errors in the plugin log?

Your network log can be found similar to this: https://github.com/quisquous/cactbot/blob/master/docs/LogGuide.md#importing-an-old-fight

**Comment by quisquous** [comment]
Is this still happening?

**Comment by quisquous** [comment]
If this is still happening, please let me know.
