### ISSUE TITLE
cactbot stopped working today

### ISSUE THREAD

**Issue by Benny89PL** [quisquous/cactbot#4517]
I started to use cacbot yesterday, I was doing Endsinger Extreme, no issues, all sound + commands where on point and great experience.

Today I went back to home, launched FF XIV, launched ACT, changed nothing - it doesn't work anymore. On Endsinger Extreme it would only show upcoming attack timers, but not anymore sound or written commands on screen like "Spread/Stack/Northwest etc.". On some bosses like on P4N it doesn't show anything at all. 

At summer farm /countdown 5 - everything works during testing.

I tried to update but there is not update it seems available. I haven't touched anything in settings since yesterday so I have no idea why it stopped working all of the sudden.

**Comment by quisquous** [comment]
Every time there is a new patch to download, the ffxiv plugin needs to be updated and this breaks all other plugins until it is fixed.  When you install the new version when it is out it should continue working again.
