### ISSUE TITLE
Cactbot UI doesnt show up after 24th May patch everything else works

### ISSUE THREAD

**Issue by Adronyth** [quisquous/cactbot#4518]
Cactbot doesnt show up anymore after patch from tuesday act doesnt show any errors i already reinstalled everything except ff14 itself.
/countdown 5 doesnt bring up the ui either everything else works parsing or triggernometrie for example.

Test Ui blue box with red frame also shows up until i lock the overlay like described in the guide. 
On monday before maintenance and patch everything worked.

**Comment by quisquous** [comment]
Have you updated to the latest ffxiv plugin that released today?

**Comment by Adronyth** [comment]
Yes it was automaticaly updated through act

**Comment by quisquous** [comment]
Probably your best bet is to ask on the ffxiv act discord and get some more direct tech support.  There hasn't been a cactbot update so nothing has changed here.

**Comment by Adronyth** [comment]
Its the only Module thats doesnt Work anymore as i said parsing and triggernometrie wirks Just fine the Test ui ist showing Up i can Lock it but it dies nothing while every Others Module works as intended

**Comment by Adronyth** [comment]
Found a solution installed alerts and timeline seperately not combined now it works maybe inmaxe the test window top small ?

**Comment by quisquous** [comment]
Glad you got it sorted!
