### ISSUE TITLE
Timers does not count down IN game, tabbed out they work

### ISSUE THREAD

**Issue by Krisos35** [quisquous/cactbot#452]
As the title say, I can start the test in La Noscea or while raiding Extreme Titania and the same problem occur. It shows up almost like pictures rather than counting down smoothly in game almost as if it's horribly lagging, but when I'm tabbed out of the game it works as usual.

Problem occurred after I had problems updating and thus just did a clean re-download, using the download from advancedcombattracker, trying both OverlayPlugin-0.3.4.0-x86-full and OverlayPlugin-0.3.4.0-x64-full, with cactbot-0.10.1 on both attempts.

I also tried once using cactbot-0.10.0. using the La Noscea test, and the same problem occured.

**Comment by Krisos35** [comment]
Edit: Problem solved. Either it was updating FFXIV_ACT_Plugin.dll and restarting the pc, or it was just restarting the pc that did it. Now it works anyway.

**Comment by Krisos35** [comment]
Problem returned even after restarting PC and updating FFXIV_ACT_Plugin.dll the next day.

**Comment by Krisos35** [comment]
I put the Frame Rate Limit in game to 144fps instead of None and now it works, though don't know if it's a permanent fix or if the problem will occur again

**Comment by gaogaostegosaurus** [comment]
I have similar problems with the overlay and FFXIV trying to hog the GPU - setting a frame limit like you did and turning off power management on GPU (like AMD Chill) seems to help. Not sure why it happens but it fixed it for me.

**Comment by quisquous** [comment]
Yeah, @gaogaostegosaurus left some good comments in #309 that might be helpful.

**Comment by quisquous** [comment]
Sounds like you have a workaround for this issue, so I'm going to close this for now.
