### ISSUE TITLE
GNB and return data.role == 'tank' not working

### ISSUE THREAD

**Issue by Amenne-ennemA** [quisquous/cactbot#453]
hello, i was running inno EX and the tank specific triggers do not seem to be triggering when i was on GNB. log is attached
[Network_20190709.log](https://github.com/quisquous/cactbot/files/3375968/Network_20190709.log)

**Comment by Amenne-ennemA** [comment]
upon further testing, using the test.HTML, i'm reported as being on job 60 GNB when on Dancer and job 80 DNC when on GNB

**Comment by KhloeAliapoh** [comment]
From what i noticed in [FFXIVProcess.cs line 121 and 122](https://github.com/quisquous/cactbot/blob/master/CactbotOverlay/FFXIVProcess.cs) the job IDs for Dnc and Gnb are swapped, Gnb should be 37 and Dnc should be 38, not the other way around.

**Comment by quisquous** [comment]
WHOOPS.  Thanks for this catch.  I swear I looked at the tables from Saint Coinach to write this, but I should have tested this properly.  Sorry!

There's not really a way for me to fix this until I get back this next weekend, but I'll put out a new release then.
