### ISSUE TITLE
raidboss: Korea server EW hunts triggers don't work after v0.26.9

### ISSUE THREAD

**Issue by Bing-su** [quisquous/cactbot#4536]
## Description

EW hunts triggers doesn't work after v0.26.9.

Could it be related to #4471 ?

## Additional information

ffxiv_act_plugin: 2.4.0.0 (kr)
overlay_plugin: 0.18.2.0
cactbot: 0.26.9

**Comment by quisquous** [comment]
Oh, none of these have a `timelineReplace` section and so they don't get auto-translated.  I guess my script to check didn't think this was even a possibility.

@Akurosia is it possible for your scripts to add this in automatically for the hunt triggers?
