### ISSUE TITLE
Tick Tracking

### ISSUE THREAD

**Issue by Diorik** [quisquous/cactbot#454]
Is there anyway to get a TickTracking (and possible AutoAttack tracking at the same time?) module given the increasing number of classes that have to try to land tick perfect abilities, often without interrupting their AAs?

**Comment by quisquous** [comment]
At the moment, there's not.  I think this is something that exists in hojoring if you want it, and so I'm not planning to include this in cactbot at the moment.

**Comment by quisquous** [comment]
Tick tracking got added for blm in issue #564, so it seems like it'd be pretty straightforward to add for monk.  It'd just need to track HoT ticks on you.

**Comment by quisquous** [comment]
It sounds like given the 5.1 changes this won't be needed for monks or samurai any more.

**Comment by Diorik** [comment]
It's dead for Samurai, but Monks are still arguing over it's necessity for Anatman because it may still be better to use it even after the change, making the timer even **more** important. 

However it's also likely to be so niche that it's not exactly offensive to just leave it as a use case for Triggernometry.
