### ISSUE TITLE
raidemulator: Adjust encounter duration display to consider offset in the encounter listing

### ISSUE THREAD

**Issue by Makar8000** [quisquous/cactbot#4548]
## Summary
![raidemulator encounter listing](https://i.imgur.com/EMQylVp.png)
For encounters that have a very large offset (minutes), it becomes difficult to find the encounters I am looking for at first glance. One of the reasons I use raidemulator is for data collection/analysis of certain mechanics with user triggers, so it is important for me to find pulls that reached a certain point (phase). Loading long encounters seems to take at least a few seconds in DSR, so I want to minimize how many unnecessary checks I do to get the actual duration of the pull. Because the "duration" field in the UI doesn't consider offset, it is basically impossible to see the length of a pull without at least clicking on the encounter row and doing some mental math to manually subtract the offset. Alternatively, I could just upload the log to fflogs to see the start time of all the relevant pulls, but this is more hoops than I feel should be necessary.

I didn't include it in my image above, but if the current behavior is important, then another idea would be to add another field/line for Pull Duration. I am not familiar enough with how others use raidemulator to understand the need to know the duration that is currently displayed instead of subtracting offset first.

**Comment by quisquous** [comment]
I definitely agree.  I have not found the time before the pull to be useful (either in this ui or in the triggers display).

**Comment by valarnin** [comment]
The biggest issue with excluding the time before pull entirely is that those log lines are still important for combatant state tracking and such. Updating the displayed values in the encounter panes at the bottom is not difficult. Adjusting the actual playback portion is... complicated.

**Comment by quisquous** [comment]
Yeah mostly my thought is that even if those lines exist silently and are still attached to the encounter, I think the UI would be easier to use if everything (encounter pane, the timeline of triggers, fight durations, etc) pretended that the fight started when the pull started.
