### ISSUE TITLE
How to separate raidboss timeline & the text alerts?

### ISSUE THREAD

**Issue by shiraiseyuki** [quisquous/cactbot#455]
I am wondering how do I reposition the timeline? (The default one has the timeline at top left and I wanna position it at bottom left instead). Can anyone help me here? Thank you!

**Comment by quisquous** [comment]
You can do this with CSS: https://github.com/quisquous/cactbot/blob/master/AdvancedCactbot.md#customizing-appearance

**Comment by shiraiseyuki** [comment]
Which one in specific that I need to change/add and where do I add it in the user/raidboss.js file? Sorry I don't know anything about coding >.<

**Comment by DamienRamirez** [comment]
What you want it Raidboss..css Edit & change this part:
#timeline-container {
  position: absolute;
  top: 0px;
To
#timeline-container {
  position: absolute;
  bottom: 0px;

**Comment by shiraiseyuki** [comment]
It worked! Thank you so much for the help!
Another question, do i need to manually change the timeline part each time there is a new cactbot update?
Is there a way to make it stay the same everytime?

**Comment by DamienRamirez** [comment]
Yes & no, Yes if you copy all the files & overwrite. No if you keep his one file each time E.g. save a copy somewhere else like my documents > FFXIV & then drag drop it into the new install each time. 
_There are other advanced ways which are easier but they will cause issues in the long run.... Drag drop is easier/safer._

**Comment by shiraiseyuki** [comment]
@DamienRamirez I see, I understand. 
With the advanced ways, do I also need to manually change the timeline everytime there is a new update?

**Comment by DamienRamirez** [comment]
No you just play around with security settings so you cant delete it until you play around with them again, Also sometimes locks ACT out of using the file... Trial & error.

**Comment by quisquous** [comment]
You should copy your change timeline-container block of code (everything from `#timeline-container {` to the closing `}` a few lines later) and paste it into a file called **cactbot/user/raidboss.css** instead of modifying **cactbot/raidboss/raidboss.css** directly.  The user files never get overwritten and always apply after cactbot's default css, and so are a much safer place to add modifications.

**Comment by shiraiseyuki** [comment]
@DamienRamirez Oh so just edit the security settings for the file and making sure that I set it so that I cannot delete/replace it? Okay, I just need to find out how to do that with the security setting.

@quisquous For some reason I cannot open the cactbot/user/raidboss.css file, instead I can open and edit the cactbot/ui/raidboss.css one. :(

**Comment by quisquous** [comment]
You may need to create the user file if it doesn't exist.

**Comment by shiraiseyuki** [comment]
@quisquous Oh it does exist, but when I try to open the file, there is a windows scrips host error. :(

**Comment by DamienRamirez** [comment]
> @quisquous Oh it does exist, but when I try to open the file, there is a windows scrips host error. :(
You don't edit the User files. You go to:
\Advanced Combat Tracker\OverlayPlugin\cactbot\ui\raidboss
**Copy** the raidboss.css file (the one with the changes)
Then navigate to
\Advanced Combat Tracker\OverlayPlugin\cactbot\user
& **paste** the copied file in here.

Thanks @quisquous for that.

**Comment by quisquous** [comment]
Is this issue all sorted then? Just trying to see if there's anything else that needs helping with here.

**Comment by shiraiseyuki** [comment]
@quisquous Yes this is all sorted out already, thank you so much!

**Comment by someONEgood** [comment]
Thought I'd toss in my two cents before this is closed, in case anyone else needed similar.
Here's what I use to keep the text alerts above the timers, as well as match the timers width to whatever width you set the window. (Hope this helps).

Replace #popup-text-container and #timeline-container with:

#popup-text-container {
  position: absolute;
  top: 0px;
  left: 0px;
  width: 100%;
  text-align: center;
}

#timeline-container {
  position: absolute;
  top: 250px;
  left: 0px;
  width: 100%;
  height: 120px;
  font-size: 14px;
}

Example:
![raidboss](https://user-images.githubusercontent.com/46905309/62808566-0ad82200-babe-11e9-96e2-4508762639c7.PNG)
