### ISSUE TITLE
raidboss: game ready sound not working on non-English clients

### ISSUE THREAD

**Issue by Bing-su** [quisquous/cactbot#4560]
## Description

game ready sound (d.va: game on!) not working on non-English clients

same issue as #4536

I tried to fix it, but the regex is a bit difficult..

**Comment by Akurosia** [comment]
I can confirm, sound does also not play in german language like it used to be

**Comment by Akurosia** [comment]
the changes from https://github.com/quisquous/cactbot/commit/e061a02c8e3d1761e4a5afd10d4f90f70011ca07 were not reflected in the translation are like for all the other files

**Comment by Akurosia** [comment]
this pr should fix the issue: https://github.com/quisquous/cactbot/pull/4561
