### ISSUE TITLE
Fisher: Timer Bars Continue Going Down/Up After Hooking Fish

### ISSUE THREAD

**Issue by DatXFire** [quisquous/cactbot#4562]
## Description

I noticed this change sometime within the last few months. Previously upon a hooking a fish the progress bars for each window would stop. However currently, they continue proceeding in the direction they were progressing at the time of hooking. Video linked below.

## Additional information
Cactbot Version: 0.26.10.0
Overlay Plugin Version: 0.16.2.0
FFXIV ACT Plugin Version: 2.6.5.3

[Video](https://www.dropbox.com/s/ul43suxbnhb2y9x/ffxiv_dx11_goYvbOvyOU.mp4)

**Comment by quisquous** [comment]
I wonder if one of the changes to the timer bars in the past few months has caused this.

**Comment by quisquous** [comment]
This should be fixed.

**Comment by DatXFire** [comment]
Hey, hadn't been fishing in a while so hadn't had a chance to test since you said this had been fixed. Unfortunately I still seem to be experiencing this issue. [Video](https://www.dropbox.com/s/alee10lfrcgd2p3/ffxiv_dx11_ytvf2xXHIF.mp4?dl=0)

Cactbot Version: 0.29.8.0
OverlayPlugin Version: 0.19.20.0
FFXIV ACT Plugin Version: 2.6.9.0

**Comment by DatXFire** [comment]
> This should be fixed.
@quisquous 
Hey, hadn't been fishing in a while so hadn't had a chance to test since you said this had been fixed. Unfortunately I still seem to be experiencing this issue. [Video](https://www.dropbox.com/s/alee10lfrcgd2p3/ffxiv_dx11_ytvf2xXHIF.mp4?dl=0)

Cactbot Version: 0.29.8.0
OverlayPlugin Version: 0.19.20.0
FFXIV ACT Plugin Version: 2.6.9.0
