### ISSUE TITLE
Incorrect call on DSR P6S Cauterize (Dives)

### ISSUE THREAD

**Issue by Ryphael** [quisquous/cactbot#4564]
A couple of friends and I have found out that cauterise on P6 in Dragonsong Reprise during the part where u need to be dived by the opposite dragon that you got tethered from is wrong. It's constantly calling out for nidhogg regardless of whether you're getting hit by Hraes or Nidhogg.

**Comment by quisquous** [comment]
Could you attach a network log here?

**Comment by Ryphael** [comment]
Hmm.. my logs exceed the limit of 25mb, even after splitting it's still too huge to upload

**Comment by quisquous** [comment]
Can you zip it or upload it to some other site and link it here?

**Comment by Ryphael** [comment]
https://www.file.io/zHwi/download/mHmHEbEc9xAi

Done, hopefully this allows you to get it
