### ISSUE TITLE
Error after uptdate. '' System. ArugmentNullException value cannot be null ''

### ISSUE THREAD

**Issue by DaCasaNolldor** [quisquous/cactbot#4571]
![image](https://user-images.githubusercontent.com/107095132/172533265-74bf514b-c316-426c-8061-7511b8b025dc.png)
Good evening everyone.

Basically after today's update, I opened ACT, I have Cactbot's DPS and Timers/etc parse in it. But strangely the dps wasn't counting, the logs and not even the cactbot working. I clicked on check for updates and it said it was normal... But on Check for cactbot updates it gives me the following error:

Failed: System.ArgumentNullException: Value cant be null
Name of the param : types
in System.Type>GetConstructor(BindingFlags bindingattr, Vinder vinder, Types[] types, ParamterModifier [] modifiers ) in
RainbowMage,OverlayPuligin.GeneralconfigTab.bntCactbotUpdate_click(Object sender, EventArgs and.

Please help

**Comment by quisquous** [comment]
The update button is the same as #4418.  The rest of the issues are normal after any ffxiv patch.  You need to wait for the ffxiv plugin to be updated.
