### ISSUE TITLE
Delayed callouts after patch 6.15

### ISSUE THREAD

**Issue by Nlilyth** [quisquous/cactbot#4576]
Did endsinger aria Ex, text triggers were delayed and seemed like it was lagging. I didnt have any problems before patch.

**Comment by quisquous** [comment]
Have you updated to the beta version?

**Comment by Nlilyth** [comment]
Yes, I did. Before applying the beta version, cactbot wasnt working. After that, I applied the beta version and It worked but delayed. Lets Say that First Aoe of Endsinger Aria Extreme Is Despair Unforgotten, ok? Usually 2 seconds before It triggers the visual text saying "aoe". Now It appears the aoe and the trigger appears right After the aoe was made. Sorry of this contains english mistakes but I am not native and plus I am at work

**Comment by Soffish** [comment]
@quisquous I have not because i have no idea where I can download the beta update

**Comment by quisquous** [comment]
> @quisquous I have not because i have no idea where I can download the beta update

@Soffish Ok, then that's why it isn't working.  After every patch, you need to update to a new version of the ffxiv plugin.   You can get it here: https://discord.com/channels/551474815727304704/551476805148737546/983877173456830504

**Comment by shulepinlol** [comment]
I got beta version from discord server and cactbot works but triggers are delayed as mentioned above

**Comment by quisquous** [comment]
I've heard reports that the new beta version is better.  Can any of you with delayed callouts give that a try?

**Comment by Nlilyth** [comment]
> I've heard reports that the new beta version is better. Can any of you with delayed callouts give that a try?

Yes, definitely! It works just like before now, for me.

**Comment by quisquous** [comment]
Thanks for the update.  I'll close it in a day or so in case anybody else has feedback.
