### ISSUE TITLE
no sounds

### ISSUE THREAD

**Issue by osuka91** [quisquous/cactbot#458]
Everything was working fine until I updated for 5.0. I can see on the overlay that cactbot is registering the actions and iI do hear the noises that sound like a drum but no voice call outs. I'm specifically talking about things like the "game on!" you hear when doing a ready check or a shirk followed by the player name . If anyone could help out I would greatly appreciate it

**Comment by osuka91** [comment]
turns out I had to edit the javascrips file in notepad and turn tts to true instead of false

**Comment by quisquous** [comment]
So the noise that sounds like a drum is what you normally hear.  The "voice call outs" which are text to speech are not on by default, and only set with that option.

It sounds like you found it.  If you didn't, you should probably set that option in your **user/raidboss.js** file and not in your **ui/raidboss/raidboss.js** file, which will be clobbered the next time you update cactbot.  See: https://github.com/quisquous/cactbot/blob/master/AdvancedCactbot.md#customizing-behavior
