### ISSUE TITLE
Fishing Timer Not Finding Zone/Updating

### ISSUE THREAD

**Issue by HotandReddy** [quisquous/cactbot#4583]
## Description

Cactbot Fisher does not function when casting in various fishing holes. Cast time remains at 0.0, no previously caught fish are shown, fish list does not update, and location is set as (----------------).

## Additional information
![Cact](https://user-images.githubusercontent.com/107214188/172926341-139b36c2-96f2-4b58-8c54-b479b9b5a3ed.png)

**Comment by vkhromenkov** [comment]
Yeah, got same problem in the Ultima Thule zone - if fishing hole has any greek letter - it bugs Fisher out.

**Comment by quisquous** [comment]
Is this fixed now?

**Comment by quisquous** [comment]
I'm going to assume this is fixed now.  Please reopen another issue if this is still happening.  Thanks for the bug report!
