### ISSUE TITLE
loud 'doot' sound alert everytime we reach in DSR phase 5 'wrath of the heaven' when 'twisting dive' finishes casting, but why?

### ISSUE THREAD

**Issue by healrsadjust** [quisquous/cactbot#4588]
Hello
I'm trying to figure out why this is happening, I have my default alerts as TTS Only, I have changed in cactbot settings and made sure that those mechanics are TTS only as well, I even have tried turning them to Text only or disabled but still this loud 'doot' comes out during then and its really annoying.  Does anyone have any other ideas to turn this sound alert off.  I never get this sound alert anywhere else, ever only used TTS, never have sound alerts on for anything.

**Comment by quisquous** [comment]
Whoops, saying "this might fix" was enough to make github think I was closing this.  Reopening.

I do think that the most likely trigger causing issues is `DSR Wrath Thunderstruck Targets`.  Could you try disabling that trigger entirely and seeing if this still happens?  I tried doing some local debugging to reproduce this, but couldn't get your situation to happen.

**Comment by healrsadjust** [comment]
I will try that out tomorrow when we go again
