### ISSUE TITLE
Having difficulty with installation

### ISSUE THREAD

**Issue by twotonerebel3** [quisquous/cactbot#46]
After following steps(maybe I made a mistake), I get this error when trying to create the overlay. To clarify, this is what shows up when I open ACT/Plugins/overlayplugin/general and read the bottom. It doesn't actually let me select cactpot as an overlay.

2/11/2018 7:26:36 PM: Error: LoadAddons: C:\Users\Jay\Desktop\ffxiv plugin stuff\addons\CactbotOverlay.dll: System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at RainbowMage.OverlayPlugin.PluginMain.LoadAddons()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Sorry if this error was mentioned or explained elsewhere, I had trouble finding something similar to it.

**Comment by quisquous** [comment]
https://github.com/hibiyasleep/OverlayPlugin/releases/tag/0.3.4.0 comes with Newtonsoft.Json.dll, which should be directly in your C:\Program Files (x86)\Advanced Combat Tracker\ folder.

Do you have that file?

**Comment by twotonerebel3** [comment]
No. I do not know what happened to it. I went and put the file in and the error kept reoccuring. Using your link i completely uninstalled ACT and then I reinstalled completely and it worked. Thanks for your help.

**Comment by quisquous** [comment]
Glad you got it working!
