### ISSUE TITLE
Enimity Plugin isn't show correct info

### ISSUE THREAD

**Issue by werewolfboy13** [quisquous/cactbot#461]
I am having an issue where after the early access I am not getting acurate info from the Enimity plugin. It is either not showing correct hp(pc allies only) or anything at all. It also isn't color coding the roles like it used to. 

Is this an issue with your plugin or the ravahn/FFXIV_ACT_Plugin? 

Screenshots attached:

![Screenshot (3)](https://user-images.githubusercontent.com/43587009/61503574-daf59d00-a99d-11e9-9e2e-403ef1556e58.png)
![Screenshot (4)](https://user-images.githubusercontent.com/43587009/61503575-daf59d00-a99d-11e9-9fed-656ff84ee3fd.png)

**Comment by werewolfboy13** [comment]
did some playing around and it looks like to me that the ffxiv act plugin does indeed report the correct info by looking at the overlay from the plugin it self.

![image](https://user-images.githubusercontent.com/43587009/61504618-aa176700-a9a1-11e9-89f2-b4595b1df9de.png)

**Comment by quisquous** [comment]
If you want to file enmity plugin issues, can you do them on the enmity plugin repository?

The HP is not correct in the latest version of this enmity plugin, as I tried to make clear in the release notes: https://github.com/quisquous/ACT_EnmityPlugin/releases/tag/v1.13.0.1

**Comment by werewolfboy13** [comment]
Sorry thanks for the info. Didn't know there was another repository for it.

**Comment by werewolfboy13** [comment]
Just an FYI found an working one https://github.com/qitana/ACT_EnmityPlugin
