### ISSUE TITLE
DSR: Brightwing count off sometimes in Haurchefant v2

### ISSUE THREAD

**Issue by djc5166** [quisquous/cactbot#4631]
## Description

Sometimes (50%?) the Brightwing callouts are off in Haurchefant v2. The callout for 'one' starts on the 2nd Brightwing, and it is off by one for the duration.

## Additional information

I don't think I've run into this in Haurchefant v1, but we don't see v1 as often since its before the checkpoint.

[log.zip](https://github.com/quisquous/cactbot/files/9048606/log.zip)

<img width="370" alt="image" src="https://user-images.githubusercontent.com/19207074/177391506-7dc20b20-ff37-4a0f-9f38-32e09c844dcf.png">

**Comment by quisquous** [comment]
Should be fixed by #4636.
