### ISSUE TITLE
Catching a map causes an unhandled exception in Fisher module

### ISSUE THREAD

**Issue by highlyunavailable** [quisquous/cactbot#464]
7/19/2019 11:48:39 AM: Info: MiniparseOverlay: BrowserConsole: Uncaught TypeError: Cannot read property 'substring' of undefined (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin-themes-master/app/rdmty.js?v=2.0, Line: 248)
7/19/2019 11:51:24 AM: Info: MiniparseOverlay: BrowserConsole: Uncaught TypeError: Cannot read property 'substring' of undefined (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin-themes-master/app/rdmty.js?v=2.0, Line: 247)
7/19/2019 12:14:48 PM: Info: Fishing: BrowserConsole: failed to look up fish: timeworn zonureskin map (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin-0.3.4.0-x64-full/cactbot/ui/fisher/seabase.js, Line: 221)

I caught a map to get this error.

**Comment by quisquous** [comment]
Not planning to make any more fishing changes.
