### ISSUE TITLE
DSR P6 Akh Afah Boss% difference

### ISSUE THREAD

**Issue by FeaEaXIV** [quisquous/cactbot#4648]
## Summary

Would it be possible for Cactbot to display the % or raw HP difference between Nidhogg/ Hraesvelgr in the lead up to each Akh Afah? 
If Nidhogg were high, for instance, it could show
```
Nidhogg
2.4%
40.3k
```
and update as close to in real time as possible? I'm not actually sure if cactbot is capable of dynamically updating the text it displays, but I figured it'd be worth an ask!

**Comment by quisquous** [comment]
Yeah, cactbot right now doesn't have any reasonable way to update text from a trigger.  It's something we could add, but I don't think it comes up very much.  It could print the % difference though just once or twice.

If you're using dalamud, you can also add https://raw.githubusercontent.com/Eternita-S/MyDalamudPlugins/main/pluginmaster.json as a custom repository and use the EnmityHp plugin.

**Comment by valarnin** [comment]
Could warn on HP diff being too large with a 15s suppress or something I guess? But yeah right now there's no way to do update text dynamically after it's displayed.

**Comment by quisquous** [comment]
I don't think this is something I'm planning on doing. This is better suited for a dalamud plugin.
