### ISSUE TITLE
raidboss: DSR phase tracker misses P6

### ISSUE THREAD

**Issue by pikapikapikapikapikapika** [quisquous/cactbot#4664]
## Description
During P6 of DSR, `data.phase` remains set to `thordan2`. I was expecting it to update to `nidhogg2`.

## Additional information
This issue happens for me both in the raidboss emulator and in-game. That said, I don't think this technically broke anything - the existing P6 triggers don't have a phase-check condition afaik.

My best guess at the root cause is that the DSR Phase Tracker matches a `StartsCasting` log line, which doesn't seem to exist for 6667. ([link to trigger](https://github.com/quisquous/cactbot/blob/triggers/06-ew/ultimate/dragonsongs_reprise_ultimate.js#L166)).

**Comment by Legends0** [comment]
I see you are right, there is no cast for 6667 as it is just the NetworkAbility that goes off.

Looking into this further, 7438 for p7 just has NetworkAOEAbility, so I expect the tracker to also miss p7. We may need to add separate triggers for these or use a different spell/regex?

**Comment by Legends0** [comment]
Ah, that leads to another bug, 7438 is searched in regex, but 71E4 is what is checked in the trigger, which still has the same issue.
