### ISSUE TITLE
larboard/starboard left/right directions confusing due to 180 degree flip

### ISSUE THREAD

**Issue by jacob-keller** [quisquous/cactbot#4673]
## Description

During o11n, Omega uses starboard and larboard cannons, while flipping 180 degrees. When used twice in a row, the second callout will give a direction which is easy to misinterpret.

This is because the direction is defined in terms of the boss facing, but since the boss just flipped and players likely haven't moved behind him, it would make sense to instead base the left/right before the flip instead.

I can make a PR for this, but wanted to determine opinion on whether this makes sense or not.

**Comment by quisquous** [comment]
Hmm, I think this would be equally confusing to folks who see the flip.  I agree that it's ambiguous, but that's why it's left/right -> move (left)/stay (right) as the followup.  Is that not working, or do you think that's also confusing?

**Comment by jacob-keller** [comment]
Hm. Yea I can see that being pretty confusing either way.

However I think it's less confusing to see:

go left -> stay left

Rather than

go left -> stay right

Especially since nothing else happens between the two mechanics and the boss also always flips back to point the way he faced originally.

But I also understand wanting to keep directions always boss relative, since that helps coordinate things more easily overall.

It's another case of "once you know it's not bad" but I had a few friends ask about it and be confused initially.

**Comment by kaedys** [comment]
I had similar issues with the left/right wing on P3S, so I ended up overwriting the alert text to `Front: >>> . . . . Back: <<<` (or vice-versa for the other wing).  It both makes it into a visual rather than having to parse "left" vs. "right" in the midst of other mechanics, and gives me directions for both if I'm in front or behind the boss.  Not sure how easily that could be translated to the default alerts, but you should be able to apply similar overrides to any mechanics that are relative to the boss's facing.

**Comment by Tsunayoshi** [comment]
Back in Savage days we always called the side left/right from behind view and then stay or move. Since the boss turns 180° if the call out was the same u have to move if the callout is opposite u stay.

**Comment by quisquous** [comment]
Just cleaning up old issues.  Sorry again that this is confusing, but just trying to be consistent as much as possible that "left" means "left flank".  People are always going to disagree about "which left" and there's not any way to satisfy everybody and that's what config ui overrides are for to change the display text.  I'm going to close this for now.

**Comment by jacob-keller** [comment]
That's fine, I think it's a reasonable position.
