### ISSUE TITLE
random 99% CPU usage bug(probably fate watcher related)

### ISSUE THREAD

**Issue by edwardez** [quisquous/cactbot#4680]
Hi,

Recently I am suffering from a issue that ACT CPU usage randomly jumps to 99% then never goes down:

![2022-08-19 19_37_32-Task Manager](https://user-images.githubusercontent.com/11089470/185726196-9ab74bf8-6389-486f-b6fb-f2d370faf0c7.jpg)

It happens randomly so I am not sure why. I downloaded [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) then it turns out threads in `clr.dll` eat up all of my CPU.

![2022-08-19 19_44_09-Advanced Combat Tracker exe_13976 Properties](https://user-images.githubusercontent.com/11089470/185726211-13010f27-6250-4cef-bd9f-9f31515363b4.jpg)

I checked stack for 10+ threads, it seems like all of them are associated with the same thing `CactbotEventSource!Cactbot.FateWatcher.ProcessActorControl`.

Not sure when this issue starts, but I am sure I am seeing this in ACT `3.6.1.277|3.6.1.276|3.6.0.275`, my cactbot is up-to-date(auto update enabled).

Could you look into it? Thanks!

````
C:\Windows\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll!System.Collections.Generic.Dictionary`2.FindEntry+0xa1
CactbotEventSource!Cactbot.FateWatcher.ProcessActorControl143+0xd8
CactbotEventSource!Cactbot.FateWatcher.MessageReceived+0x8e
[Unmanaged to Managed Transition]
clr.dll!LogHelp_LogAssert+0x1b63
clr.dll!LogHelp_LogAssert+0x1a80
clr.dll!CreateApplicationContext+0x309ac
clr.dll!CreateApplicationContext+0x304b0
[Managed to Unmanaged Transition]
C:\Windows\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll!System.Runtime.Remoting.Messaging.StackBuilderSink.AsyncProcessMessage+0x1d1
C:\Windows\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll!System.Threading.ExecutionContext.RunInternal+0x172
C:\Windows\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll!System.Threading.ExecutionContext.Run+0x15
C:\Windows\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll!System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem+0x76
C:\Windows\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch+0x156
[Unmanaged to Managed Transition]
clr.dll!LogHelp_LogAssert+0x1b63
clr.dll!LogHelp_LogAssert+0x1a80
clr.dll!LogHelp_LogAssert+0x2320
clr.dll!MetaDataGetDispenser+0x12efa
clr.dll!LogHelp_LogAssert+0x2f08
clr.dll!LogHelp_LogAssert+0x2e73
clr.dll!LogHelp_LogAssert+0x2db2
clr.dll!LogHelp_LogAssert+0x2fa3
clr.dll!MetaDataGetDispenser+0x12e47
clr.dll!LogHelp_LogAssert+0x2abf
clr.dll!LogHelp_LogAssert+0x298f
clr.dll!DllCanUnloadNowInternal+0xca5
KERNEL32.dll!BaseThreadInitThunk+0x14
ntdll.dll!RtlUserThreadStart+0x21
```

**Comment by quisquous** [comment]
Sorry for not looking at this sooner.  I'm not sure there's anything I can do here, and FateWatcher has since been moved to OverlayPlugin.
