### ISSUE TITLE
6.2 content additions planning

### ISSUE THREAD

**Issue by JLGarber** [quisquous/cactbot#4682]
With more of us contributing here, it Seems To Me to make sense to do a bit of a roll call for those of us who do regular raidboss/oopsy work so we don't step over each other. I don't really care which piece of content I do aside from "I'd prefer not to do the trial".

### Complete

- MSQ Dungeon — quisquous (initial timeline/triggers/oopsy complete)
- MSQ Trial -- panicstevenson (initial timeline/triggers/oopsy complete)
- EX Trial -- Legends0 (initial timeline/triggers/oopsy complete)
- Pandaemonium 5 — panicstevenson (initial timeline/triggers/oopsy complete)
- Pandaemonium 6 -- JLGarber and quisquous (initial timeline/triggers/oopsy complete)
- Pandaemonium 7 -- JLGarber (initial timeline/triggers/oopsy complete)
- Pandaemonium 8 -- quisquous (initial timelintriggers/oopsy complete)
- Sephirot Unreal -- JLGarber (initial timeline/triggers/oopsy complete)

I'm envisioning each of us noting what we're going to focus on, possibly sharing logs to whoever has a piece of content that we're running. I'll start by claiming the Unreal, since I already did the EX version. I'll also pick some other stuff up in a day or so if not everything is in progress, since the Unreal should be a simple find/replace for the most part.

I know of at least @valarnin @Legends0 as well as @quisquous who regularly do Raidboss stuff. Maybe @panicstevenson as well. Others please also add in your preference on content once we see stuff released!

**Comment by valarnin** [comment]
Thoughts:

1. Chime in here when we start working on something. Follow up as needed
   - Kind of clutters up a single issue
   - Makes it hard to track comments by content
2. Use this issue as a reference, open a separate issue mentioning this issue when we start working on the content
   - Lets this issue serve as a common tracking point for the patch
   - Can reference the separate issue in the PR for auto-closing
   - Problems/thoughts/brainstorming tracked per content, easier to follow and chime in if someone has feedback/help

Additionally, I think a super early PR that adds skeleton/placeholder files and folders for timeline and trigger files would be a good idea to avoid conflicts in manifest?

**Comment by Legends0** [comment]
I agree with having skeleton files in place. Makes it easier to setup and start testing since I often don't have the zone ids.

I likely won't have anything for the first week here and likely not have anything for the first day as well. I tend to focus in on the harder content first, which can be relative. No plans to do the dungeons or unreal content. If I did anything for the first day here it may just be ex and might just be a timeline.

**Comment by quisquous** [comment]
Zone ids are updated, and skeleton files should all be added now.

**Comment by Legends0** [comment]
PR up for EX trial #4689. Feel free to make edits to it as I will be away.

**Comment by xpdota** [comment]
Not sure if it should be a separate issue or not, but the second "knockback" timeline trigger callout seemed to be late for me (it was right when the knockback went off).

**Comment by Legends0** [comment]
> Not sure if it should be a separate issue or not, but the second "knockback" timeline trigger callout seemed to be late for me (it was right when the knockback went off).
> 
> (Come to think of it, it has a cast, so doesn't need to be a timeline trigger at all?)
There are three spells that go off, the timeline syncs to the insta cast one as it was consistent. It's possible to switch to the casted ones, but would need all their Spell ids and a supressSeconds. At the time I just went with the insta cast which needs timeiline trigger. It's interesting that it worked for the first but was late for the second... might be a jump in the timeline occurring that could cause this?

**Comment by xpdota** [comment]
75A0 and 75A1 seem to start casting at the same time and have the same duration, so either one should work. 75A1 is the one that actually hits people while 75A0 hits nothing, but it shouldn't matter for the purposes of the trigger.

**Comment by panicstevenson** [comment]
I will take a look at P5N

**Comment by panicstevenson** [comment]
My group is running the Extreme tonight and guaranteed someone won't have the normal mode done so I'll get that done sometime tonight.

**Comment by JLGarber** [comment]
Closing since we have done basically all the content that might cause duplication of work.
