### ISSUE TITLE
How to change the tts voice cactbot uses?

### ISSUE THREAD

**Issue by Korovia** [quisquous/cactbot#4694]
I tried to change the tts setting in windows from MS Elsa to MS Zira, but cactbot still keeps using MS Elsa and I don't know how to change it. Elsa is for reading Italian, which while funny, its really janky at reading callbacks compared to a tts designed to read English.

I restarted ACT after each attempt, no success.

**Comment by quisquous** [comment]
cactbot uses ACT to play tts.  #4650 was about this too, and discord suggests that you go to ACT -> Options -> Sound Settings -> Text to Speech -> Text to Speech Control Panel Applet and change it there.
