### ISSUE TITLE
TTS for raidboss is playing in triplicate

### ISSUE THREAD

**Issue by nitermare54** [quisquous/cactbot#47]
When I go to Summerford and do the test script each of the text to speech callouts goes off 3 times overlapping with itself. I would love some assistance. Thank you for your time.

**Comment by quisquous** [comment]
Hi! Does ACT's text to speech for its custom triggers work properly for you?

Do you happen to have more than one raidboss CactbotOverlay?

**Comment by nitermare54** [comment]
Well.... I don't know what I did that fixed it... but I cannot get it to repeat the issue anymore. Thanks for the super fast reply.
