### ISSUE TITLE
Uwu gaols not working

### ISSUE THREAD

**Issue by davachido** [quisquous/cactbot#470]
Uwu jails aren't applying assignment anymore. 

Garuda no longer assign gaols, I fixed it by changing the regex to this: 
   regex: / 15:\y{ObjectId}:(?:Titan:2B6C|Titan:2B6B):Rock Throw:\y{ObjectId}:(\y{Name}):/,
   regexDe: / 15:\y{ObjectId}:(?:Titan:2B6C|Titan:2B6B):Granitgefängnis:\y{ObjectId}:(\y{Name}):/,
   regexFr: / 15:\y{ObjectId}:(?:Titan:2B6C|Titan:2B6B):Jeté De Rocs:\y{ObjectId}:(\y{Name}):/,

**Comment by quisquous** [comment]
Oh, interesting! Thanks for the notice.
