### ISSUE TITLE
Running test_timeline.ts manually

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#4706]
I see that there's `npm run util` to run test timeline, but it's a pain to enter stuff manually.

I tried running `ts-node -r jsdom-global/register util/test_timeline.ts -f Network_26603_20220826.log -t the_fell_court_of_troia -lf` but nothing happens?

(Also, is there a reason that test_timeline.ts is in a different folder than `make_timeline.ts`?)

**Comment by JLGarber** [comment]
Agreed, having a cleaner/more obvious way to invoke it would be extremely appreciated. As it stands, I simply don't bother and still use the Python version.

**Comment by quisquous** [comment]
This has been fixed now.
