### ISSUE TITLE
Problem using translation_fight python script

### ISSUE THREAD

**Issue by mooondark** [quisquous/cactbot#472]
Hello,
first of all, when trying to use it without any modification I get :
```
$ python translate_fight.py
  File "translate_fight.py", line 63
SyntaxError: Non-ASCII character '\xc3' in file translate_fight.py on line 63, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```
So I add manually :
`# -*- coding: UTF-8 -*-` in the header

Then I always get the following error :
```
$ python translate_fight.py
  File "translate_fight.py", line 217
    print("Warning: unable to print to console, use --output-file", file=sys.stderr)
                                                                        ^
SyntaxError: invalid syntax
```
Can you help me correcting this ?

**Comment by quisquous** [comment]
It sounds like you need to use python3 instead of python2, as the print syntax changed between the two versions.

**Comment by mooondark** [comment]
Well, I hate when it's so simple :D

It works fine with python 3.x
