### ISSUE TITLE
Not working after manually updating OverlayPlugin to the new fork version

### ISSUE THREAD

**Issue by JaneSmith** [quisquous/cactbot#4720]
I recently got a notification that OverlayPlugin needed to be manually updated to a new forked version. I followed the instructions and did this. But after doing so, I've noticed that Cactbot is no longer working.

In ACT, I have FFXIV_ACT_Plugin.dll, then OverlayPlugin.dll, and then CactbotOverlay.dll. All three are enabled.

I've noticed if I click "Check For Cactbot Updates", I get the error message "Cactbot is loaded but it never registered with OverlayPlugin!".

I also can't access the general Cactbot settings, where I can configure things like TTS and such.

What's going on here? Is there any way I can fix this?

**Comment by sarunohouseki** [comment]
I'm having the exact same problem. It says I'm using an incompatible version of overlayplugin upon loading, but I'm not. 

This is the error I get upon loading ACT.
![image](https://user-images.githubusercontent.com/53544734/187053774-e8f87cc7-3c16-4a0d-bbb2-ded6e08c60c6.png)

I see that ACTx86 is not currently supported by cactbot, which is what I was using before the patch with no issue. I also don't know why I seem to be using the 32-bit version of ACT anyway, seeing as I'm running 64-bit Windows 11. But no matter how many times I try to install ACT, it always chooses to install the x86 version. I'm not sure if that's the issue, or if it's something else.

Will cactbot eventually be updated to accommodate the x86 version, or should I keep trying to figure out how to install the 64-bit version?

**Comment by panicstevenson** [comment]
@JaneSmith Does your plugin listing look like this?
![image](https://user-images.githubusercontent.com/8849608/187055367-a9a2a3c4-4d22-48e2-87d5-734242f4a07f.png)
I know some people had an issue where the plugin was randomly disabled after going through the manual steps.

@sarunohouseki How are you attempting to install that it always ends up installing the x86 version?

I would also recommend reaching out in the [ACT Discord](https://discord.gg/hK523Pj) if you haven't already/

**Comment by Makdag15** [comment]
Delete the OverlayPlugin and cactbot folder before adding the same plugin.  The easiest way to get to the folder location is to select the Plugins tab at the top and then "Browse" and that will take you to the location I have below.  Once you are at the location delete the two folders.  After that just add the two plugins from "Get Plugins".

The folder is located here:  C:\Users\"YourName"\AppData\Roaming\Advanced Combat Tracker\Plugins

**Comment by quisquous** [comment]
I filed #4848 with a bunch of things to check.  If none of those work, please ask in the ffxiv discord.
