### ISSUE TITLE
Both Cactbot and Overlay Plugin dont work with 6.2 content

### ISSUE THREAD

**Issue by Sililos** [quisquous/cactbot#4721]
Simply put, Both plugins are working as intended for all old content including 6.15 etc.
BUT when entering Fel Court, Trail 4 or Abyssos, the overlay doesn't show and no combat mechanics are shown nor alerts.
In the Cactraid settings, 6.2 dungeons appear in the content with settings. But the plugins just don't appear to register that the fights in the new content are taking place i guess.

Overlay Plugin was updated to the fork, and a fresh download and install of Cactbot were also installed.

Initially Cactbot and Overlay plugin would uninstall themselves after entering any 6.2 content but since the last update to Cactbot, this has stopped.

I should note i use Dalamund but haven't tested with the default 'launcher'.

**Comment by Ants1988** [comment]
Fel Court works for me.
ex4 works.

P5,6,7 and 8 are not coded yet.

**Comment by Sililos** [comment]
Ahh that explains it, ty XD
Fell court still doesn't work for me nor those not programed ones. I still haven't had a group for EX4 but know its norm also doesn't work.

**Comment by Ants1988** [comment]
Trial 4 Normal isn't coded yet.

Trial 4 extreme is.

**Comment by Braendyn** [comment]
I just spent an hour progging in EX 4 and no cactbot whatsoever, except for provoke/shirk notifications

**Comment by Braendyn** [comment]
I tried Fell Court, and nothing there either

**Comment by Braendyn** [comment]
I have tried it using both Dalamud and the default launcher.  Still nothing in EX 4 or Fell Court

**Comment by Sililos** [comment]
Looking like it may be broken for more than just 6.2 content. Just ran Mt Glug and it didn't appear, i then ran norm Crown and had the same thing. No bars, nor alerts, nothing.

**Comment by Braendyn** [comment]
I don't know if anyone is still looking at this thread, but I had the same issue that Sililos had.  Cactbot and Overlay was working just fine with all content except 6.2 content.  No timeline or alerts for either Extreme Trial 4 or Fell court.  I had the latest version of ACT and all plugins.  I tried removing and re-adding all plugins.  I tried launching the game with and without Dalamud.  Still nothing.

I finally got everything to work by completely removing all plugins from ACT, uninstalling ACT, then starting over from scratch with a new ACT/plugin setup.

I doubt any of that helps isolate the issue, but at least I found a viable workaround.  I hope it helps somebody.

**Comment by Makdag15** [comment]
> I don't know if anyone is still looking at this thread, but I had the same issue that Sililos had. Cactbot and Overlay was working just fine with all content except 6.2 content. No timeline or alerts for either Extreme Trial 4 or Fell court. I had the latest version of ACT and all plugins. I tried removing and re-adding all plugins. I tried launching the game with and without Dalamud. Still nothing.
> 
> I finally got everything to work by completely removing all plugins from ACT, uninstalling ACT, then starting over from scratch with a new ACT/plugin setup.
> 
> I doubt any of that helps isolate the issue, but at least I found a viable workaround. I hope it helps somebody.

You didn't need to reinstall but what you did is essentially the same thing.

Delete the OverlayPlugin and cactbot folder before adding the same plugin. The easiest way to get to the folder location is to select the Plugins tab at the top and then "Browse" and that will take you to the location I have below. Once you are at the location delete the two folders. After that just add the two plugins from "Get Plugins". Also hit the "X" to remove it from the ACT program.

Edit: If you have a .common folder delete that as well.

The folder is located here: C:\Users"YourName"\AppData\Roaming\Advanced Combat Tracker\Plugins

**Comment by SpringsTea** [comment]
> > I don't know if anyone is still looking at this thread, but I had the same issue that Sililos had. Cactbot and Overlay was working just fine with all content except 6.2 content. No timeline or alerts for either Extreme Trial 4 or Fell court. I had the latest version of ACT and all plugins. I tried removing and re-adding all plugins. I tried launching the game with and without Dalamud. Still nothing.
> > I finally got everything to work by completely removing all plugins from ACT, uninstalling ACT, then starting over from scratch with a new ACT/plugin setup.
> > I doubt any of that helps isolate the issue, but at least I found a viable workaround. I hope it helps somebody.
> 
> You didn't need to reinstall but what you did is essentially the same thing.
> 
> Delete the OverlayPlugin and cactbot folder before adding the same plugin. The easiest way to get to the folder location is to select the Plugins tab at the top and then "Browse" and that will take you to the location I have below. Once you are at the location delete the two folders. After that just add the two plugins from "Get Plugins". Also hit the "X" to remove it from the ACT program.
> 
> Edit: If you have a .common folder delete that as well.
> 
> The folder is located here: C:\Users"YourName"\AppData\Roaming\Advanced Combat Tracker\Plugins

I tried this and still couldn't get it to work. I had to also delete and re add the alerts overlay afterwards to finally get it working.

**Comment by Sililos** [comment]
Did that stuff, tonight i just did EX4, and Nada, it still doesn't work with 6.2 content for me, even after a fresh install of all plugins.

**Comment by quisquous** [comment]
I filed #4848 with a bunch of things to check.  If none of those work, please ask in the ffxiv discord.
