### ISSUE TITLE
Not all alerts are working

### ISSUE THREAD

**Issue by Kellerman51** [quisquous/cactbot#4727]
Hey i have a problem with the new Ex Trial Storms Crown
Some alterts are working like Playstation or Bait middle than out. But 90% doesnt work for me. Not as text and also not as tts.
Is it because I play the game in another language ?

**Comment by Coolwalsh22** [comment]
+1 Latest update broke Storms Crown EX callouts

**Comment by EinfachPhoenix** [comment]
I had the same problem. The "Problem" was, that the Languange Setting of the ACT Plugin was set to English instead to German(Deutsch) (the language of my Client). Found under Plugins -> FFXIV ACT Plugin -> Parser Options. Maybe that helps

**Comment by quisquous** [comment]
Glad you got this sorted, EinfachPhoenix.  @Coolwalsh22 and @Kellerman51, please take a look at everything in #4848.  if you're still having issues, please ask in the ffxiv act discord.
