### ISSUE TITLE
Getting "move to negative/positive" spam during Yiazmat

### ISSUE THREAD

**Issue by dscott-soltech** [quisquous/cactbot#473]
When you get the negative positive buff in Yiamat, you used to just get a single "move to negative/positive message.  Now it seems to spam that message during the entire duration of the effect.

**Comment by quisquous** [comment]
This is a symptom of https://github.com/ravahn/FFXIV_ACT_Plugin/issues/223#issuecomment-513486275 and should be fixed in the next ffxiv plugin release.

**Comment by quisquous** [comment]
This should be fixed now.
