### ISSUE TITLE
I have not been able to get my cactbot to work for the past few days. 

### ISSUE THREAD

**Issue by Odynson98** [quisquous/cactbot#4755]
I did all the updates and cactbot hasn't been doing call outs. I even went as far as to uninstall ACT delete the folders ACT was in, reinstall ACT and the overlays/cactbot etc and it still isn't giving me any alerts at all. I can't figure it out. Everything is enabled and it was working great before the new patch dropped. Any ideas?

**Comment by Desudro** [comment]
I wanted to pipe up and say I'm having the same problem. I even got the update today about timelines and triggers for P5S, P6S, and P7S...but it's a quiet a church mouse in all the fights.

[Network_26604_20220831.2022.09.01.zip](https://github.com/quisquous/cactbot/files/9474689/Network_26604_20220831.2022.09.01.zip)

I'm attaching (I think) a file from our static's runs last night if that would be helpful in figuring out what's wrong. I have some from normal modes today if those would also be helpful.

**Comment by Kyva11** [comment]
I'm also having the same problem. In all fights it's working but in the new savage he's not making any calls.

I've checked to see if it's up to date and it says yes.

**Comment by Desudro** [comment]
I actually think I fixed it. You have to remove the overlays and redo them, and that _should_ fix it. If that doesn't work, remove all the Cactbot overlays, remove Cactbot, and reinstall it. At least this is what worked with mine.

**Comment by Kyva11** [comment]
I just did this, tomorrow at static I'll test it and let you know if it worked too. Thanks <3

**Comment by Kyva11** [comment]
Forgot to return LMAO. Worked, thank you!

**Comment by VengefulRacoon** [comment]
> I actually think I fixed it. You have to remove the overlays and redo them, and that _should_ fix it. If that doesn't work, remove all the Cactbot overlays, remove Cactbot, and reinstall it. At least this is what worked with mine.

Do I have to do this _every time_ there's an update? I already had to do this for the previous update. It's quite annoying. Some of my static buddies don't have this problem.

**Comment by quisquous** [comment]
It should be a one time thing.  The issue (I suspect) is that you removed/readded the cactbot plugin at some point without removing/readding your overlays.  Because of the way folders used to be named on disk, this would cause a mismatch and so you'd be using old data with new plugin.  Folders are named differently now so this should no longer be an issue for anybody.

**Comment by Nitrodroki** [comment]
The most likely culprit is that you have your URL set on a previous version for the raidboss.html file
Just go into your cactbot miniparseoverlay and check that your URL is not 
file:///C:/Users/your name/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/**cactbot-0.24**/cactbot/ui/raidboss/raidboss.html
Or something like that, your raidboss.html needs to point to the correct cactbot folder, a bunch of ppl around me had this issue and just realized that their url was just pointing toward wrong file from before when cactbot was using versioning in the folder names

**Comment by Odynson98** [comment]
I finally deleted all the act folders and reinstalled completely. Forgot about the call out lines and text and tts part but when i remembered I got it working great again!

**Comment by nmains89** [comment]
So I think the comment by Nitrodroki might have been my issue. Mine was seemingly pointed at cactbot-0.23 or something like that, but what is the correct folder? The other one in that folder was just cactbot with no version attached. Is that what it should be linked to?

**Comment by quisquous** [comment]
There's a lot of people chiming in here.  I've left some instructions in #4848.  If that doesn't solve your issues, please ask in the ffxiv act discord.

@nmains89 The plugin path should match the URL.  The "newer" path is to have cactbot/cactbot/ and not cactbot/cactbot-version/ but if they match then it's not an issue.
