### ISSUE TITLE
Titania Ex

### ISSUE THREAD

**Issue by Eyons** [quisquous/cactbot#477]
Not sure if its just Titania, however when I updated to the latest version of Cactbot (0.10.3) the Raidboss timers were not showing up at any point. When I downgraded back to version 0.10.2 the timers worked just like expected.

**Comment by mooondark** [comment]
I confirm. Even the test in Middle La Noscea is not working. When downgrading to 0.10.2, it works.

**Comment by smoky2310** [comment]
I tested the Raidboss timers on the dummy but its still not working for me. I also tried to do older fights like Tsuku or Byakko and I had no timelines even with the updated Version 10.4. I get no errors and for Tsuku it shows the timeline when I do a countdown then it disappears and shows up again after about 10 seconds. And I still dont have any timeline or trigger for Eden. :/

**Comment by mooondark** [comment]
0.10.4 fixed it for me. Tried in Middle la Noscea, it is displayed correctly.

**Comment by smoky2310** [comment]
Hm I dont know what I should do.

**Comment by smoky2310** [comment]
Seems like the old fights are fine. Only problem is if i do them with GNB but i still dont have timelines for 5.0 stuff.

**Comment by Lemagex** [comment]
With 0.10.3 my solution was to change the load order in ACT to put overlay as my first plugin and then the error went away, changing it back brought the problem back. After upgrading to 0.10.4 it works in any order.

**Comment by Eyons** [comment]
Middle La Noscea is working for me now in 0.10.4

**Comment by crystalexarch** [comment]
Can canfirm.

also I had to reload the overlay to make it works.

**Comment by quisquous** [comment]
Ok, I'm going to close this now.  If folks are still having issues with 0.10.4, please open a new issue.  :)
