### ISSUE TITLE
MCH pointer for overheatTime and batteryTime

### ISSUE THREAD

**Issue by gaogaostegosaurus** [quisquous/cactbot#479]
I tried looking at them with the test file on my side and they came up "undefined". Battery and heat work OK.

Also, if it's useful, I've been getting the new DRK resources this way (I kind of just hacked it together...)

```
  player = e.detail;
  player.ID = e.detail.id.toString(16).toUpperCase(); // player.id.toString(16) is lowercase; using "ID" to designate uppercase lettering
  player.debugJobSplit = player.debugJob.split(" ");

  // Temp DRK resources
  player.jobDetail.darkarts = player.debugJobSplit[4]; // 0 or 1
  player.jobDetail.darksideTime = parseInt(player.debugJobSplit[2], 16) + parseInt(player.debugJobSplit[3], 16) * 256;
```

Using the above, there's also a simple 0/1 switch for overheated found at player.debugJobSplit[7] which I've found useful for my purposes.

**Comment by quisquous** [comment]
https://github.com/quisquous/cactbot/blob/master/ui/test/test.js#L51

I renamed them to be consistent with the other jobs, so that's probably why it's not working for you.

**Comment by gaogaostegosaurus** [comment]
Oops!

I was wondering why there didn't seem to be anything wrong with it, haha... Thanks, going to fix my side of things now.
