### ISSUE TITLE
Incorrect callout for p8s n/s e/w bird

### ISSUE THREAD

**Issue by xilostcause** [quisquous/cactbot#4792]
![image_2022-09-04_191013515](https://user-images.githubusercontent.com/112831903/188337036-afd62d5f-11cc-43f7-a876-df17ec27d22d.png)

This mechanical call-out is incorrect frequently. Just reporting it so maybe it gets fixed or is disabled. It will call phoenix east/west when it spawns north/south, and vice versa.

**Comment by djc5166** [comment]
Can also confirm

**Comment by quisquous** [comment]
Huh.  I've never seen it call this wrong.  Do you have a network log you can share with me?

**Comment by xilostcause** [comment]
I’m not entirely sure what that is. I can try

**Comment by valarnin** [comment]
> I’m not entirely sure what that is. I will say it’s strange because my static mate will say his was wrong when mine is right and vice versa as well. It’ll just call it out differently for both of us sometimes. After the 2nd instance of it being wrong I just turned off that callout completely so I’m not sure I can find a long. If you show me, I might could later this afternoon.

https://github.com/quisquous/cactbot/blob/main/docs/FAQ-Troubleshooting.md#how-to-find-a-network-log

**Comment by xilostcause** [comment]
I'll have to turn it back on and get another pull of it calling incorrectly. I only have files that have a lot of pulls where there's only a handful I had that specific trigger turned on.

**Comment by ssilve1989** [comment]
Also ran into this. I believe it called wrong when the Phoenix was spawned on East during first Illusory, but other times seemed correct

**Comment by valarnin** [comment]
Trigger on/off status is irrelevant. We just need to know "At this time of day (e.g. 9:02pm) roughly, the trigger called out X when it should have been Y", along with the log file.

**Comment by valarnin** [comment]
@quisquous Looking at the trigger, it's making a call to `getCombatants` with no delay, so that's probably the problem? Add a `delaySeconds: 0.1` to the trigger maybe?

**Comment by quisquous** [comment]
I guess I'm not sure I understand why a delay would be needed here.  Are there other cases where we have startsUsing -> getCombatants that need a delay?

My only other thought is that there are two casts of the bird (since it hits two sides) and it's possible that maybe one of them is bogus.  I was going to switch to using the snake and see if that fixed it for others.

**Comment by djc5166** [comment]
<img width="818" alt="image" src="https://user-images.githubusercontent.com/19207074/188992549-bb134255-218d-4dd3-bfde-6e8e8cc36fa2.png">

[2022.09.04.23.57.10.zip](https://github.com/quisquous/cactbot/files/9521929/2022.09.04.23.57.10.zip)

I believe this is a time when it called incorrectly. It called east/west but the bird was actually north/south

**Comment by Legends0** [comment]
I may have to review some of my logs too, but I do think it may be sometimes wrong for this mechanic.

**Comment by quisquous** [comment]
@Legends0 if you're seeing this, could you add a local trigger that has a delay, but keep the old one too and see if they ever disagree?

**Comment by Legends0** [comment]
A delay of .1s works for me where the old trigger gets wrong. It's like one in 15 pulls though that the old trigger is wrong.

**Comment by Legends0** [comment]
Somewhat related, P8S Torch Flame can miss its call too. It just won't output though.

**Comment by valarnin** [comment]
I wonder if this issue is fixed or if it's exacerbated by https://github.com/OverlayPlugin/OverlayPlugin/pull/50...

**Comment by quisquous** [comment]
> I wonder if this issue is fixed or if it's exacerbated by [OverlayPlugin/OverlayPlugin#50](https://github.com/OverlayPlugin/OverlayPlugin/pull/50)...

Yeah, I think this would certainly explain this and a number of other things.  I'll do some testing with it, but I hope it would make things more consistent (and hopefully not break other uses of getCombatants that are somehow[??] depending on the old behavior).

**Comment by quisquous** [comment]
I think this is fixed now.
