### ISSUE TITLE
Huge FPS Drop and Stutter

### ISSUE THREAD

**Issue by easly1989** [quisquous/cactbot#48]
Hello,

Yesterday I decided to try out this plugin;
As I watched the video about the raidboss feature, and how it worked and I was really exicetd about that!

But, as soon as I've got into Sigmascape v1 savage to test it out I noticed two things:
1 - fps dropped to 20 at the start of the fight
2 - sometime it felt like the computer was about to hang and freeze

During a relatively __calm__ moment I decided to turn it off, and everything went back to normal.

I'm running FFXIV with Directx_11 and ACT x64 as Administrator, everything installed on a SSD drive
My notebook is an Asus Rog running Windows 10, with16gb RAM, I7 cpu (don't remember which one atm sry, i'm at work >_<) and a GTX960M 

as I'm playing using the notebook monitor that is a 4k, my FPS usually are not higher than 60, but I never experience drops like this one, neither i've ever experienced freezes of any kind.

Do you think the problem is related to the high DPI of my monitor, and the already low FPS?
Is there something I may try before buying a new monitor? (or a PC ... >_<)

Thanks for your time,
keep up the good work!

**Comment by easly1989** [comment]
As I thought the problem was my notebook...

It is kinda lame when you buy something that should be strong enough to break to world in half, but results in something that can't break anything at all..

I resolved using 1920x1080 resolution on my notebook, now I've around 120 fps (limited to 60) and your plugin works just fine

closing this,
sorry for the long, and not neededn issue!

**Comment by quisquous** [comment]
That's good to know! I have seen something similar myself, but am not sure whether the issue is in Chrome or part of Windows composition of overlays being very slow.  Sorry that you can't use 4k, but I'm glad you got it solved.
