### ISSUE TITLE
P6S & P7S Callouts / triggers giving incorrect information

### ISSUE THREAD

**Issue by Number0115** [quisquous/cactbot#4814]
## Description

P6S Calling out Pathogenic cells number incorrect, calling out exchange of agonies incorrect sometimes, calling out cachexia de buff, timers, bait timers/in/out incorrectly every time. 

P7S Call outs for tethers, direction and or platform are totally incorrect. Stack or separate calls for purgation incorrect, calling stack stack, spread spread or any other combo regardless of debuffs.

May be others these are just what i noticed. 

## Additional information

Problem started as far as i can tell today with the last update, though uninstalling and reinstalling previous version has not fixed the issue. 

It looked like there were some new edits to some of these but i just glanced at the triggers to see if I could find a temporary fix. 

ty

(Not sure if it's helpful but Triggernometry call outs are still correct though they are in limited use personally for supplemental information but i did test what triggers i could find for these mechs and they were accurate.)

**Comment by quisquous** [comment]
Can you attach a network log here for me to look at? I have never seen these be incorrect.

**Comment by Number0115** [comment]
[Network_26604_20220909.zip](https://github.com/quisquous/cactbot/files/9539449/Network_26604_20220909.zip)

Here a random pf p7s group, all stack / spread calls are incorrect, and all tether/platform calls are incorrect. 

Not sure if I will have time to go back to 6s to log but if i get a chance will add it later.

**Comment by Number0115** [comment]
Seems it was defaulting to another person when the overlay was started and was not able to be set back to self, seems to be resolved after full uninstall of ACT and all plugins, instancing with a group and re selecting self.
