### ISSUE TITLE
Some E2N mechanics can be skipped, messes up timeline

### ISSUE THREAD

**Issue by Nitrodroki** [quisquous/cactbot#482]
For example, you can have 0 tank buster. Don't know the details tho, just that our speed kill unsync with Cactbot timeline.

**Comment by panicstevenson** [comment]
I can confirm this; last night we didn't see a single tank buster in our runs. I did notice that the boss had some flavor text associated with the beginning of new phases, so we can sync to those lines. Also, for clarity this doesn't affect the raidboss callouts, only the timeline -- callouts still function as expected.

**Comment by quisquous** [comment]
Fixed now with #483.
