### ISSUE TITLE
p8s Nest Of Flamevipers Protean only

### ISSUE THREAD

**Issue by nestofflamevipers** [quisquous/cactbot#4828]
Hello, 

I always get the "Protean" callout, but never the "In + Protean" or "Out + Protean" callout. 
A few days ago I was getting other callouts but now it only gives me the "Protean". 

Can someone confirm this and maybe could you have a look at it?

**Comment by nestofflamevipers** [comment]
Oh yeah that might be it, I am using the german version.

**Comment by Legends0** [comment]
I think I've seen this happen, but it's rare for me.

**Comment by quisquous** [comment]
@panicstevenson @Legends0 do either of you have a log for this? Mostly I just suspect that the 791F cast starts before the 7953/7952 cast, but I want to confirm

**Comment by Legends0** [comment]
So yea, I think I can confirm this issue with both protean and partner stacks. It is visible in the raidboss emulator when parsing the problem log:
![image](https://user-images.githubusercontent.com/5702579/191116921-9b2cc614-edd8-42fb-809e-de2cf3f8f648.png)
