### ISSUE TITLE
P8S initial crush/impact direction incorrect

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#4835]
When I ran last night, it said "Away to east".  The boss was facing north, then rotated counter-clockwise to face south and the call came midway through rotation.

Does the boss always face north or south? It kind of feels that way.  I think also the boss recenters to face north during Reforged Reflection before casting footprint.  Does that mean if it's no longer facing north then it's south?  Or are there other rotations here?

cc @Legends0

**Comment by Legends0** [comment]
I think this means that we still need a delaySeconds. The trigger fires the moment the cast starts, but enemies will typically start casting and turn while casting. It can be seen on fflogs replay as well taking up to 0.5s or so to finish turning.

It might always face north/south, I could check logs later.

**Comment by Legends0** [comment]
I can confirm, each time he is casting Reforged Reflection he faces north. I think it's also the 7108 teleport that recenters the boss middle with facing north right before the cast means he will always start north. As you state, we can just check the heading data, if it does not match north, it likely means he is in the process of turning south.

**Comment by Legends0** [comment]
To note, I checked 7 logs, and only saw it facing north or south. So that seems to be the case.
