### ISSUE TITLE
How to use the raidemulator??

### ISSUE THREAD

**Issue by Dskygod** [quisquous/cactbot#4839]
The file(ui/raidboss/raidemulator.bundle.js) in release package seems to be incorrect. How can I do to update?

**Comment by panicstevenson** [comment]
Did you follow the steps in the [README](https://github.com/quisquous/cactbot#raidboss-emulator)? You're likely either going to need to run Webpack in some capacity locally or use the GitHub remote URL along with OverlayPlugin's ACTWS ngrok server.

**Comment by valarnin** [comment]
You don't need ngrok but you do need OverlayPlugin's WS in general, if you want raidemulator to use your cactbot config settings and user files.

1. Enable `Plugins > OverlayPlugin WSServer > Stream/Local Overlay` by clicking `Start` if it's not already enabled.
2. Open raidemulator from the github.io link with WS param (direct link: <https://quisquous.github.io/cactbot/ui/raidboss/raidemulator.html?OVERLAY_WS=ws://127.0.0.1:10501/ws>)
3. Follow the included instructions in the modal popup to import a log file, etc
