### ISSUE TITLE
p8s random no call out during cthonic vent

### ISSUE THREAD

**Issue by zymurgy0** [quisquous/cactbot#4849]
No logs for this but it’s a relatively common occurrence. Maybe 10-25% of the time it will not call out the first cthonic vent locations. Not a huge deal by any means.

**Comment by Legends0** [comment]
I believe adding a 0.3s delay to the trigger is a temporary fix for the initial vent while the trigger is still worked on for the later vents.

**Comment by doomsz** [comment]
> I believe adding a 0.3s delay to the trigger is a temporary fix for the initial vent while the trigger is still worked on for the later vents.

how ? :(
![image](https://user-images.githubusercontent.com/80488960/196654933-f1ebc23d-08f4-4f54-b153-124326883d1b.png)
is that it ?

**Comment by zymurgy0** [comment]
This issue was resolved in PR https://github.com/quisquous/cactbot/pull/4830
