### ISSUE TITLE
gh-pages branch is too big

### ISSUE THREAD

**Issue by trim21** [quisquous/cactbot#4865]
I have a 1 year ago cactbot repo (head 16700eb4 raidemulator: Convert RaidEmulatorAnalysisTimelineUI to typescript (\# 3106) - <valarnin> 1 year, 3 months ago)

And today I pull it I found I need to pull 1.67GB files

```text
remote: Enumerating objects: 22376, done.
remote: Counting objects: 100% (3747/3747), done.
remote: Compressing objects: 100% (197/197), done.
remote: Total 22376 (delta 3596), reused 3679 (delta 3542), pack-reused 18629
Receiving objects: 100% (22376/22376), 1.67 GiB | 6.29 MiB/s, done.
Resolving deltas: 100% (14320/14320), completed with 855 local objects.
```

Then I found currently github api says cactbot git repo's size is 1.74 GB (less than 100 MB 1 year ago).

also, it take actions/checkout 2min to clone the repo in github actions...

![image](https://user-images.githubusercontent.com/13553903/192562362-1901228a-35b7-41cb-8314-5e01526ca095.png)

**Comment by MaikoTan** [comment]
maybe [`git maintenance`](https://github.com/git/git/blob/master/Documentation/git-maintenance.txt) command is useful here.

**Comment by trim21** [comment]
> maybe [`git maintenance`](https://github.com/git/git/blob/master/Documentation/git-maintenance.txt) command is useful here.

need a github admin to run it on github server, not locally.

**Comment by trim21** [comment]
```text
# git clone https://github.com/quisquous/cactbot.git --branch main --depth=10000000 cactbot-test
Cloning into 'cactbot-test'...
remote: Enumerating objects: 61899, done.
remote: Counting objects: 100% (163/163), done.
remote: Compressing objects: 100% (135/135), done.
remote: Total 61899 (delta 47), reused 132 (delta 22), pack-reused 61736
Receiving objects: 100% (61899/61899), 63.52 MiB | 9.00 MiB/s, done.
Resolving deltas: 100% (47011/47011), done.
```

```text
# git clone https://github.com/quisquous/cactbot.git --branch gh-pages --depth=10000000 cactbot-test
Cloning into 'cactbot-test'...
remote: Enumerating objects: 55939, done.
remote: Counting objects: 100% (204/204), done.
remote: Compressing objects: 100% (134/134), done.
Receiving objects:  22% (12509/55939), 909.39 MiB | 10.25 MiB/s

```

**Comment by trim21** [comment]
currently gh-pages deploy workflow has a write amplification problme.

consideing commit bf023b55fdb27a95e7fd50e61d16df01440cfc41, it only change a 80kb source file in pr 2975, which generate a 43x size commit in gh-pages, because all raidboss module need to bundled again and update 3.47MB raidboss.bundle.js file

**Comment by quisquous** [comment]
> currently gh-pages deploy flow has a write amplification problem

Should the gh-pages publishing force-push to that branch (or reset --hard to main, and then push a commit on top)? That way we don't accumulate history? I don't think the history of the pages branch is important here, and it's really just there as a place to host the current built state.

(also cc @panicstevenson for general workflow FYI)

**Comment by trim21** [comment]
you can just use https://github.com/peaceiris/actions-gh-pages 's `force_orphan` option , all branch history will be removed and only latest commit is keeps in gh-pages branch.

**Comment by trim21** [comment]
looks fine now

```text
git clone https://github.com/quisquous/cactbot
Cloning into 'cactbot'...
remote: Enumerating objects: 70226, done.
remote: Counting objects: 100% (165/165), done.
remote: Compressing objects: 100% (104/104), done.
remote: Total 70226 (delta 67), reused 137 (delta 57), pack-reused 70061
Receiving objects: 100% (70226/70226), 83.16 MiB | 4.95 MiB/s, done.
Resolving deltas: 100% (52717/52717), done.
```

**Comment by quisquous** [comment]
Thanks for the great suggestion!
