### ISSUE TITLE
CSS styles not applied to WSServer URLs? 

### ISSUE THREAD

**Issue by Theletha** [quisquous/cactbot#4868]
The overlay is not showing the correct themed CSS styles when using WSServer URLs:

`file://C:/Users/Thele/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot-0.16.11/cactbot/ui/raidboss/raidboss_timeline_only.html?OVERLAY_WS=ws://127.0.0.1:10501/ws`
`file://C:/Users/Thele/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot-0.16.11/cactbot/ui/raidboss/raidboss_alerts_only.html?OVERLAY_WS=ws://127.0.0.1:10501/ws`

Previously it has showed the correct one for the timeline only but never with the alerts as you can see 
One overlay is from ACT (Top) and the other one is via WSServer URL (Bottom)

![167521530-e4c13363-40fd-450f-bc75-008a029712f3](https://user-images.githubusercontent.com/10131942/192090609-dd53564c-100f-4082-bd6c-e37ea710f805.png)

but now even the timeline has reverted back to the default theme 

![asU2T4B](https://user-images.githubusercontent.com/10131942/192090683-61e211e4-d9dd-46b2-918a-a53050445f97.png)

Is there a way for me to change the theme for the WSServer URLs?

**Comment by panicstevenson** [comment]
I think I see the issue:
This happened with the application of https://github.com/quisquous/cactbot/pull/4843, which is a more proper version of allowing skins to work without having to put the custom CSS within the timerbars themselves.
It looks like there is code to apply CSS that has always been failing with `OVERLAY_WS=` due to the forward slashes, so CSS has just never been getting applied but it didn't really matter since skins were essentially hardcoded.
I'll try to figure out a permanent change and something temporary so you can use skins before the next cactbot release.

**Comment by panicstevenson** [comment]
Probably not worth it, but if you needed to make this change locally, you can edit `raidboss.bundle.js` locally (`%APPDATA%/Roaming/Advanced Combat Tracker/Plugins/cactbot-0.16.11/cactbot/ui/raidboss/raidboss.bundle.js` for you) line 3798:
```js
  handleSkin(skinName) {
    if (!skinName || skinName === 'default') return;
    let basePath = document.location.toString();
    const slashIdx = basePath.lastIndexOf('/');
    if (slashIdx !== -1) basePath = basePath.substr(0, slashIdx);
    if (basePath.slice(-1) !== '/') basePath += '/';
    const skinHref = basePath + 'skins/' + skinName + '/' + skinName + '.css';
    this.appendCSSLink(skinHref);
  }
```
To instead be:
```js
  handleSkin(skinName) {
    if (!skinName || skinName === 'default') return;
    const skinCSSRelativeHref = `skins/${skinName}/${skinName}.css`;
    this.appendCSSLink(skinCSSRelativeHref);
  }
```

**Comment by Theletha** [comment]
I tested it just now, and it does not seem to do anything. Do i need to make the file read only so it cant be 

![image](https://user-images.githubusercontent.com/10131942/192155274-d390f80f-2ab2-44d8-9ed5-c27a51107e1a.png)

For me the line was on 3574
![image](https://user-images.githubusercontent.com/10131942/192155392-f8ea80e1-68d4-4dc1-a96e-428dee1985f7.png)


this is what i replaced it with

![image](https://user-images.githubusercontent.com/10131942/192155403-37343dd9-3344-4305-b608-aa32f07fccf9.png)

**Comment by Theletha** [comment]
OK i managed to get it working.

So i had to change URL with the right slash "\" and then also append the code u mentioned here. with both changed it is now showing the correct CSS style for both. amazing, thanks a lot dude!

Just one question how often am i expected to change this code? is it on every update? (i dont really mind it since it's easy to do)
