### ISSUE TITLE
Eureka is not working well.

### ISSUE THREAD

**Issue by wlfjddl11** [quisquous/cactbot#4904]
The cactbot does not work well when using the Baldesion Arsenal.
cactbot does not operate during the raid Please edit it

**Comment by Bing-su** [comment]
한국어로 쓰셔도 제가 읽으니까 여기나 파판인벤 ACT 전용 게시판에 스크린샷을 첨부해서 조금 자세히 써주실 수 있을까요...

**Comment by SubZero0** [comment]
It's not calling shape changes for Ozma or Ozmashade, not sure about other mechanics (such as meteor or acceleration bombs).

**Comment by F1reman2** [comment]
I want to add more onto this.
The timeline seems to bug out when finishing either Raiden or Art/Owain, The timeline doesnt stop (which is what results in the random callouts). Once it reaches the end of the raiden timeline it automatically begins the AV callouts and so on to ozma if you wait long enough.

My Guess as to why it doesnt call some mechanics and it does call others is based on if the alert is triggered by a skill, or a preplanned event on the timeline. though i have no idea how cactbot works and if thats even how it functions.

Ive personally just been restarting ACT between bosses to fix it.

**Comment by quisquous** [comment]
Hmm, that's very curious. If you (or anyone else) can upload a recent network log (+a video to go with the log if you can, but the network log is plenty) that would be the most helpful. More recent versions of OverlayPlugin say when combat stops and starts, and that might help me track the timeline part of this down.

The only triggers that are timeline-related past raiden are a "pop eurekan potions" warning for AV's Explosive Impulse and a "black hole" warning for Ozma. Other than that, all other triggers should be theoretically working.  Everything else is based on abilities as they happen and so the timeline being incorrect should not affect them.

I am not running this content anymore and am unlikely to ever run this again at this point.  Sorry for taking so long to get around to fixing this, but I need as much as help as possible.  It sounds like the issues are:
* timeline continues running (which might lead to incorrect "pop eurekan potions" + "blackhole callouts", but only these two)
* maybe some triggers are missing? (meteor? acceleration bomb? shapes?)
* something else?

**Comment by F1reman2** [comment]
I can Confirm Those two Callouts are exactly the ones that pop up randomly XD.
I cant tell if accel bombs work for the fact that ive never gotten one.
Ill Send a log + video once i finish my next BA Clear. Should be around tomorrow.

**Comment by F1reman2** [comment]
Ok. Finally got around to Recording it.
Heres the Video For the run.
[https://www.youtube.com/watch?v=6oZZ-ePtSzo](url)
ACT Log. there are 2 ba runs in it. The first Corresponds to the Video.
[https://drive.google.com/file/d/1UOr8Y-OQhEPV7TcviRFR9EkNb6Dx9Jrd/view?usp=share_link](url)

**Comment by quisquous** [comment]
Do you have "this zone will be sealed off in 15 seconds" or "this zone is no longer sealed" style messages in your chat log anywhere? (e.g. in a dungeon or a1s or something)? I don't see any, and that's what the BA timeline uses to stop the timeline.

If you have them in other zones, then something has changed in Eureka and I need to fix it.  If you don't have them in other zones, then you need to turn on that message in your game chat log.

**Comment by F1reman2** [comment]
oh... my god. that would be the issue. Tidy chat gets rid of it. Ty so much

**Comment by quisquous** [comment]
@F1reman2 is everything else working now too? ozma shapes, etc?

**Comment by quisquous** [comment]
I'm going to close this for now. Let me know if something is still not working here.
