### ISSUE TITLE
RAIDBOSS not working.

### ISSUE THREAD

**Issue by Khandurian** [quisquous/cactbot#491]
I have triple checked my config. But I just can't get triggers to work. All I can see is working when I use raidboss is Taunt alerts, holmgang also shows up; but that's it.
I have no idea what I'm doing wrong. There are no errors in the log that I can see.

**Comment by DrLippe** [comment]
What language are you using?
Is the FFXIV Plugin set to your language?
What triggers are you expecting? 
Are triggers for the desired fight already available for your language?

**Comment by Khandurian** [comment]
GREAT QUESTIONS. Never thought that might be an issue. Let me double check and come right back to you.

> What language are you using?
> Is the FFXIV Plugin set to your language?
> What triggers are you expecting?
> Are triggers for the desired fight already available for your language?

**Comment by DrLippe** [comment]
Good news is that the raidboss overlay seems to work in general. Eden and ShB Ex primals are still pretty new and may be a little buggy. You could try entering a fight and then open the Developer Tools in ACT, go to Console and copy/paste following code 
```js
var t = []; 
for (let i in gPopupText.triggers) {
  t.push(gPopupText.triggers[i].id); 
}
console.log(t.join('\n'));
```
This should print all loaded triggers. Check if that list does contain E1S triggers.

Alternatively or for further investigation you could provide us with a log file of said fight.

**Comment by Khandurian** [comment]
How do I open dev tools in ACT?

**Comment by witch1329** [comment]
make sure you whitelist the files with windows defender too. that was my issue.

**Comment by quisquous** [comment]
Which fights are you trying to run and aren't working? Is this still happening for you?

**Comment by Khandurian** [comment]
Hello! Sorry for the late reply. I haven't checked recently since all I've
been doing is leveling. I can say for sure there are no timers whatsoever
appearing for me in any of the leveling dungeons. I understand there are
timers for those.
A thought just occurred to me, could it be that the installation is somehow
corrupted because I forgot to "unblock" the files from the RAR at some
point? I assume if that were the case then I wouldnt be able to  use any
aspect of ACT overlay plugin. Yet again, maybe its not related. To clarify,
parsing is working correctly for me (even when using the Cactbot parser)

**Comment by quisquous** [comment]
Most levelling dungeons (other than the new shadowbringers ones) don't have any timelines or triggers.

Is this still broken for you in e1s? Can you try zoning into titan extreme with an undersized party and seeing if that works?

**Comment by quisquous** [comment]
If this is still not working, please let me know.  Queuing into titan extreme by yourself is a good way to figure out if timelines are working.  I'm going to close this for now.
