### ISSUE TITLE
TTS not working/intermittent during The Baldesion Arsenal (Eureka)

### ISSUE THREAD

**Issue by ales276** [quisquous/cactbot#4924]
The TTS feature stops working during The Baldesion Arsenal, most specifically during the last 2 boss fights, AV and Ozma. Every now and then there might be a random call that comes out, but overall, it seems to have stopped working in this content. The mechanic timeline still appears, just the TTS component seem to have stopped working. Is there any news on a fix? Thanks

**Comment by xiashtra** [comment]
This seems to be a continuation of #4904, I'd suggest adding whatever information you can to that issue.

**Comment by quisquous** [comment]
I'm going to close this in favor of #4904
