### ISSUE TITLE
Add P5S Ruby 1 quadrant

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#4932]
It'd be nice to have a call for the safe corner for Ruby 1 if anybody wants to make one.

**Comment by wexxlee** [comment]
Started working on this.  When the boss uses Topaz Stones (21 line, 76FD), four hidden actors simultaneously use 76FE, which coincides with the 2 magic stone and 2 poison stones appearing.  But I can't seem to figure out what distinguishes between the stone actors being magic vs. poison.  The only variance in the four lines seems to be position data, and there's nothing I'm spotting in the earlier 20 lines or any 257 lines that would tell the game client how to render a magic vs. poison stone:

`21|2022-10-06T20:04:49.8230000-07:00|4000A8EA|Proto-Carbuncle|76FE|unknown_76fe|4000A8EA|Proto-Carbuncle|1B|76FE8000|0|0|0|0|0|0|0|0|0|0|0|0|0|0|44|44|0|10000|||92.50|101.00|-300.00|-3.14|44|44|0|10000|||92.50|101.00|-300.00|-3.14|000038E9|0|1|59f8e87b6b5d4296
21|2022-10-06T20:04:49.8230000-07:00|4000A8ED|Proto-Carbuncle|76FE|unknown_76fe|4000A8ED|Proto-Carbuncle|1B|76FE8000|0|0|0|0|0|0|0|0|0|0|0|0|0|0|44|44|0|10000|||89.00|89.00|-300.00|0.00|44|44|0|10000|||89.00|89.00|-300.00|0.00|000038EA|0|1|38e0ac3ee68b9e37
21|2022-10-06T20:04:49.8230000-07:00|4000A8EB|Proto-Carbuncle|76FE|unknown_76fe|4000A8EB|Proto-Carbuncle|1B|76FE8000|0|0|0|0|0|0|0|0|0|0|0|0|0|0|44|44|0|10000|||101.00|92.50|-300.00|-1.57|44|44|0|10000|||101.00|92.50|-300.00|-1.57|000038EB|0|1|5bafd707865ddece
21|2022-10-06T20:04:49.8230000-07:00|4000A8EC|Proto-Carbuncle|76FE|unknown_76fe|4000A8EC|Proto-Carbuncle|1B|76FE8000|0|0|0|0|0|0|0|0|0|0|0|0|0|0|44|44|0|10000|||104.00|104.00|-300.00|0.00|44|44|0|10000|||104.00|104.00|-300.00|0.00|000038EC|0|1|ef878f83d93ac319`

That said, I _think_ we can still determine the safe quadrant even without knowing which stones are magic vs. poison.  
The arena is [85-115],[85-115], and center is 100,100. The magic stones seem to spawn with an x/y offset from center of 7.5/1.0 (or 1.0/7.5, depending on which wall they are attached to).  The two poison stones seem to spawn with an offset of 4.0/4.0 from the corner (e.g. 89,89, 89,111, etc.) or from center (e.g. 96,96, 96,104, etc.).  So we can check if any quadrant is empty (if so, that's safe) -- and if not, we pick the quadrant with a stone closest to center, knowing that's the poison stone.

Will play around and do some testing (hopefully today), but curious if anyone has seen a better way to figure out which stones are magic vs. poison.

**Comment by quisquous** [comment]
thank you!!!
