### ISSUE TITLE
Phila timeline error

### ISSUE THREAD

**Issue by AllSystemsGo** [quisquous/cactbot#495]
Towards the end of a Phila encounter, at almost exactly 4 minutes into the encounter, Raid Boss reported Fierce Beating was coming but the actual attack was Pendulum

**Comment by quisquous** [comment]
Do you have a network log file that you can send me when this happened?

**Comment by quisquous** [comment]
Just pinging again, in case you still have a log file where this happened, so I can fix up the timeline.

**Comment by AllSystemsGo** [comment]
Sorry - I don't have the log file. Attempts at troubleshooting ACT wiped out all my old logs.

**Comment by quisquous** [comment]
Ok! If you (or anybody else) sees this again, please send me a log.  Thanks for the notice, but I don't think there's anything I can do without a log to make a better timeline at the moment, though.
