### ISSUE TITLE
drop `eslint-plugin-dprint`

### ISSUE THREAD

**Issue by trim21** [quisquous/cactbot#4953]
`eslint-plugin-dprint` is using a embed ts plugin `typescript-0.32.4.wasm`, and it has been pretty old.

It can't format some of our ts files already

eg: 

https://github.com/quisquous/cactbot/blob/0c1c65a8b40992a4fa19c5099620e24e1ad19cfe/ui/jobs/components/blu.ts#L6-L11

You can try change dprint config in .eslintrc.js and reformat it with eslint, nothing will change because when you formatting ts with this plugin, you will get this:

```text
Error formatting C:/Users/Trim21/proj/cactbot/ui/jobs/components/blu.ts. Message: Line 31, column 12: Unexpected token `onUseAbility`. Expected * for generator, private key, identifier or async

    override onUseAbility(id: strin
             ~~~~~~~~~~~~
Had 1 error(s) formatting.
```

**Comment by quisquous** [comment]
Do we just need to upgrade? https://github.com/dprint/dprint-plugin-typescript/blob/b8589d04f456283907fc2a5632f4bd30280d1354/dprint.json

**Comment by quisquous** [comment]
I'll think about this.  We went through a bunch of options to setting on eslint+dprint and I don't want to remove it entirely without having an alternative in mind first.

**Comment by trim21** [comment]
Another problem caused by this plugin, eslint `parserOptions.ecmaVersion` 2022 require eslint8, and doesn't work with this plugin.
