### ISSUE TITLE
A way to replace timeline text without change any regex?

### ISSUE THREAD

**Issue by trim21** [quisquous/cactbot#4956]
> The second purpose is for timelines at runtime. cactbot will use the replaceSync section to auto-replace anything inside a sync /text/ on a timeline line, and the replaceText section to auto-replace anything inside the ability text.

Is there a way to replace timeline text only? I'd like to <del>say</del> saw something on my timeline bar without affecting any regex match.

Or I have to copy whole timeline and edit it?

**Comment by quisquous** [comment]
The timeline regex is based on the original timeline text.  If you only replace the text, the regex will continue to match.  (This is something you could test pretty easily if you're worried.)  Timeline triggers also match hidden timeline entries still.  However, if you `overrideTimelineFile`, then the original text is now something different and the regex (might?) not match any more.  Hope that helps explain.

**Comment by trim21** [comment]
I'm confused now.

this should change timeline UI text, right?

![image](https://user-images.githubusercontent.com/13553903/196750222-78191744-8352-4e24-9a78-8092721912ce.png)

But it doesn't

![image](https://user-images.githubusercontent.com/13553903/196750165-1afc4798-789c-4b9e-bba8-adc784cf53d6.png)

**Comment by quisquous** [comment]
I think (maybe 95% sure) that user `timelineReplace` sections apply after the existing ones.  So, you'd need to replace the Chinese text with your own text.  `timelineReplace` works by just applying every single replacement (in order) to every text.  Adding user entries just adds more replacements to that list.

**Comment by trim21** [comment]
That's very unexpected for me...

**Comment by quisquous** [comment]
That's fair, I'm just not quite sure how else to have it work.  I thought about having the user `timelineReplace` apply first, but then what if the built-in `timelineReplace` ends up applying and replacing some of what was replaced (unexpectedly).  So, I thought that it has to go afterwards as the only safe way to do it.  I'm happy to talk about other ways to do it or if this needs to be documented better too.

For what it's worth, the cactbot config UI has timeline sections now where you can type in replacements and you don't have to do this through JavaScript.  (Hopefully this works for other languages??? I thought I tested this, but if not I'll fix it.)

**Comment by trim21** [comment]
Oh! yes! I should use UI to change them.
