### ISSUE TITLE
disabled trigger require regex or netRegex

### ISSUE THREAD

**Issue by trim21** [quisquous/cactbot#4965]
## Description

a disabled trigger  `{ id: "DSR Dragon's Rage", disabled: true }` not fail at 

https://github.com/quisquous/cactbot/blob/335801b5cdd57ef56493220651b5600ca62ff0b4/ui/raidboss/popup-text.ts#L692-L695

previous it you can disable a builtin trigger with this, but it's broken now.

**Comment by Souma-Sumire** [comment]
Yeah, it makes it very cumbersome to disable triggers.

**Comment by trim21** [comment]
this will be fixed by https://github.com/quisquous/cactbot/pull/5047 but I don't have time or energy to fix it in these days.
