### ISSUE TITLE
raidboss: incorrect p8s p2 Ashen Blaze + Spread callout? Missing Blazing Footfalls trigger

### ISSUE THREAD

**Issue by Legends0** [quisquous/cactbot#4982]
Seeing a spread call for this ashen blaze where there shouldn't be (or is this for the tank mechanic?)
![image](https://user-images.githubusercontent.com/5702579/197931382-b0cc9013-5d75-4b6a-825e-4359867f9658.png)

Was running latest commit (e699f6a), but I am not sure if it's something wrong on my end.

Perhaps related, my own blazing footfalls triggers in part 1 did not seem to do any calls or I just did not notice, I do see a lint-like error with the regex though. Also p6s did not call to get out after taking the first hit and I think there might have been a pr related to this to just stop the callout triggering for the last player that could have caused this?

**Comment by quisquous** [comment]
Yeah, I think there is something wrong here.  I saw all of the above.  The p8s reversal on fire/ice was also incorrect for some reason.  I'll try to figure out why.

cc @trim21 just because you've been making big changes recently

**Comment by quisquous** [comment]
Yes, this appears to be #4970.  It works on the commit before and breaks at this commit.  I'll look into this some more tomorrow and see if there's an easy fix.

**Comment by quisquous** [comment]
In particular in that screenshot re: NA2, the 4:18 and 4:49 calls are incorrect.  It should be "Stack First" (or maybe "Spread First" if it's a reversal) and just "Left" on its own and not "Left+ Spread".

**Comment by trim21** [comment]
sorry， I'm a cn player and don't have P8S yet…

**Comment by trim21** [comment]
anyone share a log to me  for debugging？

**Comment by trim21** [comment]
Oh yes I saw some trigger missing in DSR, too

**Comment by trim21** [comment]
Yes I know. we can't replace `NetRegexes.ability` either.

**Comment by quisquous** [comment]
Fixed by #4988
