### ISSUE TITLE
raidboss: p8s Blazing Footfalls Crush/Impact  triggers not triggering?

### ISSUE THREAD

**Issue by Legends0** [quisquous/cactbot#4984]
Seeing these not trigger today:
![image](https://user-images.githubusercontent.com/5702579/197932122-fc8d90d1-1ad5-4ae8-84c2-5b67f0ac8778.png)

**Comment by Legends0** [comment]
probably related to #4982, since this is with latest commit.

**Comment by trim21** [comment]
Oh yes I saw some trigger missing
