### ISSUE TITLE
Add triggers for Ambujam tentacle safe spots in Alzadaal's Legacy

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#4985]
It looks very promising to use map effect lines for the tentacle effects.  Does anybody want to look into this and write some triggers for it? Even sending logs + video on this issue would be very helpful.

```
00|2022-10-26T07:19:10.0000000+03:00|282B||The ambujam uses Tentacle Dig.|8e0bdc23a7258829
257|2022-10-26T07:19:10.6510000+03:00|80030057|00020001|11|00|0000|22937abf77243336
257|2022-10-26T07:19:11.4110000+03:00|80030057|00200004|11|08|0000|2d10b2333a83c8a0
```

**Comment by wexxlee** [comment]
> It looks very promising to use map effect lines for the tentacle effects. Does anybody want to look into this and write some triggers for it? Even sending logs + video on this issue would be very helpful.

I'm happy to take a stab at a trigger for this, although I probably won't be able to get to it until the weekend (jfyi in case someone else wants to tackle it sooner).
