### ISSUE TITLE
Migrating new trigger style

### ISSUE THREAD

**Issue by trim21** [quisquous/cactbot#4986]
A tracker for migrating all trigger to new object-netRegex style.

currently undone works:

- [ ] GameLog
  - [ ] message
  - [ ] dialog
  - [ ] echo

---

- [ ] documents
  - [ ] KR
  - [ ] CN
  - [ ] TW

**Comment by quisquous** [comment]
I think other missing pieces here are documentation and, once everything is converted, enforcing this style for cactbot built-in triggers.

**Comment by trim21** [comment]
There is a problem...

```ts
{
      type: 'StartsUsing',
      netRegex: NetRegexes.ability({ id: ['6D99', '6D9A', '6DD2'], source: 'Dragon-king Thordan' }),
}
```

this doesn't cause a type error anymore

**Comment by quisquous** [comment]
> There is a problem...

Is this related to #5038? or, what broke this?

**Comment by trim21** [comment]
> > There is a problem...
> 
> Is this related to #5038? or, what broke this?

no, because `{}` is correct type of `NetParam[T]`

**Comment by trim21** [comment]
it can be 
```
{
  type: 'StartsUsing',
  netRegex: {},
}
```

and therefore it can be 

```
{
  type: 'StartsUsing',
  netRegex: NetRegexes.ability({ id: ['6D99', '6D9A', '6DD2'], source: 'Dragon-king Thordan' }),
}
```
