### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by EnjuAihara** [quisquous/cactbot#499]
E2s Timelines dont work for me only triggers show up

got Ger client

**Comment by JLGarber** [comment]
It looks like there's only the English version for now. If you know the encounter well enough, you might submit a pull request. You can see the formatting for how things are localized in the [O3s trigger file](https://github.com/quisquous/cactbot/blob/2fffe0f47597e9afe9d66af16da7c1b6cf15f83b/ui/raidboss/data/triggers/o3s.js#L325). Quisquous has it set up so it's not necessary to do any translation work on the timeline files themselves, just in the trigger files.

**Comment by panicstevenson** [comment]
To echo what @JLGarber said: Please feel free to contribute back! Translations are usually submitted by others a couple of days after the English triggers are posted; although, I think @quisquous usually submits the French translations with their initial timelines.

Taking O2S as an example:
```
alarmText: {
  en: 'Death\'s Gaze: Look away',
},
```
Can be updated to:

```
alarmText: {
  en: 'Death\'s Gaze: Look away',
  de: 'Todesblick: Wegschauen',
},
```

Where `de` is the abbreviation for the German client of the game.

The trigger files for the raidboss plugin can be found under `ui/raidboss/data/triggers/<encounter_name>.js`

As long as you're familiar enough with the concepts of the fight and/or have strong enough English to parse what's written in the trigger file, you can contribute back to the cactbot community. 😄

**Comment by EnjuAihara** [comment]
The Triggers work for me but the time Bars want Show Up ist this Same issue with Client language

**Comment by panicstevenson** [comment]
Oh, I see. My bad, I didn't read the initial post as well as I should have.

I don't believe that it's required, especially if you're only seeing this issue with E2S but it worked fine with E1S.

To replace the text within the timeline, you'd follow the pattern laid out [here](https://github.com/quisquous/cactbot/blob/master/ui/raidboss/data/triggers/o3s.js#L325), but I don't think that it's necessary in order to get the English timeline, just that the moves will be in English.

**Comment by JLGarber** [comment]
My bad as well, I didn't explain that beyond just linking to it. Yes, you could just copy the English names into the localization objects within the timelineReplace array as both properties and values, but make the Locale value German instead. 

However, you wouldn't be able to sync to anything, since the English names don't match the German log lines. You could be fine for a fully linear battle, but any divergence where the timeline can't sync would break things.

**Comment by EnjuAihara** [comment]
So need to Change more to get sync Wirkung ?

**Comment by JLGarber** [comment]
Yes and no. What I told you about de-syncing was incorrect, that's not a function of the game client language selection directly, at least not in the way I presented it. However, you would still need to put a timelineReplace array in place in the file, and I don't know whether Cactbot will let you do a simple regex for "do a one-to-one replacement" and then set the locale property. I don't know enough about Cactbot's internals to say.

What really needs to happen is for someone to look through the [English timeline file](https://github.com/quisquous/cactbot/blob/master/ui/raidboss/data/timelines/e2s.txt) and put together a list of the German equivalents that the game uses. This can then be compiled into a proper timeline replacement. Given that people have already put together the replacement timelines for the normal versions of the raids, I would imagine that that will be on its way soon.

That being said, if you're up to it, the E2n timeline translation can be found in the [triggers file](https://github.com/mooondark/cactbot/blob/d8384194b4c62f9252230bcd2e2aafedb8f0338e/ui/raidboss/data/triggers/e2n.js#L242) for the encounter. I've linked to the exact place in the file so you can see how the replacement works. If I have some more time tomorrow I can find the exact lines in the E2s timeline that would still need translation and post them here. (I don't know enough German to machine-translate things safely.)

**Comment by EnjuAihara** [comment]
If we clear the Fight today i can Link a full logfile If this helps

**Comment by JLGarber** [comment]
It looks like there's a [pull request](https://github.com/quisquous/cactbot/pull/503) with the German timeline translations in the queue. Once Quisquous has time to review that, you should be covered.

**Comment by JLGarber** [comment]
@EnjuAihara Have you had time to figure out whether #503 and later updates resolved this for you?

**Comment by quisquous** [comment]
If this is still happening, please leave a comment and we can address it.  Otherwise, I'm going to close this for now.
