### ISSUE TITLE
raidboss: Incorrect ASS triggers

### ISSUE THREAD

**Issue by xiashtra** [quisquous/cactbot#4992]
## Description

There are a few issues with the ASS triggers for the first boss (Silkie) merged in #4967:

For the first and third Soaping Spree, the Suds Collector does not account for Silkie losing its suds buff, and therefore the Soaping Spree trigger makes incorrect callouts based on the last seen suds buff.

The Slippery Soap trigger is triggering off of a phantom cast from a hidden actor (0x79FB) instead of the cast from the boss actor (0x775E); for the third Slippery Soap, it fails to execute, since the phantom cast does not happen here.  This results in the "Behind puffs and party (East/West)" callout never being triggered.

@Legends0

**Comment by Legends0** [comment]
I see the PR I have just fixes the count issue, but there is a second component to this.
