### ISSUE TITLE
Regarding log type

### ISSUE THREAD

**Issue by Aireil** [quisquous/cactbot#502]
Hello,

I have a question regarding the suggestion of [not writing triggers against game log lines](https://github.com/quisquous/cactbot/blob/master/docs/LogGuide.md#dont-write-triggers-against-game-log-lines) in the log guide.

I don't understand the point about the speed. When I'm looking into the log files, usually ACT log lines are after the game log lines. So I tested to cast a spell with two triggers, one on the ACT log line and the other on the game log one. In all of the instances, the game log trigger was faster; the ACT log trigger was always delayed (depending on the cast ending or breaking).

Is this maybe no longer the case? Or maybe my test isn't really conclusive enough?

This question has been  inside my head since I've read the log guide, thank you.

**Comment by quisquous** [comment]
I think it is not always true.  Here's an 0.5s delay:
```
[20:21:31.210] 15:4001A9C6:Titan:4116:Stonecrusher:10686258:Tini Poutini:730003:3B894001:680F:2B70000:1C:41168000:0:0:0:0:0:0:0:0:0:0:88326:130964:10000:10000:0:1000:99.96767:92.28841:1.192093E-07:0.0173869:57701376:59121560:10000:10000:0:1000:100.0533:97.21521:0:-3.112351:
[20:21:31.787] 1E:10686258:Tini Poutini loses the effect of Raw Intuition from Paprika Rika.
[20:21:31.000] 00:282b:Titan uses Stonecrusher.
```

Here's one where it comes before, but there's no non-game log lines in between, so it's hard to tell if it's early or maybe just delivered simultaneously?
```
[20:21:26.201] 15:106F0213:Potato Chippy:DFB:Ruin III:4001A9C6:Titan:750003:35A70000:1C:DFB8000:0:0:0:0:0:0:0:0:0:0:0:0:58406311:59121560:10000:10000:0:1000:100.0533:97.21521:0:-3.112351:84997:84997:9200:10000:0:1000:97.8866:104.1428:0:2.855053:
[20:21:25.000] 00:282b:Titan readies Stonecrusher.
[20:21:26.289] 14:4116:Titan starts using Stonecrusher on Tini Poutini.
```

I'm not sure if something has changed here.  I have definitely found in the past that sometimes game log lines just don't get delivered at all, and so I have been in a habit of not using them.

Thanks for the input though.  I'll keep an eye on it.

**Comment by JLGarber** [comment]
Is this not the same issue [Ravahn referenced in the closed issue](https://github.com/ravahn/FFXIV_ACT_Plugin/issues/100#issuecomment-511067579) that was linked from the log line guide? That is, is the non-delivery of game log lines still an ongoing thing, or am I misunderstanding and the issue Ravahn noted is unrelated?

Not that it's a good idea to trigger against game log lines anyway, since they aren't as easy to disambiguate.

**Comment by Aireil** [comment]
I've tried again my little test and it gave me similar results, but with different amplitudes. The first time I tried it the difference was quite big, this time both triggers are closer, but there is still a difference.
I've set the game log line for broil III on the trigger "2" and the ACT log line on "1", [here's a video](https://www.youtube.com/watch?v=2NA4jBspjos).
I've switched both triggers to be sure it wasn't a delay on the TTS trigger and it yield the same results (the game log line appearing to be faster).
Not sure if the test proves anything, am I missing something?

Nonetheless, I'm wondering about this change in the trigger delay from my first test, I just started my ACT, so maybe it comes with time, I'll try again later.

**Comment by quisquous** [comment]
Thanks, that video is super interesting! I really appreciate these questions.  Thanks, @JLGarber for reminding me that the game log line issue is probably fixed now.

I was looking through logs, and my conclusion is that the `14` starts using message can sometimes be ordered before but sometimes after the `00` readies/starts casting game log.  (Although usually it's very close.) However the `15` or `16` damage line was 100% of the time before the `00` uses line in the log.  I didn't do an extensive study, but I'm curious if this is what you see as well?

I'm going to do a little bit more testing.  I want to test the hypothesis that the game log line and the `14` starts using message are delivered in the same batch by the plugin, even if one comes before the other.  If that's the case, then maybe there's a false delay in how ACT is presenting them to you.  If it's not, then maybe it's something to bring to ravahn and ask if there's some false delay that could be eliminated.
