### ISSUE TITLE
eslint cactbot-output-strings doesn't know about output strings added via indirection

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#5057]
`no 'leanSW' in 'output'eslint[rulesdir/cactbot-output-strings](https://github.com/quisquous/cactbot/blob/main/docs/RaidbossGuide.md#trigger-elements)`

See: https://github.com/quisquous/cactbot/pull/5044/files#diff-9052e588f3682bde891028636b948e55bc624627409cd50675d2dbfc0a3769e7R398

**Comment by quisquous** [comment]
cc @trim21

**Comment by quisquous** [comment]
https://github.com/quisquous/cactbot/blob/main/ui/raidboss/data/06-ew/trial/zodiark-ex.ts#L268-L269 (two blocks have enable/disable)

**Comment by trim21** [comment]
could you assign this issue to me incase I forget in the future?
