### ISSUE TITLE
ContentTypeID for The Masked Carnivale not included in content_type.ts

### ISSUE THREAD

**Issue by xiashtra** [quisquous/cactbot#5061]
## Description

The ContentTypeID for The Masked Carnivale is not included in `/resources/content_type.ts`

## Additional information

`/resources/content_type.ts` is listed as an auto-generated file from `/util/gen_zone_id_and_info.py`.  It likely needs to be made aware of The Masked Carnivale (`ContentType = 27`) for inclusion in auto-generation.

**Comment by quisquous** [comment]
Yeah, the table itself doesn't have an entry for it in the game data: https://xivapi.com/ContentType?pretty=true

The script itself would need to be updated to manually insert an entry.

**Comment by quisquous** [comment]
I think also probably the script should be updated to rename it to a better id than the first carnivale fight too.
