### ISSUE TITLE
user folder and customizing dps css?

### ISSUE THREAD

**Issue by Arokhaerr** [quisquous/cactbot#509]
Hey there, I tried customizing the dps layout with css but nothing changes at all when I setup my custom user/dps.css structure.

I am using rdmty layout and no matter what I enter into the css file it wont change anything. Do I need to put this specific dps css inside subfolders as well since its in a subfolder called rdmty? 

e.g.
is "\OverlayPlugin\cactbot\user\dps.css"
or "\OverlayPlugin\cactbot\user\dps\rdmty\dps.css"

the right folder? nothing I tried so far seems to work on it =/
It works fine though if I directly change the css inside of "\OverlayPlugin\cactbot\ui\dps\rdmty\dps.css" but that ruins the css everytime I simply overwrite a new version and thats what I thought the user folder is made for.

Any help is greatly appreciated :)

**Comment by DrLippe** [comment]
try `rdmty.css`

**Comment by Arokhaerr** [comment]
TY, it works. =D
