### ISSUE TITLE
Adding TTS via Options.PerTriggerOptions

### ISSUE THREAD

**Issue by noxaeternus** [quisquous/cactbot#51]
Hi,

Thanks for your hard work. I was wondering if it is not possible to add TTS to an existing Trigger via the User raidboss : Options.PerTriggerOptions ? 

It seems I can enable and disable the various options but not add TTS if it doesn't already exist within the trigger.  See my example below:
Options.PerTriggerOptions = {
  'General Provoke': {
    SpeechAlert: true,
    SoundAlert: true,
    TextAlert: false,
    tts: 'Provoke',
  },

}

Thanks for your help.

**Comment by quisquous** [comment]
You're wanting to be able to override or add the tts to particular triggers? (Are there ones you find particularly annoying?)

This should be pretty easy for me to add.  I'll try to take a look this weekend.

**Comment by danakj** [comment]
Quick alternative would be to copypaste the trigger into your user triggers and disable the one you copied from. Then you can edit it to taste.

**Comment by noxaeternus** [comment]
Hi quis,
I just wanted the "general provoke" to have a TTS too. Not annoying at all. 

Dana, yes, I work around it with what you suggested. Disabled "General Provoke" and created a new "Nox Provoke".  There is however a problem with this, the js file in the user folder can't take the same regex format as the ones in the "Triggers" folder. Guessing it's to do with special characters etc. Like if you copy paste the exact same "General Provoke" for instance, the whole user file breaks. It's something to do with the detecting player name regex but haven't found it yet.

Thanks

**Comment by noxaeternus** [comment]
Also , no rush. Whenever you can take a look.  There is one other thing that I would really like to do and thought you already had was detecting certain regex actions by role. I thought the following line did that:
condition: function(data) { return data.role == 'tank' },

But doesn't seem to work. I was writing something to detect and TTS Tank Deaths. I workaround it by using the names of our static tanks for now. Like:

regex: /Mickey Mouse is defeated by/,

Thanks again.

**Comment by danakj** [comment]
Can you paste your user file's content when it's not working, with the condition, to help debug?

**Comment by noxaeternus** [comment]
Sure. This is working file where I had to strip out some of the regex: 

Options.AlertsEnabled = true
Options.TextAlertsEnabled = true
Options.SoundAlertsEnabled = true
Options.SpokenAlertsEnabled = true
Options.ShowTimerBarsAtSeconds = 30
Options.KeepExpiredTimerBarsForSeconds = 0.7
Options.BarExpiresSoonSeconds = 8
Options.MaxNumberOfTimerBars = 6
Options.InfoSound = '../../resources/sounds/freesound/percussion_hit.ogg'
Options.AlertSound = '../../resources/sounds/BigWigs/Alert.ogg'
Options.AlarmSound = '../../resources/sounds/BigWigs/Alarm.ogg'
Options.LongSound = '../../resources/sounds/BigWigs/Long.ogg'
Options.InfoSoundVolume = 2
Options.AlertSoundVolume = 2
Options.AlarmSoundVolume = 2
Options.LongSoundVolume = 2

Options.DisabledTriggers = {
   'General Ready check': true,
   'General Provoke': true,
}

Options.Triggers = [

{
    zoneRegex: /.*/,
    
    triggers: [
      {
        regex: /:You are defeated by/,
        alarmText: 'YOU DIED',
      },
      {
        regex: /You blow a kiss/,
        sound: '../../resources/sounds/PowerAuras/bigkiss.ogg',
        volume: 1,
      },
      {
      id: 'Nox Provoke',
      regex: /:1D6D:Provoke:/,
      condition: function(data) { return data.role == 'tank' },
      infoText: 'Provoked',
      tts: 'Provoked',
      },
      {
        id: 'Nox Passage',
        regex: /You gain the effect of Passage of Arms/,
        infoText: 'Passage of Arms',
        tts: 'Passage Up',
      },
      {
        id: 'Nox Veil',
        regex: /You gain the effect of Divine Veil/,
        infoText: 'Divine Veil',
        tts: 'Divine Veil Up',
      },
      {
      id: 'Tank Death',
      regex: /Blah Blah is defeated by/,
      condition: function(data) { return data.role == 'tank' },
      alarmText: 'Tank Death',
      tts: 'Tank Death',
      },
    ],
},
]
Options.PerTriggerOptions = {
}

**Comment by noxaeternus** [comment]
Not working file with the "General Provoke" format replacing mine:

Options.AlertsEnabled = true
Options.TextAlertsEnabled = true
Options.SoundAlertsEnabled = true
Options.SpokenAlertsEnabled = true
Options.ShowTimerBarsAtSeconds = 30
Options.KeepExpiredTimerBarsForSeconds = 0.7
Options.BarExpiresSoonSeconds = 8
Options.MaxNumberOfTimerBars = 6
Options.InfoSound = '../../resources/sounds/freesound/percussion_hit.ogg'
Options.AlertSound = '../../resources/sounds/BigWigs/Alert.ogg'
Options.AlarmSound = '../../resources/sounds/BigWigs/Alarm.ogg'
Options.LongSound = '../../resources/sounds/BigWigs/Long.ogg'
Options.InfoSoundVolume = 2
Options.AlertSoundVolume = 2
Options.AlarmSoundVolume = 2
Options.LongSoundVolume = 2

Options.DisabledTriggers = {
   'General Ready check': true,
   'General Provoke': true,
}

Options.Triggers = [

{
    zoneRegex: /.*/,
    
    triggers: [
      {
        regex: /:You are defeated by/,
        alarmText: 'YOU DIED',
      },
      {
        regex: /You blow a kiss/,
        sound: '../../resources/sounds/PowerAuras/bigkiss.ogg',
        volume: 1,
      },
      {
      id: 'Nox Provoke',
      regex: /:(\y{Name}):1D6D:Provoke:/,
      condition: function(data) { return data.role == 'tank' },
      infoText: function(data, matches) {
        return 'Provoke: ' + matches[1];
      },
      },
      {
        id: 'Nox Passage',
        regex: /You gain the effect of Passage of Arms/,
        infoText: 'Passage of Arms',
        tts: 'Passage Up',
      },
      {
        id: 'Nox Veil',
        regex: /You gain the effect of Divine Veil/,
        infoText: 'Divine Veil',
        tts: 'Divine Veil Up',
      },
      {
      id: 'Tank Death',
      regex: /Blah Blah is defeated by/,
      condition: function(data) { return data.role == 'tank' },
      alarmText: 'Tank Death',
      tts: 'Tank Death',
      },
    ],
},
]
Options.PerTriggerOptions = {
}

**Comment by xDemonessx** [comment]
There's a  TTSApp that comes packaged with some Neospeech voices (Kate16 specifically I have) and a few others that allows you to create tts wav files. The easiest thing to do I would think, simply to replace bigkiss.ogg with the .wav. Assuming it works with .wav. You can always convert to OGG. 

[Here's an example](http://gbgl-hq.com/demoness/Provoke.wav)

You have the added bonus of using different voices, if you want to as well. Just a suggestion.

**Comment by quisquous** [comment]
> There is one other thing that I would really like to do and thought you already had was detecting certain regex actions by role. I thought the following line did that:
condition: function(data) { return data.role == 'tank' },

For what it's worth, data.role is *your* role.  You can't really have a trigger that checks if somebody is a tank when they die.

I think the only way you would be able to do this would be a complicated set of triggers, where you'd have some triggers that would detect tank skills (like heavy swing), and then set a variable on data with the names of those tanks, and then in some other trigger you could then check if the person's name who died was somebody who had previously used a tank skill.  Probably the easiest is just to do it by name of the person in your static.

**Comment by noxaeternus** [comment]
Hi,
That explains it then. Should have checked what it does properly. It's no big deal really, works well when regexing by player name. I will keep it like that. No need to overcomplicate it. 

The tts thing is also no massive issue. Thanks for suggestion XDemon but I think I will stick to just rewriting my own custom one for now that can use TTS. I am likely to want to create more and don't really want to keep creating new sound files. 

Nox

**Comment by quisquous** [comment]
@noxaeternus If I added tts to the provoke triggers, would you want:
(1) Provoke + person's name
(2) Just 'provoke'
(3) Either of the above, but only when it's somebody else (and not you) doing the provoke.

I don't want to make tts be too noisy, so was just curious what you would prefer as somebody who wanted this themselves.

**Comment by noxaeternus** [comment]
1 would be perfect as it would register my own provoke too. But either is fine.  You are right, you don't want too much noise but it would be nice to track.
