### ISSUE TITLE
Timeline not showing

### ISSUE THREAD

**Issue by Gahzombie** [quisquous/cactbot#510]
I have a friend that is trying to get cactbot to work however when testing it out everything is working but the timeline. When testing at the dummies everything showed up fine. But during ex fights like Susano or the new raids nothing is showing for him but is working 100% fine for me.

**Comment by liaoarden** [comment]
Real silly question but do they have it enabled as one of the overlays and not just the DPS meter? Are the files all unblocked? Have they tried reloading the overlay mid-fight when it stopped working?

I've had times where the raidboss module needs to be kicked once or twice and then it works again.

**Comment by Noirvent** [comment]
I actually have the same problem.
On E1S, the triggers are working (shares, swap tank, etc.), but the Timeline is not showing.
Work fine on dummies, Tsukuyomi/Seiryu Ex or Omega Savage (but not on Susano Ex with the same symptoms, triggers OK but no timeline).
Reloading mid.-fight doesn't change anything.

if that matters, my game is in french.

**Comment by DrLippe** [comment]
Timeline in SusanoEx is triggered by him saying 'Let the Revels begin'. This has not been translated yet, so it will only work on english client. 
Eden is still pretty new and work in progress

**Comment by quisquous** [comment]
Yeah, this is almost certainly just translations not being ready yet.  Is this still happening for you with the latest version?

**Comment by Noirvent** [comment]
It's been resolved for me, indeed (although I still have some delay in the mechs countdowns starting the flares part, but it's a minor hindrance).
No problem for the followings fights either
