### ISSUE TITLE
TTS no longer working

### ISSUE THREAD

**Issue by Ecosysticated** [quisquous/cactbot#511]
I downloded the new Cactbot update today and TTS is no longer working. Everything is set to True, I made sure to check the logs and there are no issues shown there. I've restarted my overlay, my game, my pc, and ACT. I went into E2 last night and they worked perfectly fine and now I can't get them up and running again.

**Comment by panicstevenson** [comment]
When downloading the latest release, did you remember to unblock the zip file?

I've had the same happen to me and that has always been my issue.

**Comment by quisquous** [comment]
Does the summerford farm test work? In terms of teleporting there and doing a /countdown to start the timeline and triggers?

**Comment by Ecosysticated** [comment]
Sorry, I figured it out. Something went wrong with the files and the example files got mixed in. I did a clean install of it and got it to work ^^;
