### ISSUE TITLE
De-synced resources for pre-6.2 game due to the changes in 6.2

### ISSUE THREAD

**Issue by sandtechnology** [quisquous/cactbot#5115]
## Description

Due to the revamp of old dungeons and trials in 6.2, the resources update of 6.2 did an breaking changes for the game pre-6.2: https://github.com/quisquous/cactbot/commit/afb903eac9204ba8c41f1107b8226645ba9338dc

For example, the zone id of The Vault was changed to `1066` from `421`, which does not exist in the pre-6.2, causing the timeline and trigger made for it broken.

This breaking changes could be happened as well in the next game version (6.3), since SE does not complete the support of The Duty Support to all main scenario quest dungeons.

It's there have any way or plan to fix that? Like adding an old id or did an replacement for those values? (Also those files is auto-generated, the changes should be done in the tools generating it, but I'm unsure which tools of this project used).

## Additional information

There are also a question for those revamped dungeons: does the timeline and trigger needs update for the revamped version? If so, how to ensure its compatibility to older game version?

**Comment by sandtechnology** [comment]
> I think if you or somebody else is interested in fixing it, go for it. Is it just The Vault? I think most of the other changes were in dungeons that don't have triggers yet.
> 
> If the triggers and timeline are still valid, then I think the way to fix it is to add the old zone id to `gen_zone_id_and_info.py` as a synthetic id (maybe `TheVault61`) and the old zone info as well into `synthetic_zone_info`. Re-run the file, and that zoneid as an additional zone id to The Vault. If they're not still valid, then maybe replace the id with `TheVault61` instead.

Thanks for replying and suggestions! The reason why I create this issue is I found this bug but I'm not familiar with cactbot, and affected zones are Snowcloak, The Keeper of the Lake, Sohm Al, The Aery, The Vault, Thornmarch (Hard) and The Steps of Fait, and I am not able to test if its timeline and trigger still valid in 6.2 (I am a CN player and don't have an international purchase), but I can do something in this case.

I would make an PR fixing that, and to make sure the name is not ambiguous with current version, I would add `(6.1)` as prefix in the content name (Since it need to divide into two files for different version).

**Comment by xiashtra** [comment]
This is going to be an on-going problem as they add Duty Support coverage to the rest of Heavensward and Stormblood.
