### ISSUE TITLE
Is there a way to fetch job info?

### ISSUE THREAD

**Issue by YQL-Skorpion** [quisquous/cactbot#5122]
Is there a ```job``` analogue of ```data.ShortName```? In particular I'm thinking about writing a few role-partner flex triggers, so it'd be extremely helpful if I can define a trigger based on whether conditions like ```['SMN', 'BLM', 'RDM'].includes(job_from_matches_target)``` evaluate to ```true```, signaling whether I flex for my caster. Sorry in advance if the answer is somewhere in documentation but I failed to find it.

**Comment by xiashtra** [comment]
`data.job`, from [job.d.ts](https://github.com/quisquous/cactbot/blob/main/types/job.d.ts) might give you what you're looking for.

**Comment by YQL-Skorpion** [comment]
It seems that `data.job` returns my job regardless; for example below is a test code used on o7n/s prey:

```
{
        id: 'O7S Prey',
        type: 'HeadMarker',
        netRegex: { id: '001E' },
        alarmText: (data, matches, output) => {
          let preyName = data.ShortName(matches.target); /* does its job correctly */
          let preyJob = data.job; /* always outputs my job */
          return output.text({ name: preyName, job: preyJob });
        },
        outputStrings: {
          text: {
            en: 'Prey: ${name} (on job ${job})',
          },
        },
      },
```

**Comment by trim21** [comment]
you can use `data.party` to get all player info in your party。

**Comment by trim21** [comment]
you can also use this script to make it return job name

https://github.com/quisquous/cactbot/issues/3000#issuecomment-855307753

**Comment by YQL-Skorpion** [comment]
I greatly appreciate the help.

Using the references (in particular `data.party`) I ended up writing something like this, and I think it's working so far!

```
          let preyName = data.ShortName(matches.target);
          var preyJob = '';
          data.party.details.forEach((p) =>
            { if (p.name === matches.target) preyJob = data.party.jobName(p.name); } );
```

**Comment by trim21** [comment]
and as we are discussing this, I think we could add a method (like `data.info(name: string) -> PlayerInfo ` for team player to get info of player @quisquous

**Comment by quisquous** [comment]
> and as we are discussing this, I think we could add a method (like `data.info(name: string) -> null | PlayerInfo{ jobID: job; ... }` for team player to get info of player @quisquous

Is this just `data.party.jobName(name: string)`?

**Comment by trim21** [comment]
maybe return a object with job id？
