### ISSUE TITLE
Some mob callouts in The Excitatron default to Chinese in some cases?

### ISSUE THREAD

**Issue by Zeffuro** [quisquous/cactbot#5128]
## Description

Both me and a friend are getting callouts for certain mobs (most notably the golden supporter) in Chinese [means something like "go get it" golden supporter].

## Additional information

https://github.com/quisquous/cactbot/blob/main/ui/raidboss/data/06-ew/map/the_excitatron_6000.ts

If available, please include any logs or screenshots depicting the issue you're experiencing.

**Comment by xiashtra** [comment]
I think this was a mistake introduced in #5093 that made it into the 0.27.23 release.  It was corrected in #5096 but that hasn't made it into a new release yet.

**Comment by Zeffuro** [comment]
Ah yeah I think you're right.
Line in question: https://github.com/quisquous/cactbot/pull/5096/files#diff-6cef61d574b59fd0ea746052f81d09f5ded93c57dbaa8a51b7b925e36af87015L12

I'm pretty sure that's it, okay should be all good next release then.

**Comment by quisquous** [comment]
Released!
