### ISSUE TITLE
Question: Splitting the user/raidboss.js

### ISSUE THREAD

**Issue by CostasAK** [quisquous/cactbot#514]
Dear Adrienne

I have been happily using the Cactbot plugin for a few raid tiers now and especially loved the ability to customise fight call-outs through the user firectory files. Now though, my raidboss.js file is getting slightly out of hand. I was wondering if there is a method to split the raidboss file by some command like "import(./raidboss-e2s.js)" for example. I'm not too familiar with JS, but a quick Google search led me to believe that I don't know the correct terms to search for... I would very much like to have all customisation available at a time, even though, of course, we're not doing all tiers in a night. Just for the sake of convenience and to allow for a spontaneous choice of fight, without having to change the user files.
Thank you for your time, especially all the time you have put into making this plugin work. I'm still amazed :)

Yours faithfully,
Gust Leonard

PS: I would have sent you a PM, but I don't know how... Hence this might not read as a typical 'issue', as you may have noticed. Apologies if this is not the right place.

**Comment by DrLippe** [comment]
Maybe I can help you aswell :)

If I understand correctly you got a lot of custom triggers in your `user/raidboss.js` file?
You could save them to a seperate file. A good way of doing this would be duplicating the `ui/raidboss.html` file and call it myRaidboss.html for example.

Now you'll create your custom trigger file, just like you would do in the `user/raidboss.js` file and call it `my-e2s.js`:
```js 
Options.Triggers = Options.Triggers.concat([
  /* your triggers here */
]);
Object.assign(Options.DisabledTriggers, {
  /* your disabled triggers here */
};
Object.assign(Options.PerTriggerOptions, {
  /* your per trigger options here */
};
```
Next go to your `ui/myRaidboss.html` file and find the `</body>` tag.
Now insert the following code:
```html
  <script src="../../user/my-e2s.js" />
</body>
```
Finally you need to point the source of your raidboss overlay to your `myRaidboss.html`.

There is another way to do this, but this way you won't delete any of your files while updating cactbot.

**Comment by CostasAK** [comment]
Thank you for the reply!

You understood correct, ideally having separate files for the different files, containing my customisation would be ideal. This looks like it should do exactly what I was looking for. Thanks again, I will try it out once I have a free evening!

Yours sincerely

PS: Should I close this now, and if so, can I still comment here if it wasn't what I was looking far after all?

**Comment by DrLippe** [comment]
just mention me @DrLippe

**Comment by CostasAK** [comment]
It worked! Thanks again. There were 2 closing parenthesis missing I believe. My template file looks like this currently (for anyone looking for this in the future):
```
'use strict';
Options.Triggers = Options.Triggers.concat([
    {
        zoneRegex: /* Area Regex */,
        timeline: `
            # Timeline items
        `,
        timelineTriggers: [
            /* Timeline triggers */
        ],
        triggers: [
            /* Triggers */
        ],
    },
]);
Object.assign(Options.DisabledTriggers, {
    /* Disabled triggers */
});
Object.assign(Options.PerTriggerOptions, {
    /* Trigger options */
});
```
