### ISSUE TITLE
about in raidemulator 

### ISSUE THREAD

**Issue by tssailzz8** [quisquous/cactbot#5142]
In some high difficulty raids, some boss locations are not back logged, so I want to use ARealmRecorded to test some triggers, but in raidemulator 'getCombatants' is overwritten, but I don't want to be overwritten in the copy, so I want to unoverwrite it, i am not good at ts,can anyone help me?

**Comment by tssailzz8** [comment]
I solved it in another way

**Comment by quisquous** [comment]
Sorry for forgetting to come back and answer this question.  I'm glad you were able to solve it.
