### ISSUE TITLE
raidboss: new timeline keyword `loop`

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#5144]
# Motivation / Proposal

I've talked about this a little bit, but wanted to add a new timeline keyword `loop`.  The idea being that I think one of the cumbersome things about timelines is adding extra times as a "loop lookahead".

For example, p1n:
https://github.com/quisquous/cactbot/blob/main/ui/raidboss/data/06-ew/raid/p1n.txt#L71-L80

```txt
# Repeat
360.0 "--middle--" sync / 1[56]:[^:]*:Erichthonios:65F5:/ window 50,50 jump 188.3
370.3 "Aetherflail Left/Aetherflail Right" #sync / 1[56]:[^:]*:Erichthonios:(6DA3|6DA2):/
370.4 "Powerful Fire/Powerful Light" #sync / 1[56]:[^:]*:Erichthonios:(65EC|65ED):/
381.4 "Aetherflail Right/Aetherflail Left" #sync / 1[56]:[^:]*:Erichthonios:(6DA2|6DA3):/
381.5 "Powerful Fire/Powerful Light" #sync / 1[56]:[^:]*:Erichthonios:(65EC|65ED):/
385.9 "--knockback stack--" #sync / 1[56]:[^:]*:Erichthonios:6D15:/
391.2 "Pitiless Flail" #sync / 1[56]:[^:]*:Erichthonios:65E5:/
398.3 "True Holy" #sync / 1[56]:[^:]*:Erichthonios:65E7:/
404.5 "--middle--" #sync / 1[56]:[^:]*:Erichthonios:65F5:/
```

The intention of these blocks is "when you get to 360, jump back to 188.3, and anything you see after 360, show it as if you jumped".  In other words, any time at 360+X would show 188.3+X, for all positive values X.

I think we could replace this with something much more reasonable like the following.

```txt
360.0 "--middle--" sync / 1[56]:[^:]*:Erichthonios:65F5:/ window 50,50 loop 188.3
```

...and have `timeline.ts` handle the "loop lookahead portion" and behave identical to the above portion.

# Questions

As proposed, `loop` can behave exactly as `jump` does, but showing different lookahead.  However, this creates some additional questions.  What if the sync never occurs?  If we hit the same loop ability again with no sync, does it just wrap back around?

I think there are other ways this could behave.  We could just have `360.0 loop 188.3` with no window, and it just jumps back unconditionally as well as does the loop lookahead.  It would sync to anything on the original loop as needed.  (And if that needed a bigger window, we could add one there as well.)

I'm sure there are other ways that this could work too.

Thoughts? cc @JLGarber @valarnin @panicstevenson

**Comment by JLGarber** [comment]
I don't think making `loop` conditional or not really changes that much. If the timeline is on pace, the jump will happen regardless of conditionality. If it's not, now we've jumped to a location that may or may not have syncs nearby, and so the timeline is still out of sync. This would mean we would end up putting wide sync windows at the start of phase loops, which isn't necessarily a bad thing, but it doesn't solve anything. We might as well just put a wide sync at the `loop` point as we currently do for `jump` *anyway*.

That being said, it just now occurred to me that if `loop` behaves conditionally as `jump` does now, a situation that could happen is that users see a timeline displayed at 359, and then when the timeline advances one second, and the sync is missed, suddenly the timeline disappears. That would be less desirable. We could of course fix it with a wide sync window on the keyword line, as we do now, but that might be a decent argument in favor of unconditionality.

**Comment by quisquous** [comment]
> That being said, it just now occurred to me that if `loop` behaves conditionally as `jump` does now, a situation that could happen is that users see a timeline displayed at 359, and then when the timeline advances one second, and the sync is missed, suddenly the timeline disappears.

I think my thought is that it would always show the lookahead regardless of whether it synced or not.  If you got past it, it would keep showing lookahead from where it looped to.
