### ISSUE TITLE
Happy New Year!

### ISSUE THREAD

**Issue by RobertAcedia** [quisquous/cactbot#5171]
No problem, not even playing FFXIV at this time, but just wanted to say Thank you!

Years ago when I did play, I used this & added in my own abilities & when to use them, so as I was tanking I could pop a DC that lasted 30 seconds for a tank buster that was coming in 28 seconds, and since I used it proactively so the CD on being able to use that DC again would be back up 30 seconds (or is that 28 secs) sooner than 99% of most tanks that only popped their DCs for tank busters when they saw the boss start their cast.

From what I've always hear from most tanks in ff14 is a complaint that they do not have enough defencive DCs but me being able to do this made me look damn good.  But it was only the very alert healers who watched when & what abilities I used, they were always very impressed on my timings, but this is how I've always played, just had it so I didn't need to wallpaper the edges of my monitor with Post-Its with attacks, their timings & what the boss did before this & how soon the tank buster would in coming.

This at the time was the 'training-wheels' I needed.

Merry Christmas & Happy New Year!

**Comment by quisquous** [comment]
You're welcome! <333
