### ISSUE TITLE
data.party isn‘t initialized correctly

### ISSUE THREAD

**Issue by panjunan-bit** [quisquous/cactbot#5184]
## Question

sometimes i am in raid and restart ACT，then i find that some trigger cant work correctly，for example I am `healer` but can‘t hear the provoke of `tanker` ，I think `data.party` isn‘t initialized correctly ， how can I do to fix it. I cant quit the raid when I am in `second  phase of p8s`

**Comment by quisquous** [comment]
I suspect this is another instance of https://github.com/OverlayPlugin/OverlayPlugin/issues/60 / https://github.com/ngld/OverlayPlugin/issues/261 and is not a cactbot-specific issue.  I think this can happen both when you restart ACT or if somebody else disconnects.

**Comment by quisquous** [comment]
This should be fixed by https://github.com/OverlayPlugin/OverlayPlugin/pull/226
