### ISSUE TITLE
After ACT update to 3.4.1, oopsyraidsy.html malfunctions

### ISSUE THREAD

**Issue by AllSystemsGo** [quisquous/cactbot#520]
Before ACT 3.4.1 released, I had cactbot (and all the support modules) working perfectly.

However, after updating to ACT 3.4.1, oopsyraidsy.html displays blank lines except for time of the mistake.

I've tried reinstalling ACT and reinstalling the OverlayPlugin. I've tried deleting and readding the overlay. None of these measures have resolved the issue. However, it is worth noting raidboss still works fine.

Attached are screenshots both in preview mode and in an actual raid (eden 3 savage). Note that only the timestamp displays.
![2019-08-06 15_41_46-FINAL FANTASY XIV](https://user-images.githubusercontent.com/4836641/62588499-bb55e400-b87a-11e9-92cc-1bf8f945f816.png)
![2019-08-06 18_02_40-FINAL FANTASY XIV](https://user-images.githubusercontent.com/4836641/62588506-bee96b00-b87a-11e9-9869-49ce7238e509.png)

edited addendum:
There are no errors in the init log.

**Comment by quisquous** [comment]
My apologies for forgetting about this issue.  Is this still happening?  If you click the open devtools button, and then the Elements tab, and expand out the divs, is there text on those lines you just can't see?

**Comment by quisquous** [comment]
Let me know if this is still happening.
