### ISSUE TITLE
about make_timeline

### ISSUE THREAD

**Issue by tssailzz8** [quisquous/cactbot#5200]
in docs it say "ts-node util/logtools/make_timeline.ts -f CapeWestwind.log -s 18:42:23.614 -e 18:49:22.934",in fact i should use ''npx ts-node util/logtools/make_timeline.ts -f CapeWestwind.log -s 2023-01-14T21:02:37.718 -e 2023-01-14T21:12:13.622''

**Comment by quisquous** [comment]
Mmm, I'm not sure.  For me, `ts-node` on its own works and I am not sure what setups require `npx`.

**Comment by valarnin** [comment]
`ts-node` will work if it's installed globally, e.g.:
```bash
npm install -g typescript
npm install -g ts-node
```

Otherwise yes, you need to use `npx ts-node ...`
