### ISSUE TITLE
Eureka plugin not popping NM

### ISSUE THREAD

**Issue by StarkITA** [quisquous/cactbot#5203]
## Description

Hello,

I have noticed that eureka plugin has stopped behaving correctly after last update. Basically, NM do not pop in map when they spawn but only when they die (becoming blue instead of red), and when you leave instance ALL of the NM pop, making a deafening sound

**Comment by xiashtra** [comment]
Duplicate of #5197 and #5198, addressed by [OverlayPlugin/OverlayPlugin/pull/161](https://github.com/OverlayPlugin/OverlayPlugin/pull/161)

**Comment by StarkITA** [comment]
Thanks!
