### ISSUE TITLE
Cactbot callouts on Memory Only option

### ISSUE THREAD

**Issue by shiraiseyuki** [quisquous/cactbot#521]
Is there any way to make cactbot to show the callout texts on screen (like "aoe", "Provoke", "Look away") when my parse mode is on "Memory Only (Not accurate)"?
The timelines do show, but the callout texts doesn't. 

Can anyone help? Thank you in advance!

**Comment by DrLippe** [comment]
Preferably [not](https://github.com/quisquous/cactbot/blob/master/docs/LogGuide.md#dont-write-triggers-against-game-log-lines).
The callouts are written for network log lines, because they are consistent and reliable. For them to work with memory log lines they need to be rewritten and they still might not work at all times.

**Comment by shiraiseyuki** [comment]
@DrLippe Thank you for the response.
Unfortunately I prefer to not use ACT with Network setting, because for some reason, my VPN (Noping), ends up taking a lot of CPU. And somehow, having ACT on Memory only helps reduce the CPU usage greatly.

If its fine, can you tell me how to rewrite them?

**Comment by DrLippe** [comment]
You have to find a log line that correlates to the action you want a trigger for.
For example
```
[timecode] 00:302b:The gravity node uses Forked Lightning.
```
and make a regular expression from it
```js
/ 00:302b:The gravity node uses Forked Lightning./
```
then replace the regex in the trigger files for said trigger and copy the trigger to your `user/raidboss.js`

It's a lot of work to do and it might not pay off

**Comment by shiraiseyuki** [comment]
Yeah, unfortunately I literally need to rewrite everything. Including the savage boss trigger etc.

How about the WinPCap Network? Does it work the same as Memory Only?

(also thank you for explaining about how to rewrite the log!)

**Comment by quisquous** [comment]
Sorry, this is not something that I'm going to do or plan to include.  I think everybody should use network only parsing, and I think there's been some discussion about whether the memory parsing can be removed from the ffxiv plugin.

The timelines may start, but they will not sync properly for you and so I would not trust that.

**Comment by shiraiseyuki** [comment]
I see, I understand, thank you so much for the response!
