### ISSUE TITLE
P4S Bloodrake Issue

### ISSUE THREAD

**Issue by Bayleef153** [quisquous/cactbot#5213]
## Description

During the Bloodrake mechanic, cactbot will always report the mechanic as "DPS Tethers" and "DPS All" even when the correct way to handle the mechanic is different. For instance. Healers/Tanks could have to take tethers, but will still report as "DPS Tethers".

## Additional information

This testing was conducted as the following classes: 
Sage/White Mage/Scholar/Astrologan

Machinist/Blk Mage/Summoner/Samurai

**Comment by wexxlee** [comment]
Never encountered this, at least running it prior to 6.3.  Could you share a log?  If you don't want to upload it here, you can post it to #contribute-logfiles in the ACT_FFXIV discord - just reference this issue.

**Comment by quisquous** [comment]
Yeah, a log file seems necessary here.  It could also be something like https://github.com/ngld/OverlayPlugin/issues/261, where the party data isn't correct.

**Comment by quisquous** [comment]
I'm going to merge this issue with #5184
