### ISSUE TITLE
Raidboss: Another Sil'dhin Subterrane some triggers not appearing

### ISSUE THREAD

**Issue by 1unie** [quisquous/cactbot#5217]
## Description

Most of ASS (normal) triggers work fine but looking into the Raidboss list I've noticed some triggers I've never seen through any of my runs. I believe these include the following, but it could be more that I haven't noticed:
- ASS Fresh Puff 2 Bait ({boss} {dir} {puff} trigger)
- ASS Golden Silver Flame ({loc} trigger)

## Additional information

Playing in French, if that matters.

**Comment by xiashtra** [comment]
Going to need logs to even start diagnosing.  I haven't noticed any issues post 6.3.

**Comment by 1unie** [comment]
Log attached @xiashtra [Uploading Network_26707_20230119.log…]()

**Comment by 1unie** [comment]
Log attached @xiashtra [Uploading Network_26707_20230119.log…]()

**Comment by 1unie** [comment]
Log on Discord: https://discord.com/channels/551474815727304704/551892582855344128/1066101585979117689

**Comment by quisquous** [comment]
Sorry for belated response. If I load this log in raidemulator, I see `Fresh Puff 2 Bait ` but I don't see `Silver Flame`. It looks like the name of the `Hateful Visage` translation is incorrect.
