### ISSUE TITLE
Doubled tts alerts

### ISSUE THREAD

**Issue by PedroMalogor** [quisquous/cactbot#522]
Hello,

i like using the group alerts feature for raidboss so my teammates in discord can hear the alerts too, but cactbot sends them out doubled, every single one, this gets confusing when there are many mechanics called out AND tanks unsing immunites or taunts and shirks at the same time.

i am using the german client and have set the following settings in raidboss.js

  TimelineEnabled: true,
  AlertsEnabled: true,
  TextAlertsEnabled: true,
  SoundAlertsEnabled: true,
  SpokenAlertsEnabled: true,
  GroupSpokenAlertsEnabled: true,

its abit hard to do a test every run cause i have to copy raidboss.js every time out of my act folder and edit it somewhere else cause i cant edit it directly in the act folder. i need a helping hand in the settings pls
small edit: when i use my headset as playback device i get only one callout. using discord bot as playback device gives two callouts

**Comment by quetzalsly** [comment]
In the act sound settings there is an option to choose different tts type, I use the one where it says single voice only and it works great.

**Comment by quisquous** [comment]
Sorry for the extremely belated reply.

Do your teammates hear the doubled sounds, or just you? Curious if the doubled sound is you hearing the discord bot and hearing it locally.  Does this happen if you don't have GroupSpokenAlertsEnabled = true?

If it's awkward to edit cactbot locally, you can copy the folder somewhere else and then redirect the overlay's url to that new folder.  You still need the addon file in the right place inside the ACT directory, but the rest of the files can live wherever (as long as you copy the whole directory).

Also, I want to apologize about the group spoken alerts feature.  They exist, but there's really not triggers that take advantage of them.  It's really not a well-supported feature at the moment in terms of being any different than the normal spoken alerts.  I'm trying to convince @panicstevenson to think about making it more real in the future.

**Comment by PedroMalogor** [comment]
sorry for the late answer. it has nothing to do with the group spken alert feature. it depends on how yukkuri is set. when using my headset as main playback device i get only one callout. when the discord bot is the source i get two callouts in a row

**Comment by quisquous** [comment]
Ah, I see! I haven't sent callouts to a discord bot before, but I would guess you need to mute it for yourself, since you're getting them locally?

**Comment by PedroMalogor** [comment]
its not locally. the others in the discord channel hear the two callouts too

**Comment by PedroMalogor** [comment]
ok, the last month was not good to and  iwas very short on time. before yukkuri i was using act triggers as discord bot. this one worked well and i tried to recreate it today but ended up in error messages so i dumped this one. i also tried out a new yukkuri bot but with the same result as the first one.
then i started agian playing with the settings and for now it seems to work finally. i will give it a hard test the comming week with mount farm/eden.

**Comment by quisquous** [comment]
This last comment makes it sound like you got it working.  If this isn't true, let me know, although I'm not sure there's anything I can do in cactbot to address this.
