### ISSUE TITLE
In dropdown menu, catbot is not an option

### ISSUE THREAD

**Issue by wlad1511** [quisquous/cactbot#523]
I went over the install instructions twice, just to make sure I wasn't doing anything incorrectly. Have both overlayplugins up, dps modules work. But when I go to make a new overlay, when selecting type, catbot is not an option.

Any ideas on what I'm doing wrong?

**Comment by DrLippe** [comment]
Go to the `OverlayPlugin/addons/` folder, right-click the `cactbot.dll` and check if it is blocked.
If so, unblock it.

**Comment by wlad1511** [comment]
I was going to be pretty disappointed in myself if that was the issue. I unblocked the zip file after downloading it, and just checked the .dll and it is not blocked.

**Comment by SunStrider8420** [comment]
Same issue here, just tried to install cactbot, followed the instructions to the letter, restarted multiple times, made sure everything is unblocked and the DLL is present. No option for Cactbot in the drop down menu for creating a new overlay.

**Comment by quisquous** [comment]
What does your folder structure look like on disk? Is there an `ACT directory/OverlayPlugin/addons/CactbotOverlay.dll` file at all?

What do you mean by "both" OverlayPlugins?

**Comment by quisquous** [comment]
Is this still happening?

**Comment by quisquous** [comment]
This is likely similar to #590.  Please let me know if this is still an issue.
