### ISSUE TITLE
Lapis Manalis Albion timeline starting at inappropriate times throughout the dungeon

### ISSUE THREAD

**Issue by xiashtra** [quisquous/cactbot#5230]
## Description

Lapis Manalis Albion timeline starting at inappropriate times throughout the dungeon.

## Additional information

Due to the sync changes in #5222, the Albion timeline now starts any time there is an environmental (map) change throughout the dungeon, including: during the first trash pull before the first boss, after the trash pull after the first boss, the zone transition after the second boss, after the third trash pull before the third boss, etc.

@quisquous

**Comment by quisquous** [comment]
Ah, I see.  They just have way too large of a sync on those lines.
