### ISSUE TITLE
jobs: add dancer technical step

### ISSUE THREAD

**Issue by tsposato** [quisquous/cactbot#525]
Hi,

It seems the Dancer technical step buff is missing from jobs.js.
I would add it myself but struggling to understand how to add the img/data url?
Has someone done this already?

**Comment by tsposato** [comment]
I figured it out and got it done and it is all working now :)
Would we want this in the actual repo?
Could do it for Standard Finish too...

**Comment by quisquous** [comment]
Yes! I would definitely want it in the repo.  Feel free to send a pull request, or I can add it myself.
