### ISSUE TITLE
DSR P6 Trigger for Wroth Flames

### ISSUE THREAD

**Issue by ToshiHitoshi** [quisquous/cactbot#5259]
Is it possible to add a new trigger to identify the starting safe spot for the party to position as they dodge Cauterize from Hraesvelgr (id:  6D3F) and the explosions from the Scarlet Price (fireballs)?

Similar to the earlier trigger to dodge the hallowed wings from Hraesvelgr and Cauterize from Nidhogg, the trigger will have to identify whether Hraesvelgr's X-position is <100. If it is, party will go east, since west is being cauterized. If the X-position is >= 100, then party will go west since either middle or east is being cauterized.

At the same time, 9 fireballs are being spawned in the following locations (I believe the npcBaseID are all 13238):
Middle: (x,94), (x, 100), (106,106)
Northeast/Northwest: (x,81), (x,87), (x,93)
Southeast/Southwest: (x, 107), (x, 113), (x,119)
The fireballs will spawn in sets of 3 in the order of either Middle, Northwest/Northeast, then Southeast/Southwest or Middle, Southeast/Southwest, then Northwest/Northeast. The safe spot is based on where the last set of fireballs spawn and can be determined after the 2nd set appears (i.e. will always be either North or South).

Hoping for some help to create a trigger that can call an intercardinal quadrant by combining both sets of conditions. I tried and failed miserably with my barebone knowledge of coding.

Thanks for any help you can offer!

**Comment by sfenix-dev** [comment]
Hi I have a makeshift user trigger from 6.1 that might still work, but it would need some serious clean up to be committed so I'll just post it here:

```js
{
  id: 'user GreatWyrmsTethers',
  netRegex: NetRegexes.tether({ id: ['00C4','00C3','00C2'] }),
  promise: async (data, matches, output) => {
    if (!data.tetherMatches) {
      data.tetherMatches = []
    }

    data.tetherMatches.push(matches);

    if(data.tetherMatches.length > 6) {
      return;
    }

    if (data.tetherMatches.length > 5) {
      data.initialTethers = [...data.tetherMatches];
      data.hraesvelgrId = data.initialTethers.filter(x => x.target === "Hraesvelgr")[0].targetId;
    }
  }
},
{
  id: 'user WrothFlamesScarlett',
  netRegex: /^(?<type>(?:03))\|(?<timestamp>(?:[^|]*))\|(?<id>(?:[^|]*))\|The Scarlet Price\|(?<job>(?:[^|]*))\|(?<level>(?:[^|]*))\|(?<ownerId>(?:[^|]*))\|(?<worldId>(?:[^|]*))\|(?<world>(?:[^|]*))\|(?<npcNameId>(?:[^|]*))\|(?<npcBaseId>(?:[^|]*))\|(?<currentHp>(?:[^|]*))\|(?<hp>(?:[^|]*))\|(?<currentMp>(?:[^|]*))\|(?<mp>(?:[^|]*))\|(?:[^|]*\|){2}(?<x>(?:[^|]*))\|(?<y>(?:[^|]*))\|(?<z>(?:[^|]*))\|(?<heading>(?:[^|]*))\|/,
  promise: async (data) => {
    if (data.hraesvelgrId && data.scarletMatches && data.scarletMatches.length === 5) {
      const hraes = await callOverlayHandler({
        call: 'getCombatants',
        ids: [parseInt(data.hraesvelgrId, 16)],
      });
      data.wrothFlamesHraes = hraes;
    }
    return true;
  },
  alertText: (data, matches, output) => {
    if (!data.scarletMatches) {
      data.scarletMatches = [];
    }
    data.scarletMatches.push(matches);

    if (data.scarletMatches.length > 5 && !data.orbs2nd) {
      let orb1 = data.scarletMatches[3];
      let orb2 = data.scarletMatches[4];
      let orb3 = data.scarletMatches[5];

      data.orbs2nd = [orb1, orb2, orb3];

      let safeMarkers = null;
      let orbAverageX = (parseFloat(orb1.x) + parseFloat(orb2.x) + parseFloat(orb3.x))/3;
      let orbAverageY = (parseFloat(orb1.y) + parseFloat(orb2.y) + parseFloat(orb3.y))/3;

      data.orbOn2nd = [orbAverageX, orbAverageY];

      // 87,87 = 4 marker
      // 113,87 = 1 marker
      // 113,113 = 2 marker
      // 87,113 = 3 marker

      if (orbAverageX == 87 && orbAverageY == 87) {
        safeMarkers = [2,3];
      }
      if (orbAverageX == 113 && orbAverageY == 87) {
        safeMarkers = [2,3];
      }
      if (orbAverageX == 113 && orbAverageY == 113) {
        safeMarkers = [1,4];
      }
      if (orbAverageX == 87 && orbAverageY == 113) {
        safeMarkers = [1,4];
      }

      data.safeMarkers = safeMarkers;

      if (data.wrothFlamesHraes && data.wrothFlamesHraes.combatants && data.wrothFlamesHraes.combatants[0]) {
        const hraes = data.wrothFlamesHraes.combatants[0];
        const hraesX = hraes.PosX;
        const hraesY = hraes.PosY;

        if (hraesX > 100) {
          data.safeMarkers = ([3,4]).filter(v => data.safeMarkers.includes(v));
        }

        if (hraesX < 100) {
          data.safeMarkers = ([1,2]).filter(v => data.safeMarkers.includes(v));
        }

        if (data.safeMarkers.length > 1) {
          data.safeMarker = Math.max(data.safeMarkers[0], data.safeMarkers[1]);
        } else {
          data.safeMarker = data.safeMarkers[0];
        }

        if (hraesY < 87 || hraesY > 113) {
          return "Go to " + data.safeMarker;
        }
      }
      return "Look for hraes, go to " + data.safeMarkers[0] + " or " + data.safeMarkers[1];
    }
  }
}
```

It was a while ago, but from what I can remember the Hraesvelgr instance that uses cauterize is the same as the boss, so I save the ID of it from when tethers happen - the source and target are switched for some reason here.

It then grabs the average position of each set of orbs and then uses that to figure out where is safe. You'll have to change the callouts since it currently calls out a marker number:

4 = Northwest
1 = Northeast
2 = Southeast
3 = Southwest

Then it restricts based on whether or not Hraes is east or west.

**Comment by ToshiHitoshi** [comment]
Thank you!!

I'm pretty sure you're right - Hraesvelgr that uses cauterize is the same as the boss (at least from what I can tell from my logs). I was able to test the user trigger in raidemulator and the orb callouts are working for me (specifically, it'll say  return "Look for hraes, go to " + data.safeMarkers[0] + " or " + data.safeMarkers[1];).

Unfortunately, I'm having trouble getting the trigger to locate Hraesvelgr, and I'm not sure which part of the code is not being executed properly on my end. Given that the orb callouts are working, I'm inclined to think it has to do with data.hraesvelgrId not working properly, but I'm not entirely sure. I inserted an alarmtext under the part of code where it says:

```
    if (data.tetherMatches.length > 5) {
      data.initialTethers = [...data.tetherMatches];
      data.hraesvelgrId = data.initialTethers.filter(x => x.target === "Hraesvelgr")[0].targetId;
      alarmText: 'test';
    }
```

but it didn't go off.

**Comment by sfenix-dev** [comment]
You can try grabbing his ID in a more sensible way (I had other stuff I cut from tethers for posting here).

Try replacing 'user GreatWyrmsTethers' with this:

```js
{
      id: 'user DSR Great Wyrmsbreath',
      type: 'StartsUsing',
      netRegex: { id: ['6D34','6D34'], source: 'Hraesvelgr' },
      run: (data, matches) => data.hraesvelgrId = matches.sourceId,
}
```

**Comment by ToshiHitoshi** [comment]
Thanks again!!

Turns out I was wrong about data.hraesvelgrId not executing properly. I had to instead remove the if statement contained within:
```
  promise: async (data) => {
    if (data.hraesvelgrId && data.scarletMatches && data.scarletMatches.length === 5) {
      const hraes = await callOverlayHandler({
        call: 'getCombatants',
        ids: [parseInt(data.hraesvelgrId, 16)],
      });
      data.wrothFlamesHraes = hraes;
    }
    return true;
  },
```
Everything seemed to work after. I'll close the issue now.
