### ISSUE TITLE
Option to select the TTS language separately ?

### ISSUE THREAD

**Issue by Snsei987** [quisquous/cactbot#527]
Would it be possible to add an option to have the timelines in one language and the TTS in another ?

**Comment by quisquous** [comment]
What's the use case here? I guess I figured that most folks who are using one language what everything the same.

**Comment by Snsei987** [comment]
Well, as I try to read guides and run the raid sometimes with pugs, I would like to have the timeline in english to know exactly what ability they are making the call for etc...

And I would also like to the the tts in my native language as I will react faster to it.

Maybe make an option `Options.TTSLanguage` which is equal to `Options.Language` by default ?
