### ISSUE TITLE
Remove 6.1 resources.

### ISSUE THREAD

**Issue by Bing-su** [quisquous/cactbot#5270]
## Summary

Tomorrow(Feb 14) is Korean server 6.2. So, I tried to remove pre-6.2 resources, but it's complicated..

**Comment by quisquous** [comment]
When is maintenance for this? Can I go ahead and land #5272?

I think once that has landed, we can remove the special 61 zones from raidboss and the gen_zone script.  However, there's no rush on doing that because the new zones have new zone ids and so it will use the newer files automatically.

**Comment by Bing-su** [comment]
SEOUL, South Korea
10:00	Tue, Feb 14 2023
18:00	Tue, Feb 14 2023

NEW YORK, United States, New York
20:00	Mon, Feb 13 2023
04:00	Tue, Feb 14 2023


But I think it's okay to do it right now. it's morning here.
