### ISSUE TITLE
Fishing UI lacking documentation

### ISSUE THREAD

**Issue by Tataru-Taru** [quisquous/cactbot#528]
So I recently tried to use the Fishing UI, but there doesn't seem to be a colour guide. Does the Yellow or Green mean the tug type?

The readme only states it shows the times when things can be hooked.

Also do you build up your own database running it for timings, or is there a file I am supposed to have in which it has them saved?

Would it be possible to get more information about this plugin added to the FAQ/Readme to explain all the functions.

**Comment by Pirate144** [comment]
Tugs are color coded, honestly don't remember which is which, think green is light, yellow medium, and red super big ones?

And yes you fill out your own database as you fish, would be cool if there was like an optional opt-in database sharing thing you could upload to and download from, but don't believe there is currently.

**Comment by quisquous** [comment]
Yeah, sorry there's not much information on the fishing plugin.  I'll add some documentation for this.

**Comment by FromTheGrayve** [comment]
So glad this was asked, I've been trying to figure out what the colors meant!
