### ISSUE TITLE
Is there a way to disable all built-in triggers in a certain area in Raidboss?

### ISSUE THREAD

**Issue by Souma-Sumire** [quisquous/cactbot#5282]
(Translated from Chinese, Using translation software, Sorry for the language problem)

I have written many user.js files covering many instances, but every time Cactbot does an update I have to manually go through all instances to manually turn off all new triggers, otherwise it disrupts my existing running environment, making it hard for me to guarantee their stability. Is there a way to disable all triggers instead of going through all IDs to disable them? Thanks.

**Comment by quisquous** [comment]
If you use the cactbot config ui, in ACT > Plugins > Cactbot Config > Raidboss, you can change "Default alert output" to be "Disabled".  These triggers will still run though (and will modify `data), but will not show extra output.  I don't know if that is enough for the triggers you have written.

I am not sure if this is enough for your use case.  If you want to add a developer-only option to fully disable triggers (no output, no code changes), you would need to write a PR and modify `ui/raidboss/raidboss_config.ts` to add an additional option there as well.  This would make it possible to globally disable all triggers fully, but you would have to write this code.

**Comment by Souma-Sumire** [comment]
Sorry for my unclear expression. I want only the default triggers for the specified zoneId to be disabled, without affecting the rest of the code running. I envision something like this.
```
// imagine 1
Options.Triggers.push({
  zoneId: ZoneId.TheOmegaProtocolUltimate,
  disableDefaultTrigger: true,
});

// imagine 2
Options.DisableDefaultTriggersZoneIds.push(ZoneId.TheOmegaProtocolUltimate);
```

**Comment by quisquous** [comment]
Do you need the triggers to be fully disabled (i.e. not doing `run` or modifying `data`) or do you just want them to not show up in alerts?

If it's that you don't want them to show up, I think #2103 is asking for the same thing.  It'd be nice if the config ui could let you set defaults for an entire section (expansion / zone / etc) rather than only on individual triggers.

I think in any case, this is a "if you want it, you're going to need to send a PR".

**Comment by Souma-Sumire** [comment]
OK, I'll keep it as it is.
When I'm competent enough to understand the project, I'll submit a PR.
