### ISSUE TITLE
Can't disable sounds or enable tts.

### ISSUE THREAD

**Issue by inarahana** [quisquous/cactbot#529]
I've followed the instructions to edit raidboss.js, and have done so in both cactbot>user and ui>raidboss but the sounds are still constant.

**Comment by reforge123** [comment]
I am having the same issue, I don't know how to enable tts instead of the noises

**Comment by inarahana** [comment]
There are two files called raidboss.js, in separate folders. I don't know which one worked so I edited them both, it seemed they weren't saving when I was exiting for whatever reason so I made a copy of both of them on my desktop, edited them and replaced them and it worked.

**Comment by Huynhs** [comment]
You should only need to edit cactbot\user\raidboss.js.  Make sure to uncomment the line
`Options.AlertsLanguage = 'en';`
and that the tts setting is enabled
`Options.SpokenAlertsEnabled = true;`

**Comment by quisquous** [comment]
If you make a file called **cactbot/user/raidboss.js** you only need to add the line `Options.SpokenAlertsEnabled = true;` to have tts.

Let me know if that doesn't work.

**Comment by reforge123** [comment]
ever since the recent update i lost tts sound even after editing the file in notepad :( I tried to do your fix too no luck just with this recent update
