### ISSUE TITLE
yeah the so called "New" instructions for act are just as useless as the old.

### ISSUE THREAD

**Issue by shackloan** [quisquous/cactbot#5290]
## Description

Description of the issue you're seeing.

## Additional information

If available, please include any logs or screenshots depicting the issue you're experiencing.

**Comment by quisquous** [comment]
Sorry, I don't know what you are asking about.  If you are having setup issues, I'd recommend going to the ffxiv act discord and asking them there: <https://discord.gg/hK523Pj>
