### ISSUE TITLE
innocence oopsyraidy error?

### ISSUE THREAD

**Issue by majesticuni** [quisquous/cactbot#530]
Hi im getting this at the bottom of the overlayplugin.dll tab, anyway to fix this?

8/9/2019 11:27:25 AM: Info: Oopsy: BrowserConsole: Unexpected JSON from innocence-ex.js, expected a triggers (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/cactbot/ui/oopsyraidsy/oopsyraidsy.js, Line: 1010)
"

**Comment by quisquous** [comment]
I think f5d91d8 should fix this.  Let me know if the next release doesn't work.
