### ISSUE TITLE
Compiling 1B overhead markers

### ISSUE THREAD

**Issue by JLGarber** [quisquous/cactbot#534]
I'm thinking of going through the repository and identifying all the known 1B log lines so they can be dropped into a single file for easy reference. In four-player content it's usually not too bad to isolate the 1B lines and figure things out, but in 24-player content it's not always simple. It (seems to me it) would be nice to just be able to search a log for a given marker type rather than sorting through all 1B lines.

I envision this as a .js-formatted text file similar to the [triggers readme](https://github.com/quisquous/cactbot/blob/master/ui/raidboss/data/triggers/README.txt). A sample would be something like this:

```
// 0028
// Earth Shaker
// Damage cone--don't overlap and don't point at other players
// Seen in Sephirot EX, St Mocianne (HARD) and Dun Scaith, among others.
/ 1B:........:(\y{Name}):....:....:0028/
```

Obviously this isn't the final revision on the formatting, but it should be a good baseline. Is this something that might be worth doing, or would it be useful to anyone if I take the time to do it?

**Comment by quisquous** [comment]
Seems reasonable! What about adding it to the log guide?https://github.com/quisquous/cactbot/blob/master/docs/LogGuide.md#1b-networktargeticon-head-markers

**Comment by JLGarber** [comment]
That makes sense. Should I plan to append a section at the end, maybe after[ Future Network Data Science](https://github.com/quisquous/cactbot/blob/master/docs/LogGuide.md#future-network-data-science)? I feel like this would enable people to find it if they need to, rather than having one incredibly outsized chunk of what's really reference material in-line.

**Comment by quisquous** [comment]
I think there's a table of contents, so it'd be fine to add a large section.  The `15` log line has a huge table an explanation in it, and so another table here seems perfect to me.

**Comment by JLGarber** [comment]
Fair enough, I'll poke at that as I have time.

**Comment by JLGarber** [comment]
I've pushed an [initial table to a personal branch](https://github.com/JLGarber/cactbot/blob/Log-Line-table-goodness/docs/LogGuide.md#1b-networktargeticon-head-markers) for testing and review. Let me know what suggestions you have after seeing it in-line.

**Comment by panicstevenson** [comment]
@JLGarber looking at your table, I think the 1-4 sword mechanic from The Twinning is the same one used in Ravana EX (I don't remember if it's in Normal as well) if you're looking for another sample to see if they're consistent (or even the same address)

**Comment by JLGarber** [comment]
Mm, so they are. I don't have the ilevel to survive EX solo to see that, but it's definitely the same marker on Hard, at least for sword 1.

**Comment by quisquous** [comment]
Looks great!

**Comment by JLGarber** [comment]
Thank you, I'm happy with how this is working out. I'll probably be submitting that pull request early next week with the markers that Catbot currently references. The consistency levels, low or high, of the various different marker types are astounding!

**Comment by JLGarber** [comment]
Now that my additions to the guide have been added, I think it's fine to close this. As usual, it's on the list for further improvements, etc etc.
