### ISSUE TITLE
Incorrect timeline in DSR (game in other language)

### ISSUE THREAD

**Issue by ne0dym7** [quisquous/cactbot#5373]
I am currently playing FFXIV in French for fun. I am also progging Dragonsong's Reprise Ultimate, and noticed that cactbot timeline is displaying incorrectly in at least 2 phases of the encounter. The alerts, however, are correct.

P4 or Eyes phase: timeline does not show.
Intermission + P5 or Thordan 2 phase: haven't paid close attentinon, but I believe it also does not show.
P6 or Double Dragons phase: shows the timeline of P4.

The image below highlights the wrong timeline and correct alert.
Would appreciate some insight, thanks

![230428-231941](https://user-images.githubusercontent.com/61278460/235279374-4beeab42-a2c8-4140-b1e2-760bf744488c.png)

**Comment by quisquous** [comment]
Probably there is a translation issue somewhere. If you provide a network log in French, I can take a look.

**Comment by ne0dym7** [comment]
Thanks for the reply, this is the ACT log from our Wednesday session. I was taking a look yesterday and indeed the timeline also doesn't show in intermission + P5.
[Network_26807_20230426.zip](https://github.com/quisquous/cactbot/files/11361579/Network_26807_20230426.zip)

**Comment by quisquous** [comment]
I think #5375 should fix this.  Reading through the timeline, if there's no sync in phase 4, then the further syncs will be missed.  Let me know if this doesn't work after the next release.

**Comment by ne0dym7** [comment]
Thanks!! Appreciate the work ^^
