### ISSUE TITLE
Questions related to the setterFunc function

### ISSUE THREAD

**Issue by Souma-Sumire** [quisquous/cactbot#5383]
_Text is generated by translation software_

I tried to change the config property but the `setterFunc` didn't work.
I tried to build the source code and add console.log to the existing setterFunc and he was called normally.
Is it only the built-in triggers that can use that. Or is this an oversight?

## Demo
```
Options.Triggers.push({
  id: "test 20230507",
  zoneId: ZoneId.MatchAll,
  config: [
    {
      id: "test setterFunc",
      name: { en: "test setterFunc" },
      type: "string",
      default: "aaa",
      // not working
      setterFunc: (value) => {
        console.log("setter", value);
        return "setter working";
      },
      // does getter exist? i don't know
      getterFunc: (value) => {
        console.log("getter", value);
        return "getter working";
      },
    },
  ],
  triggers: [{ id: "must be an valid trigger otherwise the config panel will not display", infoText: "" }],
});
```
![image](https://user-images.githubusercontent.com/33572696/236645139-21da85d9-8c69-41d0-a6ec-340fb57d614e.png)

**Comment by quisquous** [comment]
Hmm, this is working for me.  For what it's worth, there is nothing different in this case with user triggers and built-in triggers.  They all go through the same code.

 If I load in this user script I see this output from the raidboss overlay:
```
Loading id test 20230507
setter aaa
```

Did you reload ACT or raidboss to make sure the script loaded? If you turn on `Show developer options` and `Enable debug mode` (for raidboss) do you see `Loading id test 20230507`?

Sorry that I did not write documentation about this yet.  There is no getter function.  This is the best explanation that exists in the code: https://github.com/quisquous/cactbot/blob/main/resources/user_config.ts#L69-L78

The data flow here is this:
* evaluate the `default` as the starting value (either a direct value or a function)
* this default value is shown in the config ui if a value hasn't been set
* any overrides from the config ui are stored in the OverlayPlugin json file
* when loading an overlay (e.g. raidboss, but also config), the OverlayPlugin json file is loaded and any values in there will override the default value
* these values are stored on `Options` by id (for most options) or in `data.triggerSetConfig` for trigger set options
* for other overlays, `setterFunc` can also be applied to turn one option into multiple options or to do a data conversion or something like that, but probably isn't necessary most of the time

**Comment by Souma-Sumire** [comment]
Thank you for the explanation. I believe I misunderstood the timing of when this function is executed.

Now I understand that setterFunc is not executed in the config UI. Instead, it is called when attempting to read data.triggerSetConfig.testConfig in Raidboss (perhaps I thought of it more like a getter?).

For example, in this demo, I would actually get "ccc".

```
Options.Triggers.push({
  id: "test 20230508",
  zoneId: ZoneId.MatchAll,
  config: [
    {
      id: "testConfig",
      name: { en: "test 20230508" },
      type: "string",
      default: "aaa",
      debug: true,
      setterFunc: (value) => {
        console.log("setter", value); // print: "setter bbb" (modify to bbb in the config ui)
        return "ccc";
      },
    },
  ],
  triggers: [
    {
      id: "20230508 setterFuncTest trigger",
      netRegex: NetRegexes.echo({ line: "setterFuncTest", capture: false }),
      run: (data) => {
        console.log("testConfig:", data.triggerSetConfig.testConfig); // print: "testConfig: ccc"
      },
    },
  ],
});
console.log("test.js loaded");
```

I think perhaps we can close this issue and update the incorrect title?

**Comment by quisquous** [comment]
It's a "setter" in the sense that when loading process writes the value from default/saved json into the options/triggerset config, it goes through setter func when writing.  It's not a getter in the sense that anything accessing this value goes through the indirection of the function.

And yeah, if your `setterFunc` always returned `ccc` then it would ignore anything from the config ui and it would always be `ccc` in a trigger.

If you feel like this is answered, I think this is fine to just close as-is.

**Comment by quisquous** [comment]
Thanks for all the questions!

**Comment by Souma-Sumire** [comment]
Sorry for the interruption, but I have one more question.
Regarding the consideration of why the config UI does not run the setterFunc, in my opinion, it might be necessary to do so. For example, if I need the user to provide a string that meets certain formatting requirements, if I can use the setterFunc in the config UI, I can immediately validate the user's input. If the format does not meet the requirements, I can inform the user immediately and revert it to the default value. If I cannot use the setterFunc, the user would save a string in the JSON file that cannot be properly used at runtime, and the config UI would only display that string. Only when the actual trigger is executed and fails the validation, would it use the default value or show an error.

In my practice, I expose a large number (dozens) of different sorting rules for users to input as arrays in string format. I want them to be correctly separated by commas. Otherwise, it will revert to the default value after saving and refreshing, so that the user is aware of it. Without a way to perform checks, it would be difficult to detect minor input errors.
![image](https://user-images.githubusercontent.com/33572696/236702239-7a97e346-fa2a-47a0-9683-a5dbc92c87c4.png)

Perhaps another new feature could be proposed to have a callback function for validating the legality of the config when it is a string.

**Comment by Souma-Sumire** [comment]
> Thanks for all the questions!

Thank you equally for the detailed response and for your long-term dedication to the development and maintenance of this project.

**Comment by Souma-Sumire** [comment]
I think I should submit a pull request

**Comment by quisquous** [comment]
> Regarding the consideration of why the config UI does not run the setterFunc, in my opinion, it might be necessary to do so. 

I thought about this, but the setterFunc is not there to correct or validate data, it's there to transform data, if that makes sense.  To turn one piece of information into others.  I think it's the wrong data flow to have it go back and update what the config ui would see, because then the user input and the setterFunc could "fight".

I suspect you have the same idea given that you said a PR, but I think a separate function to validate (and return an error string?) would be better here.
