### ISSUE TITLE
TOP Party Synergy / Omega dodge callouts incorrect

### ISSUE THREAD

**Issue by bearsandchairs** [quisquous/cactbot#5412]
It seems the callouts for Party Synergy are incorrect when identifying the safe spots for Omega M/F before breaking off for tether positions. Haven't changed any of the settings and has only happened since 6.4 dropped.

**Comment by shingonati0n** [comment]
Confirming this, safe spots for M/F are being called out incorrectly.

**Comment by DeadeyeN** [comment]
Confirming this.

**Comment by quisquous** [comment]
This should be fixed with https://github.com/OverlayPlugin/OverlayPlugin/pull/216 and the new OverlayPlugin 0.19.20 release.
