### ISSUE TITLE
Organizing Timelines & Triggers

### ISSUE THREAD

**Issue by Snsei987** [quisquous/cactbot#542]
Hello, do you think it would be possible to organize the timelines & triggers in sub-folder ?

Like, now it's 

```
triggers/a11s.js
triggers/a12s.js
triggers/byakko-ex.js
triggers/cape_westwind.js
```

and there are tons of files but wouldn't it be easier to find a fight with subfolder ?

```
triggers/eden/e1s.js
triggers/omega/o1s.js
triggers/SB_extremes/byakko-ex.js
triggers/SB_raids/royal_city_of_rabanastre.js
```

**Comment by quisquous** [comment]
Yeah, it's definitely gotten to the point where this is overwhelming.  I was going to add the last couple of dungeons and then rearrange everything.

I'm thinking a top level set of directories like 02-arr,03-hw,04-sb,05-shb sort of thing to indicate what expansion it's from, and then underneath each doing trial, dungeon, raid, alliance.  How does that sound?

**Comment by Snsei987** [comment]
Yes sounds good, something like that ?

```
02-arr/raid/
02-arr/alliance/
02-arr/dungeons/
02-arr/trials/
```
