### ISSUE TITLE
Jobs feature issue

### ISSUE THREAD

**Issue by SherlockKZ** [quisquous/cactbot#5429]
Not sure it's act or cactbot issue, when I activated JOBS function, it does not work at all. Error msg is shown as:

Info: buff: BrowserConsole: TypeError: Component is not a constructor (Source: file:///XXXXXXX/Plugins/ACT.OverlayPlugin/cactbot/ui/jobs/jobs.bundle.js, Line: 2506)

**Comment by quisquous** [comment]
I saw this briefly before the plugin update for cactbot, where the plugin was sending `None` for a job but cactbot was looking for `NONE`.  Probably the plugin needs to send `NONE` to match here.  cc @Echoring

**Comment by Echoring** [comment]
Sorry for these busy days. I haven't met the same issue; my jobs module just working fine. I'm also not familar with how the plugin send data to job module, and cannot locate this error. cc @MaikoTan
