### ISSUE TITLE
Fields of Glory (Shatter)

### ISSUE THREAD

**Issue by Scylune** [quisquous/cactbot#5430]
Hi :)

There's 2 lines of text/speech to swap @ Fields of Glory (Shatter)

Text/Speech "Big Ice, North" = Ingame "Southwest"
Text/Speech "Big Ice, Southwest" = Ingame "North"

I didn't find where it can be swapped in mine. Or maybe users can't.

Thank you all !

**Comment by quisquous** [comment]
Previously, Shatter had 4 big tomeliths, A1-A4.  All the triggers are just on text like `The icebound tomelith A4 activates and begins to emit heat`.  If you can mouseover the map and tell me what the tomeliths are labelled now and where they are, I can update this.

**Comment by Hinalover** [comment]
Southwest
![image](https://github.com/quisquous/cactbot/assets/10355909/e22903a5-125b-4413-8559-3c36b0cf2117)
![image](https://github.com/quisquous/cactbot/assets/10355909/801c0280-cefc-47b2-9a25-dbf79831c9e9)
Center:
![image](https://github.com/quisquous/cactbot/assets/10355909/5025be72-5e83-44b7-906f-d989e36218ea)
![image](https://github.com/quisquous/cactbot/assets/10355909/0ec9e727-80e5-410e-a0f5-01e06fd08443)
North
![image](https://github.com/quisquous/cactbot/assets/10355909/546ff620-5319-43a4-9c26-1dfcf595f481)
![image](https://github.com/quisquous/cactbot/assets/10355909/1a54f56a-8ac2-4203-b679-ddb18690342b)
Southeast:
![image](https://github.com/quisquous/cactbot/assets/10355909/81a43a8c-a963-4b4d-8b77-c933332553f6)
![image](https://github.com/quisquous/cactbot/assets/10355909/9adad270-082f-4f7f-a063-be02a238f484)
