### ISSUE TITLE
oopsy: guide mistake? 

### ISSUE THREAD

**Issue by wexxlee** [quisquous/cactbot#5431]
On lines 89-91 of Oopsyraidsyguide.md:

```
**soloWarn** and **soloFail**:
The opposite of **shareWarn** and **shareFail**
in that they are trigger when something should be taken alone but hits multiple people.
```
The given description seems to be the same as `shareWarn` and `shareFail` - multiple people share damage that should be taken alone.  Based on actual usage though, it seems that `soloWarn/soloFail` are intended to catch when damage is supposed to be shared but a given player does not take damage.  

Happy to submit a quick PR if warranted, but wanted to clarify first.

**Comment by quisquous** [comment]
Yeah, that's exactly it.  `shareWarn` and `shareFail` are mistakes if multiple people are hit (e.g. spread markers).  `soloWarn` and `soloFail` are mistakes if only one person is hit (e.g. stack markers).
