### ISSUE TITLE
raidboss: start timelines from InCombat lines instead of engage/autos

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#5440]
From a random idea in: https://github.com/quisquous/cactbot/pull/5432#discussion_r1208169275

This seems like a better way to start timelines.  It'd also let us start only the timelines where it makes sense to do this, as we can't do this for dungeons or door bosses or bozja style zones.

**Comment by quisquous** [comment]
@JLGarber, what do you think about switching things over to using this, both going forward and going back to old timelines as well?

```diff
-0.0 "--sync--" sync /:Engage!/ window 0,1
+0.0 "--sync--" sync / 104:[^:]*:1($|:)/ window 0,1
```

There's been some conversation about Ravahn maybe adding these lines into the ffxiv plugin itself for fflogs, and we can switch if that ever happens.  I filed https://github.com/ravahn/FFXIV_ACT_Plugin/issues/308 for this.

**Comment by JLGarber** [comment]
Yes, that seems reasonable. Any content where we can't start from in-combat status should have zone seal lines.

**Comment by quisquous** [comment]
I do think this seems pretty good in p9s/p10s imo.  If somebody feels up for it, we could consider going back and touching up older timelines (and make_timeline) to do this.
