### ISSUE TITLE
Cactbot bar stops progressing if the game is focused

### ISSUE THREAD

**Issue by Jolkien** [quisquous/cactbot#546]
So I installed cactbot on my wife's computer and running the game window borderless or fullscreen when the game is NOT focused the bars works properly, if she actually plays the game the bars stop but the ''toc'' alert etc works but the green text doesn't show up either. Any idea what could cause this ? Her DPS overlay (Mopi Mopi) keeps working when she's playing. I have no clue what could cause this.

**Comment by quisquous** [comment]
Is it related to issue #309?

**Comment by Jolkien** [comment]
I've put a frame limiter to 60 FPS in Radeon settings I will keep you posted

**Comment by quisquous** [comment]
Did that help? Are you still having this issue?

**Comment by quisquous** [comment]
Hi, is this still happening?

**Comment by quisquous** [comment]
I'm going to close this old issue.  Please let me know if this is still happening and we can debug further.
