### ISSUE TITLE
Add more raidboss testing

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#548]
There's a bunch of common things that could be checked with automatic (python?) testing that would prevent obvious bugs:

* multiple entries of the same type in the same dict (two `regex` instead of one `regex` and one `regexFr`) or multiple `triggers` entries
* missing timeline files
* trigger and timeline missing from manifest file
* timeline triggers translated (they never should be)
* translation block exists, but doesn't translate all the syncs / texts

This should probably also apply to oopsy files as well.

**Comment by panicstevenson** [comment]
A very simple test can be made for checking the manifest integrity: making sure all the files listed in both the [raidboss manifest](https://github.com/quisquous/cactbot/blob/master/ui/raidboss/data/manifest.txt) and the [oopsyraidsy manifest](https://github.com/quisquous/cactbot/blob/master/ui/oopsyraidsy/data/manifest.txt) exist, and make sure the opposite is true as well: everything in the actual data/ folders exist within their respective manifest files.

The test can also be added to the [Travis CI run](https://github.com/quisquous/cactbot/blob/master/.travis.yml).

It should be a relatively easy test to add; I can add it if no one else gets around to it, but, if someone wants to pick it up, it's a good first task to get your feet wet.

**Comment by quisquous** [comment]
Yes yes, I definitely intended all of these thoughts to be part of travis ci!

**Comment by quisquous** [comment]
Probably should also add all the runtime checks from: https://github.com/quisquous/cactbot/blob/master/ui/raidboss/popup-text.js#L47

**Comment by quisquous** [comment]
Another random testing thought that would be nice is that all the keys in a trigger should be listed in the order that they run.  That's a little obnoxious for linting, but at the same time, I think it would add a lot of readability and consistency.

**Comment by quisquous** [comment]
I think this is mostly done.
