### ISSUE TITLE
P9S Swinging Kick question

### ISSUE THREAD

**Issue by mooondark** [quisquous/cactbot#5482]
Hi everyone,
I finally started to raid this tier and I have a small question: are the Swinging Kicks called in P9S ? I think yes if I look at p9s.ts, but I did several tries, and it never shows up.
The In/Out & partners stack/protean at the beginning of the fight are also not called. Maybe it's a language issue (since I play in FR) ?

I put the log file, if it can help.

Thx.

[Network_26809_20230601.zip](https://github.com/quisquous/cactbot/files/11632414/Network_26809_20230601.zip)

**Comment by xiashtra** [comment]
I believe your issues are due to the FR translation being incomplete.  For instance, the boss appears to be named `Cocyte` in your log (FR), whereas it is `Kokytos` in EN.  The current (incomplete) FR translation was added/updated in #5478 by @Akurosia; they might be able to provide more assistance.

**Comment by Akurosia** [comment]
Ok this is the second time this happend. There is a strange bug in my translation code that ignores the fr language and uses german instead and i dont get why.
@mooondark could you check p9s and p10s translations? (just a rough estimate of things that dont look french would be helpful to get out a quick fix

**Comment by xiashtra** [comment]
At a glance, I strongly suspect the p9n will be wrong also.  I wouldn't be surprised if everything from this patch needs another pass-through.

**Comment by mooondark** [comment]
@Akurosia, after a quick check (p9s-p12s), only p9s boss name is incorrect. Everything else is in French. And @xiashtra is right, p9n is also wrong 😋
I'll make a PR to correct those two.

Thanks mates !

**Comment by Akurosia** [comment]
ok at least i found the issue, its order of search index that created this issue. There is a skillname called "Kokytos" (0x6C27) which was checked first
