### ISSUE TITLE
No Callouts For Normal Golbez Trial

### ISSUE THREAD

**Issue by snowfi6916** [quisquous/cactbot#5497]
It doesn't make sense to me that there's callouts for Golbez EX but not Golbez normal. I just did the normal one and there's no callouts at all. Is there a reason why it's not in there yet? Thanks.

**Comment by Akurosia** [comment]
Its simple, no one made any trigger/timelines for normal mode (as the demand for normal mode is usually low) 
A list with the covereage can be found here: https://quisquous.github.io/cactbot/util/coverage/coverage.html

**Comment by snowfi6916** [comment]
Okay thanks.
