### ISSUE TITLE
P9S - Add additional Levinstrike timers

### ISSUE THREAD

**Issue by crash0zero** [quisquous/cactbot#5517]
## Summary

Would it be possible to add extra alerts/TTS call-outs to P9S for Levinstrike ?  Cactbot already notifies you what your number is, if you get one of the even numbers.  Since the way the mechanic is built forces the order you bait jumps and soak towers, can you add an extra call-out to each of those 4 numbered players, when it's their time to bait a kick or soak a tower?  This seems to be the biggest pain point in the mechanic so far... people remember to do their first half of their job as a number, and forget the second half.  I'm pretty sure this kind of call-out would be useful for both Krille/Oppo and JP Levinstrike strats.

Thanks!

**Comment by wexxlee** [comment]
This was already added in #5511 earlier today, and will be in the next release.
