### ISSUE TITLE
Modify Trigger Options by Group

### ISSUE THREAD

**Issue by Akainu87** [quisquous/cactbot#554]
Hi,

First of all, thank you for your great work!

I read some instructions here and I'm trying to create some TTS from Eden Savage. In particular, I customize the timeline txt file adding the function "alert all ... before 3 speak "voice" "tts" and I changed the raidboss.js setting True the option SpokenAlertEnabled.

Doing in this way, I noticed that now Cacbot as enabled the TTS for all Triggers in the resources, but i wanted the TTS i made in the timeline. 

I read the example I have found here and the solution is using the funciont option.pertriggeroption, selecting the ID of the trigger and modify the behaviour. By the way, considering that the trigger are quite a lot,  I'm asking if there is another function to modify a group of trigger not selecting one by one (i.e. a per trigger option that select all trigger of E1S and modifies their behaviour just in one shot).

Thank you very much again and sorry but I'm new to developing.

**Comment by quisquous** [comment]
There's not really a particularly easy way to do this.  You can do something like https://github.com/quisquous/cactbot-user/blob/master/raidboss.js#L125-L165 to save on typing, by setting up an option and using that for a bunch of different ids.

I don't really use tts very much at all except on really important mechanics where I might be doing something else at the same time (nael rp text, mostly).  Can you help me understand your use case where you want to have all tts just in E1S but not elsewhere?

**Comment by Akainu87** [comment]
In my case I just want tts callout for defensive cooldowns before certain mechanics. For all the rest I'm ok with the alarm text and just not need the tts.

**Comment by quisquous** [comment]
I don't think there's anything else that can really be done here.  There was some thought of maybe making some external config tool (issue #241), and I think that's a better answer to this sort of problem.
