### ISSUE TITLE
Adjust p9s tower timing

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#5566]
Re: #5511 (and me making assumptions about other people's comments in discord), I think the "Soak Tower" call for your tower comes out ALMOST right as the previous tower is being soaked.  It can feel a little confusing because it's so early in the sense of "should I be soaking that one???".  If the soak call were a second later (or triggered off of the tower damage itself?), then maybe it would feel less confusing because the previous tower would be done and it'd be clear it meant "soak the next one".

**Comment by wexxlee** [comment]
I think we could add a 1s. delay for the callout if it's the player's turn to soak.  I can throw a quick PR up tonight.
