### ISSUE TITLE
Raidboss no longer working. Throwing thousands of errors

### ISSUE THREAD

**Issue by VaporMoon** [quisquous/cactbot#558]
Raidboss plugin has now stopped working for some reason after I updated to the most recent release of the ACT FFXIV plugin.
I have tried downgrading the ACT FFXIV plugin and there has been no change. I have also tried re-installing Cactbot to no change.
The FSH overlay for Cactbot is still running just fine only raidboss has broken itself.
My parsing addon is running fine as well

Log file is filled with many errors:
```21/08/2019 01:46:54: Info: InitPlugin: PluginDirectory = D:\ACT Plugins\OverlayPlugin
21/08/2019 01:46:54: Info: LoadAddons: D:\ACT Plugins\OverlayPlugin\addons\CactbotOverlay.dll
21/08/2019 01:46:54: Info: LoadAddons: Cactbot.OverlayAddonMain: Initialized
21/08/2019 01:46:54: Info: InitPlugin: Initialized.
21/08/2019 01:46:55: Info: Raid-Cactbot: BrowserConsole: Uncaught SyntaxError: Unexpected token : (Source: file:///D:/ACT%20Plugins/OverlayPlugin/cactbot/ui/raidboss/raidboss.html, Line: 3)
21/08/2019 01:46:55: Info: Raid-Cactbot: BrowserConsole: Uncaught TypeError: Cannot read property 'OnDataFilesRead' of undefined (Source: file:///D:/ACT%20Plugins/OverlayPlugin/cactbot/ui/raidboss/popup-text.js, Line: 543)
21/08/2019 01:46:55: Info: Raid-Cactbot: BrowserConsole: Uncaught TypeError: Cannot read property 'SetDataFiles' of undefined (Source: file:///D:/ACT%20Plugins/OverlayPlugin/cactbot/ui/raidboss/raidboss.js, Line: 50)
21/08/2019 01:46:57: Info: Raid-Cactbot: BrowserConsole: Uncaught TypeError: Cannot read property 'OnInCombatChange' of undefined (Source: file:///D:/ACT%20Plugins/OverlayPlugin/cactbot/ui/raidboss/popup-text.js, Line: 537)
21/08/2019 01:46:57: Info: Raid-Cactbot: BrowserConsole: Uncaught TypeError: Cannot read property 'OnZoneChange' of undefined (Source: file:///D:/ACT%20Plugins/OverlayPlugin/cactbot/ui/raidboss/popup-text.js, Line: 534)
21/08/2019 01:46:57: Info: Raid-Cactbot: BrowserConsole: Uncaught TypeError: Cannot read property 'OnPlayerChange' of undefined (Source: file:///D:/ACT%20Plugins/OverlayPlugin/cactbot/ui/raidboss/popup-text.js, Line: 531)

21/08/2019 01:48:00: Info: Raid-Cactbot: BrowserConsole: Uncaught TypeError: Cannot read property 'OnLog' of undefined (Source: file:///D:/ACT%20Plugins/OverlayPlugin/cactbot/ui/raidboss/popup-text.js, Line: 540)
21/08/2019 01:48:00: Info: Raid-Cactbot: BrowserConsole: Uncaught TypeError: Cannot read property 'OnLogEvent' of undefined (Source: file:///D:/ACT%20Plugins/OverlayPlugin/cactbot/ui/raidboss/raidboss.js, Line: 47)
```

and then it just mostly repeats the line 531 error multiple times a second.

**Comment by imynwulf** [comment]
Is this still a problem with the latest update?

**Comment by VaporMoon** [comment]
Yeah I still have the errors coming through but there are some different lines it has issues with.

```
24/08/2019 07:41:37: Info: Raid-Cactbot: BrowserConsole: Uncaught SyntaxError: Unexpected token : (Source: file:///D:/ACT%20Plugins/OverlayPlugin/cactbot/ui/raidboss/raidboss.html, Line: 3)
24/08/2019 07:41:40: Info: Raid-Cactbot: BrowserConsole: Uncaught TypeError: Cannot read property 'OnDataFilesRead' of undefined (Source: file:///D:/ACT%20Plugins/OverlayPlugin/cactbot/ui/raidboss/popup-text.js, Line: 551)
24/08/2019 07:41:40: Info: Raid-Cactbot: BrowserConsole: Uncaught TypeError: Cannot read property 'SetDataFiles' of undefined (Source: file:///D:/ACT%20Plugins/OverlayPlugin/cactbot/ui/raidboss/raidboss.js, Line: 50)
24/08/2019 07:41:40: Info: Raid-Cactbot: BrowserConsole: Uncaught TypeError: Cannot read property 'OnInCombatChange' of undefined (Source: file:///D:/ACT%20Plugins/OverlayPlugin/cactbot/ui/raidboss/popup-text.js, Line: 545)
24/08/2019 07:41:40: Info: Raid-Cactbot: BrowserConsole: Uncaught TypeError: Cannot read property 'OnZoneChange' of undefined (Source: file:///D:/ACT%20Plugins/OverlayPlugin/cactbot/ui/raidboss/popup-text.js, Line: 542)
24/08/2019 07:41:40: Info: Raid-Cactbot: BrowserConsole: Uncaught TypeError: Cannot read property 'OnLog' of undefined (Source: file:///D:/ACT%20Plugins/OverlayPlugin/cactbot/ui/raidboss/popup-text.js, Line: 548)
24/08/2019 07:41:40: Info: Raid-Cactbot: BrowserConsole: Uncaught TypeError: Cannot read property 'OnLogEvent' of undefined (Source: file:///D:/ACT%20Plugins/OverlayPlugin/cactbot/ui/raidboss/raidboss.js, Line: 47)
24/08/2019 07:41:46: Info: Raid-Cactbot: BrowserConsole: Uncaught TypeError: Cannot read property 'OnPlayerChange' of undefined (Source: file:///D:/ACT%20Plugins/OverlayPlugin/cactbot/ui/raidboss/popup-text.js, Line: 539)
24/08/2019 07:41:46: Info: Raid-Cactbot: BrowserConsole: Uncaught TypeError: Cannot read property 'OnLog' of undefined (Source: file:///D:/ACT%20Plugins/OverlayPlugin/cactbot/ui/raidboss/popup-text.js, Line: 548)
24/08/2019 07:41:46: Info: Raid-Cactbot: BrowserConsole: Uncaught TypeError: Cannot read property 'OnLogEvent' of undefined (Source: file:///D:/ACT%20Plugins/OverlayPlugin/cactbot/ui/raidboss/raidboss.js, Line: 47)
24/08/2019 07:41:56: Info: Raid-Cactbot: BrowserConsole: Uncaught TypeError: Cannot read property 'OnZoneChange' of undefined (Source: file:///D:/ACT%20Plugins/OverlayPlugin/cactbot/ui/raidboss/popup-text.js, Line: 542)
24/08/2019 07:41:56: Info: Raid-Cactbot: BrowserConsole: Uncaught TypeError: Cannot read property 'OnLog' of undefined (Source: file:///D:/ACT%20Plugins/OverlayPlugin/cactbot/ui/raidboss/popup-text.js, Line: 548)
```

and then it just repeats line 47 & 548.

**Comment by DrLippe** [comment]
The first line of Error messages tells you there is an `Unexpected token :` (a colon)
Did you check the `raidboss.html`? Is there a `:` that is not supposed to be there?
It should look like this:
```html
<html>
<head>
  <meta charset="utf-8" />
  <title></title>
  <link rel="stylesheet" href="../../resources/defaults.css">
  <link rel="stylesheet" href="../../resources/resize_handle.css">
```

Click on `show devtools` in ACT and go to the Console tab.
You should find your error message here. Go to the first one and click on the source at the end of this first error message.  You should be redirected to the cause of your error.

Did you ever modify your `raidboss.html`?

**Comment by VaporMoon** [comment]
I have not modified it at all. I overwrite all files when updating.
Line 3 of my `raidboss.html` is just the same as yours.

**Comment by DrLippe** [comment]
are you using custom triggers?

**Comment by quisquous** [comment]
This looks similar to #430.  I think the cause of this is just a startup race where the plugin starts sending messages before the overlay is ready for it (but theoretically this should never happen because messages aren't sent until the overlay notifies the c# plugin).

I've tried to track this down some, but have been unable to figure out what's going on because this never happens for me locally.  The best thing I can recommend at the moment is if you see these errors to just reload the overlay that's complaining or to restart act.  I'm sorry I don't have a better answer for you.

**Comment by ngld** [comment]
I've seen this issue or at least similar errors while experimenting if `UserConfig.getUserConfigLocation` takes too long or just fails. In the case of Raidboss, the event handlers are already set up and try to call a method on an undefined value (since `gTimelineController` was never set).

The `Unexpected token :` message probably comes from the injected JavaScript. Since it's never executed, the `onOverlayInitialized` event is never fired and thus `gTimelineController` is never created.
@VaporMoon Do you have anything (except the example files) in your `user` folder?

The `gLang.countdownEngageRegex` issue mentioned in the other issue happens whenever 
`onOverlayInitialized` was processed correctly but `onPlayerChangedEvent` wasn't or arrived before `getUserConfigLocation` finished.

**Comment by VaporMoon** [comment]
I don't have any custom triggers. I do have raidboss.js file to change the pull timer sound which contains only
```
'use strict';

Options.PullSound: '../../resources/sounds/Overwatch/Reaper_-_Die_die_die.ogg';
```

and now today whenever I go to the OverlayPlugin.dll tab in ACT I now get unhandled exceptions errors. I didn't change anything since updating yesterday and I didn't get the errors then.

I will reinstall ACT and Cactbot and see what happens.

**Comment by ngld** [comment]
Uh, that's exactly where the syntax error is. That line should look like this:

`Options.PullSound = '../../resources/sounds/Overwatch/Reaper_-_Die_die_die.ogg';`

Change that and it should work again.

**Comment by quisquous** [comment]
Thanks for solving this!
