### ISSUE TITLE
P11S lightstream no longer working after today's update

### ISSUE THREAD

**Issue by Ashe-H** [quisquous/cactbot#5588]
## Description

Lightstream callouts are no longer working since I updated cactbot this morning, they were working just fine yesterday.

## Additional information

If available, please include any logs or screenshots depicting the issue you're experiencing.

**Comment by quisquous** [comment]
Sorry, this worked for me in the emulator.  Can you attach any network logs and let me know which pulls weren't working? Is it not showing anything or showing the wrong thing?

**Comment by Ashe-H** [comment]
Since I needed it at that time, I deleted everything and went back to the previous build. I will have to update it again and test it out so I can provide you with logs.

**Comment by Wessie** [comment]
Also noticed this, it seems to now be configured under `Collectors` only and never produces an actual output. The log from my report yesterday also shows no lightstream output in the emulator
<img width="604" alt="msedge_RUIpMEnxFZ" src="https://github.com/quisquous/cactbot/assets/1375663/6460a80a-d328-4731-8238-50109da78895">
