### ISSUE TITLE
P10s Jade Passage is calling out the opposite of correct.

### ISSUE THREAD

**Issue by mistahnice** [quisquous/cactbot#5593]
Noticed that cactbot added calls for P10s Jade Passage (that's the line AOE that the orbs leave behind after the half-room cleave.)

Cactbot calls either "lines safe" or "inside boxes" but it calls it incorrectly for each pattern. It will call lines safe when boxes are safe, and boxes safe when lines are safe.

**Comment by Akurosia** [comment]
Already discussed and fixed in https://github.com/quisquous/cactbot/pull/5591 and https://github.com/quisquous/cactbot/commit/6bec90a0fa65f49a9ee05051c045eaa05115aed1

**Comment by mistahnice** [comment]
Thanks!
