### ISSUE TITLE
P12s P12S Engravement 1 Tower Drop getCombatants get unmoved position

### ISSUE THREAD

**Issue by YuzukiTsuru** [quisquous/cactbot#5607]
P12s P12S Engravement 1 Tower Drop getCombatants get unmoved position.

In some cases, the position obtained by getCombatants is the default position, not the one Tether moved to, resulting in an unmatched position

**Comment by quisquous** [comment]
Hmm, does this mean that the combatant hasn't moved yet (timing issue) or that it is the wrong combatant entirely.  The `261` / `0x105` lines should tell you when combatants move.

**Comment by YuzukiTsuru** [comment]
Looks like an ACT problem, close it
