### ISSUE TITLE
How to change threshold(?) for Surging Tempest buff for WAR?

### ISSUE THREAD

**Issue by itonohito** [quisquous/cactbot#5624]
## Question

I'd like to have square for Surging Tempesst buff to become big with countdown at 29 seconds remaining (and sound signal too). Now it turns on at 10 seconds AFAIK.  Is there any way to do that?

**Comment by Echoring** [comment]
Sorry to say, jobs module is not good for customization.
This threshold are defined at here. https://github.com/quisquous/cactbot/blob/a6173c3b50567f8d0d6fc4007b1d049955a69162/ui/jobs/components/war.ts#L102
If you know how to build cactbot, you can change here and build your own. 
I'm not sure user directory will work or not for this. If it works, you can also change jobs.bundle.js at line 41311.

**Comment by itonohito** [comment]
Thank you for your help.
