### ISSUE TITLE
Albion boss in Lapis Manalis - wrong callout?

### ISSUE THREAD

**Issue by Theletha** [quisquous/cactbot#5641]
When the boss is casting his slams the prompts are calling out the danger zones instead of the safe zones. 
This is from the perspective of being in front of boss where it is currently looking. 
Are you expecting everyone to be behind the boss since he moves towards the entrance and are looking towards the entrance of boss area? 

As a tank i always do the reverse for the prompts and the prompts for the slams always get me hit since its double reversed on the slams.

**Comment by quisquous** [comment]
Left/right calls are boss relative so they are consistent.  "Left" means "go to the boss's left flank" and "right" means "go to the boss's right flank".  It is always relative to the boss.  The only real exception is for wall bosses where players are always facing the boss, and so "left" means "go to your left (facing the boss)", e.g. p8s and p12s final bosses.

**Comment by Theletha** [comment]
What do you mean exactly with boss relative?  cause the bos is looking my way and the callouts are wrong in that position

**Comment by xiashtra** [comment]
Boss relative means boss relative: if it calls "left," it means "boss's left."  You are asking for player relative, which we do not do on purpose because it could be different for each player.

There is no bug, these calls are working as intended.

**Comment by wexxlee** [comment]
> What do you mean exactly with boss relative? cause the boss is looking my way and the callouts are wrong in that position. Did you mistake his body for looking towards the middle of the arena?  

It seems like this was answered pretty well in this discord conversation earlier today: https://discord.com/channels/551474815727304704/551476873717088279/1125537334838968340

The callouts assume you are facing the boss from behind it.  So your right is also the boss's right, and if Right is the call, you would move to your right (aka its right). If you are looking at the boss from his front, its Right is now your left.  So you would still move to its right (your left). You may be facing the front of the boss during that call.  Others will be facing his rear.  The callouts doesn't change based on which way the boss is facing relative to you personally, so if you are facing his front when the call comes out, you either need to turn your camera or simply flip the call in your head.  This is a fairly common thing, especially for tanks, who tend to be facing a different side of the boss than the rest of the party.

**Comment by Theletha** [comment]
> 

But if the hole party is in front  of boss wont boss relative apply there too? or does it mean boss relative from middle of boss room? The callouts assume that the party is in the middle of the boss room

**Comment by xiashtra** [comment]
The boss has a left arm and a right arm.  It doesn't matter where you are facing him from, `left` always means `boss's left`, i.e., the side of the boss's left arm.  We do not track player position relative to the boss/arena or make calls that are player relative.

**Comment by Theletha** [comment]
> The boss has a left arm and a right arm. It doesn't matter where you are facing him from, `left` always means `boss's left`, i.e., the side of the boss's left arm. We do not track player position relative to the boss/arena or make calls that are player relative.

But with that logic you would be getting hit by the p12 boss from the wings since it would be calling out the same as what's being cast. the boss has a right wing and a left wing but it still is calling out the reverse. 

> doesn't matter where you are facing him from, left always means boss's left
so if left is always left then i should be taking the left side of the p12 boss when he cast the spell on his left wing?

**Comment by xiashtra** [comment]
It works exactly like the P12 boss; when the boss is cleaving the right side, the callout says left, as in the boss's left.  It makes no attempt to adjust for player facing.  when Albion (the Lapis Manalis first boss) uses `Right Slam`, it calls `left`, regardless of player facing.

**Comment by quisquous** [comment]
> i think i get it twisted since he turns around

Sorry for the confusion.  I understand what you're asking for and why this doesn't work for you specifically, but I think in general it would cause more confusion if it were not consistent about what "left" meant.  (Imagine this example, boss facing north, two players standing west, one slightly north of west and one slightly south of west; do you call left for one and right for the other?)

For the sake of cactbot triggers, I think it's better to just always call left-meaning-left-flank so that players always know what calls mean, and the calls are the same for everybody.
