### ISSUE TITLE
P10S Daemonic Bond  callout is opposite for non en users

### ISSUE THREAD

**Issue by YetAnotherIC** [quisquous/cactbot#5643]
Hi,

I am using a jp xiv client and I noticed cactbot is calling out the opposite for P10S Daemonic Bond(i.e. `partnersThenSpread` is called as `spreadThenPartners`).

After looking into the source code, I realized it's because boss name is hard [coded](https://github.com/quisquous/cactbot/blob/main/ui/raidboss/data/06-ew/raid/p10s.ts#L22C1-L22C44) as `const bossNameUnicode = 'Pand\u00e6monium';` while in jp client boss name is `パンデモニウム`.

This results in 

```
    {
      // Daemoniac Bonds starts casting
      // Then all of the Daemoniac Bonds DDE (spread) effects go out
      // Then 4x DDF or 2x E70 effects go out.
      id: 'P10S Pandaemoniac Bonds Cleanup',
      type: 'StartsUsing',
      netRegex: { id: '82A1', source: bossNameUnicode, capture: false },
      run: (data) => {
        delete data.daemonicBondsTime;
        delete data.bondsSecondMechanic;
        data.daemonicBondsCounter++;
      },
    },
```

not getting triggered and is still remembering the previous `data.daemonicBondsTime`(hence the opposite callout)

I can see in replaceSync the boss name is replaced with `'Pand\\\\u00e6monium': 'パンデモニウム',` [here](https://github.com/quisquous/cactbot/blob/34708993fef5a84adeefdd95953ece9e73282a98/ui/raidboss/data/06-ew/raid/p10s.ts#L708C5-L708C42) but probably the espacing is not working properly?

After I change this line to 

`[bossNameUnicode]: 'パンデモニウム',` it now works perfectly.

**Comment by quisquous** [comment]
Do you have a network log you can attach here of this fight? You can use https://quisquous.github.io/cactbot/util/logtools/splitter.html if you want to only grab one pull.

**Comment by Souma-Sumire** [comment]
念のためですが、FFXIV ACT Plugin.dllの解析オプション（Parse Options）の言語（Lauguage）設定が正しく日本語（日本語）になっているか確認していただけますか？

Just to be sure, could you please check if the language option for the parsing options (Parse Options) of the FFXIV ACT Plugin.dll is correctly set to Japanese (日本語)?
![image](https://github.com/quisquous/cactbot/assets/33572696/0b130785-4562-4dcc-9348-8eadecd4806a)

**Comment by YetAnotherIC** [comment]
Hi @quisquous

I realized "Anonymize Log"  [https://quisquous.github.io/cactbot/util/logtools/splitter.htm](https://quisquous.github.io/cactbot/util/logtools/splitter.html) is not working properly(although in most places through the log it's anonymized, I can still see my character name in some places after turning it on) so I am not comfortable with sharing it publicly. Would you mind opening up your discord privacy setting to accept direct DM on `FFXIV_ACT` server temporaily? I can send my log through there.

![act](https://github.com/quisquous/cactbot/assets/11089592/9fba0d18-5a28-4e40-b44d-3241210a370e)

@Souma-Sumire 

Yes it's 日本語
![1](https://github.com/quisquous/cactbot/assets/11089592/4ff0e341-6878-4d73-b307-79ae4b366619)


more proof on this issue


Without modifying anything, `raidemulator.html?` shows two `spread => partners`


![1](https://github.com/quisquous/cactbot/assets/11089592/72ad489a-d947-443c-928f-46c63a02f450)

Modifying line 1134210 in `raidboss_data.bundle.js` to `[p10s_bossNameUnicode]: 'パンデモニウム'` then reload cactbot

![2](https://github.com/quisquous/cactbot/assets/11089592/88c096be-7461-4851-99f6-260e84b13889)


`3:05` is now `partners -> spread`


![3](https://github.com/quisquous/cactbot/assets/11089592/6a3b1dc6-b34b-4719-82cb-7654cbe0eb16)

**Comment by quisquous** [comment]
I have all of those DM settings on.  You should be able to DM me, as far as I can tell.

**Comment by YetAnotherIC** [comment]
> I have all of those DM settings on. You should be able to DM me, as far as I can tell.

Weird it didn't work before! Just sent you the log.

**Comment by quisquous** [comment]
Oh yeah, it's not just the bond callout, it's every trigger with a `source` property. Just looking at those screenshots, there's missing aoe and turrets calls too.
