### ISSUE TITLE
Raidboss: triggerSetConfig Input Box Shows Default Value in Config Panel, but Returns Empty String Instead of Default Value When Accessed in Code

### ISSUE THREAD

**Issue by Souma-Sumire** [quisquous/cactbot#5648]
_The entire text was generated by a translation software. If there are any parts that are not clear, please let me know._

### Description
1. When the input box for triggerSetConfig is cleared and the webpage is refreshed, the config panel shows the default value. However, when accessing data.triggerSetConfig in the code, it returns an empty string '' instead of the default value.
2. The input box in the config panel should have gray font color to indicate that the triggerSetConfig value is unmodified when it is the same as the default value.

This is highly misleading to users because they see a value displayed, but in reality, it is an empty string. Moreover, this behavior contradicts the behavior of outputStrings, so I believe it is a bug. (outputStrings correctly retrieves the default value, and the value saved in the JSON is also an empty string, which is consistent with the expected behavior.)

I believe these two issues share a commonality, which is why I have reported them together.

### Reproduce
js:
```javascript
Options.Triggers.push({
  zoneId: ZoneId.MatchAll,
  id: "Souma_Test",
  config: [{ id: "TEST_20230707", name: { en: "TEST_20230707" }, type: "string", default: "Hello" }],
  triggers: [
    {
      id: "TEST 20230707",
      type: "StartsUsing",
      netRegex: { capture: false },
      infoText: (_data, _matches, output) => output.text(),
      suppressSeconds: 9999,
      run: (data, _matches, output) => {
        console.warn("config:", data.triggerSetConfig.TEST_20230707);
        console.warn("output:", output.text());
      },
      outputStrings: { text: { en: "World" } },
    },
  ],
});
```

config:
![image](https://github.com/quisquous/cactbot/assets/33572696/91362576-cf87-4b92-84c6-7632feb90ef1)

raidemulator:
![image](https://github.com/quisquous/cactbot/assets/33572696/1d119470-819a-4339-b077-faeecbc51f0f)

Clear config string and restart ACT:
![image](https://github.com/quisquous/cactbot/assets/33572696/ba82df68-8859-4276-8a72-8ab812c0aed9)

raidemulator:
![image](https://github.com/quisquous/cactbot/assets/33572696/836172ca-a607-4144-8290-4d08c5e55c38)

**Comment by quisquous** [comment]
As it is impossible to differentiate between "I am clearing this to set the default" and "nothing", my intention is that empty string should be the default as it does for output strings. I must have just missed a case to check for empty string in `config.ts` when retrieving the value.
