### ISSUE TITLE
Editing Paradeigma 2 strategy

### ISSUE THREAD

**Issue by xilostcause** [quisquous/cactbot#5650]
## Question

I wasn't sure where to ask this but I wanted to know if I could be guided on what values to change in trigger source files to call out Paradeigma 2 (Engravement 1) backwards. To my understanding, the Game8 strategy has DPS NE CW and Supports NW CCW. I was hoping there might just be something that, as a support, would trick cactbot into thinking I'm a DPS and calling out DPS locations since the group I run with does it opposite. 

Sorry if this shouldnt be posted on Github!

**Comment by quisquous** [comment]
The callouts don't tell you which spot to go to, only the two spots that are valid. So, it will work for any priority system.

**Comment by xilostcause** [comment]
Gotcha! That was I was gathering when looking at the code. Thank you for clarifying!
