### ISSUE TITLE
updated to 0.29.20 but still having raidboss trigger issue.

### ISSUE THREAD

**Issue by AriaFlolence** [quisquous/cactbot#5673]
As stated in the previous bug report, I just updated to version 0.29.20 and tried again, but still have the same problem. (raidboss trigger related error)
Sound alarms and survival skills of other classes are still output during normal attacks.

"living corpse" or "explosive meteor" etc.

**Comment by quisquous** [comment]
I assume you are playing in a language other than English?

**Comment by AriaFlolence** [comment]
> 영어가 아닌 다른 언어로 플레이하고 있다고 가정합니까?

Yes I am playing in Korean

**Comment by quisquous** [comment]
Ok, I will try to take a look at this later tonight and see why this is broken for you.  Sorry for the hassle.

**Comment by AriaFlolence** [comment]
> Ok, I will try to take a look at this later tonight and see why this is broken for you. Sorry for the hassle.

Thank you so much for your help! I'll see if the same happens to other players playing in the same environment as me.

**Comment by AriaFlolence** [comment]
> Ok, I will try to take a look at this later tonight and see why this is broken for you. Sorry for the hassle.

This issue was resolved by first updating the cactbot to a new version, then changing the job in-game once, then running the cactbot again.

Problem solved, thanks for your help.

**Comment by quisquous** [comment]
Phew, glad that was it.
