### ISSUE TITLE
[meta] 6.45 content planning

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#5712]
variant dungeon: @quisquous 
criterion dungeon:
criterion savage dungeon: 
carnivale stage 32: @xiashtra 

I'll take the variant dungeon, as I'm planning on poking at all the routes and it's not urgent.

I am also planning on doing the criterion dungeon blind this time since I don't get to do much blind content in ffxiv.  (Scheduling-wise it might be a little bit before I get there too.) I don't know if anybody else wants to volunteer to review any of these PRs in my place so I don't have to look at them? otherwise I'll just merge them and trust the authors to fix any issues as they come up. I'll also get to it eventually if nobody else has, but it might take me a bit.

blu eden raids have gotten a first pass from @xiashtra (thank you). I'm not sure if strats without roles need more info (e.g. advanced relativity telling you who your partner is and not just who double winds are), but we can fix that up as we go.

**Comment by xiashtra** [comment]
I'll work on 32 I've just been busy this week.

**Comment by wexxlee** [comment]
I'm a little busy irl right now, and not sure when I'll have time to dig into the criterion dungeon.  But if no one has started dropping stuff for it by next week, I'll try to at least get started on it.

**Comment by xiashtra** [comment]
> I'm a little busy irl right now, and not sure when I'll have time to dig into the criterion dungeon. But if no one has started dropping stuff for it by next week, I'll try to at least get started on it.

Pretty much the same for me.

**Comment by quisquous** [comment]
This is done other than #5718, which I'll land ... next week maybe I hope
