### ISSUE TITLE
oopsyraidsy doesn't work on KR 6.31

### ISSUE THREAD

**Issue by kokose1234** [quisquous/cactbot#5717]
## Description

oopsyraidsy only prints information like this:
Username: unkown_0000 (10000/10000)
Username2: unkown_0000 (10000/10000)
Username3: unkown_0000 (10000/10000)

it doesn't print gimmick mistake, it only prints wierd damage taken messages

**Comment by quisquous** [comment]
Can you include a network log for some content that has oopsy support?

**Comment by kokose1234** [comment]
@quisquous omega's skill name is not properly parsed by act.
21|2023-07-26T16:39:21.1790000+09:00|40001600|오메가|7BFD|unknown_7bfd|1016DC86|Name|730003|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|108346|108346|7800|10000|||100.14|109.10|0.00|3.14|8424620|8557964|10000|10000|||100.02|100.82|0.00|0.01|0000015D|0|1|1a6ceac4d686df90

20|2023-07-26T16:39:29.0220000+09:00|40001600|오메가|7B03|unknown_7b03|40001600|오메가|3.700|100.02|100.82|0.00|3.13|6445ec63b5274f73

21|2023-07-26T16:39:47.0170000+09:00|40001600|오메가|7B07|unknown_7b07|40001600|오메가|1B|7B078000|0|0|0|0|0|0|0|0|0|0|0|0|0|0|5526693|8557964|10000|10000|||100.02|100.82|0.00|0.00|5526693|8557964|10000|10000|||100.02|100.82|0.00|0.00|0000025A|0|1|6b8fa328c7a78417

**Comment by quisquous** [comment]
Is that a line break? Can you attach a network log for me to look at? https://github.com/quisquous/cactbot/blob/main/docs/FAQ-Troubleshooting.md#how-to-find-a-network-log

**Comment by babaisnyan** [comment]
@quisquous this is full network log

**Comment by quisquous** [comment]
OH! I'm sorry for taking so long to figure this out. I completely misunderstood what the issue is. This is something that Ravahn needs to fix.  I filed https://github.com/ravahn/FFXIV_ACT_Plugin/issues/317 for this.  Feel free to follow up there or in the ffxiv act discord.
