### ISSUE TITLE
Is writing triggers for OverlayPlugin log lines not recommended?

### ISSUE THREAD

**Issue by Souma-Sumire** [quisquous/cactbot#5730]
As the title suggests, are OverlayPlugin log lines reliable? Or are they not recommended, similar to 00 log lines?

**Comment by quisquous** [comment]
OverlayPlugin log lines should be reliable. In a lot of cases they have been added in order for people to write triggers from them.

**Comment by Souma-Sumire** [comment]
Got it, thanks
