### ISSUE TITLE
oopsyraidsy: Food Buff removal not being detected

### ISSUE THREAD

**Issue by valarnin** [quisquous/cactbot#5748]
## Description

Oopsy's food buff removal trigger is not working.

## Additional information

 I'm not sure how long this has been an issue, probably for like 3 years now since #1610. Looks like some confusion between the hex ID `0x30` which shows up in the actual line vs the decimal equivalent `48`?

https://github.com/quisquous/cactbot/blob/928d96adedb5a179bba149175d9f9408eb13f88f/ui/oopsyraidsy/data/00-misc/general.ts#L19-L50

Probably this makes more sense?

```ts
import EffectID from '../../../../resources/effect_id';
// ...
      netRegex: NetRegexes.losesEffect({ effectId: EffectID.WellFed }),
```

```
Added:
26|2023-08-03T17:25:57.4610000-04:00|30|Well Fed|942.05|10001234|Some One|10001234|Some One|294B|91425|91425|99cf04ee59e83f92
Removed:
30|2023-08-03T18:05:28.8230000-04:00|30|Well Fed|0.00|10001234|Some One|10001234|Some One|2964|94664|94664|5cec6eb3ad1d91d0
```

The `gainsEffect` trigger is obviously also suffering the same issue. Not sure if other triggers elsewhere are.

**Comment by quisquous** [comment]
Unfortunately, the effect id file is not really consistent over time. If there's ever a new ability called well fed, then they'll both be removed as being conflicts, and then this will be an error. Maybe that could change, but I think for now it needs to be literal.
