### ISSUE TITLE
P12S Classical Concept 2 without movement

### ISSUE THREAD

**Issue by DreyfussFrost** [quisquous/cactbot#5752]
Could an alternate strat option be added to just skip the "initial" call altogether, call only the "actual" positions at the start, and NOT reverse the symbol order from Classical 1?  The mechanic's easier when you just turn around and look at the real pattern.

![P12SClassical2](https://github.com/quisquous/cactbot/assets/67395342/1659573f-a492-4839-a275-e51449bb85c0)

**Comment by wexxlee** [comment]
I can PR this later tonight/tomorrow.

**Comment by DreyfussFrost** [comment]
Thanks!  Just checking since this is the more important part of the suggestion: with this option enabled, if I were to select "BPOG" as the pairs order for example, would the "actual" call that comes through still be "BPOG" from left to right, or "GOPB," as it would be after the swap PF does?  The point is to facilitate a strat with no swap.

**Comment by wexxlee** [comment]
> Thanks! Just checking since this is the more important part of the suggestion: with this option enabled, if I were to select "BPOG" as the pairs order for example, would the "actual" call that comes through still be "BPOG" from left to right, or "GOPB," as it would be after the swap PF does? The point is to facilitate a strat with no swap.

Ah, I see.  I missed that part of your strat description.
No, if you select 'BPOG', the Actual call you'll get will still invert the position before giving you the call (like it does with the other strats) -- so, if for example you're the blue X, your 'Actual' call would correspond to the far right/east column (e.g. GOPB).

That should be a fairly easy tweak, but it is a more fundamental concept change than just calling out the final/actual position, so I think the checkbox to enable it should probably be more descriptive than just "don't call initial".  Does this strat have a name?  Or do you have a link to a toolbox or guide, something than can be added to the comments?

**Comment by Legends0** [comment]
It sounds like there are two things that would need to happen. I see in the picture it is actually GOPB that would have had to be selected since currently the order/call is relative to facing the boss.

- A configuration option for classical 2 to be different order than classical 1.
- A configuration option for classical 2 call the actual result instead of initial.

**Comment by wexxlee** [comment]
> It sounds like there are two things that would need to happen. I see in the picture it is actually GOPB that would have had to be selected since currently the order/call is relative to facing the boss.
> 
> * A configuration option for classical 2 to be different order than classical 1.
> * A configuration option for classical 2 call the actual result instead of initial.

I'd lean toward doing a single config option since I don't think there's a lot of demand/value for keeping the options separate, and this corresponds to a single strat choice for classical2 (and I'm not sure it would be immediately obvious to people who want to do this strat that they'd need to check two separate boxes).

In terms of implementation, because we only have the shape position data for their initial spawn (and then calculate the safe spots and invert for the flip), I think the most direct way of implementing this is to keep the code as-is in the PR (#5754) but call reverse() on columnOrder if the config option is checked.  So for BPOG, e.g., this would internally reverse the order (GOPB), assign safe spots to the grid as the shapes initially appear, flip them (so back to BPOG), and then output the actual -- which is essentially how the video shows resolving the mech.

I do think it's worth including either a strat name (if there is one) or a link to a guide in the code comments, just so there's an external reference though.

**Comment by quisquous** [comment]
Yeah, a single option that ends up reversing the order and only calling it once sounds reasonable to me. I think hypothetically adding some extra orders (GOPB, reverse rocketship, whatever) would be better than a second checkbox if we needed to go that route.

Also, just to make sure you know, there is support for `comment` fields now (see `staffSwordDodge` as an example), if you want to give some explanation for what the checkbox means more than just the name.

**Comment by DreyfussFrost** [comment]
Sorry, these updates weren't getting forwarded to my main email address and since I wasn't able to respond immediately it slipped my mind.  As far as I know there's no "official" strat, it's just what seemed intuitive to me and my blind static when we encountered it.  Since I raid with several other more casual groups, some of whom use raidboss, I was wondering if it could be added as a strat option because I can see Classical 2 being a big hurdle for a couple players that have difficulty with spatial reasoning puzzles.  I also personally find it easier and more intuitive as a BLM main than adding a long, slow, unnecessary movement on a mechanic that gives you more than enough time to solve in your head.

I can give an example though, using Icy-Veins' diagram.

![classical2](https://github.com/quisquous/cactbot/assets/67395342/2ab61a67-1bd2-475a-871b-e4ada1672c0f)

Assuming that attachment appears correctly, let's say that's the pattern.  Since Panta Rhei just flips the pattern around 180 degrees, if you turn your camera 180 degrees _before_ the flip and look at it from the boss's point of view, then you can see the "real" pattern.

![Classical2Reversed](https://github.com/quisquous/cactbot/assets/67395342/75e2b914-71d0-4c97-946c-7191eac9ab0a)

You just find your spot in the real pattern and then turn back around to face boss and go there.

![Classical2Final](https://github.com/quisquous/cactbot/assets/67395342/c2b654d6-eb13-404e-ba43-1f2c8b10176b)

Alternatively, several people on my team just think of it as looking at the whole thing symmetrically.  If they're X (blue), they're moving to the far left column but looking across at the blue shape's position in the far right column and mirroring it (e.g. if blue is in front, they go to the rear shape).  Then, still looking at the blue shape on the other side, they find the correct position for their debuff on that side and mirror it as well.  So if they would be standing south of the blue shape on the far right, they'll stand north of whichever shape they went to on the far left.

We came up with this without guides, but looking at the Icy-Veins page now to grab that diagram, I see they also describe it as the "second method" in their Classical Concepts 2 section.  https://www.icy-veins.com/ffxiv/the-twelfth-circle-savage-part-two-raid-guide#the-classical-concepts-2

**Comment by DreyfussFrost** [comment]
> 

Thanks for the work implementing this!  I'm glad to report it works perfectly for Classical 2, however, having the checkbox enabled _also_ reverses the column order for Classical 1.  When I tested it with BPOG order, I was given the instructions for G when I was B, or O when I was P, and so on.  This was only for Classical 1.  Classical 2 works as intended!

Demonstration: https://youtu.be/wNmS1kU8OLY
