### ISSUE TITLE
old content wont show up for me on alerts and time line for some reason ?

### ISSUE THREAD

**Issue by kaidachan** [quisquous/cactbot#5762]
## Description
old content from arr all the way to shb wont show up to me on alerts or time line for some reason even tho i have everything enabled 
Description of the issue you're seeing.

## Additional information

If available, please include any logs or screenshots depicting the issue you're experiencing.

**Comment by xiashtra** [comment]
Check https://github.com/quisquous/cactbot/issues/4848 or ask in the ACT discord for more support.
