### ISSUE TITLE
PR #5754 also flips Classical 1 column order

### ISSUE THREAD

**Issue by DreyfussFrost** [quisquous/cactbot#5771]
Thanks for the work implementing the new Classical Concepts option!  I'm glad to report it works perfectly for Classical 2, however, having the checkbox enabled _also_ reverses the column order for Classical 1.  When I tested it with BPOG order, I was given the instructions for G when I was B, or O when I was P, and so on.  This only occurs during Classical 1.  Classical 2 works as intended.

Demonstration: https://youtu.be/wNmS1kU8OLY

_Originally posted by @DreyfussFrost in https://github.com/quisquous/cactbot/issues/5752#issuecomment-1694020061_

**Comment by wexxlee** [comment]
> implementing the new Classical Concepts option! I'm glad to report it works perfectly for Classical 2, however, having the checkbox enabled _also_ reverses the column order for Classical 1. When I tested it with BPOG order, I was given the instructions for G when I was B, or O when I was P, and so on. This only occurs during Classical 1. Classical 2 works as intended.

Yeah, you're right.  There should have been a phase check on columnOrder.reverse.  Apologies for that - I'll drop a PR to fix ASAP.
