### ISSUE TITLE
Cactbot sound triggers not following ACT audio device

### ISSUE THREAD

**Issue by propkitty** [quisquous/cactbot#5779]
## Description

With SlimDX Audio running to push ACT sound through to a virtual cable, all of ACT's normal triggers (such as TT) are coming through the designated virtual cable. Previously, Cactbot's sounds followed suit. However, something has changed and now Cactbot's sounds are coming through the main sound cable (same as the game's sound, my browser, etc) instead of the selected cable.

I'm not sure what changed, as nothing in my system has changed other than ACT updates, but this is producing a horrible echoing effect now.

## Additional information

![image](https://github.com/quisquous/cactbot/assets/14895964/384326f3-3043-4b35-949d-1661c7606410)

You can see in this screenshot that I just hit a custom ACT trigger and the sound plays properly, going through cable A.

![image](https://github.com/quisquous/cactbot/assets/14895964/1258a84d-6ea7-4247-993a-276fc3551c55)

Cable A, set up in SlimDX.

![image](https://github.com/quisquous/cactbot/assets/14895964/4679763e-6371-4873-8c5d-a670497ad9a3)

In this screenshot, you can see in the VAIO meter (middle) and the master section (right) that a sound is playing (which is a sound trigger from Cactbot) but there is nada under the Cable A (left).

This all worked beautifully before, but I'm not sure what's changed with Cactbot. Anyone have any idea what's going on?

**Comment by quisquous** [comment]
For what it's worth, nothing has changed with cactbot sound stuff in quite a long while. TTS from cactbot goes through ACT, but sounds are being played through CEF (running in a subprocess from ACT). I haven't ever used this program, but maybe you need to hook something to that specifically?

**Comment by propkitty** [comment]
Is TTS what produces things like the 'bongs' when a mechanic flashes from Cactbot? Just to confirm.

Nothing has changed in my set up, but it seems to have come up in just the last short while. I can check into CEF and see what might be going on - a good lead to start on. Something has had to change with something, though I couldn't tell you precisely what. It's just strange that ACT's custom triggers would come through correctly but not Cactbot's anymore.

**Comment by quisquous** [comment]
> Is TTS what produces things like the 'bongs' when a mechanic flashes from Cactbot? Just to confirm.

No, TTS is text to speech. It's the thing says text out loud. ACT and cactbot use the same mechanism for tts. However, cactbot and ACT use different mechanisms to play sounds (like the bongs). So, it would not be surprising to me if you captured one but not the other.

Nothing has changed on the cactbot side here, and there hasn't been a CEF update. Has there been an update to SlimDX?

**Comment by propkitty** [comment]
It's strange because it used to work perfectly. Are there any details on what Cactbot is using to play sounds so I can try and see if something with ACT or perhaps SlimDX has changed in that area?

Thank you, by the way, for trying to help! The echo is driving me absolutely nuts! ; ;

**Comment by quisquous** [comment]
> It's strange because it used to work perfectly. Are there any details on what Cactbot is using to play sounds so I can try and see if something with ACT or perhaps SlimDX has changed in that area?

Sorry, as I mentioned above, the sounds are being played through a CEFSharp.BrowserSubprocess (you can see these in task manager). Maybe SlimDX doesn't know about subprocesses? That's the only thing I can think of.

**Comment by propkitty** [comment]
Your comment about CEFSharp.Browser helped immensely! I went into Windows 10 and into the sub-application specific input/output choices and found that registered as an application. It allowed me to re-direct *that* specifically to the same virtual cable as ACT is and now both are going through that cable.

Thank you! Marking as closed. :)
