### ISSUE TITLE
Regarding "P12S Classical Concepts" Alert Text

### ISSUE THREAD

**Issue by Souma-Sumire** [quisquous/cactbot#5798]
## Question

I see the output text for 'P12S Classical Concepts' as follows:

```
northRow: {
  en: 'North Blue',
  de: 'Norden Blau',
  cn: '第1个蓝方块',
  ko: '위쪽 파란색',
},
middleRow: {
  en: 'Middle Blue',
  de: 'Mitte Blau',
  cn: '第2个蓝方块',
  ko: '가운데 파란색',
},
southRow: {
  en: 'South Blue',
  de: 'Süden Blau',
  cn: '第3个蓝方块',
  ko: '아래쪽 파란색',
},
```
_These texts are only output when the 'triggerSetConfig.classicalConceptsPairOrder' option is not set to the default 'shapeAndDebugff'._

I would like to ask, does 'Blue' here refer to the color blue, or does it have another meaning?

Because there are clearly three different colors for the cubes, but the text here specifies blue, which is confusing to me.

**Comment by Akurosia** [comment]
It calls out the blue, as it is the anchor for each of the 4 pairs as red and yellow figures are drawn to the blue hexagons

**Comment by Souma-Sumire** [comment]
> It calls out the blue, as it is the anchor for each of the 4 pairs as red and yellow figures are drawn to the blue hexagons它呼唤Oh, yes!! It was my mistake. Thank you for your response.
