### ISSUE TITLE
RaidBoss - In TOP only "gainseffect" triggers are shown, but not the others

### ISSUE THREAD

**Issue by quellamomo** [quisquous/cactbot#5810]
## Description

Description of the issue you're seeing.

## Additional information

If available, please include any logs or screenshots depicting the issue you're experiencing.

**Comment by quisquous** [comment]
Sorry, I need a little bit more information than this. Can you describe the issue a little bit better?

**Comment by quellamomo** [comment]
Hi, thanks for the reply. So for the RaidBoss in Cactbot, when I'm in TOP, only the triggers labeled "gainseffect" in the source codes are called out/shown on screen, but the others are not.
Examples when you open cactbot config raidboss:
Working: "TOP In Line Debuff"
               "TOP Syergy Marker"
Not working: All the others above "TOP Spotlight", the rest haven't been tested.
![image](https://github.com/quisquous/cactbot/assets/145887584/7e4b805a-c3c3-45cc-9693-57f9790966e0)

**Comment by quisquous** [comment]
This sounds like a translation / language issue. What language are you playing in? What language is the ffxiv plugin set to use? Can you post the "copy tech support" output from ACT -> Plugins -> OverlayPlugin.dll -> Copy Tech Support &c.

If you do a `/countdown 5` in summerford farms, does a timeline start?

**Comment by quellamomo** [comment]
```
Plugin Name          Enabled Version   Path
-----------------------------------------------------------------------------------------------------------------------------------------
FFXIV_ACT_Plugin.dll True    2.6.9.3   C:\Users\Eunice\AppData\Roaming\Advanced Combat Tracker\Plugins\FFXIV_ACT_Plugin.dll
OverlayPlugin.dll    True    0.19.21.0 C:\Users\Eunice\AppData\Roaming\Advanced Combat Tracker\Plugins\OverlayPlugin\OverlayPlugin.dll
CactbotOverlay.dll   True    0.29.25.0 C:\Users\Eunice\AppData\Roaming\Advanced Combat Tracker\Plugins\cactbot\cactbot\CactbotOverlay.dll


Overlay Name URL
----------------------------------------------------------------------------------------------------------------------------------------
dbm          file:///C:/Users/Eunice/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/cactbot/ui/raidboss/raidboss.html
dpscount     file:///C:/Users/Eunice/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/cactbot/ui/dps/rdmty/dps.html
death        file:///C:/Users/Eunice/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/cactbot/ui/oopsyraidsy/oopsyraidsy.html
jobs         file:///C:/Users/Eunice/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/cactbot/ui/jobs/jobs.html
hunt         file:///C:/Users/Eunice/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/cactbot/ui/radar/radar.html
fish         file:///C:/Users/Eunice/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot/cactbot/ui/fisher/fisher.html


Various Settings                                Value
-------------------------------------------------------------------------------------------------------------------------------------
Plugin Language                                 English
Machina Region                                  Global
Game Version                                    2023.07.26.0000.0000
Inject and use Deucalion for network data       True
Hide Chat Log (for privacy)                     False
Use WinPCap-compatible library for network data False
Disable high-performance network filter         False
Disable Combine Pets with Owner                 False
Disable Damage Shield estimates                 False
(DEBUG) Enable Debug Options                    False
(DEBUG) Log all Network Packets                 False
(DEBUG) Also Show 'Real' DoT Ticks              False
(DEBUG) Simulate Individual DoT Crits           False
(DEBUG) Graph Potency, not Damage               False
(DEBUG) Enable Benchmark Tab                    False
Cactbot User Dir                                C:\Users\Eunice\AppData\Roaming\Advanced Combat Tracker\Plugins\cactbot\cactbot\user\
```

Game client initial language English, but with Chinese patch/plug-in.
The plugin language is set to Chinese, and the timeline text language is set to using the parsing plugin language (something like that, I believe Chinese? )
And no I don't see any timeline if I do countdown in summerford farms.
But the other raids are working normally, except I didn't get any trigger notification in p5s before either. Eg. I can get every trigger notification in p9s-p12s.

**Comment by Souma-Sumire** [comment]
汉化补丁无法使用ACT。

**Comment by quellamomo** [comment]
I have a friend without the Chinese patch and he also only got the triggers I mentioned in TOP. I'll try without the patch and see if they work.

**Comment by quellamomo** [comment]
worked thanks
