### ISSUE TITLE
Oopsyraidsy not being enabled

### ISSUE THREAD

**Issue by tsposato** [quisquous/cactbot#582]
I have renamed the example to oopsyraidsy.js and added the oopsyraidsy overlay
I can see the overlay (with some sample data I guess?) but it never updates.
Tried in Eden normal raids (as I can see triggers in the data folder) but nothing...
Am I missing something here?

**Comment by ngld** [comment]
Did you lock the overlay? Once you do, the sample data should vanish and real data should start appearing. AFAIK oopsyraidsy doesn't need triggers and should work pretty much anywhere.

**Comment by tsposato** [comment]
Not sure if the overlay was locked or not.
Will try it later tonight and see...

**Comment by tsposato** [comment]
This fixed it, sorry I didn't see it anywhere in the docs and the other overlays don't work like that so never even tried it :(
