### ISSUE TITLE
raidboss: ex7 Miasmic Blast doesn't always call safe spot, callout sometimes wrong

### ISSUE THREAD

**Issue by valarnin** [quisquous/cactbot#5848]
## Description

As the title says, it doesn't always call the safe spot, and sometimes when it does the called out safe spot is the wrong one for the corner

## Additional information

Observations:
1. If the safe spot is in the corner, it seems to always call it out properly (e.g. `NW` or `NE`)
2. If the safe spot is not directly in the corner, sometimes the called safe spot is inverted (e.g. `ENE` instead of `NNE`, always on the correct half of the arena though)
3. If the safe spot is not directly in the corner, sometimes it does not call out a safe spot at all

**Comment by quisquous** [comment]
Ok, maybe I'll disable that for now and do a release with other changes (unless somebody has any feedback on it).

Do you have a log where it's wrong?

**Comment by valarnin** [comment]
I have the logs but I've got no good way of pulling out distinct pulls. I only half pay attention to that trigger and by the time we wipe or clear it's already passed from my mind that it was incorrect.

**Comment by quisquous** [comment]
I'm going to disable it temporarily just to avoid complaints and we can look into it. I half remember seeing an incorrect one but I almost didn't trust myself reading it at the time. I'll look through some more video and see if I can find one.

**Comment by wexxlee** [comment]
Ok, I was misremembering about the WSW thing (my comment in #5847) - it was WNW.  So I think it's true that there is always at least one safe spot in the north half of the arena.

Not sure about the wrong calls though.  I've double-checked my (limited) vod, and compared emulator output to 7 or 8 of our pulls (using fflogs replay to confirm adds placement and where we stacked).  Maybe we need more delay on the CombatantState check? I'll try to jump in tomorrow for an hour or two to see if I can repro.

**Comment by quisquous** [comment]
I scrubbed through about 4 hours of video and verified all the calls (or at least the north half of them) and they were all correct. I thought I had seen an incorrect call during prog but I suspect that's just my brain misreading.

**Comment by wexxlee** [comment]
> I scrubbed through about 4 hours of video and verified all the calls (or at least the north half of them) and they were all correct. I thought I had seen an incorrect call during prog but I suspect that's just my brain misreading.

I was able to get in there for about 90 mins this morning, and all of the calls (at least north half) were correct for me as well.

**Comment by valarnin** [comment]
Maybe something broken with my setup then. I'll try and capture better data next time I'm in there, I still need to farm another weapon.

I'd be inclined to believe that I was misremembering a bad callout as well but I know there were times where I just got no callout at all.

I'm fine with closing this with a "can't reproduce" tag or whatever and I'll re-open or open a new one if I can get a full repro.

**Comment by quisquous** [comment]
Looking through the trigger again, my only thoughts are:
* is there a need for a delaySeconds on this trigger? I think the logic would work as-is without it
* this is a shot in the dark, I wonder if three separate getCombatants calls could cause extra delay causing some weird positioning???, and it might make sense to combine them into one
* Maybe we could add some console debugging output for detected locations of the blasts if it ends up finding an incorrect number of safe spots

**Comment by quisquous** [comment]
I have run this a bunch more and it seems correct. I'm going to close this now, but let me know if you see something awry.
