### ISSUE TITLE
Different translations

### ISSUE THREAD

**Issue by xDarkOne** [quisquous/cactbot#586]
Hi, is it possible to add - language selection?
I can make a tranlation for the popups on Russian :D

**Comment by quisquous** [comment]
Currently, there's a separate `AlertsLanguage` option.  The timeline and the triggers are all based on what ACT determines, but the triggers can have a different language in game.

I am a little bit reluctant to add new languages, as there are a LOT of triggers and timelines.  Are there other people who want this feature?  Are you committing to translating everything for the next few years?

**Comment by xDarkOne** [comment]
I'am committing to translate by myself of course. And I am not sure that this is so hard to translate things like Stack, Split, etc. So yeah, i'm going to make this for the next few years.

**Comment by quisquous** [comment]
It's not that hard for me to review, it's more that I don't want to have half-finished things, if that makes sense? If you want to send pull requests, I'd be happy to take a look.

**Comment by quisquous** [comment]
I'll close this now and look for your pull requests.  Thanks!
