### ISSUE TITLE
Eden's Promise: Litany - "Watch tethered dog" instruction not helpful

### ISSUE THREAD

**Issue by JaneSmith** [quisquous/cactbot#5860]
In Eden's Promise: Litany, there's an attack where three shadow dogs appear. The boss tethers one of them, and Cactbot instructs the player to "Watch tethered dog". The dogs then shuffle around. When they're done shuffling, a room-wide attack takes place with only a small safe spot next to the previously-tethered dog.

The instruction doesn't really help, since it gives no actual information about the coming attack or how to dodge it. I watch the tethered dog jump around... but then what? Then suddenly an AoE appears under my feet and I take damage with no time to get out of the way. It's a minor complaint in the grand scheme of things, but generally Cactbot's instructions are more clear and helpful. This one stands out to be as being confusing and not really helpful.

If the instruction were simply changed to something like "Watch tethered dog _and then stand near it_" it would be a lot more clear.

**Comment by xiashtra** [comment]
Cactbot callouts are meant as a terse reminder, not a substitute for knowing how a mechanic works.

**Comment by quisquous** [comment]
Yeah, I think that long of an instruction is maybe longer than most cactbot callouts are.

I could say `Stand behind tethered dog` or alternatively I could remove it if it's just not helpful as-is. Do either of those sound reasonable?
