### ISSUE TITLE
O8S trigger storage of  fake/true indicator for recall later. 

### ISSUE THREAD

**Issue by unfaiyted** [quisquous/cactbot#59]
Would it be possible to store the previous value for true/false for the Blizzard/Thunder indicators for recall later as an enhancement to the trigger? 

Storing a variable that is cleared on recall of the Thunder. I notice you have some suppression logic already I don't know if it would be easily doable to store the value to recall later. On recall, the trigger could say something like:

(true, false)
out thunder, in blizzard 

or something to the effect. I'm not really sure about the scope of the variables and if you could easily reference the timeline file to tell you if you are at the recall stage or if some other way would be ideal. 

Thank you!

**Comment by danakj** [comment]
Triggers can add/set variables on the |data| object, and it will persist until combat ends, so that other triggers can continue to read/modify it.

The O4S triggers have a few examples of this.

**Comment by unfaiyted** [comment]
Thank you. I am looking at that now and this is really helpful and very well should be able to figure it out

**Comment by quisquous** [comment]
I'm a little confused what you're asking about.  It individually says "Fake Thunder" and "Fake Ice: Get Out", and then on Mana Release, it repeats both of these.  Did you want them on the same line?  Are you saying you're not seeing the repeat?

**Comment by unfaiyted** [comment]
Yeah, I'm seeing the repeat just fine. I use the triggers in discord via TTS.  I was trying to make something more like this : 

 tts: function(data) {
		if (data.manaCharge == 1 || data.manaCharge == 3)
					if (data.stackFire == true)
						return 'stack up';
					if (data.stackFire == false)
						return 'spread out';
		if (data.manaCharge == 2 || data.manaCharge == 4) {
			if (data.fakeBlizzard == true && data.fakeThunder == true && data.donutBlizzard == true)
				return  'in bliz on cross';

Sorry if this is a little weird, just trying to figure it out on my own, but I don't seem to be triggering the manaCharge counter variable for the TTS.

**Comment by quisquous** [comment]
Hmm! What do your manaCharge triggers look like?

**Comment by unfaiyted** [comment]
Hey,  
I got it somewhat working today actually
Mana Charge looks like this:

{ 
	id: "O8S Mana Charge",
	  regex: /Kefka starts using Mana Charge/,	
	  infoText: function(data) {
		if (data.manaCharge == 1 || data.manaCharge == 3)
				return 'stores next 1 fire';
		if (data.manaCharge == 2 || data.manaCharge ==4)
				return 'stores next 2 Thun/Bliz'; 
		return 'Storing'
	  },  
	  run: function (data) { data.manaCharge = (data.manaCharge || 0) + 1; },
	},

I basically dont think it needs any infoText but I wanted to track it working or not originally. 

I need to further suppress the duplicate callouts to clean it up more and figure out the correct callouts for Flagrant Fire but I'll see if I can figure that out too. After already clearing the fight it's probably not at all necessary but I still think it could be worth it if it was cleaned up.
