### ISSUE TITLE
No Cactbot type in drop down menu

### ISSUE THREAD

**Issue by xDazae** [quisquous/cactbot#590]
Hey, unfortunately i have been having issues with trying to get cactbot installed. It was working before but after trying to update it, it stopped working. So i tried just reinstalling EVERYTHING, deleting ACT and reinstalling it, the overlay plugin, and then cactbot. But it doesnt seem to work. I can get everything to work up until trying to make a new cactbot overlay type. The option for cactbot is never there. I've tried restarting, using winRAR, making sure i unblock everything. And even resetting my pc completely. But yet i still cant seem to get cactbot option in the type for a new overlay. Any suggestions would be great T.T

**Comment by quisquous** [comment]
I would say unblock all the DLLs in your ACT folder (or make sure all the zips you use have been unblocked before unzipping).  Is there a CactbotOverlay.dll in your OverlayPlugin/addons folder?

**Comment by xDazae** [comment]
Yeah, i looked up a lot of others that have had this issue in the past, and followed most of the advice. Making sure the CactbotOverlay.dll was in the OverlayPlugin/addons folder, and unblocking everything and double checking. What im curious is, is if the files are automatically compressed does it matter? I've tried extracting with WINrar and other zip programs, extracting them to the ACT folder, and I've also tried just copying and dragging it over to the ACT folder, and also copying and pasting. But none of these methods have worked for me. 

I'm using all the up to date githubs, and are all in the right places (also note that ive tried just making another folder in windows(C:) and try to not use program files (x86) but that didnt work either)

![image](https://user-images.githubusercontent.com/54755026/64084980-adee1700-cccb-11e9-8f81-e3b32222eb3b.png)
![image](https://user-images.githubusercontent.com/54755026/64084998-ca8a4f00-cccb-11e9-9bad-ac0ea12c9dcb.png)

But still no option for cactbot in dropdown
![image](https://user-images.githubusercontent.com/54755026/64085045-0e7d5400-cccc-11e9-8fe2-f00c2cf39d33.png)

**Comment by Akurosia** [comment]
I think your folder structure is not correct.
Based of your OverlayPlugin.dll, your cactbot files should go into 
"C:\Program Files (x86)\Advanced Combat Tracker\overlay\addons" and "C:\Program Files (x86)\Advanced Combat Tracker\overlay\cactbot".
Yours is currently here: "C:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin\addons" and "C:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin\cactbot".
Try changing it and report what happens than.

**Comment by xDazae** [comment]
@Akurosia holy crap... that was it... LOL im so dumb, i didnt know the CACTBOT files needed to be with the overlay plugin files, i thought as long as they were in the ACT folders theyd work.. WOW thanks so much it actually works now. all this time it was as simple as that. But i appreciate your help so much

**Comment by quisquous** [comment]
For what it's worth the cactbot folder can go anywhere.  The cactbot dll definitely needs to go inside the overlay plugin addons folder.  Thanks for the help, @Akurosia!
