### ISSUE TITLE
Option to increase texts time display

### ISSUE THREAD

**Issue by ddc** [quisquous/cactbot#591]
Hi, is it possible to add an option to increase the time display on "Alarm Text", "Alert Text" and "Info text" in raidboss.js, they disapear real quick.
 I was thinking about adding to my "user/raidboss.js" file like:

Options.DisplayAlarmTextForSeconds = 5;
Options.DisplayAlertTextForSeconds = 5;
Options.DisplayInfoTextForSeconds = 5;

**Comment by quisquous** [comment]
This is a great idea, thanks! Would you want different texts to have different lengths, or would a single option work just as well?

**Comment by ddc** [comment]
Well lengths for each one, like my example above, would be better, so we can have more flexibility on them.

**Comment by quisquous** [comment]
That's true, but I was just curious if you personally would set these to different values.

**Comment by ddc** [comment]
+ Well, I know ACT has its own triggers system and cactbot have "jobs.js", but I also use catcbot to alert me about lots of things, because I can see the text on my screen, and I like to keep my screen "clean" :D
+ Maybe another option as well, would be a custom text to be displayed on screen instead of those three, maybe.
+ Here are some examples, maybe I should replace those "infoText" on my examples bellow with "userInfoText" and increase the timer on them so they can stay longer on screen and dont overlap with others texts from cactbot:

```js
Options.SpokenAlertsEnabled = true;
var swiftCastReady = 'Swiftcast is ready';
var exitOpen = 'Exit is Open';

Options.Triggers = [
	{
		zoneRegex: /.*/,
		triggers:
		[
			{
				regex: /^(You use Swiftcast.)$/,
				delaySeconds = 59;
				infoText: 'swiftCastReady',
			},
		],
	},

	{
		zoneRegex: /.+(Palace Of The Dead)$/,
		triggers:
		[
			{
				regex: /The Cairn of Passage is activated!/,
				infoText: exitOpen,
			},
		],
	},
];
```

**Comment by quisquous** [comment]
Ah, in these cases you can use `durationSeconds` in these triggers to extend the length of the time it is on screen.  Does that help?

**Comment by ddc** [comment]
Yes, `durationSeconds` will work just fine with those examples. I didnt know about that variable.

**Comment by quisquous** [comment]
Oh, great! If you haven't seen it, this doc talks about all the trigger fields: https://github.com/quisquous/cactbot/blob/master/ui/raidboss/data/README.md
