### ISSUE TITLE
Cactbot randomly stops working.

### ISSUE THREAD

**Issue by nopi1001** [quisquous/cactbot#592]
I recently started using cactbot's raidboss plugin for FFXIV. I have been using ACT, with the Kagerou overlay, for some time now and decided to look into more ACT plugins. Raidboss worked perfectly for about 2 days until I got into a Titania EX party (don't know if that is related) and everything but the general alerts (those for living dead, shirk, holmgang, etc.) stopped working. So I left the Titania EX party, tested the plugin using the dummy in middle la noscea (which worked fine) and re-entered Titania EX, and ran it multiple times, only to have cactbot cease functioning again at what seemed to be random points early in her fight (working for 2-4mins then stopping (save the general alerts)). I have tried a fresh install of ACT, Kagerou, and cactbot to no apparent success. Restarting ACT itself (or reloading the raidboss overlay) has no apparent effect on it randomly stopping either.

After shutting down my computer last night and logging into FFIXIV, cactbot worked perfectly for Titania EX and other dungeons throughout the evening but stopped functioning when I entered Crown of the Immaculate EX (except for the general alerts. again, not sure if the EX trial itself is relevant).

When it randomly stops and starts working, I am not doing anything with ACT besides showing/hiding the Kagerou overlay (both it and ACT retain full functionality). I do have moderate experience with coding, but cannot seem to find anything wrong in the code itself (doesn't mean there isn't, just that my hypotheses for why the cactbot plugin was losing most of its functionality were wrong). I am also receiving no error messages from ACT, kagerou or cactbot.

I would greatly appreciate any insight as to why this may be happening. This plugin is awesome and would make savage content so much simpler for me if I could get it to function properly on a consistent basis.

Thanks in advanced for any help!

**Comment by quisquous** [comment]
What do you mean by cease functioning? Timeline stops? It sounds like triggers stop, but not the general triggers?

Were there any errors in the plugin log? Do you have a network log from your fight where there was a reset?

**Comment by nopi1001** [comment]
The timeline countdown timers and triggers for the fight itself stop working but the general triggers still work. 

There were no errors in the plugin log. I'm not entirely sure where to look for the network log from the fight. Is it something that ACT handles/records itself or is it something that I'd find in the windows event viewer?

**Comment by quisquous** [comment]
The network log is a file of the form Network_(ffxiv version)_date.log and lives in your log directory.  You can find the log directory from the ffxiv plugin options (ACT -> Plugins -> FFXIV Settings -> Open FFXIV Log Folder).  Just zip it up and attach here (or upload somewhere else, since it can be big).

Does this happen constantly for you in all fights?

The only other thing I can think is that for whatever reason cactbot is getting confused and thinking your out of battle when you're not.  One thing you could do is add the verbose **cactbot/test/test.html** page and see if the combat flag flips when the timeline disappears.

**Comment by nopi1001** [comment]
The only times that the fight triggers and timelines have stopped working so far were in the dancing plague EX and crown of the immaculate EX. But it was touch and go for the dancing plague ex; working on and off seemingly at random. While the encounter triggers and timeline stopped working completely for crown of the immaculate ex. 

I have turned on the test overlay and will keep an eye on it. 

Here are the logs for the days that raidboss was acting up. The 20190829 log was when it was acting up during Dancing Plague EX, the 20190830.2019.08.31 log for Crown of the Immaculate EX.

https://drive.google.com/open?id=1DppzeZIJPGPxz3M0Bz64um5eNbbtA_d7

**Comment by quisquous** [comment]
I think this may have been fixed along with #393 in 7c86b05.
