### ISSUE TITLE
Raidboss Eureka Skoll Howl did not call out

### ISSUE THREAD

**Issue by chun1324** [quisquous/cactbot#5924]
Related file

https://github.com/quisquous/cactbot/blob/8b54321418e5144932388c3b00fbb7d78dd398ab/ui/raidboss/data/04-sb/eureka/eureka_pyros.ts#L22

## Description

Based on the record, the netRegex id may not match

## Additional information

Origin
`netRegex: { id: '46BD', source: 'Skoll', capture: false },`

To be
`netRegex: { id: '64D9', source: 'Skoll', capture: false },`

**Comment by quisquous** [comment]
Do you have a log? This seems incorrect. 0x64D9 in decimal is 25817, and https://xivapi.com/Action/25817?columns=ID,Name says that's not Howl.

**Comment by chun1324** [comment]
> Do you have a log? This seems incorrect. 0x64D9 in decimal is 25817, and https://xivapi.com/Action/25817?columns=ID,Name says that's not Howl.

My apologies, it should be 0x36DB
https://xivapi.com/Action/14043?columns=ID,Name
![image](https://github.com/quisquous/cactbot/assets/15475075/b806b7b3-b452-4023-bd7f-52d10c192917)

**Comment by quisquous** [comment]
Ah, no worries! Thanks for looking it up.
