### ISSUE TITLE
Fishing Overlay not working, log output flooding with message.

### ISSUE THREAD

**Issue by Krojack** [quisquous/cactbot#5928]
## Description
Overlay displays but does nothing. Log output is flooded with the following:

Description of the issue you're seeing.

Whenever I move my character around (walking or on mount) I get flooded with these in the log:
`Info: Fishing: BrowserConsole: TypeError: Cannot read properties of undefined (reading 'toLowerCase') (Source: file:///N:/ACTv3/plugins/cactbot/ui/fisher/fisher.bundle.js, Line: 2698)`

Whenever I cast I get the following repeated 7 times in the log:
`Info: Fishing: BrowserConsole: Uncaught (in promise) DataError: Failed to execute 'only' on 'IDBKeyRange': The parameter is not a valid key. (Source: file:///N:/ACTv3/plugins/cactbot/ui/fisher/fisher.bundle.js, Line: 15564)`

## Additional information

I've tested several types of bait and fishing locations. Same thing. Last time I fixed, which would be fishing relic state 3 & 4, it was working fine.
**The overlay DOES WORK when I Mooch but only on Mooch.**

If available, please include any logs or screenshots depicting the issue you're experiencing.

**Comment by quisquous** [comment]
See #5919 if you're interested in maintaining the fishing overlay.
