### ISSUE TITLE
0.10.9 Minor Issue

### ISSUE THREAD

**Issue by ltel77** [quisquous/cactbot#596]
Tankbusters  in Dohn Meng: Candy Cane (1st boss) and Crippling Blow (last boss) not prompting alert. Minor issue.

**Comment by quisquous** [comment]
Did other triggers work on the last boss like "look away" for imp choir or "out of front" for toad choir?

**Comment by JLGarber** [comment]
I think I've seen this before, but it was only twice, right when I submitted the fix/updates to this, so I didn't do anything about it at the time. It's probably a casing issue, specifically with:
`Aenc Thon, Lord of the Lingering Gaze`
"The/the" in the log lines seems to be random between lower and upper case, breaking the regex. This seems to happen only on the tank busters for some reason. The simplest solution is probably to add both case versions as you already do for the [basket buster](https://github.com/quisquous/cactbot/blob/e39babf8faeedaef711aa0de4931b51b55b4c036/ui/raidboss/data/05-shb/dungeon/dohn_mheg.js#L34) during trash.

I will put together a request for this quickly.

**Comment by quisquous** [comment]
I already had a patch for this locally, suspecting that was the issue.  (Sorry for collision.)
