### ISSUE TITLE
E4S boulder triggers don't work after latest FFXIV plugin update

### ISSUE THREAD

**Issue by z00z9** [quisquous/cactbot#597]
There used to be an on-screen indicator for Go East / Go West for Crumbling Down in E4S. After 2.0.4.0 update of FFXIV ACT Plugin, this indicator is no longer displayed.

**Comment by fistingus** [comment]
Same issue here.  Also, the "cardinals first" and "corners first" message that appeared after landslide aren't showing either.  The e4s.js file in the data>05-shb>raid folder has both of these pop up texts, but the e4s.js file in the data>triggers folder does not.  Don't know if that helps someone find a solution, but there it is.

**Comment by JLGarber** [comment]
Data/triggers is an old file structure and shouldn't affect things. That being said, it's near-certain this is an effect from the update. If you have a log from Titan, you might look at it to see whether the ability ID for Crumbling down matches with the triggers.

**Comment by quisquous** [comment]
I'll verify this fixes things tomorrow and push out a release.  You can downgrade to an earlier version of the ffxiv plugin until then.

Thanks for the bug report.

**Comment by Zumi81** [comment]
I can confirm that if you downgrade to FFXIV plugin version 2.0.3.2, east/west, cardinals/corners.  Triggers work again.

**Comment by quisquous** [comment]
Looks like my fix worked fine.  I'll put out a release.
