### ISSUE TITLE
NodeJS LTS 20 Support

### ISSUE THREAD

**Issue by jpdied** [quisquous/cactbot#5989]
NodeJS 18 LTS ended active support over a month ago although it still is receiving security updates. Node is pushing 20 LTS now on their website and on Windows, the winget package manager is actively trying to upgrade 18 to 20.

I propose adding support for the current mainstream v20 LTS.

When trying to set things up with 20, you get the following:
```
$ npm install
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: cactbot@0.30.9
npm ERR! notsup Not compatible with your version of node/npm: cactbot@0.30.9
npm ERR! notsup Required: {"node":">=18.10.0 <=18.18.2"}
npm ERR! notsup Actual:   {"npm":"10.2.3","node":"v20.10.0"}
```

**Comment by quisquous** [comment]
Yeah, this is a duplicate of #5910. Github has been switching over slowly today and jobs have been intermittently failing. I think I have something that should work, but need to make sure it works on both 18 and 20.

I'm going to close this as a duplicate of that other issue.
