### ISSUE TITLE
Unable to create cactbot overlay.

### ISSUE THREAD

**Issue by Aipysurus** [quisquous/cactbot#600]
Unable to create cactbot overlay using the new OverlayPlugin.dll but works with the 0.3.4.0 version.

**Comment by Akurosia** [comment]
Which "new" OverlayPlugin.dll do you mean? 
The version from @ngld ?
If so, this is still not merged (as the last updates says this is a plan for the future)

**Comment by quisquous** [comment]
Akurosia has it right here.  Sorry if the instructions weren't clear.  The new ngld version is not supported yet, but will be eventually.
