### ISSUE TITLE
Installed/reinstalled and cannot get timer lines to appear in raidboss

### ISSUE THREAD

**Issue by Spokaloo** [quisquous/cactbot#604]
![image](https://user-images.githubusercontent.com/54926190/64311379-c0c94b80-cf58-11e9-804c-4fc8582b8ffb.png)

Providing a view of my log.  Zero errors, checked rechecked directories in ACT/Cacbot.  I had this working before flawlessly.  Just rebuilt my computer and reloaded everything and this is where I am stuck.  Just looking to get my timelines to appear again at Summerford.  Text is there but no timelines. Parser is working just fine.  Stumped.   I also apologize in advance if this isn't the right place to ask these questions!

**Comment by quisquous** [comment]
What do you mean by text is there?

If you do a `/countdown 5` in Summerford, are you saying you get the alert texts and noises, but no timeline?

**Comment by Spokaloo** [comment]
Ready to test on dummy..  Before I lock the overlay all that appears is the green, yellow and red text.  No test timelines that have always been there.

![image](https://user-images.githubusercontent.com/54926190/64312051-477f2800-cf5b-11e9-8e5b-eaac1fb06373.png)

**Comment by Spokaloo** [comment]
Following up...  It's almost like I am missing the timeline file. Unsure which file in the download realtes to this issue.

**Comment by quisquous** [comment]
So if you lock the overlay, and then do a `/countdown 5`, what happens?

**Comment by Spokaloo** [comment]
One sec.

**Comment by Spokaloo** [comment]
It totally works.  Perfectly.  I assumed because the lines were no longer there something wasn't working correctly. /bow & /poke had no effect at all.

**Comment by quisquous** [comment]
I wonder if that's an emote related thing.  Do those emotes show up in your chat box when you do them?

**Comment by Spokaloo** [comment]
They do.  I will take it into a Trust dungeon and see if it is all working as before.  The response is much appreciated as well as your hard work.

**Comment by quisquous** [comment]
Happy to help!
