### ISSUE TITLE
Desync alerts for Cactbot plugin on Weapon's Refrain Ultimate ( UWU )

### ISSUE THREAD

**Issue by heiwaastralis** [quisquous/cactbot#6045]
## Description

Cactbot alert overlay works well until post-Predation. It starts drifting from the Feather rains in Active Phase 2.

**Plugins installed :**

OverlayPlugin
Cactbot

**Overlays installed :**

Cactbot Alerts
Horizon Overlay
Giving a log along the issue. I can give more logs if needed

FFXIV ACT Plugin
[Network_26907_20231214.zip](https://github.com/quisquous/cactbot/files/13692449/Network_26907_20231214.zip)

**Comment by heiwaastralis** [comment]
Extra informations :

- This is a brand new installation ( I just built my PC and it never was used before )
- My static's friend has the same issue from an older installation.
- On my old PC, it wasnt happening.

Extra bug notice :

- Cardinals safespot don't show up for Predation ( N/S/E/W , early safe, etc... )

**Comment by quisquous** [comment]
Oh I see, you're playing in French. Have you checked: https://github.com/quisquous/cactbot/blob/main/docs/FAQ-Troubleshooting.md#verify-your-language-settings-match

**Comment by heiwaastralis** [comment]
> Oh I see, you're playing in French. Have you checked: https://github.com/quisquous/cactbot/blob/main/docs/FAQ-Troubleshooting.md#verify-your-language-settings-match

Hey, thanks for the quick answer.

On my old build I was playing in french with cactbot being in english and didnt have this issue.

My friend plays in english with cactbot in english and has the issue, too.

I will try next Monday to switch my ACT to french.

**Comment by quisquous** [comment]
If they have the issue too, can you have them forward their English log here?

**Comment by heiwaastralis** [comment]
I told them, said they had no time. Can close if you'd like as per it is solved on my side.
