### ISSUE TITLE
Multiple Raidboss errors

### ISSUE THREAD

**Issue by Gridlock346** [quisquous/cactbot#605]
As of today/yesterday raidboss isn't functioning (last time I know it was working was Monday evening). Visually if I unlock the overlay I can see the examples for the alarm/alert/info text but no timeline bar examples, and no actual warnings work. This is with cactbot version 0.10.10 and ffxiv act plugin version 2.0.4.0. When ACT first loads I get these errors:

```
9/5/2019 12:02:14 AM: Info: raidboss: BrowserConsole: Uncaught SyntaxError: Unexpected token } (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/cactbot/ui/raidboss/raidboss.html, Line: 110)
9/5/2019 12:02:19 AM: Info: raidboss: BrowserConsole: Uncaught TypeError: Cannot read property 'OnDataFilesRead' of undefined (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/cactbot/ui/raidboss/popup-text.js, Line: 551)
9/5/2019 12:02:19 AM: Info: raidboss: BrowserConsole: Uncaught TypeError: Cannot read property 'SetDataFiles' of undefined (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/cactbot/ui/raidboss/raidboss.js, Line: 50)
```

Once ffxiv is open I also get these errors
```
9/5/2019 12:09:20 AM: Info: raidboss: BrowserConsole: Uncaught TypeError: Cannot read property 'OnInCombatChange' of undefined (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/cactbot/ui/raidboss/popup-text.js, Line: 545)
9/5/2019 12:09:20 AM: Info: raidboss: BrowserConsole: Uncaught TypeError: Cannot read property 'OnZoneChange' of undefined (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/cactbot/ui/raidboss/popup-text.js, Line: 542)
9/5/2019 12:09:20 AM: Info: raidboss: BrowserConsole: Uncaught TypeError: Cannot read property 'OnPlayerChange' of undefined (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/cactbot/ui/raidboss/popup-text.js, Line: 539)
```

Followed by these which repeat every few seconds
```
9/5/2019 12:08:16 AM: Info: raidboss: BrowserConsole: Uncaught TypeError: Cannot read property 'OnLog' of undefined (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/cactbot/ui/raidboss/popup-text.js, Line: 548)
9/5/2019 12:08:16 AM: Info: raidboss: BrowserConsole: Uncaught TypeError: Cannot read property 'OnLogEvent' of undefined (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/cactbot/ui/raidboss/raidboss.js, Line: 47)
```

I tried restarting everything a few times, I've tried older versions of cacbot and ffxiv act plugin, I've tried pointing the module at https://quisquous.github.io/cactbot/ui/raidboss/raidboss.html instead of the local version. I stopped short of completely reinstalling ACT because I dread having to configure everything again. Apart from that, that's pretty much where I hit the limit of my depth. Thanks for any help.

**Comment by quisquous** [comment]
The first error line about the `Unexpected token }` looks like the problem.  What do you have in your **cactbot/user/raidboss.js** file? Could you remove that temporarily (or rename it) and then try?  I suspect that will fix your problems, and that the root of it is a syntax error in your user folder.

**Comment by Gridlock346** [comment]
That was it. The error message said ui/raidboss.js so my mind didn't jump to the user file, but I had left an extra bracket in there at line 110 after deleting some attempts at modifications for e4s. Much obliged.

**Comment by quisquous** [comment]
Perfect!  Glad we could get this sorted so easily.
