### ISSUE TITLE
Cactbot is having a problem with The Unending coil of Bahamut.

### ISSUE THREAD

**Issue by kblue061** [quisquous/cactbot#6075]
I am using the Korean server and using the 6.51 fix version. There seems to be a bug in the cactbot plugin's The Unending coil of Bahamut where the spread, stack, Dynamo, and Chariot are not displayed or read in the section where the boss is Nael in Phase 2: Nael Deus Darnus and Phase 3: Bahamut Prime. If you don't mind, can you fix it? Thank you always.

**Comment by quisquous** [comment]
Could you file this in https://github.com/OverlayPlugin/cactbot/issues/new instead of in this repository? Thanks!

**Comment by kblue061** [comment]
I sent it there. Please check. Thank you.
