### ISSUE TITLE
Some are out of output. 

### ISSUE THREAD

**Issue by shin017482** [quisquous/cactbot#6079]
## Question

What would you like to ask?

* It can be awkward because I use a translator.

korea cacbot another aloalo island's tts some are out of output. 
now, patch 6.57

Is that an error?

**Comment by JLGarber** [comment]
This repository is no longer being maintained and has been archived. Please open your issue at cactbot's new home, https://github.com/OverlayPlugin/cactbot/issues. An explanation for this change can be found at https://github.com/OverlayPlugin/cactbot/issues/5
