### ISSUE TITLE
Taunts, avoidance, and one-on-one duels notifications do not work.

### ISSUE THREAD

**Issue by shs1300** [quisquous/cactbot#6080]
Stop! Please do not file a bug here. Go to <https://github.com/OverlayPlugin/cactbot/issues/new> instead.

tank  → Taunts, avoidance, and one-on-one duels notifications do not work.

**Comment by Amahamiuu** [comment]
I think you just need to simply untick the 'Raidboss' box in the cacbot page then tick and reset it. It works for me :)

**Comment by JLGarber** [comment]
This repository is no longer being maintained and has been archived. Please open your issue at cactbot's new home, https://github.com/OverlayPlugin/cactbot/issues. An explanation for this change can be found at https://github.com/OverlayPlugin/cactbot/issues/5
