### ISSUE TITLE
M4S update to undo describing Longs as 3s and 2s

### ISSUE THREAD

**Issue by pineapples3** [quisquous/cactbot#6081]
I would like an option to ignore this section of code
Several strategies decide stack positions based on Short 2, Short 3, Long 1, and Long 2 as the positions. Having the reminder describe me as Long (2 stacks) and Long (3 stacks) respectively is very confusing for that. I could not find a way to change this in config.

![image](https://github.com/user-attachments/assets/286561d8-9d64-405a-b2a9-04ff2c1dd982)

**Comment by pineapples3** [comment]
misclicked close issue

**Comment by JLGarber** [comment]
Sorry, I missed that this had been re-opened. This repository is no longer the home of cactbot. You can re-file this at https://github.com/OverlayPlugin/cactbot/issues. Unfortunately there's not a quick solution I can offer you, so let's get this moved over there and we can talk over how that might be added to the UI, or whether it's even possible.
