### ISSUE TITLE
Setting to mute all TTS / Sounds?

### ISSUE THREAD

**Issue by IrealiTY** [quisquous/cactbot#61]
Heyo,

is there a plausible way to remove all TTS' and sound playback without deleting lines + files?

**Comment by quisquous** [comment]
In the file *cactbot/user/raidboss.js* (create if it doesn't exist), add the following lines:

```
Options.SoundAlertsEnabled = false
Options.SpokenAlertsEnabled = false
```

**Comment by IrealiTY** [comment]
Thanks, I must have been blind :)
