### ISSUE TITLE
remove song for streaming

### ISSUE THREAD

**Issue by Erao09** [quisquous/cactbot#614]
Hi,
I would like to know if it possible to remove/desactivate sounds for a stream session or just to turn down them.

Thank a lot !

**Comment by JLGarber** [comment]
There's no 1-click toggle that I know of that does precisely what you want, but you can achieve much the same effect with the [cactbot/user/raidboss.js override file](https://github.com/quisquous/cactbot/blob/39cf7a464393842abfc0059f6e4dc8af41ce59ff/user/raidboss-example.js#L73). Open this file in your `cactbot/user` directory, and set the volume on lines 73-85 lower to match what you need.  You will then need to rename `raidboss-example.js` to `raidboss.js`, then reload the overlay.

**Comment by tant4lus** [comment]
You should be able to use the Windows volume mixer to turn down ACT.

**Comment by quisquous** [comment]
Agreed with either of the above options as a way to handle this.
