### ISSUE TITLE
Raidboss plugin not working since last update, throws thousands of Uncaught TypeError's

### ISSUE THREAD

**Issue by SashaFFXIV** [quisquous/cactbot#615]
Since updating Raidboss has stopped functioning entirely. In the console there are thousands of the same kind of error and a single one at the top that is different.

`10/09/2019 9:13:00 AM: Info: Raidboss: BrowserConsole: Uncaught TypeError: Cannot read property 'SetDataFiles' of undefined (Source: file:///C:/Users/User/Downloads/ACT/plugin/Overlay%20Plugin/cactbot/ui/raidboss/raidboss.html, Line: 50)`

`10/09/2019 9:13:01 AM: Info: Raidboss: BrowserConsole: Uncaught TypeError: Cannot read property 'OnLogEvent' of undefined (Source: file:///C:/Users/User/Downloads/ACT/plugin/Overlay%20Plugin/cactbot/ui/raidboss/raidboss.html, Line: 47)`

`10/09/2019 9:13:02 AM: Info: Raidboss: BrowserConsole: Uncaught TypeError: Cannot read property 'OnLogEvent' of undefined (Source: file:///C:/Users/User/Downloads/ACT/plugin/Overlay%20Plugin/cactbot/ui/raidboss/raidboss.html, Line: 47)`

`10/09/2019 9:13:03 AM: Info: Raidboss: BrowserConsole: Uncaught TypeError: Cannot read property 'OnLogEvent' of undefined (Source: file:///C:/Users/User/Downloads/ACT/plugin/Overlay%20Plugin/cactbot/ui/raidboss/raidboss.html, Line: 47)`

There is only one 'SetDataFiles' Error but there are thousands of 'OnLogEvent' Errors and it's constantly creating new ones.

I've checked raidboss.html and there doesn't seem to be anything on line 47 or line 50 pertaining to what the errors are complaining about, so I'm not sure what's wrong.

**Comment by panicstevenson** [comment]
You said the first line is different, was it `Uncaught SyntaxError` or was it the `Uncaught TypeError: Cannot read property 'SetDataFiles'`?

If you've recently upgraded, were you sure to Unblock the download before extracting the contents?

**Comment by boxoflunch** [comment]
Hey dude, i just got the same error spam with a fresh install of act and for sure unblocked everything. something is fishy.

**Comment by quisquous** [comment]
Is this still happening?

**Comment by quisquous** [comment]
I think these sorts of errors should be fixed with the ngld overlay changes.  Please update to that and file another bug and let me know if this is still happening.
