### ISSUE TITLE
Fishing Cast Time reset

### ISSUE THREAD

**Issue by JSharpie** [quisquous/cactbot#617]
I was wondering, is the Fishing UI cast time suppose to save or is it suppose to reset everytime you reopen ACT? If not, what's the file for the saved cast time?

**Comment by ngld** [comment]
The fishing time is supposed to be saved. It's saved in the browser's IndexedDB which for OverlayPlugin is in its Cache directory. Make sure ACT can write to that directory (i.e. make sure that OverlayPlugin isn't installed in `C:\Program Files (x86)`).

**Comment by quisquous** [comment]
I think this question has been answered at this point, so closing.
