### ISSUE TITLE
Malikah's Well - Intestinal Crank

### ISSUE THREAD

**Issue by cnieuweboer** [quisquous/cactbot#624]
The "malikahs_well.js" file has a mistake for the "Intestinal Crank" regex.

Line 94 is: 
regex: / 14:3CEF:Amphibious Talos starts using Swift Spill/,

Should be: 
regex: / 14:3CF1:Storge starts using Intestinal Crank/,

**Comment by Akurosia** [comment]
On the latest file the Line is 106.
Will update it later today.
https://github.com/quisquous/cactbot/blob/master/ui/raidboss/data/05-shb/dungeon/malikahs_well.js#L106

**Comment by cnieuweboer** [comment]
Thanks for the fast response.
