### ISSUE TITLE
raidboss: inconsistent "soon" colorings

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#627]
![image](https://user-images.githubusercontent.com/462317/65379383-f02bc800-dc7b-11e9-9649-92f0b64bd3fc.png)

When adding the timeline for ifrit story mode in 8a38ef3, I noticed that in the second phase (hp between 50% and 70%) that the timers ended up being colored weirdly.

I suspect that maybe when syncs happen the timer expires soon value is not reset, and so it's using the old value prior to reset.  This probably doesn't matter except in tight-ish loops like this.

**Comment by panicstevenson** [comment]
I found this in some other random testing:

![atomic ray](https://user-images.githubusercontent.com/8849608/121119526-a167ee00-c7d0-11eb-803c-bdda97379740.JPG)

Additional information is that these did not trigger the new timerbar removed transitions added in https://github.com/quisquous/cactbot/pull/3017.
