### ISSUE TITLE
Titan german weirdness

### ISSUE THREAD

**Issue by quetzalsly** [quisquous/cactbot#628]
I am using cactbot dll from releases, but the latest master branch for the actual js/css stuff.
On titan savage, when he does the first attack with 4 patterns, evil earth I think? Some really weird german stuff is spoken and the TTS can't even pronounce it properly.

(Forgot to mention I am using english, not german).

**Comment by JLGarber** [comment]
Fairly sure it's due to [line 99](https://github.com/quisquous/cactbot/blob/59c847c470e433696c8f7e31fab3379ab4873796/ui/raidboss/data/05-shb/raid/e4s.js#L99) being tagged as English rather than German. Just a typo, I'll drop a request in to fix it.
