### ISSUE TITLE
Oopsyraidsy keeps saying our Monk pulled at the Unix Epoch

### ISSUE THREAD

**Issue by ezsoftware** [quisquous/cactbot#63]
Its kind of an amusing bug but maybe 4 pulls out of 5 it shows our monk pulling something like -1519536806 seconds early, which points to the unix epoch (jan 1, 1970).

He just says he's been preparing for that pull for almost 50 years.

**Comment by quisquous** [comment]
Thanks for the report.  I need to look into oopsy a bit more.  It was working pretty well in 4.1 (although I had one report of somebody's ninja triggering the early pull) but something changed in 4.2 and it's gotten quite flaky both on early pulls but also in misassigning death reasons (or skipping things that should be mistakes).

**Comment by ezsoftware** [comment]
This is pure conjecture, but I am guessing the fight timer is initialized when the countdown starts, so I'm betting when the monk is doing his abilities to gain stacks out of combat it tracks one of those abilities as being a combat action and compares it to the fight timer, since the fight timer isn't set yet since countdown has started yet, it deducts the current timestamp from 0 and we get something that says he started 48 years and change early.

**Comment by quisquous** [comment]
I thiiiink these recent changes should have fixed this.  Let me know if you see this again.
