### ISSUE TITLE
Timers seem to hang, and act window becomes unresponsive

### ISSUE THREAD

**Issue by boxoflunch** [quisquous/cactbot#633]
this happens with levi and titan savage where the timers just stop progressing. like i'm done for the night and the timers are still displayed but stuck like this https://i.imgur.com/M5pqui1.png.

It also screws up my taskbar icon when this happens, i have a number of shortcuts on my taskbar and when the timers hang i start seeing duplicate icons or icons out of place or for example right now i have 2 times on my taskbar right now https://i.imgur.com/ZhRrGIl.png. 

audio queues get put through and my dps overlay works same as trigonometry ( which i use to track raid buffs)

this is rather peculiar.

another edit went into normal decent and the bars froze again the text on the timer bars changed colour to black and then disappeared. kind of flashed and then went blank, and tried to start up again and then froze, the act window is unresponsive and the frozen bars are blank and sitting here/ https://i.imgur.com/oPm8xvg.png.

I might just reinstall act and see if it keeps happening.

After fresh install ran a normal eden's prime and act threw up 131 error boxes and broke my alt tab. i mean alt tab still works i just can't see what i'm swapping to any more until i let go of alt tab. pretty neat. it also buggered all my icons and windows adding lines and black bars in many places. it all cleaned up once i close act through the task manager though  oh here's one of the errors

`251|2019-09-25T04:51:52.0352583-04:00|ERROR: A device attached to the system is not functioning, STACK=   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)    at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)    at FFXIV_ACT_Plugin.Overlay.OverlayManager.ShowOverlay(OverlayType type)    at FFXIV_ACT_Plugin.Overlay.OverlayData.Run(Object parameter)|6720d4af31fd2396b9059194c37d804f
`
they are all the mostly the same line just slightly different time stamps.

hmm i use mudfish do you think that's causing issues? i know it used to mess with logs, but my combat logs are fine. 

just going to keep cataloguing until i stumble upon the fix. 
had an unknown device sitting in device manager, couldn't hazard what it was all my devices were working fine, so i uninstalled it. went into another normal raid. froze again.  going to try sans mudfish. 
mudfish is not the problem.
now i'm really stumped. my task manager after the last freeze https://i.imgur.com/pMhPCDF.png
and another set of errors in the network log `251|2019-09-25T06:09:03.4820341-04:00|ERROR: A device attached to the system is not functioning, STACK=   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)    at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)    at FFXIV_ACT_Plugin.Overlay.OverlayManager.ShowOverlay(OverlayType type)    at FFXIV_ACT_Plugin.Overlay.OverlayData.Run(Object parameter)|6ebaa15933e4651b9a6ae14f87003e7b
saga may be over.
seems i can't run trigonometry with cactbot or my act explodes. 
and now for my quest to find a happy medium.

**Comment by panicstevenson** [comment]
Interesting; I don't really have much to say except that I can use the combination of Triggernometry/Cactbot/Mudfish without issue _personally_.

`A device attached to the system is not functioning` feels extremely concerning.

**Comment by boxoflunch** [comment]
yeah stuff works fine until trigonometry is added to the mix, this like 50 errors. i wish i knew what the problem was could it be my cpu i wonder? it's probably the oldest component along with my mobo in my computer. Intel core i5 2500k @ 3.3 ghz. but when i look at the load my cpu isn't even that high, i got 16 gigs of ram and that's not being tasked either, gpu is capped usually but that's normal. temps are normal all around as well.  I really wish I could figure this out.
