### ISSUE TITLE
Cactbot TTS not working 

### ISSUE THREAD

**Issue by KitsuneIna** [quisquous/cactbot#649]
I tried to install cactbot and it worked for the most part like timeline, text and alert sounds but the TTS didn't, I tried to change either both raidboss.js from user and UI folder to "SpokenAlertsEnabled: true," and it still not working.

**Comment by Akurosia** [comment]
Which tts did you tried to trigger and on which fight?

**Comment by iFral** [comment]
I have the same issue with the raidboss spoken alerts. None seem to be pushing any sound out though the alerts are being detected.

**Comment by Akurosia** [comment]
Same question as before, which trigger did you expeced the TTS output?
currently, not all triggers have assigned TTS

**Comment by quisquous** [comment]
@Akurosia: all triggers that do not have tts specified use the info/alert/alarm text as the tts text.

**Comment by Akurosia** [comment]
Ahh ok, did not know this :)

**Comment by mdale1983** [comment]
i have the same issue as poster
in raidboss.js i have: SpokenAlertsEnabled: true,
as for the alert i'm testing 
{
      id: 'General Provoke',
      regex: /:(\y{Name}):1D6D:Provoke:/,
      regexDe: /:(\y{Name}):1D6D:Herausforderung:/,
      regexFr: /:(\y{Name}):1D6D:Provocation:/,
      tts: { 
			en: 'test',
	  },
    },
but on every use of provoke nothing is called out.

**Comment by Nidra** [comment]
I have the same Problem. Not a Single tts is working with the new version.

**Comment by BristolRuss** [comment]
Yep, same. Even doing the Test commands in Summerford Farms. I can see the alerts on screen but no TTS. This was working fine before I updated to the new NGLD plugin.

**Comment by quisquous** [comment]
Whoops, thanks for the bug reports.  As y'all say, this is definitely just an issue with ngld's plugin.  I would recommend that you either apply aa07d46 locally to your files for now, or switch back to the hibiyasleep version until the next cactbot release.

Sorry about that.  I don't use tts and so I missed this.

**Comment by Nidra** [comment]
thx for the fast fix i love this tts feature :D
