### ISSUE TITLE
pullcounter doesn't work when loaded remotely

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#65]
For whatever reason, this overlay just never does anything when loaded remotely, e.g. via https://quisquous.github.io/cactbot/ui/pullcounter/pull_counter.html

There are no errors.  It's hard to breakpoint in devtools because it's probably a loading issue and that happens extremely quickly.

I was hoping that some of the more recent initialization changes would fix this magically :sparkles: but this is going to require some more investigation to fix.

**Comment by panicstevenson** [comment]
It looks like this issue is resolved; https://quisquous.github.io/cactbot/ui/pullcounter/pullcounter.html (no underscore since the file was renamed in 7987d8fd6c7bb57905a6f185a89baa915c6765eb) loads properly as a remote file for me.

**Comment by quisquous** [comment]
Super belatedly, glad this is working now!
