### ISSUE TITLE
Job Overlay

### ISSUE THREAD

**Issue by FromTheGrayve** [quisquous/cactbot#661]
Just started using this, am i supposed to see an icon of a wedge of cheese when not in combat?

**Comment by buzzsantos** [comment]
Not the same issue, but about the overlay.

Was trying to costumize the job resource bar box location, by using other coordinates, but it seems it doesn't use the new data, and goes for the old original ones.

Kinda confused how to alter this change, The lines are this ones (version cactbot-0.11.1-ngld)
File: jobs.css Path:...\cactbot-0.11.1-ngld\cactbot\ui\jobs
 `/* Relative to #bars */
#war-procs, #pld-procs, #mnk-procs, #ast-procs, #blu-procs, #drk-procs, #blm-procs {
  position: absolute;
  top: -10px;
  left: -60px;`

**Comment by ngld** [comment]
The wedge of cheese is a reminder to eat food. Once you have the "Well Fed" buff, it disappears until the buff is almost expired. [Here are the relevant settings](https://github.com/quisquous/cactbot/blob/master/user/jobs-example.js#L15-L22)

@buzzsantos I think you need to modify the position of `#war-boxes, #pld-boxes, ...` instead. Which part you trying to move? The example you showed moved the procs which doesn't seem to be what you wanted.

**Comment by FromTheGrayve** [comment]
Aha! Thanks, that makes sense. I didn't see it in any of the videos or pictures, so I thought I'd made a mistake.

**Comment by buzzsantos** [comment]
Already fix my problem, was doing it the wrong way, was altering the original file instead of the user settings

**Comment by quisquous** [comment]
Ok, sounds like you both got this solved.  Sorry that modifying the CSS is not very well documented.
