### ISSUE TITLE
rdmty dps can't sort list

### ISSUE THREAD

**Issue by amki** [quisquous/cactbot#662]
Gives this error in log:

[14.10.2019 20:06:12] Error: Failed to sort list by : System.InvalidOperationException: Fehler beim Vergleichen von zwei Elementen im Array. ---> System.Collections.Generic.KeyNotFoundException: Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
   bei System.ThrowHelper.ThrowKeyNotFoundException()
   bei System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   bei RainbowMage.OverlayPlugin.EventSources.MiniParseEventSource.<>c__DisplayClass23_1.<CreateJsonData>b__2(KeyValuePair`2 a, KeyValuePair`2 b)
   bei System.Array.FunctorComparer`1.Compare(T x, T y)
   bei System.Collections.Generic.ArraySortHelper`1.SwapIfGreater(T[] keys, IComparer`1 comparer, Int32 a, Int32 b)
   bei System.Collections.Generic.ArraySortHelper`1.DepthLimitedQuickSort(T[] keys, Int32 left, Int32 right, IComparer`1 comparer, Int32 depthLimit)
   bei System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   bei System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   bei System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   bei RainbowMage.OverlayPlugin.EventSources.MiniParseEventSource.CreateJsonData()

with this graphical output

![grafik](https://user-images.githubusercontent.com/31262/66772983-41fff080-eebe-11e9-970d-2bd396b2c4ac.png)

**Comment by amki** [comment]
I fixed this by setting "Sort By" in the MiniParse EventSource to "DPS" see 

![grafik](https://user-images.githubusercontent.com/31262/66779440-79769900-eece-11e9-9beb-b38d11838e86.png)

Should the default be None?

**Comment by ngld** [comment]
The default is `None` since most popular overlays (Kagerou, MopiMopi, etc.) already sort and sorting twice would be a waste of CPU cycles.
The exception shouldn't be happening though. I'll fix that in the next release but that's an OverlayPlugin bug not an issue with Cactbot.

**Comment by amki** [comment]
https://github.com/ngld/OverlayPlugin/commit/af35e33882b17ec582349b2f1e0277dba2dd8131 should have fixed this so I'm closing the issue. Thanks @ngld :)
