### ISSUE TITLE
New Overlay issue 

### ISSUE THREAD

**Issue by Shbounab** [quisquous/cactbot#663]
I have no idea whats the issue here but once i attach the new overlay i get this message once its finish downloading the files and it closes ACT. No issue once i go back to the older Pluging.
Fresh Install: Running Admin 64 Bit All zip files unblocked.

![ACT issue](https://user-images.githubusercontent.com/38062244/66788052-1d9f1680-eeb4-11e9-9aa9-3a30531c546c.PNG)

**Comment by ngld** [comment]
Not an issue with cactbot itself and duplicated here: https://github.com/ngld/OverlayPlugin/issues/10
Please close this issue (to save the Cactbot devs some time), we can continue troubleshooting in the other ticket.

**Comment by quisquous** [comment]
Thanks, @ngld.  Appreciate all the support work you're doing.  :)
