### ISSUE TITLE
jobs: buff tracker should track cooldowns of jobs that don't land on you

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#664]
The buff cooldown system was built on top of showing active buffs.  Currently, if you don't get hit by a buff because you're standing too far away or you're dead, you also won't see the cooldown.

This needs to get fixed so that cooldowns happen if anybody gets an effect.

**Comment by panicstevenson** [comment]
Does this depend on https://github.com/quisquous/cactbot/issues/694 / wherever the idea of party information being brought to light lives? In my line of thinking, as this would be implemented now you would be tracking buffs for people outside of your party as well (ie "missing" litany from the DRG in the other alliance).

**Comment by quisquous** [comment]
Yeah, I think you need the party info to do this properly.

**Comment by Echoring** [comment]
I have an idea. We can add a function `gainAbilityFromPartyMember` which triggers a buff tracker with duration 0 with a shared cooldown with the original one. Buff log is a little later than ability log, so if you get the buff, this missing tracker will be overwritten.
Such like this:
```
      emboldenmissingyou: {
        gainAbilityFromPartyMember: kAbility.Embolden,
        durationSeconds: 0,
        icon: '../../resources/ffxiv/status/embolden.png',
        // Lime.
        borderColor: '#57FC4A',
        sortKey: 3,
        cooldown: 120,
        sharesCooldownWith: ['embolden'],
      },
```
