### ISSUE TITLE
Update keeps prompting this

### ISSUE THREAD

**Issue by nicholasnjh** [quisquous/cactbot#665]
![image](https://user-images.githubusercontent.com/40110522/66828681-3bd44780-ef84-11e9-98d4-05db28f677c7.png)

I have no idea what to do with it , if i click yes, it prompts it up again and again and again , if i click no then obviously its no retries anymore

**Comment by amki** [comment]
This is a bug with @ngld OverlayPlugin. I had the same problem, there was a fix for the installer in https://github.com/ngld/OverlayPlugin/commit/9990b52d513b560500a5c0d399e6e139141a2061 so I guess it's already fixed for 0.7.3?
