### ISSUE TITLE
Wrong Raidboss Alert in E1S

### ISSUE THREAD

**Issue by iFral** [quisquous/cactbot#670]
In E1S, Resurrection, the alert for tanks receiving Vice & Virtue is currently treated as though a dps is getting it from the cast earlier. I am currently using the ngld beta, so this may be the source. So for the second Vice & Virtue, and the first targeting the tanks, the alert is "Puddle Spread" instead of "Tank Laser on YOU"

**Comment by quisquous** [comment]
If you still have ACT open, can you look and see if the log has:
`14:3D78:Eden Prime starts using Vice and Virtue` or `14:3D78:Eden Prime starts using Vice And Virtue`

**Comment by quisquous** [comment]
Just curious if this is a capitalization issue.

**Comment by iFral** [comment]
Pulled it out, here's the line I have there. `[21:14:52.213] 14:44EE:Eden Prime starts using Vice And Virtue on Eden Prime.`

**Comment by JLGarber** [comment]
I ran through my static's logs from tonight as well, and it is indeed cased as *Vice And Virtue* in all versions of the ability for the ACT log lines. (So are the various "Vice Of" casts in all variants.) Game log lines are cased as *Vice and Virtue*.

@quisquous Was this on the list of things panicstevenson was going to fix across the repository at some point? I feel like I remember them mentioning it previously. This feels like the third time casing on conjunctions has been an issue in English, and I believe it's popped up for French as well.

(Looking through E1S.js further, Spear Of Paradise is correctly cased for the trigger, but I'm not completely sure whether the timeline replacements are case-sensitive or not. If they are, they will need to be updated for FR and JA, and [a superfluous entry will need to be deleted for DE](https://github.com/quisquous/cactbot/blob/66784fb878e629424b14c040c7ca0adf535dd74b/ui/raidboss/data/05-shb/raid/e1s.js#L469). If they need an update, I can put together a pull request for that and fixing the trigger casing over lunch.)

**Comment by Akurosia** [comment]
If anyone has knows how to use C# we could use a parser which uses the same function as the ACT plugin itself to fix capitalization.
The used function is "System.Globalization.CultureInfo.CurrentCulture.TextInfo.ToTitleCase(@this);"
My abilities in using this is very limited but maybe the best way we could handle this.
Maybe a comparer of all abilities in C# and pythons .title() function to see if they behave the same over all abilities/status/bnpcname/locations/logmessages

**Comment by quisquous** [comment]
Sometimes this is the ACT plugin, but sometimes this is also Square Enix.  I've seen mob names have inconsistent capitalization in the network logs.

My plan at the moment is just to make German and French regexes case insensitive.  I think English doesn't have this issue quite so often.  The followup is what I talked about in https://github.com/quisquous/cactbot/issues/543#issuecomment-541355036 where I think in the long run ability names should probably go away, as they're superfluous.

Regarding timeline text replacements, that is just text that shows up in the timeline.  So, it doesn't matter what those show.  The timeline syncs do matter, but those are almost always just one or two mob names.
