### ISSUE TITLE
RaidBoss data not updating

### ISSUE THREAD

**Issue by Chocopepero** [quisquous/cactbot#69]
When I start up the RaidBoss plugin, I see the Sample Text, but I do not see the bars. 
My ACT will then start to report error messages
`2/28/2018 6:36:44 PM: Info: InitPlugin: PluginDirectory = E:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin
2/28/2018 6:36:44 PM: Info: LoadAddons: E:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin\addons\CactbotOverlay.dll
2/28/2018 6:36:44 PM: Info: LoadAddons: Cactbot.OverlayAddonMain: Initialized
2/28/2018 6:36:44 PM: Info: LoadAddons: E:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin\addons\EnmityOverlay.dll
2/28/2018 6:36:44 PM: Info: LoadAddons: Tamagawa.EnmityPlugin.OverlayAddonMain: Initialized
2/28/2018 6:36:44 PM: Info: InitPlugin: Initialized.
2/28/2018 6:37:22 PM: Info: RaidBoss: BrowserConsole: Uncaught TypeError: Cannot read property 'SetDataFiles' of undefined (Source: https://quisquous.github.io/cactbot/ui/raidboss/timeline.js, Line: 703)
2/28/2018 6:37:22 PM: Info: RaidBoss: BrowserConsole: Uncaught TypeError: Cannot read property 'OnDataFilesRead' of undefined (Source: https://quisquous.github.io/cactbot/ui/raidboss/popup-text.js, Line: 447)
2/28/2018 6:38:08 PM: Info: RaidBoss: BrowserConsole: Uncaught TypeError: Cannot read property 'OnInCombatChange' of undefined (Source: https://quisquous.github.io/cactbot/ui/raidboss/popup-text.js, Line: 441)
2/28/2018 6:38:08 PM: Info: RaidBoss: BrowserConsole: Uncaught TypeError: Cannot read property 'OnZoneChange' of undefined (Source: https://quisquous.github.io/cactbot/ui/raidboss/popup-text.js, Line: 438)
2/28/2018 6:38:08 PM: Info: RaidBoss: BrowserConsole: Uncaught TypeError: Cannot read property 'OnLogEvent' of undefined (Source: https://quisquous.github.io/cactbot/ui/raidboss/timeline.js, Line: 700)
2/28/2018 6:38:08 PM: Info: RaidBoss: BrowserConsole: Uncaught TypeError: Cannot read property 'OnLog' of undefined (Source: https://quisquous.github.io/cactbot/ui/raidboss/popup-text.js, Line: 444)
`
It's more than likely not the error from #41 ,
I figured that it was reading from the github file directly and not from my own local files.
I'm not quite sure how to fix it.

**Comment by quisquous** [comment]
There are changes to the plugin that make the current github.io files incompatible.  You should point this at your local cactbot/ui/raidboss/raidboss.html file on your hard drive and not at github.io.

What made you configure it like this? Is the @ezsoftware bundle doing this?

**Comment by Chocopepero** [comment]
I'm not sure, I pasted the most recent release over it just to see if that was the cause. Same issue.

**Comment by quisquous** [comment]
You need to change your configuration.  In the overlay config, there's a URL entry.  You need to set that to be a file on your hard drive, likely `file:///C:/Program Files (x86)/Advanced Combat Tracker/OverlayPlugin/cactbot/ui/raidboss/raidboss.html`

**Comment by Chocopepero** [comment]
I'm brilliant. I was assigning the pointer html instead of the raidboss.html itself. I apologize for the time waste.

**Comment by quisquous** [comment]
Mm, no worries at all! You're not the only person who has done that in the past few days, so I was curious what made you point it at github.io and not at local files.

In general, I think that's fine to use github.io to use the latest and greatest, but if you're using the latest files, sometimes (like now) I'm going to update the plugin and they'll break.

**Comment by ezsoftware** [comment]
Yeah looks like its a casualty of my package 📦, since that's where the pointer file is, maybe I'll have to add something to the package that points out that those files may break if pre-release cactbot changes exist and to fall back to the non-pointer file.
