### ISSUE TITLE
Cactbot prompts to update latest, but already latest (not a huge issue)

### ISSUE THREAD

**Issue by nicholasnjh** [quisquous/cactbot#690]
![image](https://user-images.githubusercontent.com/40110522/67393309-b6c8de00-f5d4-11e9-91bb-35ea4d2c3158.png)

**Comment by lakaf** [comment]
Maybe double check to see whether your loaded CactbotOverlay.dll is pointing to the right one?

**Comment by quisquous** [comment]
It seems very likely that the CactbotOverlay.dll that you are loading is the old one.

**Comment by quisquous** [comment]
Is this still happening?

**Comment by nicholasnjh** [comment]
I've replaced the file, but it still prompts.

**Comment by quisquous** [comment]
In the plugin listing, what version is your CactbotOverlay.dll?

**Comment by quisquous** [comment]
Just checking back if this is still happening, and what it prints out for your CactbotOverlay.dll version in the overlayplugin log.

**Comment by quisquous** [comment]
I'm going to close this for now.  Let me know if this is still happening.
