### ISSUE TITLE
Oopsy: Console error since latest update 0.11.2

### ISSUE THREAD

**Issue by Akurosia** [quisquous/cactbot#692]
23.10.2019 23:59:22: Info: oopsie: BrowserConsole: Uncaught ReferenceError: data is not defined (Source: file:///E:/FINAL%20FANTASY%20XIV%20-%20A%20Realm%20Reborn/AdditionalExtern/ACT/Plugins/OverlayPlugin_hibiya/cactbot/ui/oopsyraidsy/oopsyraidsy.html, Line: 68)

Happend today in Orbone but honestly dont know what triggered it exactly.

**Comment by quisquous** [comment]
Thanks! Because there aren't Orbonne-specific triggers, it had to be something in `general.js`, and I found a mistake there that is likely it.
