### ISSUE TITLE
Exposing more data about the party

### ISSUE THREAD

**Issue by veltall** [quisquous/cactbot#694]
Each trigger (e.g. `e4s.js` Pulse of the Land) has access to 2 chunks of information:

- **matches** which is the JS object containing the regex results captured by that trigger's defined pattern
- **data** which is the JS object as defined in `popup-text.js`

```js
this.data = {
      me: this.me,
      job: this.job,
      role: this.role,
      lang: locale,
      currentHP: preserveHP,
      ShortName: this.ShortNamify,
      StopCombat: () => this.SetInCombat(false),
      ParseLocaleFloat: parseFloat,
      CanStun: () => Util.canStun(this.job),
      CanSilence: () => Util.canSilence(this.job),
      CanSleep: () => Util.canSleep(this.job),
      CanCleanse: () => Util.canCleanse(this.job),
      CanFeint: () => Util.canFeint(this.job),
      CanAddle: () => Util.canAddle(this.job),
};
```
---
Regrettably this means we don't have full information about the rest of the party, since **data** only refers to the character the player is in control of. As an example, this prevents us from triggering true/false conditions based on specific debuffs/mechanics on specific people/roles.

For example, in E2s and E4s we would like to accommodate tanks' uptime in the event that both tanks and ranged DPS receive a "get away" mechanic (timed Flare in E2s and Pulse of the Land in E4s). I might be missing something but it seems impossible to generalize the trigger conditions to establish that rule; the best I can do is to hard-code the ranged DPS identities into the rule:

```js
{
      id: 'E4S Pulse / tank front',
      regex: /........:Titan:4106:Pulse Of The Land:\y{ObjectId}:(\y{Name}):/,
      condition: function(data, matches) {
        // strictly matching 2 persons' unique IDs
        return matches[1] == '10665485' || matches[1] == '106AD69D';
      },
      alertText: {
        en: 'tank in front',
      }
},
```

**Comment by JLGarber** [comment]
I believe the current status on this is one stage before "please look forward to it". Quisquous mentioned in #578 that this is something that would be awesome, but is currently not implemented. I would guess that once the integration with ngld's fork of the overlay plugin is completed, there will be more time and possibility to expose party information.

That being said, whom do you need to have the alert? You're correct that there isn't even an awful way to do this currently, but if it's just you and your local copy, and you make calls based on that, there's no reason not to hardcode it in `user/raidboss.js`. (Obviously if you're running only pickups that's not the most viable option though...)O

**Comment by quisquous** [comment]
Yeah, I'm planning to add party information to ngld's OverlayPlugin directly.

For E4S, if I were going to do this, I would do something like (handwavy code):
```
{
  // Collect up all the spread markers.
  id: 'E4S Pulse of the Land Collect',
  regex: / 1B:\y{ObjectId}:(\y{Name}):....:....:00B9:/,
  condition: function(data) {
    if (data.phase != 'landslide' && data.phase != 'armor')
      return false;
    
    // Only care about the pulse of the land prior to bombs per phase.    
    return !data.printedBury;
  },
  run: function(data, matches) {
    data.spread = data.spread || [];
    data.spread.push(matches[1]);
  },
},
{
  // Half a second after any spread markers, call out what to do.
  id: 'E4S Pulse of the Land Check',
  regex: / 1B:\y{ObjectId}:\y{Name}:....:....:00B9:/,
  delaySeconds: 0.5,
  suppressSeconds: 5,
  alertText: function(data) {
    if (!data.spread)
      return;
  
    // Ideally cactbot can tell you these two lines in the future.
    let tanks = ['Tank One', 'Tank Two'];
    let melee = ['Melee One', 'Melee Two'];
    
    let hasSpread(x) => data.spread.indexOf(x) >= 0;
    tanks = tanks.filter(hasSpread);
    melee = melee.filter(hasSpread);
    
    if (tanks.length != 1)
      return;
    let tank = tanks[0];
    
    // Clean up.
    delete data.spread;
    
    if (melee.length == 0)
      return data.ShortName(tank) + ' up front';
    else
      return data.ShortName(tank) + ' in back';
  },
},
```

You could probably do something similar for E2S.

**Comment by quisquous** [comment]
https://github.com/ngld/OverlayPlugin/pull/17 will make sending party data possible.
