### ISSUE TITLE
Error:LoadAddons

### ISSUE THREAD

**Issue by jamrocker** [quisquous/cactbot#70]
I have gotten closer than ever to getting this to work but now when I try to add a new overlay I still don't have cactbot as an option. I found an error down below that says:

3/3/2018 1:23:08 AM: Error: LoadAddons: C:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin\addons\CactbotOverlay.dll: System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at RainbowMage.OverlayPlugin.PluginMain.LoadAddons()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

What am I doing wrong?

**Comment by quisquous** [comment]
In your `C:\Program Files (x86)\Advanced Combat Tracker\` folder (or in the `OverlayPlugin` subfolder), do you have a `Newtonsoft.Json.dll` file?

**Comment by jamrocker** [comment]
No I don't.

**Comment by jamrocker** [comment]
but i copied it exactly as it extracted why would a file disappear?

**Comment by quisquous** [comment]
Are you using the rainbowmage or the hibiyasleep version of the overlay plugin? What version is your overlay plugin? (You can check either inside ACT by clicking on the plugin you've loaded, or in Windows explorer, by right clicking on the OverlayPlugin.dll and going to properties.)

**Comment by jamrocker** [comment]
i downloaded from the hibiyasleep link...but the forked one. it says 0.3.3.9.  Should I have used the one called Kagerou?

**Comment by jamrocker** [comment]
Ok I kind of think I know what I did wrong...i downloaded the folder overlayplugin-Master but there is no overlayplugin.dll in there for me to install

**Comment by jamrocker** [comment]
But that one does have the newtonsoft file lol. i am so ridiculously confused right now.

**Comment by jamrocker** [comment]
Ok so when i switch it to English there is a link to download the release and prerelease which is the 3.3.9 version. but in the folders that hibyasleep has it says 3.4.0 but I cant find a an overlayplugin.dll. am i making sense? where am i going wrong?

**Comment by jamrocker** [comment]
Woot I got it. I poked around on hibyasleeps page and found the right version!!

**Comment by quisquous** [comment]
Did you get this all working, then?

**Comment by jamrocker** [comment]
First let me say...your response time is amazing given the fact that this is software you do out of the kindness of your heart so thank you.  Very much. Cant say it enough. I did get it working but for some reason its all randomly stopped working. Not just cactbot but all of it. Just says no data to show. Cactbot raidbossy module is running at summerford farms because i can hear the sound alerts but nothing is showing up on my screen.

**Comment by jamrocker** [comment]
It seems it was my firewall

**Comment by quisquous** [comment]
Glad you got it all re-fixed!
