### ISSUE TITLE
raidboss and job create high CPU usage when active bars are up

### ISSUE THREAD

**Issue by dylanpbacon** [quisquous/cactbot#71]
CPU: i5 6600k at 4.5gz overclocked.
GPU: GTX 1080
Primary Monitor: Asus Predator 1440p 144hz
Secondary: 1440p 60hz monitor, no overlay is on this monitor though.

ACT spikes CPU usage up to 30-40% when constantly moving bars are on the screen. These include timeline bars, pull countdown bar, and job overlay timer squares. Changing the refresh rate down from 144hz to 60hz helped mitigate the CPU usage, down to ~15-20% using the test module.

**Comment by quisquous** [comment]
Can you do a test with countdown for me, with your refresh rate at 144hz?

Add the line `console.log(+new Date());` to the top of the advance() function in https://github.com/quisquous/cactbot/blob/master/resources/timerbar.js#L331.  Then reload the jobs overlay, and do a countdown in game.

For me, I get output like:
```
3/6/2018 11:27:45 PM: Info: danabars: BrowserConsole: 1520407665651
3/6/2018 11:27:45 PM: Info: danabars: BrowserConsole: 1520407665667
3/6/2018 11:27:45 PM: Info: danabars: BrowserConsole: 1520407665684
```

...which to me says that it's running every 16-17ms. CEF and overlays *should* be locked to 60fps, but you never know.  Surely something wonky is going on here.

**Comment by dylanpbacon** [comment]
My output is similarly spaced by 16-17 ms at 144hz.

**Comment by quisquous** [comment]
:thinking: How does **cactbot/resources/timerbar_test.js** perform for you in a regular browser vs as an overlay? I'm curious if it's Chrome that's being slow or if there's some config setting that's causing Windows compositing of overlays to be slow whenever they update.

**Comment by dylanpbacon** [comment]
Both Chrome and the overlay spike to 30% CPU each while the bars are running. So I think it's a Chrome thing more than an overlay thing.

**Comment by quisquous** [comment]
Yeah, that timer bar test is 3% cpu for me on m64 on my machine.  :thinking:

Maybe a trace would help.  Can you open Chrome on your machine with just the timer bar test page open.  Then open a second tab and go to chrome://tracing and follow these instructions to generate a trace file: https://www.chromium.org/developers/how-tos/submitting-a-performance-bug

Instead of submitting just save the zipped up trace file and attach it here.  You probably don't need more than like a second or two of recording.

**Comment by dylanpbacon** [comment]
Attached.
[trace_timerbartrace.json.gz](https://github.com/quisquous/cactbot/files/1799730/trace_timerbartrace.json.gz)

**Comment by quisquous** [comment]
Thanks! Renderer process looks pretty clean.  Renderer times per frame are 2ms main thread, 1.5ms compositor thread + rasterization.  Gpu process looks pretty pegged however, but it looks like it's mostly in drivers and not in Chrome.

![image](https://user-images.githubusercontent.com/462317/37246802-2ea55464-2465-11e8-9f2d-3a072316d94a.png)

I'm beginning to suspect something like:
https://www.reddit.com/r/pcmasterrace/comments/5o32vs/psa_for_people_with_144hz_60hz_dual_monitor_with/
https://www.reddit.com/r/Monitors/comments/73ifuo/144hz_causing_high_cpu_usage/

As an experiment, could you try disconnecting your second monitor and then rerunning the test bars in Chrome?

**Comment by quisquous** [comment]
If anybody is seeing this bug still, it's been reported that the ngld overlayplugin helps to address this, for whatever reason.

**Comment by quisquous** [comment]
If the ngld overlayplugin fixes this, then I'm going to close this.  Thanks again for all the debugging.
