### ISSUE TITLE
Trying to install with the new NGLD

### ISSUE THREAD

**Issue by Vakz** [quisquous/cactbot#710]
As title says trying to install with the new NGLD setup but I am getting the following Invalid Plugin error : 

"This assembly does not have a class that implement's ACTs plugin interface."

Hope someone knows a fix been driving me crazy trying to get this working, thanks in advance for any assistance and replies.

**Comment by quisquous** [comment]
Hi! It sounds like you're using the wrong cactbot version.  If you're trying to use ngld, you need to use the CactbotOverlay.dll that comes in the ngld version of the zip file.

**Comment by Vakz** [comment]
Thank you that was exactly it feel a little foolish having downloaded the wrong zip file, thanks again for your time helping and your work overall on this!

**Comment by quisquous** [comment]
No worries.  Sorry for not having a better error message.  :)

**Comment by Vakz** [comment]
Hate to post again I thought was all done, pointed Cactbot at the raidboss.html and I see the bars (but no test bars) when lock overlay is unticked but its not actually working when in a fight.
