### ISSUE TITLE
raidboss_alerts_only.html and raidboss_timeline_only.html are not being saved

### ISSUE THREAD

**Issue by ddc** [quisquous/cactbot#715]
`raidboss_alerts_only.html` and `raidboss_timeline_only.html` are not being saved.
After open ACT the location of both files are gone.

https://imgur.com/gn3Lixj

**Comment by KattTails** [comment]
Not a cactbot issue! Fixed in a preview version of @ngld's overlayplugin [here](https://cdn.discordapp.com/attachments/551892582855344128/640697326788149268/OverlayPlugin-0.9.1.7z).

**Comment by ngld** [comment]
For anyone finding this in the future: An official update with the fix is out. Just update to 0.9.2 or newer.
