### ISSUE TITLE
Raidboss Alerts and Timeline revert back to blank

### ISSUE THREAD

**Issue by mdale1983** [quisquous/cactbot#718]
When trying out the new Raidboss_alerts_only and Raidboss_timeline_only and closign ACT they revert back to about:blank with an error call out of 

_**Warning: Raiding: InitializeOverlay: Local file C:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin\cactbot\ui\raidboss\raidboss.html?timeline=1&alerts=0 does not exist!**_

Also i've noticed files for Hades ex The copied Factory and Grand cosmos but cactbot isn't updating to grab those files nor when i manually put them into the folder do they work. Not sure if they aren't ready for public use yet or what.

**Comment by ngld** [comment]
This is an issue in OverlayPlugin 0.9.1. The 0.9.2 update should fix it, you'll have to reselect those files but afterwards the URL should stay even after an ACT restart.
Also, this is a duplicated of #715.

Regarding timelines: Cactbot doesn't automatically load new files from the repo, you'll have to wait for an update or add them manually. Downloading them isn't enough, you'll have to add them to the `ui/raidboss/data/manifest.txt` as well.
