### ISSUE TITLE
Strange Error in Cactbot ngld

### ISSUE THREAD

**Issue by SufferMyDear** [quisquous/cactbot#721]
Hey gus sicne the new change to nglds Cactbot Version i get a strange error in my overlay Log.

I  am not a programmer or developer and i dont know shit about anything like this with hibiyasleep i never got any issues. Since it wil change tooo ngld soon i have no choice.

plz can tell me some1 for dummys what the problem is ?

i added a screenshot
https://www.file-upload.net/download-13772722/error.JPG.html

thx in regards

**Comment by ngld** [comment]
Don't put Cactbot in the `addons` folder. Put it pretty much anywhere else and add it as an ACT plugin. It should load correctly as long as it's not in the ACT folder and not in the `addons` folder.

**Comment by SufferMyDear** [comment]
yeah just did that  :D and it works perfectly now :D

**Comment by SufferMyDear** [comment]
but u said the same so it had to be that ;D thx anyways :)

**Comment by SufferMyDear** [comment]
man im so glad about this support here  great job ... keep it on

**Comment by quisquous** [comment]
ngld support is amazing <3
