### ISSUE TITLE
Jobs: Divination not supported.

### ISSUE THREAD

**Issue by Pirate144** [quisquous/cactbot#726]
The raid buff tracking that the jobs module can do has no support for divination at all. Every other buff seems supported even ASTs card duration were adjust for 5.0, but there is just nothing for divination.

**Comment by Pirate144** [comment]
Follow up, was able to make my own easy by adding a line of:

 "Divination: '40A8'," to /resource/lang.js
" Divination: 'Divination'," to /resources/lang/en.js (I assume you would need to make localization of the other files)
"	  divination: {
        gainEffect: gLang.kEffect.Divination,
        loseEffect: gLang.kEffect.Divination,
        durationSeconds: 15,
        icon: '../../resources/icon/status/divination.png',
        // Whatever color
        borderColor: '#9e5599',
        sortKey: 13,
        cooldown: 120,
      },
" to /ui/jobs/jobs.js"

And adding a divination icon to the resources/icon/status folder.

I don't really use github or pull requests or w/e feel free to add it as a commit.

**Comment by quisquous** [comment]
Thanks!
