### ISSUE TITLE
O7S Timeline issue

### ISSUE THREAD

**Issue by xephero** [quisquous/cactbot#73]
I know it's kind of ironic to open an issue for something I contributed myself, but I'm not sure what's going on with this one.

During resets this week, I noticed this odd behavior: https://clips.twitch.tv/GenerousProudClintmullinsLeeroyJenkins

I double checked to make sure it wasn't something I did with my local file, but it was using the 0.6.3 release version: https://github.com/quisquous/cactbot/blob/v0.6.3/ui/raidboss/data/timelines/o7s.txt

The 3653-3378 lines were totally there. So there's a few things here

1. It looks as though the the dummy lines after the jump aren't being loaded (times 3653-3378, file lines 163-166). This is the main problem.
2. The jump timing was off and Radar wasn't in the dummy future there. This stuff I can do, and is fixed by #72

I'm not sure what would cause it to not load those specific lines unless there's some mechanism that looks at jumps to filter out unreachable items.

**Comment by quisquous** [comment]
:thinking: :upside_down_face: 

```
# Should be unreachable, only here for visual continuity before/after jump
3653 "Load Air Force"
3356 "Diffractive Laser"
3366 "Diffractive Plasma"
3378 "Run Air Force"
```

**Comment by xephero** [comment]
Y'know, I looked at those numbers what felt like a dozen times in the course of writing this to make absolutely sure. I even put "3653-3378" in my issue! How silly.

Want a PR for it?

**Comment by quisquous** [comment]
I love how you also added radar in the middle of that block and we *both* still didn't see it.  Amazing.  :)
