### ISSUE TITLE
TTS broken

### ISSUE THREAD

**Issue by Mechnium** [quisquous/cactbot#730]
I've been using TTS successfully for some time now, but a recent update seems to have broken it.  I was using hibiyasleep version and had "Options.SpokenAlertsEnabled = true;" in raidboss.js in the user folder.

Not knowing why it wasn't working after the update, I uninstalled everything and started from scratch but continued to use hibiyasleep version.  Everything appears to be working fine until I turn on tts, whereas I stop getting any sounds and no tts being played.

I then saw there is a push to go to ngld.  So I uninstalled everything for a clean install and used ngld version.  I see from issue #649 there was a tts problem but looking at the popup-text.js code it seems the fix has been incorporated now.

At this point I can't get tts working for either hibiyasleep or ngld.

**Comment by panicstevenson** [comment]
Generic answer since you're saying this change only started happening after a recent update: Are you remembering to unblock the release before extracting the archive into your ACT folder?

**Comment by Mechnium** [comment]
Hello Panicstevenson, yes I am unblocking the zip before extraction.

**Comment by panicstevenson** [comment]
Interesting; is there any log output that you're seeing within the raidboss plugin itself via ACT?

**Comment by ngld** [comment]
Does TTS within ACT itself work? To test this quickly, you can go to Options > Sound Settings, set one of the options to TTS, enter some text and click the play button.

**Comment by Mechnium** [comment]
Panicsteven, the output log looks clean.  No errors.

Ngld, I'm not hearing anything when I hit the play button after setting one of the sound options to TTS and entering in some text.  Guessing this means the problem is with ACT and not cactbot?  I'll try reinstalling ACT and testing TTS again before installing the plugins.

**Comment by panicstevenson** [comment]
Depending on your timeline (real life, not cactbot), maybe you received a recent Windows update that changes how the sound options work with Windows 10? There are new advanced sound options that dictate where sound from various applications are played from.

Granted, this is not the most recent update, so it is probably safe to rule out, but it might be worth taking a peak into your Windows Sound settings.

**Comment by Mechnium** [comment]
Ok, I closed out of ff14 and tried the sound test again, and I can hear TTS in ACT.  Looks like it just doesn't like it when ff14 is running.

**Comment by Mechnium** [comment]
Ok, I got TTS working if I use the "Use Windows API Sound (No volume control, one sound at a time)" option.  When I switch to the other option, "Use WMP API Sound (Volume control, multiple sounds, slight latency)", TTS stops working.

**Comment by Mechnium** [comment]
I'm going to close the issue as it's clearly not a cactbot issue.  Best guess is I updated ACT at the same time I updated cactbot, and it was the ACT update that changed the setting.  Reinstalling ACT didn't help because apparently "Use WMP API" is the default.  Thanks Panicstevenson and Ngld for the help!
