### ISSUE TITLE
cactbot not "reading " me in game

### ISSUE THREAD

**Issue by michii88** [quisquous/cactbot#732]
SO i been recently having issues with my timelines where I am not getting notifications or timelines. However, when I add the raidboss module I can see with alerts would go as seen below.

![image](https://user-images.githubusercontent.com/35468030/68453792-40bf9c00-01bc-11ea-8fb7-9a650b5d3451.png)

When I go to use the test module it does not read anything like this 

![image](https://user-images.githubusercontent.com/35468030/68453898-7d8b9300-01bc-11ea-9c15-956d59589dc5.png)

I know there is a connection to my alerts and timelines not going off and the test being blank. I just don't know what it is. Any help please.

**Comment by Snsei987** [comment]
Do you get any error in Cactbot's logs ?

**Comment by michii88** [comment]
No this is all I can see in the log

![image](https://user-images.githubusercontent.com/35468030/68535934-b8eaa680-030f-11ea-8f86-67a81a26132b.png)

**Comment by quisquous** [comment]
It looks like it's theoretically loading the cactbot dll, but when loaded, cactbot dlls usually print some extra information, like:
```
11/9/2019 4:06:08 PM: Info: InitPlugin: PluginDirectory = C:\Program Files (x86)\Advanced Combat Tracker\RainbowMageOverlayPlugin
11/9/2019 4:06:08 PM: Info: LoadAddons: C:\Program Files (x86)\Advanced Combat Tracker\RainbowMageOverlayPlugin\addons\CactbotOverlay.dll
11/9/2019 4:06:08 PM: Info: LoadAddons: Cactbot.OverlayAddonMain: Initialized
11/9/2019 4:06:09 PM: Info: InitPlugin: Initialized.
11/9/2019 4:06:10 PM: Info: PullCounter: cactbot: 0.12.0.0 C:\Program Files (x86)\Advanced Combat Tracker\RainbowMageOverlayPlugin\addons\CactbotOverlay.dll
11/9/2019 4:06:10 PM: Info: PullCounter: OverlayPlugin: 0.3.4.0 C:\Program Files (x86)\Advanced Combat Tracker\RainbowMageOverlayPlugin\OverlayPlugin.Common.dll
11/9/2019 4:06:10 PM: Info: PullCounter: FFXIV Plugin: 2.0.4.2 
11/9/2019 4:06:10 PM: Info: PullCounter: ACT: 3.4.4.264 C:\Program Files (x86)\Advanced Combat Tracker\Advanced Combat Tracker.exe
11/9/2019 4:06:10 PM: Info: PullCounter: Language: en
```

It seems like the CactbotOverlay.dll is not running for some reason.  What version is that file?

How long has this been happening for you?

I would also suggest to not put anything directly in the ACT folder because of how it can confuse DLL loading.  It looks like your OverlayPlugin dlls are being loaded directly from the ACT root folder.  It's better to put all of OverlayPlugin in a subfolder and load the DLLs from there.  I'm not sure if this will solve your problem, but it's worth doing to avoid future headaches regardless.

**Comment by michii88** [comment]
So a few things,

I changed around my folders so that it is the same as the instructions 
![image](https://user-images.githubusercontent.com/35468030/68538772-5b6e4e00-033f-11ea-9e08-c70925c54019.png)

Secondly, this has been happening for about 2 weeks now. I tried to use the ngld version with ngld and couldn't get it to work correctly so i switched back to hibya's and my timelines havent been right since. also i made sure to download the hibyas zip from the latest update to cactbot

**Comment by ngld** [comment]
You have to use the Cactbot overlay type for hibiyasleep, not MiniParse.
What issues did you have with my OverlayPlugin?

**Comment by michii88** [comment]
that was it thank you
