### ISSUE TITLE
Fishing Timers showing nothing

### ISSUE THREAD

**Issue by Krojack** [quisquous/cactbot#733]
## Question

I've been trying to get the Fishing timers to work but they never display any data.  I see the overlay and what bait I have selected but that's all.  The cast timer just stays at 0.0 and the @ location never changes to the fishing hole I'm at.  I do see the following in my chat log.
```
You cast your line on the Norvrandt Slope.
Something bites!
You land a stormfish measuring 44.3 ilms!
```
I have ACT installed in **N:\ACTv3\** and the **cache** folder is writable as date/time stamps are recent.

Other mods like RaidBoss work just fine.

**Comment by KattTails** [comment]
Could you try catching a fish and then pasting the relevant network log lines for us to take a look at? It seems like a regexp error as the plugin is loading and displaying fine, just not parsing the fishing events.

**Comment by Krojack** [comment]
Are you referring to the FFXIV parse logs? If so I've attached them below. I caught several fish but nothing showed up in the log however it will show me changing bait.  If there is a better way to get the network log data let me know.

[Network_2044_20191114.log](https://github.com/quisquous/cactbot/files/3847717/Network_2044_20191114.log)

I've changed my real characters name to "My Character" in the log just for this upload. Shouldn't change anything though.

**Comment by KattTails** [comment]
Oh, it seems like you have the chat filter for gathering messages turned off. The overlay parses those, so you'll need to turn on 'own gatherer messages' in one of your log filters. It should work after that. I've attached an image for the option and where to find it below: 
![image](https://user-images.githubusercontent.com/12807478/68880497-47da3300-0703-11ea-9cf2-2d785656bb04.png)

**Comment by Krojack** [comment]
Just checked and it was enabled. In fact it was enabled in 2 chat tab. I tried turning it off in one of them, no change.  I enabled other fishing messages and nothing there either.  I checked network logs again and no change there.

![ff14-ss](https://user-images.githubusercontent.com/908461/68882338-f919a280-06dc-11ea-9d45-b8fd1e352c52.jpg)

**Comment by KattTails** [comment]
Do you have this option turned on inside ACT FFXIV plugin options? 
![image](https://user-images.githubusercontent.com/12807478/68882607-693d1e00-0707-11ea-96d1-ede45644842a.png)

**Comment by Krojack** [comment]
That did it... Working now, thank you. Might wanna toss this into some FAQ or a Trouble Shooting list somewhere.

Thank you much.

**Comment by KattTails** [comment]
I'll update the readme section with this now we've confirmed it. Glad you got it working!

**Comment by quisquous** [comment]
Belatedly, this is solved.  Closing.  Thanks for the investigation!
