### ISSUE TITLE
Jobs - Not showing tracking of RDM

### ISSUE THREAD

**Issue by sparkiespaark** [quisquous/cactbot#74]
I can't seem to get it to show the tracking of RDM. Only shows the lines, but it's not tracking anything such as buffs/cds etc

**Comment by danakj** [comment]
Did you add a user/jobs.js file? If so, what is in it?

**Comment by danakj** [comment]
Also, buffs go to the right of the bars, is your cactbot window large enough to show them?

**Comment by quisquous** [comment]
Have you been able to get this to work?

**Comment by quisquous** [comment]
I'm going to go ahead and close this as I can't do much without more answers from you.  Let me know if it's still broken or if there's something we can do to help.  :)
