### ISSUE TITLE
raidboss: add canned responses

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#747]
# Summary

Similar to #740, I think it would be helpful to have some canned responses for mechanics.  This should help with translations as well as with copy and paste.  This new class could provide `Response.stackMarker(target)` style functions.

One possibility here is to write functions that return some object with `infoText`, `alertText`, `alarmText`, `ttsText`, `groupText` fields.  Then maybe triggers need to grow some new property (`output`? `alert`?) that can return such an object.  Maybe it should be an error to mix this "do everything" property with standalone `infoText` style properties for simplicity.  This is not dissimilar to oopsy's `mistake` sorts of entries that can return all kinds of mistakes (or multiple mistakes).

### misc thoughts
* Unlike the regexes which live in `resources`, I think these responses could be in some separate raidboss-only file as nothing else is really going to use them.
* In order to make the tests pass, I think this new file will need to be imported for triggers testing like regexes is.  `npm run test` will let you know, I'm sure.
* Unlike regexes where there's lots of fields and lots of optional fields, these response functions should probably just take a fixed number of ordered parameters since they're likely all mandatory?
* Should conditions be included in this multi-valued trigger entry along with the various texts? My intuition says no? If that's the case, then maybe we need canned conditions as well for like "cares about magical/physical aoe" and "target is you"?

**Comment by ngld** [comment]
> Then maybe triggers need to grow some new property [...]

Can't you just do something like this?
```javascript
{
  id: 'id string',
  regex: /trigger-regex-(with-position-1)(and-position-2)-here/,
  ...Response.stackMarker('YOU'),
}
```

**Comment by quisquous** [comment]
Oh! That's nice! I knew about that in other contexts (like arrays and parameter lists), but didn't know you could do that with properties like this.

Based on experimentation, it looks like later keys redefine the values of early keys.  It still seems like it's a mistake to have a `...Response` and an `infoText` specified, imo? Or do you think maybe you'd want to overwrite the `infoText` and that's a valid use case? That kind of breaks some of the abstraction and maybe you'd want to just have a different Response for that.  Not sure how I feel.

**Comment by ngld** [comment]
I'm not sure where you see that `infoText`. I just wanted to demonstrate that you could merge the result of a function call into an object with `...`.
