### ISSUE TITLE
raidboss: convert triggers to regex helpers

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#748]
Now that #740 has landed, I think the next step is to convert as many triggers as possible to use this.  Maybe the bulk of this could be done with some crafty python scripts? I'm sure there will be some corner cases missing or maybe some new helper functions that are needed.  I would be supportive of changing one type at a time or one file at a time, or whatever piecemeal approach makes this easier to get done.  However, I think the direction is that I'd like cactbot to use these by default, and I will use them when writing new trigger files.  Patches are very welcome.

Finally, once this conversion is done, the next step is to use the translation properties that are currently only used for timelines to also be used for triggers.  This will likely need a little bit of care and attention as the regexes (even if automatically generated) are still manual and have received manual editing over time and so may not match the translation blocks any more.

**Comment by liaoarden** [comment]
Might take a stab at this over the holidays...

If I wanted to make a script as you were suggesting would `util/` be where I toss it?

**Comment by quisquous** [comment]
I think the easiest way to do it would be to just convert one type at a time (e.g. 14 starts casting).  I don't know that the script would necessarily need to get committed, since it's mostly a run once sort of thing, and future triggers can just be written correctly the first time.

**Comment by liaoarden** [comment]
Yeah, that's a good point.

I'll give the english ones a first pass and test in Trusts and then go from there. :)

**Comment by quisquous** [comment]
Sounds great! Any conversion you get done would be much appreciated.  :)

**Comment by liaoarden** [comment]
Started working on this and a basic script that goes through it has caught a lot of the easy cases! Hopefully will have something to review before the end of Christmas but one question about how you'd like the triggers structured.

In the o5n.js update for #740 there's the following:

`regex: / 14:28A3:Phantom Train starts using Doom Strike on (\y{Name})/,` becoming 
`Regexes.startsUsing({ name: 'Phantom Train', id: '28A3' }),`

Looking at the top of #740, there's also:

`Regexes.startsUsing({id: ['1C7F', '1C90'], name: 'Deathgaze Hollow', ability: 'Void Death'})`

Should the ability always be included or omitted? The ability is also in the trigger name usually so I can see the argument for dropping the ability, but maybe it's helpful for debugging to include it in the actual helpers still?

**Comment by quisquous** [comment]
My feeling is that we should drop ability names, because they make for more translation work, and the id should be unique.  Ideally the ability name should be clear from the trigger id, and if it's not, then add a comment.  Probably the ability name should be removed anywhere that it's not needed (like that Void Death example).

See this for an example: https://github.com/quisquous/cactbot/blob/master/ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.js#L795

**Comment by liaoarden** [comment]
Question about the helpers (and let me know if you'd rather see this via a CL or just more comments in here).

For e4s my startsUsing replacements generate: `regex: Regexes.startsUsing({id: '410C', source: 'Titan'}),` which seems to work.

However, for Dohn Mehg I generate:
`Regexes.startsUsing({id: '3DAA', source: 'Dohnfast Fuath'})` from `/ 14:3DAA:Dohnfast Fuath starts using Watering Wheel/` and none of these seem to work on DRK, but reverting back to the original does work.

Also looking at helpers for `starts using $ability on $target`, I assume there will also need to be a corresponding update to the matcher logic to also include some clause similar to the **TEA Chastening Heat** matching where it does get captured?

**Comment by quisquous** [comment]
> However, for Dohn Mehg I generate:
> `Regexes.startsUsing({id: '3DAA', source: 'Dohnfast Fuath'})` from `/ 14:3DAA:Dohnfast Fuath starts using Watering Wheel/` and none of these seem to work on DRK, but reverting back to the original does work.

Hmm, that's really surprising.  What is the log line where this is or isn't targetting?

If you play your network log where you ran this dungeon back in the raidboss emulator (`ui/raidboss/raidemulator.html`), does the trigger work properly?

> Also looking at helpers for `starts using $ability on $target`, I assume there will also need to be a corresponding update to the matcher logic to also include some clause similar to the **TEA Chastening Heat** matching where it does get captured?

Yeah.  You'll need to change from `matches[1]` (or whatever index) to `matches.target` etc.  I think this should all end up more readable!

**Comment by liaoarden** [comment]
> Yeah. You'll need to change from matches[1] (or whatever index) to matches.target etc. I think this should all end up more readable!

That worked! :)

>Hmm, that's really surprising. What is the log line where this is or isn't targetting?

The raw log line: 
```
20|2019-12-25T21:13:36.0650000-08:00|40011526|Dohnfast Fuath|3DAA|Watering Wheel|40011523|Dohnfast Anemone|10.70||2d769f48adaa17c244605c3bb71cd596
```

> If you play your network log where you ran this dungeon back in the raidboss emulator (ui/raidboss/raidemulator.html), does the trigger work properly?

I'll grab a full run tomorrow once DF is out of maint, re-running my partial trust logs doesn't seem to work correctly in the raidboss emulator whereas my e4s runs did.

**Comment by liaoarden** [comment]
As an aside: #881 probably keeps me from doing the replay testing on that particular trigger. I can just continuously join and quit a trust to see about getting it to work in the future.
