### ISSUE TITLE
Util: Improvements to translation tools

### ISSUE THREAD

**Issue by JLGarber** [quisquous/cactbot#749]
Per some discussion on the ARF trigger additions in #744 , it looks like updates to the translation scripts would be in order. Given that the next major patch is coming up in a month or so, I'll probably prioritize this in preparation.

Primarily, I'm looking to update `translate_fight` to add a separate translation path that would look something like this:

1. Parse the timeline file for ability IDs and boss names.
2. Issue requests to XIVAPI to pull down the appropriate translations.
3. Consolidate the data and merge it into the existing JSON output stream. (Or maybe take a trigger file as optional input and automagically append the JSON output in the right place? I'm not as comfortable with that sort of file manipulation yet, but that might be ideal.)

The clear advantage to this over FFLogs translation is that this would just pull down the needed abilities based on the timeline, with no need to cull superfluous elements. The downside is that XIVAPI (so far as I'm aware) doesn't contain CN localizations, so we would have to pull those in from elsewhere.

I think the recent changes to regex handling will probably negate the need for the trigger updates portion of `check_translation` going forward.

I'm not sure what other features would be necessary or useful while doing these updates, so please let me know what else I should consider while planning this.

**Comment by quisquous** [comment]
https://cafemaker.wakingsands.com/ is the xivapi equivalent with CN support: https://cafemaker.wakingsands.com/Action/3?pretty=true

**Comment by JLGarber** [comment]
Oh, thank you. I didn't know about that. Same format and everything. Now to read a little on Python's handling of requests...

**Comment by ngld** [comment]
If you're new to HTTP requests in Python, I'd very much recommend the [`requests` module](https://requests.kennethreitz.org/en/master/).
It makes your life so much easier compared to `urllib`.

**Comment by JLGarber** [comment]
Ah, that would be significantly easier. I looked through `urllib` a little last night, and it was... not incomprehensible, but this is way better.

Thinking through things a little more, for parsing the timeline file, is there any reason not to just look for the sync regex per line? Obviously older timelines are a little messier, but I think it's safe to assume any future timelines will include syncs for every relevant ability. Given this, what other assumptions can we make about the sync regex? I'm sort of thinking we should start with this list:

1. `00`, usually as `00:0839:[ZONE] will be sealed off`.
2. `03`, as `03:........:Added new combatant [NAME]`
3. `15/16`, as `:[NAME]:[HEX ID]:`.

That should cover 95% of cases without trouble. There's obviously going to be some special handling for `15/16` lines that include multiple matches, as in `/:Titan:(40FF|4100):/`. (I'm not completely sure on what that handling should be, since sometimes it's multiple skills that *could* happen, and sometimes it's a single skill name with multiple different IDs.) But apart from that, for each line, we can just check whether `[ELEMENT]` is already present in the `extracted_data` list, and if not, append to that list, converting hex to decimal before doing so.

That's what I've been thinking of so far, but I'd be happy for there to be a simpler setup.

**Comment by quisquous** [comment]
Sorry, I'm not quite sure what you're proposing in terms of looking for the sync regex per line, vs what's happening right now.  Could you restate?

**Comment by JLGarber** [comment]
The current setup for `translate_fight` has no support for timeline parsing whatsoever.  `check_translation` simply does a 1-1 replacement within a trigger/timeline file if the `replaceText` JSON is already present within that file. I... guess? we could extract the timeline parsing functions from `test_timeline` into `encounter_finder` (which would then need renaming,) and bring those into commonality along with everything else. I hadn't planned on that for this, but I suppose that would be best.

**Comment by JLGarber** [comment]
Before I do too much on this, I'm probably going to end up doing an intermediate pull request to move some more functionality from `test_timeline` into `encounter_finder` as common helper functions. At this point, it needs renaming due to scope expansion, but I want to be sure that it's named something that won't need to be changed again. How would we feel about calling it `timeline_utilities`, `timeline_tools`, or something similar? Those might not be *quite* right, but they feel relatively close to what we want out of this.

**Comment by JLGarber** [comment]
Haven't had a lot of time to look at this because I accidentally joined an Ultimate group, but I've at least made progress on extracting translatable items from the timeline. A step that should happen at some point is to pull the regex search functions from `check_translation` into `encounter_tools` so that we can toss those into the List Of Things To Send To XIVAPI. (Unfortunately I'm not really up to the task of moving the regex parsing over from Python to Node.js right now, so we may have to live with that for a while longer. That being said, I feel like translating the timelines is the vast majority of what we're trying to do with this utility anyway, so I'll just focus on getting that functionality in place and worry about triggers later.)

The most significant shortcoming I'm foreseeing here is that if there's a situation where an ability isn't synced for whatever reason, the sync-hunting regexes won't pick it up to translate. Not sure how to solve that one.

**Comment by quisquous** [comment]
"accidentally" joined an ultimate group :joy:

> (Unfortunately I'm not really up to the task of moving the regex parsing over from Python to Node.js right now, so we may have to live with that for a while longer. That being said, I feel like translating the timelines is the vast majority of what we're trying to do with this utility anyway, so I'll just focus on getting that functionality in place and worry about triggers later.)

Sorry, I'm not quite sure I understand what you mean about moving regex parsing from Python to Node.js?

> The most significant shortcoming I'm foreseeing here is that if there's a situation where an ability isn't synced for whatever reason, the sync-hunting regexes won't pick it up to translate. Not sure how to solve that one.

It's kind of a hack, but my common style when writing timeline is to just comment out syncs for entries that have ability ids but I don't want synced.  Maybe it could handle that?

**Comment by JLGarber** [comment]
Oops, yes, that wasn't terribly clear. I was referring to `parse_translation()` in [`check_translation`](https://github.com/quisquous/cactbot/blob/c3dc05a427aae1bd8d185dd7018f80753963bd5c/util/check_translation.py#L128).

> It's kind of a hack, but my common style when writing timeline is to just comment out syncs for entries that have ability ids but I don't want synced. Maybe it could handle that?

Good point, that would be relatively trivial to handle. I haven't done that for my previous timeline work, but I can going forward, and "every action has an associated ID to sync to" as a going-forward assumption makes sense.

**Comment by JLGarber** [comment]
Haven't had much time to look at this because of US Thanksgiving this week. I'm wondering at this point whether there are any known deficiencies in CafeMaker? I'm thinking here that it's kind of messy to be sending requests to two different locations when we could just have all required language columns return from CafeMaker, so why even bother with XIVAPI. But of course if they don't update as fast as XIVAPI after a patch, it would make sense to use both.

**Comment by quisquous** [comment]
Yeah, I don't know how fast CafeMaker updates.  If it's just a url though, it seems fine enough to just have a single url, and we could modify it later if we need to.

**Comment by JLGarber** [comment]
That's fair. I'll just set it up to use CafeMaker for now then, and if that proves problematic after updates we'll make changes from there.

**Comment by JLGarber** [comment]
Whee, haven't had a whole lot of time to look at this, but it's nearly there. I'm a bit stuck on the `buff_match` function though, either it's bugged or I'm missing something that should be drastically obvious. (It's separately bugged in that it assumes a 7-character ObjectID rather than 8, but I'll fix that regardless in the next pull request.)

[`1A:.......:(.+) gains the effect of (.+)( from)?`](https://github.com/quisquous/cactbot/blob/00fc885f8cef3a4d0e8fba38bd017ceb2fbffad9/util/encounter_tools.py#L145) seems like it will only ever give a useful first match group, as the second `(.+)` will eat the space and "from [SOURCE]" indiscriminately before the last match can see them. 

I think it wouldn't be a problem just to use `1A:........:(.+) gains the effect of (.+)`, and assume we will never need to know a source for timeline purposes. (There aren't any current timelines that use the source for buffs, and I can't imagine a situation where it would be necessary.)

Aside from that, it's nearly done. Cafemaker doesn't seem to have the same search endpoint format that XIVAPI does, so for now this doesn't have Chinese support and just uses XIVAPI, but it runs twice as fast as FFLogs translation. I haven't yet added in support for API keys, but that will be easy. (That will speed execution up by 2-3 seconds since the XIVAPI rate limit should take effect at most once with a key.)

**Comment by quisquous** [comment]
Yay!  I figured you were probably busy and I knew it'd just be a matter of time before you got back to this.  :)

In terms of regular expressions, I think you can make it `.+?` which will not greedily grab the `from` part.  I'm surprised you'd want the `( from)?` to be optional, as I thought every effect had a source.

This is an example of the output of `Regexes.gainsEffect`: `/^.{14} 1A:[0-9A-F]{8}:(?<target>.*?) gains the effect of (?<effect>Final Word: Contact Prohibition) from (?<source>.*?) for (?<duration>-?[0-9]+(?:[.,][0-9]+)?(?:E-?[0-9]+)?) Seconds\./`

Oh interesting, re: search endpoint format.  What search were you using?  Is this for effects?

**Comment by JLGarber** [comment]
That will work only if the line in the timeline file has the full 1A string. (That is, `1A:........:[TARGET] gains the effect of [EFFECT] from [SOURCE] for [FLOAT] seconds`, as opposed to `1A:........:[TARGET] gains the effect of [EFFECT]`. ` from` is non-optional in this scenario, as if we make the third capture optional the second will simply match the first letter of [EFFECT].) Currently it looks like all timeline files follow the second convention.

Maybe instead of trying to do it all in a single line, I'll just use the regex as-is and do a second step to extract the actual effect, something like `buff_match[2].split(' from')[0]`? Probably simpler than trying to change things around in the tools file.

(I can't put my hands on any examples right now, but I'm relatively sure I've seen log lines in that second format before. It's definitely not common, and it might have just been soon after a major patch.)

The search format XIVAPI uses is https://xivapi.com/search?indexes=PlaceName&string=Neurolink+Nacelle&columns=Name_en,Name_fr. This fails when used in Cafemaker, as https://cafemaker.wakingsands.com/search?indexes=PlaceName&string=Neurolink+Nacelle&columns=Name_en,Name_fr. It's very possible I'm misunderstanding something here, but a hunt through the machine-translated documentation didn't turn anything up for me on that. (Direct searches by ID function identically between XIVAPI and CM, as with https://xivapi.com/action/4345 vs https://cafemaker.wakingsands.com/action/4345.)

**Comment by quisquous** [comment]
`translate_fight` doesn't exist any more, so closing this issue.
