### ISSUE TITLE
Cactbot Raidboss timeline sticking on screen (Summerland Farms Test)

### ISSUE THREAD

**Issue by dencur** [quisquous/cactbot#758]
Installed the latest ngld version 0.12.2.  

Went to summerland farms did a countdown 5 to test after setting my ui back up.

There is an issue with the timeline bars sticking on the screen.  See video attached.

https://streamable.com/g8suq

I completely disabled my custom configuration raidboss before testing this.   Let me know what else I can provide!

**Comment by dencur** [comment]
Also seeing this in the overlay log:

**Comment by ChristianIvicevic** [comment]
I noticed that the bars work correctly after using the Timeline only version, but the alarms are behaving odd unfortunately.

**Comment by dencur** [comment]
Just noting that this may be a duplicate of #756.  Also seeing the error they noted, but the symptom is that the timelines are broken.

**Comment by KattTails** [comment]
matches and/or matches.group are sometimes undefined and not properly checked. I've submitted a fix but for now you could downgrade to the previous version,

**Comment by dencur** [comment]
Tested and validated that @KattTails 's fix corrects the problem I was seeing 💯 🎉

**Comment by panicstevenson** [comment]
Can anyone replicate this issue outside of the Summerford Farms test? I've attempted it in a few trials, but I can't reproduce this issue outside of the dummy testing.

**Comment by KattTails** [comment]
I haven't gone into the trial but through some manipulation of the timeline files and /echo it looks like parts of the titania normal trial might trigger it. I can try and test it.

**Comment by KattTails** [comment]
About 55s into The Great Hunt (Extreme) unsynced I was able to produce the error: `[15/11/2019 4:40:55 AM] Info: Cactbot-RaidbossAlerts: BrowserConsole: Uncaught TypeError: Cannot read property '1' of undefined (Source: file:///C:/Users/EspyE/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot-ngld/ui/raidboss/raidboss.html?timeline=0&alerts=1, Line: 46)
[15/11/2019 4:41:12 AM] Info: Cactbot-RaidbossAlerts: BrowserConsole: Uncaught TypeError: Cannot read property '1' of undefined (Source: file:///C:/Users/EspyE/AppData/Roaming/Advanced%20Combat%20Tracker/Plugins/cactbot-ngld/ui/raidboss/raidboss.html?timeline=0&alerts=1, Line: 46)`

I have temporarily set Options.SpokenAlertsEnabled = true; in user\raidboss.js. During debugging the test.js, the call stack would point to the `Alert(text)` and `TTS(text)` functions as the origin of the error, calling OnTrigger() with only a text argument, leaving matches undefined.
