### ISSUE TITLE
raidboss not working with new version

### ISSUE THREAD

**Issue by Daojim** [quisquous/cactbot#76]
Hey, I just installed cactbot for the first time with 0.6.4 and I noticed that there weren't any test bars with raidboss module. Then, when I tried to test it on the striking dummy at Summerford Farms, it didn't work after setting it up.

I downloaded and installed Cactbot 0.6.3 and the raidboss module worked fine, didn't even change the settings of the module previously. Got to see the timeline and the alert texts. When I redownloaded 0.6.4, it just seems that raidboss doesn't work.

**Comment by noxaeternus** [comment]
Same here. It's not just Raidboss but also DPS parser etc. None of the overlays works since 0.6.4.

**Comment by sergserg2** [comment]
Same with DPS parser.

**Comment by quisquous** [comment]
Are there any errors in the OverlayPlugin log if you go to Plugins -> OverlayPlugin.dll in ACT and look at the list at the bottom? Could you also paste the version numbers and locations of all the DLLs from the output log?

Out of curiosity, do any of y'all use tts? That sounds silly, but overlays now wait for a bunch of things to load before starting and the same method it uses to talk to the plugin is what it uses for tts.  If you were on a slightly outdated OverlayPlugin then you might not have plugins start any more.

**Comment by ThanatosIruga** [comment]
I use hibiyasleep OverlayPlugin 0.3.4.0 and have the same issue.
I use TTS.

**Comment by noxaeternus** [comment]
0.3.4.0 here too and no errors.

**Comment by Melfice** [comment]
Updated no newest realease and now everything also doesn't work for me.
He's errors from overlay plugin on load.
14.03.2018 13:36:14: Info: deathreport: BrowserConsole: Uncaught ReferenceError: UserConfig is not defined (Source: file:///C:/Program%20Files%20(x86)/ACT/OverlayPlugin-0.3.3.14-x64-full/cactbot/ui/oopsyraidsy/oopsyraidsy.js, Line: 940)
14.03.2018 13:36:14: Info: cactbot: BrowserConsole: Uncaught ReferenceError: UserConfig is not defined (Source: file:///C:/Program%20Files%20(x86)/ACT/OverlayPlugin-0.3.3.14-x64-full/cactbot/ui/raidboss/raidboss.js, Line: 39)

**Comment by quisquous** [comment]
Sorry for the hassle, y'all.  I've marked 0.6.4 as a prerelease so other folks won't get notified of an update.  I'll try to provide a build with debugging info here tonight.

These changes to overlay initialization worked for me locally and for two other folks, so I thought it was good enough to go out.

**Comment by noxaeternus** [comment]
No worries man. Keep up the good work. This is what backups are for :)

**Comment by Melfice** [comment]
Disregard my previous report with UserConfig errors - was my own fault, didnt update resources folder (assumed nothing changed there) - that's where error came from.
Made clean install of 0.6.4 - it still didnt work, no errors in log. Just silently loads like everything is fine, but nothing is working.

**Comment by Melfice** [comment]
Out of curiousty loaded 0.6.4 dll with all resource and script files of 0.6.3 - not working, so probably something wrong in source.

**Comment by toxictaru** [comment]
same for me. I replaced the new addon and folders but nothing shows. took old addon and folders back out of the trash can xD works again. thankfull im not the only one so im not being stupid i guess

**Comment by sergserg2** [comment]
no TTS

14.03.2018 19:51:41: Info: oopsyraidsy: cactbot: 0.6.4.0 C:\Users\bob\AppData\Roaming\Advanced Combat Tracker\Plugins\OverlayPlugin\addons\CactbotOverlay.dll
14.03.2018 19:51:41: Info: oopsyraidsy: OverlayPlugin: 0.3.4.0 C:\Users\bob\AppData\Roaming\Advanced Combat Tracker\Plugins\OverlayPlugin\OverlayPlugin.Common.dll
14.03.2018 19:51:41: Info: oopsyraidsy: FFXIV Plugin: 1.6.2.5 
14.03.2018 19:51:41: Info: oopsyraidsy: ACT: 3.3.1.256 C:\Program Files (x86)\Advanced Combat Tracker\Advanced Combat Tracker.exe

**Comment by quisquous** [comment]
Let me know if 0.6.5 doesn't fix this for anybody.  Sorry again!
