### ISSUE TITLE
Cactbot timers lag heavily with NGLD

### ISSUE THREAD

**Issue by Drudicta** [quisquous/cactbot#762]
Testing in Summerford farms does not work at all, it acts as though nothing happened.

And testing Kefka, he will sue Hyperdrive on me and then when he's about to use Ice Tomb Cactbot will start screaming at me about Hyperdrive with 5 lines all stating it's in 8.6 seconds and text covering the center of my screen.

As of the moment I'm completely unable to use it.

**Comment by ngld** [comment]
Check your overlay log for errors. This is most likely a duplicate of #756 and #758.

**Comment by Drudicta** [comment]
You might be right. Though the errors I'm getting are;

[11/15/2019 10:25:24 AM] Info: WS: Warn: The current logging level has been changed to Info. 
[11/15/2019 10:31:16 AM] Info: Raidboss: BrowserConsole: Browser crashed! (OutOfMemory) Trying to restart. (Source: internal, Line: 1)

**Comment by ngld** [comment]
Do you have a custom `raidboss.js` in your `user` folder? In that case, this might be the same issue as #764.

**Comment by Drudicta** [comment]
Using the one that came with Cactbot currently. And searching my user folder, I do not. And I don't know why I didn't think of this earlier, but would clearing OverlayPluginCache possibly fix issues I'm having?

**Comment by ngld** [comment]
I don't think it's going to help but you can try... Deleting the cache folder won't break anything.

**Comment by Drudicta** [comment]
Fixed with latest update.

Thank you! :D
