### ISSUE TITLE
raidboss popup alert [tankbusters]

### ISSUE THREAD

**Issue by ashkelia** [quisquous/cactbot#763]
I just switched to ngld. i set everything up and went to summer to test. all popup alerts worked except the tankbuster. i tested it in susano ex and it was the same. 
no errors were shown in the log.
can do additional testing, just let me know where/how.

**Comment by panicstevenson** [comment]
Hey there, thanks for submitting this bug report.

I'm assuming with how you've written this that you've been using Cactbot for a while and recently migrated from RainbowMage to ngld. For these, I'm curious how you tested in Susano Ex; as it's currently written, `Assail`, the tank buster in the first phase does not have any trigger and only shows the timeline entry. The same is true for the striking dummy's "Super Tankbuster".

A good test fight for this would be entering Turn 5 solo as a tank; the only mandatory aspects for tank buster triggers are that you are either a tank or you're a healer healing a tank, other than that they're the same as any other trigger. Twintania should Death Sentence less than 30 seconds into the fight, and should display `TANK BUSTER ON YOU`.

**Comment by Webberjo** [comment]
Susano's tank buster is called Stormsplitter. Assail is the mini buster.

**Comment by panicstevenson** [comment]
Right; there’s no trigger for Assail, only a timeline entry.

**Comment by quisquous** [comment]
For what it's worth, there is also no alert for the "Super Tankbuster" in the test script.  It's just in the timeline (if you're a tank or healer).

**Comment by quisquous** [comment]
Ok, sounds like this is working, just maybe wrong expectations for what has triggers and what doesn't.  Let me know if I'm misunderstanding.
