### ISSUE TITLE
CefSharp.BrowserSubprocess CPU usage and Ram Usage

### ISSUE THREAD

**Issue by Eliteneet** [quisquous/cactbot#764]
## Description

ACT 3.4.5
NGLD 0.10.1.0
CactBot 0.12.2

Modules:
Raidboss-timeline only
Raidboss-Alerts only

I don't know if its cactbot causing this high usage or ngld, but one of them is causing huge amount of fps drops. I noticed very high cpu usage (25%-60%) and very high ram usage (2-5 gigs) and very high read/write to the ssd.

## Additional information

<img width="355" alt="cef" src="https://user-images.githubusercontent.com/2501786/68980691-08205380-07b6-11ea-916e-9e83ff88aa81.PNG">

**Comment by ngld** [comment]
How big is your log file? The last time I saw an I/O rate like that, the network log was getting spammed with errors.

Are there any errors in the overlay log? That's the text box below your overlay settings.

**Comment by Eliteneet** [comment]
<img width="404" alt="cef2" src="https://user-images.githubusercontent.com/2501786/68985422-365c5e00-07cb-11ea-8e1c-5cc9ba1dca26.PNG">

That log file is 17 mb, its one of the smallest ones.

No errors in the overlay log.

**Comment by Eliteneet** [comment]
It seems to have been my user/Raidboss.js

I don't know what I might have messed up in there but deleting that has fixed it so far. I'll continue testing.

**Comment by KattTails** [comment]
Hi, 
When the spikes occurred what were you doing in-game? Were you in an instance or other combat or for example idle in a city? Thanks.

**Comment by Eliteneet** [comment]
It would start a couple minutes after starting ACT, it didn't matter if I was in combat or not, just idle in housing area. It would not stop and would just get worse until I closed ACT.

Like I said before though it was resolved by deleting my my custom raidboss.js, I only had the option to enable TTS and some basic TTS triggers.

**Comment by quisquous** [comment]
That's wild.  Do you know what was in your old user/raidboss.js so that you could recreate this? Just curious what exactly it was that was causing this.

**Comment by Eliteneet** [comment]
Definitely user error nothing on your guys side.
