### ISSUE TITLE
Job buffs track

### ISSUE THREAD

**Issue by Inferitus** [quisquous/cactbot#77]
Heya!
So I have a little problem with my bottom buff tracker, it shows wrong time and act wierd as it counts dowm..,
eg.: for warriors it tracks the Storm's Eye buff that have a duration of 30s, but the tracker shows the number 13 and the countdowns ticks every 3s. Same with the PLD and so on...

**Comment by Inferitus** [comment]
Things seems to have their refresh rate really low here... The count down ticks every 2~3s, so it's never the same with the in game real countdown

**Comment by danakj** [comment]
Its showing GCDs not seconds.
