### ISSUE TITLE
Cactbot NGLD error

### ISSUE THREAD

**Issue by Tsunatus** [quisquous/cactbot#770]
Hello,

I am having an issue with the NGLD Cactbot as the raidboss overlay is not working or even initializing. The error in the log reads as:
[11/17/2019 9:57:51 PM] Info: Raidboss: BrowserConsole: Uncaught ReferenceError: UserConfig is not defined (Source: file:///C:/Users/*****/Documents/Experimental%20ACT/Advanced%20Combat%20Tracker/ACT%20NGLD%20Cactbot/ui/raidboss/raidboss.js, Line: 50)

![d5f24be42a879d112e7f1b72b69fda8d](https://user-images.githubusercontent.com/52554553/69028976-8896ae00-0988-11ea-8d2b-a74ce50b3a65.png)

![94bbb042d92f278047de350d7fd32d8d](https://user-images.githubusercontent.com/52554553/69030091-694d5000-098b-11ea-96b1-a9470ab22343.png)

**Comment by ngld** [comment]
The log is missing a bunch of messages. Did you clear it? That error is either caused by a previous error or missing/corrupt files.

**Comment by Tsunatus** [comment]
Which log, the one I posted on top is what ACT shows inside and the one on the bottom is what that error is pointing too which is line 50 of the raidboss.js which is basically a config file for cactbot asking for userconfig

**Comment by ngld** [comment]
I'm talking about the log in the screen shot. OverlayPlugin (and Cactbot) generate messages on startup. They're missing so either someone cleared the log or there are serious issues with your ACT installation.

The source code is neither a log nor a config file. We also know the source code so that picture isn't helpful.

**Comment by Tsunatus** [comment]
Newest update seems to work for me, had to reinstall everything. Before closing this, do you know why cactbot isn't ending the fight after a wipe? Been playing in alex and whenever my party wipes the encounter will end with the old cactbot for hiyabasleep and now it has to wait for the alloted time I put in the options

**Comment by quisquous** [comment]
@Tsunatus No, I'm, not sure what's going on.  I queued into Titan Extreme and wiped a few times and the ACT encounters (and cactbot timeline) all ended properly.  Feel free to file a separate issue if this is still happening for you and I can try to help figure out what might be going on.
