### ISSUE TITLE
Cactbot Eureka module bug

### ISSUE THREAD

**Issue by haojunsui** [quisquous/cactbot#771]
## Description

[2019/11/18 9:08:57] Info: eureka: BrowserConsole: Uncaught TypeError: Cannot read property 'primaryWeather' of undefined (Source: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin/addons/cactbot/ui/eureka/eureka.js, Line: 2122)

## Additional information

Also, the button to copy NM respawn does not show in the module anymore.

![image](https://user-images.githubusercontent.com/6809863/69075817-ff629400-09e6-11ea-8920-19f9645f3eab.png)

**Comment by quisquous** [comment]
As for the error, I cannot reproduce this.  What language are you trying to use this in? Is this just in anemos or in other eureka zones too?

As for the button, there was never a button to copy nm names in the overlay itself.  The documentation talking about a button is saying that from the ffxiv-eureka website, you can click the red clipboard to get a list of names you can copy and `/echo` in game.  This red clipboard icon:
![image](https://user-images.githubusercontent.com/462317/69475037-29b4a880-0d7d-11ea-9613-abee8ead098f.png)
