### ISSUE TITLE
Pullcounter module in WS mode in browser is throwing errors

### ISSUE THREAD

**Issue by ChristianIvicevic** [quisquous/cactbot#776]
## Description

The browser is throwing errors when trying to use the pullcounter module in WS mode (especially in OBS while streaming which is really helpful to find certain pull). It throws erors that claim specific events like OnLog... aren't avilable on undefined.

**Comment by quisquous** [comment]
Thanks for the bug report.  I'll try to take a look later this week.

**Comment by quisquous** [comment]
This should work now, but you'll have to wait for the next cactbot release because there's a plugin update that's required.
