### ISSUE TITLE
Cactbot not working anymore

### ISSUE THREAD

**Issue by Webberjo** [quisquous/cactbot#777]
## Description
Cactbot triggers and timeline no longer work since switching to ngld overlay.

## Additional information
When the first ngld overlay release was published, cactbot's timeline overlay ceased to function for me. It no longer appeared when doing any content whatsoever. I was able to get the test timeline to appear by doing a countdown on a Striking Dummy though.

As of today, neither timeline nor triggers work for me at all now, even the test ones. I thought maybe it was because I was still using hibiyasleep's overlay plugin, so I switched to the ngld overlay plugin in the latest release and copied over my user folder. No change, aside from having a different overlay.
The timeline likely doesn't work because the CactbotOverlay addon from the hibiyasleep release is incompatible with the ngld release, so I can't add it to the OverlayPlugin tab like I did before.

I even tried adding a regex to my raidboss user file to capture and log everything, but for some reason it doesn't log anything.
```js
Options.Triggers = [
  {
    zoneRegex: /.*/,
    triggers: [
      {
        regex: /.*/,
        infoText: function(data, matches) {
          console.log(data); // Doesn't log anything
          return;
        }
      }
    ]
  }
];
```
I disabled the hibiyasleep overlay plugin and restarted ACT before adding and initializing the ngld overlay plugin.
The ngld overlay plugin files are in their own folder, separate from the hibiyasleep overlay plugin files.
My OverlayPlugin tab has no errors in the log.

My Plugins:
```
Assembly Info:
FileName: C:\Users\Administrator\AppData\Roaming\Advanced Combat Tracker\Plugins\FFXIV_ACT_Plugin.dll
OriginalFilename: FFXIV_ACT_Plugin.dll
FileVersion: 2.0.4.4
ProductVersion: 2.0.4.4
FileDescription: ACT Plugin for Final Fantasy XIV
LegalCopyright: © 2019 Ravahn
```
```
Assembly Info:
FileName: C:\Program Files (x86)\Advanced Combat Tracker\ngld_OverlayPlugin\OverlayPlugin.dll
OriginalFilename: OverlayPlugin.dll
FileVersion: 0.10.1.0
ProductVersion: 0.10.1.0
FileDescription: OverlayPlugin
ProductName: OverlayPlugin
LegalCopyright: Copyright © RainbowMage 2015, Kuriyama hibiya 2016, ngld 2019
Comments: Overlay plugin for Advanced Combat Tracker
```
```
Assembly Info:
FileName: C:\Program Files (x86)\Advanced Combat Tracker\ngld_OverlayPlugin\cactbot\CactbotOverlay.dll
OriginalFilename: CactbotOverlay.dll
FileVersion: 0.12.2.0
ProductVersion: 0.12.2.0
FileDescription: CactbotOverlay
ProductName: CactbotOverlay
LegalCopyright: Copyright 2017
```

Anyone else encounter behaviour like this before? Is my only option to do yet another clean install of ACT?

**Comment by ngld** [comment]
Did you add CactbotOverlay to your plugins list? Does the Cactbot version show up in your overlay log?

**Comment by Webberjo** [comment]
I hadn't tried adding CactbotOverlay to my plugins list, previously it was an addon so I didn't think to.

After adding CactbotOverlay and restarting ACT I now see it in my OverlayPlugin tab. I set the path to my custom user directory, however, cactbot triggers and timelines still don't work, even custom ones.

**Log:**
```
Info: InitPlugin: PluginDirectory = C:\Program Files (x86)\Advanced Combat Tracker\ngld_OverlayPlugin
Info: InitPlugin: Initialized.
Info: Started watching C:\Program Files (x86)\Advanced Combat Tracker\ngld_OverlayPlugin\cactbot\../cactbot/user/
Info: cactbot: 0.12.2.0 
Info: OverlayPlugin: 0.10.1.0 
Info: FFXIV Plugin: 2.0.4.4 C:\Users\Administrator\AppData\Roaming\Advanced Combat Tracker\Plugins\FFXIV_ACT_Plugin.dll
Info: ACT: 3.4.5.265 C:\Program Files (x86)\Advanced Combat Tracker\Advanced Combat Tracker.exe
Info: Language: en
Info: LoadAddons: CactbotOverlay.dll: Initialized
```

**Comment by ngld** [comment]
Please read the release notes in the future, they explained the whole update process.
Make sure you have the correct html files and overlay type (it should be `MiniParse`).
Does it show any values if you load this URL in a `MiniParse` overlay? https://rawcdn.githack.com/quisquous/cactbot/781a37e0817ddff82271b8ab49ba1b8640aa39ac/ui/test/test.html

**Comment by Webberjo** [comment]
My fault, I only glanced over the release notes and missed that one point about adding CactbotOverlay.

Yes, it shows various debug values when I use that overlay. I never said anything about the overlay not working though, it's just the triggers and timeline that don't work.

**Comment by ngld** [comment]
If the debug values are shown, then the overlay is receiving the necessary data. So you either have the wrong files (from the hibiyasleep version) or another issue. If it's the latter case, you should see errors in the overlay log.

**Comment by Webberjo** [comment]
I don't know what else to say. I downloaded the correct zip file and extracted the contents to their own folder rather than into my hibiyasleep folder. All paths are using this folder and not the hibiyasleep one.

To test, I changed the zoneRegex in `\cactbot\ui\raidboss\data\00-misc\test.js` from `/^(Middle La Noscea|中拉诺西亚)$/` to `/.*/`, reloaded the overlay, poked a striking dummy and nothing happened. 
I've done this before in the past and this should alert "Poke #".

**Comment by ngld** [comment]
Try starting a countdown in that zone instead of poking a dummy. The countdown test is generally more reliable than the poke test. If that still doesn't work, load [this URL](https://rawcdn.githack.com/quisquous/cactbot/781a37e0817ddff82271b8ab49ba1b8640aa39ac/ui/raidboss/raidboss.html) and try the countdown again.

**Comment by Webberjo** [comment]
Tried a countdown, nothing happened at "Engage!". Tried using your provided URL for the Custom User Config Directory, reloaded the overlay, tried a countdown again and once again nothing happened.

My console log in `user\raidboss.js` still isn't logging anything either, despite the regex being "capture anything".

**Comment by ngld** [comment]
Wait... you used the URL as Custom User Config directory? You have to load it through the URL field in the `MiniParse` overlay (instead of your local `raidboss.html` file).

**Comment by Webberjo** [comment]
Woops, my bad. I pasted it into the OverlayPlugin URL field, reloaded the overlay and the overlay disappeared. Doesn't even say "No data to show". Tried doing a countdown and still nothing.

**Comment by Webberjo** [comment]
After reading the recently-updated installation instructions, I now know what my problem was and why I was so confused.

In short, I was looking for something that wasn't there and assumed something behaved a way it doesn't. Don't be like me, folks.
