### ISSUE TITLE
How can I Downgrade memory signatures and offsets in newest cactbot？

### ISSUE THREAD

**Issue by ShadyWhite** [quisquous/cactbot#779]
Hi.Is it possible to Downgrade memory signatures and offsets in newest cactbot back to 5.1 before to match with Chinese server(now 5.01).How can I do this?

**Comment by quisquous** [comment]
At the moment, there's no way to easily do this, sorry.

**Comment by ShadyWhite** [comment]
I found it is feasible to repack old version FFXIVProcess.cs with newest other files by VS.It works fine after test.But I'm afraid it will expire after you simplify your code.

**Comment by quisquous** [comment]
I think this is something I'm going to need to be able to handle in cactbot without making people rebuild the plugin.  I'll try to look into what I need to do in order to do this.

**Comment by quisquous** [comment]
I filed #821 to try to fix this.  Please subscribe there for updates.
