### ISSUE TITLE
Alert customization broken

### ISSUE THREAD

**Issue by Iilease** [quisquous/cactbot#78]
Hi, 3.5 has broken alert customizations for me. In /user/raidboss.js I have set:

Options.SoundAlertsEnabled = false 
Options.SpokenAlertsEnabled = true

But sound alerts are still being played, this happens even if I set volume to 0.

Edit: Changing it directly in /ui/raidboss/raidboss.js works.

**Comment by quisquous** [comment]
Hmm! You should still be able to change it in user.

Where is your **cactbot/user/** directory on disk vs the **addons/CactbotOverlay.dll** file?

If you change the Custom User Config Directory to point at your **cactbot/user/** directory do the overrides work?

**Comment by Iilease** [comment]
I have the main cactbot folder in ACT's root directory and CactbotOverlay.dll is in /OverlayPlugin/addons.

Pointing Custom User Config to my cactbot/user/ did the trick, thanks for the quick response!
