### ISSUE TITLE
overlay, castbar and call outs missing 

### ISSUE THREAD

**Issue by osuka91** [quisquous/cactbot#784]
I followed everything as explained and the plugin seems to be installed correctly but I don't have callouts or the targets upcoming cast. Am I missing something? I deleted the old overlay.dll added the new one along with the cactbot.dll

**Comment by ngld** [comment]
You never added an actual overlay. Check the last three steps from the installation instructions.

**Comment by osuka91** [comment]
thanks for the reply!
where can I find the overlay? I was using "https://hibiyasleep.github.io/kagerou/overlay". but i don't see a place to put a URL like there was before. how do I add the overlay, the last three steps just mentions ill have to re-add. how exactly is that done with the new update? is there an overlay you would recommend ?

**Comment by ngld** [comment]
These are the last three steps:
![ngldox_2019-11-21_03-19-05](https://user-images.githubusercontent.com/5465775/69298292-b04a7800-0c0d-11ea-9dac-67feab7337bd.png)

**Comment by osuka91** [comment]
thank you very much for your patience ngld. I look forward to using you with cactbot <3

**Comment by osuka91** [comment]
ugh spoke too soon! Locked the overlay, changed the .js file in raid boss folder to do spoken alerts and was testing with the striking dummy in summerford and it started to do the callouts and then stopped halfway :< any suggestions

**Comment by osuka91** [comment]
works with a /countdown but not when attacking the dummy. gonna try an actual raid. thanks in advance!

**Comment by osuka91** [comment]
IT WORKS THANKS AGAIN! <3333
