### ISSUE TITLE
Alexander timeline not working during P1 and P2 Transition 

### ISSUE THREAD

**Issue by iTouchmyselftoo** [quisquous/cactbot#785]
## Description

Alexander timeline not work properly?

My group is killing Living liquid at 2 mins and when transitioning from limit cut to Brute Justice and Cruise chaser the timeline is still playing limit cut mechanics instead of Phase 2 mechanics.

## Additional information

If available, please include any logs or screenshots depicting the issue you're experiencing.

**Comment by quisquous** [comment]
Thanks! Sorry about this.
