### ISSUE TITLE
Addons not working

### ISSUE THREAD

**Issue by Lycoris-Nightblossom** [quisquous/cactbot#786]
## Description

During raids, Raidboss addon and oopsyraidsy addon UI not showing up.

## Additional information

![Log file](https://user-images.githubusercontent.com/58023984/69314950-6777db00-0c70-11ea-8f41-4bebd56ae1a1.png)

**Comment by ngld** [comment]
Check your local files. If you're sure that you have the latest files and they're not corrupted, load https://quisquous.github.io/cactbot/ui/raidboss/raidboss.html in your overlay instead of the local file. If that works, replace your local files again (or just use the hosted version).

**Comment by Lycoris-Nightblossom** [comment]
I tried that and did not work. I clean reinstalled ACT, Redownloaded Cactbot and the overlay but still did not work. The overlay is there because when I force white background it does this.
![Error](https://user-images.githubusercontent.com/58023984/69319604-71064080-0c7a-11ea-8684-eec66fbf68a9.png)
But without anything on it and no sound effects when supposed to trigger.

**Comment by ngld** [comment]
If you load the above URL and unlock the overlay, you should see some example text. Do you see that? Are there any messages in the overlay log?

**Comment by Lycoris-Nightblossom** [comment]
Unlocking it does bring out the test text

**Comment by Lycoris-Nightblossom** [comment]
![error 2](https://user-images.githubusercontent.com/58023984/69320336-f9d1ac00-0c7b-11ea-88cf-f658c6a2efce.png)

**Comment by ngld** [comment]
What happens if you use the URL I mentioned earlier?

**Comment by Lycoris-Nightblossom** [comment]
The URL works now but changing to a newly downloaded local file breaks it again

**Comment by ngld** [comment]
According to the error messages in your screenshots you're most likely missing one or more files.

**Comment by Lycoris-Nightblossom** [comment]
I see, I guess I will keep using the URL since Local files seems to not be working for me. Thanks for the help.
