### ISSUE TITLE
Unknown job role

### ISSUE THREAD

**Issue by Czerror** [quisquous/cactbot#787]
CN client

Info: death: BrowserConsole: Unknown job role
 Info: BOSS: BrowserConsole: Unknown job role

**Comment by ShadyWhite** [comment]
> CN client
> 
> Info: death: BrowserConsole: Unknown job role
> Info: BOSS: BrowserConsole: Unknown job role

Just use 0.11.2 version of cactbot.Memory signatures and offsets had been update to 5.1 after 0.11.2.

**Comment by quisquous** [comment]
I filed #821 to try to fix this.  Please subscribe there for updates.

**Comment by Czerror** [comment]
> I filed #821 to try to fix this. Please subscribe there for updates.

thx I will update
