### ISSUE TITLE
Name of person with nisi debuff

### ISSUE THREAD

**Issue by FrozenNPC** [quisquous/cactbot#789]
Right now in TEA we have a notification to grab nisi of a certain color. I was wondering if it would be possible to also include the name of the player who has that color? Something like get Nisi a(player name). This would cut down on a lot of comms in that phase during the 3rd pass.

**Comment by quisquous** [comment]
Will do! Thanks for the suggestion.

**Comment by quisquous** [comment]
This should be implemented now.
