### ISSUE TITLE
Fisher: How to migrate player-collected catch data from hibiyasleep version?

### ISSUE THREAD

**Issue by rocketmantis** [quisquous/cactbot#796]
Hi, I've been using the fisher module since the start of ShB and it's very useful. As a result I have a lot of accumulated data on catches made over the last few months. With the ngld version of OverlayPlugin now being required, I switched to it today and that catch data has not been automatically migrated from the hibiyasleep version (for me at least).

So my question is: How should I go about finding my catch data and moving it to the correct location for ngld? I just used default settings for everything before, didn't customize anything about user data storage, so I don't have any particular knowledge about where I should start looking. There is nothing in my (hibiyasleep) OverlayPlugin/cache folder, which I saw mentioned, but the records were definitely being kept between sessions previously, so they must be stored somewhere else.

**Comment by quisquous** [comment]
Sorry about this usability problem.  At some point it'd be nice to somehow share everybody's catch data, but I haven't gotten there.

All the fishing data is stored in IndexedDB.  I am fairly sure that the ngld OverlayPlugin stores its browser storage in %APPDATA%\Advanced Combat Tracker\OverlayPluginCache, which has an IndexedDB folder there.  I am not 100% sure where the hibiyasleep version was.  I think it *might* be in C:\Program Files (x86)\Advanced Combat Tracker\cache\.  Does that exist for you?

If you can find the two IndexedDB folders and (maybe??) replace the newer folder with the older one, it might work? That would be my first approach to suggest.  I'd back up everything before doing any of this so you can revert if anything goes awry.

**Comment by rocketmantis** [comment]
Think we can probably call this closed for now, the window has kind of passed.
