### ISSUE TITLE
Bug with nisi alert

### ISSUE THREAD

**Issue by FrozenNPC** [quisquous/cactbot#801]
Even after gavel's done casting and passing the mechanic successfully, in some instances there is still huge red text telling you to get nisi [x]. From what I can tell this happens when you're the one who lines up first and the others come grab it from you while LoSing Cruise Chaser with the ice block. 

So say the dps are the ones with nisi and they form a line to LoS CC. The tanks and healers walk onto their required colors and get the nisi. In this case, the dps players would have cactbot tell them to grab nisi even though they have it and it stops about 10 secs after gavel is done and all debuffs from field vanish.

**Comment by Wyti** [comment]
To add to that, the big red alert is also spammed multiple time asking to take [X] color nisi, even when you have done so.
Would be great to be similar to the transition and only said it once but keep it displayed

**Comment by quisquous** [comment]
I think this should be fixed now.
