### ISSUE TITLE
Pullcounter no longer works after reaching Limit Cut in TEA

### ISSUE THREAD

**Issue by ChristianIvicevic** [quisquous/cactbot#802]
## Description

I noticed that the pull counter module would count pulls in TEA until Pepsiman has been killed once and the group reaches the Limit Cut transition. Afterwards the pull counter isn't updating anymore and the JSON file still has the same count after dozens of wipes. Apparently the module isn't parsing the end of the encounter correctly (maybe because Living Liquid is no longer available?).

Surprisingly enough even after re-entering the instance it is broken. Only restarting ACT fixes this issue.

**Comment by quisquous** [comment]
I haven't ever seen this happen.  The pull counter seems to be fine for me regardless of limit cut.

The encounter ends on a special wipe message that isn't related to mobs disappearing so I don't think that's it.

Are there any errors in your overlayplugin log when this happens? Does this always happens at limit cut?

**Comment by ChristianIvicevic** [comment]
It's been a while that this happened the last time and I assume it's a bug causing by something else. Gonna close this.
