### ISSUE TITLE
Raidboss overlay missing Timeline bars

### ISSUE THREAD

**Issue by darthmask** [quisquous/cactbot#805]
Hello,

Since updating to 0.13.0 and changing over to the NGLD version of OverlayPlugin I have been unable to get Raidboss to actually function.

The first bit that seems odd is that the "demo" overlay for resizing and such is missing the timeline bars that normally show:
![image](https://user-images.githubusercontent.com/6708670/69663356-15f69400-1054-11ea-87de-8b17e4c630b5.png)

This is accompanied by Raidboss failing to pick up anything when I attempt to actually use the /bow or /countdown tests in Summerford Farms.

Here is my overlay setup: 
![image](https://user-images.githubusercontent.com/6708670/69663689-be0c5d00-1054-11ea-8f28-770c7fe0e04d.png)

There are no errors or warnings in the log that I can see except for the current last line:
[11/26/2019 1:38:54 PM] Info: WS: Warn: The current logging level has been changed to Info.

Any assistance would be greatly appreciated

**Comment by ngld** [comment]
What's your load order? Try loading OverlayPlugin and then Cactbot immediately after the FFXIV plugin.

**Comment by darthmask** [comment]
My current load order has a discord callout plugin before overlayplugin.  I'll change the order and see if that fixes the issue.

Thanks.

**Comment by darthmask** [comment]
Definitely worked, thank you!
