### ISSUE TITLE
Is there literally ANY way to make cactob work with hibiya?

### ISSUE THREAD

**Issue by Kumicoo** [quisquous/cactbot#810]
I fucking hate ngld, it crashes my ACT, laggs my ACT out and doesnt parse right.

Can i somehow use hibiya or am i forced to use an old version of cactbot, or just ditch cactbot altogether?

**Comment by quisquous** [comment]
Sorry, you cannot use the hibiyasleep version anymore.  If you wanted to spend a lot of effort and are a developer, you could fork cactbot and merge in new changes (and keep it up to date), but it'd be a lot of work.

Re: parsing.  I am guessing that what you are getting at is that it doesn't order things correctly.  There is an option in Plugins -> OverlayPlugin.dll -> MiniParse to sort by DPS and Sort Descending (highest first).  You need to check these.

Can you give some more explanation about what's going on with the crashes and the lag?

**Comment by Kumicoo** [comment]
Hey, sorry if it sounded a bit rude.

ngld makes my ACT freeze and lag occasionally, i have already asked around and apparently that has to do with my processor. Everything else works (hibiya). Of course im not saying you should make it hibiya again or youre shit, but meh. I dont really have the option to get another cpu so yea. Guess i will use older versions until those are completely obsolete. Thanks for the great plugin

**Comment by quisquous** [comment]
Well, if it's crashing a bunch and you're getting a plugin messages that it is crashing, this would certainly explain why it's using a lot of cpu and lagging.  That's why I was curious to understand more about what's going on here.  What are people saying, in terms of your processor?

**Comment by Krojack** [comment]
It seems really weird a CPU would do this. What's the brand & model of your CPU?

**Comment by quisquous** [comment]
Sorry for all of the hassle.  Hopefully you can get a newer computer in the future and have everything work more smoothly.  I just don't have time to maintain multiple versions (especially as a number of things won't work in the older version).
