### ISSUE TITLE
fishing for collectables with chum incorrectly tracks the cast-time in as non-chum cast

### ISSUE THREAD

**Issue by mabako** [quisquous/cactbot#820]
## Description

If you try to fish with collector's glove on, and use chum, the time/tug/bite isn't recorded correctly - from what I can tell, it's recorded as non-chum cast -- maybe due to the collectable prompt delaying the 'You land a ... ' message, and chum expiring at the time of catch?

The most obvious issue is that it messes with the non-chum time table, as you can now supposedly catch fish WAY earlier than they'd ever actually bite w/o chum. The second, somewhat less annoying issue is that the chum time table is completely empty for collectable fish.

## Additional information

Go to Unfrozen Pond/CWH, use a goblin jig and fish with chum. There's only 3 fish to catch there (Icepick, Sorcerer Fish, Albino Octopus), with the first two being collectable + happening way more often than the octopus.

**Comment by mabako** [comment]
Actually similarily, if you chum, catch a fish and use mooch quick enough (presumably within 1 second after catching it), cactbot also thinks you're using chum still - and thus will also count that for the chum time table although mooching can't ever be combined with chum.

**Comment by quisquous** [comment]
Not planning to make any more fishing changes.
