### ISSUE TITLE
raidboss: Copied City alliance raid timeline problems

### ISSUE THREAD

**Issue by KattTails** [quisquous/cactbot#822]
I ran the copied city alliance raid again earlier and had problems from `Serial-jointed Command Model` onwards.

I've run test_timeline.py against it and uploaded it [here](https://pastebin.com/vhAeLyyV).
I've uploaded the network log [here](https://cdn.discordapp.com/attachments/448120801363886090/651081041750130707/Network_2045_20191201-split-2019-12-02T09-57-50.834Z.7z) too.

It looks like
```
259.1 "Systematic Suppression" sync /:Serial-jointed Command Model:48C6:/
272.0 "High-Caliber Laser" #sync /:Serial-jointed Service Model:48C7:/
276.0 "High-Caliber Laser" #sync /:Serial-jointed Service Model:48C7:/
281.9 "Forceful Impact" sync /:Serial-jointed Command Model:48CF:/
```
are skippable mechanics in the first fight, I'm assuming due to damage. 
The trash before Hobbes didn't sync at all, and even though it appears to match the Hobbes fight and onwards just fine, the timeline itself stayed hidden throughout the rest of the raid. 
Alerts worked as expected however throughout the entire raid.

**Comment by Akurosia** [comment]
I think this needs further investigation in generall. 
As for me (german client) all worked fine.

**Comment by quisquous** [comment]
Thanks for the log, that's perfect.

Trash before Hobbes is fine.  The test_timeline.py just isn't smart enough to catch `22:` lines.  I added another sync just in case.

I don't know what's up with the timeline hiding for the rest of the raid.  That sounds like a separate issue.  If that happens again, can you see if there are errors in the overlayplugin log?
