### ISSUE TITLE
Autogenerated map scales and offsets

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#823]
Eureka had some x/y position to map coord info but it's all hand generated by linear fitting data.  All of the scales and offsets are in the Map table.  These could be auto exported from saint coinach or xivapi and a global helper to convert to and from map coords could replace all those eureka values.  This would probably be useful elsewhere.

**Comment by Akurosia** [comment]
This might be helpfull: https://github.com/xivapi/ffxiv-datamining/blob/master/docs/MapCoordinates.md

**Comment by quisquous** [comment]
While I'm belatedly looking at this:

TerritoryType is the zone ids that cactbot uses: https://xivapi.com/TerritoryType/777?pretty=true

TerritoryType has a PlaceName: https://xivapi.com/PlaceName/2449?pretty=true

The Map table has the size factor and offsets by PlaceName:
https://xivapi.com/Map?columns=ID%2CPlaceName.Name%2CSizeFactor%2COffsetX%2COffsetY&pretty=true

**Comment by quisquous** [comment]
Thanks for the pointer @Akurosia.  That was exactly what I needed!
