### ISSUE TITLE
TTS not working

### ISSUE THREAD

**Issue by potentone** [quisquous/cactbot#829]
Just had to reinstall windows and stuff, along with newest version of Cactbot, now ACT TTS triggers are not working.

Worked before reinstall but it was with the earlier version(still ngld).

Tried changing to windows API sound, using the pop-up.js text change etc. Nothing has worked. Any ideas would be much appreciated.

**Comment by quisquous** [comment]
Are you talking about cactbot tts triggers? Or just general act custom triggers?

**Comment by ChemicalDisorder** [comment]
I am having the same exact issue. I can get the text triggers and sound to work. But I cant seem to get TTS to work. I have no clue what I am missing. Its as if a rule is broken in C++. My issue is with cactbot TTS

**Comment by quisquous** [comment]
@ChemicalDisorder Did you follow https://github.com/quisquous/cactbot/blob/master/AdvancedCactbot.md#text-to-speech and then in ACT in the Cactbot EventSource point the custom user directory at your cactbot/user/ folder?

**Comment by ChemicalDisorder** [comment]
Everything with TTS is set to true

**Comment by ChristianIvicevic** [comment]
I can confirm that customizing TTS is not working for me either. The following in the user raidboss file is not picked up whatsoever:

```js
Options.PerTriggerOptions = {
	'TEA Temporal Stasis No Buff': {
		SpeechAlert: true,
		TTSText: function (data) {
			return 'Cruise South';
		}
	},
	'TEA Restraining Order': {
		SpeechAlert: true,
		TTSText: function (data) {
			return 'West';
		}
	},
	'TEA House Arrest': {
		SpeechAlert: true,
		TTSText: function (data) {
			return 'Brute South';
		}
	},
	'TEA Aggravated Assault': {
		SpeechAlert: true,
		TTSText: function (data) {
			return 'Brute Side';
		}
	},
};
```

**Comment by quisquous** [comment]
Sorry for the extremely belated response to this issue.

Has the new config tool helped at all, in terms of turning on tts or turning on tts for specific triggers?

If you aren't hearing any tts for cactbot, are you able to hear any tts from ACT? If you click custom trigger, select TTS, type something in the text box, and then hit the play button, do you hear anything?

One other thing to test is to add `ui/test/test.html` as an overlay, and then type `/echo tts:testing or whatever here` and see if that plays tts.  If that doesn't play, then there's something wrong with ACT tts setup.  If that does play but other triggers don't, then there's something wrong with the trigger configuration.

**Comment by quisquous** [comment]
Is TTS still not working for all of you?

**Comment by quisquous** [comment]
Hi, is this still an issue?

**Comment by ChemicalDisorder** [comment]
Nono. I fixed it months ago. Sorry. I thought I edited my post.



Sent from my Sprint Samsung Galaxy S10.



-------- Original message --------

**Comment by Feith6** [comment]
Same issue now, had to reinstall win, after that TTS in cactbot is not working, everything else in ACT is working perfecly, sounds work, even browser TTS is working. Is there any fix for it?
