### ISSUE TITLE
how can i read the instructions carefully on a 404 page

### ISSUE THREAD

**Issue by Lleonharte** [quisquous/cactbot#831]
"2) I'd like to try the new ngld overlayplugin"
"(6) read and follow these new instructions **carefully**: https://github.com/quisquous/cactbot/tree/ngldoverlay#installing-cactbot"

this takes me to a 404 page.. wtf do i do now?

**Comment by Akurosia** [comment]
Just use the normal installing instructions under: https://github.com/quisquous/cactbot/tree/master#installing

These instructions were made before the ngld cactbot branch got merged.

**Comment by quisquous** [comment]
Updated that really old release's link just in case anybody else runs into this as well.
