### ISSUE TITLE
Wrong infoText/TTS in gubal_library_hard.js

### ISSUE THREAD

**Issue by ddc** [quisquous/cactbot#838]
## Description

Wrong infoText/TTS in ui/raidboss/data/03-hw/dungeon/gubal_library_hard.js
Inside "if" statement:
lines 79 and 80
lines 84 and 85

          if (sameMarkers) {
            return {
              en: 'Away from boss',
              fr: 'Eloignez-vous du boss',
            };
          }
          return {
            en: 'Close to boss',
            fr: 'Près du boss',
          };

## Additional information

It suppose to be the other way around:
If sameMarker, should be "Close to boss"
else: "Away from boss"

          if (sameMarkers) {
            return {
             en: 'Close to boss',
             fr: 'Près du boss',
            };
          }
          return {
              en: 'Away from boss',
              fr: 'Eloignez-vous du boss',
          };

**Comment by JLGarber** [comment]
That's definitely a substantial mistake! Not sure how that happened. I'll put together a pull request to fix it tonight.

**Comment by quisquous** [comment]
Should be fixed now, thanks for the report.
