### ISSUE TITLE
Cactbot timers no longer working

### ISSUE THREAD

**Issue by ss0703** [quisquous/cactbot#843]
I recently installed cactbot and did a run of E1S where all the timers worked as normal. I get to E3S and the timelines are a bit ahead I guess? The bar fills early well before the cast actually hits and the number to countdown to the cast is no longer there.

I've gone to Summerford Farms to do a countdown test and same thing. Timelines are there but ahead and there's no numbers.

I've tried removing the plugin itself and removing the overlay on the overlayplugin.dll tab and adding it again but nothing changes.

Any advice?

**Comment by beckyeeky** [comment]
Have you try updating the FFXIV_ACT_Plugin?

**Comment by quisquous** [comment]
What do you mean that there's no numbers? Can you screenshot?

**Comment by quisquous** [comment]
Hi, is this still happening?

**Comment by quisquous** [comment]
I'm going to close this for now.  Please file another issue if this is still happening.
