### ISSUE TITLE
Radar can't handle B (maybe other ranks too?) mobs?

### ISSUE THREAD

**Issue by Zarbalan** [quisquous/cactbot#845]
Hey there, i just tested the new radar overlay and got an error message while i encountered a B-Mob. Don't know what's the problem but maybe you can figure it out?

Radar: BrowserConsole: Uncaught TypeError: Cannot use 'in' operator to search for 'B' in undefined (Source: .../cactbot/ui/radar/radar.js, Line: 73)

Thanks for your hard work! :)

**Comment by quisquous** [comment]
Sorry for this issue.  I had tested using a cactbot/user/radar.js file that made this issue not show up.

I think if you point your radar overlay at https://quisquous.github.io/cactbot/ui/radar/radar.html instead of the local file, it'll have the fix I just landed.
