### ISSUE TITLE
Overlay disappears when ACT is minimised

### ISSUE THREAD

**Issue by RB2804** [quisquous/cactbot#847]
I only use the tool for the raid timeline, so not sure if it effects anything else, but when ACT is minimised, the overlay will disappear. I can still hear the alerts and when I have the ACT window active again they will reappear. The strange thing is the ACT window doesn't even  need to be focused, just not minimised to my taskbar. Only been happening since I moved over to the ngld overlayplugin.

**Comment by quisquous** [comment]
Can you file this issue with the ngld overlayplugin instead? https://github.com/ngld/OverlayPlugin/issues/new

It sounds like a bug with the active window detection.

**Comment by RB2804** [comment]
Done.
