### ISSUE TITLE
Radar showing multiple arrows for same hunt

### ISSUE THREAD

**Issue by Tykku** [quisquous/cactbot#848]
When first detecting a hunt Radar works fine. After detection if you move out of ACT detection range, then back into it, it places another non functioning arrow on the overlay.

https://imgur.com/a/ly1hXn8

Edit: This arrow does not clear on zone swapping.

**Comment by deice** [comment]
The code doesn't lowercase the mob name properly, so it doesn't see its already on the list. I fixed this by adding the following just before line 96: if (!(mob_name in this.targetMonsters)) {

this.RemoveMonster(mob_name.toLowerCase());

Added benefit, it pops up the latest ping to the top with this.

**Comment by deice** [comment]
That's in cactbot/ui/radar/radar.js that is. Passable workaround until its fixed.

**Comment by quisquous** [comment]
Thanks! Yeah, the lowercasing was a change right before the cactbot release and I clearly didn't test it enough.  Thanks for the pointer to the bug.
