### ISSUE TITLE
TTS Spelling certain words and names

### ISSUE THREAD

**Issue by jpdied** [quisquous/cactbot#851]
## Description
Since 0.13.3, Cactbot TTS triggers are now spelling certain words or names. For example "Interrupt Reptoid" comes out as "Interrupt R-e-p-t-o-i-d". However if I feed that exact phrase into ACT's custom triggers and test the TTS, it is read correctly. Also testing this on my Windows Text to Speech control panel and the phases are read correctly as well. It seems to happen only when fired off by Cactbot.

**Comment by Feanarus** [comment]
I also noticed this behavior and in addition comes the tts mixes two languages in one expression e.g. ucob for me german/english : instead of de: 'verteilen, dann rein' it says 'verteilen, then in' or 'verteilen, then rein' always with "then" even though the german lines are correct this happend in 0.13.3 and after

**Comment by quisquous** [comment]
@jpdied Has this changed in a recent version of cactbot? It's surprising to me that the ACT custom triggers would behave differently, as cactbot is using ACT to play the tts.

@Feanarus This sounds like a separate bug.  I see where the issue is, thanks for mentioning it.

**Comment by jpdied** [comment]
@quisquous , No this is still happening. Certain mobs will be spelled as well as certain players names. Yet it behaves correctly in the custom triggers.

**Comment by quisquous** [comment]
@jpdied Ah sorry, I was trying to ask if this was working properly in a previous version of cactbot (or ACT?) and things have changed at some point, or if it has just always been broken.

**Comment by jpdied** [comment]
@quisquous It working working with version 0.13.0. I want to say the last FFXIV patch it starting having issues but I can't recall if it was right after the patch or when 0.13.1 came out.

**Comment by jpdied** [comment]
The issue is still occurring with 0.13.5. Is there any debug options I can toggle to provide additional information?

**Comment by quisquous** [comment]
Sorry, I just haven't had a chance to look into this yet.

**Comment by quisquous** [comment]
This is very strange that this is behaving differently.  cactbot uses ACT to play all of its tts.  "Interrupt reptoid" plays for me the same via cactbot as it does via an ACT custom trigger.

Do you have any custom tts things set up, like yukkuri, etc? Also, what OS are you running?

**Comment by jpdied** [comment]
I'm on Windows 7 and I do have the Windows 10 ZiraPro enabled via Windows Server SDK in my control panel. As I mentioned though both in the Control Panel and in ACT's custom triggers its not doing it. I need to test out the Twining where "Interrupt reptoid". I was in Hades EX last night and it was spelling Igeyorhm in the phrase "Attack Igeyorhm".

**Comment by jpdied** [comment]
OK, I think I figured it out and can reproduce it. I think this is a Win 7 issue, but I realized if you type if all caps "INTERRUPT REPTOID", it will start spelling the second word. I believe this is what is currently happening. Using Discord Triggers to push my TTS to Discord, there is some additional debug info that gets placed in the plugin window. Some things are sent in all caps while others are not. Quick look over the Twinning data file, nothing seems to be full caps, but that seems to be whats causing it.
![tts_spelling_all_caps](https://user-images.githubusercontent.com/8827083/71537966-b826c780-28f1-11ea-8b23-9defcc60f593.png)

**Comment by KattTails** [comment]
The upper-case texts are all alertTexts, which get converted to upper-case here:
https://github.com/quisquous/cactbot/blob/master/ui/raidboss/popup-text.js#L428

``` js
  let alertText = triggerOptions.AlertText || trigger.alertText || response.alertText;
  if (alertText) {
    let text = triggerUpperCase(ValueOrFunction(alertText));
    defaultTTSText = defaultTTSText || text;
    if (text && showText) {
      let holder = that.alertText.getElementsByClassName('holder')[0];
```
The lower-case texts are all infoTexts, which do not get the same conversion:
https://github.com/quisquous/cactbot/blob/master/ui/raidboss/popup-text.js#L448
``` js
  let infoText = triggerOptions.InfoText || trigger.infoText || response.infoText;
  if (infoText) {
    let text = ValueOrFunction(infoText);
    defaultTTSText = defaultTTSText || text;
    if (text && showText) {
      let holder = that.infoText.getElementsByClassName('holder')[0];
```

**Comment by quisquous** [comment]
> OK, I think I figured it out and can reproduce it. I think this is a Win 7 issue, but I realized if you type in all caps "INTERRUPT REPTOID", it will start spelling the second word. I believe this is what is currently happening.

Yesssss, this is it exactly.  Thanks for the insight!
