### ISSUE TITLE
Radar doesn't work without a user config in place

### ISSUE THREAD

**Issue by deice** [quisquous/cactbot#852]
Radar module leads to errors when loading if you haven't set up a user config in cactbot/user. It  tries to check for rank keys in a non-existent config object.

Fixed my personal copy changing two lines, in AddMonster & UpdateMonsterDom functions to check for the existence of RankOptions before accessing it:

    if (options.RankOptions && monster['rank'] in options.RankOptions) // option overwrite

**Comment by Tykku** [comment]
Fix tested on my end, works fine here.

**Comment by quisquous** [comment]
Duplicate of #845.  Should be fixed now.
