### ISSUE TITLE
Force ACT to end encounter

### ISSUE THREAD

**Issue by Krojack** [quisquous/cactbot#854]
I've been lookin at the test.html overlay for funzies and noticed that it has a inCombat flag for ACT and the game it's self.  The game flag (yes/no) seems to always be correct and even remains in combat during long boss transformations.  

Question: Would be be possible to have Cactbot tell ACT when combat ends? I like having a low encounter ends setting for ACT but this splits up a lot of raid fights like Hades EX and the Eden fights.  My current workaround is to have a high second time set and to have an in-game macro that does "/echo end" when clicked. This works but it's a real pain in the butt after a while.

**Comment by quisquous** [comment]
For what it's worth, cactbot does tell ACT when you wipe.  This works in everything HW and onward, I think.  I have my encounter time set to ridiculously high and just depend on that.

The game is not always correct.  In o5 when you go in the train cars, you fall out of combat briefly.  There was also a period of time where this also happened in the moogle trial.

**Comment by KattTails** [comment]
I have a personal fork that does this fairly successfully, with a customizable delay so that you have to be out of combat in-game for (x) seconds before ending the encounter, which would mitigate that problem in o5. 5s seems like a good default as dot ticks make you re-enter combat every 3s, and it's leaving my ACT encounters looking very neat. 

The UI panel is a big mess though.. 🙃

**Comment by quisquous** [comment]
Ooh, 5 seconds out of game combat is nice, and avoids having to read logs.  Nice thinking!  I was thinking that this should probably be upstreamed to ngld's overlayplugin, as it'd be a nice feature for everybody.  Although I guess this runs into the cn vs intl version issue again there.  Oof.

**Comment by KattTails** [comment]
I guess the *best* place would for this to be in the FFXIV parser itself.

**Comment by quisquous** [comment]
https://github.com/ngld/OverlayPlugin/pull/134
