### ISSUE TITLE
Radar not showing players

### ISSUE THREAD

**Issue by FrUct1s** [quisquous/cactbot#857]
After setting up the individual overwriting options in /cactbot/user/radar.js all regular Options are set (TTS for example is working) but either Options.OnlyMobs = false; or Options.CustomMonsters is not working for players.
If I add a Monster under CustomMonsters it shows up with an arrow but it doesn't work for players.

**Comment by Bluefissure** [comment]
You probably need to add the player server in the bracket after the player's name, and then it'll pop up like:
![321.png](https://i.loli.net/2019/12/16/UqipQAg1Eh75jlN.png)

I'm a player in the Chinese server and I don't have access to the global server atm, there may also be something wrong with the first and second names, which I can't test in the Chinese server. So if it doesn't work after adding the server after the player's name, please let me know.

**Comment by FrUct1s** [comment]
You're right, Brackets are needed after the name, thank you!
