### ISSUE TITLE
Alert sound when raidboss not shown

### ISSUE THREAD

**Issue by Bluefissure** [quisquous/cactbot#859]
## Description

If raidboss module is temporarily disabled (not shown) in overlayplugin, the alert sound will be triggered as well. Should it be muted when the module is disabled?

**Comment by quisquous** [comment]
Ideally, it should, but this is really an overlayplugin issue.  There was some discussion about this in the ffxiv act discord, so hopefully ngld will implement this.  I filed this as a feature request here: https://github.com/ngld/OverlayPlugin/issues/73
