### ISSUE TITLE
Raidboss: infoText overrides tts for spoken alerts

### ISSUE THREAD

**Issue by Webberjo** [quisquous/cactbot#861]
## Description
Since the latest version of cactbot, any triggers that have both an `infoText` and `tts` property now have the `tts` value ignored when doing a spoken alert.

Ex:
```js
Options.SpokenAlertsEnabled = true;
Options.Triggers = [
	{
		zoneRegex: /.*/,
		triggers: [
			{
				regex: /test/,
				infoText: 'Foo',
				tts: 'Bar'
			}
		]
	}
]
```
If you do `/e test` in game, this trigger will play "Foo" over TTS instead of "Bar".

**Comment by quisquous** [comment]
Should be fixed with 45fc915f.
