### ISSUE TITLE
Fisher: Nothing is displayed if the fishing spot contains double-byte colons in Japanese.

### ISSUE THREAD

**Issue by myogya68** [quisquous/cactbot#863]
Nothing is displayed if the fishing spot contains double-byte colon in Japanese.

e.g
グリダニア：翡翠湖畔
リムサ・ロミンサ：下甲板層

**Comment by quisquous** [comment]
Thanks for the bug report.  I'll try to take a look when I get a chance.

**Comment by Akurosia** [comment]
At the current state (patch 5.15) following chars are used in en, de, fr, ja:
```
 &'()-ABCDEFGHIJKLMNOPQRSTUVWYZabcdefghijklmnopqrstuvwxyzÉÎÖÜßàâäèéêîôöûüœいうかきくけさざしたつなのまみめやらりるれァアィイゥウェエォオカガキギクグケゲコゴサザシジスズセゼソタダチッツテデトドナニネノハバパヒビピフブプヘベホボマミムメモャヤュユョラリルレロワンヴヶ・ー七三上下不丘中之二井交人体信像光入全凍前剣化北区十南卵口古台合吹唄嘆囁四地坏坑城埠堂場塔墓壁壇夏夜大夫奈始姿婦子学定室宿寺導小尾居屋層山岩岬岸峠峰島川州巣巻常幻底座廃廠彩影御忘恵悲愁愚戦戸所手抜排支断旅族旗早星未末村東板林査根桟梅森植構標樹橋止水氷江池沖沢河沼沿泉波泪洞流海涙液渓渡渦港湖湧湾湿源溜溝滝漠灯無燐狭獄玉生産用甲町畔知砂神祭科程穏穴窟笠管簀系紅絶翠翡者聖脈船艦花芽茶落葉蓋蔵蜜血街裁裂西見調諸谷貯超足跡路輪近造道遺邸部郷酒釣銀錆鏡間院陣陸隊隠雲霜青領頭額風飛食餌首麓：
```
When filtering out all `\w` this gets reduced to:
```
 &'()-・：
```
and further filtering with `\s` will ends up with:
```
&'()-・：
```
So when using a regex with `\w\s&'()-・：` should match all fishingspots

**Comment by myogya68** [comment]
fisher.js line:105 107 111
`[\u3000-\u30ff\u3400-\u4dbf\u4e00-\u9faf]`

Not included
`：` `\uff1a`

And... Some fish have numbers in their names
e.g.
魔科学物質666

So I think it should be like this
`[\u3000-\u30ff\u3400-\u4dbf\u4e00-\u9faf\d\uff1a]`

**Comment by quisquous** [comment]
Done, thanks for the suggestions.  Let me know if there's more to change.
