### ISSUE TITLE
Radar module wishlist

### ISSUE THREAD

**Issue by whylorainer** [quisquous/cactbot#864]
The radar module is an amazing addition but I would like to suggest a few changes hopefully for the better:

- Once a hunt is picked up by the module, it'll never unload the arrow unless: It dies, a cutscene begins or you change maps. It would be helpful to have the arrow stop showing after a certain distance away from the hunt, maybe the same distance it takes to detect it or a fixed configurable distance or expire after a certain amount of time.

- I think the option that shows you the hunt puller is swell, but it I wish it stored even if just temporarily  the name of the puller, this would mostly be useful to know if early pullers are around using player search. 
To then use this information to relay the hunt to linkshells hopefully before the pull happens. This can take form of anything, an echo message, a temporary log file, a console message, just something you can check who pulled when the hunt is done.

- A way to input in the name of players/mobs for the radar without having to deal with javascript (this is probably for later when the GUI comes in?), would mostly be useful for things like quickly tracking monster needed for hunt spawns (For example the kills needed for Okina), find an NPC or spook a friend.

**Comment by Tykku** [comment]
To go off this. First point if you are gonna make the arrow disappear based on distance can we please have the option to enable that? I like it being persistent, but understand the desire for other options.

**Comment by KattTails** [comment]
I can't imagine something like that being added and not having options to configure it. Don't worry :)

**Comment by Bluefissure** [comment]
- I already added the `Options.DetectionRange` in [user/radar-example.js](https://github.com/quisquous/cactbot/blob/master/user/radar-example.js#L10), the arrows will be hidden if you move out that range. However, we don't have a time-expiration mechanic now.

- Maybe we can add time-expiration to the puller as well? It seems weird if there's a persistent name.

- Currently, I don't have a better thought to handle custom entries,  as for the spawn mob counter, I'm thinking of new features of radar recently, maybe we can discuss them at https://github.com/quisquous/cactbot/issues/874.

**Comment by quisquous** [comment]
I think this issue is mostly resolved.

`DetectionRange` I think does what you want in terms of expiration.  I don't think there needs to be time separatelly from distance.

Puller is logged in the console.  I think it's fine for it to always be there while the mob is alive?

#891 covers the config option for custom mobs.

I'm going to close this, as I think everything here has been addressed, or is duplicated in another issue.
