### ISSUE TITLE
Raidboss and Miniparse urls reset on reboot

### ISSUE THREAD

**Issue by Rauvagol** [quisquous/cactbot#868]
The first time I open ACT each day, I need to go into the plugin settings for OverlayPlugin.dll and reset url field for miniparse and bosstimers, or the field is just blank.

Attached image for clarification on the exact field I mean

![image](https://user-images.githubusercontent.com/7938335/71216286-fe838300-226e-11ea-9845-d7669b250f88.png)

**Comment by quisquous** [comment]
See: https://github.com/ngld/OverlayPlugin/issues/70

**Comment by quisquous** [comment]
I don't think there's anything that can be done on the cactbot side of things here.
