### ISSUE TITLE
Radar module new features

### ISSUE THREAD

**Issue by Bluefissure** [quisquous/cactbot#874]
- Data persistence: Use something like `LocalStorage` to store the data in the browser storage (just like fish module), thus next time we come to a map we can reveal the recorded monster positions. This will be more convenient to record monster before a hunt train? Or linkshell is good enough?

- Position update: update position with other network packages/logs so that it detects players' current position instead of first spawn location.

- Spawn mob counter: add a counter for spawn mobs when triggering specific S rank monster.

- Collaborate: Hunt train recording is done by multiple players (in Chinese, not sure about other servers), could it be a good way to collaborate with some other js libraries like [togetherjs](https://togetherjs.com/)? Does this mean a backend is needed?

- S rank spawn point: I heard that S rank monster won't spawn at where A/B rank monsters spawned before (in a time cycle) so if we can collaborate we can predict next S spawn point.

**Comment by quisquous** [comment]
I think a lot of these are better served by something outside cactbot doing global coordination for your server.  I think if you wanted to add a spawn mob counter, you could do this with raidboss triggers for the zone.  That gets done in one of the Eureka zones, as an example.

I think cactbot is good at reading current logs and showing where mobs are, but coordinating with other people seems like something better done with another program.  I think there are already a number of other hunt plugins that already do this.  So, I'm going to close this feature request for now, sorry.
