### ISSUE TITLE
Update 13.5 

### ISSUE THREAD

**Issue by Lotax** [quisquous/cactbot#876]
Issue with newly updated 13.5 is breaking middle off fight and the alert delays when he reconnecting. Both alert and timer on raidboss

**Comment by ngld** [comment]
Unless this happened before the 5.18 update, this is most likely caused by missing network lines. Wait for the next parser update and then check again.

**Comment by quisquous** [comment]
https://gist.github.com/ngld/e2217563bbbe1750c0917217f136687d#current-stuff
