### ISSUE TITLE
triggers not working at all after the ffxiv patch?

### ISSUE THREAD

**Issue by itsyaboishin** [quisquous/cactbot#877]
hi, after today's patch triggers stopped working for me.
timelines sometimes disappear, but the triggers work ONLY on the dummy and nowhere else, tried many different fights. i tried downloading the newest cactbot version but that didn't fix anything, i swapped to the older one and still the same problem :< even tried reinstalling whole ACT.
pretty sure i've seen someone mentioning same stuff as me somewhere on discord so i believe it's not just me. no erorrs appear at all.

**Comment by KattTails** [comment]
The FFXIV plugin needs an update. This is the same for every FFXIV patch going forward.

Not a cactbot issue.
