### ISSUE TITLE
User files tied to OverlayPlugin addons folder

### ISSUE THREAD

**Issue by xephero** [quisquous/cactbot#88]
This is probably an edge case.

The Readme states:

> Note: The cactbot\ folder does not have to be located inside of the OverlayPlugin directory, but that is where it comes by default as part of a cactbot release zip file. It can be located anywhere on disk as long as the entire cactbot\ folder is kept together.

This has been true for a while, however, in the new version, it loads this path for me (taken from devtools):

`C:\Program Files (x86)\Advanced Combat Tracker\Plugins\OverlayPlugin\addons\../cactbot/user/raidboss.css`

With the actual addon at:

`C:\Program Files (x86)\Advanced Combat Tracker\Plugins\OverlayPlugin\addons\CactbotOverlay.dll`

My file was at `C:\Program Files (x86)\Advanced Combat Tracker\Plugins\Cactbot\user\raidboss.css`, so it worked relative to the html file, but now now.

It's not a huge deal, but it's worth either taking out that section of the readme, or accounting for that setup and making the path relative to the html file rather than the dll file.

**Comment by quisquous** [comment]
Mmm, thanks for this feedback.  I think what I'll do is to make it try to load from both.  Sorry for the hassle.

**Comment by xephero** [comment]
No hassle at all, no worries. Thanks for addressing it.
