### ISSUE TITLE
raidbossemulator working with more than just boss fights

### ISSUE THREAD

**Issue by liaoarden** [quisquous/cactbot#881]
Looks like raidbossemulator only works on boss fights for things like dungeon runs.

So it's a great tool for testing triggers on bosses, but less so on potential triggers during dungeons.

(Not sure how useful this actually would be since dungeon triggers on pulls are useful, but also usually completely unnecessary.)

Used the following log as a replay example:

[Network_2049_20191225-split-2019-12-26T07-45-40.622Z.log](https://github.com/quisquous/cactbot/files/4001861/Network_2049_20191225-split-2019-12-26T07-45-40.622Z.log)

**Comment by valarnin** [comment]
Is this still relevant with the new raidemulator? It won't show individual trash pulls between bosses but those fights are still included as part of the boss fight that proceeds them, and triggers should be visible as well if they're visible from the trash.

![image](https://user-images.githubusercontent.com/6119598/91242354-32c01500-e715-11ea-996f-8bb2e672a1bd.png)

**Comment by quisquous** [comment]
Yeah, I agree that the new raidboss emulator covers this.  I'll close this (but feel free to disagree and we can reopen and discuss!)
