### ISSUE TITLE
Globally customize timeline TTS point of activation (set beforeSeconds globally)

### ISSUE THREAD

**Issue by NNowakowski** [quisquous/cactbot#888]
## Summary

I'd like a feature which allows you to customize the time when TTS triggers happen.
Right now we can already show each mechanic X seconds in advance in the timeline, I'd like the same customization for the TTS triggers aswell.

It could be useful on jobs like SCH where you may want to pre-succor or Seraph a mechanic.
Right now the speech trigger activates once the cast bar on the boss appears (if there is one), which is too late for both of these cases, unless you swiftcast a succor, not even mentioning Seraph taking like 4 seconds from summon to actually casting the shield.

While this could theoretically be achieved by looking at the timeline, using the existing audio triggers would be another great help, by just shifting them X seconds forward. Currently you'd have to modify each seperate timeline file to pick out a specific mechanic and adjust the time manually, an overall setting to shift the triggers by X seconds would be much easier to handle.

**Comment by veltall** [comment]
Triggers and timelines are different things; you can't warn someone of an event that has yet to be observed. Cactbot knows nothing about healer goals until it sees the logline:
`15:.{8}:(?:Garuda|Titan):2B6[BC]:Rock Throw:.{8}:(?<name>[a-zA-Z' ]+)`

If you want to pre-empt an event, you need foreknowledge which is what timeline provides. It would be nice if there were a bridge between a timeline file and a trigger, so you could have a timeline event activate a trigger prematurely, but for all intents and purposes, they seem to be separate things.

**Comment by NNowakowski** [comment]
> Triggers and timelines are different things; you can't warn someone of an event that has yet to be observed. Cactbot knows nothing about healer gaols until it sees the logline:
> `15:.{8}:(?:Garuda|Titan):2B6[BC]:Rock Throw:.{8}:(?<name>[a-zA-Z' ]+)`
> 
> If you want to pre-empt an event, you need foreknowledge which is what timeline provides. It would be nice if there were a bridge between a timeline file and a trigger, so you could have a timeline event activate a trigger prematurely, but for all intents and purposes, they seem to be separate things.

But isn't this exactly what the timeline is able to do already?
Looking at some files, this one being from TEA for example, it has a property "beforeSeconds" which I'd think tells the trigger how many seconds in advance it should activate:
`  zoneRegex: /^The Epic [Oo]f Alexander \(Ultimate\)$/,
  timelineFile: 'the_epic_of_alexander.txt',
  timelineTriggers: [
    {
      id: 'TEA Fluid Swing',
      regex: /Fluid Swing/,
      beforeSeconds: 5,
`

**Comment by veltall** [comment]
Timeline files are capable of "predicting" events, triggers aren't.

**Comment by NNowakowski** [comment]
> Timeline files are capable of "predicting" events, triggers aren't.

Maybe I do not quite understand how this works but isn't this exact snippet here the trigger?
```
  zoneRegex: /^The Epic [Oo]f Alexander \(Ultimate\)$/,
  timelineFile: 'the_epic_of_alexander.txt',
  timelineTriggers: [
    {
      id: 'TEA Fluid Swing',
      regex: /Fluid Swing/,
      beforeSeconds: 5,
      // TODO: this is likely calling out twice sometimes because
      // the timeline resyncs and it becomes 5 seconds before again.
      // This is probably a problem for all timeline triggers (whoops)
      // and needs to be fixed more generally rather than adding a
      // suppression.
      suppressSeconds: 1,
      preRun: function(data) {
        data.swingCount = (data.swingCount || 0) + 1;
      },
      alertText: function(data) {
        let multipleSwings = data.swingCount == 2 || data.swingCount == 3;
        if (data.role == 'healer') {
          if (multipleSwings) {
            return {
              en: 'Tank Busters',
              de: 'Tank buster',
              fr: 'Tank busters',
              ja: 'タンクバスター',
            };
          }
```

The alertText is what is gonna be shown under the timeline and also the text which is gonna be spoken by the TTS setting, no? I don't mind ACT custom triggers or anything the like but just the default text which is outputted by Cactbot when enabling the cactbot TTS feature.

**Comment by veltall** [comment]
This is likely the bridge I was mentioning. If you look at the timeline file, the name for the tank buster event is **Fluid Swing**, and the regex matches exactly that. 

With this feature, it's possible to do what you wanted here

> an overall setting to shift the triggers by X seconds would be much easier to handle.

by creating a triggers that match desired **Timeline events** and adding to them the `beforeSeconds` property.

**Comment by NNowakowski** [comment]
> This is likely the bridge I was mentioning. If you look at the timeline file, the name for the tank buster event is **Fluid Swing**, and the regex matches exactly that.
> 
> With this feature, it's possible to do what you wanted here
> 
> > an overall setting to shift the triggers by X seconds would be much easier to handle.
> 
> by creating custom triggers that match desired **Timeline events** and adding to them the `beforeSeconds` property.
> 
> Example
> 
> ```js
> {
>       id: 'TEA Splashes',
>       regex: /Splash x6/,
>       beforeSeconds: 5,
>       alertText: {
>         en: 'splashes in 5',
>       };
> }
> ```

Yup, that is exactly what I'd have to do right now, which can be quite the hassle to do it for every single timeline.

It would be nice to have an overall setting (in the raidboss user settings) which applies the specified beforeSeconds to each timeline event, or adding the specified amount to all already registered beforeSeconds parameters.

That way you can just set it globally if you like to have announcements further into the future instead of having to dig through all the timelines and setting the properties yourself manually.

**Comment by veltall** [comment]
I don't think this will work, but you can try regexing the trigger name in your config file to catch as many triggers as you want and modify them in one swoop.

**Comment by quisquous** [comment]
I've added "before seconds" to the config ui for anything that is a timeline trigger, but I think in general this is just not something that's possible to do.  I will try to make "big" aoes in the future that really need prep more warning than they currently have in the future.
