### ISSUE TITLE
Cactbot plugins stopped working

### ISSUE THREAD

**Issue by meciuPL** [quisquous/cactbot#89]
Since instaling the newest version all the modules stopped working. In the logs I get the following message:

18.03.2018 17:06:33: Info: pull: BrowserConsole: Uncaught TypeError: window.OverlayPluginApi.overlayMessage is not a function (Source: , Line: 6)

18.03.2018 17:10:38: Info: raid: BrowserConsole: Uncaught TypeError: window.OverlayPluginApi.overlayMessage is not a function (Source: , Line: 6)

Any idea whats causing the problem?

**Comment by quisquous** [comment]
You are very likely not on the right version of OverlayPlugin.  You need to be on the hibiyasleep 0.3.4.0 version.  I'm guessing the log message prints out an earlier version?

**Comment by Neoseeker12** [comment]
Tried again with 0.3.4.0, still broken, test.html doesn't give any and log got same error.

**Comment by quisquous** [comment]
I'm still a little suspicious of a version difference here.  cactbot 0.6.5 prints out version numbers and paths in the logs.  Can you copy and paste what it says here?  (Sometimes folks have plugins in different directories or oddly named plugins that get picked up accidentally.  I believe you when you say you're using 0.3.4.0, but maybe that's not the one it's using somehow.)

If that doesn't work, I have another thought, but I wanted to double check the easy thing first.

**Comment by Neoseeker12** [comment]
Recheck the logs and turned out cactbot did not picked up the one in overlayplugin folder but an outdated one in root, remove it and it works.

Thanks for the suggestion.

**Comment by quisquous** [comment]
Glad you got it sorted! Are you the same person that created this issue, or is that a separate person who is having a similar issue?

**Comment by Neoseeker12** [comment]
Different person.

**Comment by meciuPL** [comment]
Issue was solved for me after reinstalling ACT completly.
