### ISSUE TITLE
Add infotext option to stay permanently / go away with callback

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#9]
Instead of info text timing out, it'd be nice to have some persist.

This could get used for the 6 fulms under, or when dps need to float for double stack, or to tell you what color you are during o4s color lasers?

Even better would be an update function, so you could do stuff like: "thunder 3: you are 10.2 yalms away from the boss DANGER"

**Comment by DrLippe** [comment]
popup-text.js:

add to `f`
```js
let resolveText = (condition, callback) => {
  if (condition(gPopupText.data)) {
  callback();
}
```
replace timeout in `alarmText`, `alertText `and `infoText `with:
```js
if ('resolve' in trigger)
  window.setInterval(resolveText.bind(that, trigger.resolve, removeText.bind(that, holder, div), this), 300);
else
  window.setTimeout(removeText.bind(that, holder, div), duration * 1000);
```
trigger.js
```js
{
  id: 'example',
  regex: /hello world/,
  resolve: function(data) { 
    if (data.role != tank) 
      return false;
    return true; 
  },
  infoText: 'hello world',
} 
```

This actually works! But i couldn't figure out how to clear the interval after the condition was met.

**Comment by quisquous** [comment]
Ok, I think this was an idea from the past which never really ended up being that useful of an idea.
