### ISSUE TITLE
Raidboss: Not allowed to load local resource

### ISSUE THREAD

**Issue by Tyecon** [quisquous/cactbot#90]
Raidboss customization is not working, log shows:
```
2018-03-19 3:45:06 PM: Info: Raidboss: BrowserConsole: Not allowed to load local resource: file:///C:/Programs/Advanced%20Combat%20Tracker/OverlayPlugin/cactbot/user/raidboss.js (Source: https://quisquous.github.io/cactbot/ui/raidboss/raidboss.html, Line: 0)
2018-03-19 3:45:06 PM: Info: Raidboss: BrowserConsole: Not allowed to load local resource: file:///C:/Programs/Advanced%20Combat%20Tracker/OverlayPlugin/cactbot/user/raidboss.css (Source: https://quisquous.github.io/cactbot/ui/raidboss/raidboss.html, Line: 0)
```

The URL is set to: file:///C:/Programs/Advanced Combat Tracker/OverlayPlugin/resources/cactbot/raidboss/cactbot-raidboss-pointer.html
Zip unblocking, Firewall, and Admin rights have been checked.
Seems like a security not letting files load issue.

**Comment by Tyecon** [comment]
I don't seem to be the only one with the issue: https://www.reddit.com/r/ACTOverlayPlugin/comments/84sfth/help_using_cactbot/

**Comment by CptDraco** [comment]
Set the URL to "../OverlayPlugin/cactbot/ui/raidboss/raidboss.html"
Also check your directory file structure and verify that it is installed according to the README.md file There is an issue with the newer release that isn't loading the customization files unless they are in the correct directory. #88 
See the picture here for an example. Hope I helped!
https://github.com/quisquous/cactbot/raw/master/screenshots/OverlayPluginRaidbossConfig.png

**Comment by quisquous** [comment]
Out of curiosity, in your cactbot config, what is your custom user config directory set to? Is it `file:///C:/Programs/Advanced%20Combat%20Tracker/OverlayPlugin/cactbot/user/`?

**Comment by Tyecon** [comment]
CptDraco was right with changing "/OverlayPlugin/resources/cactbot/raidboss/cactbot-raidboss-pointer.html" to "../OverlayPlugin/cactbot/ui/raidboss/raidboss.html" fixed it. Thank you.

My user config dir: "..Tracker/OverlayPlugin/cactbot/user/"

**Comment by quisquous** [comment]
Sorry about this.  You should be able to use the pointer file correctly in the next version.
