### ISSUE TITLE
got error says Got a subscription for missing event "onForceReload"!

### ISSUE THREAD

**Issue by patsy158** [quisquous/cactbot#900]
[12/31/2019 10:36:13] Info: LoadAddons: CactbotOverlay.dll: Initialized
[12/31/2019 10:36:14] Error: Got a subscription for missing event "onForceReload"!

**Comment by KattTails** [comment]
If you're using the web hosted version of an overlay like raidboss, eg `https://quisquous.github.io/cactbot/ui/raidboss/raidboss.html` then you can ignore this for now.

When the new version of cactbot is released this error should go away.

**Comment by patsy158** [comment]
thank you so much :3 💯
