### ISSUE TITLE
Cactbot Event Source Page Empty

### ISSUE THREAD

**Issue by aeslin1031** [quisquous/cactbot#902]
Hi, sorry to bother you. I can't figure this out. 
I just updated to the new ngnl plugin and downloaded the latest cactbot version. I was following the readme here **https://github.com/quisquous/cactbot#installing-cactbot**

I added the raidboss module fine. It works. Then I got the section called "Cactbot Customization" and I can't see what I'm supposed to do to get  the same screen as the guide. Mine is blank and just has a field that says "Custom User Config Directory" which is blank and then a checkbox for "reload overlay on file change". I don't have any of the options that the guide shows. I'm not sure if I did something wrong. I can't fine a part of the guide that talks about what to enter here. Can anyone help? 
![2020-01-01 12 06 02](https://user-images.githubusercontent.com/59417362/71643983-1acfe880-2c8f-11ea-86cb-c9fdd35433ea.png)

**Comment by Akurosia** [comment]
Did you use the latest Overlay plugin from ngld

**Comment by ngld** [comment]
The screenshot in the README is from an unreleased version. The [README for Cactbot 0.13.5](https://github.com/quisquous/cactbot/tree/v0.13.5#cactbot-customization) (which you're using) doesn't contain said screenshot.

The next Cactbot version (which will contain the new settings screen) will probably be released within a few days (it requires an OverlayPlugin update which I'll release today).

**Comment by quisquous** [comment]
This should be fixed now.  I have heard of some people still having empty event source pages, but this is because of an incorrect newtonsoft json dll in their act folder (with an error about it in the overlayplugin log).
