### ISSUE TITLE
cactbot Jobs doesn't work after 0.14.0 in Korean server

### ISSUE THREAD

**Issue by Bing-su** [quisquous/cactbot#906]
When using 0.13.5, it worked well.

![jobs 작동안함](https://user-images.githubusercontent.com/37621276/71707067-3e2f9a80-2e2b-11ea-826e-d9ada719cab7.png)

overlay plugin logs
![녹화_2020_01_03_13_09_45_708](https://user-images.githubusercontent.com/37621276/71707085-5ef7f000-2e2b-11ea-94b1-93c1cb8a0758.gif)

Windows 10 64bit
FFXIV KR 5.01 DX11

FFXIV ACT plugin KR 2.1.0.1
Overlay plugin 0.12.1.0

**Comment by KattTails** [comment]
Hi,

Can you check if this .dll works for you? 
[CactbotOverlay.zip](https://github.com/quisquous/cactbot/files/4018142/CactbotOverlay.zip)

**Comment by Bing-su** [comment]
I checked, but it still not worked.

**Comment by KattTails** [comment]
Can you paste your overlayplugin.dll log here? I'm interested in the lines shown here: 
![image](https://user-images.githubusercontent.com/12807478/71710397-ff322280-2df3-11ea-88ba-28ce3c97ffb8.png)

**Comment by Bing-su** [comment]
here
![Cap 2020-01-03 16-32-11-955](https://user-images.githubusercontent.com/37621276/71711954-96c06100-2e46-11ea-8776-48ab531588c8.png)

**Comment by KattTails** [comment]
Yep okay I see what the problem is. The korean offsets are only loaded if you're using the korean ACT plugin which has `Korean` in the file name, as it's given in the releases by Ravahn.

For now, can you rename your `FFXIV_ACT_Plugin.dll` to include `Korean`, eg `FFXIV_ACT_Plugin_Korean.dll`. It should work then and you should see `Version: ko` in the log. Please make sure you delete the dll I linked above and use the official release also.

**Comment by Bing-su** [comment]
Thanks! It works cool.... with another small problem.
![Cap 2020-01-03 16-55-21-254](https://user-images.githubusercontent.com/37621276/71712747-fbc98600-2e49-11ea-8c7b-2da2602a0bf5.png)
![Cap 2020-01-03 16-55-47-992](https://user-images.githubusercontent.com/37621276/71712758-0421c100-2e4a-11ea-845d-d2c414294fe6.png)

anyway this issue is completed. I closed it.

**Comment by KattTails** [comment]
The version check will fail if you've closed and re-opened ACT too many times; githubs servers will temporarily block you. It should disappear after a while.
