### ISSUE TITLE
14.0 Ready Check trigger no longer works.

### ISSUE THREAD

**Issue by djc5166** [quisquous/cactbot#907]
## Description

All other triggers are working, all options for Ready Check are enabled in the new control panel. No notifications or sounds are playing for my/others ready checks.

## Additional information

If available, please include any logs or screenshots depicting the issue you're experiencing.

**Comment by werewolfboy13** [comment]
same issue here

**Comment by quisquous** [comment]
Hmm, that's odd.  The ready check works just fine for me.  What language are you using? Do you have anything set in your `cactbot/user/` file?

**Comment by werewolfboy13** [comment]
english i have it defaulted

**Comment by werewolfboy13** [comment]
had to do that to get it fixed

**Comment by quisquous** [comment]
What do you mean by you had to do that to get it fixed? What did you do that fixed it?

**Comment by djc5166** [comment]
I'm using English,

I've never manually edited any of the files.

**Comment by werewolfboy13** [comment]
it want loading the files just removed the customised one from the older versions.

**Comment by werewolfboy13** [comment]
now its randomly working

**Comment by mooondark** [comment]
It doesn't work in French too

**Comment by quisquous** [comment]
It works fine if you do the ready check.  ;)
