### ISSUE TITLE
O8S Trigger ID's

### ISSUE THREAD

**Issue by KurushiiEX** [quisquous/cactbot#91]
I noticed while browsing around the trigger ID's that are in the O8S.js file that two are using " instead of '. I don't know if it causes any issues. The two are:
"O8S Past's End"
"O8S Future's End"

**Comment by imynwulf** [comment]
When you use the double quote like that, it simply prevents you from having to escape the apostrophe. 

'O8S Past\'s End' would be the same effect, but the other way looks cleaner and achieves the same effect. 

No harm there.

**Comment by quisquous** [comment]
This is all valid JS! No problems here.  :)
