### ISSUE TITLE
Not working after 0.14.0

### ISSUE THREAD

**Issue by Zakjal1** [quisquous/cactbot#917]
After installing version 0.14.0 cactbot doesn't work anymore for me. I have everything updated and having a real hard time trying to figure what is wrong. It doesn't work when I start a boss encounter and also nothing happens when I try to test it at Summerfond.

FFXIV ACT Plugin version is 2.0.4.13
Overlay version is 0.12.1.0

The CactBot eventsource tab is completely blank and the logs window has a line saying:
"Error: Fatal: The loaded Newtonsoft.Json version is older than expected (9.0.0.0  < 12.0.0)! This might cause strange bugs in OverlayPlugin and its addons."

Not sure how to fix that be honest and I don't even know if it has been there before.

**Comment by Akurosia** [comment]
First: This is not directly a cactbot issue and more of an Overlay plugin issue
Second: Make sure that the folder containing the `Advance Combat Tracker.exe` does not include any `Newtonsoft.Json.json`

**Comment by Zakjal1** [comment]
> 
> 
> First: This is not directly a cactbot issue and more of an Overlay plugin issue
> Second: Make sure that the folder containing the `Advance Combat Tracker.exe` does not include any `Newtonsoft.Json.json`

I see, I thought it was cactbot related because my parser is working normally.

There is a similar file in the ACT.exe folder, "Newtonsoft.Json.dll"

**Comment by KattTails** [comment]
That's the file @Akurosia meant. You shouldn't have any plugin files in the `Program Files (x86)\Advanced Combat Tracker\` folder. A clean ACT folder looks like this: 
![image](https://user-images.githubusercontent.com/12807478/71756062-94c9c280-2e85-11ea-9584-a01d84b8bfac.png)

If you remove any files that aren't in this image, and re-install your plugins into subfolders, e.g in folders such as `%APPDATA%\Advanced Combat Tracker\plugins\<pluginname>\` then they will not conflict with each other.

**Comment by Zakjal1** [comment]
> 
> 
> That's the file @Akurosia meant. You shouldn't have any plugin files in the `Program Files (x86)\Advanced Combat Tracker\` folder. A clean ACT folder looks like this:
> ![image](https://user-images.githubusercontent.com/12807478/71756062-94c9c280-2e85-11ea-9584-a01d84b8bfac.png)
> 
> If you remove any files that aren't in this image, and re-install your plugins into subfolders, e.g in folders such as `%APPDATA%\Advanced Combat Tracker\plugins\<pluginname>\` then they will not conflict with each other.

Ah, that was issue behind it. Not sure how this happened, maybe doing the updates from ACT end up creating those files there for some reason. In any case, thank you both, I'm gonna close this now.
