### ISSUE TITLE
Infinite scroll in new config tab

### ISSUE THREAD

**Issue by rgdoabc** [quisquous/cactbot#918]
When I go to the new settings, instead of loading the html file only once, it keeps loading the file again at the bottom, like a page with infinite scroll.

Memory usage skyrocketed and only goes back to normal after closing ACT.

![loop](https://user-images.githubusercontent.com/19763987/71760361-3c9dbb00-2e9b-11ea-9ea9-2f63c5688082.png)

**Comment by Akurosia** [comment]
This happens when FFXIV closes with the latest Cactbot version. Checkout #911 which will fix this issues in future releases.
