### ISSUE TITLE
Triggers in raidboss

### ISSUE THREAD

**Issue by meciuPL** [quisquous/cactbot#92]
Is there a way to disable certain triggers without simply removing them from the directory or do I need to always turn off the module if I don't want them in certain fights? Also is there a way to change the colours of the timeline bars?

**Comment by danakj** [comment]
Yes these are both discussed in the docs.

https://github.com/quisquous/cactbot/blob/master/AdvancedCactbot.md#configuring-ui-modules

"Customizing Appearance" is how to go about changing the bar colors.

"Customizing Behavior" discusses disabling triggers.
