### ISSUE TITLE
About hunt.js file manual edit

### ISSUE THREAD

**Issue by Jaehyuk-Lee** [quisquous/cactbot#920]
## Question

What would you like to ask?
I couldn't find way to make `resources/hunt.js` file with `util/get_hunt_data.py`.
So, I manually edited it.
I mean, I don't know how to make that python program to work. 
```
C:\>python get_hunt_data.py
Traceback (most recent call last):
  File "get_hunt_data.py", line 85, in <module>
    get_from_coinach()
  File "get_hunt_data.py", line 63, in get_from_coinach
    reader = coinach.CoinachReader(verbose=True)
  File "C:\coinach.py", line 46, in __init__
    if not os.path.isfile(os.path.join(self.coinach_path, _COINACH_EXE)):
  File "C:\Program Files\Python38\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

I couldn't fix it. However, I tried half-manual editing it.

I extracted `bnpcnames.exd` with ffxiv_explorer, to English and Korean csv files. and made my own program with C# to make Korean texts into Unicode Encoded strings, hunt.js was written in Unicode Encoded ones.(maybe it doesn't matter though) I manually Ctrl+F and Ctrl+C, Ctrl+V to hunt.js with matching names.
and found it working well with Korean FFXIV.

But... `hunt.js` says
```
// Auto-generated from get_hunt_data.py
// DO NOT EDIT THIS FILE DIRECTLY
```
so... it would be okay to use this "self edited file" my own.
but I don't know if it's okay to upload here that `hunt.js` file. Without editing `get_hunt_data.py` program.

I think `hunt.js` file will be overwritten after re-executing that `get_hunt_data.py`, but hunt data won't be updated until next expansion, expected from previous patch experiences.

**Comment by quisquous** [comment]
I added ko support in the python script.  Let me know if you have any issues or comments on what got automatically added there.

**Comment by Jaehyuk-Lee** [comment]
~~I think my problem is not related to code. I get similar error with latest `gen_hunt_data.py` with python v3.8. Is there any requirements to execute that python code?~~
```
Traceback (most recent call last):
  File "gen_hunt_data.py", line 118, in <module>
    get_from_coinach()
  File "gen_hunt_data.py", line 99, in get_from_coinach
    reader = coinach.CoinachReader()
  File "C:\coinach.py", line 46, in __init__
    if not os.path.isfile(os.path.join(self.coinach_path, _COINACH_EXE)):
  File "C:\Program Files\Python38\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
~~I've cloned repository, and tried `python gen_hunt_data.py` on git-bash and cmd.~~

Oh, I need [`SaintCoinach`](https://github.com/ufx/SaintCoinach/releases) to run this.
I didn't realize that. leaving comment here to notice other contributors who might wondering about this.

But, another error occured..

```
처리되지 않은 예외: System.IO.DirectoryNotFoundException: 디스크에 없는 경로에 액세스하려고 했습니다.
translates: unhandled error: System.IO.DirectoryNotFoundException: tried to access not existing directory
   위치(means location): SaintCoinach.IO.PackCollection..ctor(DirectoryInfo dataDirectory) 파일(means file) C:\projects\saintcoinach\SaintCoinach\IO\PackCollection.cs:줄(means line) 30
   위치: SaintCoinach.ARealmReversed.Update(Boolean detectDataChanges, IProgress`1 progress) 파일 C:\projects\saintcoinach\SaintCoinach\ARealmReversed.cs:줄 361
   위치: SaintCoinach.Cmd.Program.Main(String[] args) 파일 C:\projects\saintcoinach\SaintCoinach.Cmd\Program.cs:줄 50
Traceback (most recent call last):
  File "gen_hunt_data.py", line 118, in <module>
    get_from_coinach()
  File "gen_hunt_data.py", line 101, in get_from_coinach
    update_coinach(monsters, reader)
  File "gen_hunt_data.py", line 77, in update_coinach
    exd = reader.exd('NotoriousMonster', lang=locale)
  File "C:\coinach.py", line 52, in exd
    return self._coinach_cmd('exd', table, lang)
  File "C:\coinach.py", line 78, in _coinach_cmd
    raw_output = subprocess.check_output(
  File "C:\Program Files\Python38\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Program Files\Python38\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'C:\SaintCoinach\SaintCoinach.Cmd.exe "C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn" "lang de" "exd NotoriousMonster"' returned non-zero exit status 3762504530.
```
I have Global server client installed(`C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn`), but why is this happening? Maybe this problem has something relative with #913.
