### ISSUE TITLE
Error while running gen_hunt_data.py

### ISSUE THREAD

**Issue by Jaehyuk-Lee** [quisquous/cactbot#921]
Question

What would you like to ask?

I tried `python gen_hunt_data.py` with `SaintCoinach`([`SaintCoinach.Cmd-master-b693-5bcf049.zip`](https://github.com/ufx/SaintCoinach/releases/tag/Build-693)) extracted on root directory on C drive.

```
처리되지 않은 예외: System.IO.DirectoryNotFoundException: 디스크에 없는 경로에 액세스하려고 했습니다.
translates: unhandled error: System.IO.DirectoryNotFoundException: tried to access not existing directory
   위치(means location): SaintCoinach.IO.PackCollection..ctor(DirectoryInfo dataDirectory) 파일(means file) C:\projects\saintcoinach\SaintCoinach\IO\PackCollection.cs:줄(means line) 30
   위치: SaintCoinach.ARealmReversed.Update(Boolean detectDataChanges, IProgress`1 progress) 파일 C:\projects\saintcoinach\SaintCoinach\ARealmReversed.cs:줄 361
   위치: SaintCoinach.Cmd.Program.Main(String[] args) 파일 C:\projects\saintcoinach\SaintCoinach.Cmd\Program.cs:줄 50
Traceback (most recent call last):
  File "gen_hunt_data.py", line 118, in <module>
    get_from_coinach()
  File "gen_hunt_data.py", line 101, in get_from_coinach
    update_coinach(monsters, reader)
  File "gen_hunt_data.py", line 77, in update_coinach
    exd = reader.exd('NotoriousMonster', lang=locale)
  File "C:\coinach.py", line 52, in exd
    return self._coinach_cmd('exd', table, lang)
  File "C:\coinach.py", line 78, in _coinach_cmd
    raw_output = subprocess.check_output(
  File "C:\Program Files\Python38\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Program Files\Python38\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'C:\SaintCoinach\SaintCoinach.Cmd.exe "C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn" "lang de" "exd NotoriousMonster"' returned non-zero exit status 3762504530.
```
I have Global server client installed(`C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn`), but why is this happening? Maybe this problem has something relative with #913.

This might be an issue with SaintCoinach but I don't know what exactly this error came from. So, I firstly post this here.

**Comment by Akurosia** [comment]
Saint coinach is only accepted in 2 directories by default, `'C:\\SaintCoinach\\'` and `'D:\\SaintCoinach\\'`
These MUST include the one of those must include the `SaintCoinach.Cmd.exe` (with all other needed files for it to run).
If you use a different path, you can add it to the coinach.py _DEFAULT_COINACH_PATHS variable

**Comment by Jaehyuk-Lee** [comment]
It's on `'C:\\SaintCoinach\\'`. I have `SaintCoinach.Cmd.exe` there...

**Comment by Akurosia** [comment]
What happens if you run saint coinach manually? does it work or also throw an error?

**Comment by Jaehyuk-Lee** [comment]
![K-003](https://user-images.githubusercontent.com/4695371/71778752-1d1aa580-2ff5-11ea-9192-f13b025ed940.png)
similar with error logs up there

**Comment by Akurosia** [comment]
in the SainCoinach dir open the \Definitions\game.ver file and change the version number to 2019.12.19.0000.0000

**Comment by Jaehyuk-Lee** [comment]
Oh.... it worked as it was intended to work. Thank you!
But, I didn't customize anything about SaintCoinach, is this my problem or SaintCoinach has it's release file problem?

**Comment by Akurosia** [comment]
afaik its a saind problem, that definitions are not updated to the latest patch.
changing the game.ver string is a trick one of the maintainers showed me a while ago

**Comment by Jaehyuk-Lee** [comment]
Ah, is that 'version' means, FFXIV client version? I got why it has problem. Thanks!

**Comment by Jaehyuk-Lee** [comment]
I've added README to util directory. Thanks for those information @Akurosia !! (It's now on pull request.) #925
