### ISSUE TITLE
Raidboss TTS not working when using OBS to stream/record

### ISSUE THREAD

**Issue by NNowakowski** [quisquous/cactbot#922]
## Description

I'm having issues with using the TTS feature of raidboss whenever I open OBS on the side.
Cactbot will still play triggers with audio files (ex. the Ready Check), however TTS messages for tankbusters, aoes etc. won't be played.
I still see the text alerts on the raidboss overlay, however no TTS is output anymore.
As soon as I close OBS the TTS returns again.

I've got an overlay in OBS using the ngdl OverlayPluginWSServer where I do show the DPS meter, changing that to show the raidboss overlay did not fix the issue however. Turning off the OverlayPluginWSServer and deleting the overlay in OBS did also not fix the issue. So it must be a conflict with OBS in general

## Additional information

OBS:
![image](https://user-images.githubusercontent.com/16933892/71775990-b14f2300-2f89-11ea-908b-a15a921eacfd.png)

Raidboss:
![image](https://user-images.githubusercontent.com/16933892/71775994-c5932000-2f89-11ea-9d77-91b4f28fc860.png)

Cactbot:
![image](https://user-images.githubusercontent.com/16933892/71776007-d5126900-2f89-11ea-8c83-9738f06b6f2e.png)

**Comment by quisquous** [comment]
Sorry for the belated response.  I am really not sure what's going on here.  I have no issues with OBS.  Does other TTS from ACT play while OBS is up? See the questions I asked in #829 and let me know how that works with/without OBS up for you.

**Comment by NNowakowski** [comment]
Custom Triggers do work without OBS open but they also break with OBS opened.
It's likely that one of the recent Windows updates broke this behaviour and it's an ACT problem in general.
Changing the sound API ACT uses to either a plugin one or the other, non-default one, fixes this issue.

**Comment by quisquous** [comment]
Ok, thanks for the test.  This sounds like some issue with Windows and ACT, and there's not really much that cactbot can do about it.
