### ISSUE TITLE
xephero DPS gauges are mis-alligned with 14.0.1

### ISSUE THREAD

**Issue by liaoarden** [quisquous/cactbot#924]
![xephero-dps-gauge-glitch](https://user-images.githubusercontent.com/2417229/71777886-48e94d00-2f5b-11ea-8b59-d2531a3f4aa2.PNG)

The overlay seems to have enough room, but it looks like it thinks it has less space than it does and is overflowing down a section. This is more noticable when there are multiple combatants, though it usually only affects the firs two.

**Comment by quisquous** [comment]
Thanks.  I don't quite know why this started happening, but I've seen this too.  I may just rewrite the xeph dps parser to use grid instead of flexbox as it would help avoid these issues.

**Comment by quisquous** [comment]
I think this is fixed.
