### ISSUE TITLE
(deleted title)

### ISSUE THREAD

**Issue by Kumicoo** [quisquous/cactbot#927]
## Question

What would you like to ask?

**Comment by ngld** [comment]
Oh great, someone complains that something we provide for free and develop in our spare time isn't perfect...

Regarding the actual problem: I'm going to guess that you see an error in your overlay log that complains about `Newtonsoft.Json` being outdated. If you do see that error, then you broke ACT yourself by installing plugins incorrectly. Use the `View Loaded Assemblies` button in ACT to find the old version and remove it.

**Comment by quisquous** [comment]
https://github.com/quisquous/cactbot/blob/master/CODE_OF_CONDUCT.md#our-standards

If you have a question, please ask it without being insulting or ableist.
