### ISSUE TITLE
Cactbot Raidboss

### ISSUE THREAD

**Issue by Exobrem** [quisquous/cactbot#93]
Edit: I'm an idiot. Issue solved with "lock overlay" option. I apologize for wasting your time.

**Comment by quisquous** [comment]
Excellent! Glad you got it sorted.

I'm sorry for the confusion.  You're not the first person at all who's been confused by that.  I wonder sometimes if I need some on screen ui that's like "lock this overlay to remove this temporary text" kind of banner going on too.

**Comment by danakj** [comment]
That's a good idea.
