### ISSUE TITLE
Cacbot Pluggings/Configuration Screen Errors

### ISSUE THREAD

**Issue by DeusMundum** [quisquous/cactbot#931]
Since the 14.0 update my Raidboss and oopsy plugs have stopped working and the new configuration window is completely blank. Likely that I've not followed something correctly but please help

**Comment by ngld** [comment]
Check your overlay log, if it contains an error mentioning an outdated `Newtonsoft.Json` version, [follow these instructions](https://gist.github.com/ngld/e2217563bbbe1750c0917217f136687d#overlayplugin-complains-that-newtonsoftjson-is-outdated).

**Comment by DeusMundum** [comment]
Thank you, that fixed the issue
