### ISSUE TITLE
Raidboss ucob translation issue

### ISSUE THREAD

**Issue by Feanarus** [quisquous/cactbot#941]
## Description

for the "UCU Nael Quote 12, 13 and 14 the german TTS-line mismatch with the TEXT-line
and in UCU Nael Quote 14 "...Pfadt/," without "t" -> "...Pfad/,"

## Additional information
![ucob](https://user-images.githubusercontent.com/38397799/72109834-03e86080-3337-11ea-9023-b092c5539421.PNG)

**Comment by Akurosia** [comment]
just made a PR #945 for this
