### ISSUE TITLE
Not sure if this is an issue with Cactbot?

### ISSUE THREAD

**Issue by FromTheGrayve** [quisquous/cactbot#960]
Error: Fatal: The loaded Newtonsoft.Json version is older than expected (11.0.0.0  < 12.0.0)

This shows up in the OverlayPlugin log.

**Comment by quisquous** [comment]
https://gist.github.com/ngld/e2217563bbbe1750c0917217f136687d#overlayplugin-complains-that-newtonsoftjson-is-outdated

**Comment by FromTheGrayve** [comment]
Thank you! Sorry I didn't realize there was a FAQ and wasted your time! Bookmarking that now!
