### ISSUE TITLE
New update not working

### ISSUE THREAD

**Issue by Sacuura** [quisquous/cactbot#963]
![cactbot issue](https://user-images.githubusercontent.com/59811833/72229813-9a529700-356e-11ea-805e-cabb765d164e.PNG)

## Description

Description of the issue you're seeing.

## Additional information

If available, please include any logs or screenshots depicting the issue you're experiencing.

**Comment by ngld** [comment]
The error message switched the numbers around. You have OverlayPlugin 0.12.2 but need 0.13.0. Go to Plugins > OverlayPlugin.dll > General and click `Check For Updates`.

**Comment by quisquous** [comment]
Added a better note to the release page about this too.

**Comment by quisquous** [comment]
If you're still having issues, please let me know.
