### ISSUE TITLE
15.0 Raidboss TEA limit cut number callouts no longer working.

### ISSUE THREAD

**Issue by djc5166** [quisquous/cactbot#964]
## Description

15.0 Raidboss TEA limit cut number callouts no longer working.

No sound effects or popup triggers from raidboss for LC numbers.

Normal timelines and callouts still working as normal.

## Additional information

Rolled back to last version, working again.

**Comment by quisquous** [comment]
Thanks for the report.  This is very strange, as nothing changed with respect to limit cut markers since the last version.  Let me run this through the emulator and see if I can see anything locally.

**Comment by djc5166** [comment]
I tried also taking the .jss/.txt from 14.1 into 15.0 and it has the same issue, but I don't think those files even changed with this release?

**Comment by ngld** [comment]
Can you check if you see an error like this in your overlay log?
`Error: LoadAddons: CactbotOverlay.dll: System.FormatException: String was not recognized as a valid DateTime.`

**Comment by quisquous** [comment]
I ran my last parse through the emulator and everything seemed fine, so it's definitely not something with the triggers file itself.

The other thing I changed that might in this realm is capitalizing the player name.  I wonder if something is awry there.

What's your in-game name? Can you import your Network log into ACT, right click on the encounter, go to view logs, and search for `1B.*your name` (or whatever your name is) and click search as regex, and let me know what lines pop up?

**Comment by djc5166** [comment]
> Can you check if you see an error like this in your overlay log?
> `Error: LoadAddons: CactbotOverlay.dll: System.FormatException: String was not recognized as a valid DateTime.`

I didn't see any errors on loading, unless they would pop up while running?

**Comment by ngld** [comment]
Unlikely. Looks like this is a different error. You're not seeing any erros in your overlay log, right?

@quisquous Apparently there's an issue where date strings get written like this: `2020-01-13T05:10:45.2718174+01:00` and `DateTime.Parse` then fails to parse them. Removing the second parameter seems to fix the issue.
Sorry for going off-topic. This error just popped up in a different discussion and I wanted to provide some more context for my question.

**Comment by djc5166** [comment]
> 1B.*your name
I don't see any errors, searching for 1B.anything returns 0 results.

My name does have hyphens in it. It's Sanic Gotta-go-fast

**Comment by quisquous** [comment]
Yeah, just so I can verify what I suspect is happening here, can you look in your log and find a line that has ` 1B:` and your name in it, and a line that has ` 15:` and your name in it? There should be some of each for an encounter that gets to the first limit cut.

**Comment by djc5166** [comment]
> Yeah, just so I can verify what I suspect is happening here, can you look in your log and find a line that has ` 1B:` (that's a space and then 1B:) and your name in it, and a line that has ` 15:` and your name in it? There should be some of each for an encounter that gets to the first limit cut.

[21:17:48.785] 1B:106E392C:Sanic Gotta-go-fast:0000:8CD2:0053:0000:0000:0000:

[21:18:07.410] 15:400130CF:Cruise Chaser:4834:Alpha Sword:106E392C:Sanic Gotta-go-fast:EC710005:3DC30000:580F:4720000:580F:2B70000:1E:0:1C:48348000:0:0:0:0:0:0:122405:148573:6900:10000:0:1000:84.30558:108.6819:0:-2.636837:8329440:8329440:10000:10000:0:1000:93.97286:116.8227:0:-2.171814:00009CD7

I think these are what you are looking for?

**Comment by quisquous** [comment]
One more thing.  With the new version of cactbot, can you add `https://quisquous.github.io/cactbot/ui/test/test.html` as an overlay, and tell me what the capitalization of your name is?

**Comment by quisquous** [comment]
If the ` 14:` and the test page have your name capitalized as `Sanic Gotta-Go-Fast`, then I think the fix is going to be to use the new version of the ffxiv plugin 2.0.4.16 ([link to beta](https://discordapp.com/channels/551474815727304704/551476805148737546/666038800207577128)) which should capitalize the other lines.

**Comment by djc5166** [comment]
> Two more things. With the new version of cactbot, can you add `https://quisquous.github.io/cactbot/ui/test/test.html` as an overlay, and tell me what the capitalization of your name is?
> 
> Can you also look up a line that has ` 14:` in it from your log as well?
> 
> Sorry for all the questions. I've been trying to debug some hyphen issues with other players and I just want to make sure I understand everything.

[21:17:17.605] 14:1D90:Makar Helmaroc starts using Esuna on Sanic Gotta-Go-Fast.

I will check the overlay when I get back to my machine.

**Comment by djc5166** [comment]
Fixed with new version and beta parsing plugin.

**Comment by quisquous** [comment]
Sweet, glad it's sorted.  Sorry for the hassle.

I'm honestly surprised that you haven't seen more missing triggers, but maybe you aren't tanking or healing, which is where a lot of the `14` lines that are capitalized differently come from.

**Comment by djc5166** [comment]
> Sweet, glad it's sorted. Sorry for the hassle.
> 
> I'm honestly surprised that you haven't seen more missing triggers, but maybe you aren't tanking or healing, which is where a lot of the `14` lines that are capitalized differently come from.

I am a tank :D There might have been some other things missing, but LC callouts were the most apparent.
