### ISSUE TITLE
wierd black box in upper left corner?

### ISSUE THREAD

**Issue by geowolf18** [quisquous/cactbot#965]
when i start ACT theres a wierd black box in the upper left corner of my primary monitor

**Comment by quisquous** [comment]
Is this an overlay? Do you have a screenshot?

**Comment by geowolf18** [comment]
![wierd rectangle](https://user-images.githubusercontent.com/45958074/72316986-db79a280-3665-11ea-9305-8a2700e92fd1.PNG)
here is what it looks like the black rectangle in the left corner never showed up till today

**Comment by ShadyWhite** [comment]
![image](https://user-images.githubusercontent.com/44015352/72317335-e79c4900-36d3-11ea-9fbb-a0906afc2004.png)
![image](https://user-images.githubusercontent.com/44015352/72317356-f71b9200-36d3-11ea-88d8-8feff4af5702.png)
Turn off this.

**Comment by geowolf18** [comment]
thanks
