### ISSUE TITLE
Eureka plugin

### ISSUE THREAD

**Issue by Wildman48** [quisquous/cactbot#969]
## Description

Been using the Eureka plugin for months now and noticed today that when a NM pops I don't get the sound or notification showing on the map until i get really close to the area. Maybe around 100 yalms it then pops up and sounds off.
## Additional information
This is the latest version of cactbot and overlay plugin. I'm noticing this in Hydatos. I haven't been in this zone in a while but I can check other zones and report back if it's the same issue. I just know it would always make a sound and notify me on the map no matter where i was in the zone.

If available, please include any logs or screenshots depicting the issue you're experiencing.

**Comment by ngld** [comment]
Patch 5.18 broke that part of the Eureka overlay. [A fix is being worked on](https://github.com/quisquous/cactbot/pull/903)

**Comment by Wildman48** [comment]
understood, thank you.
