### ISSUE TITLE
E4S Crumbling Down Bug

### ISSUE THREAD

**Issue by kalar33** [quisquous/cactbot#976]
Yesturday while doing E4S with my static, three of us that use Cactbot were having the same problem. If Titan started with **Earthen Wheels** (stand on sides), then during the Crumbling Down phase there would be no pop up or TTS telling you to go East or West.
But if Titan started with **Earthen Gauntlets** (Stand in front), then during the Crumbling Down phase
there would be a Pop up and TTS telling you East or West.

**Comment by djc5166** [comment]
Also have seen this with the latest version.
