### ISSUE TITLE
o8s hyperdrive and ultimate embrace trigger

### ISSUE THREAD

**Issue by Iilease** [quisquous/cactbot#98]
Is missing the colon between the spell id and kefka. 

`regex: / 14:2910:Kefka starts using Ultimate Embrace on (\y{Name})/,`

`regex: / 14:(?:28E8|2912):Kefka starts using Hyperdrive on (\y{Name})/,`

**Comment by jerrybotticelli** [comment]
Also, is there suppose to be a space at the beginning? `/ 14:`

**Comment by Iilease** [comment]
Yes, the only change needed was the colon, tested it in o8s last night and it worked perfectly.

**Comment by quisquous** [comment]
Whoops.  Thanks for this!  And yeah, there's a space at the beginning before the log type id.
