### ISSUE TITLE
Cactbot Event Source doesn't load (blank), and cactbot doesn't work

### ISSUE THREAD

**Issue by SaltedyLevity** [quisquous/cactbot#980]
I've been using the raidboss (timeline) portion of cactbot to appear on my stream since like the .10 version with (mostly) no issues. I think this started happening either with the current version (.15.2) or one or two previous where it's no longer working. I _think_ it was when the overhaul/addition to managing customized settings was added into the ACT interface.

I'm on FFXIV plugin 2.0.4.13 and ngld Overlay plugin 13.2.0. Net framework looks to be version 4.8.

The "Cactbot Event Source" tab of the OverlayPlugin.dll doesn't load, it just comes up blank:
![image](https://user-images.githubusercontent.com/54490191/72856596-00cf6780-3c89-11ea-973d-903fe487cd6d.png)

Additionally when I try to add new overlays and select any of the cactbot ones, they do appear, but they don't interact with the game (e.g. load raidboss, go to summerford, /bow, /countdown, nothing) - both when pre-selecting or when trying to add a custom one, it's the same.

I DID previously have minor customizations in a \user file to turn off all the alerts and pop-ups etc. as I only wanted the visual timeline for vods - so in case that was the issue I removed my old version of cactbot entirely, did a fresh download/unblock/extract/install with no user file, and it's the same issue.

Not sure what I'm missing? Any help is appreciated!

**Comment by quisquous** [comment]
https://gist.github.com/ngld/e2217563bbbe1750c0917217f136687d#overlayplugin-complains-that-newtonsoftjson-is-outdated

**Comment by SaltedyLevity** [comment]
Thank you! Wouldn't have even thought to search for that.

**Comment by quisquous** [comment]
Glad you got it sorted! :+1:
