### ISSUE TITLE
Trick Attack Icon dont show appropriately

### ISSUE THREAD

**Issue by rsigim** [quisquous/cactbot#983]
[image](https://user-images.githubusercontent.com/22231296/72918706-e64acc00-3d24-11ea-82fd-f48a2cd77a9f.png)

I checked the job.js, the path of the icon and the icon himself is ok, yet I cant see whats wrong why is no showing the icon

**Comment by quisquous** [comment]
This is because you copied and pasted from `cactbot/user/jobs-example.js` into your `cactbot/user/jobs.js` file.  There's a `Options.PerBuffOptions = {` section that turns trick attack red that you likely have copied and pasted.

**Comment by quisquous** [comment]
Let me know if you are still having problems getting this working.

**Comment by rsigim** [comment]
Sorry for late feedback.

And yes, the mentioned option was the problem. Thanks for your support!
