### ISSUE TITLE
Cactbot suddenly stopped working

### ISSUE THREAD

**Issue by roldion** [quisquous/cactbot#988]
Just wondering if this is the correct OverlayPlugin to use?

Assembly Info:
FileName: C:\Temp\FF14 Addins\OverlayPlugins\OverlayPlugin.dll
OriginalFilename: OverlayPlugin.dll
FileVersion: 0.3.4.0
ProductVersion: 0.3.4.0
FileDescription: OverlayPlugin
ProductName: OverlayPlugin
LegalCopyright: Copyright © RainbowMage 2015, Kuriyama hibiya 2016
Comments: Overlay plugin for Advanced Combat Tracker

When trying to load cactbot-0.15.2.zip, it comes up with the error below:

![CactBotError](https://user-images.githubusercontent.com/25762253/73054468-7e7fb700-3ec5-11ea-8179-bd438547d6fa.jpg)

**Comment by Akurosia** [comment]
You have to use nglds fork of the overlay plugin: https://github.com/ngld/OverlayPlugin/releases

**Comment by roldion** [comment]
Thank you very much :) got it fixed now after deleting the old and using this

Sent from Yahoo Mail on Android 
 
  On Fri, Jan 24, 2020 at 4:24 PM, Akurosia Kamo<notifications@github.com> wrote:   
You have to use nglds fork of the overlay plugin: https://github.com/ngld/OverlayPlugin/releases
