### ISSUE TITLE
Cactbot not running

### ISSUE THREAD

**Issue by phoenixi0n** [quisquous/cactbot#99]
I'm really sorry about this, I'm quite new to this cactbot thing. I've been reading around but I seem to not be able to use cactbot since it keeps giving me this error message

![image](https://user-images.githubusercontent.com/36949651/38456066-930e95d6-3ac3-11e8-9515-e850c173ebcb.png)

![image](https://user-images.githubusercontent.com/36949651/38456090-c57c4ae0-3ac3-11e8-9469-616ec837237d.png)

I tried everything:
1. Running it as administrator
2. Updating all the files based on : https://www.reddit.com/r/ACTOverlayPlugin/comments/3b7ogz/instructionslatest_download/?st=j4pvvxeo&sh=c37c574a
3. Copying it from C to another drive and use the same file
4. Re-installing ACT

All kinds of effort still failing me to run cactbot. Please help

**Comment by quisquous** [comment]
It looks like you're trying to load cactbot twice here.  The second screenshot is correct.  The first screenshot has the error.  You shouldn't try to load CactbotOverlay.dll directly from ACT.  Remove the CactbotOverlay.dll from that first screenshot.

https://github.com/quisquous/cactbot#potential-errors-and-workarounds has some notes about the "This assembly does not have a class that implements ACT's plugin interface" error.

**Comment by phoenixi0n** [comment]
alright, so i've removed the one from the plugin page (as in the first screenshot) and after i followed this guide:https://github.com/quisquous/cactbot#adding-overlay-modules, tested it on raid and dummy. Everything is working. Thanks!!
