### ISSUE TITLE
Error when loading

### ISSUE THREAD

**Issue by Smuggus** [quisquous/cactbot#991]
## Description
I get this error
System.Exception: Cactbot requires OverlayPlugin 0.13.0, found 0.12.2.0
   at Cactbot.PluginLoader.InitPlugin(TabPage pluginScreenSpace, Label pluginStatusText)
   at Advanced_Combat_Tracker.FormActMain.pluginPanelEnabledChecked(Object sender, EventArgs e)
Cactbot not working at all :C

## Additional information

If available, please include any logs or screenshots depicting the issue you're experiencing.

**Comment by Akurosia** [comment]
The error does exactly tell you whats wrong.
You have to update your Overlay plugin to at least version 0.13.0 (you still have 0.12.2.0 installed)
Here is a link to the latest overlay plugin: https://github.com/ngld/OverlayPlugin/releases/latest

**Comment by Smuggus** [comment]
I updated the plug in prior to updating cactbot. I tried to manually update it but it still doesnt work. The auto update said it was an incomplete installation so I removed it from plug ins and did it manually, I wont lie I'm not 100% sure what version it was but I clicked a link to update to the latest version. Perhaps I need to remove the plug in completely and reinstall it. Thank you for the tip!

**Comment by Smuggus** [comment]
I uninstalled the plugin and did a fresh install for the ffxiv overlay plugin, and reinstalled cactbot to the newest version. Now when i attempt to activate raidboss i get this error:

 Info: CACTBOT: BrowserConsole: Uncaught (in promise) TypeError: Cannot read property 'detail' of null (Source: file:///C:/Users/Me/cactbot-0.15.2/cactbot/resources/user_config.js, Line: 35)

I dont know what this means :C

**Comment by ngld** [comment]
Do you see any other errors (or messages) in the overlay log?

**Comment by Smuggus** [comment]
That's all I saw. I attempted to load the overlay a few times and that's all that came up

**Comment by ngld** [comment]
You can make the log display larger, or scroll or use `Ctrl+A` to select the whole log and copy&paste it. At the very least you should see two more lines from OverlayPlugin which always show up.

**Comment by Smuggus** [comment]
OK, so. I fixed it. Im not sure why but i just deleted everything, ACT, parsing plug in, cactbot, everything. I reinstalled it all, made sure it was up to date, reloaded it and it works now. What went wrong? I have no idea, but i think something that was installed had something messed up, and removing it all and starting from scratch fixed it. Thank you for all the help!

**Comment by quisquous** [comment]
Glad you got it sorted!
